libsdl-org/SDL

- src/video/wayland/SDL_waylanddatamanager.c
- src/video/wayland/SDL_waylanddatamanager.h
- src/video/wayland/SDL_waylandevents.c
- In `src/video/wayland/SDL_waylanddatamanager.c`, Log `data_offer_receive` and `primary_selection_offer_receive`,
- In `src/video/wayland/SDL_waylanddatamanager.h`, Split FILE vs TEXT offers : booleans `has_mime_text`  and `has_mime_file`,
- In `src/video/wayland/SDL_waylandevents.c`, Log `data_device`, `data_offer`, `primary_selection_device` and `primary_selection_offer` events, Record FILE vs TEXT offers during `data_device_handle_enter` for use in `data_device_handle_drop`, Handle `text/plain;charset=utf-8` data offer in `data_device_handle_drop`.
This is the best I can propose at this point :
- On the one hand, it works for Exult Studio dragging and dropping shapes into Exult, and it works when the Drag and Drop source is any tool of the LibreOffice family into `testdropfile`. I …
> Support SDL_EVENT_DROP_TEXT in Wayland

- src/video/kmsdrm/SDL_kmsdrmvideo.c
The window couldn't be created on a secondary screen with KMSDRM backend. Its always was repositioned at 0,0.
The patch moves window too the top-leftt corner of a proper display it belongs to
The window is always created on the first screen in KMSDRM backend
> Fixed secondary screens on KMSDRM

- src/video/vita/SDL_vitatouch.c
~~NOTE: I am in process of local testing of the thing, I will turn this into ready-to-merge PR once I confirm the thing works on my end perfectly.~~ I found another bug, going to report it separately, This one let's just merge.
- Begining of device ID with 0 violates the SDL's specification that means the 0 is an error, invalid, failure, etc. But on Vita here it's an actual device...
- Replacing 0 and 1 with 1 and 2 to resolve this violation.
#9830
> Fixed the incorrect touch device IDs on the Vita

- test/testcamera.c
Add performance logging to testcamera.
- Log the number of times SDL_AppIterate() is called per minute
- Log the average FPS based on SDL_AcquireCameraFrame() calls per minute
- Log camera specifications upon approval, including resolution, FPS, and pixel format
- Adjust default framerate to 30 FPS
> testcamera: Add logging for camera FPS

- include/SDL3/SDL_video.h
- src/test/SDL_test_common.c
- src/video/SDL_video.c
This is undocumented since the individual flags are separate window creation properties, but it's useful to have a shared definition for this, which is used internally and for migrating code from SDL2.
> Added SDL_PROP_WINDOW_CREATE_FLAGS_NUMBER

- src/video/x11/SDL_x11mouse.c
Cursor visibility in the SDL input layer only reflects whether ShowCursor/HideCursor was called. In the case of relative mode, the cursor can be hidden, but the SDL_Mouse visibility flag will be true.
Track cursor visibility separately in the X11 driver. Fixes the cursor becoming visible when using the warping relative mode with XWayland.
(cherry picked from commit b0713a7d3047ca121c4257337da48cafbcbc44d4)
Fixes #10550
> x11: Track cursor visibility internally

- src/file/SDL_iostream.c
This is the SDL3 side of a PR optimizing the stdio implementation of `SDL_SeekIO(..., 0, SDL_IO_SEEK_CUR)`.
I did not change any implementations other than stdio because I am confident that `fseek(fp, 0, SEEK_CUR)` is a no-op, and I'm not certain about the other implementations. It's also possible that the underlying API is better optimized on other platforms.
Please feel free to alter my branch, it exists only for the sake of this PR.
#10556 (fixes SDL3 side only)
> SDL_iostream.c: stdio_seek - skip API call for SEEK_CUR with 0 offset

- src/main/psp/SDL_psp_main.c
At the moment closing an SDL2 based application on the Playstation Portable using the home button will forcefully exit. This makes the application unable to make sure that everything exited out fine.
With this change, the user can handle the home button close in a way that makes sense for them. They will be forced to do so, though, as otherwise the application will freeze when trying to exit. I don't see this as different from how SDL2 based applications which do not handle the close button being pressed on PC not exiting, though. I think this is acceptable.
> PSP: Throw SDL_Quit event upon exit

- src/audio/pipewire/SDL_pipewire.c
- src/camera/pipewire/SDL_camera_pipewire.c
g++-13 complains:
```
SDL_pipewire.c:129:42: warning: assignment to "struct pw_main_loop *
(*)(struct pw_main_loop *)" from incompatible pointer type "struct
pw_main_loop * (*)(const struct spa_dict *)"
[-Wincompatible-pointer-types]
129 | #define SDL_PIPEWIRE_SYM(x) PIPEWIRE_##x = x
SDL_pipewire.c:148:5: note: in expansion of macro "SDL_PIPEWIRE_SYM"
148 |     SDL_PIPEWIRE_SYM(pw_main_loop_new);
```
g++-14 complains:
```
SDL_pipewire.c:129:42: error: assignment to "struct pw_main_loop *
(*)(const struct pw_main_loop *)" from incompatible pointer type
"struct pw_main_loop * (*)(const struct spa_dict *)"
[-Wincompatible-pointer-types]
```
> Resolve g++-14 build failures in pipewire code

- src/dynapi/SDL_dynapi_procs.h
- src/render/vulkan/SDL_render_vulkan.c
- src/stdlib/SDL_stdlib.c
- src/video/SDL_RLEaccel_c.h
- src/video/SDL_video_unsupported.c
This fixes warnings, shown when making `SDL_bool` a typedef of `int`.
```patch
--- a/include/SDL3/SDL_stdinc.h
+++ b/include/SDL3/SDL_stdinc.h
@@ -210,7 +210,8 @@ void *alloca(size_t);
* \sa SDL_TRUE
* \sa SDL_FALSE
*/
-typedef int SDL_bool;
+#include <stdbool.h>
+typedef bool SDL_bool;
/**
* A signed 8-bit integer type.
* 
```
It also makes all `SDL_is` return a `SDL_bool`.
> Fix warnings shown when making SDL_bool a typedef of bool

- CMakeLists.txt
This results in a 20kiB smaller file for Linux binaries, built in release mode, and 200kiB for MinGW binaries. (both unstripped)
> cmake: only build uclibc when building without external libc

- Android.mk
- CMakeLists.txt
- VisualC-GDK/SDL/SDL.vcxproj
- VisualC-WinRT/SDL-UWP.vcxproj
- VisualC/SDL/SDL.vcxproj
- VisualC/tests/testautomation/testautomation.vcxproj
- Xcode/SDL/SDL.xcodeproj/project.pbxproj
- cmake/test/CMakeLists.txt
- src/SDL_internal.h
- src/dynapi/SDL_dynapi.c
- test/CMakeLists.txt
- test/testautomation_intrinsics.c
- test/testautomation_main.c
- test/testnative.h
When testing the binaries in the release workflow, then we don't want to add the `include` directory of this repo to the include search path. (we want to test the headsers of the binary package, not the headers in the source tree)
A few tests include `SDL_build_config.h` as a way to conditionally enable/disable tests.
This pr also fixes a python-releated issue in the release workflow.
> Include SDL_build_config.h without a 'build_config/' prefix

- src/video/windows/SDL_windowswindow.c
Currently on Xbox GDK, windows do not have input focus by default. So unless you set the `SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS` hint or do something else to explicitly focus the window (e.g. press the Xbox guide button, then close the system menu), all input events will be ignored.
I went back to the SDL 2.24.x branch and found it has the same behavior, so I don't believe this is a regression. I think we just happened to get lucky because `testcontroller` sets the aforementioned hint, as does FNA and presumably any other engines/games that have shipped with SDL GDK.
This change brings Xbox in line with the Windows implementation directly below by explicitly setting the focus.
> GDK: Xbox should have input focus by default

- include/SDL3/SDL_init.h
This fixes some recently added trailing doc comments in `SDL_init.h` to use the correct format for trailing doc comments.
> Fix trailing doc comments in SDL_init.h

- include/SDL3/SDL_hints.h
This PR removes SDL_PEN hints that are no longer used.
> Remove SDL_PEN hints that are no longer used

- src/gpu/vulkan/SDL_gpu_vulkan.c
Partially addresses #10629. That one reports D3D12 leaks; turns out there is one in Vulkan as well.
cc @thatcosmonaut
> gpu_vulkan: fix memory leak in VULKAN_CreateDevice

- include/SDL3/SDL_test_common.h
- src/test/SDL_test_common.c
- test/testgpu_spinning_cube.c
This adds a `--gpu <gpu-driver>` to all tests using SDL_test.
Fixes #10626
> SDL_test: add --gpu option

- src/gpu/vulkan/SDL_gpu_vulkan.c
This warning showed up with cl 19.29.30154 (from Visual Studio 2019)
@thatcosmonaut
> Fix C4090: 'function': different 'const' qualifiers

- src/gpu/metal/SDL_gpu_metal.m
This PR fixes uninitialized memory access in `METAL_BeginRenderPass` when using SDL_gpu with the Metal backend.
I tried to integrate SDL_gpu into my project but even the [SDL_gpu_examples](https://github.com/TheSpydog/SDL_gpu_examples) files were always crashing. I tracked it down to the uninitilaized memory access in `METAL_BeginRenderPass` `texture->msaaHandle` with the help of clang's AddressSanitizer. With ASan `msaaHandle` will be filled with `0xbebebebe`.
https://github.com/libsdl-org/SDL/blob/5d5a685a8004fe8ceaf3dc5b3e9b431b32603e4b/src/gpu/metal/SDL_gpu_metal.m#L2083
This memory is allocated in `METAL_ClaimWindow` with `SDL_malloc` and not all fields are initialized.
https://github.com/libsdl-org/SDL/blob/5d5a685a8004fe8ceaf3dc5b3e9b431b32603e4b/src/gpu/metal/SDL_gpu_metal.m#L3410 …
> GPU Metal: Fix uninitialized memory access crash in `BeginRenderPass`

- src/SDL_log.c
This partially reverts 125ce7137987ec91b931b4fb97d9c3c7af88c377
See #10523
> SDL_Log: don't rely on printf to forward stderr to the debug stream

- include/SDL3/SDL_gpu.h
When compiling following code:
```c
#include <SDL3/SDL_gpu.h>
int main(void) {return 0;}
```
there are a bunch of "unknown type" errors:
```c
/path/to/SDL-git/include/SDL3/SDL_gpu.h:608:5: error: unknown type name ‘SDL_PropertiesID’
/path/to/SDL-git/include/SDL3/SDL_gpu.h:794:5: error: unknown type name ‘SDL_FColor’
/path/to/SDL-git/include/SDL3/SDL_gpu.h:1627:5: error: unknown type name ‘SDL_Rect’
/path/to/SDL-git/include/SDL3/SDL_gpu.h:2267:5: error: unknown type name ‘SDL_FlipMode’
/path/to/SDL-git/include/SDL3/SDL_gpu.h:2289:5: error: unknown type name ‘SDL_Window’
```
This commit adds the headers for these types to `SDL_gpu.h`.
> Added includes to SDL_gpu.h

- include/SDL3/SDL_test_assert.h
- include/SDL3/SDL_test_font.h
- include/SDL3/SDL_test_fuzzer.h
- include/SDL3/SDL_test_harness.h
- include/SDL3/SDL_test_log.h
- include/SDL3/SDL_test_md5.h
Some `SDL_test_*.h` files were missing some headers:
```c
/path/to/SDL-git/include/SDL3/SDL_test_assert.h:55:42: error: unknown type name ‘SDL_PRINTF_FORMAT_STRING’
/path/to/SDL-git/include/SDL3/SDL_test_font.h:55:1: error: unknown type name ‘SDL_bool’
/path/to/SDL-git/include/SDL3/SDL_test_font.h:55:32: error: unknown type name ‘SDL_Renderer’
/path/to/SDL-git/include/SDL3/SDL_test_font.h:76:5: error: unknown type name ‘SDL_FRect’
/path/to/SDL-git/include/SDL3/SDL_test_font.h:136:89: error: unknown type name ‘size_t’
/path/to/SDL-git/include/SDL3/SDL_test_fuzzer.h:60:25: error: unknown type name ‘Uint64’
/path/to/SDL-git/include/SDL3/SDL_test_harness.h:124:90: error: unknown type name ‘Uint64’
/path/to/SDL-git/include/SDL3/SDL_test_log.h:50:18: error: unknown type name …
```
> Added headers to some SDL_test_*.h files

- include/SDL3/SDL_test_memory.h
```c
/path/to/SDL-git/include/SDL3/SDL_test_memory.h:52:33: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
52 | void SDLTest_RandFillAllocations();
|                                 ^
|                                  void
```
> SDL_test_memory.h: Added void to function prototype

- include/SDL3/SDL_assert.h
This fixes multiple definitions of SDL_assert* in SDL_assert.h when SDL_WIKI_DOCUMENTATION_SECTION is defined.
(This is currently required for my SDL header parser/binding generator to work)
> Fix multiple definitions of SDL_assert* when SDL_WIKI_DOCUMENTATION_SECTION is defined

- src/render/sdlgpu/SDL_shaders_gpu.c
The change is to fix a typo which causes us to select the wrong shader variant.
> Fix typo where the wrong shader were being selected for metal in the sdl_render_gpu backend

- src/gpu/SDL_sysgpu.h
These functions had special cases for a few BC formats, but all block-compressed formats should need the same logic. Furthermore they weren't handling the sRGB variants of those formats.
cc @thatcosmonaut
> GPU: Fix and generalize BytesPerRow() and BytesPerImage()

- src/gpu/d3d12/SDL_gpu_d3d12.c
While trying out SDL GPU I discovered that resizing the window would not resize the swap chain.
After digging into the code I found that the implementation for d3d12 was resizing the swap chain to the old size instead of the new window size.
Simple enough fix, just pass the new window size when resizing the swap chain.
> GPU: Fix swap chain resize for d3d12

- src/test/SDL_test_fuzzer.c
- test/testautomation_audio.c
It's not an error if we don't, but we'll get 0 bytes out of the stream if we don't flush, which the audio_resampleLoss test treats as a failure.
Fixes https://github.com/libsdl-org/SDL/issues/10613
> Make sure we put more than RESAMPLER_MAX_PADDING_FRAMES into an audio stream

- src/gpu/metal/SDL_gpu_metal.m
Using the `@()` syntax to construct an `NSString` assumes the parenthesized pointer is null-terminated, but the Metal shader source included in `render/sdlgpu/shaders/metal.h` is not null-terminated.
Quoting the clang documentation on Objective-C literals:
> When the type of the parenthesized expression is `(char *)` or `(const char *)`, the result of the boxed expression is a pointer to an `NSString` object containing equivalent character data, which is assumed to be `\0`-terminated and UTF-8 encoded.
Because the `@()` syntax assumes null-termination, it may read garbage data after the shader source (up to the next null byte), which can then cause the Metal shader compiler to fail. To prevent this, instead of using the `@()` boxing syntax, we explicitly construct an `NSString` using the …
> GPU: Compile Metal shader source from NSString

- include/SDL3/SDL_gpu.h
- src/gpu/SDL_gpu.c
- src/gpu/d3d11/SDL_gpu_d3d11.c
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
- src/render/sdlgpu/SDL_render_gpu.c
- test/testgpu_spinning_cube.c
Resolves https://github.com/libsdl-org/SDL/issues/10673. I also lopped off the `_BIT` suffix since it's a Vulkan-ism that doesn't match the other SDL flag enums.
> Change GPU flag enums to defines

- include/SDL3/SDL_gpu.h
Removed the ampersands and rephrased the various Flags doc comments, and fixed a minor typo in the TextureFormat comment. Hopefully this is more in line with the SDL3 convention now. :)
> GPU: Minor documentation cleanup

- src/gpu/d3d12/SDL_gpu_d3d12.c
For some reason only known to Microsoft, `PFN_D3D12_XBOX_CREATE_DEVICE` is defined in `d3d12_xs.h`, but not in `d3d12_x.h`.
Checked/compiled with two recent GDK releases, including the latest version.
> GDK build: PFN_D3D12_XBOX_CREATE_DEVICE not defined for Xbox One

- src/gpu/SDL_gpu.c
- src/render/sdlgpu/SDL_shaders_gpu.c
Compilation without vulkan: SDL_GPU_VULKAN is always defined, test against 0 or 1
> Compilation without vulkan: SDL_GPU_VULKAN is always defined, test against 0 or 1

- Android.mk
otherwise it fails compilation with: 
```
SharedLibrary  : libSDL3.so
ld.lld: error: version script assignment of 'SDL3_0.0.0' to symbol 'SDL_CloseStorage' failed: symbol not defined
ld.lld: error: version script assignment of 'SDL3_0.0.0' to symbol 'SDL_CopyStorageFile' failed: symbol not defined
and so on ...
```
> Android.mk: allow to compile with storage functions

- include/SDL3/SDL_events.h
- include/SDL3/SDL_gpu.h
This was causing interop issues.
> Add padding for non-32-bit-aligned types in structs

- CMakeLists.txt
- src/gpu/SDL_gpu.c
- src/gpu/d3d11/SDL_gpu_d3d11.c
- src/gpu/d3d12/SDL_gpu_d3d12.c
This fixes build against mingw-w64 version 8.0.3:
- CreateEventEx() is guarded by _WIN32_WINNT >= 0x0600:
In SDL_gpu_d3d12.c, include core/windows/SDL_windows.h
that defines _WIN32_WINNT properly to account for that
- DXGIInfoQueue stuff is not available in all toolchains
such as mingw-w64 version 8.0.3
- SDL_gpu_d3d11.c: _WIN32 is always defined by MinGW, as
is the case for all windows-targeting compilers, so it
doesn't guarantee absence of DXGIInfoQueue stuff:
rely on __IDXGIInfoQueue_INTERFACE_DEFINED__, as it is
done elsewhere.
Fixes: https://github.com/libsdl-org/SDL/issues/10705 .
> [GPU] MinGW build fixes:

- include/SDL3/SDL_test_common.h
- include/SDL3/SDL_test_harness.h
- src/test/SDL_test_common.c
- src/test/SDL_test_harness.c
- test/testautomation.c
- test/testautomation_audio.c
- test/testautomation_blit.c
- test/testautomation_iostream.c
- test/testautomation_render.c
- test/testautomation_sdltest.c
- test/testautomation_subsystems.c
- test/testautomation_surface.c
- test/testautomation_timer.c
- test/testmultiaudio.c
By making an api for argument parsing, we can move argument parsing for testautomation into SDL_test.
This allows `SDLTest_RunSuites` to no longer need various arguments, and allows future refactoring of the test suite library without worrying too much about breaking the test suite api (it's used by SDL_image's test).
Tagging @1bsyl because he did recent work on the test suite library.
> Add an API for argument parsing to SDL3_test

- docs/README-migration.md
- include/SDL3/SDL_iostream.h
- include/SDL3/SDL_joystick.h
- include/SDL3/SDL_stdinc.h
- include/SDL3/SDL_storage.h
- src/file/SDL_iostream.c
- src/joystick/virtual/SDL_virtualjoystick.c
- src/storage/SDL_storage.c
- src/storage/generic/SDL_genericstorage.c
- src/storage/steam/SDL_steamstorage.c
- test/testautomation_iostream.c
- test/testautomation_joystick.c
- test/testcontroller.c
We guarantee that we will only add to the end of these interfaces, and any new fields will be optional.
> Initialize interface structures so they can be extended in the future

- src/audio/pipewire/SDL_pipewire.c
Check the client version first, before we start the hotplug thread and check the core version.
We are seeing crashes on systems with pipewire 0.65, which we suspect has an issue not properly shutting down the hotplug thread once SDL decides to move on to another audio backend.
> pipewire : check minimum client library version early

- include/SDL3/SDL_gpu.h
- src/dynapi/SDL_dynapi_procs.h
- src/gpu/SDL_gpu.c
- src/gpu/SDL_sysgpu.h
- src/gpu/d3d11/SDL_gpu_d3d11.c
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
- src/render/sdlgpu/SDL_pipeline_gpu.c
- src/render/sdlgpu/SDL_render_gpu.c
- src/render/sdlgpu/SDL_shaders_gpu.c
- test/testgpu_simple_clear.c
- test/testgpu_spinning_cube.c
This is a mass renaming to convert all GPU parameters and struct members into snake_case. Additionally, some parameters were renamed to make the APIs more SDL-ish (e.g. `somethingCount` -> `num_somethings`), reduce redundancy (`sizeInBytes` -> `size`), or remove vestigial Vulkan-isms (`pFences` -> `fences`).
While this is mostly straightforward, there are a handful of odd edge cases. `layer_count_or_depth` doesn't follow the `num_` prefix convention, but it's not entirely clear how we'd rephrase it. Is `blendfactor` one or two words? Should `mip_level` be renamed to `level`? And so forth... Would appreciate some opinions on this.
It'd also be nice to clean up some of the massive inconsistency this is causing in the backends between camelCase and snake_case, but that doesn't affect the …
> GPU: Rename struct members and parameters for SDL3 naming conventions

- include/SDL3/SDL_camera.h
- include/SDL3/SDL_dialog.h
- include/SDL3/SDL_events.h
- include/SDL3/SDL_gamepad.h
- include/SDL3/SDL_keyboard.h
- include/SDL3/SDL_mouse.h
- include/SDL3/SDL_pen.h
- include/SDL3/SDL_render.h
- include/SDL3/SDL_vulkan.h
This adds transitively included headers as direct includes to headers who require symbols from those added headers. (This makes life for my bindings generator a little easier)
I've also found some headers that are included but don't seem to be used, if you'd like I can submit a separate pull request to remove those.
> Include files with required types directly

- include/SDL3/SDL_gpu.h
This fixes some recent doc comments in SDL_gpu.h to use the correct syntax for trailing doc comments.
> Fix trailing doc comments in SDL_gpu.h

- src/stdlib/SDL_malloc.c
In `SDL_realloc()`, when `size` is `0`, it is changed to `1`, but only if `ptr` is `NULL`:
https://github.com/libsdl-org/SDL/blob/1ba99c53d48ec1f1f7c58b20326fc0c964ce5aa2/src/stdlib/SDL_malloc.c#L6460-L6468
This could be a problem, when calling `SDL_realloc()` with size 0 and a valid `ptr`. Then `size` would stay `0`,
`realloc(ptr, 0)` would be called and then the return value would be implementation-defined:
```c
void *ptr1 = SDL_realloc(NULL, 0); // OK, size is changed to 1
const size_t some_value = 123;
void *ptr2 = SDL_malloc(some_value);
if (ptr2) {
void *ptr3 = SDL_realloc(ptr2, 0); // <===== implementation-defined return value
}
```
> SDL_realloc() with size 0 now always defaults to size 1

- src/test/SDL_test_harness.c
```c
/path/to/SDL-git/src/test/SDL_test_harness.c:62:3: warning: redefinition of typedef 'SDLTest_TestSuiteRunner' is a C11 feature [-Wtypedef-redefinition]
62 | } SDLTest_TestSuiteRunner;
|   ^
/path/to/SDL-git/include/SDL3/SDL_test_harness.h:117:40: note: previous definition is here
117 | typedef struct SDLTest_TestSuiteRunner SDLTest_TestSuiteRunner;
|                                        ^
```
> Fix warning: redefinition of typedef 'SDLTest_TestSuiteRunner'

- include/SDL3/SDL_audio.h
- include/SDL3/SDL_camera.h
- include/SDL3/SDL_guid.h
- include/SDL3/SDL_pen.h
- include/SDL3/SDL_system.h
- include/SDL3/SDL_thread.h
- include/SDL3/SDL_touch.h
- include/SDL3/SDL_version.h
As discussed in #10748, this removes unused includes. It only removes includes that are completely unused. Some includes appear to be unused but have symbols referenced to in comments, I didn't remove those in case it'd break a documentation processor.
This removes `stdinc.h` from some files. I'm not sure if you want to keep that even if it's unused.
> Remove unused includes

- src/core/android/SDL_android.c
- src/core/freebsd/SDL_evdev_kbd_freebsd.c
- src/core/openbsd/SDL_wscons_kbd.c
- src/dialog/unix/SDL_portaldialog.c
- src/joystick/SDL_joystick.c
- src/joystick/linux/SDL_sysjoystick.c
- src/render/vulkan/SDL_render_vulkan.c
- src/sensor/SDL_sensor.c
- src/video/gdk/SDL_gdktextinput.cpp
- test/testdropfile.c
- test/testffmpeg_vulkan.c
`calloc-transposed-args` warnings appear, when the parameters for `nmemb` and `size` are passed to `calloc()` in reversed order. (This is recognized by where `sizeof()` is called)
First commit fixes all `calloc-transposed-args` warnings I could find during SDL compilation on my platform and could test.
Second commit should fix these warnings on other platforms, which I could **not** test.
These were found with a regex search: `calloc[\s]*\([\s]*sizeof[\s]*\(`
Here are the warnings which were fixed in the first commit:
```c
/path/to/SDL-git/src/joystick/SDL_joystick.c: In function ‘SDL_OpenJoystick_REAL’:
/path/to/SDL-git/src/joystick/SDL_joystick.c:1089:49: warning: ‘SDL_calloc_REAL’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument …
```
> Fix warnings: calloc-transposed-args

- include/SDL3/SDL_audio.h
This keeps them all in the same place, and merges them into the documentation.
Just making sure this doesn't upset any compilers before merging.
> audio: Make system-specific audio format types part of SDL_AudioFormat.

- include/SDL3/SDL_hints.h
- src/video/x11/SDL_x11vulkan.c
On most Unix platforms supported by SDL, the canonical name used to load a library at runtime includes its ABI major version, and the name without a version is not guaranteed to exist on non-developer systems. libX11-xcb.so.1 is correct on Linux, and probably on other Unix platforms like FreeBSD.
A notable exception is OpenBSD, which apparently does not use ABI-suffixed names, so continue to use libX11-xcb.so there.
#10677 
---
I believe this is correct, but it's untested: I don't know how to arrange for SDL3 to be on the relevant code path. I think it would be necessary to use a driver that implements `VK_KHR_XCB_SURFACE_EXTENSION_NAME` but not `VK_KHR_SURFACE_EXTENSION_NAME`.
> x11vulkan: Use the correct SONAME of libX11-xcb.so.1 on Linux, etc.

- include/SDL3/SDL_begin_code.h
- include/SDL3/SDL_stdinc.h
- src/dynapi/gendynapi.py
I found some spare time to document a few of the SDL_stdinc.h APIs ~~and add missing SDL_RESTRICT qualifiers to match the libc function signatures.~~
~~I also added `SDL_RESTRICT` qualifiers to the corresponding implementations. Let me know if you believe there are any problems with doing this.~~
Update: The `SDL_RESTRICT` macro has now been removed entirely in favor of documenting aliasing invariants in doc comments.
> stdinc: Document some APIs; remove SDL_RESTRICT in favor of doc comments

- src/video/wayland/SDL_waylandwindow.c
Clients may rely on this event to signal when they should redraw themselves, so send it when appropriate.
Fixes #10782
> [SDL2] wayland: Send exposure events when showing or resizing the window

- src/test/SDL_test_harness.c
#10773
```c
/path/to/SDL-git/src/test/SDL_test_harness.c:213:51: warning: cast from 'void (*)(void)' to 'SDL_TimerCallback' (aka 'unsigned int (*)(void *, unsigned int, unsigned int)') converts to incompatible function type [-Wcast-function-type-strict]
213 |     timerID = SDL_AddTimer(timeoutInMilliseconds, (SDL_TimerCallback)callback, 0x0);
|                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I removed the `SDL_NORETURN` from the function `SDLTest_BailOut()`, because MSVC complained:
```c
D:\a\SDL\SDL\src\test\SDL_test_harness.c(228): error C2220: the following warning is treated as an error
D:\a\SDL\SDL\src\test\SDL_test_harness.c(228): warning C4646: function declared with 'noreturn' has non-void return type
```
1 down, 761 more to go =)
> SDL_test_harness.c: Fix warning -Wcast-function-type-strict

- test/testoffscreen.c
```c
/path/to/SDL-git/test/testoffscreen.c:116:9: warning: bool literal returned from 'main' [-Wmain]
116 |         return SDL_FALSE;
|         ^      ~~~~~~~~~
/path/to/SDL-git/test/testoffscreen.c:124:9: warning: bool literal returned from 'main' [-Wmain]
124 |         return SDL_FALSE;
|         ^      ~~~~~~~~~
/path/to/SDL-git/test/testoffscreen.c:132:9: warning: bool literal returned from 'main' [-Wmain]
132 |         return SDL_FALSE;
|         ^      ~~~~~~~~~
```
> Fix testoffscreen.c: bool literal returned from 'main'

- src/core/unix/SDL_appid.h
- src/events/SDL_mouse.c
- src/video/x11/SDL_x11sym.h
- test/testautomation_blit.c
- test/testgpu_spinning_cube.c
- test/testrelative.c
`clang` `-Wstrict-prototypes`
```c
/path/to/SDL-git/src/events/SDL_mouse.c:1257:35: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
1257 | void SDL_DisableMouseWarpEmulation()
|                                   ^
|                                    void
/path/to/SDL-git/src/video/x11/SDL_x11sym.h:161:32: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
161 | SDL_X11_SYM(void,XrmInitialize,(),(),)
|                                ^
|                                 void
/path/to/SDL-git/src/core/unix/SDL_appid.h:27:34: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
27 | extern const char *SDL_GetExeName();
| …
```
> Adding void to empty function prototype parenthesis

- src/test/SDL_test_harness.c
- src/video/x11/SDL_x11sym.h
`clang` `-Wextra-semi`
Interesting fact:
The extra semicolon in `src/video/x11/SDL_x11sym.h` produced 44 warnings.
> Removing extra semicolons

- src/dynapi/gendynapi.py
This PR adds missing `SDL_WPRINTF_VARARG_FUNCV` since https://github.com/libsdl-org/SDL/commit/eda459ac49e290d1c33783ef48132d899c36504b to fix gendynapi.
> Add missing SDL_WPRINTF_VARARG_FUNCV in gendynapi.py

- src/gpu/vulkan/SDL_gpu_vulkan.c
Some remnants from before stencil ref and blend constants got moved to dynamic state. We may be able to optimize this further by only calling the Vulkan commands when a render pass is active.
> vulkan: Avoid redundant commands for dynamic states

- src/video/wayland/SDL_waylandmessagebox.c
I'm new to SDL and I wanted to write a quick HelloWorld program that just displays a box and closes the application.
I couldn't get it to work with SDL_GetError() returning "No message system available" so I spent some hours searching through docs and googling to see if someone had a similar issue. There were few github issues and everything I found had been created years ago and dealt with SDL2, not SDL3.
After nothing being helpful I just decided to debug the issue myself and almost immediately found that for some reason even though run_zenity() returns success, the if block that should follow doesn't execute, and instead get_zenity_version() just returns failure with a comment stating that run_zenity() should have already set the error message by calling SDL_SetError() (which it …
> Fix bug with SDL_ShowMessageBox not working with wayland

- include/SDL3/SDL_gpu.h
- src/gpu/SDL_gpu.c
- src/gpu/SDL_sysgpu.h
- src/gpu/d3d11/SDL_gpu_d3d11.c
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
- src/render/gpu/SDL_pipeline_gpu.c
- test/testgpu_spinning_cube.c
We got some feedback that the "vertex binding" terminology was confusing. E.g. "What is a binding? How is that different from a vertex buffer? Is a binding index the same as a buffer bind slot?"
To hopefully clarify this, we're renaming `VertexBinding` to `VertexBufferDescription`. This is conceptually similar to `ColorTargetDescription` which details the parameters for certain pipeline slots, separate from the actual resources that will be bound to them.
I also tweaked the docs, renamed a few struct members/parameter names to (hopefully) be more clear about their usage, and added some validation checks for vertex input.
> GPU: Rename VertexBinding to VertexBufferDescription

- src/gpu/d3d11/SDL_gpu_d3d11.c
- src/gpu/d3d12/SDL_gpu_d3d12.c
This fixes some bad assumptions we had regarding vertex buffer strides.
For D3D11, this allows more vertex buffers to be bound than the current pipeline supports, addressing over-read issues that were causing errors like `D3D11 ERROR: ID3D11DeviceContext::IASetVertexBuffers: Vertex Buffer stride (-33686019) for slot 1 is too large`.
For both D3D11 and D3D12 this fixes an issue where non-contiguous vertex buffer slots were not getting their strides set correctly. They were assigning the stride based on the index of the vertex buffer description rather than its `slot`.
> GPU: Fix D3D11/D3D12 vertex strides for multiple vertex buffers

- include/SDL3/SDL_test_log.h
- src/test/SDL_test_common.c
- src/test/SDL_test_log.c
`SDLTest_LogEscapedString` escapes non-printable characters.
Its behavior can be compared to python's `repr`.
For example, the multi-line string
```
Tests whether we can write to stdin and read from stdout
{'succes': true, 'message': 'Success!'}
Yippie ka yee
EOF
```
will be printed as `"Tests whether we can write to stdin and read from stdout\r\n{'succes': true, 'message': 'Success!'}\r\nYippie ka yee\r\nEOF"`
(this is a test case of the SDL_process pr)
> SDL_Test: add SDLTest_LogEscapedString

- include/SDL3/SDL_stdinc.h
- src/events/SDL_pen_c.h
- src/stdlib/SDL_string.c
- test/testautomation_stdlib.c
I believe this fixes all the unintended bugs in
- `SDL_strtol`,
- `SDL_strtoul`,
- `SDL_strtoll`,
- `SDL_strtoull`, and
- `SDL_wcstol`.
In addition, it also adds support for octals and other bases. See the test cases for examples. Covering every single edge case and combination of important parameters would be impractical but I believe this makes the implementations for these functions compliant with the libc specs ([strtol/strtoll](https://pubs.opengroup.org/onlinepubs/9799919799.2024edition/functions/strtol.html), [strtoul/strtoull](https://pubs.opengroup.org/onlinepubs/9799919799.2024edition/functions/strtoul.html), [wcstol](https://pubs.opengroup.org/onlinepubs/9799919799.2024edition/functions/wcstol.html)).
It also improves `SDL_strtod` slightly (use `unsigned long long` to parse the …
> Rewrite/fix bugs in `SDL_strtol` and friends

- src/process/windows/SDL_windowsprocess.c
- test/testprocess.c
In the Windows implementation of processes, the arguments only had their double quotes escaped. Backslashes that appear before quotes (but not ones that don't!) also needed to be escaped. This PR fixes that, and adds some extra tests with quotes, backslashes, and other symbols that may have an impact if escaping is not done properly.
Fixes #10831
> Windows process: escape backslashes that appear before double quotes

- include/SDL3/SDL_process.h
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
- src/process/SDL_process.c
- test/testprocess.c
Not sure if this is _really_ needed but I ended up immediately writing these helpers for myself and they do allow processes created with the simpler API and pipe_stdio to be used more flexibly than SDL_Read/WriteProcess without ever having to touch the property API.
> Add convenience functions to get process IOStreams

- include/SDL3/SDL_process.h
SDL_process.h requires symbols from these includes, but didn't include them.
> Add missing includes to SDL_process.h

- sdl2.m4
Fix a typo in sdl2.m4. occured -> occurred. blast007 pointed this out in [BZFlag](https://github.com/BZFlag-Dev/bzflag) [#359](https://github.com/BZFlag-Dev/bzflag/pull/359).
N/A
> Comment typo fix: occured is not occurred

- include/SDL3/SDL_gpu.h
- src/gpu/metal/SDL_gpu_metal.m
In Metal, there's a single "namespace" for all buffers in a given stage. So vertex buffers, uniform buffers, and storage buffers compete for space in the 31 slots Metal provides.
Previously we were binding vertex buffers at index 30 and growing downward to avoid index collisions with other buffers. However, this is no longer necessary. We only support 4 uniform buffers and 8 storage buffers, so instead of having some awkward contortions in our indexing logic, we can just have the vertex buffers bindings start in the middle and grow upward.
@Akaricchi Could you check if this fixes the issue you were seeing on Metal?
> GPU: Metal vertex buffer indices should grow upward

- include/SDL3/SDL_gpu.h
- src/gpu/SDL_gpu.c
- src/gpu/d3d11/SDL_gpu_d3d11.c
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
- test/testgpu_spinning_cube.c
Resolves https://github.com/libsdl-org/SDL/issues/10847
Currently MSAA textures are actually two textures in a trench coat: one multisample, one resolve. Which one you get depends on the context. E.g. if you're binding it as a render target, it uses the multisample texture. If you're sampling from it, it uses the resolve texture.
While it's convenient to not have to juggle two textures, in practice we've found this setup to be confusing and full of subtle gotchas. It also prevents you from doing certain operations like preserving the contents of a multisample texture across render passes, or sampling from a multisample texture[*].
So instead, we're introducing a new setup for MSAA. Multisample textures are just that, multisample textures. Resolve textures must be created separately and …
> GPU: Rework MSAA

- src/camera/v4l2/SDL_camera_v4l2.c
If the device signals that it is ready, we should return success. I am not sure why it worked in some situations before, so I suspect `device->shutdown` might be set wrongly somewhere, but not sure.
This enables me to use obs virtual camera (v4l2 loopback) and some more configurations of my webcam.
refs:
- https://www.kernel.org/doc/html/v5.6/media/uapi/v4l/func-select.html#return-value
- https://github.com/obsproject/obs-studio/blob/16b8e9c3fe48e2dadfa0723cc162e842936bbab8/plugins/linux-v4l2/v4l2-input.c#L221
looks like #10698 describes this.
> v4l2: return success if the device is ready

- src/render/gpu/shaders/build-shaders.sh
* render: Fix detection of fxc, dxc in build-shaders.sh
We want `$USE_FXC` to default to the result of evaluating the variable
`$HAVE_FXC`, not the literal string `HAVE_FXC`, and the same for dxc.
* render: Don't try to rebuild D3D11, D3D12, Metal shaders without spirv-cross
---
Related to #10878. Context for this is that Debian requires source code for everything we ship, so I can't include SDL in Debian without being able to compile at least the subset of the shaders that are actively used in Debian from their original .vert/.frag files. We don't currently have spirv-cross available, but we also don't actually need it, because D3D11, D3D12 and Metal are not relevant on Linux.
> render: Don't try to rebuild D3D11, D3D12, Metal shaders without spirv-cross

- src/render/gpu/shaders/.gitignore
- src/render/gpu/shaders/build-shaders.sh
- src/render/gpu/shaders/fix-shaders.sh
* render: Integrate fix-shaders.sh into build-shaders.sh
By writing the fxc and dxc output to a temporary file and then
converting that temporary file to the desired filename, we avoid
the incompatible semantics of sed -i on GNU systems (sed -i does not
create a backup filename, and does not take an argument unless it is
"bundled") and macOS (sed -i requires an argument, possibly empty).
Resolves: https://github.com/libsdl-org/SDL/issues/10878
---
Please test on whatever platform @slouken is using (macOS?) before merging!
> render: Integrate fix-shaders.sh into build-shaders.sh

- src/joystick/SDL_joystick.c
Add the Thrustmaster TMX to the SDL wheel list to allow it to be properly supported as a wheel.
The Thrustmaster TMX should now be properly detected as a wheel with SDL.
VID: `0x044F`
PID: `0xB67F`
> Add Thrustmaster TMX VID & PID to wheel device list.

- test/testaudio.c
- test/testaudiostreamdynamicresample.c
- test/testhittesting.c
- test/testintersections.c
- test/testmanymouse.c
- test/testoverlay.c
- test/testwm.c
Scales pointer coordinates where needed to fix the following tests when run with the --high-pixel-density flag:
- testaudio
- testaudiostreamdynamicresample
- testhittesting
- testintersections
- testmanymouse
- testoverlay
- testwm
Addresses problematic tests as noted in #10875
> tests: Fix tests when run with the --high-pixel-density flag

- src/video/windows/SDL_windowsevents.c
Contents of `winuser.h` are generally not available when targeting `WINAPI_PARTITION_GAMES`.
Don't compile the call to `GetMessageTime` on Xbox, fixes a build failure.
- Fixes #10159
> Don't call GetMessageTime on Xbox platforms

- src/gpu/vulkan/SDL_gpu_vulkan.c
Removing a lock usage ended up being a week-long optimization rabbit hole.
Optimizing Vulkan descriptor set usage is very hard. I experimented with a lot of different approaches. The main issue is that descriptor set pools have to be created from descriptor set layouts, so it wasn't immediately clear how we could have a descriptor pool and cleanly avoid locking. I tried hashing descriptor sets so they could be re-used instead of updated, but the extra record keeping was incredibly complex and ended up offsetting most of the benefits of descriptor set reuse.
After a lot of testing I settled on the following changes:
- We now de-duplicate pipeline layout and descriptor set layout objects. This significantly cuts down on the number of descriptor pools.
- Descriptor set layouts use monotonic …
> GPU: Vulkan descriptor management rewrite

- src/gpu/SDL_gpu.c
Especially as of #10910 the Vulkan backend is profoundly more optimal than D3D12 in both performance and memory usage. Seeing as we'll need to do significant rewrites to optimize D3D12 memory management and descriptor usage, we should just bump Vulkan to the top of the preference list to put our best foot forward. We can always revisit this once optimizations are completed.
> Prefer Vulkan even on Windows

- include/SDL3/SDL_stdinc.h
- test/testautomation_stdlib.c
As discussed in https://github.com/libsdl-org/SDL/pull/10899
> Add SDL_PRILL? format specifiers specifically for long long type.

- src/gpu/SDL_gpu.c
- src/gpu/d3d11/SDL_gpu_d3d11.c
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
This PR contains a few fixes for multisampling in the GPU API:
* Removes support for multisample 2D array textures; they're not supported on Metal until very recent iOS/tvOS versions, and they don't seem particularly useful in general.
* Adds a missing validation check to ensure MSAA resolve textures were created with the COLOR_TARGET usage flag.
* Fixes Metal multisample textures using the incorrect MTLTextureType. Resolves https://github.com/libsdl-org/SDL/issues/10891)
> GPU: MSAA fixes

- src/video/kmsdrm/SDL_kmsdrmvideo.c
Modern kernels (v5.8+) allow non-root usage of `drmDropMaster()`, so we can hold on to our fd after dropping master on it. This fixes populating `drm_fd` in the KMSDRM `SysWMinfo` when using Vulkan. Also add a missing error check for open() while we're here.
I'll open a PR for SDL3 if this looks fine.
> kmsdrm: Keep fd around if we can drop master

- src/gpu/SDL_gpu.c
Tiny fix for building with SDL_GPU_DISABLED since backends is not defined then.
> GPU: fix build when SDL_GPU_DISABLED is set

- include/SDL3/SDL_pixels.h
Related to https://github.com/libsdl-org/SDL/pull/10921
`SDL_Colorspace` enum constant aliases `SDL_COLORSPACE_RGB_DEFAULT` and `SDL_COLORSPACE_YUV_DEFAULT` don't appear in the wiki.
https://wiki.libsdl.org/SDL3/SDL_Colorspace
This commit moves them into the enum.
> Move default colorspace aliases into enum

- src/joystick/hidapi/SDL_hidapijoystick.c
- src/joystick/windows/SDL_rawinputjoystick_c.h
- src/video/windows/SDL_windowsmouse.h
Adding `void` to function prototypes.
Compiler: `MSVC`
Warning: `C4255`
Flag: `/w14255`
```c
C:\path\to\SDL-git\src\joystick\windows\SDL_rawinputjoystick_c.h(25,33): warning C4255: 'RAWINPUT_IsEnabled': no function prototype given: converting '()' to '(void)' (compiling source file ..\..\src\joystick\hidapi\SDL_hidapijoystick.c)
C:\path\to\SDL-git\src\joystick\windows\SDL_rawinputjoystick_c.h(29,46): warning C4255: 'RAWINPUT_UnregisterNotifications': no function prototype given: converting '()' to '(void)' (compiling source file ..\..\src\joystick\hidapi\SDL_hidapijoystick.c)
C:\path\to\SDL-git\src\video\windows\SDL_windowsmouse.h(32,41): warning C4255: 'WIN_UpdateMouseSystemScale': no function prototype given: converting '()' to '(void)' (compiling source file …
```
> Fix warning: no function prototype

- src/core/android/SDL_android.c
Android OpenURL and Toast methods return Booleans now, so let's use the correct interface.
> Change JNI calls to comply with recent Boolean error return changes

- src/video/SDL_blit.c
- src/video/SDL_surface.c
- test/testautomation_surface.c
A zero sized source rect draws pixels sourced from a 0x0 region on the source surface.
Fixes https://github.com/libsdl-org/SDL/issues/8580
> A zero source rect is valid for blitting

- src/video/wayland/SDL_waylandevents.c
Suppose host has some three-finger gesture. Then we get the following sequence of events:
DOWN-DOWN-DOWN-MOTION-CANCEL
Note that there is no UP in this sequence. So if we don't handle CANCEL then we end up thinking that fingers are still touching the screen. Ideally we should inform the application that cancel has happened as not to trigger spurious taps but still this is way better than being stuck with phantom finger touch.
> Handle wayland touch cancel message

- include/SDL3/SDL_gpu.h
- src/gpu/d3d11/SDL_gpu_d3d11.c
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
Adds a bool to SDL_GPURasterizerState that allows developers to specify whether they would prefer depth clipping or depth clamping in a given graphics pipeline.
This feature requires additional Vulkan physical device features (`depthClamp` and `shaderClipDistance`), but they're broadly supported outside of low-end Android.
Some special care will need to be taken with D3D since it behaves differently from the other graphics APIs, so I noted that in the doc comments for the struct.
Resolves https://github.com/libsdl-org/SDL/issues/10815
Resolves https://github.com/libsdl-org/SDL/issues/10814
> GPU: Add enable_depth_clip to RasterizerState

- include/SDL3/SDL_gpu.h
- src/dynapi/SDL_dynapi_procs.h
- src/gpu/SDL_gpu.c
- src/gpu/SDL_sysgpu.h
- src/gpu/d3d11/SDL_gpu_d3d11.c
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
Resolves #10945 
TODOs are the Metal support check and documenting the universally-supported read-write texture formats.
I'd also like to make sure the header documentation is very clear about the potential pitfalls of doing this, so if the wording could be improved, let me know.
> GPU: Simultaneous compute pass read-write

- include/SDL3/SDL_clipboard.h
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
- src/video/SDL_clipboard.c
This function allows to retrieve the available mime types without doing any synthesizing.
None, but we'd need that in FreeRDP
> clipboard: add SDL_ClipboardMimeTypes

- test/testcolorspace.c
```c
/path/to/SDL-git/test/testcolorspace.c:130:9: warning: 'return' will never be executed [-Wunreachable-code-return]
130 |         return;
|         ^~~~~~
```
`StageCount` is an enum constant with a current value of `8`.
The check `StageCount <= 0` can probably be removed.
```c
enum
{
StageClearBackground,
StageDrawBackground,
StageTextureBackground,
StageTargetBackground,
StageBlendDrawing,
StageBlendTexture,
StageGradientDrawing,
StageGradientTexture,
StageCount
};
```
```c
if (StageCount <= 0) {
return;
}
```
This assumes that the elements in the enum will not change drastically in the future.
> testcolorspace.c: Fix unreachable code warning

- include/SDL3/SDL_filesystem.h
- src/filesystem/SDL_filesystem.c
- src/filesystem/posix/SDL_sysfsops.c
- src/filesystem/windows/SDL_sysfsops.c
- test/testfilesystem.c
> filesystem: SDL_EnumerateDirectoryCallback uses an enum now, not an int.

- include/SDL3/SDL_process.h
```c
/path/to/SDL-git/include/SDL3/SDL_process.h:148:31: warning: commas at the end of enumerator lists are a C99-specific feature [-Wc99-extensions]
148 |     SDL_PROCESS_STDIO_REDIRECT,     /**< The I/O stream is redirected to an existing SDL_IOStream. */
|                               ^
```
> Remove trailing comma in enum

- src/render/SDL_render.c
- src/render/SDL_sysrender.h
- src/render/gpu/SDL_render_gpu.c
> Render GPU: Don't call GetWindowSizeInPixels during RenderPreset

- include/SDL3/SDL_gpu.h
- src/gpu/d3d11/SDL_gpu_d3d11.c
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/vulkan/SDL_gpu_vulkan.c
This avoids querying window size in a relatively hot function, `SDL_AcquireGPUSwapchainTexture`.
Also removes a pointless Vulkan surface extent check, the limits are guaranteed by the spec.
> GPU: recreate swapchain on window pixel size change event

- src/SDL_hashtable.c
The original SDL hashtable implementation is pretty naive. Every key-value pair is stored in a separate allocation, and collisions are resolved via a linked list. While this scheme is very simple to implement, it's bad for cache locality (and therefore performance).
This new implementation uses an open-addressing scheme, which places every pair in one contiguous array instead of separate buckets. It automatically grows as the load factor increases, which was a TODO in the old code. Linear probing is used to resolve collisions, which keeps colliding items close in memory. [Robin hood hashing](https://programming.guide/robin-hood-hashing.html) is used to greatly reduce variance in the probe sequence length across all items. The backward shifting optimization for deletions (described at the …
> A better hashtable implementation

- src/video/SDL_video.c
SDL_GetWindowOpacity is always returning 1.0f, even if the opacity has been changed. It was caused by a wrong error check condition in the SDL_SetWindowOpacity, preventing the update of the opacity value.
> Fix window opacity update

- include/SDL3/SDL_gpu.h
- src/dynapi/SDL_dynapi_procs.h
- src/gpu/SDL_gpu.c
- src/gpu/SDL_sysgpu.h
- src/gpu/d3d11/SDL_gpu_d3d11.c
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
- src/render/gpu/SDL_render_gpu.c
- test/testgpu_simple_clear.c
- test/testgpu_spinning_cube.c
Resolves #10982 
The relevant ABI change here is that we are returning swapchain dimensions from `SDL_AcquireGPUSwapchainTexture` once again. I decided that this makes sense in light of certain window synchronization edge cases and the fact that swapchain textures are the only textures outside of client control.
Importantly, this PR reworks certain Vulkan swapchain management concerns.  There is a very specific corner case on Win32 + NVIDIA where the Vulkan surface capability extents can return (0,0), particularly if the window is minimized, but also in certain other unclear cases. If this happens we cannot use the surface to create a swapchain, because the minimum extents are (1, 1), but it doesn't mean that using the window is now completely invalid for swapchain usage. If this occurs, …
> GPU: Add swapchain dimension out params

- src/render/SDL_render.c
- src/render/SDL_sysrender.h
- src/render/gpu/SDL_render_gpu.c
- src/render/opengl/SDL_render_gl.c
- src/render/opengles2/SDL_render_gles2.c
- src/render/psp/SDL_render_psp.c
This makes it so we don't have to surface the rectangle winding order for applications that want to use the raw geometry API.
> Disable backface culling and use a constant rectangle winding order.

- src/hidapi/windows/hid.c
Returns bytes_written if WriteFile returns synchronously
Relevant mainstream discussions:
https://github.com/libusb/hidapi/pull/697
https://github.com/libusb/hidapi/issues/695
If this gets in, SDL2 branch might need some similar touch (I won't..)
> hidapi: update hid_write() for windows from mainstream.

- src/process/posix/SDL_posixprocess.c
- test/testprocess.c
Fixes https://github.com/libsdl-org/SDL/issues/10997
> Don't close file descriptors already handled by AddFileDescriptorCloseActions()

- src/SDL_hashtable.c
- src/SDL_hashtable.h
Decided in https://github.com/libsdl-org/SDL/issues/11032#issuecomment-2389656487
> Removed const qualifiers from SDL_CreateHashTable() parameter types

- src/render/vulkan/SDL_render_vulkan.c
`SDL_Vulkan_GetResultString()` is already declared in `src/video/SDL_vulkan_internal.h`:
https://github.com/libsdl-org/SDL/blob/07fd88d2413db6157dd32d3659e4dbef68272b8e/src/video/SDL_vulkan_internal.h#L56
> Remove redundant SDL_Vulkan_GetResultString() declaration

- include/SDL3/SDL_render.h
- src/render/SDL_render.c
Before this commit, it would adjust for the logical presentation settings. Now, it works as it did before the logical presentation render target was removed: it takes current viewport and scale into account, as well.
Fixes #10978.
> render: Restore previous policy for converting window/render coordinates.

- src/events/SDL_pen.c
> Removed redundant condition in src/events/SDL_pen.c

- src/timer/unix/SDL_systimer.c
The function `CheckMonotonicTime()` doesn't set `checked_monotonic_time` to `true` if `clock_gettime()` succeedes, because of a trailing `else` statement in line 76:
https://github.com/libsdl-org/SDL/blob/020fb6889ccb5a8ac7e6b16e375de935514f09a6/src/timer/unix/SDL_systimer.c#L70-L83
This commit assumes, that the `checked_monotonic_time` variable should always be set, when the function `CheckMonotonicTime()` is called.
The last big rehaul of this function happened in 8121bbd083b5a568709305270b554f2add3ba4a1
> Always set checked_monotonic_time when calling CheckMonotonicTime()

- include/SDL3/SDL_video.h
- src/video/SDL_egl.c
Now it has access to information it needs and it's clear who is reponsible for memory management.
Fixes #11039.
> video: Improve the EGL attribute callbacks.

- src/gpu/d3d12/SDL_gpu_d3d12.c
Missed one library handle in 0b5e01a (only used in Xbox builds)
> Change evasive library handle to `SDL_SharedObject*`

- src/camera/pipewire/SDL_camera_pipewire.c
fix wrong pipewire prototype for function `pw_proxy_add_listener`
This make compilation fail with GCC 14, resulting in a `incompatible-pointer-types` error.
> fix pipewire prototype

- include/SDL3/SDL_events.h
- src/core/android/SDL_android.c
- src/events/SDL_clipboardevents.c
- src/events/SDL_clipboardevents_c.h
- src/events/SDL_events.c
- src/video/SDL_clipboard.c
- src/video/SDL_clipboard_c.h
- src/video/cocoa/SDL_cocoaclipboard.m
- src/video/uikit/SDL_uikitclipboard.m
- src/video/wayland/SDL_waylandevents.c
- src/video/windows/SDL_windowsclipboard.c
- src/video/x11/SDL_x11clipboard.c
- src/video/x11/SDL_x11clipboard.h
- src/video/x11/SDL_x11events.c
- src/video/x11/SDL_x11video.c
- src/video/x11/SDL_x11video.h
- src/video/x11/SDL_x11window.c
- src/video/x11/SDL_x11xfixes.c
This patch modifies the clipboard handling so that when we receive an external clipboard update, if we call `SDL_GetClipboardMimeTypes()` during the treatment of a `SDL_EVENT_CLIPBOARD_UPDATE` it will return the available mime types.
This patch codes updates of the array of mime types in the `SDL_VideoDevice` when we receive an external clipboard change notification.
This PR is for comments, I'm open to other solutions like having the new mime types contained in the `SDL_ClipboardEvent`. Most platform have a notion of clipboard owner, perhaps that should also be indicated in the clipboard event so that we know if it's an internal or external update.
This should solve #10598 at least with what we do in FreeRDP.
> [RFC] clipboard: update the supported mime types when it's an external update

- test/testautomation_images.c
Changed image data pixel format to BGRA32.
Tested on x86_64 and PowerPC.
#10794
> test: Make blit_testExampleApplicationRender work on big endian

- src/video/x11/SDL_x11mouse.c
XGrabPointer can warp the cursor into the window when confining, so set the flag to refresh the global coordinates when queried.
Fixes #8090
> x11: Refresh the global cursor coordinates when confining the pointer

- include/SDL3/SDL_hints.h
- src/video/cocoa/SDL_cocoaevents.m
This PR adds a new hint for smooth momentum values in SDL_EVENT_MOUSE_WHEEL events on MacOS.
When scrolling on a touchpad on MacOS the scroll values usually contain momentum inside all native applications. But inside SDL the scroll values were without momentum. This PR adds a simple hint to control `"AppleMomentumScrollSupported"` MacOS API for requesting the native momentum.
Please let me know if there is a better name for the hint or if you have better wording for the documentation part.
Here is a simple "browser" test application with scrolling to see the difference.
| Momentum | Video |
|--------|--------|
| OFF | <video src="https://github.com/user-attachments/assets/9d71ea5e-82b1-4d04-b211-84f10bf5f977"> |
| ON | <video src="https://github.com/user-attachments/assets/399c759c-635e-4e …
> macOS: Add a hint for smooth momentum values in SDL_EVENT_MOUSE_WHEEL events

- examples/audio/01-simple-playback/simple-playback.c
- examples/audio/02-simple-playback-callback/simple-playback-callback.c
- examples/audio/03-load-wav/load-wav.c
- examples/camera/01-read-and-draw/read-and-draw.c
- examples/pen/01-drawing-lines/drawing-lines.c
- examples/renderer/01-clear/clear.c
- examples/renderer/02-primitives/primitives.c
- examples/renderer/03-lines/lines.c
- examples/renderer/04-points/points.c
- examples/renderer/05-rectangles/rectangles.c
- examples/renderer/06-textures/textures.c
- examples/renderer/07-streaming-textures/streaming-textures.c
- examples/renderer/08-rotating-textures/rotating-textures.c
- examples/renderer/09-scaling-textures/scaling-textures.c
- examples/renderer/10-geometry/geometry.c
- examples/renderer/11-color-mods/color-mods.c
- examples/renderer/14-viewport/viewport.c
- examples/renderer/15-cliprect/cliprect.c
- examples/renderer/17-read-pixels/read-pixels.c
- examples/template.c
Note this removes _all_ the message boxes, not just the ones when SDL_Init fails. If that's too much, we can adjust.
Fixes #11094.
> examples: Use SDL_Log() instead of message boxes for errors.

- include/SDL3/SDL_stdinc.h
Currently, `SDL_PRINTF_VARARG_FUNC` and `SDL_PRINTF_VARARG_FUNCV` macros are only enabled when compiling with GCC. This PR also defines them for Clang, which means that they can now be used on Windows when compiling with MSVC toolchain (as opposed to MinGW).
None
> Use the printf vararg verification macros when compiling with clang

- android-project/app/src/main/AndroidManifest.xml
I lost some time on wondering why audio was only partly working, turns out I only had specified the feature usage, but not the permission, which was hiding a couple lines below in the manifest I copied from the sdl example.
Simply move 1 line up in the manifest and delete a redundant one.
This now mimics how Camera looks.
> fix microphone permission and feature flags being spread out

- src/gpu/vulkan/SDL_gpu_vulkan.c
This is already checked for in vkAcquireNextImageKHR but it can also be returned by vkQueuePresentKHR.
> Check for VK_SUBOPTIMAL_KHR also in vkQueuePresentKHR

- examples/game/01-snake/snake.c
* snake: Add basic app metadata
All SDL3 applications and games should ideally have this.
* snake: Add extended app metadata
All of these are optional, but nice-to-have, and we have reasonable
values available for all of them.
> Add app info to Snake example

- src/test/SDL_test_font.c
With the recent changes to logical presentation, this is necessary for the font to look good when scaled.
Fixes https://github.com/libsdl-org/SDL/issues/11123
> Allow linear interpolation of the font textures

- src/SDL.c
This is not shown by default, but will be shown when using SDL_LOGGING=system=info or higher, where it will hopefully nudge app authors towards initializing this information.
> Log app ID as SYSTEM/INFO during initialization

- include/SDL3/SDL_main.h
Basically all platforms where SDL_main.h renames `main()` to `SDL_main()` use the platform-specific `main()` (or `WinMain()` or whatever) implementations in SDL_main_impl.h - and that renaming is enabled with:
```c
#if defined(SDL_MAIN_NEEDED) || defined(SDL_MAIN_AVAILABLE)  || defined(SDL_MAIN_USE_CALLBACKS)
#define main SDL_main
#endif
```
The only exception is Android, where `main()` *is* renamed, but SDL_main_impl.h isn't used, because `SDL_main()` is called from Java.
So I think it's cleaner and less error-prone (for adding additional platforms that need `SDL_main()` in the future), to use the same check for including SDL_main_impl.h as is used for `#define main SDL_main` and only list the exceptions (currently Android) there explicitly.
If new "weird" platforms like Android turn up, …
> Simplify code to include SDL_main_impl.h in SDL_main.h

- include/SDL3/SDL_hints.h
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/joystick/gdk/SDL_gameinputjoystick.c
- test/testcontroller.c
Tests included in VisualC-GDK now default to the GPU renderer, but crash on Xbox because the swap chain size isn't set, causing the backbuffer texture creation to fail.
The second change just enables the GameInput joystick driver in `testcontroller`, which is the only system driver initialized on Xbox right now.
> VisualC-GDK: fix tests on Xbox

- src/video/x11/SDL_x11events.c
Pasting from an SDL2 application to some targets (like chromium/electron-based applications) causes them to hang.
This was already fixed by #7703 for SDL3, but the change was never backported.
> [SDL2] x11: Set correct clipboard target type in `SelectionRequest` handling

- src/gpu/d3d11/SDL_gpu_d3d11.c
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/vulkan/SDL_gpu_vulkan.c
Querying window size can be problematic, so let's avoid it when we can. Need to sanity check this on Linux before merge.
> GPU: Avoid calling SDL_GetWindowSizeInPixels when possible

- src/gpu/vulkan/SDL_gpu_vulkan.c
The SDL_GPUColorTargetInfo structure needs to be zeroed, as otherwise we can end up trying to create a resolve_texture which doesn't exist, causing a rather difficult-to-debug segfault when calling SDL_BlitGPUTexture() with a load op of SDL_GPU_LOADOP_CLEAR.
> gpu: vulkan: Fix an uninitialised structure in SDL_BlitGPUTexture()

- android-project/app/src/main/AndroidManifest.xml
The addition of grammaticalGender will be required by certain locale changes. 
Also adding fontWeightAdjustment & fontScale for good measure.
Fixes #10293
> Add more configChanges to Android Manifest

- include/SDL3/SDL_stdinc.h
- include/SDL3/SDL_timer.h
- src/SDL_hashtable.c
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
- src/main/generic/SDL_sysmain_callbacks.c
- src/render/SDL_render.c
- src/timer/SDL_timer.c
- test/testautomation_stdlib.c
- test/testtimer.c
SDL_DelayNS() now passes through to the high precision OS delay function, and SDL_DelayPrecise() tries to busy wait to get as close as possible to the desired wait time.
Fixes https://github.com/libsdl-org/SDL/issues/11141
> Added SDL_DelayPrecise()

- include/SDL3/SDL_hints.h
Replacing `SDL_HINT_` with just `SDL_` in string literal for hint `SDL_HINT_MAC_SCROLL_MOMENTUM`.
This hint was added in c2b98e21bade35bcccba249f5e74ba08d5b88e5a
after the 3.1.3 preview
> Rename hint string literal SDL_HINT_MAC_SCROLL_MOMENTUM

- include/SDL3/SDL_gpu.h
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
- src/gpu/SDL_gpu.c
- src/gpu/SDL_sysgpu.h
- src/gpu/metal/SDL_gpu_metal.m
This is a fairly common client need and it's annoyingly nuanced to implement, so we should expose it.
> GPU: Add SDL_CalculateGPUTextureFormatSize

- include/SDL3/SDL_hints.h
This was added after 3.1.3 preview.
> Set hint SDL_HINT_MAC_SCROLL_MOMENTUM version to SDL 3.1.4.

- include/SDL3/SDL_bits.h
Since SDL3, SDL_bits.h is included with SDL.h, which wasn't the case in SDL2. Because of this, when compiling with clang on windows(msvc) and using the _-Werror_ and _-Wsign-conversion_ flags, the compiler warns of an implicit sign conversion on 
_SDL_MostSignificantBitIndex32_ on source files that include <SDL/SDL3.h>.
The change adds an explicit cast to this specific case, which is the only code path that does not return an int direcly. Since the conversion is done anyways, I believe there's no harm in making it an explicit cast.
> explicit cast to int in SDL_bits

- include/SDL3/SDL_main.h
- include/SDL3/SDL_main_impl.h
Fixing an oversight in #11126, and introducing a #define in SDL_main.h that communicates that
`main()` *should* be renamed to `SDL_main()` (and `SDL_main()` should be implemented by SDL in case of `SDL_MAIN_USE_CALLBACKS`), but no **native** main function must be implemented by SDL_main_impl.h because it's implemented somewhere outside the C/C++ codebase, for example in Java code. Currently that's only defined for Android.
SDL_MAIN_EXPORTED is defined for platforms where the real main() function is outside of the code that uses SDL, like Android where Java code is used that calls SDL_main().
My last simplification of the conditions for including SDL_main_impl.h had one problem: I forgot that SDL_main_impl.h must be included even on Android when SDL_MAIN_USE_CALLBACKS is used, because then …
> Fix SDL_MAIN_USE_CALLBACKS with Android, introduce SDL_MAIN_EXPORTED

- build-scripts/SDL_migration.cocci
SDL_bool wasn't renamed when using the coccinelle script. Specifying typedef like other data types in SDL_migration.cocci works.
> SDL_migration.cocci: Fix renaming SDL_bool

- include/SDL3/SDL_opengl.h
I've added two macros in SDL_opengl.h to help with dynamically loading OpenGL:
- `#define SDL_OPENGL_1_NO_PROTOTYPES` to hide function prototypes
- `#define SDL_OPENGL_1_FUNCTION_TYPEDEFS` to add PFNGL*PROC function types
They help avoid clashing names for OpenGL functions up to 1.3 when developers use a different or a custom OpenGL loader.
I've also added the typedefs (PFNGL...PROC) for those functions. Since they seem not to be standard, I made another macro to hide them by default. I created them with gedit 41.0 find-and-replace, with find = `GLAPI ([a-zA-Z0-9 \*]+) GLAPIENTRY (gl[a-zA-Z0-9]+) *\(([^)]+)\);` and replace = `typedef \1 (APIENTRYP PFN\U\2\EPROC) (\3);`. This is probably compatible with other regex engines; the least common-looking feature I used is `\U` for uppercase and …
> Add macro guards for OpenGL <=1.3 function prototypes

- src/video/SDL_blit_0.c
Inlining `BlitBtoNAlpha` and `BlitBtoNAlphaKey` increases the object size significantly due to the increased complexity, and aren't as likely to be used compared to the other 1/2/4bpp blitting routines.
> Reduce the size of the SDL_blit_0 alpha code

- docs/README-migration.md
- src/SDL_hints.c
Especially SDL_VIDEODRIVER is commonly used to use the native Wayland backend, so I think it's a good idea to keep supporting the old name instead of forcing users to find out that they now have to add an underscore..
Not sure how popular SDL_AUDIODRIVER is, but with all the audio backends that exist on Linux alone I'm sure some people use it to work around sound issues.
I'm not 100% sure what the best way to do this is, but the easiest way to do it cleanly seemed to be to implement a small wrapper around SDL_getenv() in SDL_hints.c that, if SDL_getenv() returned NULL for the given name (i.e. the "proper" SDL3 hint string), checks whether it was SDL_HINT_VIDEO_DRIVER or SDL_HINT_AUDIO_DRIVER and tries again with "SDL_VIDEODRIVER" and "SDL_AUDIODRIVER".
This is not overly generic and might …
> Old env vars as fallback for SDL_VIDEO_DRIVER + SDL_AUDIO_DRIVER

- src/video/SDL_blit.h
- src/video/SDL_blit_1.c
- src/video/SDL_blit_A.c
- src/video/SDL_blit_N.c
This uses 8x unrolling for cases where each iteration of the loop is expected to only require a few instructions, and 4x unrolling for other loops, which should hopefully provide a better tradeoff between speed and executable size. It also makes it easier for specific platforms to use different levels of unrolling, e.g. if RAM is limited or the cache is small.
> Allow for more fine tuning of Duff's device routines

- test/testdrawchessboard.c
This is split out from PR #9598, with the default changed to use the window surface API instead of the accelerated renderer.
> testdrawchessboard: Allow using the standard render API

- src/video/cocoa/SDL_cocoaopengl.m
Fixed the usage of `Cocoa_GLES_LoadLibrary` in `Cocoa_GL_CreateContext()`. It was still using the old SDL2 style of return success/failure.
Fixes issue https://github.com/libsdl-org/SDL/issues/11175
> SDL3: Fixed Cocoa_GL_CreateContext() not returning a context on success

- src/video/SDL_blit.h
- src/video/SDL_blit_0.c
- src/video/SDL_blit_1.c
- src/video/SDL_blit_A.c
- src/video/SDL_blit_N.c
- test/CMakeLists.txt
Original PRs: #11173, #11174, #11177.
> Backport size related PRs to SDL2

- src/SDL_assert.c
- src/video/SDL_video.c
Only message boxes with a single button are supported.
> 3DS: Support simple message boxes (SDL2)

- include/SDL3/SDL_main.h
After discussion on Discord, I've updated the documentation about how the main callbacks API uses threads. I think I got this right, but please look over it to verify.
In particular, is it guaranteed that SDL itself will always push its own events on the main thread on all platforms in the future?
I removed the thread safety notice from `SDL_AppInit` as I'm not sure what "not thread safe" is supposed to mean in that context. As far as I'm aware, this function is only called once by SDL at the very start of the program and never by anyone else.
Should the notes about SDL calling on the main thread be moved to the thread safety section?
> Document main callbacks API thread safety

- src/dynapi/SDL_dynapi.c
- src/dynapi/gendynapi.py
In a later stage, we should probably turn it into a python module that can be imported.
This would be useful for generating [tbd](https://github.com/libsdl-org/SDL_image/issues/438)s and [ymls for llvm-ifs](https://github.com/libsdl-org/setup-sdl/issues/25).
> Refactor gendynapi.py to make it more re-usable

- src/gpu/vulkan/SDL_gpu_vulkan.c
Resolves #11186 
The frame counter was incrementing too soon, causing the in-flight fence index to be incorrect.
> GPU Vulkan: Fix frame counter timing

- src/video/SDL_clipboard.c
Update size value in case where platform uses GetClipboardText(). This should fix clipboard_testClipboardDataFunctions on those platforms.
#8355 ?
> Set size parameter in SDL_GetClipboardData()

- VisualC/pkg-support/cmake/sdl2-config.cmake
When `SDL2main.lib` cannot be found, the component for `SDL2::SDL2` was set to not found instead of `SDL2::SDL2main`.
If possible, it should be cherry-picked to `2.30.x` since it also applies there.
N/A
> [SDL2] Fix VisualC CMake package

- src/video/windows/SDL_windowsmodes.c
workaround the missing DISPLAYCONFIG_DEVICE_INFO_GET_SDR_WHITE_LEVEL enum value
and DISPLAYCONFIG_SDR_WHITE_LEVEL struct.
Fixes: https://github.com/libsdl-org/SDL/issues/11193
Closes:  https://github.com/libsdl-org/SDL/pull/11205
> SDL_windowsmodes.c: Fix MSVC builds against SDKs older than 10.0.17134.0

- src/audio/SDL_wave.c
- src/file/SDL_iostream.c
- src/video/SDL_bmp.c
- test/testshape.c
This fixes two issues similar to SDL_Load/SaveBMP() in https://github.com/libsdl-org/SDL/commit/b766c824bd9c7bc966ddc293beedd5a33b8c6cf2.
SDL_LoadFile() overwrote the error from SDL_IOFromFile() similar to SDL_LoadBMP().
SDL_LoadWAV_IO() didn't set an error if the iostream was NULL similar to SDL_SaveBMP_IO(). (Found inline IO function calls by searching for `_IO(SDL`).
There are two other minor fix commits.
* https://github.com/libsdl-org/SDL/issues/11188 (SDL_LoadFile pointed out by AntTheAlchemist)
> Don't overwrite error in SDL_LoadFile() and set error in SDL_LoadWAV_IO()

- src/process/windows/SDL_windowsprocess.c
- test/childprocess.c
- test/testprocess.c
Standard I/O doesn't work well with non-blocking handles, so make sure any pipes are in blocking mode before launching child processes.
Fixes https://github.com/libsdl-org/SDL/issues/10998
> Make sure stdio handles are in blocking mode

- CMakeLists.txt
Since vita has full posix fs support via newlib, enable posix fsops there.
> PSVITA: enable posix fsops

- CMakeLists.txt
- include/SDL3/SDL_events.h
- include/SDL3/SDL_main.h
- include/SDL3/SDL_main_impl.h
- include/build_config/SDL_build_config.h
- include/build_config/SDL_build_config.h.cmake
- include/build_config/SDL_build_config_android.h
- include/build_config/SDL_build_config_emscripten.h
- include/build_config/SDL_build_config_ios.h
- include/build_config/SDL_build_config_macos.h
- include/build_config/SDL_build_config_windows.h
- include/build_config/SDL_build_config_wingdk.h
- src/SDL.c
- src/SDL_assert.c
- src/SDL_utils.c
- src/audio/SDL_audio.c
- src/audio/SDL_sysaudio.h
- src/camera/SDL_syscamera.h
- src/dynapi/SDL_dynapi.h
- src/file/SDL_iostream.c
- src/joystick/SDL_gamepad_db.h
- src/joystick/SDL_joystick.c
- src/joystick/SDL_sysjoystick.h
- src/thread/pthread/SDL_systhread.c
- src/video/SDL_egl.c
- src/video/SDL_sysvideo.h
- src/video/SDL_video.c
**What's this about?**
Historically, SDL ports for private (NDA'd) platforms have been developed by copy-pasting the public SDL repository into a separate repository, and then making all the platform-specific changes in that copied repo. This has proven difficult to maintain for several reasons:
* Updating the private repos requires carefully merging / rebasing on the public repo while preserving platform-specific commit history.
* Private repos cannot benefit from bug fixes and features in the public repo until an aforementioned merge takes place. As a result, they often end up lagging behind the latest public version.
* Non-platform-specific bug fixes made on the private branches sometimes don't make their way back to the public repository.
In a perfect world we could just have …
> Improve support for private platforms

- src/render/vitagxm/SDL_render_vita_gxm_tools.c
Since color format in renderer(s) changed from using SDL_Color to SDL_FColor, shader params format has to be updated to reflect that
> VITA: fix shader color format

- docs/release_checklist.md
"Do the release" in the checklist has now become:
1. Create a commit bumping the version
2. Create a git tag for this commit
3. Push the tag to libsdl-org/SDL
4. Run the `create-release.py` script on this tag
5. Download the assets, verify, and upload them
> doc: explain build-scripts/create-release.py in the release checklist

- test/testyuv.c
```c
/path/to/SDL-git/test/testyuv.c:242:32: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
242 | static bool run_colorspace_test()
|                                ^
|                                 void
```
> Add `void` to `run_colorspace_test()` function prototype

- .github/workflows/create-test-plan.py
- include/SDL3/SDL_stdinc.h
Because strdup is not ANSI but POSIX, and its prototype might be hidden..
... and re-enable clang-tidy in CI for LoongArch64.
Fixes:  https://github.com/libsdl-org/SDL/issues/11219.
> SDL_stdinc.h: provide a prototype for strdup for __clang_analyzer__ case

- include/build_config/SDL_build_config_xbox.h
Fixes link error for Xbox builds.
> Define SDL_DIALOG_DUMMY in SDL_build_config_xbox.h

- src/thread/windows/SDL_systhread.c
#8849 changed the Windows thread naming code to always run the legacy RaiseException path. It also introduced an exception handler that's meant to stop that exception from being accidentally handled by outside code.
However the new exception handler continues execution for *any* exception that's raised in the brief time that the handler is active. The handler is activated briefly during thread setup. This ends up being a problem if, for example, the main thread starts a new thread and then immediately causes an exception that's meant to be properly handled instead of continued.
In practice in my app that uses LuaJIT it occasionally caused a panic error inside LuaJIT during my app's startup. Here's an example: https://github.com/love2d/love/actions/runs/11376760949/job/31650135750
To avoid …
> windows: fix race condition with exception-based thread naming.

- src/video/openvr/SDL_openvrvideo.h
- src/video/openvr/openvr_capi.h
Also, let SDL handle stdint.h and stdbool.h.
P.S.: Why does SDL_openvrvideo.h override and define `GL_APIENTRY`
and `GL_APICALL` as nothing for windows???
> video/openvr: Avoid type redefinition errors.

- include/SDL3/SDL_hints.h
- src/video/kmsdrm/SDL_kmsdrmsym.h
- src/video/kmsdrm/SDL_kmsdrmvideo.c
- src/video/x11/SDL_x11modes.c
- src/video/x11/SDL_x11modes.h
This has the side effect of providing more descriptive names for KMSDRM displays, if the `drmModeGetConnectorTypeName` functionality is present.
> Allow sorting KMSDRM and X11 displays via the display priority hint

- include/SDL3/SDL_hints.h
The docs for SDL_HINT_AUDIO_FORMAT has a list that's been condensed into a single paragraph. This PR fixes that.
> Fix formatting of docs for SDL_HINT_AUDIO_FORMAT

- src/video/SDL_blit_N.c
The function serves as a 16-bit version of `Blit4to4MaskAlpha`, which now covers a wider range of pixel formats and supports removing the alpha component.
> Refactor Blit_RGB555_ARGB1555 to be more generic

- include/SDL3/SDL_render.h
The flags parameter was removed in 17520c2e6eeac14839ecc510472353bf84a9c985
Removing the mention of flags in the comment.
Also adding parenthesis for `SDL_GetRenderDriver` in the comment.
> SDL_CreateRenderer() comment: Remove mention of flags

- src/video/windows/SDL_windowsevents.c
RawKeyboard incorrectly checks the flag mixing up KeyUp and KeyDown events.
RI_KEY_BREAK indicates key is Up, not Down. Fixes a typo introduced during bool migration https://github.com/libsdl-org/SDL/commit/6fc6e3dc7eb55da70281f945bc11ee382c24e245
> Windows RawKeyboard: fix mixed up KeyUp and KeyDown events

- src/render/direct3d11/SDL_render_d3d11.c
- src/render/direct3d12/SDL_render_d3d12.c
- test/testsprite.c
You can test this using "dxcap -forcetdr"
> Fixed crashes handling D3D11/12 device lost in testsprite

- src/video/openvr/SDL_openvrvideo.c
This also fixes incorrect interpretation of OPENVR_SetupJoystckBasedOnLoadedActionManifest() return value.
> Fixed warning C4456: declaration of 'e' hides previous local declaration

- src/render/vitagxm/SDL_render_vita_gxm_memory.c
- src/render/vitagxm/SDL_render_vita_gxm_tools.c
Somehow it has gone unnoticed, that since implementing texture memory pool in vita gxm render, there was no gpu mem left for message boxes. This fixes it by using PHYCONT mem for them instead.
> VITA: fix SDL_ShowMessageBox by using different memory type

- src/render/vitagxm/SDL_render_vita_gxm_memory.c
- src/render/vitagxm/SDL_render_vita_gxm_tools.c
Somehow it has gone unnoticed, that since implementing texture memory pool in vita gxm render, there was no gpu mem left for message boxes. This fixes it by using PHYCONT mem for them instead.
> VITA: fix SDL_ShowMessageBox by using different memory type (SDL2)

- include/SDL3/SDL_error.h
- include/SDL3/SDL_gpu.h
- include/SDL3/SDL_hints.h
- include/SDL3/SDL_log.h
- include/SDL3/SDL_render.h
- include/SDL3/SDL_stdinc.h
- include/SDL3/SDL_system.h
- include/SDL3/SDL_timer.h
New identifiers, after the 3.1.3 pre-release are currently marked as either 3.1.4 or 3.1.5 or 3.1.6.
The new pre-release version will be 3.1.6.
This commit sets all those marked as 3.1.4 or 3.1.5 to 3.1.6.
> Set version of new identifiers after 3.1.3 release to 3.1.6

- docs/README-wayland.md
- examples/camera/01-read-and-draw/read-and-draw.c
- examples/game/01-snake/snake.c
- examples/pen/01-drawing-lines/drawing-lines.c
- examples/renderer/01-clear/clear.c
- examples/renderer/02-primitives/primitives.c
- examples/renderer/03-lines/lines.c
- examples/renderer/04-points/points.c
- examples/renderer/05-rectangles/rectangles.c
- examples/renderer/06-textures/textures.c
- examples/renderer/07-streaming-textures/streaming-textures.c
- examples/renderer/08-rotating-textures/rotating-textures.c
- examples/renderer/09-scaling-textures/scaling-textures.c
- examples/renderer/10-geometry/geometry.c
- examples/renderer/11-color-mods/color-mods.c
- examples/renderer/14-viewport/viewport.c
- examples/renderer/15-cliprect/cliprect.c
- examples/renderer/17-read-pixels/read-pixels.c
- examples/renderer/18-debug-text/debug-text.c
The new official examples are great, but they use 255 for opaque value, whereas you have proper #defines for int and float.
Let's then use SDL_ALPHA_OPAQUE(_FLOAT), what do you think?
> examples now using SDL_ALPHA_OPAQUE(_FLOAT) for opaque alpha value

- include/SDL3/SDL_gpu.h
- src/gpu/vulkan/SDL_gpu_vulkan.c
Resolves #11107 
There is an edge case as demonstrated by this pseudocode:
```
SDL_GPUBuffer* b;
SDL_GPUTransferBuffer* t;
// Frame 0:
cmdbuf0 = SDL_AcquireGPUCommandBuffer();
SDL_DownloadFromGPUBuffer(b, t);
fence0 = SDL_SubmitGPUCommandBufferAndAcquireFence(cmdbuf0);
// Frame1:
cmdbuf1 = SDL_AcquireGPUCommandBuffer();
/* Do some rendering */
fence1 = SDL_SubmitGPUCommandBufferAndAcquireFence(cmdbuf1); // Defrag happens here
SDL_WaitGPUFence(fence0); // download is in cmdbuf0 so we wait on fence0
void* m = SDL_MapGPUTransferBuffer(t); // Defrag did not happen yet on GPU but transfer buffer points to the new buffer with garbage data
```
The solution is to allocate download buffers on their own dedicated memory blocks so they are not ever defragmented. Download buffers should be …
> GPU Vulkan: Use dedicated allocation for download buffers

- .github/workflows/create-test-plan.py
- cmake/macros.cmake
- docs/README-cmake.md
It's still possible to build SDL by configuring with `-DSDL_NO_UNIX_DESKTOP_SANITY_CHECK=ON`
The error message is:
```console
CMake Error at cmake/macros.cmake:404 (message):
SDL could not find X11 or Wayland development libraries on your system.
This means SDL will not be able to create windows on a typical *nix
operating system.  Most likely, this is not wanted.
On Linux, install the packages listed at
https://github.com/libsdl-org/SDL/blob/main/docs/README-linux.md#build-dependencies
If you really don't need desktop windows, the documentation tells you how
to skip this check.
https://github.com/libsdl-org/SDL/blob/main/docs/README-cmake.md#cmake-fails-to-build-without-x11-or-wayland-support
```
Error on ci:
https://github.com/madebr/SDL/actions/runs/11485462451/job/31965601937#step:23:5 …
> Make building SDL without X11 or Wayland harder

- include/SDL3/SDL_stdinc.h
Allows defining custom `SDL_SINT64_C(c)` and `SDL_UINT64_C(c)` macros. Similar to how you can currently [define custom `SDL_PRIs64`](https://github.com/libsdl-org/SDL/blob/a04fda211c296162301ff09359796b72414aa535/include/SDL3/SDL_stdinc.h#L426-L435), etc macros.
This is useful for getting equivalent binding generation on windows and unix. See our troubles in https://github.com/ppy/SDL3-CS/pull/169.
> Allow defining custom SDL_SINT64_C and SDL_UINT64_C macros

- docs/README-ios.md
From the [docs]:(https://developer.apple.com/documentation/bundleresources/information_property_list/uiapplicationsupportsindirectinputevents)
> In iOS 17 and later, the system defaults to supporting indirect input events, meaning it treats your app the same as if you specify YES.
Added info about it
> README-ios.md: Add info about UIApplicationSupportsIndirectInputEvents on iOS 17

- src/video/cocoa/SDL_cocoaopengl.m
Just putting this in a PR so I can make sure the Mac builders like it.
Fixes #10900.
> cocoa: Make sure GL context destruction happens on the main thread.

- .github/workflows/generic.yml
- android-project/app/src/main/AndroidManifest.xml
- examples/game/01-snake/snake.c
After this change, `SDL_build_config.h` (and `SDL_revision.h`) generated by CMake will be in the GitHub artifacts.
This pr also:
- adds a null pointer check to the snake example
- add a disabled permission to the Android manifest to access the internet. This is a requirement for SDL3_net.
> ci: upload build config headers

- src/video/openvr/SDL_openvrvideo.c
- make all of function pointers static
- make EGLint context_attribs[] static
- comment out unused function pointer ov_wglGetCurrentContext
- remove unused SDL_DisplayMode openvr_dm_default
- move SDL_VideoDisplay openvr_vd_default to OPENVR_VideoInit()
context and eliminate its C99 initializers
- replace atoi() calls with SDL_atoi()
- replace atof() calls with SDL_atof()
> video/openvr: minor clean-up:

- src/filesystem/posix/SDL_sysfsops.c
Return `false` instead of `-1`.
> SDL_EnumerateDirectory(): (posix) Fix return value when directory is invalid.

- include/SDL_events.h
- include/SDL_gamecontroller.h
Add documentation for when GAMEPAD_ADDED events are added to the event queue.
Unlike SDL 3, new events are not generated during AddMapping* functions. You have to call AddMapping* before SDL_Init if you rely on CONTROLLERDEVICEADDED events.
Backport of https://github.com/libsdl-org/SDL/pull/11286
https://discourse.libsdl.org/t/deviced-added-events-for-devices-plugged-in-at-game-start/55039
> docs: Explain events for already plugged in controllers

- src/filesystem/SDL_filesystem.c
On Windows it was already implemented.
> SDL_CreateDirectory(): directory tree creation for absolute paths for non-Windows platforms

- src/gpu/metal/SDL_gpu_metal.m
Fixes a variety of Metal version availability warnings, mostly for pixel formats. Instead of a texture format translation array, we're now using a translation function because guarding for `@available` requires runtime checks.
This also adds an OS version check (macOS 10.13+, iOS/tvOS 13.0+) to `METAL_PrepareDriver` so that old OS versions can't proceed with creating a GPU Metal driver. Annoyingly, we still have to add `if @available` guards for older OS versions to quiet the warnings.
> GPU: Add Metal availability checks

- include/SDL3/SDL_vulkan.h
Add the lines
```cpp
#undef VK_DEFINE_HANDLER
#undef VK_DEFINE_NON_DISPATCHABLE_HANDLE
```
At the end of `SDL_vulkan.h` to allow `vulkan/vulkan.h` to define `VK_NULL_HANDLE` (and certainly other stuff as well) properly for C++ and `vulkan/vulkan.hpp`.
This change was tested using https://github.com/feelamee/sdl-bug-with-vulkan-cpp-api (for checking compilation errors) and SDL's testvulkan on x86-64 archlinux, and compiled with gcc.
Fix to issue #11328
> Fix issue #11328

- VisualC/examples/audio/01-simple-playback/01-simple-playback.vcxproj
- VisualC/examples/audio/02-simple-playback-callback/02-simple-playback-callback.vcxproj
- VisualC/examples/audio/03-load-wav/03-load-wav.vcxproj
- VisualC/examples/camera/01-read-and-draw/01-read-and-draw.vcxproj
- VisualC/examples/game/01-snake/01-snake.vcxproj
- VisualC/examples/game/02-woodeneye-008/02-woodeneye-008.vcxproj
- VisualC/examples/game/03-infinite-monkeys/03-infinite-monkeys.vcxproj
- VisualC/examples/generate.py
- VisualC/examples/pen/01-drawing-lines/01-drawing-lines.vcxproj
- VisualC/examples/renderer/01-clear/01-clear.vcxproj
- VisualC/examples/renderer/02-primitives/02-primitives.vcxproj
- VisualC/examples/renderer/03-lines/03-lines.vcxproj
- VisualC/examples/renderer/04-points/04-points.vcxproj
- VisualC/examples/renderer/05-rectangles/05-rectangles.vcxproj
- VisualC/examples/renderer/06-textures/06-textures.vcxproj
- VisualC/examples/renderer/07-streaming-textures/07-streaming-textures.vcxproj
- VisualC/examples/renderer/08-rotating-textures/08-rotating-textures.vcxproj
- VisualC/examples/renderer/09-scaling-textures/09-scaling-textures.vcxproj
- VisualC/examples/renderer/10-geometry/10-geometry.vcxproj
- VisualC/examples/renderer/11-color-mods/11-color-mods.vcxproj
- VisualC/examples/renderer/14-viewport/14-viewport.vcxproj
- VisualC/examples/renderer/15-cliprect/15-cliprect.vcxproj
- VisualC/examples/renderer/17-read-pixels/17-read-pixels.vcxproj
- VisualC/examples/renderer/18-debug-text/18-debug-text.vcxproj
Removes the wildcard from `<ClCompile>`  to prevent visual studio warnings. Instead, the C source file name is explicitly specified when generating the project files.
- https://github.com/libsdl-org/SDL/pull/11255#issuecomment-2445169931
> Explicity specify C source file in VS examples

- include/SDL3/SDL_gpu.h
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
- src/gpu/SDL_gpu.c
- src/gpu/SDL_sysgpu.h
- src/gpu/d3d11/SDL_gpu_d3d11.c
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
Sometimes applications might want to cancel a command buffer without executing any of the commands that have been recorded, for example if there is a lot of backpressure and SDL_AcquireGPUSwapchainTexture fills in the swapchain texture handle with NULL. This should allow for improved application structure, because applications can bail out of submitting unnecessary work to the GPU.
This introduced an edge case on Vulkan where cancelling a command buffer could cause initial layouts it modified to get out of sync. Now we execute a memory barrier to transition the texture to its default layout when it is created.
Needs a Metal implementation before merge. This might also be a good opportunity to look at the Metal presentation timing - I think we should be bailing out of …
> GPU: Add SDL_CancelGPUCommandBuffer

- src/video/khronos/vulkan/vulkan_metal.h
When targeting versions 10.13, you will receive this warning/error:
In both SDL_cocoavulkan.m and SDL_cocoavideo.m:
SDL/src/video/khronos/vulkan/vulkan_metal.h:92:32: 'MTLSharedEvent' is only available on macOS 10.14 or newer
This is the last remaining issue that will cause CI/CD to fail when we set the target to older apple platforms.
See https://github.com/libsdl-org/SDL/issues/11371
> Supress Metal warning when compiling against macOS 10.11-10.13

- .github/workflows/create-test-plan.py
- .github/workflows/release.yml
- docs/README-cmake.md
- docs/README-macos.md
Sets minimum OS version when building for macOS, iOS, and tvOS
See: https://github.com/libsdl-org/SDL/issues/11332 and https://github.com/libsdl-org/SDL/issues/11333
This sets the minimum version for the following platforms rather than using the newest:
macOS to 11.0 or higher (currently 14)
iOS to 13.0 or higher (currently 17)
tvOS to 13.0 or higher (currently 17)
Using the values suggested at https://github.com/libsdl-org/SDL/issues/11332#issuecomment-2438953930
This has revealed a few issues with SDL GPU on older iOS/tvOS versions; already discussed in https://github.com/libsdl-org/SDL/issues/11333 and directly with TheSpyDog
> Add version info when building CI/CD for apple platforms

- src/gpu/vulkan/SDL_gpu_vulkan.c
The CHECK_VULKAN_ERROR_AND_RETURN macro in SDL_gpu_vulkan.c was missing a return statement. I haven't tested this, but the name of the macro and how it's used indicates it should return, so this seems like a bug
> Add return to CHECK_VULKAN_ERROR_AND_RETURN macro

- include/SDL3/SDL_hints.h
- src/events/SDL_mouse.c
A one-liner fix. Also fix formatting in the doc comments.
> Refresh cursor visibility when relative-mode hint is set

- test/CMakeLists.txt
Without this change using the `-j` flag while building the tests causes errors. 
The PSPSDK has been updated to allow for setting the target directory of EBOOT.PBP file. We can use this to make it possible to use the `-j` flag while building them. Right now this still causes errors.
I'll see if I can do the same for SDL3
> PSP: Allow building tests in parallel

- examples/CMakeLists.txt
I wasn't aware of it, but the examples building contains a copy of some of the code from the tests directory which was causing issues for parallel builds. This fixes this
#11390
> PSP: Fix building examples in parallel

- src/video/SDL_video.c
Calling the functions with a `NULL` argument causes a segfault.
This commit adds a `NULL` check to the functions.
> SDL_GetDisplayForPoint(), SDL_GetDisplayForRect(): Check argument for NULL.

- docs/README-migration.md
- include/SDL3/SDL_video.h
- src/video/SDL_video.c
This commit does the following:
- SDL_GetClosestFullscreenDisplayMode(): Renames parameter `mode` to `closest`.
- Inside SDL_GetClosestFullscreenDisplayMode(): Checks, if the parameter is NULL at the beginning of the function.
(It doesn't really make sense to call the function without a valid parameter. It just returns true/false if there is/isn't a closest mode, but doesn't set any.)
- README-migration.md: SDL_GetClosestFullscreenDisplayMode() was listed as removed. This commit deletes this entry.
> SDL_GetClosestFullscreenDisplayMode(): Rename parameter `mode` to `closest`

- include/SDL3/SDL_iostream.h
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
- src/file/SDL_iostream.c
This adds the following convenience functions:
- `bool SDL_SaveFile_IO(SDL_IOStream *src, const void *data, size_t datasize, bool closeio);`
- `bool SDL_SaveFile(const char *file, const void *data, size_t datasize);`
They work similarly to their "Load" counterparts.
Closes #11421
> Add SDL_SaveFile and SDL_SaveFile_IO functions

- include/SDL3/SDL_stdinc.h
SDL_PRI**s**64 tried to default to PRI**s**64 but the correct macro is PRI**d**64.
SDL_PRIs32 already correctly uses PRId32. I tried to use PRIs64 and found SDL 2 and 3 also try to use it.
> Fix SDL_PRIs64 to use standard PRId64

- test/testautomation_keyboard.c
The test currently fails if the system's keyboard layout does not bind the `A` scancode to the `A` key. This, assuming all keyboard layouts have the `space` scancode bound to the `space` key, fixes it.
(I also really want to have all the tests to go green on my machine without having to change my keyboard layout!)
Fixes #11396
> testautomation keyboard: use `space` instead of `a`

- CMakeLists.txt
The SDL_VERSION_... variables are uninitialized.
SDL3_VERSION is initialized by the project() command.
Visible in CMake config output.
Alternative: PROJECT_VERSION
> Fix SDL_REVISION_CENTER

- .github/workflows/create-test-plan.py
Added PowerPC32 to the list of platforms to make artifacts from
I didn't add PPC to the list of plataforms that tests are run on since this also isn't the case for PPC64LE
No issues relating to this as far as I know
> Make PPC32 Artifacts

- src/events/SDL_mouse.c
- src/events/SDL_mouse_c.h
closes #11422
@Slartibarty can you verify if this fix works for your game?
> fix erroneous mouse motion when alt-tabbing in CS2

- src/video/windows/SDL_windowsmodes.c
WIN_AddDisplay asserted that the returned index is the expected next one in the list. This can be an unexpected number when displays are add and removed in a batch (eg, Remote Desktop disconnect and reconnect). Instead always just make use of the next index, even if it is not the expected next index value. 
This fixes issue #9105
> Always Use Next Display Index

- src/events/SDL_mouse.c
- src/events/SDL_mouse_c.h
- src/video/windows/SDL_windowsmouse.c
closes #11412 
includes the following quirks:
- all calculations and truncation being done in 16.16 fixed point
- octagonal speed normalization using logical and bitwise operations only
- multiplier being averaged with the previous value if speed is increasing
excludes the following quirk:
- exact match of output quantization patterns (SDL apps will always receive float events)
https://github.com/user-attachments/assets/59c112b4-7e57-431b-9daf-366b26019105
Though to be honest, I personally would still suggest removing the hint altogether.
Philosophically I don't think it should be SDL's job to emulate system acceleration under relative mode in the first place, if a developer really wants to emulate it they can use warping or just implement their own scaling. 
Practically, there are also …
> fix windows mouse relative system scale

- src/video/cocoa/SDL_cocoawindow.m
Sequoia needs the window briefly made key when it comes out of fullscreen before minimizing it, so the minimize request is now deferred to later in the fullscreen switching function. This also properly restores fullscreen on the restoration of key status in the case where a fullscreen window is requested to minimize after losing key status, but is never actually minimized.
Fixes #11494
> cocoa: Fix minimizing fullscreen windows on Sequoia

- src/render/SDL_render.c
The debug text font is less legible when scaled linearly.
Before:
Afer:
> render: use nearest pixel scaling for debug text

- CMakeLists.txt
- src/locale/psp/SDL_syslocale.c
This makes SDL_GetPreferredLocales work on the PSP in SDL3.
> PSP: Add locale support

- examples/CMakeLists.txt
- examples/game/04-bytepusher/README.txt
- examples/game/04-bytepusher/bytepusher.c
I wrote a BytePusher VM implementation and thought it could be a good example. See here for more information about BytePusher and example programs: https://esolangs.org/wiki/BytePusher
It's written in C99. I don't know if examples are required to be C89, but I can fix that if you're interested
edit: Looks like they are, and I forgot to update the Visual Studio projects. Anyway, let me know if you want this and I'll fix it
> Add BytePusher example

- src/gpu/d3d12/SDL_gpu_d3d12.c
`CreateEventEx` is unavailable in Windows XP. The provided solution was sourced from the WASAPI backend, which had to address the same problem.
According to [official](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createeventa) [documentation](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createeventexa), both calls should be functionally identical, with calls to `CreateEvent` implicitly creating events with the `EVENT_ALL_ACCESS` access right.
This change alone is not enough to get Windows XP support working again: the usage of `CreateWaitableTimerExW` in the Windows `SDL_systimer.c` currently prevents any executables from running, due to the function being introduced in Windows Vista. If the relevant code is removed, however, …
> Avoid usage of `CreateEventEx` in D3D12 GPU backend.

- src/video/SDL_fillrect.c
Hello, I work on pygame-ce, and I've noticed in profiling various games that Surface.fill(), our Python interface to SDL_FillRect, is a significant part of runtime for most pygame-ce games (most pygame-ce games are software rendered).
I tested out fill() at various surface resolutions with a 32 bit surface and found that the performance of this function is very spiky. I found that surfaces with widths divisible by 16 had the best performance by far.
Looking into the SSE FillRect implementation I found that the function has to do a lot of work to adjust into a 16 byte aligned state, run several 64 byte chunks, then finish any extra pixels at the end. The algorithm considers each row separately (as you need for fills that take a smaller region of the surface). However, there is a common …
> Optimize SDL_FillSurfaceRect(2|4)SSE for "full surface fills"

- src/test/SDL_test_common.c
This fixes some flags not printing in testwm.c
> Add missing SDL_WindowFlags to SDL_test_common.c

- src/video/directfb/SDL_DirectFB_render.c
DirectFB: fix DirectFB_SetTextureScaleMode() declaration
Fixes:
```
src/video/directfb/SDL_DirectFB_render.c: In function ‘DirectFB_CreateRenderer’:
src/video/directfb/SDL_DirectFB_render.c:1153:35: error: assignment to ‘void (*)(SDL_Renderer *, SDL_Texture *, SDL_ScaleMode)’ from incompatible pointer type ‘void (*)(void)’ [-Wincompatible-pointer-types]
1153 |     renderer->SetTextureScaleMode = DirectFB_SetTextureScaleMode;
|                                   ^
```
> [SDL2] DirectFB: fix DirectFB_SetTextureScaleMode() declaration (fixes gcc-14.x compile)

- include/SDL3/SDL_audio.h
- src/audio/SDL_audiocvt.c
> audio: Allow channel maps to specify -1 to mute a channel.

- src/audio/SDL_audio.c
Assign the length of audio buffer after obtaining the audio buffer.
See https://github.com/libsdl-org/SDL/issues/11122#issuecomment-2484053860
This resolves #11122
> [SDL2] Fix order of events in case audio buffer size changes

- src/dynapi/gendynapi.pl
The objfiles of different builds show various differences in the calls to SDL_DYNAPI_entry elements. This is generated dynamically by gendynapi.pl which uses an unordered opendir/readdir pair. To make the build reproducible and thereby e.g. debugging easier change this to be used in an ordered fashion.
https://github.com/libsdl-org/SDL/issues/11565
> dynapi: order for a reproducible build

- include/SDL3/SDL_hints.h
Hello,
"gpu" value is currently missing in docs of "SDL_HINT_RENDER_DRIVER". I put it just before "software" as it looks like it's the correct order.
See issue #11572
Have a good day
> docs: added "gpu" to the list of possible values of SDL_HINT_RENDER_DRIVER in SDL_hints.h

- include/SDL3/SDL_surface.h
Fixed an inaccuracy in the return parameter information in the SDL_ConvertPixels function
> Fixed an inaccuracy in the return parameter information in the SDL_ConvertPixels function

- src/file/io_uring/SDL_asyncio_liburing.c
- SDL_asyncio_liburing.c: replace size_t casts on pointers with intptr_t
sizeof(size_t) might not be the same as sizeof(intptr_t). see, e.g. the
CHERI case: https://github.com/libsdl-org/SDL/pull/4552
- SDL_asyncio_liburing.c: replace __kernel_time64_t use with SDL's Sint64
__kernel_time64_t might not be available and Sint64 simply is enough for
our use here.
> SDL_asyncio_liburing.c cleanups

- src/video/windows/SDL_windowsevents.c
- src/video/windows/SDL_windowsevents.h
- src/video/windows/SDL_windowsrawinput.c
Currently, the rawinput thread incorrectly spreads the timestamps over idle time if the poll interval is less than 100ms, and abruptly switches to lumping all accumulated inputs to happen simultaneously if it exceeds 100ms. 
This means that any game which implements retroactive event handling based on timestamps will jarringly snap between the two polar opposite extremes of incorrect behaviour.
This PR replaces the arbitrary 100ms threshold with logic based on measuring the idle start and end time. 
If the thread idled for more than 125000 nanoseconds, it is considered to have not had any input in its queue before it entered idle, and the events are spread over the interval between thread wake-up and pump finish, with the final input aligned to the pump finish time. 
If the thread idled …
> Fix rawmouse wrong timestamp

- src/gpu/vulkan/SDL_gpu_vulkan.c
Our Vulkan driver was assuming the existence of this physical device feature, but we need to explicitly enable it. This feature is universally supported on desktop, and is supported by 86% of Android devices (which is very high by Android standards).
Resolves https://github.com/libsdl-org/SDL/issues/10735
> GPU: Vulkan requires drawIndirectFirstInstance feature

- Android.mk
- CMakeLists.txt
- VisualC-GDK/SDL/SDL.vcxproj
- VisualC-GDK/SDL/SDL.vcxproj.filters
- VisualC/SDL/SDL.vcxproj
- VisualC/SDL/SDL.vcxproj.filters
- include/SDL3/SDL_dialog.h
- src/dialog/SDL_dialog.c
- src/dialog/SDL_dialog.h
- src/dialog/android/SDL_androiddialog.c
- src/dialog/cocoa/SDL_cocoadialog.m
- src/dialog/haiku/SDL_haikudialog.cc
- src/dialog/unix/SDL_portaldialog.c
- src/dialog/unix/SDL_portaldialog.h
- src/dialog/unix/SDL_unixdialog.c
- src/dialog/unix/SDL_zenitydialog.c
- src/dialog/unix/SDL_zenitydialog.h
- src/dialog/windows/SDL_windowsdialog.c
- I've added a new function to create dialogs with properties: SDL_ShowFileDialogWithProperties. There is only one function for all dialog types; I've added an enum called SDL_FileDialogType instead.
- The old functions are now wrappers around SDL_ShowFileDialogWithProperties. This significantly simplifies the implementation on multiple platforms, which basically just regrouped all functions into one with different parameters.
- I've added three new options: setting the dialog's title, the accept button's label and the cancel button's label.
- I've fixed a few bugs and cleaned up the code a bit:
- Zenity does, in fact, support modal dialogs. One just has to check the extended help for more options and discover the amazing(-ly poorly documented) `--attach` option. The only issue is that it …
> Add SDL_ShowFileDialogWithProperties with some more options

- build-scripts/build-web-examples.pl
- examples/template-category.html
- examples/template-homepage.html
- examples/template.css
- examples/template.html
Hello,
Following conversation in #10350 ; here are some changes:
- added CSS similar to the wiki
- added an homepage for project
- added a page for each category
- modified the example page: added a sidebar (I put on the right side, I thought it was less distracting that way), fixed source/console buttons that were fixed and prevented the page from scrolling
- added a simple breadcrumb on pages
I've tested the changes on Safari/Chrome/Firefox (and also on Safari's iPhone) in dark and light modes. I apologise in advance for my Perl code (I haven't wrote any perl in my life) — but that was easier to work with real data than on HTML mockups.
The big missing thing is to generate images for all examples, and make the HTML use those images instead of the placeholder ones (that's why the PR is …
> WIP: Examples: work on web output

- examples/template.html
Hello,
This follows previous PR #11581 ; I just realised I've missed a `max-width` on the canvas to make sure it still displays nicely on mobile, sorry!
Before this PR:
After this PR:
> examples: web output: fix canvas size for small screens

- include/SDL3/SDL_gpu.h
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
- src/gpu/SDL_gpu.c
- src/gpu/SDL_sysgpu.h
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
The current frame submission logic allows 3 frames in flight before AcquireSwapchainTexture blocks or returns false. Some users have been reporting high visual latency with vsync on as a result of this, which is expected.
First, this PR adds a function to make this behavior configurable. The client can choose a value between 1 and 3 to make a tradeoff between visual latency and throughput. Secondly, our default now targets the happy medium, which is 2.
> GPU: Add SetGPUAllowedFramesInFlight

- include/SDL3/SDL_render.h
- src/render/SDL_render.c
Closes #11279 
This is the lowest-possible overhead API for planar texture copy, leaving the responsibility of calculating the points entirely to the users, allowing them to perform flips, stretches, shears, and rotations by calculating the basis vectors directly.
```c
bool SDL_RenderTextureAffine(
SDL_Renderer *renderer, 
SDL_Texture *texture,
const SDL_FRect *srcrect,
const SDL_FPoint *origin,
const SDL_FPoint *right,
const SDL_FPoint *down
)
```
Type | Name | Description
-- | -- | --
SDL_Renderer * | renderer | the renderer which should copy parts of a texture.
SDL_Texture * | texture | the source texture.
const SDL_FRect * | srcrect | a pointer to the source rectangle, or NULL for the entire texture.
const SDL_FPoint * | origin | a pointer to a point indicating the location the …
> add SDL_RenderTextureAffine

- src/video/SDL_sysvideo.h
- src/video/SDL_video.c
- src/video/uikit/SDL_uikitvideo.m
- src/video/uikit/SDL_uikitviewcontroller.h
- src/video/uikit/SDL_uikitviewcontroller.m
Text input in SDL's iOS implementation is directly activated by requesting the hidden `UITextField` to become first responder. Once it becomes first responder, a software keyboard is shown if there are no hardware keyboard is attached, and `textFieldTextDidChange` events are raised whenever text is inputted by a hardware/software keyboard.
SDL has been doing the `becomeFirstResponder`/`resignFirstResponder` calls in the `ShowScreenKeyboard`/`HideScreenKeyboard` path. These paths are controlled by the `AutoShowingScreenKeyboard()` function, which returns false when a hardware keyboard is attached (unless the `SDL_HINT_ENABLE_SCREEN_KEYBOARD` hint is set to 1), therefore the text fields never become first responder and no text input is allowed by hardware keyboard regardless of whether …
> Refactor iOS text input activation to better work with hardware keyboards

- src/video/wayland/SDL_waylandmessagebox.c
When no extra buttons are passed to zenity with `--question --switch`
arguments it fails to show anything, however, SDL3 still reports
success. To handle this case, we pass an additional "OK" button.
The double quotes were passed literally to the zenity arguments which
resulted in the message box displaying literal `""` when no text was
given. The empty string is more logical in this case, e.g., the empty
title results in the message box having lesser height.
> Wayland message box: improve zenity argument handling

- src/gpu/SDL_gpu.c
- src/gpu/SDL_sysgpu.h
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
- SDL_ClaimWindowForGPUDevice should set an error on failure
- define `EXPAND_ARRAY_IF_NEEDED` once (remove duplicate in vulkan driver)
- make GPU macros function-like by doing `do { ... } while (0)`
/cc @thatcosmonaut
> gpu: SDL_ClaimWindowForGPUDevice should set error on failure + function-like macro's

- src/dialog/unix/SDL_zenitydialog.c
SDL process is using `posix_spawnp` which already does the path lookup
so additional indirection via `env` is unnecessary
Simplifies logic of spawning the zenity process by avoiding allocations
of static strings
Introduce `const` where appropriate
SDL properties passed to the `SDL_Zenity_ShowFileDialogWithProperties`
may be destroyed/modified immediately upon the function return.
Therefore, we must copy all the strings and structures passed via
pointers; otherwise, the `SDL_ZenityFileDialog` thread attempting to
read them will cause data race.
N/A
> zenity dialog: fix data race and reduce number of allocs

- src/video/wayland/SDL_waylandvideo.c
Some compositors [may not implement commit-timing-v1 in addition to fifo-v1](https://invent.kde.org/plasma/kwin/-/merge_requests/6474), at least not immediately, and [Mesa doesn't require commit-timing for FIFO behavior](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/32556#note_2694119).
Only check for fifo-v1 to enable Wayland by default, as that should be enough to get the desired behavior (no pacing with dodgy frame callbacks or risk of blocking forever).
Quick check with @misyltoad that this is ok?
> wayland: Only require fifo-v1 for Wayland by default

- include/SDL3/SDL_hints.h
- src/audio/alsa/SDL_alsa_audio.c
- src/audio/alsa/SDL_alsa_audio.h
Fixes https://github.com/libsdl-org/SDL/issues/8577
> Added support for ALSA dmix audio output (thanks @sylware!)

- include/SDL3/SDL_video.h
- src/events/SDL_windowevents.c
- src/video/SDL_sysvideo.h
- src/video/SDL_video.c
- src/video/cocoa/SDL_cocoawindow.h
- src/video/cocoa/SDL_cocoawindow.m
- src/video/dummy/SDL_nullvideo.c
- src/video/emscripten/SDL_emscriptenvideo.c
- src/video/haiku/SDL_bwindow.cc
- src/video/offscreen/SDL_offscreenwindow.c
- src/video/openvr/SDL_openvrvideo.c
- src/video/qnx/SDL_qnxvideo.c
- src/video/wayland/SDL_waylandwindow.c
- src/video/wayland/SDL_waylandwindow.h
- src/video/windows/SDL_windowsevents.c
- src/video/windows/SDL_windowswindow.c
- src/video/windows/SDL_windowswindow.h
- src/video/x11/SDL_x11events.c
- src/video/x11/SDL_x11window.c
- src/video/x11/SDL_x11window.h
- test/testautomation_video.c
It is not uncommon for clients to redundantly set the window size and position, either as a holdover from an SDL 1 port, when this was required, or due to any window state change triggering a universal update function that sets all window state, even if unnecessary (e.g. always calling SDL_SetWindowSize(), even if the window is fullscreen). Historically, these clients expect that their behavior won't override the base window state, which is an assumption that the windowing changes in SDL 3 broke by caching size and position changes that can't be applied immediately.
This change drops size and position requests when the window is in the maximized and fullscreen states (fullscreen-desktop windows will be repositioned, but the non-fullscreen floating position will not be overwritten), which …
> video: Drop size and position requests for windows in a fixed size/position state

- src/dialog/SDL_dialog_utils.c
- src/dialog/windows/SDL_windowsdialog.c
This fixes two bugs with file filters for dialogs on Windows. The details of the bugs are in the commit messages:
- convert_filters: For some obscure reason I can't remember, I had made it so the suffix would be added only if the filter list was empty. That isn't the expected behavior and caused a mishandling of memory on Windows, which requires a two-null-bytes suffix.
- clear_filt_names: The Windows implementation of dialogs use the Win32 API, which expects the file filters to have null bytes as separator, and two null bytes at the end of the filter list. To help with string manipulation, the internal code uses 0x01 bytes instead of null bytes, and converts all 0x01 bytes into null bytes at the last moment. If someone decides to put two consecutive 0x01 bytes in their filter names, the …
> Fix dialog filters on Windows

- src/gpu/d3d12/SDL_gpu_d3d12.c
The initial approach for D3D12 staging descriptors was to generate two massive heaps of view and sampler staging descriptors up front. This was the cause of the D3D12 backend's incredibly high memory usage.
The revised approach is to start with a pool of 1024 staging descriptors per heap type. When all of these are used up, the pool expands with another heap of 1024 staging descriptors. If a resource is destroyed, its index in the descriptor heap is returned to the pool so another resource can use it.
I think the results speak for themselves:
Before: ![before](https://github.com/user-attachments/assets/65cc83d2-0d5b-48d0-95ca-2a1bcb2568df)
After: ![after](https://github.com/user-attachments/assets/17187b5a-d199-4f7e-a1d4-7f2f9b315164)
This patch also allows the resource bind function to …
> GPU: Optimize usage of D3D12 staging descriptors

- include/SDL3/SDL_gpu.h
Fixed an inaccuracy in the documentation for SDL_CancelGPUCommandBuffer
> Fixed an inaccuracy in the documentation for SDL_CancelGPUCommandBuffer

- include/SDL3/SDL_surface.h
Fixed an inaccuracy in the documentation for SDL_ConvertPixelsAndColorspace
> Fixed an inaccuracy in the documentation for SDL_ConvertPixelsAndColorspace

- src/video/x11/SDL_x11video.h
- src/video/x11/SDL_x11xinput2.c
Slave pointer devices can seemingly lag behind the master for some reason, so use the master pointer coordinates for absolute motion.
Master events are now only filtered out on the pen path to avoid duplicates.
Fixes #11646
> x11: Use the master pointer device for absolute motion

- src/video/windows/SDL_windowswindow.c
Use hidden uxtheme.dll and user32.dll functions for darkmode instead of using DwmSetWindowAttribute.
Fixes context menu on title bar.
I couldn't find function to get Windows build number so I import RtlGetVersion from ntdll to get it.
#11535
> Improve Win32 darkmode and fix title bar's context menu

- include/SDL3/SDL_hints.h
- src/events/SDL_mouse.c
- src/events/SDL_mouse_c.h
- src/video/windows/SDL_windowsevents.c
- src/video/windows/SDL_windowswindow.c
- src/video/windows/SDL_windowswindow.h
This commit does the following:
- add logic in the `WM_MOUSEMOVE` case of the Window to conditionally call `WIN_UpdateClipCursor` upon receiving cursor motion if SDL is expecting the mouse to be clipped in some way (Fixes #7890)
- remove Windows-specific periodic refresh of cursor clipping and its `SDL_HINT_MOUSE_RELATIVE_CLIP_INTERVAL` hint (superceded by the above bullet point)
- streamline the processing logic within `WIN_UpdateClipCursor` for better readability of each branch, and avoid calling the Platform API until it is absolutely necessary.
- move `relative_mouse_center` field from Windows-specific per-window `SDL_WindowData` to the global `SDL_Mouse` struct, and the corresponding hint callbacks to `SDL_mouse.c` instead of `SDL_windowswindow.c`
relevant commits: …
> streamline cursor clipping logic on windows

- include/SDL3/SDL_events.h
- src/events/SDL_events.c
- src/events/SDL_mouse.c
- src/events/SDL_mouse_c.h
- src/video/SDL_sysvideo.h
- src/video/SDL_video.c
- src/video/windows/SDL_windowsevents.c
- src/video/windows/SDL_windowsrawinput.c
- src/video/windows/SDL_windowsrawinput.h
- src/video/windows/SDL_windowsvideo.c
Proof of concept that closes #7674. Other platforms can be implemented on a rolling basis but shouldn't be a blocker for merge.
> add alternate raw mouse motion events with windows implementation

- CMakeLists.txt
This pr removes EXTRA_CFLAGS as we have a new cmake ported by myself on [ps2sdk repository](https://github.com/ps2dev/ps2sdk/blob/master/samples/ps2dev.cmake) superceeds #11027
> [PS2SDK]: Remove EXTRA_CFLAGS.

- src/gpu/d3d12/SDL_gpu_d3d12.c
This PR removes the hardcoded TRIANGLE primitive topology type from D3D12 pipeline creation and replaces it with a lookup into a new translation array.
Confusingly, D3D12 has "primitive topology" and "primitive topology type" as different types. The latter represents the general class of primitive topologies that a pipeline can support, and the former is the specific topology used for a given set of draw calls.
Resolves https://github.com/libsdl-org/SDL/issues/11680
> GPU: Fix non-triangle D3D12 primitive topology types

- include/SDL3/SDL_assert.h
Fix missing parens in `#if defined`. The previous code doesn't match SDL style and some binding generators don't support it
> Fix missing parens in preprocessor defined op

- test/testautomation_pixels.c
It seems created surfaces are ARGB8888 format on both BE and LE, therefore BGRA32 failed.
> Fix testautomation pixels_saveLoadBMP big endian issue

- include/SDL3/SDL_asyncio.h
Removed references to non-existent method SDL_GetAsyncIOTaskResult
> Removed references to non-existent method SDL_GetAsyncIOTaskResult

- src/gpu/metal/SDL_gpu_metal.m
When creating a GPU device in debug mode, we should enable Metal validation like we do for Vulkan and D3D12. This native validation helps catch errors that are difficult or impossible to detect from SDL's side (like malformed shaders). Unlike other APIs, Metal's validation layers are enabled via an environment variable that must be set before device creation.
> GPU: Enable Metal validation in debug mode

- src/video/windows/SDL_windowsclipboard.c
Calling `SDL_GetClipboardData` on **Windows** may generate an incorrect bitmap file header for uncompressed bitmaps. This issue arises because SDL3 sometimes populates the `BITMAPFILEHEADER` with incorrect `bfOffBits` values, leading to corrupted bitmaps.
This PR addresses the problem by recalculating the pixel offset more accurately in the `WIN_GetPixelDataOffset` function, considering the presence of a palette array in the case of indexed bitmaps. Additionally, it corrects the usage of `biSizeImage`, taking into account that this [value can sometimes be zero](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-bitmapinfoheader) for uncompressed RGB bitmaps.
To test this, compile and run the code on Windows. Take a screenshot and press the `V` key, then check the …
> Fix `SDL_GetClipboardData()` for bitmap on Windows (SDL3). 

- src/events/SDL_mouse.c
- src/events/SDL_mouse_c.h
We'll track the click count separately for each input source, and the click distance is calculated using a point on an infinite plane that is pushed around by mouse motion deltas, unclamped by the window edge.
This should improve things for https://github.com/libsdl-org/SDL/issues/5843
> Fixed mouse click count for relative mode and multiple mice

- src/thread/pthread/SDL_systhread.c
Set thread name on Android the same way as we do on Linux.
Acording to Bionic source code this function is available since 2013 [1] and hase the same signature.
[1] https://android.googlesource.com/platform/bionic/+/2a1bb4e64677b9abbc17173c79768ed494565047
/
> Use `pthread_setname_np` also on Android

- include/SDL3/SDL_gpu.h
- src/gpu/metal/SDL_gpu_metal.m
This PR adds documentation for the OS/driver/hardware requirements for each of the SDL_GPU backends. This should hopefully clear up a lot of ambiguity around "is this device supported" and gives developers something concrete to use for their own system requirements and support.
At runtime, to ensure the device meets SDL_GPU driver's system requirements, Vulkan and D3D12 perform a series of feature support queries during the device creation process. However, for Metal, we only performed a single OS version check. This allowed apps to get pretty far into their lifecycle on unsupported devices before they crashed by using an unsupported feature.
To fix this, I've added hardware support queries as early as possible (right after MTLDevice creation) to detect if the app is running on an …
> GPU: Document system requirements, add upfront Metal hardware support checks

- src/dialog/windows/SDL_windowsdialog.c
This fixes memory management with the title of the dialog.
**Note:** I've noticed that Windows suffers from the same issue as the Unix implementation did; the parameters are not copied over from the properties before passing them to a new thread, making it necessary to track their lifetime until the callback is invoked. I did not fix that yet.
Fixes #11661
> Fix memory management for Windows dialog title

- src/dialog/SDL_dialog_utils.c
#9856 introduced an `nfilters` parameter for the filetype filter count, but missed a check where some code tests for the end of the array via a legacy "is the next item null?". This can cause the windows filetype filter string to be generated malformed, as the conversion function reads beyond the range requested by `nfilters`, and this malformed output can in turn cause garbage text to appear in the filetype dropdown menu. This out-of-bounds read could also potentially cause a segfault if the input array doesn't have at least N+1 elements.
This PR replaces the legacy nullcheck with the appropriate check against `nfilters`, preventing said garbage text from appearing.
Didn't see an existing issue, and it was such a quick fix I didn't think it worth opening one.
> Windows: Prevent garbage text appearing in OpenFileDialog filters field

- src/video/uikit/SDL_uikitviewcontroller.m
This fixes the text prediction bar showing text from a previous text input session and also potentially overwriting text:
https://github.com/user-attachments/assets/11324eef-a161-4e8b-af6e-ce4857886e47
Eventually it would probably be nice to allow SDL to request the current text content from the consumer as a `SDL_TEXTINPUT_...` property and fill that to the internal text field to make the prediction synchronise with the current content. That would probably also get rid of the entire `obligateForBackspace` string. Wouldn't mind implementing that if it's fine to implement only for iOS, not quite experienced to deal with other platforms.
> Reset text field content when stopping text input on iOS

- src/video/windows/SDL_windowswindow.c
Regular child windows aren't positioned relative to the parent.
Fixes #11738
> win32: Only recalculate the position on show for popup windows

- src/misc/ios/SDL_sysurl.m
Apparently as of iOS 18.2, the deprecated API we were using just refuses to work at all.
Fixes #11728.
> misc: Fix SDL_OpenURL on newer iOS releases.

- android-project/app/src/main/java/org/libsdl/app/SDLActivity.java
- android-project/app/src/main/java/org/libsdl/app/SDLControllerManager.java
- android-project/app/src/main/java/org/libsdl/app/SDLSurface.java
- src/core/android/SDL_android.c
- src/events/SDL_pen.c
- src/events/SDL_pen_c.h
- src/video/android/SDL_androidpen.c
- src/video/android/SDL_androidpen.h
Related to https://github.com/libsdl-org/SDL/issues/10516
This PR implements Android pen backend. It is very basic because a pen I have is missing a lot of features. It only has a pen tip and a single button (no tilt support or whatever). I added some code for eraser, but I couldn't test because I don't have.
It also refactors input handling to use pointer count more extensively to reduce duplicate code, which also removes a DeX-specific workaround. I know I should have separated PRs, but [this doc](https://developer.android.com/reference/android/view/InputDevice#SOURCE_STYLUS) suggested that one shouldn't use `getSource` to determine whether the event came from stylus, so I ended up combining them.
`ACTION_BUTTON_PRESS`/`ACTION_BUTTON_RELEASE` doesn't seem to get triggered for stylus, so …
> Add basic Android pen backend

- Android.mk
- VisualC-GDK/SDL/SDL.vcxproj
- VisualC-GDK/SDL/SDL.vcxproj.filters
- VisualC/SDL/SDL.vcxproj
- VisualC/SDL/SDL.vcxproj.filters
- include/SDL3/SDL_hints.h
- src/events/SDL_windowevents.c
- src/tray/SDL_tray_utils.c
- src/tray/SDL_tray_utils.h
- src/tray/cocoa/SDL_tray.m
- src/tray/dummy/SDL_tray.c
- src/tray/unix/SDL_tray.c
- src/tray/windows/SDL_tray.c
- test/testtray.c
`SDL_HINT_QUIT_ON_LAST_WINDOW_CLOSE` will not fire if there are active tray icons. This impacts only applications that create tray icons, and that at least one icon outlives the last visible top-level window. `SDL_EVENT_QUIT` will fire when the last active tray is destroyed if there are no active windows.
This effectively means that `SDL_HINT_QUIT_ON_LAST_WINDOW_CLOSE` actually means "Quit when last _window or tray_ is closed". It does not affect any application that does not use system tray icons.
I've added a dummy window to `testtray` to help observe this behavior.
Closes #11722
> `SDL_HINT_QUIT_ON_LAST_WINDOW_CLOSE` also considers system tray icons

- src/video/wayland/SDL_waylandwindow.c
- src/video/x11/SDL_x11window.c
Additionally, ensure that coordinates set while the window is hidden are applied when shown on X11 and Wayland.
Fixes #11750
> X11: Don't overwrite the popup window position on resize

- src/video/windows/SDL_windowsevents.c
- src/video/windows/SDL_windowswindow.c
- src/video/windows/SDL_windowswindow.h
Even if a borderless window doesn't have the resizable borders hint set, the WS_MAXIMIZEBOX property needs to be set on the window, or maximizing it will make it fullscreen, covering the taskbar, instead of only filling the usable desktop space. The style property needs to be retained until the window is no longer maximized, even if the resize flag is toggled off, or restoring from minimized can fail.
The default of the nearest monitor also needs to be used when querying it from the window, or null can be returned when the window is coming out of minimized, which results in the restored, maximized window being the wrong size.
Fixes #11714
> win32: Fix borderless, maximized windows

- examples/demo/01-snake/snake.c
- examples/demo/02-woodeneye-008/woodeneye-008.c
- examples/demo/04-bytepusher/bytepusher.c
These links were not updated when the `game` directory was renamed to `demo`.
N/A
> examples: Fix dead links in app metadata

- src/render/gpu/SDL_render_gpu.c
This PR replaces the "present fence" hack in the GPU backend of the render API with the new wait and frames-in-flight APIs which were added to cover this exact use case. I have never used the render API so this is a 100% blind change with zero testing done on my part. Somebody who uses the render API will need to do the appropriate testing. Theoretically there should be no changes in external behavior.
> render: Update GPU backend to use the new present workflow

- Xcode/SDL/SDL.xcodeproj/project.pbxproj
- examples/pen/01-drawing-lines/drawing-lines.c
- src/video/uikit/SDL_uikitpen.h
- src/video/uikit/SDL_uikitpen.m
- src/video/uikit/SDL_uikitview.h
- src/video/uikit/SDL_uikitview.m
This PR is currently just pulling in @frenzibyte's work; I'm going to clean up a few things and merge.
Reference Issue #9911.
Reference Issue #10516.
> uikit: Initial Apple Pencil support.

- include/SDL3/SDL_stdinc.h
Newer emscripten SDK does an unconditional #include <stdbool.h>, which clashes with our custom bool.h typedef
Fixes #11445
> stdinc: use __has_include to detect <stdbool.h>

- include/SDL3/SDL_tray.h
- src/tray/windows/SDL_tray.c
Removes some libc-specific functions from the Windows tray implementation.
Fixes #11749
> Remove libs function from Windows tray

- src/audio/alsa/SDL_alsa_audio.c
```bash
[ 28%] Building C object CMakeFiles/SDL3-shared.dir/src/audio/alsa/SDL_alsa_audio.c.o
/mnt/devel/dev/projects-NEW/external/libs/c/SDL/sources/SDL-git-Sackzement/src/audio/alsa/SDL_alsa_audio.c:499:5: warning: use of an empty initializer is a C23 extension [-Wc23-extensions]
499 |     {
|     ^
1 warning generated.
```
> Fix C23 empty initializer warning.

- include/SDL3/SDL_thread.h
```c
/path/to/SDL/include/SDL3/SDL_thread.h:119:24: warning: commas at the end of enumerator lists are a C99-specific feature [clang-diagnostic-c99-extensions]
119 |     SDL_THREAD_COMPLETE,    /**< The thread has finished and should be cleaned up with SDL_WaitThread() */
|                        ^
```
> Fix C99 trailing enum comma warning.

- include/SDL3/SDL_hints.h
- src/main/generic/SDL_sysmain_callbacks.c
Now (only in the generic backend, where it is implemented), this hint is always respected. Previously it would only be used if no windows were created, to help reduce CPU load on things like loopwave.
Since it's always used now, the default has changed from 60 (Hz) to 0 (run as fast as possible). Things like loopwave should still likely force this way lower than the previous default (and already do: loopwave explicitly sets it to 5).
The hint can now also be set to "waitevent" which will cause SDL_AppIterate to only be called after new events have arrived, for apps that are entirely driven by input and want to consume (almost) no power or CPU time until then.
Fixes #11093.
Fixes #11387.
So the screen recorder obviously doesn't capture this precisely, but here's testsprite on my laptop, …
> main: Adjust how SDL_HINT_MAIN_CALLBACK_RATE works.

- include/SDL3/SDL_gpu.h
Not a huge change since the "how" is already there, we're just adding the "why" as well.
Fixes #10852
> gpu: Document why VertexID/InstanceID builtins are unreliable

- docs/README-migration.md
I was confused on how to migrate SDL_GetWindowData and SDL_SetWindowData by the migration guide, this pr aims to show the functions to migrate to instead of just insinuating to use Properties which people unfamiliar with SDL might not understand.
Change migration guide for SDL_GetWindowData and SDL_SetWindowData to show usage of SDL_SetPointerProperty with SDL_GetWindowProperties intead of just SDL_GetWindowProperties.
> Clarify migration for GetWindowData and SetWindowData

- src/video/SDL_clipboard.c
- test/testautomation_clipboard.c
Don't skip setting clipboard data when no callbacks are supplied so that the clipboard may be cleared before SDL sets clipboard data (there may be data in the clipboard not set by SDL)
#11814
> clipboard: Ensure SDL_ClearClipboardData clears data even when no data has been set by SDL

- src/gpu/d3d12/SDL_gpu_d3d12.c
When calculating mip sizes width and/or height can drop below 1, i.e. generating a mip from a 2x1 texture would produce a desired size of 1x0.
```
Assertion failure at SDL_BlitGPUTexture_REAL (E:\Documents\Projects\SDL3\src\gpu\SDL_gpu.c:2541), triggered 1 time:
'!"Blit source/destination regions must have non-zero width, height, and depth"'
```
None I'm aware of
> [GPU] Fix mip generation for 2x1 textures on D3D12

- src/video/cocoa/SDL_cocoawindow.m
- src/video/wayland/SDL_waylandwindow.c
- src/video/windows/SDL_windowswindow.c
- src/video/x11/SDL_x11window.c
Fix focus issues when a popup that is the child of a window that does not currently have keyboard focus is hidden or destroyed.
There is definitely some common code that can be factored out here, but I'll leave that for another time since it's a cleanup rather than a bug fix.
Fixes #11804
> video: Fix focus when non-focused popup windows are hidden

- src/audio/coreaudio/SDL_coreaudio.m
- src/video/cocoa/SDL_cocoamessagebox.m
- src/video/cocoa/SDL_cocoawindow.h
- src/video/cocoa/SDL_cocoawindow.m
Several recent changes inadvertently broke SDL2 on various macOS versions older than 10.15. These changes restore compatibility.
With the `kAudioChannelLayoutTag_*` enum values, when on an OS version that doesn't support the correct layout, I'm not sure if it's better to error out as I'm currently doing, or to use a not quite right channel layout as in previous versions.
> SDL2: compatibility fixes for macOS < 10.15

- src/test/SDL_test_fuzzer.c
- test/testautomation_intrinsics.c
- test/testautomation_sdltest.c
- test/testplatform.c
`-ftrapv` traps when it detects signed overflow.
This pr replaces locations where signed overflow occurs with unsigned math, which is well-defined.
I tested these changes by building SDL3 with `-DCMAKE_C_FLAGS=-ftrapv` and running testautomation as
```
ctest -R testautomation --repeat-until-fail 50 --output-on-failure
```
Fixes #9158
> tests: avoid undefined signed overflow

- INSTALL.md
- docs/README-windows.md
This PR adds documentation on getting started with MinGW64 on Windows.
I added a new MinGW64 section to docs/README-windows.md that walks through the process of setting up MinGW64 with MSYS2 and then using it to build and instal a system SDL. I also modified the minimal CMakeLists.txt from docs/README-cmake.md to show how you can link with such a system SDL in Windows.
https://github.com/libsdl-org/SDL/issues/11740
> Add detailed documentation on building with MinGW64

- src/video/windows/SDL_windowsevents.c
The eraser button is a secondary button next to the barrel button on some pens (see https://learn.microsoft.com/en-us/windows-hardware/design/component-guidelines/windows-pen-designs#physical-design). It will be reported as the button `2` in [SDL_PenButtonEvent](https://wiki.libsdl.org/SDL3/SDL_PenButtonEvent).
**RFC**: We may also want to consider pressing the eraser button to function as the `eraser` in [SDL_PenTouchEvent](https://wiki.libsdl.org/SDL3/SDL_PenTouchEvent). The SDL docs specifically call out the `eraser` as the pen being inverted, but it can be changed to a generic "erase". (I would still keep the eraser as a button, as it can be used even if the pen is not touching the tablet.)
```diff
diff --git a/src/video/windows/SDL_windowsevents.c …
```
> Windows pen: handle pen eraser button as the second button

- src/gpu/vulkan/SDL_gpu_vulkan.c
While investigating https://github.com/libsdl-org/SDL/issues/11820 I noticed that we also crash immediately if the window is minimized. This appears to be because we get a null VkSurfaceKHR pointer somewhere and then pass it in to QuerySwapchainSupport (I wasn't able to identify the source of the null pointer), and the user-mode driver just dereferences the null pointer and crashes.
> [GPU] Fix crash in nvidia user-mode win32 driver when game window is minimized during swapchain resize

- include/SDL3/SDL_tray.h
- src/tray/cocoa/SDL_tray.m
- src/tray/unix/SDL_tray.c
- src/tray/windows/SDL_tray.c
This fixes two issues with the system tray:
- Windows now properly supports dark mode for the context menu.
- `SDL_GetTrayEntries` returns a caller-owned pointer (it simply duplicates the internal list).
Fixes #11787
> Tray: `SDL_GetTrayEntries` caller-owned pointer, dark mode support on Windows

- src/tray/windows/SDL_tray.c
Tray systems have their own window event handler; this adds support for dark theme for its context menus.
Fixes #11789
> Support dark theme for tray menus on Windows

- examples/template.html
In `examples/template.html`, tabs would no longer move with their drawer due to a change in CSS. This resulted in tabs showing on top of each other's drawer, which could potentially cover up code or debugging info.
I've updated the CSS code to make the tab labels work again, and also make them hide to avoid hiding the other tab when they show up.
_None_
> Fix HTML examples template tabs

- src/video/wayland/SDL_waylandevents.c
This adds an opt-in workaround for intermittent unplayably stuck keys in https://github.com/jtothebell/fake-08 . While Fcitx5 is running in Wayland mode, my character suddenly falls like a brick when flying midair. Upon respawning, it runs in one direction without any (arrow) keys pressed until pressing and releasing all keys. Things were working fine until I added `export SDL_VIDEODRIVER=wayland`. This emulator has a `#define KB_ENABLED` but the games I play don't use it. However, I want to keep the input method running for other apps.
Per https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland , `SDL_IM_MODULE=fcitx` is discouraged, therefore setting it must be intentional. Fcitx also suggests running SDL on X11, which I won't so that DOSBox is readable on HiDPI. This PR makes SDL match …
> Let SDL_IM_MODULE=fcitx override Wayland as a workaround to fix key repetition detection

- src/audio/wasapi/SDL_wasapi.c
- src/audio/wasapi/SDL_wasapi.h
Fixes #9673.
(the branch name says 'sdl2' but this is for SDL3.)
> wasapi: Don't crash/hang if transitioning to/from a Remote Desktop Connection.

- src/video/wayland/SDL_waylandwindow.c
- src/video/wayland/SDL_waylandwindow.h
Apply the supplied xdg-toplevel bounds to resizable windows during initial mapping. Libdecor functionality will have to added separately, as the functionality needs to be added to the library first.
Fixes #11747
> wayland: Apply toplevel bounds to windows

- src/video/wayland/SDL_waylandvideo.c
- src/video/wayland/SDL_waylandwindow.c
- src/video/wayland/SDL_waylandwindow.h
- wayland-protocols/xdg-shell.xml
Apply the supplied xdg-toplevel bounds to resizable windows during initial mapping. Libdecor functionality will have to be added separately, as the functionality needs to be added to the library first.
Fixes #11747
> [SDL2] wayland: Apply toplevel bounds to windows

- docs/README-android.md
An attempt to clean up the Android docs a bit.
The project setup section was pretty outdated and disjointed, making it confusing to follow for someone who has never touched Android stuff before. I tried to clean it up a bit and made the CMake variant work more like SDL_helloworld, where build.gradle is just pointed to the project's top level CMakeLists instead of trying to jam sources in app/jni/src. I also added a note about assets.srcDirs to make it clear that you don't really _have_ to copy anything to app/src/main/assets in order to bundle them.
~~Marked as draft because I have no idea if this version makes any sense to others and I've probably messed something up :)~~
It should be good now.
> Android doc cleanup

- src/tray/unix/SDL_tray.c
g_object_unref() only accepts valid object instances.
> tray: Don't call g_object_unref(NULL)

- src/tray/unix/SDL_tray.c
* tray: Don't try to use GTK 2 versions of libappindicator
We use GTK 3 functions in this file, so we cannot load a libappindicator
whose SONAME indicates that it is using GTK 2.
* tray: Load GTK and libappindicator by versioned names, except on OpenBSD
We are expecting a specific ABI (we can see that from the declarations
listed in this file) and the whole point of SONAME versioning is to
say that the library conforms to a specific ABI. If the SONAME is not
the one we expect, then calling its functions is likely to crash.
As usual, an exception to this is that OpenBSD does not use SONAME
versioning.
---
Similar to #10776, but for the new "system tray" code.
> tray: Only load known-good SONAMEs for libappindicator

- src/video/windows/SDL_windowsevents.c
- src/video/windows/SDL_windowswindow.c
Non-resizable windows still need to apply the pending size when calculating the client rect, as they can be resized programmatically.
Fixes programmatically resizing windows without the WS_THICKFRAME style.
Closes #11883
> win32: Use the pending size during NCCALCSIZE

- include/SDL3/SDL_assert.h
- include/SDL3/SDL_bits.h
- include/SDL3/SDL_stdinc.h
- src/SDL_internal.h
With these patches, I can successfully use the SDL3 headers with MSVC 6 (from 1998).
> Add support for including SDL3 headers in older toolchains

- docs/README-migration.md
- include/SDL3/SDL_keycode.h
- src/events/SDL_keymap.c
- src/events/SDL_keysym_to_keycode.c
- src/events/SDL_keysym_to_keycode_c.h
- src/events/SDL_keysym_to_scancode.c
- src/test/SDL_test_common.c
- src/video/wayland/SDL_waylandevents.c
- src/video/wayland/SDL_waylandevents_c.h
- src/video/x11/SDL_x11events.c
- src/video/x11/SDL_x11keyboard.c
- src/video/x11/SDL_x11video.h
- test/checkkeys.c
This adds support for the "Mod3" modifier, commonly used as "Level 5 Shift" (or often remapped for custom purposes), as well as adding some extra key codes for common Xkb mappings. Left Tab is found in the default ASCII keymap, Level 5 Shift is found in some international layouts, and the Meta, Hyper, and Multi-key Compose keys are often enabled by tweak tools for customizing the keyboard layout, so it makes sense to add them. These keycodes, which don't correspond to any particular scancodes in the USB spec, are mapped to SDL keycodes by setting bit 30 of the raw keysym value. This is safe, as keysyms are only 29 bits, and this is well out of the range of UTF32 characters.
This also allows for passing through unknown keysyms with the keysym bit set, which allows clients to handle any …
> X11/Wayland: Support the "Mod3" modifier and add extra keycodes for common Xkb keys

- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
> gpu: Show a debug error when pipelines are not given the right shader stages

- .github/workflows/generic.yml
- CMakeLists.txt
- docs/README-cmake.md
This avoids double negation when configuring CMake projects.
So `-DSDL_DISABLE_INSTALL=FALSE` becomes `-DSDL_INSTALL=TRUE`.
> cmake: remove `_DISABLE_` from CMake options

- src/video/x11/SDL_x11dyn.c
- src/video/x11/SDL_x11dyn.h
- src/video/x11/SDL_x11events.c
- src/video/x11/SDL_x11keyboard.c
- src/video/x11/SDL_x11keyboard.h
- src/video/x11/SDL_x11sym.h
- src/video/x11/SDL_x11window.c
- src/video/x11/SDL_x11window.h
Tested with fcitx5 and ibus on Xorg and Xwayland
* Used US English with dead keys and verified that ` followed by a results in à
* Used Hangul to enter Korean and got text in the expected order
* Used the mozc IM to enter Japanese and was able to generate candidates and so forth
Fixes https://github.com/libsdl-org/SDL/issues/3907
Fixes https://github.com/libsdl-org/SDL/issues/6164
Fixes https://github.com/libsdl-org/SDL/issues/11894
> Use XIM for IME input on X11

- include/SDL3/SDL_tray.h
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
- src/tray/cocoa/SDL_tray.m
- src/tray/dummy/SDL_tray.c
- src/tray/unix/SDL_tray.c
- src/tray/windows/SDL_tray.c
- src/video/cocoa/SDL_cocoaevents.m
Also removed the app delegate from the tray code on Cocoa and folded that into SDL3AppDelegate.
Fixes https://github.com/libsdl-org/SDL/issues/11906
> Added SDL_ClickTrayEntry()

- src/gpu/metal/SDL_gpu_metal.m
> gpu: Initialize Metal stencil format even if stencil test is disabled

- examples/template.html
This is large text and is already covered by the header and breadcrumb
> Removed redundant information in example pages

- examples/audio/01-simple-playback/simple-playback.c
- examples/audio/02-simple-playback-callback/simple-playback-callback.c
Audio played by sine wave examples becomes gradually distorted over time due to insufficient precision in sine wave generation, making it possible to confuse with an actual audio buffering issue.
Move to using doubles instead of floats in sine wave math
Fixes https://github.com/libsdl-org/SDL/issues/11936
> examples: use doubles to generate sine waves to avoid distortion

- include/SDL3/SDL_hints.h
- src/video/cocoa/SDL_cocoavideo.m
- src/video/cocoa/SDL_cocoawindow.h
- src/video/cocoa/SDL_cocoawindow.m
Adds SDL_HINT_VIDEO_MAC_FULLSCREEN_MENU_VISIBILITY to control whether or not the menu can be accessed when the cursor is moved to the top of the screen when a window is in fullscreen spaces mode.
The three values are 'always', 'never', and 'auto' (default), with auto resulting in a hidden menu if fullscreen was toggled programmatically, and the menu being accessible if fullscreen was toggled via the button on the window title bar, so the user won't be stuck in fullscreen if the client app/game doesn't have a readily available option to toggle it.
Will leave this open for a bit to see if anyone has an opinion on a different default setting, or if this should just be a boolean always/never.
Fixes #8518
> cocoa: Add a hint to control menu visibility in fullscreen spaces windows

- include/SDL3/SDL_gpu.h
- src/gpu/SDL_gpu.c
- src/gpu/SDL_sysgpu.h
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
- test/testgpu_spinning_cube.c
All GPU resources now implement a name property in their create functions. These are only set in debug mode.
The header docs now encourage users to use these properties instead of the `SDL_SetGPUBufferName` and `SDL_SetGPUTextureName` functions due to thread safety issues.
Resolves #11927
> GPU: Add name properties to resources

- src/tray/windows/SDL_tray.c
SDL_CreateTray now respects SDL_HINT_WINDOWS_INTRESOURCE_ICON_SMALL and SDL_HINT_WINDOWS_INTRESOURCE_ICON hints and uses the specified icon as the tray icon.
Previously `SDL_CreateTray` loaded the default application icon `LoadIcon(NULL, IDI_APPLICATION)`
if icon argument was NULL. With this change it now checks if there was a hint specified.
SDL_HINT_WINDOWS_INTRESOURCE_ICON_SMALL has priority over SDL_HINT_WINDOWS_INTRESOURCE_ICON,
because it is more suited to be a small tray icon. If loading the icon fails it loads the default application icon like before.
This change significantly simplifies setting tray icons for applications that use
icon resources in their program. These hints are already used for setting window icons,
so extending their functionality to the tray icon API would …
> Added support for custom tray icon on Windows via SDL hints.

- include/SDL3/SDL_events.h
- include/SDL3/SDL_tray.h
Fixes some typos and outdated references to SDL symbols in the docs
> Fix references in docs

- src/events/SDL_keyboard.c
- src/events/SDL_mouse.c
Replaces 3 uses of memcpy that could be overlapping.
fixes #11958
> events: use SDL_memmove instead of SDL_memcpy for overlapping memory

- src/video/windows/SDL_windowsevents.c
Fixes https://github.com/libsdl-org/SDL/issues/11807 on Windows
> Child windows shouldn't take focus if the parent window is in relative mouse mode

- src/video/windows/SDL_windowsmouse.c
Corrected the calculation of the vertical hotspot position in the `GetCachedCursor` function.
Changed the variable from `data->hot_x` to `data->hot_y` to ensure the correct vertical position of the cursor's hotspot is used when scaling.
> Fix incorrect hotspot calculation for cursor positioning

- src/events/SDL_mouse.c
Currently `SDL_GetMouseNameForID()` doesn't set an error message, when passing an invalid mouse ID:
```c
if(!SDL_GetMouseNameForID(99)) {
printf("Error \"%s\"", SDL_GetError());
}
```
Prints
```c
""
```
This commits sets an error message when the function fails.
The style of the message is inspired by a similar joystick error message:
https://github.com/libsdl-org/SDL/blob/68cc173d9293e890ba93feaed1d3dc17742aa9b3/src/joystick/SDL_joystick.c#L515
> `SDL_GetMouseNameForID()`: Set an error message for invalid mouse IDs.

- src/video/cocoa/SDL_cocoavideo.m
- src/video/cocoa/SDL_cocoawindow.h
- src/video/cocoa/SDL_cocoawindow.m
The existing algorithm works well for min-max ratios, but didn't allow edge expansion of fixed aspect ratio windows. Use NSWindow setContentAspectRatio instead.
> cocoa: fixed resizing windows with fixed aspect ratio

- src/video/windows/SDL_windowsevents.c
Fixes https://github.com/libsdl-org/SDL/issues/11976
> windows: don't set focus click pending if SDL_HINT_MOUSE_FOCUS_CLICKTHROUGH is set

- src/video/cocoa/SDL_cocoawindow.m
- src/video/windows/SDL_windowsevents.c
Previously, Win32 and Mac would eat all mouse button events when the cursor was over a draggable area. Pass non-left clicks through, so they can be used to open menus or perform other functions while over client-side title bars. Neither platform seems to do anything with non-left clicks over draggable areas anyway.
X11 and Wayland already behave in this manner.
Fixes #11974
> Normalize hit testing across platforms

- src/video/SDL_video.c
- src/video/uikit/SDL_uikitevents.m
Fixes https://github.com/libsdl-org/SDL/issues/11627
> Keep the lifecycle observer active while there are windows active

- src/video/cocoa/SDL_cocoaevents.m
- src/video/cocoa/SDL_cocoamouse.h
- src/video/cocoa/SDL_cocoamouse.m
- src/video/cocoa/SDL_cocoawindow.m
We can't directly set the mouse focus since we may get spammed by entered/exited events, but we can process the current focus later in the mouseMoved handler in line with the mouse motion event sequence.
Fixes https://github.com/libsdl-org/SDL/issues/8188
> cocoa: clear mouse focus based on NSEventTypeMouseExited events

- include/SDL3/SDL_test_common.h
- src/test/SDL_test_common.c
- src/video/SDL_video.c
- test/testgl.c
Original patch was from @ramezgerges (thanks!).
Second patch (also from @ramezgerges), adds some testing for the feature to test/testgl.c.
Fixes #11697.
> video: SDL_GL_GetAttribute gets correct SDL_GL_CONTEXT_RELEASE_BEHAVIOR value.

- include/SDL3/SDL_filesystem.h
- include/SDL3/SDL_storage.h
- src/filesystem/SDL_filesystem.c
- src/filesystem/posix/SDL_sysfsops.c
- src/filesystem/windows/SDL_sysfilesystem.c
- src/filesystem/windows/SDL_sysfsops.c
- src/storage/SDL_storage.c
- src/storage/generic/SDL_genericstorage.c
- test/testfilesystem.c
This addresses all of @nightmareci's bugs about paths in the Filesystem and Storage APIs.
The only one that _might_ be controversial (CC @flibitijibibo) enforces policy at the top level of the Storage API to forbid paths that have "." or ".." elements in them, or '\\' path separators; they won't even get to the backend for further processing. This is both to prevent breaking out of a storage base path, but alsoto deal with the possibility that a storage backend won't actually support ".." paths; sure, the filesystem does, but will a .zip archive exposed as a Storage object?
Forbidding '\\' just makes sure you don't accidentally hardcode a path that will be a surprising failure as soon as you port your code outside of Windows (and on the flip side, so you don't get a totally different …
> Filesystem and Storage path politics

- src/video/x11/SDL_x11window.c
Ensures the EGL surface is set for foreign X11 windows.
Moves the EGL surface creation code over to SetupWindowData so it works for foreign X11 windows too.
Also slightly changes up the cleanup code for SetupWindowData, to avoid copy pasting.
#10611
> [SDL2] Set EGL surface for foreign X11 windows

- src/events/SDL_mouse.c
- src/events/SDL_touch.c
This PR fixes an off-by-one error for controlling what synthetic mouse events are generated on PSVita using `SDL_HINT_VITA_TOUCH_MOUSE_DEVICE`.
The touch IDs for the front and back touchscreen on Vita appear to have changed within SDL from 0 and 1 respectively to 1 and 2 in https://github.com/libsdl-org/SDL/commit/a31dc6dfcb8b3a50a9713702271aeaa7c5930131. This made the behaviour of `SDL_HINT_VITA_TOUCH_MOUSE_DEVICE` values off-by-one compared to what it should be.
I've fixed it so that the behaviour of the hint values properly match [what is documented in the wiki](https://wiki.libsdl.org/SDL3/SDL_HINT_VITA_TOUCH_MOUSE_DEVICE), shifting the internal `vita_touch_mouse_device` by one. I do not have a Vita so I can't test on real hardware, but I have tested it on an emulator (Vita3K) that …
> Vita: Fix off-by-one error for synthetic mouse events

- examples/audio/01-simple-playback/simple-playback.c
- examples/audio/02-simple-playback-callback/simple-playback-callback.c
Audio distortion after a while caused by loss of precision in dividing a large floating point number resolved by keeping `current_sine_sample` (formelly named `total_samples_generated`) between `0` and `spec.freq - 1`.
We are wrapping around `current_sine_sample` by the number of samples per second so that `current_sine_sample * freq` always results in a small number while also making the `phase` go between `0` and `1`, avoiding discontinuity in the signal. This removes the necessity of using a `double` to dealy the amount of time until we get distortion.
Fixes https://github.com/libsdl-org/SDL/issues/11936
> Fixed sine wave distortion over time.

- examples/audio/01-simple-playback/simple-playback.c
- examples/audio/02-simple-playback-callback/simple-playback-callback.c
`phase` should be a `float` value that ranges between `0` and `1`.
`phase` was `int` in the previous implementation but now it should be `float` as it ranges between `0` and `1`.
FIX https://github.com/libsdl-org/SDL/pull/12013#issuecomment-2599465628
> Fixed wrong type of `phase`

- src/tray/windows/SDL_tray.c
The `test/testtray` program would crash on Windows when adding any item and then removing it, because a submenu's parent_entry field was not set.
Additionally, I noticed that some extraneous code copied from the `{G,S}etTrayEntryChecked` made `{G,S}etTrayEntryEnabled` work only for checkboxes, which is not the desired behavior.
Both issues were fixed in this commit.
---
Relatedly, it may be worth to take some time before the first full release to exhaustively test trays and dialogs on all platforms. I did some summary testing on Windows, but I can write extensive unit tests that can quickly be run on all platforms, so that we won't need to manually try every possible combination to find embarrassing mistakes like these two.
Fixes #12002
> Windows trays: Fix fetching parent entry from submenu, allow enabling and disabling entries that aren't checkboxes

- src/dialog/windows/SDL_windowsdialog.c
This fixes the memory issue with multithreading in the Windows implementation of file dialogs.
I've also fixed a few more issues where I saw them. For example, the arguments passed to the thread functions weren't freed. I ran the program again with `--trackmem` and it said `Memory allocations: Total: 0.00 Kb in 0 allocations, 112 unknown frees`, hoping that's alright.
@AntTheAlchemist Can you confirm that this fixes the problem?
Fixes #11713 (hopefully)
> Fix Windows file dialog memory management

- src/video/windows/SDL_windowsevents.c
- src/video/windows/SDL_windowswindow.c
- src/video/windows/SDL_windowswindow.h
Always restore the base floating size/position of a window before possibly entering the maximized state when leaving fullscreen, as the base size can be lost during the fullscreen transition, resulting in the window de-maximizing to the wrong size.
Fixes #12006
> Win32: Fix restoring a maximized window after leaving fullscreen

- include/SDL_haptic.h
- src/haptic/linux/SDL_syshaptic.c
SDL2 version of #12031 
Provious code wrongly assumed that direction is not an important part of conditional effect. Moreover, if there's need to hardcode polar direction, the default should be `0x4000` (north).
For one axis affects, a direction of 0 means complete lack of force, if a FFB-enabled device takes direction into force calculation. A sine function graph can be used to represent the resulting forces where X is the input direction and Y is the force multiplier (360 degrees equals to 1).
This fixes conditional effect playback on Moza Racing devices, which do not ignore direction field.
> [SDL2] Translate conditional effect direction instead of hardcoding it to 0

- include/SDL3/SDL_haptic.h
- src/haptic/linux/SDL_syshaptic.c
Previous code wrongly assumed that direction is not an important part of conditional effect. Moreover, if there's need to hardcode polar direction, the default should be `0x4000` (North).
For one axis affects, a direction of 0 means complete lack of force, if a FFB-enabled device takes direction into force calculation. A sine function graph can be used to represent the resulting forces where X is the input direction and Y is the force multiplier (360 degrees equals to 1).
This fixes conditional effect playback on Moza Racing devices, which do not ignore direction field.
> [SDL3] Translate conditional effects direction instead of hardcoding it to 0

- include/SDL3/SDL_main.h
In order for `SDL_main.h` to function properly, we need some way of detecting which platform we're building for. For most platforms this is a simple `#if SDL_PLATFORM_*` check, but private platforms complicate matters. Since even their preprocessor symbols may be under NDA, we can't check for private platforms in `SDL_platform_defines.h`. To work around this in my initial pass on improving private platform support (https://github.com/libsdl-org/SDL/pull/11220), I required that applications themselves define `SDL_PLATFORM_PRIVATE_MAIN` either in their code or their build system in order to use `SDL_main.h`.
This ended up being annoying in practice, so @icculus pitched the idea of using `__has_include` instead. This way we can auto-detect the existence of header files containing the secret …
> Automatically detect SDL_main_private.h

- include/SDL3/SDL_gpu.h
Fixes a few small typos in the GPU documentation from before the signed floating-point texture formats got renamed.
> documentation typo: SFLOAT -> FLOAT

- src/dialog/unix/SDL_portaldialog.c
Fixes https://github.com/libsdl-org/SDL/issues/12036
> dialog: cleaned up D-Bus portal implementation

- examples/audio/01-simple-playback/README.txt
- examples/audio/01-simple-playback/simple-playback.c
- examples/audio/02-simple-playback-callback/README.txt
- examples/audio/02-simple-playback-callback/simple-playback-callback.c
- examples/audio/03-load-wav/README.txt
- examples/audio/03-load-wav/load-wav.c
Fix multiple occurences of typo "an simple" to "a simple" in audio examples
There were multiple occurrences of the same typo in the audio examples section, where "an" was used instead of "a" when the next word was "simple"
> Fix multiple occurences of typo "an simple" to "a simple" in audio examples

- android-project/app/src/main/java/org/libsdl/app/SDLControllerManager.java
Copies this fully correct pen handling code:
https://github.com/libsdl-org/SDL/blob/4231848791dae4e0a9afb32e2f9e897985b7dde2/android-project/app/src/main/java/org/libsdl/app/SDLSurface.java#L264-L278
to the existing half-correct pen handling code in `SDLControllerManager.java`.
This should probably be handled by a common function, but I was unsure where to put it. Probably in `SDLActivity` but that already has 2190 lines of code, which is discouraging.
> Copy Android pen handling code from `SDLSurface` to `SDLControllerManager`

- include/SDL3/SDL_log.h
I noticed in the SDL3 source code there's inconsistency in whether a `\n` is put on the end of log messages or not, but discussing with @slouken elsewhere, it seems it's valid to not have `\n` on the end of messages, so I've documented that. I also documented that you really shouldn't even have `\n` in messages for consistent/expected cross-platform behavior.
Maybe the bit about log messages being atomic isn't needed, since the log functions are documented as thread-safe, but I think it's good for helping new users.
If this PR is accepted, the log calls in the SDL source code maybe should be changed to match it, not having `\n` on the end of log messages.
> Improve log documentation

- src/audio/SDL_audiocvt.c
To trigger this bug, the source and destination channel count have to not match, and the source format also has to not be f32.
This fixes a buffer overrun (and intermittent crash) when playing audio from the opening FMV of Bloodborne in the ShadPS4 emulator. That audio is in 8 channel, s16le format, which triggers an audio conversion code path that probably isn't very common.
https://github.com/shadps4-emu/shadPS4/issues/2034
> Fix buffer overrun in ConvertAudio with different src/dst channel count

- src/video/x11/SDL_x11events.c
- src/video/x11/SDL_x11window.c
- src/video/x11/SDL_x11window.h
An undefined position means that the window manager can handle placement, so SDL shouldn't override that by forcing a position when showing a window.
Allows for removing a fair bit of now-unnecessary code as well.
Fixes #12060
> x11: Don't force position windows with an undefined position

- src/io/SDL_iostream.c
The amount of memory being allocated is actually `size + 1`, not `size`, so my change reflects that. The code before would only be correct if the actual size of allocation were exactly `size`.
> Fix possible integer overflow of size + 1 in SDL_LoadFile_IO()

- src/tray/windows/SDL_tray.c
Creating just a `SDL_Tray` without a `SDL_TrayMenu` crashes when the tray icon is clicked.
SDL commit: 17c4bdd754e860f166bdd2090c3d8a346a1a2bba
System:
Windows 10
Visual Studio 17 2022
Windows SDK version 10.0.26100.0
target Windows 10.0.19045
<details><summary>Code example</summary>
<p>
```c
#include <SDL3/SDL.h>
#include <stdio.h>
int main() {
if (!SDL_Init(SDL_INIT_VIDEO)) {
printf("%s\n", SDL_GetError());
return -1;
}
SDL_Window* window = SDL_CreateWindow("SDL3_tray_test", 400, 300, 0);
if (!window) {
printf("%s\n", SDL_GetError());
return -1;
}
SDL_Renderer* renderer = SDL_CreateRenderer(window, NULL);
if (!renderer) {
printf("%s\n", SDL_GetError());
return -1;
}
SDL_Surface* tray_surface = SDL_CreateSurface(1, 1, SDL_PIXELFORMAT_RGBA32);
if (!tray_surface) {
printf("%s\n", …
```
> Avoid a crash when a tray without a menu is clicked on Windows.

- include/SDL3/SDL_stdinc.h
Fixed a few documentation typos w/ regards to single- vs double- precision function variants.
> Documentation: typos around float precision

- src/video/windows/SDL_windowsmouse.c
This fix prevents C undefined behavior from being invoked on Windows if the user's configured cursor speed is below 6.
Reported by https://github.com/castholm/zig-examples/issues/1
I have a fork of SDL that builds SDL using Zig as a drop-in C compiler, which uses Clang under the hood. In debug and "safe" release modes, it enables Clang's [UBSan](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) and inserts traps to guard against undefined behavior.
On the line affected by this PR, if the user's cursor speed is lower than 6, it will result in an attempt to left-shift a negative value, which is UB in C.
Swapping out `<< 2` and `<< 3` for `* 4` and `* 8` respectively is a simple fix. You could also use something like `SDL_max(0, v - 2) << 2` but I would argue using multiplication …
> Fix undefined behavior in SDL_windowsmouse.c

- src/dialog/unix/SDL_portaldialog.c
Fixes practical deadlock situation that arises when using SDL dialogs on a machine that doesn't have a session dbus booted.
My downstream application is using `SDL_ShowOpenFileDialog` from the main (UI) thread to prompt the user to select some files. Here's a gist of the usage, which I think conforms to the documentation (the lifetimes of the arguments are held in the callback closure, etc.):
- https://gist.github.com/adamkewley/d0847228e93dcdb2a1d9a5c679f170a5
This works fine on Windows/Mac, but I encountered a deadlock when using it from Ubuntu on WSL2, `gdb` indicated the main thread was waiting on `connection_send_with_reply_and_block` (the line changed by this PR) but, because this call can't timeout, it locks the entire application if (e.g.) dbus doesn't respond.
In this specific …
> Change DBUS introspection timer from INFINITE -> DEFAULT when introspecting available dialog services

- src/video/x11/SDL_x11pen.c
I noticed this when running with ASAN on my own project. X11_MaybeAddPenByDeviceID doesn't free the device info. The documentation for XIQueryDevice says that it should be freed and the other callsite in X11_InitPen does, so I figure this is a pretty safe change. Tested against my own project for sanity.
> Free XIDeviceInfo in X11_MaybeAddPenByDeviceID

- include/SDL3/SDL_audio.h
In `include/SDL3/SDL_audio.h` almost all parameters of type `SDL_AudioDeviceID` are named `devid`:
```c
const char *      SDL_GetAudioDeviceName      (SDL_AudioDeviceID devid)
bool              SDL_GetAudioDeviceFormat    (SDL_AudioDeviceID devid, SDL_AudioSpec *spec, int *sample_frames)
int *             SDL_GetAudioDeviceChannelMap(SDL_AudioDeviceID devid, int *count)
SDL_AudioDeviceID SDL_OpenAudioDevice         (SDL_AudioDeviceID devid, const SDL_AudioSpec *spec)
bool              SDL_IsAudioDevicePhysical   (SDL_AudioDeviceID devid)
bool              SDL_IsAudioDevicePlayback   (SDL_AudioDeviceID devid)
float             SDL_GetAudioDeviceGain      (SDL_AudioDeviceID devid)
bool              SDL_SetAudioDeviceGain      (SDL_AudioDeviceID devid, float gain)
void …
```
> Rename parameters of type SDL_AudioDeviceID from dev to devid

- src/video/SDL_video.c
- src/video/uikit/SDL_uikitmodes.m
It's a regression since https://github.com/libsdl-org/SDL/commit/20f1061cc86b07146ba410e551d4994cd430e209
Based on what you do in main branch, I just set driverdata to NULL after both SDL_free() and CFRelease().
Code from main branch for reference:
SDL_video.c:
```
void SDL_DelVideoDisplay(SDL_DisplayID displayID, bool send_event)
{
SDL_VideoDisplay *display;
int display_index = SDL_GetDisplayIndex(displayID);
if (display_index < 0) {
return;
}
display = _this->displays[display_index];
if (send_event) {
SDL_SendDisplayEvent(display, SDL_EVENT_DISPLAY_REMOVED, 0, 0);
}
SDL_DestroyProperties(display->props);
SDL_free(display->name);
SDL_ResetFullscreenDisplayModes(display);
SDL_free(display->desktop_mode.internal);
display->desktop_mode.internal = NULL;
SDL_free(display->internal); …
```
> Fixed crash when trying to disconnect secondary display on iOS

- include/SDL3/SDL_camera.h
In `include/SDL3/SDL_camera.h` almost all parameters of type `SDL_CameraID` are named `instance_id`:
```c
const char *       SDL_GetCameraName    (SDL_CameraID instance_id)
SDL_CameraPosition SDL_GetCameraPosition(SDL_CameraID instance_id)
SDL_Camera *       SDL_OpenCamera       (SDL_CameraID instance_id, const SDL_CameraSpec *spec)
```
But there is one function, which uses the parameter name `devid`:
```c
SDL_CameraSpec ** SDL_GetCameraSupportedFormats(SDL_CameraID devid, int *count)
```
This commit renames it to `instance_id`.
Also adjusts the comment a bit to be the same as the other ones.
_This PR is not AI generated :)_
> Rename parameter of type SDL_CameraID from devid to instance_id

- examples/pen/01-drawing-lines/drawing-lines.c
- src/video/cocoa/SDL_cocoapen.m
- Negate tilt.y in Cocoa pen handling to correct inverted Y tilt axis
- Update drawing example to display X/Y tilt values for visualization
- see https://github.com/qt/qtbase/blob/0f128fd7c5a9ee721d1e631743f6eb61d927cf3b/src/plugins/platforms/cocoa/qnsview_tablet.mm#L63
- see https://source.chromium.org/chromium/chromium/src/+/main:components/input/web_input_event_builders_mac.mm;drc=0af5ffa1e4cc4cc4f818725f8fee93ec57855e4b;l=421
> Fix inverted pen Y tilt on macOS and add tilt display to example

- src/filesystem/SDL_filesystem.c
Checking for the backslash in addition to the forward slash. Tested on linux and windows via wine, with the code from the issue. Here is the outputs for each, before and after:
wine before fix:
0.  xplorer.exe
1.  h.exe
...
54.  otepad.exe
55.  egedit.exe
56.  undll.exe
57.  ystem.ini
58.  wain.dll
59.  wain_32.dll
60.  in.ini
61.  inhelp.exe
62.  inhlp32.exe
wine after fix:
0.  explorer.exe
1.  hh.exe
...
54.  notepad.exe
55.  regedit.exe
56.  rundll.exe
57.  system.ini
58.  twain.dll
59.  twain_32.dll
60.  win.ini
61.  winhelp.exe
62.  winhlp32.exe
linux before fix:
0.  libSDL3.dll.a
1.  libSDL3_test.a
2.  libjerry-core.a
3.  libSDL3_test.a:Zone.Identifier
4.  libjerry-port.a
5.  libSDL3.dll.a:Zone.Identifier
6.  libdxil.so
7.  libjerry-ext.a
8.  libdxcompiler.so
linux after fix:
0. …
> check for backslashes as well as the forward slash

- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
Resolves #12132 
If the client calls a Bind function with the same state that's already being used, we end up doing pointless re-binding work. Obviously the workflow in that issue report is stupid but there are some reasonable cases, particularly legacy applications implementing an SDL GPU backend, where the client might want to defensively bind resources and we shouldn't penalize them for it.
This patch simply checks the slots being bound to see if the same resource is already in there. If it is then the backend skips setting the bind flag.
Needs a Metal implementation before merge.
> GPU: Resource binding state shadowing

- src/video/wayland/SDL_waylandwindow.c
Some clients don't expect this, and it can cause issues, particularly if events are emitted while creating a hidden window.
> wayland: Don't send size events while the window is hidden

- src/camera/SDL_camera.c
The drivers are not needed if camera support as a whole is disabled.
Also fixes a problem in our internal builds failing to build the (not needed) camera drivers.
cc @slouken
> do not build camera drivers if camera support is disabled

- src/gpu/vulkan/SDL_gpu_vulkan.c
On the latest Vulkan SDK's validation layers, we started seeing a new error on some of our examples:
```
VUID-VkGraphicsPipelineCreateInfo-layout-07990(ERROR / SPEC): msgNum: -278545623 - Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-layout-07990 ] Object 0: handle = 0x4b7df1000000002f, name = CustomSampling.frag, type = VK_OBJECT_TYPE_SHADER_MODULE; Object 1: handle = 0x2b424a0000000034, type = VK_OBJECT_TYPE_PIPELINE_LAYOUT; | MessageID = 0xef65bb29 | vkCreateGraphicsPipelines(): pCreateInfos[0].pStages[1] SPIR-V (VK_SHADER_STAGE_FRAGMENT_BIT) uses descriptor [Set 2, Binding 0, variable "Texture"] of type VK_DESCRIPTOR_TYPE_STORAGE_IMAGE but expected VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER or VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE.
The Vulkan spec states: If a resource variable is …
```
> GPU: Describe "readonly storage" images as sampled images on Vulkan backend

- src/render/SDL_render.c
(...in order to avoid issue where inadvertently using top height, if the npatch existed on a larger texture than the drawn edge, would cause too many pixels to be included in the bottom part of the render.)
There is a bug currently with `SDL_RenderTexture9Grid`, its hard to notice. 
Two (2) conditions are needed to trigger, that I noticed.
a) The 9Grid texture is larger in height than the full size of the 9Grid, for example, if there is empty space bellow due to the 9Grid being stored on a spritesheet (streaming texture in minimal reproduce provided).
b) The 9Grid texture has different top and bottom margins. 
Then when drawing the 9Grid, `top_height` was inadvertently used as `curr_src.h` _when drawing `lower_left` and `lower_right`, as well as bottom of the 9Grid,_  causing either extra …
> proposed fix: set curr_src.h to bottom_height before drawing bottom edges / corners in SDL_RenderTexture9Grid

- src/video/windows/SDL_windowsevents.c
Fixes https://github.com/libsdl-org/SDL/issues/12169
> Call the windows message hook for WM_ENTERSIZEMOVE and WM_ENTERMENULOOP

- include/SDL3/SDL_gpu.h
- include/SDL3/SDL_hints.h
- include/SDL3/SDL_mouse.h
- include/SDL3/SDL_process.h
- include/SDL3/SDL_test_common.h
- include/SDL3/SDL_thread.h
- include/SDL3/SDL_tray.h
- include/SDL3/SDL_vulkan.h
- src/core/SDL_core_unsupported.c
- src/stdlib/SDL_malloc.c
- src/stdlib/SDL_qsort.c
- src/test/SDL_test_memory.c
- src/thread/SDL_thread.c
- src/video/SDL_video.c
- test/testdialog.c
This commit formats the spaces around pointer symbols.
Examples:
Space between pointer and `SDLCALL`:
```c
From: void *SDLCALL SDL_SomeFunction();
To:   void * SDLCALL SDL_SomeFunction();
```
Pointer directly besides parameter:
```c
From: void SDL_SomeFunction(void* param);
To:   void SDL_SomeFunction(void *param);
```
Pointer directly besides variable name:
```
From: void(SDLCALL * SDL_SomeFunctionPointer)();
To:   void(SDLCALL *SDL_SomeFunctionPointer)();
```
> Formatting spaces around pointer symbol.

- include/SDL3/SDL_rect.h
Is this allowed since the function is inline and not part of the dynapi list?
> Remove const from parameter of inline function SDL_RectsEqualEpsilon()

- src/video/windows/SDL_windowsevents.c
This change ensures that the `DispatchModalLoopMessageHook` function is only called if the `g_WindowsMessageHook` is set.
> Check nullptr before calling the windows message hook for WM_ENTERSIZEMOVE and WM_ENTERMENULOOP

- src/video/windows/SDL_windowswindow.c
This allows an OpenGL context to be properly created on XB1 and XSX platforms. We use the OGL to DX12 wrapper in Mesa/Gallium and the ifdef'ed out code was preventing `WIN_GL_SetupWindow` from being called. That's something we caught while migrating from SDL2 to SDL3. The SDL2 code has this code active for XB1 and XSX and it still work correctly there.
(None)
> Allow OpenGL initialization on XB1 and XSX.

- include/SDL3/SDL_platform_defines.h
I spotted this when reviewing the N-Gage PR - `__3DS__` is defined by the toolchain, meaning that undefining is likely to cause problems for other projects where the SDL headers are included.
> Remove #undef __3DS__

- src/core/linux/SDL_dbus.c
This is somewhat of an RFC PR to address the D-Bus related leak reports mentioned in various bug reports here and in sdl2-compat. LeakSanitizer is detecting these leaks because `libdbus-1.so` was unloaded by `SDL_DBus_Quit()` without calling `dbus_shutdown()`. This will be the case for most SDL-based apps that don't also use D-Bus themselves or set `SDL_SHUTDOWN_DBUS_ON_QUIT=1` to ask us to call `dbus_shutdown()` ourselves. We can avoid these false warnings by leaving `libdbus-1.so` loaded in cases that we don't do a `dbus_shutdown()` to clean it up properly.
Since many shared libraries remain loaded throughout the whole process lifetime, LeakSanitizer does not perform leak checks for loaded shared libraries (they may have legitimate allocations that are managed internally and not …
> dbus: fix spurious leak reports with SDL_SHUTDOWN_DBUS_ON_QUIT=0

- include/SDL3/SDL_tray.h
- src/tray/cocoa/SDL_tray.m
- src/tray/dummy/SDL_tray.c
- src/tray/unix/SDL_tray.c
- src/tray/windows/SDL_tray.c
Most parameters use the name `count` for the number of elements.
For comparison:
```c
SDL_AudioDeviceID * SDL_GetAudioPlaybackDevices(int *count);
SDL_AudioDeviceID * SDL_GetAudioRecordingDevices(int *count);
int * SDL_GetAudioDeviceChannelMap(SDL_AudioDeviceID devid, int *count);
int * SDL_GetAudioStreamInputChannelMap(SDL_AudioStream *stream, int *count);
int * SDL_GetAudioStreamOutputChannelMap(SDL_AudioStream *stream, int *count);
SDL_CameraID * SDL_GetCameras(int *count);
SDL_CameraSpec ** SDL_GetCameraSupportedFormats(SDL_CameraID instance_id, int *count);
char ** SDL_GlobDirectory(const char *path, const char *pattern, SDL_GlobFlags flags, int *count);
char ** SDL_GetGamepadMappings(int *count);
SDL_JoystickID * SDL_GetGamepads(int *count);
SDL_GamepadBinding ** …
```
> SDL_GetTrayEntries(): Rename parameter `size` to `count`

- mingw/pkg-support/Makefile
fix the ` sdl2.pc`  produced by the mingw32 devel package Makefile. (bug introduced in 2.30.10)
Also use `$(MAKE)`  instead of assuming `make`
Note : this PR is for 2.30.x
> SDL2: Fix mingw32 makefile

- src/gpu/vulkan/SDL_gpu_vulkan.c
Vulkan does not allow setting both the depth and stencil aspect for samplers. Since integer sampling is not supported without extensions we might as well just disable it on the sampler view, which will still allow sampling depth from a depth-stencil texture.
Resolves #12192
> GPU: Remove stencil bit from sampler aspect mask on Vulkan

- include/SDL3/SDL_hints.h
This is currently the only non-ASCII character in the public headers.
> Remove non-ASCII character from public header SDL_hints.h

- src/events/SDL_windowevents.c
- src/render/SDL_render.c
- src/render/SDL_sysrender.h
These are necessary for proper operation of the renderer and shouldn't be blocked by event filters, etc.
> Let the renderer always see window events

- CMakeLists.txt
When building with zig cc I get:
```
error: always_inline function '_mm_crc32_u32' requires target feature 'crc32', but would be inlined into function 'calc_crc32c' that is compiled without support for 'crc32'
5 |       crc32c = (unsigned)_mm_crc32_u32(crc32c, *(unsigned*)text);
|                          ^
1 error generated.
```
This PR adds -mcrc32, another option would be to use a different SSE4.2 op
> Fix SSE 4.2 test

- src/video/windows/SDL_windowsevents.c
This is for Windows.
Reference: https://gamedev.net/forums/topic/672094-keeping-things-moving-during-win32-moveresize-events/5254386/
Based on the above reference, this change fixes the hang for me. The expose event fires immediately upon clicking, instead of hanging for 0.5 seconds.
> Fix for 500ms hang after user clicks on the title bar, but before moving

- src/video/windows/SDL_windowsmouse.c
There is a potential resource leak in `WIN_CreateHCursor`. If `CreateColorBitmap(surface)` fails for non-monochrome surfaces, the function exits without freeing `ii.hbmMask`, leading to a memory leak.
> Memory Leak in WIN_CreateHCursor When CreateColorBitmap Fails

- examples/renderer/10-geometry/geometry.c
This PR updates the geometry renderer example such that the `color` values of `vertices[3]` are set correctly in `SDL_AppIterate`.
Currently, `vertices[3].color.g`, `vertices[3].color.b` and `vertices[3].color.a` are unset in `SDL_AppIterate`. The changes in this PR fix that.
N/A
> Fix geometry renderer example vertex creation

- src/video/windows/SDL_windowsshape.c
`mask` is created but never deleted if `SetWindowRgn()` fails. This may lead to resource leaks, as the allocated region remains in memory. To fix this, we should call DeleteObject(mask); before returning in case of failure.
> Proper Resource Cleanup in WIN_UpdateWindowShape

- src/joystick/hidapi/SDL_hidapi_ps5.c
In my application, I allow users to toggle an option which eventually ends up resetting a few of the available joystick hints. One of these options toggles the "enhanced reports" functionality for PS4/PS5 controllers (and others?)
One user reported that when these options were changed, it crashed in `SDL_SetHint -> SDL_SetHint_REAL -> SDL_SetHintWithPriority_REAL -> SDL_PS5PlayerLEDHintChanged -> HIDAPI_DriverPS5_UpdateEffects`.
This is an odd setup, and not one I encourage, but crashing here is obviously not the expected behaviour.
Some quick debugging showed that this was a use-after-free, caused by the LED callback being registered for `SDL_HINT_JOYSTICK_ENHANCED_REPORTS` instead of `SDL_HINT_JOYSTICK_HIDAPI_PS5_PLAYER_LED`.
This tiny patch changes the hint callback to match …
> joystick: Fix PS5 player LED hint change callback name

- src/audio/pipewire/SDL_pipewire.c
PipeWire now requires the correct struct type is used, otherwise it will fail to compile.
Reference: https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/188d920733f0791413d3386e5536ee7377f71b2f
Fixes: https://github.com/libsdl-org/SDL/issues/12224
> pipewire: Ensure that the correct struct is used for enumeration APIs

- src/render/vulkan/SDL_render_vulkan.c
The problem was if the size of the vertex buffer was exceeded, the currentVertexBuffer would be reset to zero and thus we'd leave it pointing to an in-use VB that would get overwritten on the next present before the vkQueueSubmit occurred.
Fixed to make sure the currentVertexBuffer is always set correctly.
#12142
> Fix #12142 - VB being overwritten during Present

- src/video/wayland/SDL_waylandwindow.c
This will be needed later, after libdecor passes through toplevel bounds, but for now it causes a crash in the Cairo plugin, so remove it.
Fixes #12258
> wayland: Don't set libdecor frame visibility before the first commit

- src/render/direct3d11/SDL_render_d3d11.c
- src/render/direct3d12/SDL_render_d3d12.c
- src/render/gpu/SDL_render_gpu.c
- src/render/opengles2/SDL_render_gles2.c
- src/render/vulkan/SDL_render_vulkan.c
This is the output format of stb_image for image decoding, so let's avoid a texture format conversion where possible.
Also standardized SDL_PIXELFORMAT_ARGB8888 as the default texture format for all renderers.
> Added support for SDL_PIXELFORMAT_ABGR8888 textures

- src/gpu/d3d12/SDL_gpu_d3d12.c
Code used wcslen that return number of characters, but D3D12 debug layer uses bytes + wide chars
> [GPU] D3D12 backend debug markers were being cut

- src/tray/unix/SDL_tray.c
`SDL_CreateTray` missed a check for `icon` being non-NULL before using it as the tray icon in the AppIndicator implementation. This PR adds the missing check.
> Check for non-NULL icon for trays on Unix

- src/audio/SDL_audio.c
- src/audio/SDL_sysaudio.h
- src/audio/pipewire/SDL_pipewire.c
- src/video/SDL_sysvideo.h
- src/video/SDL_video.c
- src/video/wayland/SDL_waylandvideo.c
Preferred driver entries have special conditions for initializing, which aren't relevant when a specific driver was explicitly requested.
Fixes #12247
> audio/video: Skip preferred drivers when loading a driver on demand

- src/events/SDL_mouse.c
Currently the relative mouse position is only set if relative mouse mode is enabled.
That makes `SDL_GetRelativeMouseState()` only work in relative mouse mode.
This commit removes the check for relative mouse mode and lets the variables be always set.
Fixes #12286
> SDL_GetRelativeMouseState(): Get relative mouse position also when relative mouse mode is disabled

- src/video/windows/SDL_windowsmouse.c
In the `WIN_CreateSystemCursor` function, the `SDL_SYSTEM_CURSOR_PROGRESS` case is using `IDC_WAIT` instead of the appropriate `IDC_APPSTARTING` cursor. Both `SDL_SYSTEM_CURSOR_WAIT` and `SDL_SYSTEM_CURSOR_PROGRESS` would display the same static hourglass cursor, failing to differentiate between waiting and in-progress states.
Replaced `IDC_WAIT` with `IDC_APPSTARTING`.
> Fixed Cursor Icon State for SYSTEM_CURSOR_PROGRESS

- src/audio/SDL_audio.c
- src/camera/SDL_camera.c
- src/render/SDL_render.c
- src/video/SDL_video.c
When passing an invalid index to `SDL_GetNumVideoDrivers()` it returns NULL.
This commit adds an error message.
> SDL_Get*Driver() functions: Set error message on failure

- src/test/SDL_test_harness.c
Clang-Tidy with the check `clang-analyzer-unix.Malloc` shows a potential leak in `src/test/SDL_test_harness.c`.
This would happen if the function prematurely returns when an error happens.
This commit frees the variables before the function returns prematurely.
Warning:
```shell
[ 49%] Building C object CMakeFiles/SDL3_test.dir/src/test/SDL_test_harness.c.o
/path/to/SDL/src/test/SDL_test_harness.c:518:16: warning: Potential leak of memory pointed to by 'failedTests' [clang-analyzer-unix.Malloc]
518 |         return SDL_OutOfMemory();
|                ^
/path/to/SDL/src/test/SDL_test_harness.c:407:9: note: Assuming field 'testIterations' is >= 1
407 |     if (runner->user.testIterations < 1) {
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/path/to/SDL/src/test/SDL_test_harness.c:407:5: note: …
```
> src/test/SDL_test_harness.c: Free variables before returning

- test/testautomation_intrinsics.c
Clang-Tidy with the check `clang-analyzer-unix.Malloc` shows potential leaks in `test/testautomation_intrinsics.c`.
This would happen if the function prematurely returns when an error happens.
This commit frees variables before the function returns prematurely.
<details><summary>Warnings Log</summary>
<p>
```shell
[ 57%] Building C object test/CMakeFiles/testautomation.dir/testautomation_intrinsics.c.o
/path/to/SDL/test/testautomation_intrinsics.c:432:24: warning: Potential leak of memory pointed to by 'a' [clang-analyzer-unix.Malloc]
432 |                 return TEST_ABORTED;
|                        ^
/path/to/SDL/include/SDL3/SDL_test_harness.h:51:30: note: expanded from macro 'TEST_ABORTED'
51 | #define TEST_ABORTED        -1
|                              ^ …
```
> test/testautomation_intrinsics.c: Free variables before returning

- test/testaudio.c
Adding an assert, that a list node, with a pointer to a previous node, is not the start of the list.
This gets rid of a clang-tidy "use after free" warning:
```shell
[ 65%] Building C object test/CMakeFiles/testaudio.dir/testaudio.c.o
/path/to/SDL/test/testaudio.c:1262:9: warning: Use of memory after it is freed [clang-analyzer-unix.Malloc]
1262 |         DestroyThing(things);  /* make sure all the audio devices are closed, etc. */
|         ^            ~~~~~~
/path/to/SDL/test/testaudio.c:1261:5: note: Loop condition is true.  Entering loop body
1261 |     while (things) {
|     ^
/path/to/SDL/test/testaudio.c:1262:9: note: Calling 'DestroyThing'
1262 |         DestroyThing(things);  /* make sure all the audio devices are closed, etc. */
|         ^~~~~~~~~~~~~~~~~~~~ …
```
> test/testaudio.c: Fix use-after-free warning

- src/video/wayland/SDL_waylandcolor.c
- src/video/wayland/SDL_waylandcolor.h
- src/video/wayland/SDL_waylandvideo.c
- src/video/wayland/SDL_waylandvideo.h
- src/video/wayland/SDL_waylandwindow.c
- src/video/wayland/SDL_waylandwindow.h
- wayland-protocols/color-management-v1.xml
Supports the official wp_color_manager_v1 protocol.
> wayland: Add color manager protocol support

- src/audio/pulseaudio/SDL_pulseaudio.c
Moving the `SDL_AddAudioDevice(recording, description, &spec, handle);` call
so it only gets executed if `handle->device_path` is valid and therefore `handle` wasn't freed.
```shell
[ 30%] Building C object CMakeFiles/SDL3-shared.dir/src/audio/pulseaudio/SDL_pulseaudio.c.o
path/to/SDL/src/audio/pulseaudio/SDL_pulseaudio.c:782:9: warning: Use of memory after it is freed [clang-analyzer-unix.Malloc]
782 |         SDL_AddAudioDevice(recording, description, &spec, handle);
|         ^
path/to/SDL/src/audio/pulseaudio/SDL_pulseaudio.c:789:9: note: Assuming 'i' is non-null
789 |     if (i) {
|         ^
path/to/SDL/src/audio/pulseaudio/SDL_pulseaudio.c:789:5: note: Taking true branch
789 |     if (i) {
|     ^
path/to/SDL/src/audio/pulseaudio/SDL_pulseaudio.c:790:9: note: Calling …
```
> AddPulseAudioDevice(): Fix use-after-free

- src/video/windows/SDL_windowsclipboard.c
In `WIN_ConvertDIBtoBMP`, the code incorrectly uses `sizeof(BITMAPINFOHEADER)` instead of `pbih->biSize` to calculate the offset to pixel data in the BMP header. This leads to invalid BMP files when the DIB uses a header larger than BITMAPINFOHEADER.
Replaced `sizeof(BITMAPINFOHEADER)` with `pbih->biSize` as it represents the actual size of the DIB header (e.g., 40, 108 bytes), ensuring the correct offset to pixel data.
> Incorrect bfOffBits Calculation in WIN_ConvertDIBtoBMP

- src/video/windows/SDL_windowsmouse.c
> If I'm not mistaken, this code block is redundant, because `goto` jumps to `error`,  which then frees the memory.
> 
> 
> 
> In the case of the `entry` variable, its memory doesn't have to be freed at all inside this function. Either its allocation succeeded and its variable will be placed in `data->cache`, or the allocation returned `NULL` and freeing it is a noop.
> 
> 
> 
> BUT, I think this code block introduced a double-free. 
> 
> If `entry` is `NULL` it frees `hcursor`, and after the jump to `error` it does it again.
> 
>  
_Originally posted by @Sackzement in [a513168](https://github.com/libsdl-org/SDL/commit/a51316890218c89fa3350178cbe2c79146a01d2e#r152660538)_
Based on this input from @Sackzement, we can remove the code block to prevent double-free.
> Removing Double-free Issue

- src/video/windows/SDL_windowsvideo.c
In `WIN_SuspendScreenSaver` function, the code does not check the return value of `SetThreadExecutionState`, leading to incorrect success reporting.
Check the return value and return `true` only if the API call succeeds.
> Unchecked Return Value in WIN_SuspendScreenSaver

- src/render/SDL_render.c
I ran into the usage of `restrict` breaking builds targeting Windows XP, as the v141 MSVC toolset doesn't support the keyword.
> Remove usages of `restrict` keyword in SDL_render.c

- src/audio/emscripten/SDL_emscriptenaudio.c
Verified locally by running `browser64.test_sdl2_mixer_wav` in emscripten.
> Fix SDL_emscriptenaudio.c under wasm64

- src/thread/windows/SDL_systhread.c
RaiseException expects the size in units of ULONG_PTR, rather than ULONG. The Microsoft documentation also does this: https://learn.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2015/debugger/how-to-set-a-thread-name-in-native-code?view=vs-2015
This means the size passed by SDL is double the amount expected on 64-bit systems, possibly overflowing the stack.
> thread/windows: fix stack overflow in exception naming

- examples/input/01-joystick-polling/joystick-polling.c
- examples/renderer/09-scaling-textures/scaling-textures.c
- src/audio/SDL_audio.c
- src/camera/SDL_camera.c
- src/events/SDL_mouse.c
- src/gpu/vulkan/SDL_gpu_vulkan.c
- src/render/vulkan/SDL_render_vulkan.c
- src/test/SDL_test_fuzzer.c
- src/video/wayland/SDL_waylandvideo.c
- src/video/x11/SDL_x11events.c
- src/video/x11/SDL_x11pen.c
- src/video/x11/SDL_x11shape.c
- src/video/x11/SDL_x11xinput2.c
- src/video/x11/SDL_x11xsync.c
- test/testaudiohotplug.c
- test/testautomation_render.c
- test/testdraw.c
- test/testdrawchessboard.c
- test/testrendercopyex.c
- test/testrendertarget.c
- test/testscale.c
- test/testviewport.c
^^ vv
```shell
[ 12%] Building C object CMakeFiles/SDL3-shared.dir/src/audio/SDL_audio.c.o
/path/to/SDL/src/audio/SDL_audio.c:892:39: warning: redundant cast to the same type [google-readability-casting]
892 |     const SDL_AudioDeviceID highest = (SDL_AudioDeviceID) SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK;  // According to AssignAudioDeviceInstanceId, nothing can have a value this large.
|                                       ^~~~~~~~~~~~~~~~~~~
[ 13%] Building C object CMakeFiles/SDL3-shared.dir/src/camera/SDL_camera.c.o
/path/to/SDL/src/camera/SDL_camera.c:652:26: warning: redundant cast to the same type [google-readability-casting]
652 |     SDL_Camera *device = (SDL_Camera *) camera;  // currently there's no separation between physical and logical device.
| …
```
> Remove redundant casts

- include/SDL3/SDL_assert.h
I am encountering this problem with gcc 9 in an arm64 environment roughly comparable to Debian bullseye.
> fallback to defining SDL_TriggerBreakpoint as __builtin_trap in older linux arm64 environments that do not have a __has_builtin facility

- src/video/cocoa/SDL_cocoakeyboard.m
use utf32 encoding for SDL_TextEditingEvent.start and .length (from utf16) for macos
fix #12344
> make start&length represent utf32 indices (macos)

- src/audio/SDL_audioresample.c
- src/audio/alsa/SDL_alsa_audio.c
- src/gpu/vulkan/SDL_gpu_vulkan.c
- src/joystick/SDL_gamepad.c
- src/video/wayland/SDL_waylanddatamanager.c
- test/testgpu_spinning_cube.c
Add 'const' to pointer parameters under src/ and test/ which are not modified in the function definitions.
```shell
[ 12%] Building C object CMakeFiles/SDL3-shared.dir/src/audio/SDL_audioresample.c.o
/path/to/SDL/src/audio/SDL_audioresample.c:447:26: warning: pointer parameter 'table' can be pointer to const [readability-non-const-parameter]
447 | static float Sinc(float *table, int x, int y)
|                          ^
|                   const 
[ 16%] Building C object CMakeFiles/SDL3-shared.dir/src/joystick/SDL_gamepad.c.o
/path/to/SDL/src/joystick/SDL_gamepad.c:431:68: warning: pointer parameter 'src' can be pointer to const [readability-non-const-parameter]
431 | static void AdjustSensorOrientation(SDL_Joystick *joystick, float *src, float *dst)
| …
```
> Add 'const' to pointer parameters

- src/camera/v4l2/SDL_camera_v4l2.c
- test/testcamera.c
`format_sdl_to_v4l2` did not map `SDL_PIXELFORMAT_MJPG` to `V4L2_PIX_FMT_MJPEG`.
I also changed the return value to `0` when it get an unknown pixel format. I'm not sure what's appropriate here.
Fixes #12358
> Fix v4l2 camera

- src/video/SDL_stb.c
- src/video/openvr/SDL_openvrvideo.c
- src/video/stb_image.h
I integrated changes from SDL_image and updated as needed for JPEG memory loading functionality.
Fixes https://github.com/libsdl-org/SDL/issues/12364
> Fix errors when building stb_image with -DSDL_LIBC=OFF

- docs/README-linux.md
Fcitx related support only relies on libdbus.
> Remove unnecessary fcitx's devel package dependency in linux doc

- src/io/SDL_asyncio.c
```shell
[ 16%] Building C object CMakeFiles/SDL3-shared.dir/src/io/SDL_asyncio.c.o
/path/to/SDL/src/io/SDL_asyncio.c:69:26: warning: Access to field 'lock' results in a dereference of a null pointer (loaded from variable 'asyncio') [clang-analyzer-core.NullDereference]
69 |         SDL_DestroyMutex(asyncio->lock);
|                          ^
/path/to/SDL/src/io/SDL_asyncio.c:299:9: note: Assuming 'file' is non-null
299 |     if (!file) {
|         ^~~~~
/path/to/SDL/src/io/SDL_asyncio.c:299:5: note: Taking false branch
299 |     if (!file) {
|     ^
/path/to/SDL/src/io/SDL_asyncio.c:301:16: note: Assuming 'queue' is non-null
301 |     } else if (!queue) {
|                ^~~~~~
/path/to/SDL/src/io/SDL_asyncio.c:301:12: note: Taking false branch
301 |     } else if (!queue) {
| …
```
> src/io/SDL_asyncio.c:SDL_AsyncIOFromFile(): Fix null-dereference warning

- include/SDL3/SDL_gpu.h
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
There are a small handful of features we expose in SDL_GPU that are not universally supported across devices/backends. I've added documentation to denote these potential pitfalls and removed a couple misfeatures from the backend logic.
Resolves https://github.com/libsdl-org/SDL/issues/12093
> Document/ignore GPU features without universal support

- include/SDL3/SDL_gpu.h
- src/gpu/SDL_gpu.c
Adding some documentation and debug validation for the newly "reserved for future use" struct members in the GPU API. Addresses the feedback from https://github.com/libsdl-org/SDL/pull/12373. 
(In the process I also caught a validation issue where we weren't returning NULL for a failed assertion in `CreateGPUGraphicsPipeline`.)
> gpu: Validate that reserved struct members are unset

- src/gpu/vulkan/SDL_gpu_vulkan.c
Fixes #12383.
Initialize memory that may be read later.
RenderDoc and similar tools will no longer read uninitialized memory for the color. They will instead read transparent.
https://github.com/libsdl-org/SDL/issues/12383
> gpu: initialize VkDebugUtilsLabelEXT::color

- include/SDL3/SDL_hints.h
- src/haptic/SDL_haptic.c
My idea is to introduce `SDL_HINT_JOYSTICK_HAPTIC_AXES` (subject to change) that could overwrite haptic->naxes for a given VID:PID similar to `SDL_HINT_JOYSTICK_DEVICE` but with added naxes value. Example: `SDL_JOYSTICK_HAPTIC_AXES="0x1234/0xABCD/0x1"`
Description can be found in the linked issue.
This will help in fixing force feedback in some rouge games like Richard Burns Rally which tries to change `cAxes` value of an already create effect which leads to direct input errors and non-functioning force feedback.
Apart from that, this isn't final form as I'd like some pointers or maybe I did it in a way that's not great. This implementation is based on hod loading VIDPID lists work. I'll clean up commits and their descriptions in the coming days.
To test, I've used a modified wine build …
> [SDL3] Add SDL_HINT_JOYSTICK_HAPTIC_AXES

- VisualC-GDK/SDL/SDL.vcxproj
- VisualC-GDK/SDL/SDL.vcxproj.filters
- VisualC/SDL/SDL.vcxproj
- VisualC/SDL/SDL.vcxproj.filters
- Xcode/SDL/SDL.xcodeproj/project.pbxproj
- src/events/SDL_events.c
- src/events/SDL_eventwatch.c
- src/events/SDL_eventwatch_c.h
- src/events/SDL_windowevents.c
- src/render/SDL_render.c
- src/render/SDL_sysrender.h
- src/video/cocoa/SDL_cocoametalview.m
Also refactored event watch code so it can be shared between internal window event dispatch and public event watchers.
Fixes https://github.com/libsdl-org/SDL/issues/12376
> Cocoa metal layers need their size updated before renderer updates

- include/SDL_hints.h
- src/haptic/SDL_haptic.c
SDL2 version of #12367 
Related issue: #12341 
Allows users to overwrite the number of haptic axes defined for a given joystick.
Since this isn't changing any existing APIs and behavior I ported it to SDL2. The reason being many distros will still rely on SDL2 and officially, many big SDL consumers like Wine, support only SDL2 (though I haven't had any issues with SDL2-compat which works great).
Builds without errors/warnings on local machine.
> [SDL2] Add SDL_HINT_JOYSTICK_HAPTIC_AXES

- include/SDL3/SDL_stdinc.h
I believe this header isn't necessary for clang-tidy, string.h has all the functions we care about.
Fixes https://github.com/libsdl-org/SDL/issues/12238
> strings.h isn't available in Windows environments

- src/gpu/vulkan/SDL_gpu_vulkan.c
Our Vulkan memory allocation strategy is to do large heap allocations at a time (64MB or larger) and then slice out sections of them for resource binding. This means we have to defragment regularly or else holes will appear in the allocations. 
The defrag process creates a new buffer on an available unfragmented allocation and then preserves data by enqueueing a copy command to preserve the data. We do the copy for GPU buffers, but we skip it for transfer buffers. This causes an issue where persistently-used upload transfer data is corrupted. An easy solution for this is to do what we did for download transfer buffers and make them dedicated allocations, meaning that they live alone on a heap allocation. 
The only drawback is the `maxMemoryAllocationCount` limit. The most common driver …
> GPU: Make Vulkan transfer buffers dedicated allocs

- src/events/SDL_clipboardevents.c
[This issue](https://github.com/libsdl-org/SDL/issues/12152) happens because SDL receives a data offer that was sent by itself.
https://github.com/libsdl-org/SDL/blob/69803253100111f870c068300d336edac19783b4/src/video/wayland/SDL_waylandevents.c#L2500
Then it assumes that the received event is from another client, and cleans up our clipboard contents.
https://github.com/libsdl-org/SDL/blob/69803253100111f870c068300d336edac19783b4/src/events/SDL_clipboardevents.c#L29-L35
I'm not sure if this is a right way to fix, because `owner` field of `SDL_ClipboardEvent` becomes basically useless on Wayland, but I couldn't find out a way to confirm that `wl_data_offer` did not come from SDL itself.
This PR fixes it by not cleaning up clipboard until the app sets clipboard next time, but I know that …
> Don't cleanup clipboard in SDL_SendClipboardUpdate

- src/events/SDL_events.c
- test/testautomation_events.c
Also added a test case to catch the main thread waiting indefinitely when a function is pending.
Fixes https://github.com/libsdl-org/SDL/issues/12390
> Wake the main thread for main function dispatch

- src/gpu/d3d12/SDL_gpu_d3d12.c
Only set the depth texture format if the user specifies that they have a depth stencil target.
Sometimes I reuse `SDL_GPUGraphicsPipelineCreateInfo` to reduce boilerplate. If you:
1.
- Set the depth stencil format
- Set `has_depth_stencil_target` to `true`
2.
- Set `has_depth_stencil_target` to `false`
Your console will be spammed with D3D12 errors such as:
D3D12 ERROR: ID3D12CommandList::DrawInstanced: The depth stencil format does not match that specified by the current pipeline state. A null depth stencil view may only be bound when the pipeline state depth stencil format is UNKNOWN. (pipeline state = D32_FLOAT, DSV ID3D12Resource* = 0x0000000000000000:'(nullptr)') [ EXECUTION ERROR #615: DEPTH_STENCIL_FORMAT_MISMATCH_PIPELINE_STATE]
> Change D3D12 GPU backend to respect has_depth_stencil_target

- src/filesystem/SDL_filesystem.c
The underlying pattern matcher `WildcardMatch` does not handle Windows path separators, because of that `*` matches entire path all the way down the hierarchy.
For example, the following call will scan and match entire filesystem in Windows:
```c
SDL_GlobDirectory("C:\\", "*", 0, NULL);
```
The fix normalizes separator to `/` so that path and pattern look for the same thing.
> Windows: Fix SDL_GlobDirectory

- src/events/SDL_pen.c
- src/joystick/linux/SDL_sysjoystick.c
OpenscanHub found a bunch of issues in the SDL3 code, which may or may not be false positives.
I think that the 2 attached patches fix an actual problem and I ask to review and apply them.
> Some assorted fixes

- src/events/SDL_mouse.c
The functions which dispatch mouse events were not taking into account that a pen may be the source of an event, so I've added tests for `SDL_PEN_MOUSEID` in places where they already check for `SDL_TOUCH_MOUSEID` so that pen and touch will behave the same when generating mouse events.
Commit [680ac7](https://github.com/libsdl-org/SDL/commit/680ac762584b2be9059af8849721797a40f37200) then fixes a related issue I found that isn't listed that requires the previous commits to function:
If `SDL_HINT_PEN_MOUSE_EVENTS` and `SDL_HINT_MOUSE_TOUCH_EVENTS` are both enabled, the pen generated synthetic mouse event will then produce a touch event with `SDL_MOUSE_TOUCHID` without this additional check to identify a pen as the source. It can't identify a pen as a source without `SDL_PEN_MOUSEID` being …
> Fix pen generated mouse events not having SDL_PEN_MOUSEID 

- src/gpu/d3d12/SDL_gpu_d3d12.c
Since there is no option to change it this seems like a much better default value. The stretching behaviour is really off-putting.
The new behavior shows a small black border when resizing the windows. This makes it more in line with the other backends and it's what you would expect to happen as a user.
> GPU_d3d12: Switched the default swapchain scaling mode to none.

- src/camera/SDL_camera.c
> camera: clear the spec when closing, so re-opening can probe again

- include/SDL3/SDL_render.h
- src/render/SDL_render.c
- src/render/SDL_sysrender.h
New functions to set default scale mode for newly created textures per renderer and get current scale mode set for given renderer.
This will save using `SDL_SetTextureScaleMode` every time we create new texture and want to use nearest-point scale instead of linear. Helpful for pixel art games where everything should be scaled to nearest-point.
* SDL_SetDefaultTextureScaleMode(SDL_Renderer *renderer, SDL_ScaleMode scale_mode)
* SDL_GetDefaultTextureScaleMode(SDL_Renderer *renderer, SDL_ScaleMode *scale_mode)
#11919
> Function to change default texture scale mode per renderer

- include/SDL3/SDL_render.h
- src/render/SDL_render.c
- test/testautomation_render.c
New function `SDL_RenderTexture9GridTiled`, borders and center is tiled instead of stretched. This is a known alternative method for 9-slicing.
Here is the difference (right is tiled):
> Added tiled 9-grid texture rendering function

- include/SDL3/SDL_mouse.h
- src/events/SDL_mouse.c
- src/events/SDL_mouse_c.h
- src/video/wayland/SDL_waylandevents.c
This PR introduces a new API function `SDL_SetRelativeMouseTransform`, which lets app developers add a callback that hooks into SDL's relative mouse input processing to modify the resultant delta value. When set, this overrides the default relative speed/system scaling functionality, giving full control to the developer to scale from raw deltas.
Because this is a callback, developers can also do their own bookkeeping on incoming mouse deltas inside their function, potentially enabling usecases such as a userland implementation of per-device relative mouse accumulator states leveraging the multithreaded setup of some platforms for low-latency asynchronous writes instead of needing to go through the event queue.
(For the record, the refactor of this PR was also partially motivated by me …
> add `SDL_SetRelativeMouseTransform`

- src/camera/pipewire/SDL_camera_pipewire.c
- src/core/linux/SDL_dbus.c
- src/core/linux/SDL_dbus.h
This helps the Pipewire camera driver to access cameras in a sandboxed environment without host Pipewire socket access. Unlike other platforms, no event is sent when the user rejects camera access. This is because there is no mechanism to query cameras through the portal, and we only obtain access to the Pipewire fd if the user accepts the request. The Pipewire driver will attempt to open the host socket instead.
Maybe allowing a `SDL_GetCameraPermissionState` call happen before `SDL_GetCameras` could work? I didn't bother doing any API change for now.
> camera/pipewire: Implement the XDP Camera portal

- src/camera/pipewire/SDL_camera_pipewire.c
The Debian 12 'bookworm' stable release only has 0.3.65, which is earlier than the introduction of that symbol. Similarly, Steam Runtime 3 'sniper' and Steam Runtime 2 'soldier' have a backport of 0.3.65 from Debian 12, so they have the same limitation.
steamrt/tasks#686
> pipewire: Don't require pw_check_library_version() with Pipewire < 0.3.75

- src/video/SDL_sysvideo.h
- src/video/SDL_video.c
This is true if fullscreen is pending or currently active. This is a better check in SDL_SetDesktopDisplayMode() because a fullscreen mode may be pending and complete asynchronously and the window hasn't been set to fullscreen yet.
> Added fullscreen_active to better track fullscreen state

- src/video/x11/SDL_x11messagebox.c
I noticed that using SDL_ShowSimpleMessageBox doesn't work on my system, by using valgrind to track the issue, I noticed that XCreateFontSet fails and noticed that
1. All of font descriptions included in SDL3's g_MessageBoxFont don't work on my system
2. Using comma separated list of font descriptions may still fail even if valid font description is present in the list
I fixed the first problem by adding "misc" to the font description list for both Unicode and Latin1.
I fixed the second problem by iterating over all font descriptions, instead of using comma separated list, which can fail.
I managed to fix the issue and message boxes now appear on my screen! (Screenshot included):
> Fix for Message Box failing to init on X11

- src/video/SDL_video.c
- src/video/x11/SDL_x11video.c
Openbox doesn't send size or position events when entering fullscreen, so they must be synthesized. This is not desirable on any other window manager that does send size and position information, as it can break fullscreen positioning on multi-monitor configurations.
Fixes libsdl-org/sdl2-compat#393
> x11: Synthesize fullscreen size events on Openbox

- src/video/x11/SDL_x11window.c
External windows often handle their own events, and SDL implicitly processing events during synchronization can be unexpected and cause issues. For requests that don't change the window state beyond size or position, use the legacy synchronization method that synthesizes events from the window attributes without processing events.
Fixes libsdl-org/sdl2-compat#262
> x11: Don't implicitly process events for external windows

- src/render/SDL_render.c
The platforms that needed this (Windows Phone and Windows RT) are no longer supported, and if this is needed in the future it should be done at the renderer level, not here.
Fixes https://github.com/libsdl-org/SDL/issues/12475
> Removed logic forcing vsync on if setting it off fails

- docs/INTRO-cmake.md
- docs/INTRO-mingw.md
- docs/INTRO-visualstudio.md
Based on helping folks in the Discord, I've decided to revise some of the existing INTRO readmes.
- The readme wasn't clear about how to actually get SDL, so this was adjusted to recommend downloading a release of the source.
- The readme suggested modifying the VC++ directories property. This can easily become a footgun for beginners, who might accidentally wipe out the directories here. Additionally these directories aren't generally where people should be going to add includes, so now we direct them to the appropriate property page/section.
- Minor touchup to how we describe the menuing. 
- This readme also wasn't clear about acquiring SDL.
- Touched up how we describe where the executable lives after building, trying to not go into full detail.
We have a lot of folks coming to SDL …
> Added MinGW Intro readme, touched up CMake and Visual Studio readmes.

- src/video/cocoa/SDL_cocoawindow.m
> cocoa: Ignore both clicks and motion on tooltip windows

- src/thread/n3ds/SDL_syssem.c
`if (sem) return;` -> `if (!sem) return;`
> Fix n3ds/SDL_syssem.c:SDL_SignalSemaphore (libsdl-org/SDL#12411)

- src/video/emscripten/SDL_emscriptenevents.c
With ASAN enabled the existing code triggered a `null-pointer-dereference` in the `strcmp` since `EMSCRIPTEN_EVENT_TARGET_WINDOW` is a "fake" pointer with the value `((const char*)2)`. In fixing this it was also noticed that using the `#window/#document/#screen` targets as mentioned in the docs fails since `document.querySelector()` returns `null` for them and we should instead be mapping them to the special HTML targets provided.
Possibly relates to #12073.
> emscripten: Fix handling of special HTML targets

- src/events/SDL_mouse.c
- src/events/SDL_mouse_c.h
This adds an internal hint to be used by sdl2-compat to provide integer values in mouse events, `SDL_GetMouseState()`, `SDL_GetRelativeMouseState()`, etc. I'm assuming we don't want to expose this to regular SDL3 users, though I can move it to `SDL_hints.h` if we do want that.
This avoids a number of pitfalls with the current approach in https://github.com/libsdl-org/sdl2-compat/pull/378 like:
- Sending "duplicate" events when not enough fractional motion has accumulated to reach the next integer value
- Inconsistency between x/y and xrel/yrel values received by SDL2 apps due to the hidden fractional component (see https://github.com/libsdl-org/sdl2-compat/issues/372#issuecomment-2691888221)
- Changing global accumulator state in a function that may be called to process the same event …
> mouse: Add internal integer mouse mode hint for sdl2-compat

- src/video/windows/SDL_windowsevents.c
Fixes undefined behavior introduced in https://github.com/libsdl-org/SDL/commit/69d28027adb70daf962621bb5e8ab00a069cbe30, reported downstream in https://github.com/david-vanderson/dvui/issues/198 :
If `cursorPos.y` is negative (which it is when clicking on a window's title bar), the left shift is undefined behavior.
(for reference: https://learn.microsoft.com/en-us/cpp/code-quality/c26453?view=msvc-170).
This was caught downstream by a panic when using LLVM's ubsan (undefined behavior sanitizer).
The code formulation in this PR first asserts that the value is in bounds for `short` (16-bit),
then converts & promotes the value to `unsigned int` (32-bit) to ensure the shift is legal.
The alternative would be to simply `& 0xFFFF` the operand.
This would hide any out-of-bounds values for (`< …
> avoid UB (left shift of negative number) in SDL_windowsevents.c

- src/stdlib/SDL_string.c
- test/testautomation_stdlib.c
Fixes https://github.com/libsdl-org/SDL/issues/12510
> Fixed sscanf("#026", "#%1x%1x%1x", &r, &g, &b)

- include/SDL3/SDL_hints.h
- include/SDL3/SDL_video.h
- src/video/emscripten/SDL_emscriptenevents.c
- src/video/emscripten/SDL_emscriptenvideo.c
- src/video/emscripten/SDL_emscriptenvideo.h
Move hints used by Emscripten to window properties. This change will be necessary if multiple windows for Emscripten will be supported in the future.
- ~~Removed hint `SDL_HINT_EMSCRIPTEN_CANVAS_SELECTOR`~~
- ~~Removed hint `SDL_HINT_EMSCRIPTEN_KEYBOARD_ELEMENT`~~
- Added Window Create Property `SDL_PROP_WINDOW_CREATE_EMSCRIPTEN_CANVAS_ID`
- Added Window Create Property `SDL_PROP_WINDOW_CREATE_EMSCRIPTEN_KEYBOARD_ELEMENT`
-  Use hint `SDL_HINT_EMSCRIPTEN_CANVAS_SELECTOR` as override to `SDL_PROP_WINDOW_CREATE_EMSCRIPTEN_CANVAS_ID`
- Use hint `SDL_HINT_EMSCRIPTEN_KEYBOARD_ELEMENT` as override to `SDL_PROP_WINDOW_CREATE_EMSCRIPTEN_KEYBOARD_ELEMENT`
> emscripten: move hints to window properties

- src/events/SDL_mouse.c
- src/events/SDL_mouse_c.h
SDL 2.0.18 added preciseX/Y to mouse wheel events for smooth scrolling, which we cannot emulate in sdl2-compat without a mechanism to control integer position and scroll deltas separately. This converts `SDL_MOUSE_INTEGER_MODE` from a boolean hint into an integer hint where `1` converts mouse coordinates only and `2` converts both mouse coordinates and wheel deltas.
> mouse: Allow use of integer coordinates with fractional wheel events

- examples/demo/01-snake/snake.c
- add SDL_Joystick pointer
- add SDL_JOYSTICK_INIT and SDL_CLOSEJOYSTICK checks to app start and close
- add separate handler for Joystick HAT changes
- add events to main loop's switch statement
- JOYSTICK_ADDED
- JOYSTICK_REMOVED
- HAT_MOTION
- Only D-pad HAT is implemented; stick and buttons may function but not configurable (but neither is keyboard)
- JOYSTICK_HAT_MOTION is implemented separately from KEYDOWN to control the snake. This is fine for now, but ideally, each possible input handler should be abstracted to an action to pass into the switch statement to influence the snake.
> Add SDL_Joystick support to Snake demo example

- src/video/SDL_video.c
Some backends can't actually position a window until it is shown/mapped, so assume that it will be where it was asked to be as long as it is hidden.
Fixes libsdl-org/sdl2-compat#415
> video: Send pending coordinates for moved, hidden windows

- src/gpu/vulkan/SDL_gpu_vulkan.c
Since we restructured presentation, in the typical path Wait is called before acquiring a swapchain texture to prevent the GPU from getting too far ahead. Wait triggers command buffer cleanup. However, originally the backend assumed that command buffers were always cleaned up inside of Submit, and if a command buffer was cleaned this triggered the deallocation check. In light workloads command buffers tend to be cleaned up inside of Wait. This meant that the deallocation was never triggered.
The fix is to set a flag on VulkanRenderer that is triggered when a memory region is freed and the allocation has 0 remaining used regions. If this flag is set to 1, we check for empty allocations and deallocate them in Submit. 
Resolves #12507
> GPU: Fix Vulkan backend never checking deallocations

- src/render/SDL_render.c
Trying to return a boolean here instead of a pointer was causing compilation failure.
> Fix return type in SDL_CreateGPURenderState

- src/gpu/metal/SDL_gpu_metal.m
Fixes a use-after-free when creating METALLIB shaders. I was under the incorrect impression that `dispatch_data_create` implicitly copied the data passed to it, but [according to the docs](https://developer.apple.com/documentation/dispatch/1452970-dispatch_data_create) a copy is only made if the destructor is set to the constant `DISPATCH_DATA_DESTRUCTOR_DEFAULT`.
Resolves https://github.com/libsdl-org/SDL/issues/12569
> gpu: Fix MTLLibrary dispatch data destructor

- src/gpu/vulkan/SDL_gpu_vulkan.c
This is just a small fix, somebody forgot to reassign the Vulkan result before checking it again.
> Fix Vulkan error check

- src/render/opengles2/SDL_render_gles2.c
Discovered this while building SDL3 and the Snake example for Emscripten with [UBSan](https://emscripten.org/docs/debugging/Sanitizers.html). With the sanitizer enabled, running the example logs:
```
<omitted>/src/render/opengles2/SDL_render_gles2.c:1024:74: runtime error: subtraction of unsigned offset from 0x00000000 overflowed to 0x00000000
<omitted>/src/render/opengles2/SDL_render_gles2.c:1025:118: runtime error: member access within null pointer of type 'SDL_VertexSolid' (aka 'struct SDL_VertexSolid')
<omitted>/src/render/opengles2/SDL_render_gles2.c:1026:131: runtime error: member access within null pointer of type 'SDL_VertexSolid' (aka 'struct SDL_VertexSolid')
```
The first error happens because the program is adding an offset to a null pointer, which is UB.
The second and third …
> emscripten: Fix undefined behavior in opengles2 renderer

- android-project/app/src/main/java/org/libsdl/app/HIDDeviceBLESteamController.java
- android-project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
- android-project/app/src/main/java/org/libsdl/app/HIDDeviceUSB.java
- android-project/app/src/main/java/org/libsdl/app/SDL.java
- android-project/app/src/main/java/org/libsdl/app/SDLAudioManager.java
- android-project/app/src/main/java/org/libsdl/app/SDLControllerManager.java
- android-project/app/src/main/java/org/libsdl/app/SDLDummyEdit.java
- android-project/app/src/main/java/org/libsdl/app/SDLInputConnection.java
- android-project/app/src/main/java/org/libsdl/app/SDLSurface.java
- docs/README-migration.md
- test/android/cmake/SDLEntryTestActivity.java.cmake
Most of SDL internals are already private by default (using `-fvisibility=hidden` and the version script).
So I think it makes sense to also reduce the visibility of the Java helper classes.
> android: reduce visiblity as much as possible

- include/SDL3/SDL_gpu.h
- src/gpu/vulkan/SDL_gpu_vulkan.c
Enable the `sampleRateShading` feature on Vulkan to allow running fragment shaders per-sample when using MSAA (i.e. effectively doing SSAA).
As support for this feature is nearly universal (99.1% in GPU info database), having it be mandatory shouldn't cause problems. Additionally, DirectX and Metal backends already provide it without needing any extra flags, so this seems like an easy addition bringing Vulkan to parity.
To activate per-sample shading you need to reference `gl_SampleID`/`SV_SampleIndex` in your fragment shader (correction: it seems that using a `sample` interpolation qualifier on your inputs is normally sufficient); this is consistent across all (public) GPU backends. Vulkan also allows to activate per-sample shading during pipeline creation, which would be nice to expose, …
> GPU: Request sampleRateShading feature on Vulkan

- src/video/SDL_surface.c
- test/testautomation_surface.c
Fixes https://github.com/libsdl-org/SDL/issues/12556
> Don't create surfaces with invalid pixel formats

- src/SDL_assert.c
Downstream issue: https://github.com/emscripten-core/emscripten/issues/21732
On Emscripten, `SDL_PromptAssertion()` uses `allocate()`, which is considered a legacy JS library function and is no longer included by default, which may result in JavaScript errors if legacy symbols are not included in the build (e.g. by passing `-sLEGACY_RUNTIME` to `emcc`). In addition to runtime errors, it will also prevent passing `--closure 1` to `emcc` to minify JS from working, see the issue linked above.
This is a simple fix that rewrites the relevant `SDL_PromptAssertion()` parts to avoid the need for allocations entirely.
The same problem is present in SDL2, so if this PR is merged, the fix should be backported to SDL2 as well.
> emscripten: Don't use legacy JS library functions for assertions

- include/build_config/SDL_build_config.h.cmake
Hi, I'm adding CMake support for some of the private targets, and for them to work with the automatically generated config file all these definitions are needed (well, at least some of them of course).
Maybe the most "controversial" one will be the last conditional include. I made it that way because that allows us to undefine certain automatically detected functions that are incorrectly detected, as well as manually add anything we need, but I'm open to suggestions about how to tackle that (without modifying the main `CMakeLists.txt` which was the whole point).
This is not the only thing needed, there are other things I needed but we can discuss them on their respective repos.
> add private definitions to SDL_build_config.h.cmake

- src/video/wayland/SDL_waylandevents.c
- src/video/x11/SDL_x11events.c
This can be tested with `testime`. In other applications, Ctrl/Alt+number does not result in a text input, but SDL sends a text input event on it.
I was looking for a better solution than simply filtering, but GLFW also filters text events on [X11](https://github.com/glfw/glfw/blob/master/src/x11_window.c#L1247)/[Wayland](https://github.com/glfw/glfw/blob/master/src/wl_window.c#L1199) while Ctrl/Alt is held, so I think this should be okay.
https://github.com/libsdl-org/SDL/issues/4695, but this also happens on X11 for me and some people on comments.
> Don't send text event while ctrl/alt is held on X11/Wayland

- src/gpu/vulkan/SDL_gpu_vulkan.c
If the window is flagged with SDL_WINDOW_TRANSPARENT, create the associated swapchain with a composite alpha value that supports blending, if available.
Fixes transparent windows on the Vulkan backend, and prevents possible validation errors by ensuring that the composite alpha value is always a valid bit in VkSurfaceCapabilitiesKHR::supportedCompositeAlpha.
To note, the DX 11 and 12 backends don't currently support transparent windows either. I tried implementing this for DX12, but all I was able to get was a black or empty window when using `IDXGIFactory4_CreateSwapChainForComposition`, even with all of the `DXGI_SWAP_CHAIN_DESC1` struct parameters seemingly set correctly and the function succeeding. Looking at the old DX12 renderer, it looks like transparent windows just don't work …
>  GPU: Support swapchain buffer transparency in Vulkan

- src/gpu/SDL_gpu.c
The GPU API doesn't currently support transparent windows (transparent swapchain effects doesn't seem possible on D3D12) so we should explicitly fail so users don't expect transparency and then not get it.
Fixes https://github.com/libsdl-org/SDL/issues/12410
> SDL_ClaimWindowForGPUDevice() should fail for transparent windows

- android-project/app/proguard-rules.pro
- android-project/app/src/main/java/org/libsdl/app/SDLAudioManager.java
remove un-needed proguard rule: onNativePen()
rename audio native function to have prefix "native" in their name
> proguard rules for native methods

- src/video/windows/SDL_windowswindow.c
Set `value` when calling `SDL_clamp()`.
Progress bar PR: https://github.com/libsdl-org/SDL/pull/12530
> WIN_SetWindowProgressValue(): Fix value clamp

- src/video/SDL_video.c
- src/video/windows/SDL_windowswindow.c
From https://github.com/libsdl-org/SDL/pull/12616
- Move `value` clamp from `WIN_SetWindowProgressValue()` to `SDL_SetWindowProgressValue()`, so it doesn't need to be implemented for every platform.
> SDL_SetWindowProgressValue(): Move value clamp from `WIN_SetWindowProgressValue()` to `SDL_SetWindowProgressValue()`

- include/SDL3/SDL_video.h
From https://github.com/libsdl-org/SDL/pull/12616
Add comments to:
`SDL_SetWindowProgressState()`:
- `SDL_PROGRESS_STATE_NONE` disables the progress bar.
`SDL_SetWindowProgressValue()`:
- Parameter `value` gets clamped.
- If the state is `SDL_PROGRESS_STATE_NONE` or `SDL_PROGRESS_STATE_INDETERMINATE`, it gets changed to `SDL_PROGRESS_STATE_NORMAL`.
> Additions to progress bar comments

- src/video/SDL_video.c
From https://github.com/libsdl-org/SDL/pull/12616
`SDL_SetWindowProgressState()`:
- Check if `state` is a valid parameter, return `SDL_InvalidParamError()`.
This adds a check if the `state` argument even exists before calling the platform specific function(where `SDL_Unsupported()` can be returned if a specific state is not supported on a platform)
> SDL_SetWindowProgressState(): Add parameter validation check for `state`

- src/video/windows/SDL_windowswindow.c
Currently, if `state` is a valid/existing parameter, but it not supported on a platform(in this case Windows) the error message is: "That operation is not supported" (from SDL_Unsupported())
This could be misinterpreted as: "This function is not supported"
This commit changes the function call `SDL_Unsupported()` into `SDL_SetError("Parameter 'state' is not supported")`.
A mixture of `SDL_InvalidParamError("state")` and `SDL_Unsupported()`.
> WIN_SetWindowProgressState(): Unsupported parameter error message

- src/events/SDL_keyboard.c
Calling `SDL_TextInputActive()` with a null window will clobber the last SDL error.
Fixes #12606
> keyboard: Don't check text input on a null window

- include/SDL3/SDL_stdinc.h
Closes #11961
`SDL_malloc()` is either implemented via `malloc()`, which implies the guarantees specified by the C runtime and by extension the C standard, or `dlmalloc()`, which aligns to 16 bytes on Apple OSes and `2 * sizeof(void *)` otherwise (unless `MALLOC_ALIGNMENT` is overridden, which isn't the case for SDL).
> Document SDL_malloc alignment guarantees

- include/SDL3/SDL_video.h
- src/video/SDL_video.c
- src/video/wayland/SDL_waylandvideo.c
Some protocols take a wl_output object to function, so expose the underlying object via a property on the video displays.
Fixes #12642
> wayland: Expose wl_output objects on video displays

- src/video/SDL_surface.c
#12479 introduced a memory leak when you duplicate a surface of the mjpeg type.
Yes, this leak gets massive fast.
Unset `SDL_SURFACE_PREALLOCATED` when allocating the memory for the jpeg data, so that `SDL_DestorySurface()` frees the memory again.
> video: fix surface leak when duplicating mjpeg

- CMakeLists.txt
On Apple platforms, when `SDL_AUDIO` is disabled, the current CMakeLists.txt does not set `SDL_FRAMEWORK_AVFOUNDATION` which results in a link error if `SDL_CAMERA` is enabled.
This pull request modifies CMakeLists to enable `SDL_FRAMEWORK_AVFOUNDATION` when `SDL_CAMERA` is enabled.
> Fix missing AVFoundation in CMakeLists.txt

- include/SDL3/SDL_power.h
As reported by "BackMode" on Discord, it is tempting to invoke this function every frame to show the real-time status of the battery (e.g. as part of drawing ImGui), but this function can actually be quite expensive on some platforms (e.g. due to opening file handles).
Example flamegraph on Ubuntu:
This PR adds a performance disclaimer to its documentation.
> Add performance disclaimer in `SDL_GetPowerInfo` documentation

- src/gpu/vulkan/SDL_gpu_vulkan.c
this was causing problems when i was specifying non-zero buffer slots in `SDL_BindGPUVertexBuffers`, `SDL_GPUVertexAttribute` and `SDL_GPUVertexBufferDescription`.
`firstSlot + i` is simply copied over from metal and d3d12 backends.
> fix vulkan vertex buffer indexing

- src/audio/pipewire/SDL_pipewire.c
I would argue that returning early is considerably simpler then jumping to section in this sample. It avoids variable assignment and `goto` logic.
> Return early instead of goto

- include/SDL3/SDL_video.h
- src/video/emscripten/SDL_emscriptenvideo.c
> Add Emscripten window data to window properties

- src/video/emscripten/SDL_emscriptenmouse.c
- test/testmouse.c
> Handle global mouse state for Emscripten

- cmake/sdlchecks.cmake
This fixes the feature detection in cases where linking the final executable would fail. This is fine since SDL only opens these libraries using dlopen as well.
For now this PR is intended to discuss whether this is the correct approach to handle this, or whether there is a better solution. If we decide to handle it this way this would probably need to be applied to more  feature tests.
See: https://github.com/libsdl-org/SDL/issues/12719
> only build static library in some feature tests

- include/SDL_cpuinfo.h
Reference issue: https://github.com/libsdl-org/SDL_image/issues/537
Reference issue: https://github.com/libsdl-org/SDL_mixer/issues/648
> SDL_cpuinfo.h: only include immintrin.h for x86 targets.

- src/SDL_hints.c
- src/core/android/SDL_android.c
- src/core/android/SDL_android.h
This hint needs to persist outside of the normal application flow, so use the environment to set the initial value, and then save the value set via SDL_SetHint() after that.
Fixes https://github.com/libsdl-org/SDL/issues/12677
> Added special handling for SDL_HINT_ANDROID_ALLOW_RECREATE_ACTIVITY

- src/video/x11/SDL_x11events.c
On non-compositing window managers, XIconifyWindow can trigger map/unmap events, which would toggle the window hidden/shown state. This should not be done, as a hidden window in SDL is equivalent to a withdrawn window in X, and SDL will try to set/reset state when it is shown again.
Unless the window is explicitly being withdrawn via X11_HideWindow(), set unmapped windows to the minimized/occluded state, and send a restored event when mapped again.
Fixes #12712
> x11: Don't set the hidden flag when minimizing windows

- src/gpu/vulkan/SDL_gpu_vulkan.c
While doing some testing on my project, I noticed some bad defrag behavior:
After a nightmare debugging session I finally traced the cause.
Our defrag strategy is as follows: when a resource fails to find any available memory regions with enough space to bind itself, a new block is allocated so the resource can be bound immediately. Since the failure may have been due to fragmentation, existing blocks are checked for fragmentation and marked to be defragged.
The bug:
- The defrag process causes a new block of the same size to be allocated. Every resource in the currently defragging block is copied to the new block, and then marked for destruction. 
- Defrag is triggered when a command buffer is submitted and at least one block is marked for defrag. To avoid overallocating or stalling for …
> GPU Vulkan: Fix recursive Submit calls causing defrag to fail

- include/SDL3/SDL_gpu.h
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
This PR contains four independent changes:
1. SDL_CreateGPUTexture() incorrectly uses SDL_CopyProperties() which results in a harmless "`Parameter 'src' is invalid`" error being registered if `SDL_GPUTextureCreateInfo.props` is null. While SDL_CreateGPUTexture() returns successfully and therefore the error should be ignored multiple users have incorrectly used SDL_GetError() to see the error and have made support requests relating to it. E.g. #12638. This PR corrects the usage.
2. A user managed to receive the error message "`vkCreateGraphicsPipelines Unhandled VkResult!`" While I'm not sure what the VkResult value actually was the Vulkan docs do mention that VK_ERROR_INVALID_SHADER_NV can be returned from vkCreateGraphicsPipelines() and that value wasn't being stringified. This PR adds …
> GPU: Nitpicks

- src/video/emscripten/SDL_emscriptenevents.c
- src/video/emscripten/SDL_emscriptenevents.h
- src/video/emscripten/SDL_emscriptenvideo.c
Moved global event handlers from `SDL_CreateWindow` to `SDL_VideoInit`
- `emscripten_set_mouseup_callback`
- `emscripten_set_focus_callback`
- `emscripten_set_blur_callback`
- `emscripten_set_pointerlockchange_callback`
- `emscripten_set_fullscreenchange_callback`
- `emscripten_set_resize_callback`
This change will be necessary for #12575
> Emscripten: Move global event handlers

- src/gpu/vulkan/SDL_gpu_vulkan.c
Previously the strategy was to clean up on presentation submits, because those are more likely to be expensive anyway. This means that certain cleanups are never triggered in headless mode. This patch makes it so that headless Submits always perform cleanups.
Resolves #12737
> GPU Vulkan: Clean up in Submit in headless mode

- src/video/x11/SDL_x11window.c
It doesn't work well with Vulkan, and Vulkan windows may not have the Vulkan flag set in all circumstances, so only enable it if we explicitly know that OpenGL is being requested instead.
Fixes #12742
> x11: Only enable _NET_WM_SYNC_REQUEST for OpenGL windows

- include/SDL3/SDL_stdinc.h
Reference issue: https://github.com/libsdl-org/SDL/issues/12749.
If this isn't wanted here in mainstream, just close this.
> bool is 4 bytes in Apple MacOS X 32 bit PPC ABI

- src/dialog/windows/SDL_windowsdialog.c
This changeset causes the save dialog spawned by `SDL_ShowOpenFileDialog` in Windows to prompt a user if they try to save over an existing file.
This is a "maybe you'd like this, maybe not" PR of a patch I plan on using in [opensim-creator](https://www.opensimcreator.com/). I was previously using [nativefiledialog](https://github.com/mlabbe/nativefiledialog) which, by default, prompts the user if they open a save dialog in Windows and try to overwrite an existing file. I personally like this behavior (prevents a little accident 😄 ), but it's up to the SDL team if you agree!
The documentation for the `OFN_OVERWRITEPROMPT` flag is available in the docs for the `OPENFILENAMEA` struct, [here](https://learn.microsoft.com/en-us/windows/win32/api/commdlg/ns-commdlg-openfilenamea). Here's a …
> [Windows]: dialog: Add `OFN_OVERWRITEPROMPT` to save dialogs

- CMakeLists.txt
- src/video/SDL_egl.c
It's not used by the Emscripten video driver.
> Disable EGL in Emscripten builds

- src/joystick/hidapi/SDL_hidapi_8bitdo.c
Fix IMU orientations for 8bitdo wireless 2 controller in bluetooth mode. 
Fix IMU timing stamp - simulate the timing stamp from the controller hardware's perspective, as opposed to the receiving computer's perspective. Do this by advancing a time stamp by a fixed rate, based on observation of average rate over bluetooth.
> Fix Orientation, Gyro Sensitivity, and Timings for 8bitdo Wireless 2 Controller

- .github/workflows/create-test-plan.py
- CMakeLists.txt
- VisualC-GDK/SDL/SDL.vcxproj
- VisualC-GDK/SDL/SDL.vcxproj.filters
- VisualC/SDL/SDL.vcxproj
- VisualC/SDL/SDL.vcxproj.filters
- src/core/windows/SDL_gameinput.cpp
- src/core/windows/SDL_gameinput.h
- src/joystick/gdk/SDL_gameinputjoystick.cpp
- src/video/windows/SDL_windowsgameinput.cpp
- src/video/windows/SDL_windowsgameinput.h
- src/video/windows/SDL_windowsvideo.h
The biggest change is that the C API is no longer available.
Here are more details:
https://www.nuget.org/packages/Microsoft.GameInput
Fixes https://github.com/libsdl-org/SDL/issues/12802
> Updated to GameInput v1.1

- src/events/SDL_keyboard.c
- src/events/SDL_keyboard_c.h
- src/events/SDL_keymap.c
- src/events/SDL_keymap_c.h
- src/events/SDL_mouse.c
- src/events/SDL_mouse_c.h
- src/events/SDL_touch.c
- src/events/SDL_touch_c.h
- src/test/SDL_test_common.c
- src/video/cocoa/SDL_cocoakeyboard.m
- src/video/wayland/SDL_waylandclipboard.c
- src/video/wayland/SDL_waylanddatamanager.c
- src/video/wayland/SDL_waylanddatamanager.h
- src/video/wayland/SDL_waylandevents.c
- src/video/wayland/SDL_waylandevents_c.h
- src/video/wayland/SDL_waylandkeyboard.c
- src/video/wayland/SDL_waylandkeyboard.h
- src/video/wayland/SDL_waylandmouse.c
- src/video/wayland/SDL_waylandmouse.h
- src/video/wayland/SDL_waylandvideo.c
- src/video/wayland/SDL_waylandvideo.h
- src/video/wayland/SDL_waylandwindow.c
- src/video/wayland/SDL_waylandwindow.h
- src/video/windows/SDL_windowskeyboard.c
- src/video/x11/SDL_x11keyboard.c
Wayland environments can expose more than one seat for multiple collections of input devices, which can include multiple, simultaneously active, desktop pointers and keyboards with independent layouts. The Wayland input backend previously presumed that only one seat could exist, which caused broken behavior if the compositor exposed more than one, which is possible on wlroots based compositors such as Sway. This introduces support for handling multiple seats, including proper handling of dynamically adding and removing seats and capabilities at run time.
The SDL Wayland input system was accreted over time, and the assumption that only one seat will ever exist resulted in state and related objects not always being tied to their most appropriate owner in a multi-seat scenario, so …
> wayland: Add multi-seat support

- src/video/windows/SDL_windowswindow.c
Under certain circumstances, processing events may try to position a child before it is fully initialized. Check the internal data before proceeding.
Fixes #12831
> win32: Check internal data when positioning child windows

- include/SDL3/SDL_mouse.h
This corrects conformance to SDL style. This pattern lets my binding generator detect the type of defines and collect them into a flags type (technically only the MASK defines belong as part of the flags but this is how it was structured before SDL_MouseMotionTransformCallback was added)
> The SDL_BUTTON_*MASK defines must come immediately after the SDL_MouseButtonFlags typedef to be associated

- src/video/x11/SDL_x11events.c
In https://github.com/libsdl-org/sdl2-compat/issues/465, the affected app doesn't see key presses for dead keys when text input is enabled. While I believe this behavior is technically allowed per the documentation around text input, it's not how the Wayland video driver behaves nor what SDL2 did on the same system.
Fixes https://github.com/libsdl-org/sdl2-compat/issues/465
> x11: Send key events for dead keys consumed by the IME

- include/SDL3/SDL_surface.h
Closes https://github.com/libsdl-org/SDL/issues/12858
SDL2 PR: https://github.com/libsdl-org/SDL/pull/12864
> SDL_BlitSurface() comment: Remove sentence about final blit rect being stored in srcrect and dstrect

- include/SDL3/SDL_video.h
- src/video/openvr/SDL_openvrvideo.c
I'm not sure about the policy for changing the name of constants that's been in a release, but I found this after I wrote some code to automatically get the type of properties
The property `SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_STENCIL_UINT8` in `SDL_gpu.h` is also missing a (common) suffix, but `UINT8` arguably implies `NUMBER` so I'm not sure about that one. It's the only property with a `UINT8` suffix though. This PR doesn't change it.
> Add missing type suffix to SDL_PROP_WINDOW_OPENVR_OVERLAY_ID

- src/video/SDL_surface.c
Fixes https://github.com/libsdl-org/SDL/issues/12844
> SDL_BlitSurfaceScaled(): Do not blit if surfaces have no pixel data

- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
Multiple users have attempted to pass uncompiled shader code into SDL_CreateGPUShader() and SDL_CreateGPUComputePipeline() and have gotten confused by the resulting error messages (e.g. #12522). This is a bigger deal for the D3D12 backend than the others as parsing the shader code is done lazily in that backend so the errors appear unrelated to shader compilation.
This PR adds a small sanity check to all backends that detects obviously-invalid shader code by checking for a magic number in the blob and returns a more helpful error message if hit. It is not possible to detect MSL via this method so the existing error handling is kept for that format.
> GPU: Validate shader bytecode

- src/gpu/d3d12/SDL_gpu_d3d12.c
This PR makes enabling the D3D12 debug layer an optional endeavor so that it's possible to create a device on systems where the debug layer is not available even when debug mode is enabled. Currently device creation will fail when debug mode is enabled but work fine if debug mode is disabled.
The D3D12 debug layer is an optional feature that can be installed via "Windows Settings -> System -> Optional features" and adding the "Graphics Tools" optional feature.
> GPU: Make D3D12 debug layers optional

- src/render/SDL_render.c
Allowing rendering with a zero-sized `srcrect` in function `SDL_GetRectIntersectionFloat()` so that it works similar to how `SDL_RenderTextureRotated()` and `SDL_BlitSurfaceScaled()` handle zero-sized srcrects.
First PR and discussion on rendering zero-sized srcrect: https://github.com/libsdl-org/SDL/issues/8580
Related(and videos on how it looks): https://github.com/libsdl-org/SDL/pull/12850
> SDL_GetRectIntersectionFloat(): Allow rendering zero-sized srcrect

- src/joystick/SDL_joystick.c
- src/joystick/SDL_sysjoystick.h
This was already present for regular rumble to ensure that controllers would continue rumbling for extended periods, but was missing for trigger rumble. I don't know if this affects any controllers at the moment, but it's helpful for future-proofing.
> Joystick: Add trigger rumble resend

- src/video/x11/SDL_x11events.c
- src/video/x11/SDL_x11window.h
Xfce, unlike every other window manager in existence, sends ConfigureNotify events before PropertyNotify events when toggling the fullscreen and maximized window state. Check the window state when handling ConfigureNotify events and defer emitting SDL size/position events until the corresponding PropertyNotify event arrives, since SDL and clients expect to get the window state before the new size and position.
Fixes #12870
> x11: Handle size/position events arriving before state events

- src/video/windows/SDL_windowsevents.c
- src/video/windows/SDL_windowswindow.c
- src/video/windows/SDL_windowswindow.h
Prior to https://github.com/libsdl-org/SDL/pull/11237 , ClipCursor is periodically refreshed on an interval set by a hint, taking place at the end of PumpEvents. 
My previous PR changed it to run as a response to WM_MOUSEMOVE instead, which is an approach that makes sense for a `GetMessage()` based application where the event loop is mostly idle, so immediately responding to clipping discrepancies would immediately stop further errant mouse movement messages
However, since SDL apps uses a pump-based event loop, this means that multiple movement events may have accumulated before the pump, the expensive calls would then be run on each of those messages redundantly. 
For pump-based apps, the correct approach for the initial idea behind the aformentioned PR is instead to respond to those …
> Make WM_MOUSEMOVE queue ClipCursor refresh to end of PumpEvents instead of immediately calling

- src/video/emscripten/SDL_emscriptenopengles.c
According to the documentation and testing the `emscripten_webgl_create_context` function returns `0` on error as oppposed to a negative number. This was causing the error message to be empty when the later `emscripten_webgl_make_context_current` call fails given the invalid context.
See https://emscripten.org/docs/api_reference/html5.h.html#c.emscripten_webgl_create_context
> Emscripten: fix incorrect error check for WebGL context creation

- src/video/uikit/SDL_uikitview.m
This loop appears twice, with a one-off difference:
https://github.com/libsdl-org/SDL/blob/main/src/video/uikit/SDL_uikitview.m#L213
https://github.com/libsdl-org/SDL/blob/main/src/video/uikit/SDL_uikitview.m#L243
In the second case, when i is 0, SDL_BUTTON_MASK(0) attempts to shift left by a negative number, causing crashes.
This PR aligns the second loop with the first.
> Fix crash in UIKit indirect pointer handling

- src/joystick/hidapi/SDL_hidapi_steamdeck.c
Previously, touchpad events were not reported to the application. This patch exposes two touchpads and forwards x/y/pressure information from the HIDAPI packet.
This fixes issue #12855
> SDL_hidapi_steamdeck: report touch controller events

- src/video/windows/SDL_windowsevents.c
Use GetMessagePos instead of GetCursorPos when it pertains to the coordinate at which the event had taken place.
Also inlined WIN_UpdateMouseCapture since it's a single-instance procedure with lots of side effects.
> chore: clean up usage of GetCursorPos in wndproc

- CMakeLists.txt
This variable is always defined when targeting Android:
- when using the toolchain file shipped along the ndk (using ` -DCMAKE_TOOLCHAIN_FILE=$ENV{ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake`)
- when using the toolchain file provided by CMake (using `-DCMAKE_SYSTEM_NAME=Android`)
Fixes #12653
> cmake: use CMAKE_ANDROID_NDK variable as root of Android ndk

- include/SDL3/SDL_audio.h
- src/audio/SDL_audio.c
- src/audio/SDL_sysaudio.h
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
This adds a hook that runs in the audio device thread, before it starts processing bound audio streams, and a second hook that runs after.
The specific need here: the SDL_mixer rewrite wants to be able to change things on multiple tracks (what SDL2_mixer calls "channels") atomically. For example, stopping multiple tracks with a fadeout should have them all start fading at the exact same time, which it can't accomplish if the device thread is halfway through processing streams when SDL_mixer tries to start the fade...some will be fading a little sooner than the rest.
A generic "lock the whole device" API wasn't feasible, since there's already a ton of locking needed to find the lock that applies to the SDL_AudioDeviceID  the app would have, so when one goes to _unlock_ the device later, …
> audio: Added SDL_SetAudioIterationCallbacks().

- include/SDL3/SDL_gpu.h
- src/gpu/d3d12/SDL_gpu_d3d12.c
Fixes #12835.
Putting this in a Pull Request to make sure it actually builds on all the Windows targets.
> gpu: Warn about Direct3D 12 texture alignment requirements.

- VisualC-GDK/SDL/SDL.vcxproj
The call to compile_shaders_xbox.bat fails if ProjectDir contains a space. Wrapping the command in quotes fixes the issue.
If for example your ProjectDir is located at 
`C:\Users\My Name\Foo\`
Then you'll get a failed pre-build step with an error, reporting that `C:\Users\My` is not a valid command.
Fixes #12897.
> GDK: Handle ProjectDir containing spaces

- src/video/x11/SDL_x11events.c
- src/video/x11/SDL_x11window.h
- src/video/x11/SDL_x11xinput2.c
There is a quirk with XInput2 mouse capture that causes a leave event to be sent if the pointer moves out->in->out, which breaks mouse tracking outside the window. If the mouse leaves the window with buttons pressed, continue tracking it until the buttons are released.
Fixes #12723
> x11: Better handle XInput2 mouse tracking outside the window

- src/tray/unix/SDL_tray.c
Fixes:  https://github.com/libsdl-org/SDL/issues/12908.
> tray, unix: make pointers g_object_ref and g_object_ref_sink static

- src/events/SDL_mouse.c
- src/events/SDL_mouse_c.h
- src/video/cocoa/SDL_cocoawindow.m
- src/video/kmsdrm/SDL_kmsdrmmouse.c
- src/video/wayland/SDL_waylandmouse.c
was trying to tackle #12163, but the adhoc additions accumulated over the years made it hard to reason about the cursor visibility logic, so this PR is just a preamble cleanup split into self-contained commits
> chore: rename internal cursor visibility fields

- src/events/SDL_mouse.c
- src/events/SDL_mouse_c.h
- src/video/riscos/SDL_riscosmodes.c
- src/video/wayland/SDL_waylandmouse.c
- src/video/x11/SDL_x11mouse.c
Likely the last preparatory change before attempting a solution at #12163.
This introduces one minor behavior change and one minor internal symbol change, the changes are split into individual commits as atomic units.
Before, calling SDL_SetCursor with a new cursor will unconditionally set the displayed cursor to the one requested regardless of focus, which means that if this is called while unfocused the cursor will flash to the requested on for one frame before correcting back to the default non-focused cursor.
Now, the side effect of actually setting the displayed cursor is split to its own `SDL_RedrawCursor()` procedure which always checks focus, and SDL's internal usage of `SDL_SetCursor(NULL)` is replaced with this for better clarity.
> SDL_SetCursor shouldn't skip focus check when setting new cursor 

- include/SDL3/SDL_video.h
- src/video/SDL_sysvideo.h
- src/video/SDL_video.c
- src/video/cocoa/SDL_cocoawindow.h
- src/video/cocoa/SDL_cocoawindow.m
- src/video/wayland/SDL_waylandevents.c
- src/video/wayland/SDL_waylandvideo.c
- src/video/wayland/SDL_waylandwindow.c
- src/video/wayland/SDL_waylandwindow.h
- src/video/windows/SDL_windowsevents.c
- src/video/windows/SDL_windowswindow.c
- src/video/windows/SDL_windowswindow.h
- src/video/x11/SDL_x11window.c
- src/video/x11/SDL_x11window.h
- test/testpopup.c
By default, popups are automatically constrained to be completely within display bounds, so as not to cut off information and result in an unusable menu, or unreadable tool tip. In some cases, however, this is not wanted, so a property to toggle this behavior is added.
There are also cases where the client may not want a popup menu to implicitly grab the keyboard focus when shown, as is the default behavior, so popup menus now respect the focusable flag/property, as well as being able to toggle focus grabbing via SDL_SetWindowFocusable().
Much of the general popup focus code was identical between backends, and the changes here would have introduced even more verbatim code, so the popup focus code was factored out. There can probably be further simplification here, but care has to be …
> Add support for non-constrained and non-grabbing popups

- src/gpu/vulkan/SDL_gpu_vulkan.c
Fixes a thread safety issue when creating pipeline objects on multiple threads.
> GPU Vulkan: Add locks for layout object lookups

- src/gpu/SDL_gpu.c
- src/gpu/SDL_sysgpu.h
A very common user error is to bind the same texture as both a render target and a sampler texture or storage texture. This is undefined behavior on every backend, so our spec shouldn't allow it. This patch causes SDL to assert if a client does this when the GPU device is in debug mode.
Fixes #12762
> GPU: Validate that textures are not bound for both read and write on render passes

- VisualC-GDK/SDL/SDL.vcxproj
- VisualC-GDK/SDL/SDL.vcxproj.filters
- VisualC/SDL/SDL.vcxproj
- VisualC/SDL/SDL.vcxproj.filters
- Xcode/SDL/SDL.xcodeproj/project.pbxproj
- android-project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
- include/SDL3/SDL_hints.h
- src/hidapi/libusb/hid.c
- src/joystick/hidapi/SDL_hidapi_gip.c
- src/joystick/hidapi/SDL_hidapijoystick.c
- src/joystick/hidapi/SDL_hidapijoystick_c.h
- src/joystick/usb_ids.h
This new driver is based on official documentation released by Microsoft in September, though it still lacks several important features, notably the Security handshake for wireless dongles and audio support. It is, however, more reliable and extensible than the old driver already.
Some current limitations, though none of these are worse than the current state of things:
- The Security handshake is unimplemented so dongles don't work
- Several less-used packets are stubbed out and just give warnings
- Some interfaces (e.g. Wheel and FlightStick) aren't implemented yet
> Joystick: Add new GIP driver to replace old Xbox One wired driver

- src/video/x11/SDL_x11messagebox.c
Message boxes, when using X11, were not centered on a monitor if there were multiple monitors connected and the parent window was `NULL`. This PR fixes that if XRandr is available.
> X11: Center Message Box on Multi Monitor Displays

- include/SDL3/SDL_events.h
- src/events/SDL_events.c
- src/events/SDL_mouse.c
- src/events/SDL_mouse_c.h
Reintroduce integer mouse wheel x/y fields for use by sdl2-compat (and applications that don't care to support smooth scrolling). It's much easier to just have SDL3 provide these than handle it properly in all the places in sdl2-compat where we interact with events at various stages of processing.
https://github.com/libsdl-org/sdl2-compat/issues/461
> events: Add integer wheel fields for sdl2-compat

- src/render/opengles2/SDL_render_gles2.c
This fixes undefined behavior resulting from adding offsets to nullptr.
> Port #12581 to SDL2

- src/video/windows/SDL_windowswindow.c
- src/video/windows/SDL_windowswindow.h
If it is known that the window will immediately enter fullscreen upon being shown, set the borderless style when showing the window to hide the borders, or they may linger in the background if the client takes some time to draw the first frame.
Unnecessarily calling ShowWindow with SW_RESTORE when applying the window flags must be suppressed in this case, or the borders can reappear in a weird, partial state.
Fixes libsdl-org/sdl2-compat#474
> win32: Hide the borders when showing a fullscreen window

- include/SDL3/SDL_stdinc.h
Fixes:  https://github.com/libsdl-org/SDL/issues/12948.
If accepted, will need cherry-picking into all active SDL2 and SDL3 branches.
> don't prototype strdup() for __clang_analyzer__ case in windows builds.

- src/video/x11/SDL_x11messagebox.c
The functions are undefined if built without XRandR.
Fixes #12960
> x11: #ifdef the XRandR path in the message box code

- src/video/x11/SDL_x11events.c
- src/video/x11/SDL_x11window.h
- src/video/x11/SDL_x11xinput2.c
The xserver always sends EnterNotify events, even when the pointer is captured, which lead to ungrab commands being issued, cancelling the capture. Don't update the grab state if a captured pointer is re-entering the window, or the capture will be cancelled.
Commit 8c733d1f7bdb03b2082028349e97137c0bdea13b is reverted, as the workaround is no longer needed.
Fixes #12956
> Fix X11 mouse capture (take 2)

- src/joystick/hidapi/SDL_hidapi_gip.c
Using a 0 sequence number is always allowed and avoids having to synchronize sequence numbers with the controller (and potentially confusing other things talking to the controller)
Also fixes occasional long running rumble at controller connection.
> Use motor sequence ID 0 in the HIDAPI GIP driver

- src/video/emscripten/SDL_emscriptenframebuffer.c
The Module interface is the one used by the outside world.  This code is inside the module itself so can use the internal name, avoiding the need to export this function on the Module at all.
See https://github.com/emscripten-core/emscripten/pull/24269
> [emscripten] Remove reference to Module['createContext']

- src/video/x11/SDL_x11events.c
- src/video/x11/SDL_x11video.h
IME text events can result in sending duplicate key press events, which will result in undesired repeated key presses. Since the events are exact duplicates, compare the serials to filter out redundant key down events.
Fixes #12965
> x11: Filter out duplicate key presses when an IME is active

- src/camera/mediafoundation/SDL_camera_mediafoundation.c
- src/core/windows/SDL_windows.c
- src/filesystem/windows/SDL_sysfilesystem.c
- src/joystick/windows/SDL_dinputjoystick.c
- src/video/windows/SDL_windowsclipboard.c
- src/video/windows/SDL_windowsmodes.c
- src/video/windows/SDL_windowsmodes.h
- src/video/windows/SDL_windowswindow.c
The surrounding code in all of these instances expects the Unicode variants. Previously, this code mixed Unicode and ANSI/ASCII calls if `UNICODE` was undefined, which caused type and logic errors. Explicitly spelling out the W removes any reliance on that macro.
I also made an SDL 2 version on [this branch](https://github.com/nmlgc/SDL/tree/windows_unicode_SDL2).
> windows: fix Unicode function and type inconsistencies

- src/gpu/SDL_gpu.c
- src/gpu/SDL_sysgpu.h
Resolves #12993 
99% of the time binding a texture as both a render target and sampler is a user error. Our GenerateMipmaps process is a rare exception that blits one level to another. In debug mode we set a special bool that ignores the texture validation until the generation process is complete.
> GPU: Special case to avoid assert on GenerateMipmaps

- src/hidapi/SDL_hidapi.c
On our project that uses both hidapi and SDL was getting symbol conflicts:
```
ld.lld: error: duplicate symbol: hid_version
>>> defined at SDL_hidapi.c
>>>            SDL_hidapi.c.o:(hid_version) in archive ../3rdparty/libsdl-org/SDL/libSDL3.a
>>> defined at hid.c
>>>            hid.c.o:(.text+0x0) in archive ../3rdparty/hidapi/hidapi/src/linux/libhidapi-hidraw.a
ld.lld: error: duplicate symbol: hid_version_str
>>> defined at SDL_hidapi.c
>>>            SDL_hidapi.c.o:(hid_version_str) in archive ../3rdparty/libsdl-org/SDL/libSDL3.a
>>> defined at hid.c
>>>            hid.c.o:(.text+0x10) in archive ../3rdparty/hidapi/hidapi/src/linux/libhidapi-hidraw.a
```
hid_version and hid_version_str were missing from the symbol renaming for the libusb implementation.
> Add hid_version and hid_version_str to renamed LIBUSB impl symbols

- CMakeLists.txt
- docs/README-wayland.md
- src/core/linux/SDL_dbus.c
- src/core/linux/SDL_dbus.h
- src/core/linux/SDL_progressbar.c
- src/core/linux/SDL_progressbar.h
- src/video/SDL_video.c
- src/video/wayland/SDL_waylandvideo.c
- src/video/x11/SDL_x11video.c
Linux support for progress bar display in task bar (`SDL_SetWindowProgressState()` and `SDL_SetWindowProgressValue()`) using the [Unity LauncherAPI](https://wiki.ubuntu.com/Unity/LauncherAPI) through DBus.
Limitations/quirks of the underlying API:
- It only knows `SDL_PROGRESS_STATE_NORMAL` mode for progress display, so all other modes will behave like `SDL_PROGRESS_STATE_NORMAL` when using this API.
- A .desktop file is required to make the progress actually visible.
- Only supported by some DEs, AFAIK Unity, KDE and maybe others when libunity is installed?!
- The last set progress bar state is persisted throughout multiple program runs, thus I've added a "reset" call when a new Window gets created (maybe doing this globally once after DBus init would be better?!)
- _Setting progress for …
> Add progress bar support for Linux

- src/video/x11/SDL_x11video.c
Openbox needs fullscreen size/position event synthesized, but does not send display changed events.
Fixes #12998
> x11: Fix the Openbox quirk flag

- src/audio/aaudio/SDL_aaudio.c
- src/audio/aaudio/SDL_aaudiofuncs.h
Implements SDL_HINT_AUDIO_DEVICE_SAMPLE_FRAMES functionality for AAudio. Fixes #12983.
> AAudio: Implemented sample frames hint

- src/gpu/vulkan/SDL_gpu_vulkan.c
Currently, read/write buffers used in compute pipelines can produce various sync validation errors, such as the following:
```
vkQueueSubmit(): WRITE_AFTER_WRITE hazard detected. vkCmdDispatchIndirect (from VkCommandBuffer 0x1984545e2d0 submitted on the current VkQueue 0x1983c426b50) writes to VkBuffer 0x61a000000061a, which was previously written by another vkCmdDispatchIndirect command (from VkCommandBuffer 0x1988a31c320 submitted on VkQueue 0x1983c426b50).
The current synchronization allows VK_ACCESS_2_SHADER_READ_BIT accesses at VK_PIPELINE_STAGE_2_VERTEX_SHADER_BIT|VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT|VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT, but to prevent this hazard, it must allow VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT accesses at VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT.
```
This …
> GPU Vulkan: set correct destination usage mode for storage buffer read/write bindings

- src/tray/windows/SDL_tray.c
> Fix `SDL_SetTrayEntryLabel` on Windows

- include/SDL3/SDL_process.h
- src/process/SDL_process.c
- src/process/windows/SDL_windowsprocess.c
- test/childprocess.c
- test/testprocess.c
This PR avoids quoting strings if it does not have newlines, as well as adding `SDL_PROP_PROCESS_CREATE_CMDLINE_STRING` as an alternative.
This issue was described in #12945.
This PR offers two solutions:
1. SDL will not quote strings unless it needs to (if it includes whitespaces).
2. `SDL_CreateProcessWithProperties` will accept another property called `SDL_PROP_PROCESS_CREATE_CMDLINE_STRING`, which lets library users pass an escaped command line to `CreateProcess` directly.
This is useful for SDL wrappers that needed to allow users to call old executables that has their own command line escaping.
Take `cmd.exe /S /C` as example: `/S` will strip first and last double quotes from the command line, after `/C` itself.
| Method | Passed to `CreateProcess` | Passed to batch processing |
| …
> [Process API] Quoting enhancements

- src/audio/SDL_audio.c
The keys and values of device_hash are pairs
`(SDL_AudioDeviceID devid, void *dev)` where dev can be either a `SDL_AudioDevice *` or a `SDL_LogicalAudioDevice *`, depending on bit 1 of devid.
We can confirm that we have got this right by looking at the instance_id member, because logical audio devices happen to start with the devid, whereas physical devices start with a pointer which is unlikely to match the devid by chance.
---
This would hopefully have made #12977 easier to diagnose.
An alternative to this would be to have two separate hash tables: one map `{ SDL_AudioDeviceID => SDL_AudioDevice * }` where all the device IDs have bit 1 unset, and one `{ SDL_AudioDeviceID => SDL_LogicalAudioDevice * }` where all the device IDs have bit 1 set. That would use a bit more memory, but should …
> audio: Assert that all devices from device_hash are the appropriate type

- src/joystick/SDL_joystick.c
SDL_VIRTUAL_JoystickDriver was referenced outside an #ifdef when setting is_virtual, which caused a linker error. I modified it so that is_virtual is set to false if virtual joystick support is not enabled.
This fixes #13008
> joystick: Fix linker error when building without virtual joystick support

- src/video/x11/SDL_x11events.c
- src/video/x11/SDL_x11video.h
This wound up introducing some bugs and quirks such as duplicated and delayed/missed key events, and the fixes to try and work around these issues seemingly created new issues themselves, so revert this for now.
Fixes #13006
> Revert "x11: Send key events for dead keys consumed by the IME"

- include/SDL3/SDL_gpu.h
- src/gpu/SDL_gpu.c
- src/gpu/SDL_sysgpu.h
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
A proposed implementation for #12849, so Vulkan device features can be opt out using dedicated GPU properties.
> SDL GPU: Implemented opt out Vulkan device features

- src/gpu/SDL_gpu.c
Only certain texture formats are valid for writes in a compute shader. This patch causes an assert if the texture binding is an invalid format.
It's probably worth also exposing this to the client with some kind of Supports query API call, but we can add that in a separate patch so we can cherry-pick this one back to 3.2.x.
Resolves #13043
> GPU: Validate that a texture format is valid for compute writes

- src/video/cocoa/SDL_cocoamouse.m
macOS: Fixes bug with NSEventTypeMouseMoved having a NULL window causing us to suppress future mouse move events because the window was considered out of focus.  This was causing Dota to infinitely pan the camera because it would stop getting mouse move events.
> Fix #13057 - macOS: fix bug with mouse move events not occuring after an window exit event 

- src/events/SDL_events.c
On the Steam Deck, axis events are extraordinarily spammy, producing on the order of 1000 log lines per second of info even when the sticks are not being moved. This PR suppresses these events when `SDL_HINT_EVENT_LOGGING` is < 2, as well as the "update complete" events because they are equally spammy.
This is the easiest solution, but a more robust solution could be to have an adjustable "deadzone" for event logs, so that axis events will only be logged if the axis is beyond a certain threshold. Or, even better, to have an adjustable axis deadzone within SDL itself, so it won't produce events at all if they are within the deadzone.
See #13059.
> Suppress spammy gamepad and joystick update events when SDL_HINT_EVENT_LOGGING < 2

- include/SDL3/SDL_gpu.h
Fix properties name in SDL_CreateGPUDeviceWithProperties
The property names in the documentation for the SDL_CreateGPUDeviceWith Properties method differ from the actual ones.
> Fix properties name in SDL_CreateGPUDeviceWithProperties

- src/gpu/SDL_gpu.c
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
Currently `shader_formats` on the gpu device gets set to what the backend can support. This ends up incorrectly reporting that `DXIL` shaders are supported on older D3D12 devices that only support `DXBC` shaders. Changed to detect and correctly set `shader_formats` field which then when `SDL_GetGPUShaderFormats` is called will return accurate shader support information.
Please note I do not have access to the NDA platforms so each of those drivers would need to set the `shader_formats` correctly.
Loading of the blit pipelines fails because these are `DXIL` and there is no `DXBC` equivalents to use. I'm keen to look into that in a separate PR.
> GPU: D3D12 incorrectly reports DXIL shader support when using an older GPU

- src/gpu/SDL_gpu.c
- src/gpu/SDL_sysgpu.h
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
This allows us to do more thorough checks for each backend; this is particularly important for D3D12 which has lots of different shader formats, resulting in apps/devices having lots of chances to not have the necessary shaders to run properly.
Fixes #12514
> gpu: Check shader format support in PrepareDriver

- src/joystick/hidapi/SDL_hidapijoystick.c
`SDL_PrivateJoystickAdded` was called before setting the InstanceId in the adapter's `ctx->joysticks` array.  This would eventually broadcast the `SDL_EVENT_JOYSTICK_ADDED` event with the new InstanceId, if your program listens for the added events and opens joysticks at that point it would always fail because there would be no matching InstanceId in the joysticks array.
> Fix: GameCube controller adapter hotplug not working

- build-scripts/wikiheaders.pl
Missed it last time. Previously it turned
`(bool) Returns true on success or false on failure; call [SDL_GetError](SDL_GetError)() for more information.`
into
` for more information.`
The previous regex matched `(ANYTHING[Link](Link)ANYTHING)` so the shorter fix would be to just remove the first `ANYTHING` part, but it looked like a complete abomination anyway.
> docs: fix man page return value section generation

- src/video/wayland/SDL_waylandevents_c.h
- src/video/wayland/SDL_waylandkeyboard.c
The text input cursor should reflect the cursor position, not the entire text input rect. Set it correctly so that IME chooser dialogs appear in the correct location.
Fixes #13086
> wayland: Set the text input cursor rect properly

- src/render/ps2/SDL_render_ps2.c
Fixing a wrong definition type (it will be an error with GCC 15)
> [PS2] [SDL2] Fix wrong `vsync_handler` defintion type

- src/gpu/d3d12/SDL_gpu_d3d12.c
In the D3D12 backend, needVertexBufferBind was never marked false, meaning that they would be rebound every time.
This PR just sets needVertexBufferBind to false after vertex buffers have been bound.
> gpu/d3d12: Mark vertex buffers as bound

- src/tray/unix/SDL_tray.c
Use `g_object_ref` in `SDL_CreateTraySubmenu()` as introduced with 3be67ced646f9d884c32ce6858f39fe9dd8d634b for the top-level menu.
`DestroySDLMenu()` which gets called by `SDL_RemoveTrayEntry()` seems to expect a `g_object_ref` now for `menu->menu`.
I think this was an oversight and should have been in the commit mentioned above.
With this change the segfault described in  #13083 no longer occurs.
I guess @Semphriss should probably review this PR.
This should fix #13083
> Fix #13083 segfault in `SDL_RemoveTrayEntry()` for submenu entries

- src/video/x11/SDL_x11dyn.h
Fixes building when statically linking.
Closes #13103
> x11: Include the XTest header when needed

- src/video/x11/SDL_x11video.c
- src/video/x11/SDL_x11window.c
Non-compositing window managers seem to always need the fullscreen dimensions sent, so do this universally, except on XWayland, where doing so seems to cause hitching in certain cases.
Some compositors/window managers don't actually send MapNotify or PropertyNotify when mapping the window, which didn't clear the flag used to prevent the initial state from being mangled, and could keep windows from leaving fullscreen.
Fixes #13104 
Fixes libsdl-org/sdl2-compat#491
> x11: Fixes for fullscreen

- Xcode/SDL/pkg-support/share/cmake/SDL3/SDL3Config.cmake
The extra text causes Meson/Ninja builds to fail as headers are not found.
This change removes the text "SHELL" from `INTERFACE_COMPILE_OPTIONS` and cleans up the extra quotation marks.
(https://github.com/libsdl-org/SDL/issues/13113)
> Clean up INTERFACE_COMPILE_OPTIONS

- src/audio/emscripten/SDL_emscriptenaudio.c
- src/video/emscripten/SDL_emscriptenvideo.c
`Emscripten_GetSystemTheme` and `EMSCRIPTENAUDIO_OpenDevice` did not work for me when I enabled `PROXY_TO_PTHREAD` in Emscripten. Both methods access globals that are only available in the main thread. This should fix these.
> emscripten: Proxy to the main thread where needed

- include/SDL3/SDL_audio.h
- src/audio/SDL_audiocvt.c
- src/audio/SDL_audioqueue.h
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
This allows an app to add data to an audio stream without an allocating a copy, if they are maintaining the data elsewhere.
> audio: Added SDL_PutAudioStreamDataNoCopy.

- src/gpu/d3d12/SDL_gpu_d3d12.c
Not a _whole_ lot to see here, we're just def'ing out more DXGI stuff on Xbox. Will cherry-pick to 3.2.x as long as CI is happy.
> gpu: Xbox buildfix

- include/SDL3/SDL_begin_code.h
I'm running into places where I want to define data that is aligned for SSE or NEON access, so being able to tell the compiler "this struct (or struct member) needs to be aligned to 16 bytes" or "this stack variable needs to be aligned" becomes _essential_.
All compilers supporting C11 or C++11 support a keyword for this, and GCC/Clang/MSVC all have their own syntax to handle it, long before those standards.
I'm torn about what to do on compilers that don't support it (which is...possible no significant compilers). Seeing as they will definitely miscompile code in that case, I have it intentionally generate an error; the docs currently say it the macro defined in this case, the code currently defines it to something like an error message. It's not clear to me which approach is better, or …
> begin_code: Added SDL_ALIGNED macro.

- include/SDL3/SDL_pixels.h
Added an opening bracket in line 520, in the comment block of SDL_PixelFormat. Simple addition to the readability of documentation.
None
> Update SDL_pixels.h - Readability Improvement

- src/joystick/hidapi/SDL_hidapi_8bitdo.c
Performed tests on new 8bitdo firmware, and all gyros are currently rated at 125hz, 2000degrees per second.
Moved certain consts to defines (sensor rate in hz, and degrees per second)
Updated some comments.
8Bitdo controllers were slightly miscalibrated
> Gyro degrees per second is 2000 across all 8bitdo controllers

- src/video/x11/SDL_x11keyboard.c
The steam deck keyboard accepts a text input area for the purpose of positioning the keyboard to avoid covering the input box. This PR adds these properties to the steam deck keyboard invocation.
Text input area is represented by the white rectangle:
> Pass text input rect to steam deck keyboard invocation

- src/video/x11/SDL_x11pen.c
Fixes a crash if Xinput2 fails to load.
If `SDL_VIDEO_DRIVER_X11_XINPUT2` and `SDL_VIDEO_DRIVER_X11_DYNAMIC_XINPUT2` are defined, SDL will try to load Xinput2 at runtime. If this succeeds, everything works as expected.
However, if SDL fails to find Xinput2, it will attempt to call some Xinput2 functions anyway. Right now, they're guarded on the feature being enabled not on the library being loaded. Since the library failed to load, the functions will be null, so calling them typically leads to a crash.
This PR checks whether or not XInput2 was successfully initialized before calling these functions. It's possible that I didn't catch every instance of this issue--the calls in `SDL_x11pen.c` were easy to find as one of them happens at init time.
(I'm a first time contributor--if there's a …
> Checks if Xinput2 is loaded before trying to call Xinput2 functions

- .wikiheaders-options
`wikiheaders.pl` not parsing this correctly with the comment on the same line, causing this error:
```
Argument "0  # !!! FIXME: maybe later, but there are probably docu..." isn't numeric in int at ./build-scripts/wikiheaders.pl line 132, <OPTIONS> line 26.
```
Sort of #12967
> Move comment in SDL2's .wikiheaders-options to own line

- docs/README-touch.md
There are too many `=` unnecessarily around, making it hard to read.
> README-touch.md(sdl2): fix header separators

- src/render/ngage/SDL_render_ngage.c
- src/video/ngage/SDL_ngagevideo.c
Since commit 2ef7944 was reverted, alpha transparency isn't supported, so this reflects that in the texture format. It should be possible to support both formats and only separate the mask for formats that have alpha.
This has not been tested.
> Correct the texture format used for the N-Gage

- docs/README-cmake.md
Fix a broken link inside README-cmake.md that's meant to send to README-linux.md
also made said link more consistent with other links by adding .md suffix
I fixed a broken link in README-cmake.md that was meant to link to the dependencies part of README-linux.md but instead gave a 404 error page as the path was incorrect.
I also added the .md suffix to that link as most links to document pages also have that suffix
> Fix broken link inside README-cmake.md

- src/joystick/hidapi/SDL_hidapi_switch.c
Switch controllers have factory configured IMU sensitivity coefficients. These should be retrieved using an SPI flash read and applied to the scaling factors used for the sensor data. Previously, these coefficients were constants, which were correct for some controllers but wrong for others.
Addresses the scale-related inaccuracy in https://github.com/libsdl-org/SDL/issues/13197. There is also a timing-related inaccuracy that will be addressed by @HilariousCow separately.
> Read Switch controller gyro/accel sensitivity coeffs (SDL3)

- src/video/wayland/SDL_waylandevents.c
Otherwise, it will be left in an uninitialized, non-empty state if the tablet protocol isn't present.
Fixes #13214
> wayland: Ensure that the tablet tool list is always initialized to empty

- test/gamepadutils.c
- test/gamepadutils.h
- test/testcontroller.c
Adds a visual suite to the testcontroller tool to help validate IMU data from new gamepad drivers and HID implementations.
Intended for developers working on controller firmware or SDL HID support to confirm correctness of IMU data processing.
The 3D gizmo renders accumulated rotation using quaternion integration of gyroscope packets. If a controller is rotated 90° in real space, the gizmo should reflect a 90° change, allowing quick detection of incorrect sensitivity or misaligned axes.
Also includes:
- Euler angle readout (pitch, yaw, roll)
- Real-time drift calibration display with noise gating and progress
- Accelerometer vector overlay
- Live polling rate estimation to verify update frequency
> Added tools for evaluating gyroscope accuracy and IMU polling rates.

- src/joystick/hidapi/SDL_hidapi_flydigi.c
Flydigi IMU rate now matches observed rate of packets in both dongle and wired connection.
Flydigi Vader 4 Pro IMU rate correction was set at a fixed 125hz. In actuality rate is 1000hz over dongle and 500hz when wired.
This fixes issues in downstream programs which relied on accurate time stamps for the gyro values.
Note: There is still some question over the gyro pitch and yaw speed rate - it may have a some sensor "deadzoning" or other response curves applied.
> Flydigi Vader 4 Pro IMU rate correction

- src/events/scancodes_xfree86.h
Fixes the scancodes of F21-F24 keys being reported as `SDL_SCANCODE_UNKNOWN` in Linux distributions.
Because of this those keys were unsupported, whatever the keysyms bound to it.
Add `SDL_SCANCODE_F21` to `SDL_SCANCODE_F24` in `xfree86_scancode_table2`, so these keys are recognized. SDL now sends events with `key.scancode` set to those scancodes, and `e->key.key` set to the corresponding keycode in the current keyboard layout.
The text input for those keys was already working and is unaffected.
https://github.com/libsdl-org/SDL/issues/13238
> Fix support for F21 to F24 scancodes on Linux

- src/render/vitagxm/SDL_render_vita_gxm.c
- src/render/vitagxm/SDL_render_vita_gxm_types.h
The same as https://github.com/libsdl-org/SDL/pull/13194 but for SDL3
Backported by a cherry-picking with a conflict resolution and adjusting of the code.
> [SDL3] Vita: Fixed absence of clipping when viewport is set

- src/hidapi/libusb/hid.c
A quick search implies that it is a bogus warning:
https://www.google.com/search?q=visual+studio+C5287
Fixes MSVC CI failures happening since yesterday.
> hidapi/libusb: disable C5287 warning in MSVC builds

- src/video/windows/SDL_windowsevents.c
- src/video/windows/SDL_windowsgameinput.cpp
I found that if you hold down a mouse button when leaving raw input mode (usually due to relative mouse mode being disabled), then the buttons will "stick" until you press them again.
This means that if you have a game that opens a menu with escape, and you hold down a mouse button while doing so, you have to click twice in order to click a menu button.
The raw input code changed a fair bit in SDL3, and `mouse_button_flags` is no longer invalidated when reading from raw input, so I added some code that resets the variable when reading any mouse button from GameInput or raw input. Which fixed the issue in the game I was encountering it in.
I can't find any issues that report this specific bug, since it seems like a relatively hard thing to diagnose.
Lemme know if any more info would be …
> win32: Invalidate window message mouse button flags when reading buttons from raw input or GameInput

- test/CMakeLists.txt
- test/testtray.c
Without this patch the installed `testtray` test points to nonexistent files.
> test: Fix resource paths in testtray

- src/audio/alsa/SDL_alsa_audio.c
it is informational only and seeing ERROR on the terminal was confusing
> alsa: change an SDL_LogError into SDL_LogDebug.

- src/joystick/hidapi/SDL_hidapi_ps4.c
- src/joystick/hidapi/SDL_hidapi_ps5.c
We're working on adopting SDL3 as our gamepad/joystick input driver in Godot Engine:
- https://github.com/godotengine/godot/pull/106218
We vendor a subset of the library (a bit hacked together to keep only the joystick/haptic/hidapi subsystems) and compile it with our own buildsystem using the same flags as the rest of Godot. (Would be happy to discuss this some more by email btw, SDL subsystems seem somewhat modular but there are cross-includes - e.g. `events` depending on `video` - which make it a bit tricky to just compile some parts).
This includes flags to disable floating-point contraction following this PR:
- https://github.com/godotengine/godot/pull/94655
We did this to fix precision differences on arm64 platforms with LLVM which caused bugs on macOS, but as there were signs that …
> joystick: Fix MSVC errors C2099 with `/fp:strict`

- include/SDL_keyboard.h
Added a reference to SDL_Keymod for the `mod` field of `SDL_Keysym` struct. The field's type is Uint16, so you can't quickly jump to definition (I saw that this is fixed in SDL3, which is nice!)
> keyboard: Add reference to SDL_Keymod in the comments

- src/audio/SDL_audio.c
`SDL_GetAudioDeviceChannelMap` will AV trying to memcpy from a `NULL` pointer if there is no channel map for the device.
#13276
> Fix #13276: Crash in SDL_GetAudioDeviceChannelMap

- src/video/x11/SDL_x11messagebox.c
In Factorio, we disable `SDL_FORK_MESSAGEBOX` because `Otherwise, when the game crashes, about 50% of the time it just sits there, hung in a call to waitpid for some reason` (direct quote from the blame).
In SDL2, we did this by editing the define in the source file, but I am attempting to avoid editing SDL3 source code, so I'd rather define it in our fastbuild configuration.
This PR allows that by only defining `SDL_FORK_MESSAGEBOX` if it is not already defined.
> Allow overriding SDL_FORK_MESSAGEBOX in build environment

- include/SDL3/SDL_hints.h
- src/main/generic/SDL_sysmain_callbacks.c
A use case where supporting floating point callback rates is useful is when setting the callback rate to the display's refresh rate, which isn't always an exact integer. So, I've added such support to the callback rate hint.
The change of `callback_rate_increment`'s type to `Uint64` is actually necessary now, because a nonzero less-than-one callback rate results in the increment being multiple seconds, so it's best to have as much room as possible for the increment in such a use case.
As `SDL_atof()` parses integer strings as expected, this PR doesn't introduce ABI breakage.
> Add support for floating point main callback rates

- src/video/wayland/SDL_waylandwindow.c
- src/video/wayland/SDL_waylandwindow.h
The spec states that xdg_surface must have seen an initial configure event before attaching a buffer, however, this was only being done when initially showing the window, and not after show->hide->show cycle.
Always wait for the initial configure event when (re)creating an xdg_surface as part of the show window sequence.
Fixes #13295
> wayland: Ensure that the xdg_surface is always configured after creation

- docs/README-macos.md
Replaces `SDL_GetEventState` with `SDL_EventEnabled` in documentation.
> README-macos.md: replace old API calls

- src/thread/psp/SDL_systhread.c
At the moment creating a thread with the name set to NULL will cause a crash on PSP, this PR resolves this.
I'll create this same PR for SDL3 if it is approved. The crash is caused by sceKernelCreateThread requiring the thread name to not be NULL. Since a lot of other platforms to allow thread names to be left blank, there is code out there which will cause this crash.
> SDL2: Don't crash PSP when no thread name is specified

- Xcode-iOS/Demos/src/fireworks.c
Significantly reduces CPU usage in the iOS fireworks demo by implementing proper frame rate limiting and idle state management.
- Replaced `SDL_Delay(1)` (targeting ~1000 FPS) with conditional rendering (targeting 60 fps or 10 fps depending on state)
- Added idle state detection to skip expensive operations when no particles are active.
**Performance improvements:**
- **Idle**: 120%+ CPU → 0-1% CPU  
- **Active**: 200%+ CPU → around 50% CPU
- Maintains full responsiveness and visual quality
I explored this as we are having significant performance issues with XCSoar on iOS, using SDL2 and OpenGLES (see https://github.com/XCSoar/XCSoar/issues/1693).
After checking your example, I thought this might be normal for OpenGLES on iOS since it was officially deprecated by Apple (and might not …
> Xcode-iOS/Demos/src/fireworks.c: Make rendering CPU efficient

- src/joystick/hidapi/SDL_hidapi_ps5.c
DualSense Edge natively reports at 1 kHz for all connection types, but gyro sample rate was limited to 250 Hz for USB.
> Allow 1 kHz sample rate for DualSense Edge over USB

- src/timer/unix/SDL_systimer.c
I'm marking this PR as draft since I'm not really sure this should be merged, because it fixes an issue on older Android devices. I'm opening it for discussion.
This PR works around a kernel bug described in the commit message (fixed upstream with [1]). The state of Android ecosystem is that old devices that have this bug won't ever be updated so the only possible solution is to work around the bug in SDL.
Android 8.1 (kernel 3.18.94) arm64 emulator image is the last OS version producing this bug. Judging by https://apilevels.com/ there are still ~7% of users using this OS version or lower.
I don't know if Android versions specify a minimum kernel version to be used with. If they don't, a vendor can decide to ship an older kernel with a new Android OS (for example, because the GPU driver …
> draft: don't use `CLOCK_MONOTONIC_RAW` on Android

- include/SDL3/SDL_gpu.h
The comment implies that `pitch` should only be set to the padding *between* elements, which may confuse a lot of newbies (like me..) and lead them to just set pitch to 0. Which obviously doesn't work.
This new comment is just a dumbed down version of what `pitch` actually is, it's the size of a single vertex (combined with any padding).
> Clarify SDL_GPUVertexBufferDescription.pitch comment

- src/gpu/vulkan/SDL_gpu_vulkan.c
Went through the code because I had an issue with something unrelated (was my own stuff that was the problem). I did however notice this in the function for binding compute descriptor sets that it reset the _Vertex_ uniform offsets instead of the _Compute_ one. No idea if there was an issue with this but made a pull request anyway for it. Go ahead and close it if it is not an issue.
> vulkan: Potential copy paste issue fix in VULKAN_INTERNAL_BindComputeDescriptorSets

- src/dialog/cocoa/SDL_cocoadialog.m
Uses the correct action `setNameFieldStringValue` of `NSSavePanel` to set the default file name. Originally, `setDirectoryURL` was used instead, which did not set the default file name.
Fixes issue #13014.
> For save file dialogs, make setting default file name on MacOS functional

- src/video/windows/SDL_windowskeyboard.c
Keymap construction is an expensive process, so keymaps are cached to facilitate fast switching, as they are static after initial construction, and do not need to be rebuilt every time they are changed at the system level.
In the typical case where the system is configured with a small number of keyboard layouts (currently 4, but can be adjusted), they will be constructed and pre-cached at startup to avoid the runtime overhead of dynamically building them on demand at first use, which could cause hitching in the case of a game with tight frame deadlines. Otherwise, keymaps will be constructed and added to/evicted from the cache as needed.
> win32: Implement keymap caching

- src/audio/alsa/SDL_alsa_audio.c
- src/core/linux/SDL_progressbar.c
- test/gamepadutils.h
- test/testcontroller.c
```c
[ 28%] Building C object CMakeFiles/SDL3-shared.dir/src/audio/alsa/SDL_alsa_audio.c.o
/path/to/SDL/src/audio/alsa/SDL_alsa_audio.c:1473:13: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
1473 | static bool ALSA_start_udev()
|             ^~~~~~~~~~~~~~~
/path/to/SDL/src/audio/alsa/SDL_alsa_audio.c:1486:13: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
1486 | static void ALSA_stop_udev()
|             ^~~~~~~~~~~~~~
/path/to/SDL/src/core/linux/SDL_progressbar.c:35:14: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
35 | static char *GetDBUSObjectPath()
|              ^~~~~~~~~~~~~~~~~
/path/to/SDL/src/core/linux/SDL_progressbar.c:65:14: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
65 | static …
```
> Fixed a few "-Wstrict-prototypes" warnings

- src/gpu/SDL_gpu.c
`render_pass` gets dereferenced in `RENDERPASS_COMMAND_BUFFER` before the NULL check.
```c
/path/to/SDL/src/gpu/SDL_gpu.c:2248:8: warning: check of ‘render_pass’ for NULL after already dereferencing it [-Wanalyzer-deref-before-check]
2248 |     if (render_pass == NULL) {
|        ^
‘SDL_EndGPURenderPass_REAL’: events 1-2
2246 |     commandBufferCommonHeader = (CommandBufferCommonHeader *)RENDERPASS_COMMAND_BUFFER;
|                               ^
|                               |
|                               (1) pointer ‘render_pass’ is dereferenced here
2247 | 
2248 |     if (render_pass == NULL) {
|        ~                       
|        |
|        (2) ⚠️  pointer ‘render_pass’ is checked for NULL here but it was already dereferenced at (1)
```
> SDL_gpu.c: Fixed deref-before-check warning

- src/audio/SDL_audiotypecvt.c
This fixes #13432 :
Building SDL for armeabi-v7a gives this warning:
```
SDL/src/audio/SDL_audiotypecvt.c:541:14: warning: '#pragma FENV_ACCESS' is not supported on this target - ignored [-Wignored-pragmas]
541 | #pragma STDC FENV_ACCESS ON
```
> Fix warning on Android arm-v7

- .github/workflows/create-test-plan.py
- .github/workflows/generic.yml
- use Unix Makefiles (with parallelization) CMake generator
- use binutils strings binary from devkitpro
( Manual backport of commit e6d200e51c88a0406c770c52bf7f415181243189 )
> ci+n3ds: avoid apt-get package manager

- src/video/SDL_sysvideo.h
- src/video/SDL_video.c
- src/video/windows/SDL_windowsopengl.c
- src/video/windows/SDL_windowsopengl.h
Implements attribute SDL_GL_FLOATBUFFERS for SDL_GL_GetAttribute using [GL_ARB_color_buffer_float](https://registry.khronos.org/OpenGL/extensions/ARB/ARB_color_buffer_float.txt) extension.
Also, sets WGL_PIXEL_TYPE_ARB attribute to WGL_TYPE_RGBA_FLOAT_ARB only if extension WGL_ARB_pixel_format_float is available.
> Implement SDL_GL_GetAttribute for SDL_GL_FLOATBUFFERS

- src/video/SDL_sysvideo.h
- src/video/SDL_video.c
- src/video/windows/SDL_windowsopengl.c
- src/video/windows/SDL_windowsopengl.h
Implements attribute SDL_GL_FLOATBUFFERS for SDL_GL_GetAttribute using [GL_ARB_color_buffer_float](https://registry.khronos.org/OpenGL/extensions/ARB/ARB_color_buffer_float.txt) extension.
Also, sets WGL_PIXEL_TYPE_ARB attribute to WGL_TYPE_RGBA_FLOAT_ARB only if extension WGL_ARB_pixel_format_float is available.
> [SDL2] Implement SDL_GL_GetAttribute for SDL_GL_FLOATBUFFERS

- src/video/wayland/SDL_waylanddatamanager.c
@Kontrabant
Here, if the parameter `offer` is NULL, an error message is only set but nothing else is done.
Is it good enough to just return?
```c
/path/to/SDL/src/video/wayland/SDL_waylanddatamanager.c:397:19: warning: Access to field 'data_device' results in a dereference of a null pointer (loaded from variable 'offer') [clang-analyzer-core.NullDereference]
397 |     data_device = offer->data_device;
|                   ^~~~~
/path/to/SDL/src/video/wayland/SDL_waylanddatamanager.c:394:9: note: Assuming 'offer' is null
394 |     if (!offer) {
|         ^~~~~~
/path/to/SDL/src/video/wayland/SDL_waylanddatamanager.c:394:5: note: Taking true branch
394 |     if (!offer) {
|     ^
/path/to/SDL/src/video/wayland/SDL_waylanddatamanager.c:397:19: note: Access to field 'data_device' results in a …
```
> SDL_waylanddatamanager.c:Wayland_data_offer_check_source(): Return when `offer` is NULL

- src/video/cocoa/SDL_cocoawindow.m
Check NSWindow::isVisible before sending SDL_WINDOWEVENT_RESTORED during Cocoa_WindowListener::windowDidResize
Fixes `SDL_WINDOWEVENT_RESTORED` being sent to the application while the window is still miniaturized. This can happen if macOS resizes the window as a result of a display density change.
This can happen if the user changes their display resolution settings in `System Preferences > Displays` from the default on a retina display to 2x the default.
This can also happen if the user disconnects a non-retina display and the OS needs to move all application windows to another retina display.
In either case, any miniaturized windows will be resized accordingly while remaining miniaturized. SDL was treating all window resizes as if the window was visible and not miniaturized, which is …
> Fix SDL_WINDOWEVENT_RESTORED firing on macOS if the window is still miniaturized during a resize

- src/core/linux/SDL_udev.c
- src/core/linux/SDL_udev.h
- src/joystick/linux/SDL_sysjoystick.c
xpad has a series of questionable design choices when it comes to button mapping. Notably, BTN_TRIGGER_HAPPY1-4 are used for the D-pad on dance mats instead of the typical BTN_DPAD_*, and maps the paddles to BTN_TRIGGER_HAPPY5-8. This commit plumbs through driver detection for a udev device and adds special exceptions for xpad's quirks. When not using xpad, it assumes that the paddles are instead mapped to BTN_TRIGGER_HAPPY1-4, which is what upcoming driver projects use instead.
It also exposes KEY_RECORD as the share button regardless of vendor, which had previously been gated behind being a Microsoft controller. All Xbox Series controllers can include this button, and many third party ones do.
I've noticed that there is a special exception to Xbox 360 wireless controller mapping of the …
> joystick: Improve Xbox controller mapping with xpad quirks

- src/joystick/hidapi/SDL_hidapi_flydigi.c
Binary integer literals are a C23 feature.
This commit turns them into hexadecimal literals.
```c
[ 40%] Building C object CMakeFiles/SDL3-shared.dir/src/joystick/hidapi/SDL_hidapi_flydigi.c.o
/path/to/SDL-git/src/joystick/hidapi/SDL_hidapi_flydigi.c:338:14: warning: binary integer literals are a C23 extension [-Wc23-extensions]
338 |         case 0b0001:
|              ^
/path/to/SDL-git/src/joystick/hidapi/SDL_hidapi_flydigi.c:341:14: warning: binary integer literals are a C23 extension [-Wc23-extensions]
341 |         case 0b0011:
|              ^
/path/to/SDL-git/src/joystick/hidapi/SDL_hidapi_flydigi.c:344:14: warning: binary integer literals are a C23 extension [-Wc23-extensions]
344 |         case 0b0010:
|              ^
/path/to/SDL-git/src/joystick/hidapi/SDL_hidapi_flydigi.c:347 …
```
> Replaced binary integer literals with hexadecimal integer literals

- src/stdlib/SDL_getenv.c
The current implementation uses the returned address of the `dlsym` function directly to load the `environ` symbol. But this function doesn't return the address to the symbol itself, instead it returns the address to the location where the actual address is stored, i.e. it's an additional indirection. Consequently, the implementation fails to load and process the environment variables successfully.
One example where this error shows up is in the `Dialog API`: in an `X11` environment, the `zenity` driver requires access to the user's `DISPLAY` and `XAUTHORITY` environment variables. Because these variables aren't transfered to the `zenity` process, no dialogs are shown. This can be exercised in the `test/testdialog.c` testprogram.
The fix changes the indirection level of the `dlsym` call …
> SDL_getenv.c: fix dynamic loading of environ symbol on FreeBSD

- src/audio/psp/SDL_pspaudio.c
It turns out rc can be higher than 0, which does not mean it failed. I will make an issue for it, since it seems our documentation does not mention this.
This resolves #13411
> psp: fix audio not playing

- src/gpu/vulkan/SDL_gpu_vulkan.c
AcquireGPUSwapchainTexture can return the wrong sizes if acquiring the image fails and the swapchain is recreated, since the window dimensions could have changed.
I ran into the same issue as https://github.com/libsdl-org/SDL/issues/12820 and I believe this is the root cause.
> GPU: Fix wrong Vulkan swapchain size when retrying acquire

- src/joystick/SDL_gamepad.c
- src/joystick/hidapi/SDL_hidapi_sinput.c
- Implement correct SInput generic mapping string to map analog axes
- Implement 6 axis count fallback for generic SInput Device
Reported-by: Antheas Kapenekakis <git@antheas.dev>
> Fix Axis Inputs for Generic SInput Device

- src/render/opengles2/SDL_render_gles2.c
<details><summary>Warning</summary>
<p>
```c
[ 19%] Building C object CMakeFiles/SDL3-shared.dir/src/render/opengles2/SDL_render_gles2.c.o
/path/to/SDL/src/render/opengles2/SDL_render_gles2.c:1744:20: warning: Potential leak of memory pointed to by 'data' [clang-analyzer-unix.Malloc]
1744 |             return false;
|                    ^
/usr/lib/clang/20/include/stdbool.h:26:15: note: expanded from macro 'false'
26 | #define false 0
|               ^
/path/to/SDL/src/render/opengles2/SDL_render_gles2.c:1607:5: note: Control jumps to 'case SDL_PIXELFORMAT_NV12:'  at line 1618
1607 |     switch (texture->format) {
|     ^
/path/to/SDL/src/render/opengles2/SDL_render_gles2.c:1622:9: note:  Execution continues on line 1637
1622 |         break;
|         ^ …
```
> Fix potential memory leak in SDL_render_gles2.c

- src/video/wayland/SDL_waylandwindow.c
Moves main window surface destruction to after window decoration destruction, prevent a premature blank that left the inside of the window blank while the decorations were still visible.
#13481
> wayland: reorder surface destruction to avoid premature blanking

- src/video/SDL_surface.c
- test/testautomation_surface.c
SDL_BlitSurfaceScaled could crash when passed large coordinates, due to final_dst.w or final_dst.h getting negative values.
SDL_GetRectIntersection calls fail due to potential overflow issue so clipping is not done but there is no error to the user, until segmentation fault.
#7614 sounds similar.
> Fix SDL_BlitSurfaceScaled crash

- src/joystick/hidapi/SDL_hidapi_sinput.c
This is a typo that does not compile anymore.
cc @mitchellcairns
> sinput: fix compiling with debug output on

- src/hidapi/linux/hid.c
hidapi error messages are only allocated if SDL is not used by hidapi for error messages.
Therefore `free()` only needs to be called without SDL.
Gets rid of following warning:
```c
[ 15%] Building C object CMakeFiles/SDL3-shared.dir/src/hidapi/SDL_hidapi.c.o
path/to/SDL/src/hidapi/linux/hid.c:137:2: warning: Attempt to free released memory [clang-analyzer-unix.Malloc]
137 |         free(*error_str);
|         ^
path/to/SDL/src/hidapi/SDL_hidapi.c:1552:9: note: Assuming 'SDL_hidapi_refcount' is not equal to 0
1552 |     if (SDL_hidapi_refcount == 0 && SDL_hid_init() < 0) {
|         ^~~~~~~~~~~~~~~~~~~~~~~~
path/to/SDL/src/hidapi/SDL_hidapi.c:1552:34: note: Left side of '&&' is false
1552 |     if (SDL_hidapi_refcount == 0 && SDL_hid_init() < 0) {
|                                  ^ …
```
> Fix double-free warning in src/hidapi/linux/hid.c

- src/video/x11/SDL_x11events.c
- src/video/x11/SDL_x11events.h
- src/video/x11/SDL_x11xinput2.c
Discard wheel events from "Master" devices to avoid duplicates. X doesn't have specific wheel events, but press events for buttons 4 through 7 represent one 'tick' of the wheel in a specific direction.
Other buttons must be passed through for pointer emulation when using a pen to work correctly.
@icculus, could you give this a check with a pen to make sure it didn't break anything in that case?
Fixes #13430
> x11: Filter mouse wheel events from "Master" devices

- include/SDL3/SDL_assert.h
`SDL_assert()` and `SDL_enabled_assert()` use `0` to initialize pointer members instead of `NULL`:
```c
static struct SDL_AssertData sdl_assert_data = { 0, 0, #condition, 0, 0, 0, 0 }; \
```
instead of
```c
static struct SDL_AssertData sdl_assert_data = { false, 0, #condition, NULL, 0, NULL, NULL }; \
```
When compiling SDL with the flag `-Wzero-as-null-pointer-constant` there are 2108 warnings instead of "only" 130 because of that.
This flag could have been used to detect the issue https://github.com/libsdl-org/SDL/issues/13628 with a pre-C23 standard:
```c
/path/to/SDL/src/render/vulkan/SDL_render_vulkan.c: In function ‘VULKAN_GetSampler’:
/path/to/SDL/src/render/vulkan/SDL_render_vulkan.c:3763:20: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
3763 | …
```
> SDL_enabled_assert(): Use `NULL` istead of `0` to explicity initialize the pointer members of SDL_AssertData

- src/video/SDL_video.c
`window->HDR.SDR_white_level` is compared with itself, which makes part of the condition always false.
> Fix condition for setting HDR properties

- src/core/android/SDL_android.c
This PR fixes `SDL_GlobDirectory` on Android.
When regular `opendir` fails, it proceeds to check asset manager. The offending assertion checks for empty path (top-level asset bundle directory), or that the path ends with a separator. The supplied comment reads `SDL_SYS_EnumerateDirectory() should have verified this.`, but in fact `SDL_SYS_EnumerateDirectory` guarantees there would no trailing slash:
https://github.com/libsdl-org/SDL/blob/483b8d4d984a66e6e4b063828743afd768683fc3/src/filesystem/posix/SDL_sysfsops.c#L44-L54
Assertion is still required to handle `NULL` (`AAssetManager_openDir` will cause segmentation fault if path is `NULL`).
> Fix directory globbing on Android

- src/video/windows/SDL_windowsevents.c
- src/video/windows/SDL_windowswindow.c
SDL_GetWindowFlags() also ORs in pending flags, whereas the current state is needed here, particularly when creating/showing a window.
Fixes #13695 (for real this time)
> win32: Use the current flags to determine if NCCALCSIZE is required

- src/core/unix/SDL_gtk.c
- src/core/unix/SDL_gtk.h
- src/tray/unix/SDL_tray.c
This commit changes the location of tray menu icons on Linux. Previously, these icons were stored in `/tmp/SDL_<id>/<n>.bmp`. Unfortunately, with sandboxed application packaging formats like Flatpak and the strict marketplace distribution guidelines that go with them, writing to `/tmp` is *heavily* discouraged and would require developers using SDL to apply for an exemption on every application with a tray icon. This instead moves the directory to `${XDG_CACHE_HOME}/SDL/tray-<id>/<n>.bmp`. This is a location that is accessible in these sandboxed environments with an additional `SDL` namespace added to pass filtering rules that linters use. This pulls in no additional dependencies, and simply relies on `g_get_user_cache_dir` from `glib`.
An example of the strict sandboxing rules I am …
> tray: linux - use `.cache` directory for temporary icon paths

- src/video/wayland/SDL_waylandvideo.c
This commit replaces the keyboard check with a pointer check when the mouse is removed.
cc @Kontrabant
> SDL_waylandvideo.c:display_remove_global(): Check pointer when removing mouse

- src/gpu/vulkan/SDL_gpu_vulkan.c
According to the `vkDeviceWaitIdle` specification, `Host access to all VkQueue objects created from device must be externally synchronized`.
In some cases, like creating a texture, a submit can happen at the same time as vkDeviceWaitIdle.
> GPU: Hold submit lock before waiting for device idle

- src/joystick/SDL_gamepad.c
- In previous firmware for my gamepads, the buttons were sent in a static order for ABXY according to button letter rather than physical position.
- To be more 'transparent' to the driver and save myself from future fragmentation, I am updating the mappings to be consistent and always expect the buttons in a given cardinal format, rather than a glyph format.
- This better aligns with the existing 'fallback' behavior of a generic device and will help gamepad designers achieve better consistency.
- Updated to use the SEWN cardinal layout to better reflect standard gamepads.
- Coincides with firmware library update: https://github.com/HandHeldLegend/HOJA-LIB-RP2040/commit/d45810e32b55abd382f67eb8043602c2c6da5213
> SInput: Mapping updates for GCUltimate/ProGCC

- CMakeLists.txt
This change keeps the existing MSVC flags when CMake is run more than once.
Fix #13375
> Keep MSVC Flags Consistent across CMake runs

- src/video/uikit/SDL_uikitviewcontroller.m
- Alternative to / closes #11699 
When selecting a password to auto-fill in the current text field, the `textField.text` property is overwritten with that password, and if the password is less than 16 characters, it triggers the code that resets the text content and messes up the entire logic that is supposed to perform backspaces and such.
The fix is to simply reset the text (i.e. fill back the "obligatory for backspace" text) when the event is triggered with a `string` of length zero, i.e. when the user deletes characters (see [docs](https://developer.apple.com/documentation/uikit/uitextfielddelegate/textfield(_:shouldchangecharactersin:replacementstring:)?language=objc)).
The fix above can be argued to be more of a band-aid than a solid fix, but there's no better fix than to rewrite …
> Fix iOS text input not working with password integration

- src/audio/pulseaudio/SDL_pulseaudio.c
For recording using PulseAudio, use fragsize buffer for recording to fix issues in Sober.
Fixes #13399
> Use PulseAudio fragsize buffer correctly

- test/testautomation_rect.c
Fixing these three warnings, which appear when building with emscripten and tests enabled:
```c
[ 54%] Building C object test/CMakeFiles/testautomation.dir/testautomation_rect.c.o
/path/to/SDL/test/testautomation_rect.c:927:45: warning: variable 'rectA' is uninitialized when passed as a const pointer argument
here [-Wuninitialized-const-pointer]
927 |     intersection = SDL_GetRectIntersection(&rectA, (SDL_Rect *)NULL, &result);
|                                             ^~~~~
/path/to/SDL/test/testautomation_rect.c:1175:45: warning: variable 'rectA' is uninitialized when passed as a const pointer
argument here [-Wuninitialized-const-pointer]
1175 |     intersection = SDL_HasRectIntersection(&rectA, (SDL_Rect *)NULL);
|                                             ^~~~~ …
```
> emscripten tests: fix warning: uninitialized variable

- src/gpu/vulkan/SDL_gpu_vulkan.c
The [description of VkSubpassDescription](https://registry.khronos.org/vulkan/specs/latest/man/html/VkSubpassDescription.html) states that the subpass `pResolveAttachments` is an array _of the same size_ as the `pColorAttachments` array (the color attachment references), each resolve reference corresponds to the color attachment in the same index in the latter array. When a color attachment has no resolve operation, the `attachment` member of the `VkAttachmentReference` must be `VK_ATTACHMENT_UNUSED`.
The current code is incorrect as it seems to assume the `pResolveAttachments` array is of different length.
This results in the following bug when one uses multi-render targets: When there are 2 MRTs, **MRT#0** is a multisample texture with no resolve texture (and whatever store op) and …
> GPU/vulkan : fix indexing error for resolve attachment references

- include/SDL3/SDL_gpu.h
- src/gpu/d3d12/SDL_gpu_d3d12.c
We previously thought this wasn't possible because constant buffer offsets and partial updates were unavailable, but we were reading the wrong table - this is only the case for D3D11...
https://learn.microsoft.com/en-us/windows/win32/direct3d11/overviews-direct3d-11-devices-downlevel-intro
... while 12 doesn't list this feature at all:
https://learn.microsoft.com/en-us/windows/win32/direct3d12/hardware-feature-levels
We double checked and Jesse Natalie confirmed that this feature is required for D3D12 even for 11_0 drivers. (Thanks Jesse!)
> gpu: D3D12 only requires feature level 11_0.

- include/SDL3/SDL_gpu.h
- src/gpu/d3d12/SDL_gpu_d3d12.c
This is equivalent to https://github.com/libsdl-org/SDL/pull/13781 but it didn't cherry-pick cleanly due to differences between 3.2 and 3.4.
> gpu: D3D12 only requires feature level 11_0 with Resource Binding Tier 2

- test/testffmpeg_vulkan.c
The `AVVulkanDeviceQueueFamily` struct was introduced by libavutil 59.34.100: https://github.com/FFmpeg/FFmpeg/commit/13489c8a2154a2e0e8fd3c3c45f7856b4c3110b0 .
This test would fail to build with FFmpeg 7.0.3 "Dijkstra", for example flatpak `org.freedesktop.Platform//24.08`.
You can test this with:
```bash
flatpak install org.freedesktop.Sdk//24.08
flatpak run --filesystem="$(pwd)" org.freedesktop.Sdk//24.08 -c 'cmake -B _build_fp -G Ninja -DSDL_TESTS=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON'
flatpak run --filesystem="$(pwd)" org.freedesktop.Sdk//24.08 -c 'cmake --build _build_fp'
SDL_LOGGING=system=debug flatpak run --devel --filesystem="$(pwd)" --device=dri --socket=wayland org.freedesktop.Sdk//24.08 -c './_build_fp/test/testffmpeg'
```
> testffmpeg: avutil queue family version check

- src/joystick/SDL_gamepad.c
- src/joystick/android/SDL_sysjoystick.c
Previously, `SDL_ShouldIgnoreJoystick` wasn't being called for Android, and fingerprint sensors were recognized as joysticks. I also decided to change the code a little bit so other fingerprint sensors (possible fingerprint sensors list here: https://github.com/godotengine/godot/issues/47656#issuecomment-2200419158) are ignored too. This change was tested using Godot Engine in my fork in a separate branch: https://github.com/Nintorch/godot/tree/sdl-test and I can confirm it works as expected.
https://github.com/libsdl-org/SDL/issues/4971
> Allow Android to ignore unnecessary joysticks (like fingerprint sensors)

- src/joystick/emscripten/SDL_sysjoystick.c
This PR adds support for Emscripten (Web) joystick rumble support via `EM_ASM_INT` Emscripten macro and Web Gamepad API (specifically, gamepad's `vibrationActuator` property). I haven't found built-in Emscripten support for this feature in a form of C API, so that's why I decided to wrap pieces of JavaScript code inside `EM_ASM_INT` macros for this to work. (P.S. I used `object['property']` notation instead of `object.property` because of JavaScript minifiers and [Emscripten wiki suggesting to use it](https://emscripten.org/docs/api_reference/emscripten.h.html#c.EM_ASM:~:text=As%20of%20Emscripten%201.30.4%2C%20the%20contents%20of%20EM_ASM%20code%20blocks%20appear%20inside%20the%20normal%20JS%20file%2C%20and%20as%20result%2C%20Closure%20compiler%20and%20other%20JavaScript%20minifiers%20will …
> Add Emscripten (web) joystick rumble support

- src/video/x11/SDL_x11xinput2.c
Use the scaled motion values if the relative system scale hint is set, and a custom transformation function is not set (matches the behavior of other platforms).
Closes #13748
> x11: Enable the relative mouse system scale hint.

- src/events/SDL_keymap.c
- src/video/wayland/SDL_waylandevents.c
- src/video/windows/SDL_windowskeyboard.c
- src/video/x11/SDL_x11keyboard.c
If a bound keymap is being destroyed, unbind it to ensure that the keyboard state won't be left pointing to an invalid keymap. Backends now no longer need to manually do this when destroying keymaps during keyboard removal and shutdown.
Closes #13749
> keyboard: Release bound keymaps during the destruction process

- src/process/windows/SDL_windowsprocess.c
> The problem
> Windows. Windows is the problem.
> [#8129](https://github.com/libsdl-org/SDL/issues/8129)
This PR takes the [QT](https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/io/qprocess_win.cpp#n648) method of sending WM_CLOSE to all application window, then send WM_CLOSE to the main thread of the child process.
Windows always makes things more complicated.
On Windows, there are multiple ways to gracefully terminate a process.
1. Send WM_CLOSE to a Window.
2. Send Ctrl+Break event with `GenerateConsoleCtrlEvent`.
None of these two ways cover all applications - WM_CLOSE only works when the program has a message loop like in GUI programs, `GenerateConsoleCtrlEvent` has [quirks](https://github.com/microsoft/Terminal/issues/335).
> Process(windows): try sending WM_CLOSE for graceful process termination

- src/render/opengl/SDL_render_gl.c
- src/render/opengles2/SDL_render_gles2.c
- src/video/SDL_sysvideo.h
- src/video/SDL_video.c
- src/video/wayland/SDL_waylandvideo.c
- src/video/wayland/SDL_waylandwindow.c
- src/video/wayland/SDL_waylandwindow.h
When attaching a renderer (GL based specifically) to a window that was not created with the appropriate flags, the window would be destroyed and recreated to configure it for the desired rendering backend. While most of the issues with this have been mitigated over time, there can still be some undesirable side effects from doing so on certain platforms.
If the window was just created and was never configured for any graphics context, it is possible that the reconfiguration can be done without destroying the window first.
The Wayland implementation fixes an issue when creating a window with the fullscreen flag on wlroots based Wayland compositors, and can likely be extended to other platforms to avoid unnecessarily destroying/recreating a window in the very common case where a window is …
> video: Try to reconfigure the window for OpenGL without destroying it

- src/tray/unix/SDL_tray.c
- src/video/SDL_stb.c
- src/video/SDL_stb_c.h
- src/video/stb_image_write.h
PNG has better compatibility with certain desktops.
This requires the stb_image_write header library for PNG writing functionality.
Fixes #12716
> tray: Save icons on *nix platforms to PNG instead of BMP

- src/SDL.c
I did not add another `!defined(SDL_CAMERA_DISABLED)` as the camera subsystem depends on the video subystem.
https://github.com/libsdl-org/SDL/pull/13807#issuecomment-3228503301
> Don't compile helper function when building without audio/video/joystick support

- src/dialog/windows/SDL_windowsdialog.c
The IFileDialog support [commit](https://github.com/libsdl-org/SDL/commit/355c001a541d286997a321a63a6eaed306982bae) assumed the existence of a couple function/enum/GUID definitions from `shlobj.h` and `shlobjidl.h` which don't exist if `_WIN32_WINNT` is defined to be less than `0x0600`, breaking XP build compatibility.
So, to retain compatibility without requiring the definitions from the headers themselves, just do a couple things manually:
- Define the `FILEOPENDIALOGOPTIONS` type/enum values (guarded behind `__IFileDialog_INTERFACE_DEFINED__`)
- Define the `IFileDialog`, `IFileDialog2`, and `IFileOpenDialog` vtables (guarded behind their respective `_INTERFACE_DEFINED__` macros)
- Define all of the GUIDs we need which aren't available in the XP headers, prefixed with `SDL_`, similar to …
> dialog: Fix compilation with pre-Vista headers.

- include/SDL3/SDL_sensor.h
Matches the convention set by other enum types within SDL, such as SDL_GamepadButton
This allows people to iterate over all sensor types explicitly. For me, this is to create a fast array lookup for each sensor type.
> Add SDL_SENSOR_COUNT to SDL_SensorType

- src/gpu/SDL_gpu.c
- src/gpu/vulkan/SDL_gpu_vulkan.c
Found when running in valgrind looking at another issue.
- RenderPass' depth_stencil_target
Tripped in SDL_BindGPUFragmentSamplers when not binding a DS target
- VulkanCommandBuffer's swapchainRequested
Tripped in VULKAN_Submit for the end transition barrier when creating an image. The field is only reset when reused, not on first use
> Fix two uninitialized variables in SDL-GPU

- android-project/app/src/main/java/org/libsdl/app/HIDDeviceUSB.java
- android-project/app/src/main/java/org/libsdl/app/SDLActivity.java
- android-project/app/src/main/java/org/libsdl/app/SDLControllerManager.java
- android-project/app/src/main/java/org/libsdl/app/SDLSurface.java
Since min API supported is 21
we can assume  `Build.VERSION.SDK_INT  >= 21` and simplify some checks.
this also merge SDLJoystickHandler_API16, SDLJoystickHandler_API19 and SDLJoystickHandler
into SDLJoystickHandler
> Android: simplification since min API supported is 21

- src/gpu/vulkan/SDL_gpu_vulkan.c
Got a report from someone with an old driver that didn't have this extension; this is only needed for KHR_driver_properties and we have a fallback for when this isn't available, so skip it where possible.
> gpu: VK_KHR_get_physical_device_properties2 can be optional

- CMakeLists.txt
- cmake/sdlcompilers.cmake
I think `include/SDL3/SDL_intrin.h` should get a similar makeover.
> cmake: use TargetConditionals.h for SIMD testing on Apple

- src/video/SDL_RLEaccel.c
- src/video/SDL_blit.c
- src/video/SDL_surface.c
Reference https://github.com/libsdl-org/sdl2-compat/issues/476
> Don't set SDL_SURFACE_LOCK_NEEDED until a surface is RLE encoded

- src/main/ios/SDL_sysmain_callbacks.m
To achieve > 60 Hz refresh rates on iOS it is required to setup CADisplayLink callback and set preferredFrameRateRange to appropriate values. This was being done only in `src/video/uikit/SDL_uikitviewcontroller.m`. However when main callbacks are used then different CADisplayLink dictates refresh rate.
Fixes https://github.com/libsdl-org/SDL/issues/13882
> iOS: Set preferredFrameRateRange in main callbacks CADisplayLink to make > 60 Hz refresh rates work

- test/testrendertarget.c
This file was never added, and I believe this just had a 50% alpha channel added to the standard icon.bmp
Fixes https://github.com/libsdl-org/SDL/issues/13394
> Removed reference to icon-alpha.bmp

- src/video/cocoa/SDL_cocoaevents.m
Older compilers don't understand this syntax.
> Guard use of @available in SDL_cocoaevents.m

- src/video/x11/SDL_x11framebuffer.c
An alternative to #13747. Can you confirm if this fixes it @allelomorph?
> X11: Check for invalid opcodes in SHM error handler

- src/render/gpu/SDL_render_gpu.c
Creating buffers in GPU is very expensive (NSight clocked around 1.5 ms in Debug for the CPU/GPU buffer). We need to make sure to set the size so that we don't reallocate each frame.
> Fix reallocation of GPU renderer vertex buffer

- src/video/emscripten/SDL_emscriptenframebuffer.c
- src/video/emscripten/SDL_emscriptenmouse.c
- src/video/emscripten/SDL_emscriptenvideo.c
- Specifying an alpha format for the framebuffer means that the alpha channel doesn't need to be set in `Emscripten_UpdateWindowFramebuffer`.
- Using `SDL_PIXELFORMAT_RGBA32` seems to be closer to what [the documentation](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas) says, which describes pixel data in terms of bytes rather than packed words.
> Consistently use SDL_PIXELFORMAT_RGBA32 with Emscripten

- test/testprocess.c
Previously the test would kill the child process while it was in the process of initializing (loading DLLs, etc) and this would cause the test to fail.
> Fixed testprocess on 32-bit Windows

- .github/workflows/create-test-plan.py
This architecture is deprecated and is now failing with: Windows SDK 10.0.22621.0 : 'C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um' not found or was incomplete
Fixes https://github.com/libsdl-org/SDL/issues/13949
> Remove Windows 32-bit ARM build from CI

- src/video/wayland/SDL_waylandmouse.c
'vd' and 'd' are only used if SDL_USE_LIBDBUS is set.
```console
../src/video/wayland/SDL_waylandmouse.c: In function 'Wayland_InitMouse':
../src/video/wayland/SDL_waylandmouse.c:1054:20: warning: unused variable 'd' [-Wunused-variable]
1054 |     SDL_VideoData *d = vd->internal;
|                    ^
```
> wayland: Silence unused variable warning

- src/joystick/apple/SDL_mfijoystick.m
The current macos joypad implementation uses vendorName as the joy name.
The vendorName on macos is just the local device name of the controller. This name can also be changed by the user by simply changing the name of the device in the Bluetooth settings. productCategory on the other hand always returns a more fitting unchanging device name.
So for example: If I connect my Switch Pro Controller that I renamed to "My amazing controller" to my laptop, vendorName is "My amazing controller", whereas e.g. on Windows it is set to "Nintendo Switch Pro Controller" (iirc). If the joy name was set to productCategory instead the result would be "Switch Pro Controller", which would help properly identify which controller is actually connected to the computer.
[Relevant Apple …
> [apple] Use productCategory instead of vendorName for joypad name

- docs/README-ps2.md
- include/SDL3/SDL_hints.h
- src/render/ps2/SDL_render_ps2.c
I've been wanting to use the lowres 240p mode on PS2 as I like to do software rendering, and the CPU is somewhat weak. These changes allow for that.
This adds the special hints: `SDL_HINT_PS2_GS_WIDTH`, `SDL_HINT_PS2_GS_HEIGHT`, `SDL_HINT_PS2_GS_PROGRESSIVE`, `SDL_HINT_PS2_GS_MODE`
They allow for the framebuffer width and height to be set, progressive to be turned on/off and to decide which regional format to use for the signal (PAL/NTSC). Furthermore, the region is no longer overridden by default, so the console will use its native region, instead of NTSC.
https://github.com/ps2dev/ps2sdk-ports/issues/183
https://github.com/libsdl-org/SDL/pull/13969
> [SDL3] [PS2] Framebuffer resolution + 240p/480p + PAL support

- test/testautomation_video.c
Like emscripten, window positioning and sizing is not supported on Android.
> testautomation: fix video tests on Android

- src/tray/SDL_tray_utils.c
- src/tray/SDL_tray_utils.h
- src/tray/windows/SDL_tray.c
re-add the tray icon upon taskbar restart
tray will be lost when taskbar restart
> tray(Win32): re-add the tray icon upon taskbar restart

- src/core/android/SDL_android.c
> Android: fix 'SDL_MessageBoxFlags' is not a valid JVM type.

- src/video/x11/SDL_x11messagebox.c
- src/video/x11/SDL_x11toolkit.c
- src/video/x11/SDL_x11toolkit.h
This removes multiple text positoning hacks, this should fix the positoning errors on many fonts.
> X11TK: Remove text positioning hacks, use proper ascent values.

- src/render/psp/SDL_render_psp.c
Since it's no known way to use geuine viewport with PSP SDK, I implemented the workaround using manually added/subtracted offsets to vertices passing to the render API. To assign viewport and cliprect in valid way, I copied part of code from the Vita's module and adjusted it to work on PSP.
Just a small note to author of #13314, @fjtrujy, please take changes that I done into your work since the viewport via existing way just doesn't work at all.
There are showcases made on emulator (it's absoutely same on hardware):
EDIT: This valid on emulator, on hardware it glitchies because quick alternation of values seems unsafe.
Since existing API calls of `sceGuOffset` and `sceGuViewport` give no effect in order to set the viewport, however, scissors works as charm, I found that I can replicate …
> SDL_render_psp.c: Implemented working viewport support

- .github/workflows/generic.yml
- cmake/PkgConfigHelper.cmake
- test/testffmpeg.c
This fixes:
- unused static variable warning (`SDL_IID_ID3D11Resource` is unused)
- `.a` static suffix is also present in `.dll.a` mingw import libraries
- testffmpeg not being tested on msys2 ci
> ci: build testffmpeg on MinGW (msys2) build bots

- src/video/x11/SDL_x11keyboard.c
XDestroyIC crashes if passed a null parameter.
Fixes #14089
Fixes #14076
> x11: Check for a valid input context before destroying it

- include/SDL3/SDL_video.h
https://github.com/libsdl-org/SDL/issues/14107
> SDL_WINDOWPOS_* macros are to be used with SDL_[GS]etWindowPosition

- include/SDL3/SDL_hints.h
- include/SDL3/SDL_video.h
- src/video/emscripten/SDL_emscriptenevents.c
- src/video/emscripten/SDL_emscriptenvideo.c
- src/video/emscripten/SDL_emscriptenvideo.h
Same idea as before, but this has moved to an Emscripten-specific window property and override hint.
Normal testsprite:
testsprite turning on the FILL_DOCUMENT setting:
This takes extra steps to put everything in the DOM except the canvas into a hidden div, so nothing is seen rendering when the window resizes and there's no risk of scrollbars popping up if the document would overflow window size due to the elements behind the canvas:
...everything gets put back when destroying the window:
This still needs to be tested with HighDPI on Windows, as that was an issue mentioned in the original issue, so this is a Draft PR for now.
Fixes #11949.
> emscripten: Another attempt at optionally having the canvas use whole window.

- CMakeLists.txt
- src/stdlib/SDL_mslibc.c
- test/testautomation_stdlib.c
Aside from a typo in `CMakeLists.txt`, the main issue is the new _ftoul2_legacy() builtin used for `double` → `uint64_t` conversions in `cl.exe` versions ≥v19.41. SDL currently needs such conversions in:
* MainCallbackRateHintChanged()
* SDL_PrintFloat()
* WIN_ApplyWindowProgress()
This seems enough to justify implementing this function rather than trying to work around it, [as it was done in sdl12-compat](https://github.com/libsdl-org/sdl12-compat/issues/352).
This [implementation from ReactOS](https://git.reactos.org/?p=reactos.git;a=commitdiff;h=f637e6b809adb5e0ae420ef4f80c73b19172a2e7) passes the stdlib testautomation, and also matches the behavior of Microsoft's 64-bit libc for the currently implementation-defined case of calling SDL_PrintFloat() with values >`SDL_MAX_UINT64`.
That …
> Fix SDL_uclibc for 32-bit Windows on current Visual Studio

- src/core/unix/SDL_fribidi.c
- src/video/x11/SDL_x11toolkit.c
- src/video/x11/SDL_x11toolkit.h
The `.editorconfig` is configured to make editors that support it clean up trailing whitespace when saving, which means that whenever a contributor whose text editor *doesn't* support `.editorconfig` makes a contribution that adds trailing whitespace, we'll get well-intentioned whitespace changes mixed into unrelated commits that happen to touch those same files later. We can avoid this by keeping trailing whitespace out of the tree.
> X11: clean up trailing whitespace

- src/video/x11/SDL_x11toolkit.c
Adds even more CRTC checks to X11TK
Reference issue: https://github.com/libsdl-org/SDL/issues/14140.
> X11TK: Add more checks to the Xrandr code path to avoid errors

- src/dialog/unix/SDL_zenitydialog.c
- src/dialog/unix/SDL_zenitymessagebox.c
- src/dialog/unix/SDL_zenitymessagebox.h
Reference issue: https://github.com/libsdl-org/SDL/issues/14140
~This doesn't detect pressed button id, limited to the 'OK' button,~
~and potentially does not use (correct) user-provided button label.~
~However, current distros all provide new-enough zenity versions,~
~so the issues mentioned above are actually non-issues.~
> zenity dialog: make sure that --modal --attach switches are supported. 

- src/video/SDL_video.c
Currently function to create Metal view will automatically convert window to Metal one. Made the behaviour the same for Vulkan.
Also fixed a bug in SDL_ReconfigureWindowInternal. More information in the issue linked below.
https://github.com/libsdl-org/SDL/issues/14142
> Always convert window to Vulkan window on SDL_Vulkan_CreateSurface

- src/render/direct3d/SDL_render_d3d.c
Fix build with `SDL_LEAN_AND_MEAN`.
Avoid checking `texturedata->yuv` when `SDL_HAVE_YUV` is not defined.
The condition in question checks whether `texturedata->yuv` is not a null pointer.
Thus, when SDL is compiled without YUV support, this pointer does not exist, allowing us to treat it as a null pointer by eliminating this branch.
https://github.com/libsdl-org/SDL/issues/14151
> Fixed building with SDL_LEAN_AND_MEAN

- src/render/opengl/SDL_render_gl.c
This also adjusts the priority of available pixel formats, since `SDL_PIXELFORMAT_RGBA32` is available in all versions of OpenGL while the others were added later on.
> Use the correct pixel formats for OpenGL on big endian

- include/SDL3/SDL_iostream.h
- src/io/SDL_iostream.c
- test/testautomation_iostream.c
The `"x"` mode for `fopen()` (open file only if it doesn't exist) used to be a glibc-exclusive extension, but was later standardized in C11, and is now also implemented as part of every other widely-used libc:
* [musl](https://git.musl-libc.org/cgit/musl/tree/src/stdio/__fmodeflags.c?id=0ccaf0572e9cccda2cced0f7ee659af4c1c6679a) 
* [Android Bionic / OpenBSD](https://android.googlesource.com/platform/bionic/+/731631f300090436d7f5df80d50b6275c8c60a93/libc/upstream-openbsd/lib/libc/stdio/flags.c#86)
* [Apple / FreeBSD](https://github.com/apple-oss-distributions/Libc/blob/63976b830a836a22649b806fe62e8614fe3e5555/stdio/FreeBSD/flags.c#L91-L92)
As a result, `"x"` has already been working on all our automatically tested platforms that implement `SDL_IOFromFile()` via `fopen()`. So all we'd be …
> iostream: Properly support the "x" mode for SDL_IOFromFile()

- examples/asyncio/01-load-bitmaps/load-bitmaps.c
- examples/audio/01-simple-playback/simple-playback.c
- examples/audio/02-simple-playback-callback/simple-playback-callback.c
- examples/audio/03-load-wav/load-wav.c
- examples/audio/04-multiple-streams/multiple-streams.c
- examples/audio/05-planar-data/planar-data.c
- examples/camera/01-read-and-draw/read-and-draw.c
- examples/demo/01-snake/snake.c
- examples/demo/02-woodeneye-008/woodeneye-008.c
- examples/input/02-joystick-events/joystick-events.c
- examples/input/04-gamepad-events/gamepad-events.c
- examples/misc/01-power/power.c
- examples/misc/02-clipboard/clipboard.c
- examples/renderer/01-clear/clear.c
- examples/renderer/02-primitives/primitives.c
- examples/renderer/03-lines/lines.c
- examples/renderer/04-points/points.c
- examples/renderer/05-rectangles/rectangles.c
- examples/renderer/06-textures/textures.c
- examples/renderer/07-streaming-textures/streaming-textures.c
- examples/renderer/08-rotating-textures/rotating-textures.c
- examples/renderer/09-scaling-textures/scaling-textures.c
- examples/renderer/10-geometry/geometry.c
- examples/renderer/11-color-mods/color-mods.c
- examples/renderer/14-viewport/viewport.c
- examples/renderer/15-cliprect/cliprect.c
- examples/renderer/17-read-pixels/read-pixels.c
- examples/renderer/18-debug-text/debug-text.c
- examples/renderer/19-affine-textures/affine-textures.c
- examples/template.c
This also ensures that the examples work on fullscreen-only platforms like the 3DS, where the window size will be equal to the display mode size rather than using the provided size.
Two examples haven't been adapted yet:
- `demo-infinite-monkeys` (there is some code to handle adapting to different screen sizes, but it currently deletes the previous lines of text when a screen change occurs)
- `pen-drawing-lines` (I don't have the hardware to test it with)
> Support resizable windows with most examples

- src/render/metal/SDL_render_metal.m
This PR fixes compiling the Metal renderer on macOS with SDL_LEAN_AND_MEAN defined (meaning SDL_HAVE_YUV is 0). There was a curly bracket on the wrong side of a preprocessor conditional causing compiler errors.
> Fix compiling Metal renderer with SDL_LEAN_AND_MEAN
