include/SDL_stdinc.h, src/audio/SDL_wave.c, src/test/SDL_test_common.c, src/video/SDL_bmp.c, src/video/dummy/SDL_nullframebuffer.c
The DJGPP compiler emits many warnings for conflicts between print
format specifiers and argument types. To fix the warnings, I added
`SDL_PRIx32` macros for use with `Sint32` and `Uint32` types. The macros
alias those found in <inttypes.h> or fallback to a reasonable default.
As an alternative, print arguments could be cast to plain old integers.
I opted slightly for the current solution as it felt more technically correct,
despite making the format strings more verbose.
This is a follow-up to commit c760c02.
=> Fix format string warnings for width-based integers

src/video/wayland/SDL_waylandwindow.c
This is a Git-based replacement for a patch in #3739.
Not much to see here, just some trailing whitespace in one of the Wayland files.
=> wayland: Minor whitespace fix

.gitignore
- ignore the `.vs` folder generated by VS2019
=> ignore vs2019 meta folder

INSTALL.txt, TODO.txt, docs/README-git.md, docs/README-platforms.md, docs/README.md, test/testautomation_audio.c, test/testautomation_clipboard.c, test/testautomation_events.c, test/testautomation_keyboard.c, test/testautomation_main.c, test/testautomation_mouse.c, test/testautomation_pixels.c, test/testautomation_platform.c, test/testautomation_rect.c, test/testautomation_render.c, test/testautomation_rwops.c, test/testautomation_video.c
spawned by issue - https://github.com/libsdl-org/SDL/issues/4064
- Updated url references to the shiny new `libsdl-org/SDL/wiki`
- Cleaned up the `moin.fcg` and `moin.cgi` references
- Updated urls from `http:` to `https:`
=> Update wiki.libsdl.org urls to libsdl-org/SDL/wiki

configure.ac
The "-e" parameter to the echo utility is not recognised on some shells as it is non-standard. This PR replaces usage of "echo -en" with "printf" which is standardized.
Fixes summary output on FreeBSD.
=> Replace "echo -en" with "printf" in autoconf script

CMakeLists.txt
I have had some success applying this change in my fork and would like to propose it for merge.
The current CMake setup in SDL already allows including SDL as a dependency of other CMake projects not only with `find_package()` but also using the [`FetchContent()`](https://cmake.org/cmake/help/latest/module/FetchContent.html) API and [`add_subdirectory()`](https://cmake.org/cmake/help/latest/command/add_subdirectory.html), both of which I understand are known as "sub projects" and are distinct from the `find_package()` method (which is used for finding _installed_ libraries).
With the current setup, there is a discrepancy between the targets SDL exports depending on what method is used to acquire SDL:
- `find_package()` exports targets in the `SDL2::` namespace such as `SDL2::SDL2`, …
=> CMake: Support uniform link target names regardless if find_package() or sub-project is used

src/stdlib/SDL_stdlib.c
`SDL_isxdigit()` should only accept A-Fa-f, not A-Za-z (it shouldn't use `SDL_isalpha()`).
`SDL_ispunct()` shouldn't accept spaces (it should use `SDL_isgraph()` instead).
=> Fix errors with fallback impls of SDL_isxdigit() and SDL_ispunct()

Xcode/SDL/SDL.xcodeproj/project.pbxproj
SDL_mfijoystick.m requires ARC, but the Xcode project's macOS targets weren't compiling the file with ARC enabled.
=> macOS: Fix Xcode project when deployment target is > 10.7

src/core/freebsd/SDL_evdev_kbd_freebsd.c
Enable it again after quitting evdev input.
=> Disable FreeBSD console mouse when initializing evdev input

src/render/metal/SDL_render_metal.m, src/test/SDL_test_common.c, src/video/SDL_video.c
As per https://github.com/libsdl-org/SDL/issues/3991#issuecomment-778849521 , SDL_Render is failing to choose the Metal backend when the window isn't explicitly created with `SDL_WINDOW_METAL`. I believe the most idiomatic fix is to make windows created without an explicit backend allow creation of metal views on macOS/iOS – SDL already behaves that way with OpenGL. This also avoids what was happening in the original bug report with the window getting destroyed and recreated.
This wasn't a problem until SDL 2.0.14, since SDL 2.0.12 had metal support without the `SDL_WINDOW_METAL` window flag (the flag only adds validation / error checking, it doesn't cause any sort of Metal view to be created on its own - `SDL_Metal_CreateView` is what does that).
=> mac/iOS: allow Metal in windows created without an explicit backend

docs/README-kmsbsd.md
This PR adds documentation for KMSDRM video backend on *BSDs. People are welcome to give suggestions to this PR.
Fixes #4086.
=> Add documentation for KMSDRM on *BSDs

src/cpuinfo/SDL_cpuinfo.c, test/testplatform.c
This PR makes the following changes:
- `readProcAuxvForNeon` has been changed to use `Elf32_auxv_t`, the SIMD and SDL1 detection code. It is also only built on 32--bit ARM, since it was unused with AArch64.
- The non-ARM check is prioritized over the OpenBSD and `elf_aux_info` checks.
- SDL_HasARMSIMD is now tested in `testplatform`.
Fixes #4095.
=> Minor improvements for CPU detection on ARM

src/audio/pulseaudio/SDL_pulseaudio.c
PC config
* Debian Buster
* Pulseaudio enabled
I setup a recording with the following params :
```
SDL_AudioSpec want;
SDL_zero(want);
want.freq = 48000;
want.format = AUDIO_S16;
want.channels = 2;
want.samples = 960;
```
I expect to get a 3840 bytes buffer every 20 ms. Instead, sometimes I get a bulk of 3840 bytes buffer every ~2 seconds.
The behavior can change, depending of the platform. Sometime the first record works, and then the next one fails. Sometimes it never works.
fragsize wasn't initialized, and it is used for recording according to pulseaudio description.
If the value is 0 or -1, pulseaudio configures it itself (with a different strategy). But sometimes we can get a random (and large) value that makes pulseaudio give us large sample at a very low frequency.
* …
=> pulseaudio: Initialize fragsize to fix mic recording

src/audio/pulseaudio/SDL_pulseaudio.c, src/audio/pulseaudio/SDL_pulseaudio.h
This avoids copying samples into an additional mixing buffer in the common case by getting a pointer to pulseaudio memory with pa_stream_begin_write(). In case this fails or returns a too small memory area, we fall back to the old behavior. Tested with a variety of apps and the zerocopy path is pretty much always hit.
=> pulseaudio: Add "zerocopy" playback path

src/video/cocoa/SDL_cocoaevents.m
On MacOS, if an application is not already running and it is opened via a custom URL/Protocol, the SDL_DROPFILE event is not invoked as expected.
If the application is already running, SDL_DROPFILE is invoked as expected. 
The solution is to set the event handler earlier on, I've moved it to init.
=> Fix URL Event Handler on MacOS

src/joystick/hidapi/SDL_hidapijoystick.c, src/joystick/linux/SDL_sysjoystick.c
This improves SDL's ability to detect HIDAPI joystick hotplug in a
container environment because we cannot reliably receive events from
udev in a container.
Previous related issues (not for HIDAPI) https://github.com/libsdl-org/SDL/issues/3868 and https://github.com/libsdl-org/SDL/issues/3889
Fixes: https://github.com/libsdl-org/SDL/issues/4006
/cc @smcv
=> Add HIDAPI enumeration using inotify

src/joystick/hidapi/SDL_hidapijoystick.c
The recent inotify/HIDAPI pull request (#4098) broke building when inotify is not available, as <unistd.h> is not included properly.
This is a pretty niche case (I can't imagine there being any systems without inotify), but it does cause a compile error due to missing definitions of acces(), close(), and F_OK:
```
…/SDL/src/joystick/hidapi/SDL_hidapijoystick.c: In function 'HIDAPI_JoystickInit':
…/SDL/src/joystick/hidapi/SDL_hidapijoystick.c:743:20: warning: implicit declaration of function 'access' [-Wimplicit-function-declaration]
743 |         } else if (access("/.flatpak-info", F_OK) == 0
|                    ^~~~~~
…/SDL/src/joystick/hidapi/SDL_hidapijoystick.c:743:45: error: 'F_OK' undeclared (first use in this function)
743 |         } else if (access("/.flatpak-info", F_OK) == 0
| …
```
=> Fix build when inotify not available (broken by inotify/HIDAPI changes)

src/video/kmsdrm/SDL_kmsdrmvulkan.c
I have implemented compatible physical device selection instead of basing the selection on the wrong variable.
This is a fix for issue:
https://github.com/libsdl-org/SDL/issues/3997
=> [KMSDRM] Implement better physical device selection. Fixes issue #3997: "Vulkan KMS/DRM doesn’t work on Pi4"

.github/workflows/gh-pages.yml, .github/workflows/main.yml, mkdocs.yml
Added github actions for building sdl for the three major systems (linux, windows and osx)
the build currently fails for windows. There is some unresolved symbol - it already works for linux and macosx.
```
SDL_xinputhaptic.c
Generating Code...
Creating library D:/a/SDL/SDL/build/Debug/SDL2d.lib and object D:/a/SDL/SDL/build/Debug/SDL2d.exp
SDL_hidapijoystick.obj : error LNK2019: unresolved external symbol close referenced in function HIDAPI_IsEquivalentToDevice [D:\a\SDL\SDL\build\SDL2.vcxproj]
D:\a\SDL\SDL\build\Debug\SDL2d.dll : fatal error LNK1120: 1 unresolved externals [D:\a\SDL\SDL\build\SDL2.vcxproj]
Building Custom Rule D:/a/SDL/SDL/CMakeLists.txt
SDL.c
```
I'm using cmake for the build at the moment. If there is interest in e.g. configure && make let me know.
Also included is a …
=> CI: added github actions for build and for publishing the docs

src/sensor/windows/SDL_windowssensor.c
=> Fix memory leak in ConnectSensor

src/video/kmsdrm/SDL_kmsdrmvulkan.c
Variable `device_props` is never freed.
=> Fix memory leak in KMSDRM_Vulkan_CreateSurface

src/joystick/hidapi/SDL_hidapijoystick.c
This fix implicit declaration of close and unused variable warning.
=> Guard Inotify stuff with macro

docs/README-linux.md
This fixes the formatting, and adds `pkg-config`, `libjack-dev`, `libdrm-dev` and `libgbm-dev` to the list of packages.
=> Update the Linux build instructions

src/video/SDL_blit.h
pixman ARM blitters are 32 bit only
Closes:  https://github.com/libsdl-org/SDL/issues/4095
=> disable pixman ARM blitters for __aarch64__ | _M_ARM64

src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandevents_c.h, src/video/wayland/SDL_waylandmouse.c
Unlike Mutter and Sway, KWin actually checks the serial passed in
wl_pointer_set_cursor(). The serial provided is supposed to be the
serial of the pointer enter event, but we were always passing 0.
This caused KWin to drop our requests to hide the cursor.
Thanks to the KDE folks for spotting this in my debug logs
https://bugs.kde.org/show_bug.cgi?id=433540
Fixes #3576
=> Wayland: Fix mouse pointer hiding on Plasma Wayland

include/SDL_hints.h, src/video/kmsdrm/SDL_kmsdrmvideo.c
In some cases, it can be useful to have the KMSDRM backend even if it cannot
be used for rendering. An app may want to use SDL for input processing while
using another rendering API (such as an MMAL overlay on Raspberry Pi) or
using its own code to render to DRM overlays that SDL doesn't support.
This also moves the check for DRM master to an earlier point where we can fail
initialization of the backend, rather than allowing the backend to initialize
then failing the creation of a window later.
=> KMSDRM: Add hint to enable the backend without DRM master

src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
This is a Git-based replacement for #4047.
As a refresher: Wayland desktops currently have no way of knowing that our window is fixed-size; while we do ignore resize events in our callbacks, the desktop will still provide resize UI and a maximize button that can mess with the window in unintended ways. This patch is meant to address this, though on KDE the fix doesn't work until you toggle the border. If anyone familiar with KDE's implementation of server-side decorations we could use some help with this one...
=> [Wayland] Explicitly set min/max size for xdg-shell

src/audio/pipewire/SDL_pipewire.c
Some minor cleanups and a small addition to the Pipewire backend:
- Add some missing static qualifiers
- Constify the buffer size calculation and add a note warning against increasing the upper limit as doing so can cause a buffer overflow
- Add the application name to the stream properties
=> Minor Pipewire Cleanups

src/cpuinfo/SDL_cpuinfo.c
The clang-cl compiler defines `__llvm__` but not `__GNUC__`. The `__cpuid` intrinsic doesn't seem to exist with clang-cl, so the code won't link properly. The `__GNUC__` versions of these functions will work properly on Windows with clang-cl.
Fixes #4144
=> Update cpuid code for clang-cl

include/SDL_audio.h, src/audio/SDL_audio.c, src/audio/SDL_audiodev.c, src/audio/SDL_sysaudio.h, src/audio/alsa/SDL_alsa_audio.c, src/audio/coreaudio/SDL_coreaudio.m, src/audio/directsound/SDL_directsound.c, src/audio/disk/SDL_diskaudio.c, src/audio/os2/SDL_os2audio.c, src/audio/pipewire/SDL_pipewire.c, src/audio/pulseaudio/SDL_pulseaudio.c, src/audio/qsa/SDL_qsa_audio.c, src/audio/wasapi/SDL_wasapi.c, src/audio/wasapi/SDL_wasapi.h, src/audio/wasapi/SDL_wasapi_win32.c, src/audio/wasapi/SDL_wasapi_winrt.cpp, src/audio/winmm/SDL_winmm.c, src/dynapi/SDL_dynapi_overrides.h, src/dynapi/SDL_dynapi_procs.h
This is a Git version of the patch found in #2911.
Life-or-Death Backends:
Pretty Important Backends:
Bonus Points:
=> Add SDL_GetAudioDeviceSpec

src/video/vita/SDL_vitavideo.c
This fixes incorrect typecasting from `char*` to `SceWChar16*`
=> Fix typecasting in vita port IME

src/video/SDL_blit_N.c
Add a trivial blitter to convert from RGB555 to ARGB1555, 
and also working from BGR555 to ABGR1555
Fixed bug #3727
=> Fixed bug 3727 - Blit from RGB555 to ARGB1555

src/audio/pipewire/SDL_pipewire.c
Removes the node nickname (e.g. Intel HDA: ... or NVidia HDA: ...) from sink/source nodes as it doesn't provide any meaningful information and names now match those used in Pulseaudio, so any stored configuration data will be compatible between the two audio backends.
=> Pipewire: Remove the node nickname from the beginning of sink/source names

src/audio/netbsd/SDL_netbsdaudio.c
A user reported that the mpv video player hangs after attempting to set an unsupported number of channels with the SDL audio output, because it thinks it's successfully opened the device. This makes the failure graceful.
I also wonder whether we should force the format to stereo if this fails - does SDL handle that gracefully?
=> netbsdaudio: Handle ioctls failing

src/stdlib/SDL_iconv.c
This PR fixes compilation with iconv on FreeBSD and makes SDL2 always prefer the system's iconv implementation over the libiconv one.
=> Fix compilation with iconv on FreeBSD

cmake/sdlchecks.cmake
This PR fixes CMake script on FreeBSD.
Fixes #4133.
=> Fix CMake script on FreeBSD

src/video/SDL_egl.c
This PR makes SDL2 load libOpenGL.so.1 if libGL.so.1 is not found when loading OpenGL library.
Fixes #4158.
=> Load libOpenGL.so.1 if libGL.so.1 is not found

src/video/SDL_egl.c
Fixes: https://github.com/libsdl-org/SDL/issues/4158
faba1be07dc57ced6dc1fb929b029253dde5bef4 has a typo.
With this patch applied I confirm it to be working in a libX11-less setup.
=> Set ALT_OGL to libOpenGL.so.0 instead of libOpenGL.so.1

include/SDL_cpuinfo.h
The llvm-mingw project includes cross-compilers targeting ARM: https://github.com/mstorsjo/llvm-mingw/releases
Currently, compilation fails with this configuration, because neon features are used as long as __ARM_NEON is defined, but arm_neon.h was not included. It's normally included by SDL_cpuinfo.h, so it seems appropriate to add it there.
=> Include arm_neon.h in mingw targeting ARM Windows.

src/render/SDL_render.c
I noticed that this is only a half-solution and harmful too, because it causes a window recreation in `GLES2_CreateRenderer()` caused by the fact that `SDL_GL_ResetAttributes()` in `SDL_video.c` is hardcoded to set full OPENGL `profile_mask, major, minor` parameters instead of GLES2 ones.
That's just wrong, and could theorically be fixed easily: but modifying `SDL_GL_ResetAttributes()` to make it set the right GLES `profile_mask, major, minor` parameters, full OPENGL programs don't work anymore becauses (I suspect) of the MANY hardcoded codepaths in  `SDL_video.c`.
So, unless `SDL_video.c` (and maybe other places where things are hardcoded via `#if SDL_VIDEO_OPENGL` directives) has a major rewrite, enforcing an opengles2 renderer when KMSDRM is being used is not possible without damaging …
=> Undo SDL_CreateRenderer() modifications aimed at create opengles2 when KMSDRM is in use.

configure.ac
This simply modifies configure.ac (related to the classic "make" build system) so when the resulting configure script is run, it reports differentiated GLX and GLVND OpenGL implementations.
For example: without this commit, "opengl" will be reported twice if both GLX and GLVND OpenGL implementations are present, which is confusing and not nice.
With this, "opengl(glx)" and "opengl(glvnd)" would be reported.
=> Report differentiated glx and glvnd OpenGL implementations.

src/events/SDL_keyboard.c, src/stdlib/SDL_iconv.c
I just happened to observe that the UTF-8 hander function in `SDL_keyboard.c` happens to be handling invalid UTF-8 as valid UTF-8. The function tries to interpret extra bytes in the source string, that are normally considered illegal UTF-8 encodings and out of the specs for the encoding system. Also fixed the same issue, on another file.
Ref: https://en.wikipedia.org/wiki/UTF-8 
For the UTF-8 encoding specs
=> Fix invalid UTF-8 handling of extra bytes

test/configure.ac
**PREVIOUS  ISSUE**
Many of the tests in /tests wouldn't link if only the modern full OpenGL implementation (GLVND) is present on the system. This commit fixes that.
**WHAT THIS COMMIT DOES**
What this commit does is enable the `libOpenGL.so` detection in `tests/configure.ac`.
So if `libOpenGL.so` is present test programs will be linked against `-lOpenGL` instead of `-lGL`.
-If both `libGL.so` and `libOpenGL.so` are present, `libOpenGL.so` is preferred as it's a modern and vendor-neutral implementation, vs the old and X11-bound `libGL.so`
-If only `libGL.so` is present, libGL.so will be used.
-If only `libOpenGL.so` is present it will be used.
=> Fix tests configuration and building when only GLVND full OpenGL implementation is present

src/video/kmsdrm/SDL_kmsdrmopengles.c, src/video/kmsdrm/SDL_kmsdrmvideo.c, src/video/kmsdrm/SDL_kmsdrmvideo.h
Moved the `gbm_init` flag from `dispdata` (the display driverdata) to `viddata` (the general video driverdata).
Having `gbm_init` flag in dispdata means that each display has it's own copy of `gbm_init`, **which makes NO SENSE AT ALL** because, even if he have several displays, `KMSDRM_GBMInit()` must never be run more than 1 time.
Before this change, KMSDRM_GBMInit() was being run everytime a new window was created on a different display, which in turn took the FD master from window 1 to window 2, and thus window 1 wouldn't be able to display anything.
=> Make the gbm_init flag a viddata member to avoid GBM re-init when several displays are connected.

src/video/kmsdrm/SDL_kmsdrmmouse.c, src/video/kmsdrm/SDL_kmsdrmvideo.c
I did some adjustments in KMSDRM_CreateWindow() it's error handling now makes sense: I was tired of seeing uninformative segfaults when something went wrong, so I decided to put an end to that.
Now, KMSDRM_CreateWindow() returns an error value as expected when something goes wrong, and doesn't call SDL_DestroyWindow() by itself, because that's SDL_CreateWindow()'s job when KMSDRM_CreateWindow() returns an error code.
Also, the condition for cursor initialization on a display is moved from SDL_kmsdrmmouse.c to KMSDRM_CreateWindow() because cursor creation is done on a per-display basis.
Before this, SDL would do an ugly segfault when KMSDRM window creation failed. Now, it lands gracefully with a proper error on the console.
=> [KMSDRM] Better error handling: no more segfaults on window creation failure.

src/video/kmsdrm/SDL_kmsdrmmouse.c, src/video/kmsdrm/SDL_kmsdrmvideo.c, src/video/kmsdrm/SDL_kmsdrmvideo.h
Made some adjustments in the video and mouse units to improve how default cursor is 
created and managed. It was a little confusing.
Also, since SDL_SetMouseFocus() seems to cause a KMSDRM_ShowMouse() call on it's own, there's no need for me to manually re-show the cursor of a display when I create a new window, so I removed the code that did that.
I had accidentally disabled default cursor creation and display because of the confusing logic I was using.
This fixes that, too.
=> [KMSDRM] Improve cursor management.

src/video/kmsdrm/SDL_kmsdrmvideo.c
Deference the windata pointer *after* checking that it's non-NULL.
Fix a segfault. Happens for instance with PPSSPP.
=> [KMSDRM] Fix segmentation fault

src/thread/pthread/SDL_systhread.c
Drop include of `SDL_platform.h` as `SDL_plaform.h` is already included by `SDL_internal.h` -> `SDL_config.h` -> `SDL_platform.h`
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> src/thread/pthread/SDL_systhread.c: drop include of SDL_platform.h

src/video/kmsdrm/SDL_kmsdrmvideo.c
I did a small adjustment in KMSDRM_GetClosestDisplayMode() so the video mode is searched on the right display, instead of always being searched on the display with index 0 (this was accidentally hardcoded from the old days when KMSDRM backend wouldn't support more than 1 connected display).
Previously, dual display setups wouldn't work with KMSDRM because searching for a video mode on the wrong display is not a good idea and leads to odd results.
With this small fix it's possible to create two windows, one in each display. Nice!
=> Ask for videomode on the correct display when creating a window

src/video/wayland/SDL_waylandmessagebox.c
A copypasting mishap caused a block to go not-updated... without this block the output_len never gets assigned, meaning button string comparisons will never happen.
I also added --no-wrap to work around a Zenity issue. Now dialogs look a lot better!
Part of #4227
=> Wayland MessageBox fixes

src/video/kmsdrm/SDL_kmsdrmvideo.c, src/video/kmsdrm/SDL_kmsdrmvulkan.c
Made some small changes in SDL_kmsdrmvulkan.c so we chose an exact video mode if available (instead of looking for a small-enough one: what was I thinking?), or create a new mode if it's not possible to find a matching mode.
GZDoom would only display a part of the screen before this (because we were simply chosing a small enough video mode, instead of a matching one).
This is fixed now.
=> [KMSDRM] For Vulkan, use a mode with the same exact size as the window, if possible, or create a new one.

src/audio/pipewire/SDL_pipewire.c, src/audio/pipewire/SDL_pipewire.h
A few Pipewire fixes and cleanups, including a fix for a race condition.
Since Pipewire starts it's own processing threads, we can wind up in the processing callbacks before all of the members of SDL_AudioDevice (callbackspec, work_buffer and stream) are allocated/initialized, as they aren't initialized until after the call to the driver's OpenDevice() function returns. We don't want to touch any of these variables in the callbacks until the device state is set to unpaused, which can only happen once initialization is fully complete.
Other than that, some redundant locks were removed and stream creation now blocks instead of spinning until the stream state is either ready or failed, as creating streams can sometimes take a bit of time and busy waiting for many milliseconds isn't ideal.
=> Audio: Pipewire cleanups and fixes

test/testmessage.c
On Wayland -- or at least on some Wayland implementations -- windows aren't shown until something has been rendered into them. For the 'testmessage' test program, this means that the final messagebox (a modal one) is blocking an "invisible window", which can then be difficult to close.
By creating a renderer and presenting once, the window is properly displayed, and the test behaves as it does under X11  including XWayland).
The zenity based implementation of ``SDL_ShowMessageBox()`` added in #4227 is only used if either XWayland isn't available or a Wayland-using window handle is passed in (for a modal dialog). Otherwise, the X11 implementation has priority. This probably makes sense — since the zenity implementation is less complete — but it means that, if XWayland is present, only the …
=> testmessage: Create a renderer for window display on Wayland

src/core/linux/SDL_ibus.c
As the title says. On Wayland, attempts to connect to `unix` handles instead of `unix-wayland` will be refused, meaning IME support won't work at all. This actually affects XWayland as well!
Spun off of #4246.
=> linux: Fix ibus support on Wayland/XWayland

include/SDL_thread.h, src/dynapi/SDL_dynapi_overrides.h, src/dynapi/SDL_dynapi_procs.h, src/thread/SDL_thread.c
commit 6b8f933589aa3925978a23e77a305a7e89c6ae4a
Author: Xing Ji <jixingcn@gmail.com>
Date:   Wed Mar 24 22:31:29 2021 +0800
update the dynapi by `gendynapi.pl`
commit ebd1790c19983b652713f40ab1e139e485e1a2b7
Author: Xing Ji <jixingcn@gmail.com>
Date:   Wed Mar 24 22:17:48 2021 +0800
revert the change in src/dynapi
commit 734b5f85c1613070081e39238e84198128971b53
Merge: 5a56e5a8 5ac6bd54
Author: Xing Ji <jixingcn@gmail.com>
Date:   Wed Mar 24 22:14:40 2021 +0800
Merge remote-tracking branch 'libsdl/main' into jixingcn
commit 5a56e5a8227d9cff6b497b681c618a76bec1cae1
Author: Xing Ji <jixingcn@gmail.com>
Date:   Mon Mar 22 23:55:10 2021 +0800
Fix #3596, can call the `SDL_TLSCleanup` to cleanup the TLS data when closing the application
Allow calling `SDL_TLSCleanup` explicitly by the …
=> Fix #3596, call `SDL_TLSCleanup` to clean up the TLS memory when closing the application

src/audio/wasapi/SDL_wasapi.c
When I implemented GetAudioDeviceSpec I reused a format conversion that already existed, and as part of moving it to a standalone function I added an assert, worried that I would run into some critical formats that would need to be added for the new feature. It turns out I was half right, there is a common format used on Windows for sound devices, unfortunately the format is 24-bit PCM.
This assert ended up just being annoying more than anything, and we documented in the API that 0 for format means the format wasn't recognized, so just forget I added this...
Fixes #4239, #4223
=> wasapi: Remove assert added by 67e8522d

src/audio/SDL_audio.c
While we should normally expect _something_ from the stream based on the
AudioStreamAvailable check, it's possible for a device change to flush the
stream at an inconvenient time, causing this function to return 0.
Thing is, this is harmless. Either data will be NULL and the result won't matter
anyway, or the data buffer will be zeroed out and the output will just be
silence for the brief moment that the device change is occurring. Both scenarios
work themselves out, and testing on Windows shows that this behavior is safe.
Fixes #4221
=> audio: Allow AudioStreamGet to return 0 in RunAudio.

src/video/kmsdrm/SDL_kmsdrmvideo.c, src/video/kmsdrm/SDL_kmsdrmvulkan.c
Made some small adjustments to KMSDRM Vulkan surface creation code.
-display_mode is already a pointer, so no need to use a pointer-to-pointer here.
-Get the display index from the display being used by the window, as we do in normal KMSDRM/GLES/OpenGL operation to support multiple displays, instead of always using display index 0.
-Some spacing was corrected here and there.
I don't think this fixes any issue, but it's aimed to improve the quality of the code a bit.
=> [KMSDRM] Minor Vulkan code adjustments regarding pointers and display index.

src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandkeyboard.c, src/video/wayland/SDL_waylandkeyboard.h, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandvideo.h
Note that this is purely to make it possible to enter text that requires
composition - for example, before this commit Kanji input didn't work at all.
~XWayland does not appear to support our X implementation~, so this is critical
to have implemented in some form. EDIT: #4248 fixes XWayland.
The big problem this still has is that we need the window position, and this is
still not implemented. Once we have this information we can do the equivalent
of XTranslateCoordinates to put the rectangle where we want it.
=> wayland: Initial text input and IME support

src/video/cocoa/SDL_cocoaopengl.m
I just moved the patch I provided on bugzilla to here, the issue explains why I fixed it like this.
Whether setWindow also should be using an async dispatch is up to discussion but I never got any feedback on that.
#3680
=> Use dispatch_async for -[NSOpenGLContext update]

src/video/wayland/SDL_waylandmessagebox.c
Check `messageboxdata->buttons[i].text` for NULL before passing it to `strcmp`.
It is checked in a previous loop (line 82), it should be checked here too.
=> NULL passed to strcmp in Wayland_ShowMessageBox

src/video/windows/SDL_windowsvideo.h
According to Microsoft's documentation for [`MONITOR_DPI_TYPE`](https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/ne-shellscalingapi-monitor_dpi_type), it is introduced in Windows 8.1 and defined in `ShellScalingApi.h`, which is never automatically included by `Windows.h`. However, there are no references to `ShellScalingApi.h` anywhere in the SDL codebase.
In `src/windows/video/SDL_windowsvideo.h` there is a copypasted definition for `MONITOR_DPI_TYPE` for when the Windows SDK version is less than Windows 8.1 (`#if WINVER < 0x0603`). However, there is no accompanying `#else` clause to `#include <ShellScalingApi.h>` when the header would be available. Thus, when compiling against a Windows SDK version of 8.1 or above, the code fails to compile due to the missing …
=> Include ShellScalingApi.h when targeting Windows 8.1+ SDKs

src/video/winrt/SDL_winrtvideo.cpp
Rename locally-defined Interface ID symbols to avoid conflict with
locally linked dxgi library. Prefixed with `SDL_` to match with
other references in render_d3d11 or wasapi.
=> WinRT: Rename Interface ID symbols

src/video/wayland/SDL_waylandwindow.c
Fixes #4281.
Continuing off my work from #4065, it looks like Wayland took even _more_ notes from X and made the min/max an issue when calling the set_fullscreen functions, causing the display server to clamp the window and resize it to something really weird and wrong. The solution was to fold _all_ of the min/max work into a new function and do a full commit every single time we change the dimensions in some way. It turns out it's cleaner like this anyway!
=> wayland: Fix toggling fullscreen with fixed-size windows

src/video/windows/SDL_windowsevents.c
On windows, when toggling the state of RelativeMode rapidly, there is a high chance that `SDL_WINDOWEVENT_ENTER` / `SDL_WINDOWEVENT_LEAVE` events will stop firing indefinitely.
This aims to resolve that shortcoming by ensuring mouse focus state is correctly updated via `WM_MOUSELEAVE` events arriving via the windows event hook.
I have tested this using the following code (built on top of my test project for reporting https://github.com/libsdl-org/SDL/issues/4165. Apologies for writing it in c#, my development environment is not set up completely for c++ development.
```csharp
using System;
using System.Diagnostics;
using SDL2;
namespace SDL2IsolatedRelativeModeTest
{
class Program
{
static bool relative;
static void Main(string[] args)
{
SDL.SDL_Init(SDL.SDL_INIT_VIDEO); …
```
=> Fix race condition that can lead to ENTER/LEAVE window events never firing

CMakeLists.txt, include/SDL_cpuinfo.h, include/SDL_endian.h
This should be it. Utility polyfill is provided, removed the no-longer-needed conditionals. The linkage warning is also silenced.
=> Support for intrinsics in MSW + Clang scenario.

CMakeLists.txt
fixes #4292 
Fix UWP build with stock CMakeLists.txt:
1. Remove `/NODEFAULTLIB` for `WINDOWS_STORE` platform since we need to link against C++ runtime anyway
2. Move `-nodefaultlib:vccorlib$<$<CONFIG:Debug>:d>` and followings to `EXTRA_LIBS` to align with other platforms
3. Use WinRT specific locale implementation since Win32 implementation uses API that is not available on WinRT
Stock CMakeLists.txt cannot build DLL when targeting UWP #4292 .
=> cmake: Fix UWP DLL build by removing /NODEFAULTLIB

src/video/wayland/SDL_waylandclipboard.c, src/video/wayland/SDL_waylanddatamanager.c, src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandevents_c.h, src/video/wayland/SDL_waylandvideo.c
This is mostly a preparation patchset for fixing Wayland clipboard support. 
For reasons I don't fully understand, this fixes #3724. I could see it passing 2 '\0' chars before, and now it doesn't? Valgrind revealed no sign of uninitialized memory before or after the patchset.
EDIT: Figured out what Wayland's deal was, now also fixes #3725.
=> Various fixes for Wayland clipboard support

src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandsym.h
Wayland keyboard layouts are passed via the `group` parameter in `keyboard_handle_modifiers`, and map to `xkb_layout_index_t` in xkbcommon. This patch supports both initial and live-updated keyboard layouts. The translation in Wayland_keymap_iter is mostly ripped off the X11 backend.
Fixes #3471, fixes #4142. Partially addresses #4187, X11 still doesn't support live updates AFAIK.
=> wayland: Set the keymap in keyboard_handle_modifiers

src/video/kmsdrm/SDL_kmsdrmvideo.c
This PR makes the backend report correct position to the application.
Fixes `SDL_GetWindowPosition` reporting incorrect positions on KMSDRM backend.
=> KMSDRM: Report correct window position to the application

src/video/wayland/SDL_waylandvideo.c
This adds an SDL_AddDisplayMode call to make the Wayland resolution list similar to macOS; the desktop mode should be scaled but we also want to provide unscaled resolutions provided by the server so that clients can do proper high-DPI support by targeting the display mode dimensions as drawable sizes, rather than window sizes.
=> wayland: Add unscaled resolutions to the display mode list

src/joystick/linux/SDL_sysjoystick.c
The information whether a specific joystick can be used as a gamepad is
not going to change every frame, so we can cache the result into a
variable.
This dramatically reduces the performance impact of SDL2 on small
embedded devices, since the code path that is now avoided was quite
heavy.
#4229
=> joystick: linux: Avoid checking for gamepad mapping each frame

src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandvideo.h, src/video/wayland/SDL_waylandwindow.c
This unearthed an unspeakably large amount of bugs in the wl_output enumerator,
notably the fact that the wl_output user pointer was to temporary memory!
This was "fixed" in e862856, and was then pointed out as a leak in 4183211,
which was undone in d9ba204. The busted fix was correct that the malloc was an
issue, but wrong about _why_; SDL_AddVideoDisplay copies by value and does not
reuse the pointer, so generally you want your VideoDisplay to be on the stack,
but of course the callbacks don't allow that, so a malloc was a workaround. But
we can do better and just host our temporary display inside WaylandOutputData
because that will be persistent while also not leaking.
Wait, wasn't I talking about move events? Right, that: wl_surface_listener does
at least give us the ability to know …
=> wayland: Implement basic window move events via wl_surface_listener.

src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandvideo.h, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
A random grab bag of commits for Wayland:
- GetDisplayBounds and GetDisplayDPI implemented (they were literally passed right to us, woops)
- Found a couple functions that SDL_video.c doesn't need from us, stripped those out
- RestoreWindow was a stub for some reason, fixed that for maximize windows (minimized windows, we're screwed)
- Threw in SetWindowModalFor because it turns out toplevel makes this easy to do
Nothing to see here, unlike HideWindow which will be a gigantic refactor (which is why I'm doing this now).
=> The Jackbox Wayland Pack

src/video/x11/SDL_x11events.c, src/video/x11/SDL_x11sym.h, src/video/x11/SDL_x11window.c
Fixes #4187 for X11 (it was already fixed for Wayland by #4303).
=> Fix keymap updating for X11 backend

include/SDL_video.h, src/dynapi/SDL_dynapi_overrides.h, src/dynapi/SDL_dynapi_procs.h, src/video/SDL_sysvideo.h, src/video/SDL_video.c, src/video/cocoa/SDL_cocoavideo.m, src/video/cocoa/SDL_cocoawindow.h, src/video/cocoa/SDL_cocoawindow.m, src/video/windows/SDL_windowsvideo.c, src/video/windows/SDL_windowswindow.c, src/video/windows/SDL_windowswindow.h
This PR adds an API to change the SDL_WINDOW_ALWAYS_ON_TOP flag after window creation.
I added implementations for Windows and macOS.
=> Add SDL_SetWindowAlwaysOnTop()

src/video/wayland/SDL_waylandmessagebox.c
Previous version used `popen` which required to sanitize user-provided text. Not sanitizing text could cause failure if it included a `"` or command injection with \`cmd\`.
This new version launches zenity with `execvp` so we don't need to sanitize. It then reads pressed button from a pipe.
Fix #4308
=> Reimplement wayland message box function with execvp. 

src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
This moves around the xdg_toplevel management in a way that allows us to implement HideWindow/ShowWindow properly.
For the most part this actually ended up being isolated from the rest of the driver; we have some early returns when the toplevel hasn't been made yet but it turns out it's more robust to just push all window state at ShowWindow time anyway. As a result this is really just changing the location and not really changing core functionality. The one exception is an extremely annoying behavior in the Wayland protocol where you have to manually detach any buffers from the wl_surface when creating the toplevel a second time, even though unmapping is supposed to be a full reset.
This was tested in both windowed/fullscreen mode on GNOME and Plasma and behavior was consistent.
=> wayland: Refactor toplevel mapping, implement HideWindow

cmake/sdlchecks.cmake
changes unnecessary check_c_source_runs to check_c_source_compiles,
removes the reduntant cross-compile check, and defines _GNU_SOURCE
for PTHREAD_MUTEX_RECURSIVE checks just like the autotools version.
Fixes: https://github.com/libsdl-org/SDL/issues/4262
Closes:  https://github.com/libsdl-org/SDL/pull/4282
=> CMake: fixes to pthreads detection.

src/joystick/windows/SDL_windowsjoystick.c
=> winrt: Always use a thread for joystick support

src/video/SDL_egl.c
This is similar to the check we have in the Cocoa video driver, where we have to catch attempts to go below 0 in SDL_GL_SetSwapInterval. Without this, some doofus working on an XNA reimplementation might accidentally pass -1 to eglSwapInterval where the spec silently clamps the input value to EGL_MIN_SWAP_INTERVAL and returns success, leading all GLES and Wayland contexts to run without vsync on for several years totally unnoticed.
I'm helping with an EGL_EXT_swap_control_tear extension, but it's still under review. We can add support for that when it's done.
=> egl: Reject attempts to set negative swap intervals

src/video/wayland/SDL_waylandopengles.c, src/video/wayland/SDL_waylandwindow.c
This fixes a couple issues I had with the original patch:
- The 100ms timeout is largely arbitrary and doesn't make sense for every scenario - in particular, we can assume that higher refresh rates don't need to wait as long because the callback should fire way sooner than it would elsewhere, so we can reduce the wait time as a result.
- The callback added only works for OpenGL, so let's run less code for Vulkan windows that aren't helped by this patch.
=> Minor fixes to Wayland SwapWindow patch

src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
Destroy the frame callback before destroying the surface.
Fixes https://github.com/libsdl-org/SDL/issues/4348.
=> wayland: destroy frame callback when window is destroyed

src/video/wayland/SDL_waylandwindow.c
Small fix to prevent accessing a NULL frame callback. This happened for me only with the `testvulkan` example.
=> fix NULL frame_callback access

src/video/wayland/SDL_waylandwindow.c
Also, Maximize should be ignored for fixed-size windows. This replicates X11 behavior.
Fixes #4345.
=> wayland: Maximize/Restore should set the relevant window flags

include/SDL_video.h
This adds a note to SDL_GetWindowBordersSize that explains the timing issue involved with SDL's query and the target display server; it's recommended to hold off on calling this function until the window system has a chance to actually _make_ the borders so it can tell us what the dimensions really are.
Fixes #3853.
=> include: Document timing issue with SDL_GetWindowBordersSize

configure, configure.ac, src/video/wayland/SDL_waylandvideo.h
Generic check for desktop GL and EGL on Linux systems
Desktop GL can also be used for Wayland, but the configure script currently requires GLX header or KMS/DRM video driver support to enable it. This change provides a generic check for desktop GL and EGL on Linux systems.
This change is typically useful to enable desktop GL on a pure Wayland system.
Nicolas Caramelli
=> Generic check for desktop GL and EGL on Linux systems

src/video/wayland/SDL_waylandtouch.c
On wayland systems, this will send x,y coordinates in `SDL_TouchFingerEvent` normalised to [0..1] instead of window coordinates.
According to https://wiki.libsdl.org/SDL_TouchFingerEvent, the `SDL_TouchFingerEvent`, the x,y coordinates should be normalised to [0..1]. This wasn't the case on wayland clients. Therefore, this merge request fixes that.
Games and applications using SDL, running with a wayland compositor and working around this issue will break on touch input if this gets merged. I haven't accounted for that within this merge request, I don't know if I should and I don't know how I should. Suggestions are welcome.
Tested on SailfishOS running the Lipstick wayland compositor. Could anyone verify this on other wayland compositors with touch input?
Resolves #4361
=> Wayland: send normalized coordinates in touch inputs events

src/video/x11/SDL_x11window.c
Removes deprecated code meant to support extremely ancient, pre-UTF-8
versions of Xorg. Uses new xlib API's for doing this same thing.
Closes #4288.
Closes rust-sdl2/Rust-SDL2#1087.
=> (X11) Set _NET_WM_NAME properly, fixes Unicode window titles

docs/README-kmsbsd.md
This PR adds a DragonFlyBSD-specific note about KMSDRM backend.
=> Update README-kmsbsd with DragonFly BSD note

src/core/winrt/SDL_winrtapp_direct3d.cpp, src/video/winrt/SDL_winrtevents_c.h, src/video/winrt/SDL_winrtpointerinput.cpp
Today in "we swear we didn't slap together a mouse API based on an earlier touch API," it appears the reason UWP couldn't process multiple mouse buttons at the same time is because rather than fire a press event for each one, it fires a press for the first event and then treats all other presses as _move_ events. No, I'm not totally sure why either. The good news is that while the event API is junk, the structure passed in the event gives us enough information to simulate the events within SDL's event queue. The result: Press/Release events are exactly as they were before, while move events check for secret press/release events hidden inside the PointerPoint.
Fixes #3908, https://github.com/FNA-XNA/FNA/issues/338
CC @PumpkinPaul
=> winrt: Fix support for multiple simultaneous mouse button presses

src/core/openbsd/SDL_wscons_kbd.c, src/core/openbsd/SDL_wscons_mouse.c
This PR improves WSCONS backend.
1. Adds missing Space key to WSCONS-to-SDL conversion table.
2. Removes WSCONS mouse scaling.
=> Improve WSCONS backend

src/audio/coreaudio/SDL_coreaudio.m
Removed duplicate SDL_AtomicGet() for the paused value.
Not sure if there was a reason for putting two of them in the if-clause since it could theoretically matter if it is important that the second check for paused is always done last. But in that case you could remove the first instance instead.
=> Removed duplicate SDL_AtomicGet()

src/joystick/controller_type.h, src/joystick/hidapi/SDL_hidapijoystick.c, src/joystick/usb_ids.h
Be more explicit about Xbox 360/One device ids that can be seen **on Windows**.
When Xbox One/Series Controllers are connected via USB they all are using `XBOXGIP` driver that produces a special input device with PID `0x02FF` (GIP software PID) for any connected controller. When connected via `Xbox Wireless Adapter` or Bluetooth/Bluetooth LE - driver produces different PIDs for each Xbox One pad type.
On the other hand `Xbox 360 Wireless Controller Reciever` (PID `0x0719`) is using `XUSB` driver and produces special PID `0x02A1` (XUSB software PID) for any connected Xbox 360 Wireless Controller. Wired Xbox 360 controllers are seen as `0x028E`.
Also fixed Xbox One Series X Controller comment.
=> Be more explicit about Xbox 360/One device ids

src/joystick/SDL_joystick.c
Adds the T500RS to the list of known wheels when querying the device type.
lsusb: `Bus 003 Device 005: ID 044f:b65e ThrustMaster, Inc. TRS Racing wheel`
dmesg after plugging in the device using https://github.com/cazzoo/hid-tmff2 / https://github.com/scarburato/hid-tminit/
```
[  924.442276] usb 3-6.2: new full-speed USB device number 4 using xhci_hcd
[  924.540297] usb 3-6.2: New USB device found, idVendor=044f, idProduct=b65d, bcdDevice= 1.00
[  924.540304] usb 3-6.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[  924.540307] usb 3-6.2: Product: Thrustmaster FFB Wheel
[  924.540309] usb 3-6.2: Manufacturer: Thrustmaster
[  924.628496] input: Thrustmaster Thrustmaster FFB Wheel as /devices/pci0000:00/0000:00:01.2/0000:20:00.0/0000:21:08.0/0000:2a:00.3/usb3/3-6/3-6.2/3-6.2:1.0 …
```
=> Added T500RS to known wheel list

src/video/kmsdrm/SDL_kmsdrmopengles.c, src/video/kmsdrm/SDL_kmsdrmvideo.c, src/video/kmsdrm/SDL_kmsdrmvideo.h
Hi,
I last updated SDL at commit 850d9c8c0daff485a07f065846ef0b00d067b258 at which point the KMSDRM backend was working well for my use case (https://redream.io). However, after updating to the latest I was having a number of issues:
* The mode requested in KMSDRM_SetDisplayMode wasn't updating the new surface_w / surface_h variables which caused the surface being created to be out of sync with the mode set. This fix is fairly straight forward.
* The mode requested in KMSDRM_SetDisplayMode wasn't being honored when calling SDL_SetWindowFullscreen(..., SDL_WINDOW_FULLSCREEN). KMSDRM_ReconfigureWindow was using the previous window size to find a mode and overriding the requested mode with that. My patch contains a fix for my particular case, but as mentioned in the commit message I'm still …
=> kmsdrm regression fixes

src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandvideo.h, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h, wayland-protocols/xdg-activation-v1.xml
This is a draft of Wayland RaiseWindow support - I say "draft" because I have no way of testing to make sure this works. Will mark as ready to merge once that's done.
Other than that, there's not much to see - the protocol implements window raising as an "activation token" which we send to the compositor and it may or may not honor our request depending on how it feels. Worst case it makes our window blink in the taskbar instead of actually raising it, which is better than nothing I suppose.
Test is [here](http://flibitijibibo.com/activationtest.tar.bz2). Use `./run.sh` to run with Wayland, alt-tab to a different window, and in 3 seconds the RaiseWindow call should occur.
=> wayland: Implement RaiseWindow with xdg-activation

src/hidapi/mac/hid.c
HIDAPI needs to ignore devices supported by Apple's Game Controller framework in the same way IOKit joystick does to avoid duplicate devices.
There's probably a few ways to handle this, but this seems to be the simplest patch to make.
=> Have HIDAPI skip MFI supported HID devices on macOS to avoid duplicate devices

src/events/SDL_events.c, src/video/SDL_sysvideo.h, src/video/cocoa/SDL_cocoaevents.h, src/video/cocoa/SDL_cocoaevents.m, src/video/cocoa/SDL_cocoavideo.m, src/video/windows/SDL_windowsevents.c, src/video/windows/SDL_windowsevents.h, src/video/windows/SDL_windowsvideo.c, src/video/windows/SDL_windowsvideo.h, src/video/x11/SDL_x11events.c, src/video/x11/SDL_x11events.h, src/video/x11/SDL_x11video.c, src/video/x11/SDL_x11video.h, test/CMakeLists.txt, test/Makefile.in, test/checkkeysthreads.c
When possible use native os functions to make a blocking call waiting for
an incoming event. Previous behavior was to continuously poll the event
queue with a small delay between each poll.
The blocking call uses a new optional video driver event,
WaitEventTimeout, if available. It is called only if an window
already shown is available. If present the window is designated
using the variable wakeup_window to receive a wakeup event if
needed.
The WaitEventTimeout function accept a timeout parameter. If
positive the call will wait for an event or return if the timeout
expired without any event. If the timeout is zero it will
implement a polling behavior. If the timeout is negative the
function will block indefinetely waiting for an event.
To let the main thread sees events sent form a …
=> Modifies WaitEvent and WaitEventTimeout to actually wait

include/SDL_video.h, src/dynapi/SDL_dynapi_overrides.h, src/dynapi/SDL_dynapi_procs.h, src/video/SDL_sysvideo.h, src/video/SDL_video.c, src/video/windows/SDL_windowsvideo.c, src/video/windows/SDL_windowswindow.c, src/video/windows/SDL_windowswindow.h, src/video/x11/SDL_x11video.c, src/video/x11/SDL_x11window.c, src/video/x11/SDL_x11window.h
For #4372
Implements a bare minimum to flash a window, for user's attention.
I only tested this with wine(for the windows part) and KDE.
The goal would be to match a description like this(from glfwRequestWindowAttention):
```
This function requests user attention to the specified window. 
On platforms where this is not supported, attention is requested to the application as a whole.
Once the user has given attention, usually by focusing the window or application,
the system will end the request automatically.
```
I only used the code we had in our project, and also only tested it for that => I didnt test it for multi window application or similar
Right now i just set SDL_SetError to "Not implemented" if the function doesn't exists.
=> Implement bare minimum for SDL_FlashWindow

src/events/SDL_events.c, src/video/SDL_sysvideo.h, src/video/windows/SDL_windowsevents.c
This PR contains several bugfixes and an optimization for the recently merged PR #4419 after kicking the tires on the new code a bit.
At least a couple of these are probably 2.0.16 blockers (breaking `SDL_PeepEvent(SDL_ADDEVENT)` wakeup and windows keyboard grab).
2e4cc77 fixes the case where an SDL application may use `SDL_PeepEvent(SDL_ADDEVENT)` to add an event to the queue. That would not trigger a wakeup of a waiting `SDL_WaitEvent()` call, potentially leading the application to deadlock.
212ac69 fixes the `SDL_HINT_WINDOWS_ENABLE_MESSAGELOOP=0` case where we would never wait at all if no event was already pending for us. In that case, `SDL_WaitEvent()` and `SDL_WaitEventTimeout()` would always immediately return 0, potentially leading to an unintended busy loop. The fix is simply to …
=> Fixes for new wait/wakeup code

include/SDL_test_common.h, src/test/SDL_test_common.c, test/testwm2.c
This adds a `SDLTest_CommonDrawWindowInfo` function to SDL_test_common.h and uses it in `testwm2` to draw various information about the window/renderer directly into the SDL window itself:
While you can get most or all of this information printed to console with `--info all`, it's nicer IMO to have it printed in the window itself, especially for testing exclusive fullscreen (may be difficult to see your debugger console), or things that change in realtime. I wanted this in particular so I can see at a glace what happens when windows are dragged between highdpi multi-monitor setups with different scale factors on different monitors.
=> testwm2: draw various debug logging into the window itself

src/video/wayland/SDL_waylandopengles.c
Who could have guessed that Wayland SwapWindow would still be problematic???
In doing more testing with larger titles, I've found that some applications will call SwapWindow once or more during startup, before the window has been shown. Unlike _after_ startup this affects every compositor I could get my hands on including GNOME, so at this point I'm just putting this function out of its misery and skipping it entirely when we know the window is completely hidden from the user.
A proper fix would be to introduce a timeout extension that acts the same way as vkAcquireNextImageKHR, but this is easier and involves a lot less paperwork.
Fixes Source 1 games at minimum (though they crash later in Miles for some unknown reason).
=> wayland: Drop SwapWindow calls for hidden windows

src/joystick/SDL_joystick.c
Without this comma it is impossible to enable both the Vita and Dummy
drivers at the same time.
Signed-off-by: Paul Cercueil <paul@crapouillou.net>
=> joystick: Add missing comma in joystick drivers list

src/joystick/virtual/SDL_virtualjoystick.c
SDL_JoystickSetVirtualAxisInner() and SDL_JoystickSetVirtualHatInner()
did not properly sanitize the 'axis' and 'hat' parameters.
Signed-off-by: Paul Cercueil <paul@crapouillou.net>
=> joystick: virtual: Fix event injection for axes/hats

src/filesystem/windows/SDL_sysfilesystem.c
Tested on Windows 10 x64, versions 19041 and 10586.
`SDL_GetBasePath` tries to reallocate its temporary buffer for long paths, but `GetModuleFileNameExW` always truncates and succeeds, so `len` was always equal to `buflen - 1` which is 127.
Easily fixed by checking for `buflen - 1` instead of `buflen`.
For paths longer than MAX_PATH, this problem sometimes got hidden by Windows path shortening (`C:\PROGRA~1\` etc.).
~~No issue for this bug AFAICT.~~
**EDIT: Fixes https://github.com/libsdl-org/SDL/issues/4439.**
Originally caused by the patch written for https://github.com/libsdl-org/SDL/issues/1390.
=> Windows: Fix SDL_GetBasePath() truncating paths

CMakeLists.txt
Adds missing libs to pkgconfig/cmake configs, that are required to be linked with app with gl-enabled build onf SDL2
=> PSVita: Add missing lib dependencies for gl-enabled build

src/render/vitagxm/SDL_render_vita_gxm.c
Fixes SDL_RenderSetLogicalSize on PSVita. GXM resets viewport each frame, so we need to re-apply viewport settings prior to drawing.
=> Vita: Reset/re-apply viewport on frame start/target change. 

src/video/wayland/SDL_waylandwindow.c
Most games will typically call SetWindowSize after unsetting fullscreen, but some exclusively toggle fullscreen and let resize events do the rest - Super Hexagon is one such game.
This makes it so going from fullscreen->windowed restores the `windowed` dimensions, as it does on other backends. Without this, fixed-size windows will be stuck in the display mode dimensions, which the game will not expect.
=> wayland: Fix returning to a window from fullscreen without calling SetWindowSize

configure.ac
Prefixing `-static-libgcc` with `-Wc,` is required to prevent it from being stripped out by libtool.
https://www.gnu.org/software/libtool/manual/html_node/Stripped-link-flags.html#Stripped-link-flags
#1622
=> Ensure that libgcc is linked statically on Windows

src/video/kmsdrm/SDL_kmsdrmvideo.c, src/video/kmsdrm/SDL_kmsdrmvideo.h
Change 270cd3a79e49a18f3658eb8b7a1877a3840effad fixed an issue with the KMSDRM backend when using SDL_SetWindowDisplayMode -> SDL_SetWindowFullscreen to perform a mode set, but it unfortunately broke other use cases for two reasons:
* The KMSDRM backend would early out when SDL_video.c called KMSDRM_SetDisplayMode with the desktop mode. This had been worked around by having KMSDRM_ReconfigureWindow check window->flags for SDL_WINDOW_FULLSCREEN_DESKTOP. When I added the conditional in there to check for SDL_WINDOW_FULLSCREEN it unintentionally caused this workaround to fall apart. I've fixed this in 9bbf0bbf072e2203a330d1dc5d51e9970157a222 by setting the driverdata field on the desktop_mode so KMSDRM_SetDisplayMode works correctly with it, and the workaround is no longer necessary (as far …
=> more kmsdrm regression fixes

src/events/SDL_events.c
This PR contains 2 bugfixes for the new event wake/wake code.
b77db48 improves performance by avoiding queuing redundant wakeup events and preventing spurious wakeups due to those additional wakeup events.
417c0bc2 fixes issues originating from the lack of calls to `SDL_PumpEvents()`. Win32 and X11 backends perform additional processing in their `PumpEvents()` handler that handles things like updating the cursor clip region and tickling the screensaver, so it needs to run regularly. `PumpEvents()` also performs batch event processing rather than one-at-a-time like `WaitEventTimeout()` does, so it is more efficient to process events this way.
=> Additional fixes for wait/wakeup code

src/video/cocoa/SDL_cocoavideo.m, src/video/cocoa/SDL_cocoawindow.h, src/video/cocoa/SDL_cocoawindow.m
Continuation of work for #4372.
This should be reviewed by a Mac developer before getting merged, I don't really know what I'm doing and mostly ripped off other functions that referenced NSApp. Seems fine on flibitMacBook but I dunno if that autoreleasepool thing is necessary.
=> cocoa: Implement FlashWindow

src/joystick/SDL_joystick.c
Having used this for a couple years, I can definitely confirm that it is not a joystick.
This fixes the Anne Pro II keyboard (OBINLB USB-HID Keyboard) showing up as a joystick under SDL.
=> Fix Anne Pro II keyboard showing up as a joystick

src/joystick/SDL_gamecontroller.c, src/joystick/usb_ids.h, src/joystick/windows/SDL_dinputjoystick.c
See  https://partner.steamgames.com/doc/features/steam_controller/steam_input_gamepad_emulation_bestpractices for details on what is Steam Virtual Gamepad.
=> Add Steam Virtual Gamepad and Xbox 360 Wired Controller defines instead of magic values

CMakeLists.txt
This is currently a small patch we have in our [Conan](https://conan.io) package for SDL https://github.com/bincrafters/community/blob/4dc894cc2c4df43aabf39c212aa0a31047d183e1/recipes/sdl2/all/conanfile.py#L184
Introduced in https://github.com/bincrafters/conan-sdl2/commit/9fb93a60446914da2a0fafc692cbd175c2d5db50 by @sse4 (partially for https://github.com/bincrafters/community/issues/574).
These two small changes should improve compatibility with MinGW.
=> CMake: Small improvement for MinGW

src/video/x11/SDL_x11modes.c
`X11_SetDisplayMode` currently calls `X11_XRRSetCrtcConfig` alone. This results in the monitor's viewport getting changed, but the underlying screen dimensions stay the same.
The spec indicates that `RRSetCrtcConfig` only changes the crtc mode and has no effect on the screen dimensions, only mentioning that the new crtc must fit entirely within the screen size. For the size to change, `RRSetScreenSize` also needs to be called.
This affects Metro Exodus on Linux, when changing the resolution in the in-game settings Metro gets stuck in a loop waiting for the size of its Vulkan surface to change. Because `XRRSetScreenSize` is not called the screen size is never changed, the Vulkan surface dimensions do not change, and Metro hangs forever watching for a surface size update that will never …
=> Call XRRSetScreenSize before setting CRTC config (fixes Metro Exodus)

src/events/SDL_mouse.c, src/video/windows/SDL_windowswindow.c
This aims to remove all cases of the cursor being "warped" to the center of the window when entering relative mode without `relative_mode_warp` being set. The goal here is to solve a race condition where the centering of the cursor can occasionally be accepted as a user input, causing the mouse to "jump" in position and cause an unexpected large delta. As mentioned in the issue. this only happens with high frequency toggling.
Please see each individual commit message for further rationale on the changes.
Closes https://github.com/libsdl-org/SDL/issues/4165.
```csharp
using System;
using SDL2;
namespace SDL2IsolatedRelativeModeTest
{
class Program
{
static bool relative;
static void Main(string[] args)
{
SDL.SDL_Init(SDL.SDL_INIT_VIDEO);
SDL.SDL_SetHint(SDL.SDL_HINT_EVENT_LOGGING, "2"); …
```
=> Fix OS cursor unexpectedly returning to center on toggling relative mode

src/video/windows/SDL_windowsopengles.c
When hint SDL_HINT_OPENGL_ES_DRIVER is set to "1" (e.g. for ANGLE support), assertion due to !_this->gl_config.driver_loaded can be causes while EGL is available. So, commenting SDL_assert(!_this->gl_config.driver_loaded).
#4177
=> Commenting a false alarm in WIN_GLES_SetupWindow.

CMakeLists.txt
This PR allows for building with cmake's [add_subdirectory](https://cmake.org/cmake/help/latest/command/add_subdirectory.html#command:add_subdirectory) function, like so:
```cmake
add_subdirectory(lib/SDL2 lib/SDL2_BIN EXCLUDE_FROM_ALL)
target_link_libraries(main PRIVATE SDL2)
```
As far as I know (and tested), that is the only change this commit makes; in-tree building is still prevented.
=> Use CMAKE_CURRENT_BINARY_DIR instead of CMAKE_BINARY_DIR

src/video/windows/SDL_windowsmouse.c
When `RegisterRawInputDevices` fails, reset `rawInputEnableCount` back to 0.
When `ToggleRawInput(SDL_TRUE)` is called twice, the second time will return 0 (success), even if it failed the first time.
This is an issue, since `SDL_SetRelativeMouseMode` assumes if the SetRelativeMouseMode backend failed, it does not need to be disabled afterwards.
https://github.com/libsdl-org/SDL/blob/32e736d2603e0c15dc69a717d7f0921a0c0abe69/src/events/SDL_mouse.c#L804-L816
The code responsible is unchanged since the reference counting was added, so this is likely just an oversight.
https://github.com/spurious/SDL-mirror/blob/be872bff15966a60d2358972ab083b3e565b61ee/src/video/windows/SDL_windowsmouse.c#L36
```
// WIN_SetRelativeMouseMode returns SDL_Unsupported, causing a fallback to relative_mode_warp, …
```
=> Fix ToggleRawInput result when RawInput is not supported

.github/workflows/main.yml
This PR adds a `-A ARM64` CMake build the GitHub Actions to ensure new PRs compile properly on ARM64.
SDL has been compiling and running successfully on Windows ARM64 for a while. Let's keep it that way 😉 
N/A
=> CI: Add Windows ARM64 builds

src/render/vitagxm/SDL_render_vita_gxm.c
Do not announce support for RGB/BGR textures in vita renderer and allow sdl to upconvert them to ARGB/ABGR.
That was causing issues, because internally RGB textures are ARGB in sdl, with alpha channel nulled, and current shader wouldn't draw them with blending enabled.
There were two solutions: 1) this one (e.g. remove support) and 2) provide different shaders for them, that explicitly set alpha to 1 (like gles2 renderer does). But providing different shaders would cause increase in shader switching = more updates to context state, and as there's no memory gain from supporting RGB/BGR i decided to go with 1.
=> Vita: Remove 'support' for rgb/bgr textures, that was causing issues with them

src/video/wayland/SDL_waylanddatamanager.c, src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandmouse.c, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandwindow.c
Wayland video subsystem uses a mix of libc and SDL functions.
This patch switches libc functions to SDL ones and fixes a mismatch in memory allocation/dealloccation of `SDL_Cursor` in SDL_waylandmouse.c (`calloc` at https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandmouse.c#L201 then `SDL_free` at https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandmouse.c#L313 ) which caused memory corruption if custom memory allocator where provided to SDL.
None.
=> Replace libc functions to SDL equivalent in wayland video subsystem

src/video/vita/SDL_vitagl.c, src/video/vita/SDL_vitagl_c.h
Simply adds the needed callback for handling updating SceCommonDialog on each call to `eglSwapBuffers`. Now you can use the keyboard regardless of which backend is used.
=> Add On-Screen Keyboard support to Vita OpenGL renderer

src/video/vita/SDL_vitatouch.c
It's not a touchscreen, but an additional touch panel on the back of the device.
=> vita: touch: Mark the back panel as an indirect absolute touch device

src/joystick/hidapi/SDL_hidapi_switch.c
Makes the switch pro controllers and joycons vibrate at different strengths instead of ON/OFF.
Each linear actuator is capable of vibrating at high and low frequency at the same time. Since we have 2 actuators we simply duplicate the vibration to the other one.
As a side note: I got HD rumble in a functional state on my fork. I would like to push those changes but first I want to discuss how to do it in such a way that it's convenient for everyone since it needs extra data(frequency values) to work properly.
=> hidapi_switch: Implement analog rumble

VisualC/SDL/SDL.vcxproj, VisualC/SDLmain/SDLmain.vcxproj, VisualC/SDLtest/SDLtest.vcxproj, VisualC/tests/checkkeys/checkkeys.vcxproj, VisualC/tests/controllermap/controllermap.vcxproj, VisualC/tests/loopwave/loopwave.vcxproj, VisualC/tests/testatomic/testatomic.vcxproj, VisualC/tests/testautomation/testautomation.vcxproj, VisualC/tests/testdraw2/testdraw2.vcxproj, VisualC/tests/testfile/testfile.vcxproj, VisualC/tests/testgamecontroller/testgamecontroller.vcxproj, VisualC/tests/testgesture/testgesture.vcxproj, VisualC/tests/testgl2/testgl2.vcxproj, VisualC/tests/testgles2/testgles2.vcxproj, VisualC/tests/testjoystick/testjoystick.vcxproj, VisualC/tests/testoverlay2/testoverlay2.vcxproj, VisualC/tests/testplatform/testplatform.vcxproj, VisualC/tests/testpower/testpower.vcxproj, VisualC/tests/testrendertarget/testrendertarget.vcxproj, VisualC/tests/testrumble/testrumble.vcxproj, VisualC/tests/testscale/testscale.vcxproj, VisualC/tests/testsensor/testsensor.vcxproj, VisualC/tests/testshape/testshape.vcxproj, VisualC/tests/testsprite2/testsprite2.vcxproj, VisualC/tests/testvulkan/testvulkan.vcxproj, VisualC/tests/testyuv/testyuv.vcxproj
This works with both Visual Studio 2010 and 2019 without having to retarget the solution.
=> Automatically select the default platform toolset for MSVC builds

src/video/vita/SDL_vitavideo.c
Adds a Return Key press emulation when a user hits the enter key.
`sceImeDialogGetResult` returns 3 values for the resulting button that was pressed. `SCE_IME_DIALOG_BUTTON_NONE`, `SCE_IME_DIALOG_BUTTON_CLOSE` and `SCE_IME_DIALOG_BUTTON_ENTER`. 
Typically when a user hits enter, they would expect it to have the same effect as pressing the return key, but a check for that case was missing. This creates issues for some software that uses SDL for keyboard input (Namely Ren'Py) as they will check for a return key press for confirmation. 
I added an `SDL_SendKeyboardKeyAutoRelease` call to handle simulating a return key input when a user closes the keyboard using the enter key to fix this issue.
=> Add Return Key support to Vita On-Screen Keyboard

src/video/x11/SDL_x11window.c
X11_XChangeProperty return 1 on success:
https://gitlab.freedesktop.org/xorg/lib/libx11/-/blob/master/src/ChProp.c#L93
=> Fix error handling in X11_SetWindowTitle

src/joystick/hidapi/SDL_hidapi_switch.c
Makes the switch pro controllers and joycons vibrate at given strength and frequency.
Following the changes of #4523. This PR implements HD rumble support in a form of GameControllerEffect or JoystickEffect. 
The effect data has a size of 8 bytes and contains the following format.
Byte 0-1: Low amplitude value from 0 to 65535
Byte 2-3: High amplitude value from 0 to 65535
Byte 4-5: Low frequency value in hertz 
Byte 6-7: High frequency value in hertz
=> hidapi_switch: Implement HD rumble effect

src/audio/SDL_audio.c, src/video/SDL_video.c
These two commits implement comma-separated lists for the `SDL_AUDIODRIVER` and `SDL_VIDEODRIVER` environment variables. This is useful because it effectively provides a way to reorder the hardcoded default driver list at runtime.
I've tested on Linux with the `wayland` and `x11` drivers. E.g. try setting `SDL_VIDEODRIVER=wayland,x11` and then unsetting `WAYLAND_DISPLAY`. Should skip the `wayland` driver and load `x11` (provided XWayland is available of course).
=> Comma-separated lists in audio/video driver environment variables

src/audio/wasapi/SDL_wasapi.c
WASAPI_WaitDevice is used for audio playback and capture, but needs to
behave slighty different.
For playback `GetCurrentPadding` returns the padding which is already
queued, so WaitDevice should return when buffer length falls below the
buffer threshold (`maxpadding`).
For capture `GetCurrentPadding` returns the available data which can be
read, so WaitDevice can return as soon as any data is available.
In the old implementation WaitDevice could suddenly hang. This is
because on many capture devices the buffer (`padding`) wasn't filled
fast enough to surpass `maxpadding`. But if at one point (due to unlucky
timing) more than maxpadding frames were available, WaitDevice would not
return anymore.
Issue #3234 is probably related to this.
=> Fixed microphone randomly stop working

src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
This fixes some crashes on startup I had when in high-DPI mode - for some reason this affected one setup and not the others, which is why this wasn't caught until now.
=> wayland: Rewrite update_scale_factor to always use the current display scale

src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandvideo.h, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
Ugh, okay, so to add on to #4541, it turns out that in addition to surfaces not being ours, we can also get outputs that aren't ours as well. Kind of bummed that the pointers don't match for a single output, but that's what we're left with.
Fixes high-DPI with libdecor support (for real this time).
=> wayland: Tag/Check wl_output objects as well, fixes crashes when libdecor is in use

src/video/wayland/SDL_waylandwindow.c
Fixes a crash when creating and destroying a window without calling SwapWindow.
Fixes #4545
=> wayland: Assign frame_callback on window creation

src/video/wayland/SDL_waylandwindow.c
Each window can have at most one zxdg toplevel decoration, but as of #4323, we accidentally create two. (If libdecor is not in use). This causes wayland windows with server-side decorations (e.g. on KDE/KWin) to crash with the message:
```
zxdg_decoration_manager_v1@7: error 1: decoration has been already constructed
```
This extra ``zxdg_decoration_manager_v1.get_toplevel_decoration()`` call was introduced while [deprecating wl-shell and xdg-shell-stable support](https://github.com/libsdl-org/SDL/pull/4323), and possibly was a bad interaction with #4374, which moved the decoration creation around.
Fixes: 6aae5b44f8 ("Remove wl-shell and xdg-shell-unstable-v6 support (#4323)")
=> wayland: Don't create zxdg toplevel decoration twice

src/video/wayland/SDL_waylandevents.c
As of [1], SDL now compiles with a warning in ``SDL_waylandevents.c`` on
32-bit systems under gcc 10.3.0:
```
/tmp/SDL/src/video/wayland/SDL_waylandevents.c: In function 'seat_handle_capabilities':
/tmp/SDL/src/video/wayland/SDL_waylandevents.c:958:22: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
958 |         SDL_AddTouch((SDL_TouchID)seat, SDL_TOUCH_DEVICE_DIRECT, "wayland_touch");
|                      ^
/tmp/SDL/src/video/wayland/SDL_waylandevents.c:964:22: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
964 |         SDL_DelTouch((SDL_TouchID)seat);
|                      ^
```
This is due to ``SDL_TouchID`` always being 32-bit, but seat being a pointer
which is (obviously) only 32-bit on 32-bit systems. The …
=> wayland: Avoid a pointer→TouchID cast warning

src/video/x11/SDL_x11opengl.c, src/video/x11/SDL_x11opengl.h
When choosing an X11 Visual for a window based on its GLX capabilities, first
try glXChooseFBConfig (if available) before falling back to glXChooseVisual.
This normally does not make a difference because most GLX drivers create a
Visual for every GLXFBConfig, exposing all of the same capabilities.
For GLX render offload configurations (also know as "PRIME") where one GPU is
providing GLX rendering support for windows on an X screen running on a
different GPU, the GPU doing the offloading needs to use the Visuals that were
created by the host GPU's driver rather than being able to add its own. This
means that there may be fewer Visuals available for all of the GLXFBConfigs the
guest driver wants to expose. In order to handle that situation, the NVIDIA GLX
driver creates many GLXFBConfigs …
=> x11: Use glXChooseFBConfig when available in X11_GL_GetVisual

src/audio/SDL_audiocvt.c
Optimized SDL_Convert51ToStereo_AVX to reduce loads and shuffling.
I found this version to be roughtly 5-10% faster, depending on the CPU.
=> Optimized SDL_Convert51ToStereo_AVX

include/SDL_audio.h, include/SDL_events.h, src/audio/SDL_audiocvt.c, src/audio/SDL_audiodev.c, src/cpuinfo/SDL_cpuinfo.c, src/render/opengles2/SDL_render_gles2.c, src/stdlib/SDL_iconv.c, src/video/SDL_egl.c, src/video/x11/SDL_x11mouse.c
This is needed to support CHERI, and thus Arm's experimental Morello prototype, where pointers are implemented using unforgeable capabilities that include bounds and permissions metadata to provide fine-grained spatial and referential memory safety, as well as revocation by sweeping memory to provide heap temporal memory safety.
The issues addressed fall into several categories:
1. Pointer provenance: integers and pointers are not the same, and casting to a virtual address-sized integer is a lossy operation, so it is vital to use (u)intptr_t rather than size_t or similar in pointer->integer casts that will be later cast back to a pointer and dereferenced, and for stuffing integers into `void *` or similar using (u)intptr_t in the casts suppresses warnings that alert the developer to …
=> Fixes to support CHERI/Morello

src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandevents_c.h, src/video/wayland/SDL_waylandkeyboard.c, src/video/wayland/SDL_waylandkeyboard.h, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandvideo.h, wayland-protocols/text-input-unstable-v3.xml
~~This was my last attempt to get the official text input protocol working with the Wayland driver. It was eventually abandoned because the protocol just doesn't work at all, based on my testing of both this patch as well as the official wlroots example. It's a really simple API so I'm not sure what we could be doing wrong. On all the desktops I could test against, all I get is an enter event with nothing else following it. Luckily all this does is add support for spawning the OSK, which end users can technically do themselves, and setting the text input rectangle, which only matters for windowed mode where we can't just assume the window is pinned at 0,0 like in fullscreen mode.~~ See https://github.com/libsdl-org/SDL/pull/4360#issuecomment-889334249 !
Fixes #3578.
=> wayland: Add support for text-input-unstable-v3

src/video/wayland/SDL_waylandwindow.c
This adds a surface commit after setting/unsetting capabilities.
The libdecor code path in function `SetFullscreen` sets/unsets the `LIBDECOR_ACTION_RESIZE` capability before/after setting fullscreen. This internally sets/unsets min/max limits and tells the client to commit its main surface via `libdecor_frame_toplevel_commit`, which in turn calls a client-provided callback. In SDL's case, this is calls `SDL_SendWindowEvent`.
In an earlier implementation of `libdecor_frame_toplevel_commit`, we indeed committed the surface via `wl_surface_commit` but this causes interference with OpenGL and Vulkan that commit the surface on their own. However, the "xdg" code paths use `CommitMinMaxDimensions` which in turn uses `wl_surface_commit` to commit the min/max limits without issues. So it seems to …
=> libdecor: commit after setting/unsetting limits

src/video/cocoa/SDL_cocoakeyboard.h, src/video/cocoa/SDL_cocoakeyboard.m, src/video/cocoa/SDL_cocoavideo.m
This PR adds support for keyboard grab on macOS using the `CGSSetGlobalHotKeyOperatingMode()` API. It suppresses system key combos to allow the application to handle them itself.
This function is not a public API (and thus, not permitted for App Store apps), so we will not compile this in by default. Instead, we'll use `SDL_MAC_NO_SANDBOX` (like the Cocoa mouse tap removed in 2fdbae22cb2f75643447c34d2dab7f15305e3567 did) to enable the compilation of this code using private APIs.
This feature is not compiled in by default so it should be safe, but I don't mind waiting until after 2.0.16 if needed.
=> cocoa: Add keyboard grab support

src/video/wayland/SDL_waylandwindow.c
Another new field was added to Wayland WMInfo this release, so guard it accordingly to prevent crashes from older applications.
=> wayland: Fix GetWindowWMInfo for <2.0.15

src/render/SDL_render.c
The ``RenderDrawLinesWithRects()`` and ``RenderDrawLinesWithRectsF()`` functions can sometimes call ``QueueCmdFillRects()`` with the data pointed to by ``frects`` uninitialised. This can occur if none of the lines can be replaced with rects, in which case the ``frects`` array is empty, and ``nrects`` is 0.
gcc 10.3.0 will detect this possibility, and print a warning like:
```
/home/david/Development/SDL/src/render/SDL_render.c: In function 'RenderDrawLinesWithRectsF':
/home/david/Development/SDL/src/render/SDL_render.c:2725:15: warning: '<unknown>' may be used uninitialized [-Wmaybe-uninitialized]
2725 |     retval += QueueCmdFillRects(renderer, frects, nrects);
|               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/david/Development/SDL/src/render/SDL_render.c:499:1: note: by …
```
=> render: Fix -Wmaybe-uninitialized warning in RenderDrawLinesWithRects{,F}

src/video/wayland/SDL_waylandwindow.c
When we removed the OpenGL resize workaround it introduced a problem for fullscreen windows in particular: When leaving fullscreen we tried to send a resize event, but UpdateFullscreenMode would send a SIZE_CHANGED immediately after, deleting our resize event and causing the following configure event's resize to be ignored. This timing issue resulted in fullscreen windows not being resized at all when becoming a floating window.
By always forcing resize events from configure events, we ensure that RESIZED always makes it through. SetWindowSize-type changes should be unaffected as they do not fire configure events.
Fixes toggling fullscreen for games like Super Hexagon (again).
=> wayland: Always trigger a resize when handling a configure event.

src/video/wayland/SDL_waylandevents.c
This fixes a crash on pressing keyboard button when compositor sends
zero as repeat rate, indicating that key repeat should be disabled.
From Wayland protocol spec:
> Negative values for either rate or delay are illegal. A rate of zero
> will disable any repeating (regardless of the value of delay).
=> wayland: Disable key repeat when repeat rate equals 0

src/misc/unix/SDL_sysurl.c
From the vfork manpage:
> The  vfork()  function has the same effect as fork(2), except that
> the behavior is undefined if the process created by vfork() either
> modifies any data other than a variable of type pid_t used to store
> the return value from vfork(), or returns from the function in which
> vfork() was called, or calls any other function before successfully
> calling _exit(2) or one of the exec(3) family of functions.
unsetenv is still called inside a child process, so it does not influence the rest of the application.
Fixes 9b7b928765ce732ca3024a42d0281fea7192ecaf
=> unix: OpenURL: Move unsetenv above vfork

src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
Store and restore floating dimensions when restoring from maximised/fullscreen to floating state. This affects the xdg and libdecor implementations.
We now store the window size if the window is in a floating mode (not fullscreen/maxmised/tiled) so that when we have to restore from a  fullscreen/maxmised/tiled state to a floating state, we use our previous floating dimensions.
I added a dedicated "floating_*" set of variables and did not reuse the `windowed` that seem to have a similar use. This is because `windowed` is only used for fullscreen and is in a more global scope, whose changes might have some undesired effects. The new "floating" variables are only used within Wayland and should not affect the public SDL API.
There are remaining issues with transitioning from between …
=> wayland: restore floating states

src/video/wayland/SDL_waylandwindow.c
Otherwise our windows have no window decoration on compositors that support *xdg-decoration-unstable-v1*, but default to client-side mode.
Contrary to what the comment was stating, there is nothing in the protocol that would make redundant calls to [`zxdg_toplevel_decoration_v1::set_mode`](https://wayland.app/protocols/xdg-decoration-unstable-v1#zxdg_toplevel_decoration_v1:request:set_mode) problematic.
=> wayland: Always call Wayland_SetWindowBordered when showing the window

src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
Commit 871c11191bfc7214061a3da37c112522a102ddf5 removed delayed resize handling, but it left the whole structure untouched that now became unnecessary. To help with code clarity, get rid of the structure where pending resize state used to be stored and pass all the data directly to `Wayland_HandlePendingResize` (now renamed to `Wayland_HandleResize`, since it's not "pending" anymore but applied immediately)
/cc @flibitijibibo @icculus - this shouldn't change the behavior in any way (neither positive nor negative) since the logic stays the same - but that's assuming I did not make a mistake, so some additional testing will be appreciated
=> wayland: Clean up Wayland_HandlePendingResize

src/video/wayland/SDL_waylandwindow.c
This allows the windowed size to be restored for windows initially created already in non-floating state.
=> wayland: Initialize floating size at window creation

src/video/wayland/SDL_waylandwindow.c
Changes intended to workaround #4563. Fixing it properly seems to be a larger task, which is unlikely to get done for 2.0.16, so this at least allows us to not crash meanwhile. See the commit messages for more information.
/cc @flibitijibibo
=> wayland: Workaround protocol violations when toggling fullscreen

configure.ac
The ``$(objects)`` directory (usually ``build/``) may not have been created by the time the ``wayland-scanner`` protocol files are being compiled. The ``$(gen)`` directory is explicitly made with ``mkinstalldir``, but the final object file (and gcc dependency files) need to go into ``$(objects)``.
For whatever reason, this only ever seemed to occur if ``--disable-shared`` was set.
Note that this PR doesn't regenerate ``./configure`, as there were a few unexplained, unrelated differences my version of ``autoconf`` created, as as an autotools novice, I didn't want to poke that bear just yet.
This hopefully should fix #3689
=> configure.ac: mkdir $(objects)/ when building wayland protocols

src/render/SDL_render.c
The Renderer logical scaling code scales mouse coordinates, and needs to take the window DPI into account on HIGHDPI windows. However, the variable which tracks this, renderer->dpi_scale, is set once when the renderer is created, and then not updated. In the event that the window is moved to another screen, or the screen DPI otherwise changes, this will be outdates, and potentially the coordinates will be all wrong.
So let's update the dpi_scale on the ``SIZE_CHANGED`` event: it's at least a possibility that this will be issued on some OSes when DPI changes, and it's otherwise already handled by SDL_Renderer's event filter.
=> Update the Renderer dpi_scale on SIZE_CHANGED event (fix #4580)

configure.ac
The `LINKER` variable is set to a literal `CC` or `CXX` instead of the appropriate `make(1)` variable.
The `LINKER` variable is set in configure.ac as either 'CC' or 'CXX' where it is then passed to the created Makefile. This fails with
slibtool which can't find the 'CC' file and can be fixed by correctly setting the LINKER variable to an actual Makefile variable like '$(CC)' or '$(CXX)' instead. Presumably GNU libtool does some magic here to hide the issue.
Introduced in: https://github.com/libsdl-org/SDL/commit/761d38379b8d5eabc02327f8363baeda52316939 https://github.com/libsdl-org/SDL/pull/4537
=> build: Fix the LINKER variable.

src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandvideo.h, src/video/x11/SDL_x11video.c, src/video/x11/SDL_x11video.h
This lazy init logic is dead code since dbdbae4, so we can drop it after 2.0.16.
#4587
=> linux: remove x11/wayland d-bus lazy init code

src/video/SDL_video.c
SDL_CreateWindow() with SDL_WINDOW_FULLSCREEN didn't work on Windows if resolution is higher than desktop resolution.
SDL_SetWindowDisplayMode() on a fullscreen window switches the display resolution, but didn't set `window->w` and `window->h` and doesn't adjust the size of the window-surface either.
Setting `window->fullscreen.w` and `.h` to a resolution as close as possible to the requested one (using SDL_GetClosestDisplayModeForDisplay()) in SDL_CreateWindow() (if called with SDL_WINDOW_FULLSCREEN) fixes the first issue.
The second issue is fixed by setting `window->w` and `->h` and after setting the new display mode in SDL_SetWindowDisplayMode(), and then calling SDL_OnWindowResized() to make sure it's applied.
(I hope this is the correct/best way?)
Fixes #3313
=> Fixes for fullscreen mode

include/SDL_hints.h, src/video/wayland/SDL_waylandvideo.c
Useful for testing xdg-shell path with compositors like Weston.
=> wayland: Add a hint to allow disabling libdecor use

test/testvulkan.c
``SDL_Vulkan_GetDrawableSize()`` doesn't always return a size which is within the Vulkan swapchain's allowed image extent range.
(This happens on X11 a lot when resizing, which is bug #3287)
Clamp the value we get back from ``SDL_Vulkan_GetDrawableSize()`` to this range. Given the range usually is just a single value, this is almost always equivalent to just using the min or max image extent, but this seems logically most correct.
Without this change, ``testvulkan --resizable`` gives a lot of warnings when resized on X11:
```
VUID-VkSwapchainCreateInfoKHR-imageExtent-01274(ERROR / SPEC): msgNum: 2094043421 - Validation Error: [ VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 ] Object 0: handle = 0xcff5f0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7cd0911d | vkCreateSwapchainKHR() …
```
=> testvulkan: Clamp the drawable size to the allowed range

src/video/wayland/SDL_waylandvideo.h, src/video/x11/SDL_x11video.h
b08b1bde introduced a subtle bug. Despite not using D-Bus types directly, the code used the `SDL_USE_LIBDBUS` definition set by `SDL_dbus.h` to conditionally compile calls `SDL_DBus_ScreensaverTickle()` and `SDL_DBus_ScreensaverInhibit()`. As a result, it still compiled without `SDL_dbus.h` included, but screensaver suspension silently failed to work.
The D-Bus stuff could probably use some tweaks to be harder to accidentally break, but for now just restore the header includes.
=> x11/wayland: fix screensaver suspension via D-Bus

CMakeLists.txt
According to https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html
`${CMAKE_INSTALL_LIBDIR} ` is only variable which should be used as base
directory. Without that patch on 64 bit archs libraries, cmake modules and
pkgconfig file are installed for example in /usr/lib6464 base directory.
Fixes #4621
=> Fix breaking GNUInstallDirs cmake module $CMAKE_INSTALL_LIBDIR directory

src/video/windows/SDL_windowsevents.c, src/video/windows/SDL_windowswindow.c, src/video/windows/SDL_windowswindow.h
=> Fixing WM_CHAR event handling for Unicode characters outside the Basic Multilingual Plane

CMakeLists.txt, cmake/sdlchecks.cmake, configure, configure.ac, include/SDL_config.h.cmake, include/SDL_config.h.in, include/SDL_config_android.h, include/SDL_config_iphoneos.h, include/SDL_config_macosx.h, include/SDL_config_os2.h, include/SDL_config_pandora.h, include/SDL_config_wiz.h, src/dynapi/SDL_dynapi.h, src/thread/pthread/SDL_systhread.c, src/video/directfb/SDL_DirectFB_opengl.c, src/video/nacl/SDL_naclopengles.c, src/video/x11/SDL_x11opengl.c
- cmake, configure (CheckDLOPEN): --enable-sdl-dlopen is now history..
detach the dl api discovery from SDL_LOADSO_DLOPEN functionality.
define HAVE_DLOPEN. also define DYNAPI_NEEDS_DLOPEN (CheckDLOPEN is
called only for relevant platforms.)
- update SDL_config.in and SDL_config.cmake accordingly.
- SDL_dynapi.h: set SDL_DYNAMIC_API to 0 if DYNAPI_NEEDS_DLOPEN is
defined, but HAVE_DLOPEN is not.
- pthread/SDL_systhread.c: conditionalize dl api use to HAVE_DLOPEN
- SDL_x11opengl.c, SDL_DirectFB_opengl.c, SDL_naclopengles.c: rely
on HAVE_DLOPEN, not SDL_LOADSO_DLOPEN.
- SDL_config_android.h, SDL_config_iphoneos.h, SDL_config_macosx.h,
SDL_config_pandora.h, and SDL_config_wiz.h: define HAVE_DLOPEN.
Closes: https://github.com/libsdl-org/SDL/pull/4351
=> configuration updates for dlopen:

src/audio/SDL_audiocvt.c
C.f.: https://github.com/libsdl-org/SDL/issues/4533
The user _should_ still be able to enable avx (e.g. by `-mavx` or something)
@slouken, @jbsolomon: please verify this.
=> Don't disable clang avx instrinsics on win32 if __AVX__ is defined.

src/joystick/linux/SDL_sysjoystick.c, src/video/wayland/SDL_waylandvideo.c
Just some stuff I found when running Taisei under ASan. The first commit fixes a leak of cached joystick mappings, allocated at: https://github.com/libsdl-org/SDL/blob/44a76710d1a4f2bbcee47b14d4bdd8d75263d094/src/joystick/linux/SDL_sysjoystick.c#L1625
It also streamlines some divergent duplicate code to avoid similar issues in the future. 
The second commit fixes a leak of Wayland output names, allocated at: https://github.com/libsdl-org/SDL/blob/44a76710d1a4f2bbcee47b14d4bdd8d75263d094/src/video/wayland/SDL_waylandvideo.c#L302
=> Fix some minor memory leaks on Linux

include/SDL_endian.h, include/SDL_stdinc.h
The `__clang_major__` and `_clang_minor__` macros provide a marketing
version, which is not necessarily comparable for clang distributions
from different vendors[1]. In practice, the versioning scheme for
Apple's clang is indeed completely different to that of the llvm.org
releases. It is thus preferable to check for features directly rather
than comparing versions.
In this specific case, `__builtin_bswap16` was being used with older
Apple clang versions that don't support it.
[1] https://clang.llvm.org/docs/LanguageExtensions.html#builtin-macros
=> Correctly check for bswap builtins before using

src/audio/SDL_audiocvt.c
Don't rely on checking `__clang_major__` since it is not comparable
between different vendors. Don't use `#pragma clang attribute` since it
is only available in relatively recent versions, there's no obvious way
to check if it's supported, and just using `__attribute__` directly (for
gcc as well) results in simpler code anyway.
=> Improve portability of SDL_Convert51ToStereo_AVX

test/checkkeys.c
On Wayland -- or at least on some Wayland implementations -- windows
aren't shown until something has been rendered into them. For the
'checkkeys' test program, this means that keyboard input isn't
registered, making the program rather useless.
By creating a renderer and presenting once, the window is properly
displayed, and the test behaves as it does under X11 (including
XWayland).
The exact same thing was done with testmessge in 1cd97e2695 (PR #4252)
=> checkkeys: Create a renderer for window display on Wayland

include/SDL_stdinc.h, src/events/SDL_events.c, src/joystick/iphoneos/SDL_mfijoystick.m, src/video/wayland/SDL_waylandevents.c, test/testvulkan.c
Add a function to clamp a value to a range.
``SDL_clamp(x, a, b)`` is equivalent to ``SDL_min(a, SDL_max(x, b))``: it ensures that ``x`` is neither smaller than ``a``, nor larger than ``b``. This is implemented as a macro, alongside the ``SDL_min()`` and ``SDL_max()`` macros. It similarly can evaluate its inputs more than once, so isn't safe to use if its arguments are expressions with side effects.
Note that, as far as I can tell, ``clamp()`` is even less standardised than ``min()`` and ``max()``, so I'd understand if having it in ``SDL_stdinc.h`` doesn't seem like the best fit.
Thoughts?
=> [Feature] Add new SDL_clamp() macro

include/SDL_stdinc.h
SDL_clamp was missing parenthesis around the whole expression, causing issues with operator precedence.
=> Added missing parenthesis around SDL_clamp

src/video/wayland/SDL_waylandevents.c
This can happen e.g. on pure wayland system where there is no X11 locales for xkbcommon to find.
On a pure Wayland system, completely without X, libxkbcommon would not be able to find locales in /usr/share/X11/locale/ (which are installed by libx11 if X is present), so input->xkb.compose_table and input->xkb.compose_state will be NULL. In this case check input->xkb.compose_state for NULL before using it.
-
=> waylandevents: prevent segfault if xkb compose table is not found

include/SDL_keycode.h
Some applications check for KMOD_RESERVED when printing set key modifiers but it was replaced with KMOD_SCROLL in https://github.com/libsdl-org/SDL/commit/cb1e20b058f1de55b98f32b7d16cff1f896f88dd. Those applications fail to compile against the latest SDL headers / 2.0.17 due to missing KMOD_RESERVED.
It [affected ioquake3](https://github.com/ioquake/ioq3/blob/bc8737d707595aebd7cc11d6d5a5d65ede750f59/code/sdl/sdl_input.c#L76-L87) (now [fixed](https://github.com/ioquake/ioq3/commit/77d6cde137d9dca0ac4f2473d25c278bc65e34d9)) but it still affects past versions and many derivatives.
Patch restores KMOD_RESERVED for source-level compatibility with SDL 2.0.0.
=> Restore KMOD_RESERVED for backward compatibility

include/SDL_video.h
I removed a comma at end of enumerator list in the `include/SDL_video.h` file to fix a compilation problem with GCC.
Here is the code to compile with GCC:
```
#include <SDL.h> /* for SDL_Init */
int main()
{
if(SDL_Init(SDL_INIT_VIDEO | SDL_INIT_AUDIO) != 0)
{
SDL_Log("Unable to initialize SDL: %s", SDL_GetError());
return 1;
}
SDL_Quit();
return 0;
}
```
Here is the result:
```
gcc -std=c89 -pedantic -Wall -Werror -g `pkg-config sdl2 --cflags` -o main.out main.c `pkg-config sdl2 --libs-only-L` `pkg-config sdl2 --libs-only-l`
In file included from /usr/include/SDL2/SDL_events.h:33,
from /usr/include/SDL2/SDL.h:41,
from main.c:1:
/usr/include/SDL2/SDL_video.h:210:28: error: comma at end of enumerator list [-Werror=pedantic]
SDL_FLASH_UNTIL_FOCUSED,            /**< Flash the window until it …
```
=> include/SDL_video.h: Remove a comma at end of enumerator list

include/SDL_config.h.cmake
I get a bunch of warnings, one for each time SDL_config.h gets included like below (I am building with `-Wundef`)
```
SDL2/SDL_config.h:206:7: warning: "__WIN32__" is not defined [-Wundef]
#elif __WIN32__
^
```
This commit removes them
=> remove warnings from Wundef in SDL_config.h.cmake

src/audio/pipewire/SDL_pipewire.c
This can be used by recent pipewire to avoid resampling.
For more info see the following pipewire commits:
https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/1ff208875cfd18f35ae6821328c236e21d348c84
https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/bf66a3b2362093dbcc3a35dffe4d6bea2a896c67
https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/7846687df869d99d95701b419080234450fd6d8d
=> audio: pipewire: Set PW_KEY_NODE_RATE to suggest a rate.

src/audio/pipewire/SDL_pipewire.c
This fixes audio with the pipewire backend in The Evil Within (running on FAudio).
=> audio: pipewire: Reset hotplug atomic variables on deinit.

CMakeLists.txt
Although GCC and Clang automatically generate color diagnostics on terminal output, they do not do so when the compiler output is piped through another process, like in the case for ninja-build and ccache.
Similarly, it would also be nice to be able to see the color diagnostics on the CI build log in the web interface provided by the CI providers.
=> Force color diagnostics when applicable

src/joystick/SDL_gamecontrollerdb.h
This change corrects the mappings for the Atari gamecontroller and adds support for the Atari Xbox 360 compatible gamecontroller. The Atari game controller can switch between Atari and Xbox 360 mappings.
The changes were made to src/joystick/SDL_gamecontrollerdb.h. The test/controllermap command was used to generate the mapping for the Atari gamecontroller in Xbox 360 compatibility mode.
=> Fixed the Atari gamecontroller mappings and added Atari Xbox 360 Compatibility

src/audio/SDL_audio.c, src/video/SDL_video.c
The recent change to make SDL_AUDIODRIVER support comma-separated lists
broke the previous behavior where an SDL_AUDIODRIVER that was empty
behaved the same as if it was not set at all. This old behavior was
necessary to paper over differences in platforms where SDL_setenv may
or may not actually delete the env var if an empty string is specified.
This patch just adds a simple check to ensure SDL_AUDIODRIVER is not
empty before using it, restoring the old interpretation of the empty
var. This also adds a similar fix for SDL_VIDEODRIVER.
=> Restore previous behavior of empty SDL_AUDIODRIVER trying all drivers.

include/SDL_hints.h, src/audio/pipewire/SDL_pipewire.c, src/audio/pulseaudio/SDL_pulseaudio.c, src/core/linux/SDL_dbus.c
See SDL bug #4703. This implements two new hints:
- ``SDL_SCREENSAVER_INHIBIT_APP_NAME``
- ``SDL_SCREENSAVER_INHIBIT_ACTIVITY_NAME``
These allow the application and activity name used by ``org.freedesktop.ScreenSaver``'s Inhibit method, which are often shown in the UI as the reason the screensaver (and/or suspend/other power-managment features) is disabled.
Open questions:
- Do we want to merge ``SDL_HINT_SCREENSAVER_INHIBIT_APP_NAME`` with ``SDL_HINT_AUDIO_DEVICE_APP_NAME``?
- If so, do we still also support them separately?
- If so, do we want to do so with a Hint, or do we introduce a separate ``SDL_SetAppName()`` function?
=> Add DBUS screensaver inhibition naming hints

src/video/x11/SDL_x11events.c
Horizontal scroll direction is mixed up on X11.
Docs say "the amount scrolled horizontally, positive to the right and negative to the left". My tests show:
```
OS is configred so scrollbar moves to the direction of wheel.
Linux
Left         = +0 +1
Right        = +0 -1
Windows
Left         = +0 -1
Right        = +0 +1
```
For reference GLFW already does this: https://github.com/glfw/glfw/blob/22b586b3d87c91581074cc2a47fe5eba6f10bf0d/src/win32_window.c#L939
Given note in GLFW repository, i suspect MacOS events also need inverting. I am waiting for someone with hardware to test. When i get test data I will amend this PR if needed.
=> Fix horizontal wheel scroll event direction

include/SDL_hints.h, src/video/windows/SDL_windowskeyboard.c
This PR fixes an issue with IME support on Windows where SDL2 windows in a Windowed state were not showing the IME Candidate Window. There were 2 root causes of this issue, the first was the existence of a UI Sink that was not toggleable. The second was a mistake in the code that set the position of the IME Candidate Window. The incorrect structure was being allocated and passed along to the function responsible for setting the Candidate Window's position.
I have added a new SDL hint "SDL_HINT_IME_SHOW_UI", which when true will ensure that the standard IME UI will appear as normal. If left false, default behavior (prior to this commit) is retained. This ensure backwards compatibility.
Future improvements would include the ability to get the current IME Candidate Window's candidate list so …
=> Added: Support for showing the IME Candidate Window on Windows

test/configure.ac
AC_CONFIG_AUX_DIRS is an undocumented, internal version of
AC_CONFIG_AUX_DIR that takes a whitespace-separated list, instead of a
single path to add to the list. It also does not automatically treat
the given path as being relative to the $srcdir, unlike the documented
AC_CONFIG_AUX_DIR.
Newer versions of autoconf treat the argument to AC_CONFIG_AUX_DIRS
as being literal (they do not expand the shell variable), causing
autoreconf to fail if $srcdir is explicitly specified. The argument to
AC_CONFIG_AUX_DIR is checked  relative to $srcdir anyway, so there is no
need to specify $srcdir a second time.
Resolves: https://github.com/libsdl-org/SDL/issues/4719
=> test: Fix path used in AC_CONFIG_AUX_DIR

test/Makefile.in
The version with an implicit pattern rule tended to fail if test/
was built in an "out-of-tree" build directory not below test/, for
example:
cd SDL
mkdir _build-test
( cd _build-test; ../test/configure )
make -C _build-test
as a result of the pattern rule first checking for axis.bmp, then for
../test/axis.bmp, then ../test/../test/axis.bmp, and so on until the
maximum path length was reached.
Note that this requires GNU make. The FreeBSD ports file for SDL seems
to use GNU make (gmake) already, so presumably SDL's build system is
already relying on GNU make extensions.
https://github.com/libsdl-org/SDL/pull/4720#issuecomment-913576524
=> test: Use a static pattern rule to copy data to $(builddir)

docs/README-raspberrypi.md
Just some markdown formatting fixes.
Just some markdown formatting fixes of the Raspberry Pi related documentation. These are obviously purely cosmetic, but it fixes GitHub's rendering of the file.
none
=> Markdown formatting fixes (purely cosmetic, fixes GitHub's rendering)

CMakeLists.txt, docs/README-vita.md, include/SDL_config.h.cmake, include/SDL_egl.h, src/render/vitagxm/SDL_render_vita_gxm.c, src/render/vitagxm/SDL_render_vita_gxm_memory.c, src/render/vitagxm/SDL_render_vita_gxm_memory.h, src/render/vitagxm/SDL_render_vita_gxm_shaders.h, src/render/vitagxm/SDL_render_vita_gxm_tools.c, src/render/vitagxm/SDL_render_vita_gxm_tools.h, src/render/vitagxm/SDL_render_vita_gxm_types.h, src/video/SDL_egl.c, src/video/vita/SDL_vitaframebuffer.c, src/video/vita/SDL_vitaframebuffer.h, src/video/vita/SDL_vitagl.c, src/video/vita/SDL_vitagl_c.h, src/video/vita/SDL_vitagl_pvr.c, src/video/vita/SDL_vitagl_pvr_c.h, src/video/vita/SDL_vitakeyboard.c, src/video/vita/SDL_vitakeyboard.h, src/video/vita/SDL_vitamessagebox.c, src/video/vita/SDL_vitamessagebox.h, src/video/vita/SDL_vitamouse.c, src/video/vita/SDL_vitamouse_c.h, src/video/vita/SDL_vitatouch.c, src/video/vita/SDL_vitatouch.h, src/video/vita/SDL_vitavideo.c, src/video/vita/SDL_vitavideo.h
This adds support for gles1/gles2 context creation and sdl renderers on PSVIta via native pvr gpu driver (PVR_PSP2).
=> Vita: egl/gles1/gles2 support

CMakeLists.txt, include/SDL_revision.h.cmake
The first commit is based on these two MSYS2 patches:
- https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-SDL2/001-fix-cmake-target-relocation.patch
- https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-SDL2/003-fix-static-library-name.patch
=> cmake: MinGW build fixes

docs/README-vita.md, src/video/vita/SDL_vitagl_pvr.c, src/video/vita/SDL_vitakeyboard.c, src/video/vita/SDL_vitatouch.c, src/video/vita/SDL_vitavideo.c, src/video/vita/SDL_vitavideo.h
Added `libime` keyboard support for PVR_PSP2 as `ime_dialog` will not function with the PVR driver.
Added env vars for enabling 720p and 1080i display modes with PVR_PSP2. Only the PSTV supports these resolutions **officially**.
Added env vars to independently disable the front or back touchpads to prevent unwanted mouse inputs on 1k models.
=> Vita: PVR_PSP2 OSKeyboard Support/Independent Touchpad Disabling

include/SDL_render.h, src/dynapi/SDL_dynapi_overrides.h, src/dynapi/SDL_dynapi_procs.h, src/render/SDL_render.c, src/render/SDL_sysrender.h, src/render/direct3d/SDL_render_d3d.c, src/render/direct3d11/SDL_render_d3d11.c, src/render/metal/SDL_render_metal.m, src/render/opengl/SDL_render_gl.c, src/render/opengles/SDL_render_gles.c, src/render/opengles2/SDL_render_gles2.c, src/render/psp/SDL_render_psp.c, src/render/vitagxm/SDL_render_vita_gxm.c
Currently, if an application wants to toggle VSync, they'd have to tear down the renderer and recreate it. This patch fixes that by letting applications call `SDL_RenderSetVSync()`.
This is the same as the patch in #3673, except it applies to all renderers (including PSP, even thought it seems that the VSync flag is disabled for that renderer). Furthermore, the renderer flags also change as well, which #3673 didn't do. It is also an API instead of using hint callbacks (which could be potentially dangerous).
Closes #3673.
=> Add `SDL_RenderSetVSync()`

include/SDL_render.h, src/render/SDL_render.c
Followup to #4157.
In the future, we might want to support special swap intervals. To prevent applications from expecting nonzero values of `vsync` to be the same as "on", fail with `SDL_Unsupported()` if the value passed is neither 0 nor 1.
=> `SDL_RenderSetVSync()`: Restrict `vsync` to 0 or 1

VisualC/SDL/SDL.vcxproj, src/video/windows/SDL_windowskeyboard.c
Fixes an issue where IME Text that has trailing whitespace U+12288 is incorrectly striped when the candidate that was issued was explicitly a U+12288 character. The intention appears to be that U+12288 gets striped as trailing whitespace to a string, not prevent U+12288 from being issued as the IME_TEXT as a whole.
Additionally, a minor fix for a previous fix (PR #4707) to the candidate window not positioning correctly (SDL_SetTextInputRect).
Retains previous trailing whitespace strip code with the addition that the string length must be larger than 1 character long.
ImmSetCompositionWindow called along side ImmSetCandidateWindow to address a regression with #4707.
None
=> Fixed: Whitespace being striped from the end of IME strings incorrectly + Regression with SDL_SetTextInputRect

src/atomic/SDL_atomic.c
Original code was assuming that Clang is linked to `libatomic` from GCC, which's not always the case – Clang can use atomic implementation from its own `compiler-rt` library [1].
For example, such explicit usage of "native" atomic implementation for Clang is present on Gentoo [2] – in this case, it's possible to create completely GCC-free toolchain. Proposed change should allow such systems to fully utilize atomics from compiler-rt.
Also I think it can fix Android bug mentioned in the comment, since according to [3] and [4], they've slated GCC for removal in v18; while support for required `#ifdef` is _kinda_ there [5], I guess it'll be safe to remove `if !defined(__ANDROID__)` altogether.
[1] https://clang.llvm.org/docs/Toolchain.html#atomics-library
[2] …
=> atomic: detect clang separately

include/SDL_endian.h
- Existing code for relying on compiler-provided builtins was used only for x86/amd64 arch;
- `__GNUC__` macro effectively removed anything beyond GCC/MSVC/Watcom (at least Clang)
=> fix: allow builtins for all archs

include/SDL_video.h
For some reason, this function isn't listed on the wiki despite already having doxygen comments.
=> Update description of SDL_SetWindowAlwaysOnTop

src/render/vitagxm/SDL_render_vita_gxm_tools.c
@isage Fallback to LPDDR in case of failed CDRAM texture allocation on Vita
Texture allocations will fail if we're out of VRAM on PS Vita. This PR tries allocating the texture with `SCE_KERNEL_MEMBLOCK_TYPE_USER_RW_UNCACHE` `SceKernelMemBlockType` in case of failed `SCE_KERNEL_MEMBLOCK_TYPE_USER_CDRAM_RW` allocation.
Additionally it's using aligned stride in `sceGxmColorSurfaceInit`. `sceGxmColorSurfaceInit` will result in a crash if stride is not aligned by 2. It will also result in visual bugs during rendering to render target if it's not aligned by 8.
=> Fallback to LPDDR in case of failed CDRAM texture allocation on Vita

src/render/vitagxm/SDL_render_vita_gxm.c
@isage Finish current scene when destroying the texture on Vita
Make sure that we've ended the current scene before running `sceGxmFinish` and destroying the texture. Might fix some crashes with destroyed SDL_Texture before GXM rendering is finished.
Some kind of delayed garbage collection might be a faster solution, but I guess this should work for now.
=> Finish current scene when destroying the texture on Vita

src/video/wayland/SDL_waylandmouse.c, src/video/wayland/SDL_waylandmouse.h, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandvideo.h
This patch is smaller than it looks. The only real difference is that we now load cursor themes at ShowCursor time rather than at VideoInit, because we need to check the window's scale as part of determining the cursor theme. We keep the themes in an array that gets freed at quitting time.
Fixes #4617
=> wayland: Add support for high-DPI cursors

include/SDL_stdinc.h, src/core/freebsd/SDL_evdev_kbd_freebsd.c, src/dynapi/SDL_dynapi.c, src/dynapi/SDL_dynapi_overrides.h, src/dynapi/SDL_dynapi_procs.h, src/joystick/bsd/SDL_bsdjoystick.c, src/stdlib/SDL_string.c
The implementation is based on the `make_message` function from [here](https://linux.die.net/man/3/sprintf), which should work with `snprintf` implementations that aren't fully C99 compliant.
=> Add SDL_asprintf and SDL_vasprintf

src/render/vitagxm/SDL_render_vita_gxm.c
Run `sceGxmEndScene` on `VITA_GXM_RunCommandQueue` on PS Vita
End the scene at the end of the RunCommandQueue. Eliminates the need of checking if the scene is active on texture destruction, rendertarget switching and probably some other places too.
=> End Scene on RunCommandQueue on Vita

src/events/imKStoUCS.c, src/events/imKStoUCS.h, src/video/wayland/SDL_waylandevents.c, src/video/x11/SDL_x11keyboard.c
Another Wayland patch that's a lot smaller than it seems... but I'm uneasy about one thing: @slouken, should we just put imKStoUCS.c somewhere else so both Wayland and X11 can use the same file? Where should I put it if so?
Fixes #4666.
Fixes #4642.
=> wayland: Reuse KeySymToUcs4 to replicate X11 keymap behavior

include/SDL_syswm.h, src/video/wayland/SDL_waylanddyn.h, src/video/wayland/SDL_waylandsym.h, src/video/wayland/SDL_waylandwindow.c
This PR exposes the `xdg_toplevel` object to SysWM, which, most importantly, allows SDL2 applications to set parents for the surfaces to another non-SDL2 Wayland window with a `xdg_toplevel`.
=> wayland: Expose xdg_toplevel to SysWM

src/render/vitagxm/SDL_render_vita_gxm_tools.c
Use SDL_calloc for allocation of gxm_texture on PS Vita
Use SDL_calloc instead of SDL_malloc for allocation of gxm_texture struct. In some rare cases newly created struct may contain a pointer to the main render target, which may lead to crash on texture destruction.
=> Use SDL_calloc for allocation of gxm_texture

src/video/wayland/SDL_waylandopengles.c
Some wayland compositors report the refresh rate as 0. Since we want to force a minimum refresh rate of 10 frames worth, we were dividing by the reported refresh rate, causing a divide-by-zero.
If the refresh rate is 0, instead force a frame every second if no frame callbacks are received. This value (1000ms) could be changed if that seems necessary: it's a bit longer than the 667ms you'd get with a 60fps output.
This fixes bug #4785 — I've tested it with sway and supertux2, and could reproduce the issue without this patch, and the game ran smoothly with it.
CC: @flibitijibibo for general wayland brokenness.
=> video: wayland: Support displays with a 0 refresh rate (fix #4785)

Xcode-iOS/Demos/Info.plist
Xcode 13.0 appears to require this key to be present in the Info.plist to be able to run the compiled code.
=> Xcode-iOS Demos: Add CFBundleShortVersionString to Info.plist

src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandopengles.c, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandvideo.h
Under KDE/KWin 5.22.5 with Wayland, some games can periodically get "stuck" and not render anything if vsync is enabled. Moving the mouse (or otherwise providing input) does kick it back into gear. In particular, this affects [mkxp](https://github.com/Ancurio/mkxp)-based games, such as [Imposter Factory](https://store.steampowered.com/app/1182620/Impostor_Factory/), and probably anything else which renders on a different thread from the one it pumps events on.
``wl_display_dispatch()`` will block if there are no events available, and while we try to avoid this by using ``SDL_IOReady()`` to verify there are events before calling it, there is a race condition between ``SDL_IOReady()`` and ``wl_display_dispatch()`` if multiple threads are involved.
In the case of Impostor Factory, reverting …
=> wayland: Don't let multiple threads dispatch wayland events at once

src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandopengles.c
Check the result of these against 0 explicitly, so that it's obvious
we're bailing out on failure, not success.
This is a fixup for commit 25f9e32 from pull request #4802.
=> wayland: Cleanup some SDL_TryLockMutex() calls (fixup for PR #4802)

SDL2Config.cmake
Create `SDL2::SDL2` aliased target on static-only build.
https://github.com/libsdl-org/SDL/issues/4501
=> Alias SDL2::SDL2 to SDL2::SDL2-static on static-only builds

src/video/windows/SDL_windowsevents.c
6fe6946 has been better fixed by b28ed02 or another related relative mouse mode change of @slouken in SDL 2.0.17 and as such can be reverted to reduce unneeded processing in WM_MOUSEMOVE
Existing Issue:
I originally reported this issue within #3330 (not the original bug at the top but rather if you scroll down in the conversation). After reverting https://github.com/libsdl-org/SDL/commit/6fe6946a2fceca155a6a706805c1027c3152b135 the bug still seems to be fixed in a better way now.
=> Revert `6fe6946` "Fixed relative mode mouse events stopping if you click on the title bar"

SDL2Config.cmake
"get_filename_component(SDL2_LIBDIR ${sdl2implib} PATH)" failed if sdl2implib was set from sdl2implibdbg instead of ${sdl2implibdbg}
I thought I tested this case, but apparently I didn't.
Thanks to seyuup for pointing this out in https://discourse.libsdl.org/t/how-is-sdl2-supposed-to-be-used-with-cmake/31275/14
=> Fix Debug-only builds with CMake

src/audio/paudio/SDL_paudio.c, src/audio/qsa/SDL_qsa_audio.c, src/audio/sun/SDL_sunaudio.c, src/core/unix/SDL_poll.c, src/core/unix/SDL_poll.h, src/events/SDL_events.c, src/video/wayland/SDL_waylanddatamanager.c, src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandopengles.c, src/video/x11/SDL_x11events.c
`WaitEventTimeout()` on X11 and Wayland backends use `SDL_IOReady()` which automatically retries `poll()` on `EINTR`. If someone sends a signal to our process, we'll get the signal and set `send_quit_pending` in the signal handler but never wake the waiter inside `SDL_WaitEvent()`. To fix this, avoid suppressing `EINTR` when calling `SDL_IOReady()` from our `WaitEventTimeout()` implementations.
When we get an `EINTR` error in `WaitEventTimeout()`, we'll return 1 to indicate that a new event may have been generated. This will cause the event core to call `SDL_PumpEvents()` which calls `SDL_SendPendingSignalEvents()` to generate the `SDL_QUIT` event if the signal was `SIGINT` or `SIGTERM`.
To add the additional option to `SDL_IOReady()`, I converted the second parameter to a `flags` option …
=> Fix signal handling while blocking in SDL_WaitEvent() on X11/Wayland

.gitignore, VisualC/SDL.sln, VisualC/tests/testsurround/testsurround.vcxproj, test/CMakeLists.txt, test/Makefile.in, test/README, test/testsurround.c
Adds a surround sound testing tool to verify channel layouts, swizzling logic, etc. using the new `SDL_GetAudioDeviceSpec()` function added in SDL 2.0.16.
This is a basic surround sound testing tool loosely based on `loopwave.c`. It plays a 5 second tone on each audio channel of each audio device. There's currently no support for manually selecting audio device or channel count, changing channel test times, or adjusting the frequency of the tone.
=> testsurround: Add surround sound channel tester

.github/workflows/main.yml, CMakeLists.txt, test/CMakeLists.txt
This PR enables `SDL_TEST=ON` in CI and fixes a couple of build errors encountered during the test build.
The interesting changes in this PR are the CMake changes I had to make to get `SDL_TEST=ON` build to work. I'd appreciate a review from someone who can sanity check the CMake stuff before merging.
=> Fix CMake test build issues and start building tests in CI

include/SDL_timer.h, src/dynapi/SDL_dynapi_overrides.h, src/dynapi/SDL_dynapi_procs.h, src/timer/SDL_timer.c, src/timer/dummy/SDL_systimer.c, src/timer/haiku/SDL_systimer.c, src/timer/os2/SDL_systimer.c, src/timer/psp/SDL_systimer.c, src/timer/unix/SDL_systimer.c, src/timer/vita/SDL_systimer.c, src/timer/windows/SDL_systimer.c, test/testtimer.c
Note that this removes the timeGetTime() fallback on Windows; it is a
32-bit counter and SDL2 should never choose to use it, as it only is needed
if QueryPerformanceCounter() isn't available, and QPC is _always_ available
on Windows XP and later.
OS/2 has a similar situation, but since it isn't clear to me that similar
promises can be made about DosTmrQueryTime() even in modern times, I decided
to leave the fallback in, with some heroic measures added to try to provide a
true 64-bit tick counter despite the 49-day wraparound. That approach can
migrate to Windows too, if we discover some truly broken install that doesn't
have QPC and still depends on timeGetTime().
Fixes #4870.
CC @sezero, who might want to make sure I didn't screw up the OS/2 patch.
=> timer: Added SDL_GetTicks64(), for a timer that doesn't wrap every ~49 days.

src/timer/psp/SDL_systimer.c, src/timer/unix/SDL_systimer.c
Fixes the timeval/timespec delta calcuations in unix and psp SDL_GetTicks64 to avoid sign mismatches.
As mentioned in https://github.com/libsdl-org/SDL/pull/4872#issuecomment-957073495, the move to SDL_GetTicks64 added Uint64 casts to the usec/nsec deltas, which is incorrect as those values can be negative, causing incorrect tick count calculation.
=> Fix timeval/timespec delta calculations

test/testtimer.c
Add a one second long loop that checks that time deltas are not totally unreasonable.
Mention #4872
=> testtimer: Add basic sanity check for SDL_GetTicks*()

src/misc/macosx/SDL_sysurl.m
Hello,
This MR updates macOS implementation of SDL_OpenURL so that we can also open paths like "/Users/Bob/Documents".
Current implementation of macOS SDL_OpenURL can only open URLs such as `https://www.libsdl.org`, `scheme://something` or `file:///Users/Bob/Documents`.
However, some libraries for Mac (for example, PHYSFS) return Unix paths like `/Users/Bob/Documents`. A simple concatenation `"file://" + path` cannot work be cause we can end up with an invalid URL, for example when the path has a space in it (we would end up with `file:///Users/Bob/Library/Application Support/MyApp`).
In this MR, if the url cannot be opened, we try to open the path using another method: creating the NSURL with "fileURLWithPath" (which is [available since macOS …
=> SDL_OpenURL (macOS): try to open path if the url cannot be opened

src/joystick/windows/SDL_windows_gaming_input.c
This is a workaround to catch the case where a delayed WGI device add callback leads to a crash due to having uninitialized the joystick subsystem.
Ideally we would be able to flush these callbacks prior to returning from `WGI_JoystickQuit()`, but I couldn't find a way that worked reliably. Even calling `SDL_PumpEvents()` after unregistering the callback doesn't seem to be enough.
If nobody comes up with anything smarter than this before 2.0.18, we should probably get this in.
#4915
=> WGI: Add workaround for delayed callbacks after WGI_JoystickQuit()

include/SDL_test_common.h, src/test/SDL_test_common.c, src/test/SDL_test_font.c, test/testwm2.c
Adds a clickable mode list to testwm2 - clicking a mode calls SDL_SetWindowDisplayMode. 
This will enable testing 2 scenarios that weren't really possible with the SDLTest apps:
- going from windowed to a specific fullscreen display mode
- going from one fullscreen mode to another
Also draws a few more bits of information in testwm2 (video driver name, renderer name, window's current display mode).
The first commit adjusts `SDLTest_DrawString` to support drawing on more than one SDL_Renderer. Previously, if you launched `testwm2 --windows 2`, only one of the windows would get the on-screen info text.
=> testwm2: Add clickable mode list for testing SDL_SetWindowDisplayMode

src/stdlib/SDL_string.c
This patch was from @Markvy (thanks!).
Fixes #4795.
=> stdlib: SDL_snprintf now adds decimal places for ("%f", 0.0).

include/SDL_gamecontroller.h, src/joystick/iphoneos/SDL_mfijoystick.m
=> Support returning sfSymbolsName for game controller controls on Apple platforms

android-project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
"If your app targets Android 12, you must specify the mutability of each PendingIntent object that your app creates. This additional requirement improves your app's security."
"Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if  some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles."
https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability
FLAG_IMMUTABLE was added in API 23. 
https://developer.android.com/reference/android/app/PendingIntent#FLAG_IMMUTABLE
Using API 30 would also fix the Android 12 issue. Alternatively if PendingIntents should be mutable you could change it to "FLAG_MUTABLE". Prior to Android 12 PendingsIntents were mutable by default.
From my testing on …
=> If Android version >= API 23 PendingIntent.FLAGIMMUTABLE

src/joystick/windows/SDL_windows_gaming_input.c
The Xbox One driver stack doesn't propagate the VID/PID down to the HID devices that end up in the GetRawInputDeviceList() output. This means we end up matching against the wrong VID/PID and can't properly exclude Xbox One controllers from WGI.
Fortunately, it is possible to walk back up the device tree to find the parent with the matching VID/PID.
#4914
=> WGI: Fix SDL_IsXInputDevice() for Xbox One controllers

src/video/windows/SDL_windowsmouse.c
It turns out the `LR_COPYDELETEORG` flag introduced in #4927 would cause the cursor to disappear. This PR fixes the problem. I tested it on Windows 10 19043.1288.
=> SDL_windowsmouse.c: Remove LR_COPYDELETEORG flag

src/video/windows/SDL_windowskeyboard.c
This PR uses the better Win32 API, which gives the IME more information on how to properly position the candidate window.
The attached images speak for themselves.
Setting both `ptCurrentPos` and `rcArea` is required, as without the `ptCurrentPos` the window will appear in the wrong spot if it's close to display edge.
Microsoft docs for: [CANDIDATEFORM](https://docs.microsoft.com/en-us/windows/win32/api/imm/ns-imm-candidateform) and [COMPOSITIONFORM](https://docs.microsoft.com/en-us/windows/win32/api/imm/ns-imm-compositionform).
For reference, I'm setting the `rect` to roughly the red box here:
Normal look |  IME close to display edge
:--:|:--:
Normal look |  IME close to display edge
:--:|:--:
None.
=> Properly position the IME window(s) on Windows when using `SDL_SetTextInputRect`

include/SDL_stdinc.h, include/begin_code.h, src/audio/SDL_wave.c, src/render/software/SDL_draw.h, src/stdlib/SDL_iconv.c, src/stdlib/SDL_string.c, src/video/SDL_blit.h, src/video/SDL_fillrect.c, src/video/SDL_pixels.c, src/video/directfb/SDL_DirectFB_WM.c, src/video/directfb/SDL_DirectFB_events.c, src/video/windows/SDL_windowsevents.c, test/controllermap.c, test/testgamecontroller.c, test/testjoystick.c
Case fallthrough warnings can be suppressed using the `__fallthrough__` compiler attribute. Unfortunately, not all compilers have this attribute, or even have `__has_attribute` to check if they have the `__fallthrough__` attribute. `[[fallthrough]]` is also available in C++17 and the next C2x, but not everyone uses C++17 or C2x.
So define the `SDL_FALLTHROUGH` macro to deal with those problems - if we are using C++17 or C2x, it expands to `[[fallthrough]]`; else if the compiler has `__has_attribute` and has the `__fallthrough__` attribute, then it expands to `__attribute__((__fallthrough__))`; else it expands to an empty statement, with a `/* fallthrough */` comment (it's a `do {} while (0)` statement, because users of this macro need to use a semicolon, because `[[fallthrough]]` and …
=> Add and use `SDL_FALLTHROUGH` for fallthroughs

include/SDL_stdinc.h, include/begin_code.h, src/audio/SDL_wave.c, src/render/software/SDL_draw.h, src/stdlib/SDL_iconv.c, src/stdlib/SDL_string.c, src/video/SDL_blit.h, src/video/SDL_fillrect.c, src/video/SDL_pixels.c, src/video/directfb/SDL_DirectFB_WM.c, src/video/directfb/SDL_DirectFB_events.c, src/video/windows/SDL_windowsevents.c, test/controllermap.c, test/testgamecontroller.c, test/testjoystick.c
This is a re-do of #4791, but now we fall back to using the `/* fallthrough */` comment if the compiler is too old (GCC is less than 7, or Clang is less than 10), to work around a problem where using a `__attribute__` as a sole statement warns about a declaration not declaring anything.
=> Add and use `SDL_FALLTHROUGH` for fallthroughs (take 2)

src/hidapi/SDL_hidapi.c
Body of `SDL_hid_exit` is never executed.
None
=> Fix refcounting in SDL_hid_exit

src/video/cocoa/SDL_cocoawindow.m
macOS 10.6 has some touch NSEvents which do not have a subtype
(Begin/EndGesture, Magnify, Rotate, Swipe) and cause an uncaught
exception which triggers SIGABRT and the program exits.
As it is, none of the macOS 10.6 touch events are detected as a
trackpad (including Gesture due to using different subtypes).
Described in more detail in issue #4960.
=> cocoa: Fix abort on touch event types without a subtype

android-project/app/src/main/AndroidManifest.xml
Limit WRITE_EXTERNAL_STORAGE permission to Android SDK 22 and below
Direct access to the external storage is no longer allowed as of SDK 30. But on older version of Android you will still need WRITE_EXTERNAL_STORAGE in order to request the Download Manager to download files to your external file folder.
=> [Android] Limit WRITE_EXTERNAL_STORAGE to SDK 22-

src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandvideo.h
Tested and known to work on Plasma, just needs a second pair of eyes to verify correctness. Functionally it's the same as before, but once we've initialized the display we write directly to the "real" VideoDisplay instead of the placeholder we use when starting up the video subsystem, with the addition of an orientation event at the end of the `done` event.
Fixes #4878 but may actually fix another bug where the Wayland output transform value was interpreted as bitflags and not a linear enum.
=> wayland: Add support for SDL_DisplayOrientation

CMakeLists.txt, cmake/sdlchecks.cmake, include/SDL_config.h.cmake
I found these by diffing SDL_config.h generated from CMake vs the configure script. I would have just checked this in, but I wanted to get confirmation that none of these were intentional deviations from Autotools.
Changes:
- `SDL_CLOCK_GETTIME` now defaults to ON for Unix to match autotools build
- Add detection of `float.h` and `Xdbe`
- Fix detection of `pthread_setname_np()` (requires `_GNU_SOURCE` defined)
- Move `SDL_USE_IME` definition into `SDL_config.h.cmake`
=> cmake: Sync build config options with autotools

src/joystick/SDL_joystick.c, src/joystick/windows/SDL_rawinputjoystick.c
The RawInput joystick driver depends on a window and notifications registered by the Windows joystick driver. On joystick init, we ensure that the Windows joystick driver is initialized after RawInput to prevent invoking RawInput before it's ready. However, joystick quit happens in the same order as initialization. This creates a race condition where the Windows joystick driver can still invoke `RAWINPUT_WindowProc()` during/after `RAWINPUT_JoystickQuit()` has been called. There are also similar race conditions in WGI, XInput, and RawInput related to `DevicePresent()` functions being called after their respective `JoystickQuit()` functions that are all resolved by reversing the order of quitting the joystick drivers.
With deinitialization in reverse order, we can now simplify the locking …
=> Fix "Passed a NULL mutex" error in RawInput joystick driver

src/render/direct3d11/SDL_render_d3d11.c
Possible fix issue: https://github.com/libsdl-org/SDL/issues/4987
I'm not sure what to do the check in this way, perhaps it is worth checking only windows 7.
P.S. I don't know how the code would behave if it is not installed [Platform Update for Windows 7](https://docs.microsoft.com/en-us/windows/win32/direct3darticles/platform-update-for-windows-7). Possible that he would have worked without this PR.
=> Fixed d3d11 renderer creation

src/hidapi/SDL_hidapi.c
Valgrind report reachable blocks when quitting an application.
It seems  UDEV isn't fully released.
```
==46884== 328 bytes in 1 blocks are still reachable in loss record 174 of 225
==46884==    at 0x4843839: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==46884==    by 0x8B21384: ??? (in /usr/lib/x86_64-linux-gnu/libudev.so.1.7.1)
==46884==    by 0x8B11EA7: udev_monitor_new_from_netlink (in /usr/lib/x86_64-linux-gnu/libudev.so.1.7.1)
==46884==    by 0x4B17927: SDL_UDEV_Init (SDL_udev.c:141)
==46884==    by 0x4B189EB: SDL_UDEV_GetUdevSyms (SDL_udev.c:569)
==46884==    by 0x48DEBF6: SDL_hid_init_REAL (SDL_hidapi.c:1065)
==46884==    by 0x4B0C41F: HIDAPI_JoystickInit (SDL_hidapijoystick.c:311)
==46884==    by 0x48E50F9: SDL_JoystickInit (SDL_joystick.c:247)
==46884== …
```
=> Release UDEV ressources

src/render/opengl/SDL_render_gl.c
Without this, moving the window changes the viewport and causes contents to render stretched.
Fixes #1504
=> SDL_render_gl.c: GL_RunCommandQueue: always set viewport_dirty on macOS

src/joystick/windows/SDL_rawinputjoystick.c
`RAWINPUT_JoystickGetCapabilities()` always returns 0 instead of actual joystick capabilities.
None.
=> Return capabitlities from RawInput joystick

src/haptic/android/SDL_syshaptic.c
@slouken okay for 2.0.18?
Fixes #5018
=> haptic: Fix SDL_MouseIsHaptic() always return SDL_TRUE on Android

test/testgamecontroller.c
Stabilizing the analog stick events for Sixaxis, & Dualshock controllers.
Fixing an issue I had here: https://discourse.libsdl.org/t/playstation-controllers-analog-sticks-dont-work-properly-on-sdl2/33688/2. At the very least the game controller test program should work with these controllers as expected.
=>  Added a hint for joysticks on Linux

src/hidapi/SDL_hidapi.c
Matters e.g. for windows, and good for correctness.
Suggest for 2.0.18
=> hidapi: mark libusb function pointers with LIBUSB_CALL.

src/video/x11/SDL_x11messagebox.c, src/video/x11/SDL_x11sym.h, src/video/x11/SDL_x11video.c, src/video/x11/SDL_x11window.c, src/video/x11/SDL_x11window.h
Closes #4924.
Based on patches of the past, such as this work by James Cloos in July 2010: https://github.com/exg/rxvt-unicode/commit/d7d98751b7385416ad1694b5f1fde6c312ba20d5, as well as code comments in the Perl module X11::Protocol::WM (https://metacpan.org/pod/X11::Protocol::WM) and even the code to Xlib itself, which taught me that we should never have been using `XStoreName`, all it does is call `XChangeProperty`, hardcoded to `XA_STRING`!
What can I say, when the task is old school, the sources are too 😂
cc @morgant @slouken 
Sorry for any problems caused to y'all's release cycle, I would've never caused any on purpose. I still believe I'm right per the spec (as Qt once believed in 2014), but seven years later is still too late. I wonder who will be trying again in 2028? Not me …
=> Add back X11 legacy WM_NAME encodings

src/video/x11/SDL_x11window.c
This fixes a compile warning — and possible invalid memory read — introduced in 9c03d255 ("Add back X11 legacy WM_NAME encodings"), which was part of PR #5029, fixing Bug #4924.
The issue is with one of the added warnings in ``X11_GetWindowTitle()``. Basically, the "title" variable passed to SDL_LogError() hasn't been initialised yet: we could pass propdata in directly, but it's better to move the SDL_LogError() call until after title is set, IMHO.
This fixes the following warning from gcc (SUSE Linux) 11.2.1:
```
In file included from /home/david/Development/SDL/src/video/x11/../../SDL_internal.h:45,
from /home/david/Development/SDL/src/video/x11/SDL_x11window.c:21:
/home/david/Development/SDL/src/video/x11/SDL_x11window.c: In function 'X11_GetWindowTitle': …
```
=> video: x11: Fix an invalid SDL_LogError() call

src/video/windows/SDL_windowsevents.c
The Windows key up event loss workaround added in 3b85e3fdfce01c528a6ebf9ac537bdc106ba4963 breaks holding down the Windows key while keyboard grab is active. The fix is simply not to do the workaround when keyboard grab is enabled (since keyboard grab ensures we don't lose the key up event in the first place).
When our keyboard grab hook is installed, GetKeyState() will return 0 for the GUI keys even when they are pressed. This leads to spurious key up events when holding down the GUI keys and the inability to use any key combos involving those modifier keys.
Holding Windows key down in `testgl2 --keyboard-grab` without the fix:
```
INFO: SDL EVENT: SDL_KEYDOWN (timestamp=3000 windowid=1 state=pressed repeat=false scancode=227 keycode=1073742051 mod=1024)
INFO: SDL EVENT: SDL_KEYUP …
```
=> windows: Fix GUI key state when grabbing the keyboard

docs/README-macos.md
Otherwise, the API documentation will encode the home directory of the
user or autobuilder that built SDL, instead of telling the user to use
the literal string $(HOME) as intended.
See also <https://github.com/doxygen/doxygen/issues/7073>.
=> docs: Don't let Doxygen expand HOME environment variable

src/video/kmsdrm/SDL_kmsdrmmouse.c, src/video/kmsdrm/SDL_kmsdrmsym.h, src/video/kmsdrm/SDL_kmsdrmvideo.c, src/video/kmsdrm/SDL_kmsdrmvideo.h
`gbm_device_get_fd()` in at least some libmali versions duplicate handle.
See https://discourse.libsdl.org/t/handle-leak-in-sdl-kmsdrmmouse-c/33750/5 for details!
Other implementations do not do duplication. To prevent handle leak save drm_fd in `SDL_DisplayData` structure.
This PR should provide graphics libraries agnostic fix. Please review change in `KMSDRM_CreateCursorBO()` thoroughly - I am not sure whether the handle saved in `dispdata->cursor_bo_drm_fd` always will be the correct one!
Currently on devices with libmali versions duplicating the handle there is a handle leak. At least in some situations it leads to major issues (e.g. https://github.com/batocera-linux/batocera.linux/issues/5005 - this particular issue was solved by …
=> workaround for libmali gbm_device_get_fd()

src/render/SDL_render.c, src/render/SDL_sysrender.h, src/render/direct3d11/SDL_render_d3d11.c, src/render/software/SDL_render_sw.c
Before some future modification to viewport  / cliprect, some "simplication".
Don't use "renderer->viewport" in back-ends but use the one that comes from SETVIEWPORT cmd
- tested for the software renderer.
- not tested for D3D11
=> Don't use "renderer->viewport" in back-ends

src/core/linux/SDL_fcitx.c
The integer in the message should be 64bit instead of 32.
=> Fix the wrong int size for fcitx capability.

WhatsNew.txt
Adds documentation for CMake change in 7850d0cf6fa1b2e7d8999d0506bb907ae071f497 to release notes for 2.0.18.
#5057
=> Update 2.0.18 release notes with CMake prefix change

src/audio/wasapi/SDL_wasapi.c
IAudioClient::SetEventHandle  Parameter eventHandle should not be NULL
After call IAudioClient_SetEventHandle(this->hidden->client, NULL);
We will receive such an error message
"avcore\audiocore\client\audioclient\audioclientcore.cpp(1869)\AUDIOSES.DLL!00007FF8CD2E5FD4: (caller: 00007FF86CA53F12) ReturnHr(1) tid(31a8) 80070057 The parameter is incorrect."
https://docs.microsoft.com/en-us/windows/win32/api/audioclient/nf-audioclient-iaudioclient-seteventhandle
<html><body>
<h2 id="parameters" class="heading-anchor">Parameters</h2>
<p><code>[in] eventHandle</code></p>
<p>The event handle.</p>
<h2 id="return-value" class="heading-anchor"><a class="anchor-link docon docon-link" href="https://docs.microsoft.com/en-us/windows/win32/api/audioclient/nf-audioclient-iaudioclient-seteventhandle#retur …
=> IAudioClient::SetEventHandle  Parameter eventHandle should not be NULL

src/video/wayland/SDL_waylandwindow.c
tl;dr: Wayland fullscreen is broken under KDE Plasma 5.23.4, and crashes with the message:
```
xdg_surface@28: error -1: invalid window geometry size (0x0)
```
The xdg_shell spec seems to state[1] that ``xdg_toplevel_configure`` events can always provide a 0×0 width/height to signal that the compositor doesn't care. SDL previously assumed the provided width/height was always valid for fullscreen windows, and so applied it as-is.
This broke SDL applications on KDE/KWin 5.23, which now sends 0×0 configure events (and, in 5.23.3, 1×1 events for some reason), breaking all SDL applications in fullscreen[2], when ``SDL_VIDEODRIVER=wayland``
See also the mention of the 1×1 window issue in https://github.com/libsdl-org/SDL/pull/4306#issuecomment-976272935
[1]: …
=> [Wayland] Handle 0×0 xdg_toplevel_configure in fullscreen

include/SDL_main.h, src/main/psp/SDL_psp_main.c
SDL2main was not working for PSP, because it wasn't being activated and
it wasn't unsetting the main. Besides that a debug screen being started
was causing issues with joystick input and the sceKernelExitGame call
is no longer needed with the current PSPDEV SDK.
=> Fix SDL2main on PSP

src/video/cocoa/SDL_cocoamouse.m
Rounding the scroll deltas from trackpads causes jerky scrolling behavior by artificially amplifying the effects of very small scroll movements.
We should only round events from devices with discrete scroll wheels, because we know the smallest unit of movement there is a single tick.
The Cocoa mouse wheel code could still use some more love from someone with the time and expertise to poke around with a bunch of different input devices. I took a look at Qt, wxWidgets, GLFW, and QEMU for examples of how they were handling these scroll events and every one of them did it a little differently than the others. Some capped discrete scroll events at 1 tick, some scaled deltas by various factors determined by "feel", using `NSEvent.deltaY` vs. `NSEvent.scrollingDeltaY` vs. `NSEvent.deviceDeltaY`, …
=> cocoa: Don't round scroll deltas from trackpads

src/joystick/SDL_gamecontrollerdb.h, src/video/psp/SDL_pspvideo.c
- Add missing mapping
- Make sure the only window has the keyboard focus (so no `SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS` is needed)
This is a commit in the downstream PSP SDL2 which makes the GameController API work on the PSP. It was made by @sergiou87
=> Fix SDL_GameController API for PSP

src/render/psp/SDL_render_psp.c
At the moment the PSP version of SDL2 has issues rendering textures bigger than 64x64. This also affects fonts used with SDL2_ttf.
This PR backports a portion of a commit made by @stdgregwar in the downstream SDL2 port for PSP which addresses these issues. It's not a complete fix for all rendering related issues, but it gets us a long way there.
Here is an example where you see the background texture and the fonts not rendering correctly:
With this change the same screen looks like this:
=> Improve PSP renderer

src/video/wayland/SDL_waylandevents.c
When using xkb to swap modifier keys on Wayland, SDL did not correctly translate scancodes into keycodes. This pull-request attempts to fix that.
This bug seems very similar to #3471 which was closed in #4303. However, trying to checkout that particular commit results in a broken `checkkeys` app on Sway (window is not shown) so I'm unable to test if the bug was still reproducible at that point.
1. Swap the physical caps-lock and left-control key on the keyboard using XKB.
This step is compositor specific, but on `sway` this can be configured using the `XKB_DEFAULT_OPTIONS=ctrl:swapcaps` environment variable (this needs to be set before starting the compositor).
2. Run the `test/checkkeys` app and press/release once the *physical* caps-lock key (which has been remapped to left-control). …
=> wayland: fix keycodes of swapped xkb modifier keys

src/video/cocoa/SDL_cocoaopengles.m, src/video/windows/SDL_windowsopengles.c
Same as #4178 but for Cocoa (Mac). When using GLES provided by Google ANGLE, this assertion happens, though SDL properly functions when the line the assertion line is ignored.
#4177
=> Ignore a false alarm in Cocoa_GLES_SetupWindow

src/video/x11/SDL_x11framebuffer.c
If the X server's byte order is different from the client, things might display in the wrong colour.
Apparently we can just set the byte_order field to the client's byte order, and the X server will adjust everything automatically:
https://xorg.freedesktop.narkive.com/GbSD1aPq/ximage-s-byte-order-field
=> video: x11: Set XImage's byte_order field (fix #5081)

src/audio/sndio/SDL_sndioaudio.c
With the 2.0.18 update on OpenBSD, the sndio audio backend runs into 2 assertion failures on start of several applications. These include ppsspp, scummvm, hashlink, teeworlds. 
```
WARN:                                                                                     
Assertion failure at SDL_AudioDetectDevices_Default (/usr/ports/pobj/sdl2-2.0.18/SDL2-2.0.
18/src/audio/SDL_audio.c:229), triggered 1 time:                                            'current_audio.impl.OnlyHasDefaultOutputDevice'                                         
Abort/Break/Retry/Ignore/AlwaysIgnore? [abriA] : A                                        
WARN:                                                                                     
Assertion failure at SDL_AudioDetectDevices_Default …
```
=> fix assertion failure in sndio audio caused by the recent hotplugging support

src/render/direct3d11/SDL_render_d3d11.c, src/render/direct3d11/SDL_shaders_d3d11.c
This changes the D3D11 renderer's common vertex struct to replace float color components with unorm8, and to eliminate an unused z position component. It makes the d3d11 backend a bit more performant and a little simpler.
This is one (small) part of the cleanup mentioned in https://github.com/libsdl-org/SDL/issues/5093#issuecomment-992872412.
=> d3d11 renderer: reduce vertex bandwidth and calculations.

include/SDL_pixels.h, src/render/SDL_render.c, src/render/SDL_sysrender.h, src/render/direct3d/SDL_render_d3d.c, src/render/direct3d11/SDL_render_d3d11.c, src/render/metal/SDL_render_metal.m, src/render/opengl/SDL_render_gl.c, src/render/opengles/SDL_render_gles.c, src/render/opengles2/SDL_render_gles2.c, src/render/psp/SDL_render_psp.c, src/render/software/SDL_render_sw.c, src/render/vitagxm/SDL_render_vita_gxm.c, src/render/vitagxm/SDL_render_vita_gxm_tools.c, src/render/vitagxm/SDL_render_vita_gxm_types.h, src/video/directfb/SDL_DirectFB_render.c
This changes SDL_Render backend code to match the higher level SDL_RenderGeometry/QueueGeometry code's use of `SDL_Color *` instead of `int *`.
#5093 and #5087 deal with this topic.
=> Renderer backends use SDL_Color instead of int for geometry colors.

CMakeLists.txt
* Disable (comment-out) arm simd/neon blitters until #4484 fixed.
* Add missing dependency for pvr gles backend.
=> Vita: disable arm asm blitters and add missing pvr dep

src/render/psp/SDL_render_psp.c
At the moment artifacts are visible on textures after they have just been changed on the PSP. This persist for a few frames. This PR fixes that.
Before this fix:
After this fix:
The image below is what this example should look like. It's a simple test to see if SDL can scale images or show parts of them on the PSP. That's why it looks a bit weird.
=> Fix PSP texure artifacts

src/render/SDL_render.c, src/render/SDL_sysrender.h, src/render/opengles2/SDL_render_gles2.c
Stride computation and Queuing data are cleaner
This avoid doing `*((SDL_Color *)verts++) = col_;` which triggers an aliasing warning
=> GLES2 cast with SDL_Vertex and SDL_VertexSolid

src/thread/psp/SDL_systhread.c
This PR fixes wrong values in the thread priorities for `PSP`
=> [PSP] Fix wrong value for thread priorities following official PSP Docs

src/video/SDL_video.c
Quit the events, keyboard, mouse and touch systems if `SDL_VideoInit` fails due to not being able to create a driver.
See #5000
=> Make SDL_VideoInit cleanup when errors occur before video driver creation.

src/render/opengl/SDL_glfuncs.h, src/render/opengl/SDL_render_gl.c
With this change the OpenGL renderer backend uses glDrawArrays instead of glBegin/glEnd, and its internal vertex arrays use 32 bit (8 bit per component) colors instead of 128 bit (32 bit per component) colors for improved performance and less memory usage.
This isn't very important for short draws, but ones with a lot of vertices have overhead in glBegin and with the large float color values which this change reduces. The color values were already being converted from 8 bits per component to floats before being sent to GL, so sending them natively as 8 bit per component values eliminates some conversion code without losing any precision.
Very short draws might get a little slower than before in the GL backend (because drivers tend to optimize glBegin/glEnd for those cases), but the …
=> GL renderer uses glDrawArrays instead of glBegin/glEnd.

src/video/cocoa/SDL_cocoamodes.m
Since backingScaleFactor is "locked" to 1.0 / 2.0 / 3.0, it does not reflect the actual resolution scaling.
E.g. on Intel MBP 16", the native resolution is 3072x1920 with 226 dpi.
With the current implementation, the DPI is fluctuating:
For scaled resolution 1792x1120, SDL_GetDisplayDPI returns ddpi=264.279755
For scaled resolution 2048x1280, SDL_GetDisplayDPI returns ddpi=302.000000
For scaled resolution 3072x1920, SDL_GetDisplayDPI returns ddpi=226.279556
The proposed DPI calculation implementation was first tested in [Flycast #33](https://github.com/flyinghead/flycast/pull/33) since Jan 2020 and improved in [Flycast #181](https://github.com/flyinghead/flycast/pull/181) on Feb 2021.
Actual implementation in Flycast:
https://github.com/vkedwardli/flycast/blob/b56c5b1c51657ab7335dcef4eac52 …
=> macOS: Calculate correct DPI by not using backingScaleFactor

src/video/cocoa/SDL_cocoawindow.m
Fixes #5111 by initializing `pendingWindowWarpX`/`Y` to INT_MAX on construction.
When the titlebar is first clicked, a call tree from `Cocoa_HandleTitleButtonEvent` -> `clearFocusClickPending` -> `onMovingOrFocusClickPendingStateCleared` -> `mouse->WarpMouseGlobal(pendingWindowWarpX, pendingWindowWarpY)` is triggered.
I'm not really 100% on what the purpose of `pendingWindowWarpX`/`Y` is or if there's some deeper issue that should have prevented the `WarpMouseGlobal` call from happening in the first place, but I think it's sensible to make sure that any mouse warps have to be explicitly asked for post-construction.
#5111
=> Fix macOS cursor jumping to corner on first titlebar click

src/audio/aaudio/SDL_aaudio.h
Adds `stdbool.h` header to prevent build error with NDK 21d.
Currently with NDK 21d I am hitting 
```
In file included from _deps/sdl2_content-src/src/audio/aaudio/SDL_aaudio.c:29:
In file included from _deps/sdl2_content-src/src/audio/aaudio/SDL_aaudio.h:27:
/opt/android-sdk-linux/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/aaudio/AAudio.h:809:9: error: unknown type name 'bool'
bool privacySensitive) __INTRODUCED_IN(30);
^
/opt/android-sdk-linux/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/aaudio/AAudio.h:1527:12: error: unknown type name 'bool'
AAUDIO_API bool AAudioStream_isPrivacySensitive(AAudioStream* stream)
```
This appears to be a bug in NDK itself. It's currently possible to workaround by adding the header here in this …
=> Android: fixes build NDK 21d

src/video/x11/SDL_x11events.c
Removes a (seemingly) unreachable return path.
`_this` is the `SDL_VideoDevice`, as initialized in [`X11_CreateDevice`](https://github.com/libsdl-org/SDL/blob/d0de4c625ad26ef5401665ca26b5f2c0fb76e91b/src/video/x11/SDL_x11video.c#L152), which always initializes the `driverdata` field to non-`NULL`. It is also not reset to `NULL` in [X11_DeleteDevice](https://github.com/libsdl-org/SDL/blob/d0de4c625ad26ef5401665ca26b5f2c0fb76e91b/src/video/x11/SDL_x11video.c#L99).
Thus, this code path seems unreachable to me.
The return value in this code path is also wrong: It should be negative to indicate that waiting for the timeout failed.
Otherwise [`SDL_WaitEventTimeout`](https://github.com/libsdl-org/SDL/blob/d0de4c625ad26ef5401665ca26b5f2c0fb76e91b/src/events/SDL_events.c#L984) would incorrectly …
=> X11_WaitEventTimeout: remove unreachable return

.github/workflows/psp.yaml
The tests can now build for PSP. This PR makes them build automatically in the Github action for it.
This is related to #5168
=> Build tests for PSP in CI

CMakeLists.txt
CMake doesn't define the "/MP" compile-option by default, and doing so allows projects to be built in parallel under Visual Studio.
=> Under MSVC, build project-sources in parallel.

src/joystick/SDL_joystick.c, src/joystick/windows/SDL_dinputjoystick.c
WGI's `IEventHandler_CRawGameControllerVtbl_InvokeAdded()` callback calls `SDL_DINPUT_JoystickPresent()` but DInput is not initialized until after WGI. This leaves a window where WGI can invoke DInput while `dinput == NULL`, causing the application to crash. Fix this by initializing WGI after DInput (and the joystick core will deinitialize them in reverse order).
While I was looking at this, I also found that `dinput == NULL` could happen if `SDL_DINPUT_JoystickInit()` failed, so fix that too.
I have no idea what conditions cause this race to manifest so reliably, but it seems to happen every time for one Moonlight user.
Downstream issue: https://github.com/moonlight-stream/moonlight-qt/issues/700
=> Fix crash in SDL_DINPUT_JoystickPresent()

src/filesystem/psp/SDL_sysfilesystem.c
At the moment GetPrefPath does work on the PSP, but only if org is set. This resolves that with the same workaround found in the Vita port.
This is the output of testfilesystem on PSP with this change:
```
host0:/sdl-testfilesystem/> ./testfilesystem.prx 
Load/Start host0:/sdl-testfilesystem/testfilesystem.prx UID: 0x04290A7D Name: SDL App
host0:/sdl-testfilesystem/> INFO: base path: 'host0:/sdl-testfilesystem/'
INFO: pref path: 'host0:/sdl-testfilesystem//libsdl/testfilesystem/'
INFO: pref path: 'host0:/sdl-testfilesystem//testfilesystem/'
```
Before this change it would crash.
=> [PSP] Make sure GetPrefPath also works without org

test/CMakeLists.txt
Some tests do not need to be run on PSP, because they test features the PSP does not have. There were also some tests which were missing from NEEDS_RESOURCES and were reporting errors on PSP because of it.
I think it's useful that all tests are build for PSP, but they do not all need to be packaged in EBOOT.PBP files to allow them to be launched on PSP. This PR makes this not happen for a couple of test which are clearly not useful for the PSP. They are the following:
- checkkeys (requires keyboard support)
- checkkeysthread (requires keyboard support)
- testcustomcursor (requires mouse support)
- dropfile(requires drag and drop support)
- testgesture (requires touch pad support)
- testgles (requires OpenGL ES support)
- testgles2 (requires OpenGL ES support)
- testhaptic (requires haptic …
=> Don't make eboot files for all test on psp

src/audio/psp/SDL_pspaudio.c
With this PR we are allowing PSP to reproduce audios with a different frequency than `44100` as it was previously hardcoded.
=> [PSP] Improve Audio Support

src/render/psp/SDL_render_psp.c, src/video/psp/SDL_pspvideo.c
Add support for the following features in the PSP port:
- Rendering to a target texture
- Storing render target in system memory if there is not enough space in vram
- 16 bit color mode
- Color and alpha modulation
This cherry picks all the commit from a PR in the downstream PSP SDL2 port which were not yet upstreamed: https://github.com/joel16/SDL2/pull/5
I also made sure to clean it up a little bit, make it work with cmake and tested it.
It still has some issues when rendering to a texture. There is some minor artifacting found when rendering to a texture if the texture is deleted before the screen is refreshed and rendering to texture is still a bit slow, but I do think it's worth merging. Without these changes trying to render to a texture results in a black screen. We are still …
=> Improve rendering on PSP

test/CMakeLists.txt
Since offscreen rendering is not supported on the PSP, this test does not to be build into an eboot.
=> Don't make psp eboot for testoffscreen

src/events/SDL_events.c
We don't want to catch explicit `SDL_PumpEvents()` calls by the application with our polling check to avoid stale data. If the call to `SDL_PumpEvents()` produced no events, there will be a sentinel sitting in the queue that will cause `SDL_PollEvent()` to immediately return 0 next time it is called. It also causes the application's next `while (SDL_PollEvent(&evt))` loop to only return events from that last manual call to `SDL_PumpEvents()`, even if it occurred quite some time ago. That's probably not the behavior the application wants.
Our `SDL_WaitEventTimeout()` implementation avoids this issue by always popping an event after calling `SDL_PumpEvents()`. This will remove the new sentinel if we didn't get any new events.
=> events: Only add sentinels for pumping done inside SDL_WaitEventTimeout()

CMakeLists.txt, SDL2Config.cmake
This makes it so that the generated targets are not interdependent,
which allows Linux distributions to split libraries into the
appropriate subpackages as needed.
Fixes #4553
=> cmake: Split SDL2-static and SDL2main into their own target exports

src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandevents_c.h
This fixes two bugs related to handling of key repeats (i.e. sequences of key presses generated by pressing and holding a key)  on Wayland.
One is related to the handling of an overflow on a 32-bit ticks counter (could result in either a very high number of iterations or an infinite loop if a key repeat event happens near the ~49 days `SDL_GetTicks` overflow) and the other fixes a bug where spurious repeat key presses can be generated if the application is not calling `SDL_PumpEvents` for some seconds.
Each fix is in a separate commit, plus one refactorization commit as groundwork for one of the fixes.
1.  **wayland: Avoid infinite loop in keyboard_repeat_handle**
If `repeat_info->next_repeat_ms` overflows, many key presses will be generated. In the worst case, `now = 0xFFFFFFFFU` and the …
=> Wayland key repeat fixes (fix infinite loop on ticks overflow + fix spurious repeats when not pumping events)

cmake/sdlchecks.cmake
If egl.pc sets at least two macros as the i.MX Vivante driver does, e.g.:
| Cflags: -I${includedir} -DLINUX -DWL_EGL_PLATFORM
then we get the following error during configuration:
| -- Performing Test HAVE_OPENGL_EGL
| CMake Error: Parse error in command line argument: WL_EGL_PLATFORM
|  Should be: VAR:type=value
If one changes to add a value to the macro, e.g.
| Cflags: -I${includedir} -DLINUX=1 -DWL_EGL_PLATFORM=1
then cmake does not error out but the macro is not passed to the
C compiler.
CMAKE_REQUIRED_FLAGS is the wrong variable to pass the CFLAGS in,
CMAKE_REQUIRED_DEFINITIONS should be used.
Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>
=> cmake: sdlchecks.cmake: pass cflags to the appropriate cmake variable

CMakeLists.txt
when using alternate unwind implementations like LLVM libunwind
this library is not provided yet the libunwind features are fully
implemented in main libunwind, making this hard dependency assumes
a particular libunwind implementation, this patch makes it optional
which makes the builds to work with llvm libunwind
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> cmake: Remove libunwind-generic as hard dependency

CMakeLists.txt
Mostly meant to allow SDL2 to be incorporated as a sub-project of external CMake projects, i.e. there should be no need to make a matching change in the autoconf build.
Default behavior is unchanged.
=> Optionally disable generation of SDL2main and uninstall projects.

src/render/opengles2/SDL_render_gles2.c
Turns out they're much faster!
Fixes #5206.
=> opengles2: Use client-side arrays on everything but Emscripten.

src/video/SDL_video.c
SDL_WINDOWEVENT_SIZE_CHANGED is now sent even if the resulting size of the window does not match the requested size.
When calling `SDL_SetWindowSize()`, the window may be resized to a different size than what was requested (for example on X11: https://github.com/libsdl-org/SDL/blob/main/src/video/x11/SDL_x11window.c#L956). In this case `SDL_WINDOWEVENT_SIZE_CHANGED` is not sent.
This patch check if the resulting window size is different from the original size to send the `SDL_WINDOWEVENT_SIZE_CHANGED`.
This bug can easily be triggered by requesting a size bigger than the screen size.
Fix #2782
=> Always send SDL_WINDOWEVENT_SIZE_CHANGED when window is resized

src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
This adds tracking (particularly useful for the non-libdecor case) when actual resize has occurred to let us know when we need to generate `SDL_WINDOWEVENT_RESIZED`. The libdecor case is fairly simple because we update to the new dimensions and call `Wayland_HandleResize()` in the same callback.
For non-libdecor, it's more complex because we update the dimensions in `handle_configure_xdg_toplevel()` but call `Wayland_HandleResize()` in `handle_configure_xdg_shell_surface()`, so the window dimensions will already be changed by the time `Wayland_HandleResize()` is called. Since checking `window->w != width` etc. in `Wayland_HandleResize()` won't work in this case, we need a separate variable to track a "pending resize" to ensure the event is generated.
The Wayland resize logic is pretty …
=> wayland: Avoid spurious resize events

src/audio/pipewire/SDL_pipewire.c
As of 0.3.22, Pipewire uses config files instead of explicitly hardcoding modules to load.  This changes the Pipewire backend to use the new method to load the realtime module to boost playback/capture thread priority and removes the deprecated method.  To accommodate this change, the minimum Pipewire version was raised slightly from 0.3.20 to 0.3.22.  This shouldn't be a problem as 0.3.22 is almost a year old and distros that use Pipewire as the audio backend have been tracking upstream fairly closely given the flurry of development over the last year.
The current Pipewire packages in supported versions of Fedora and Ubuntu (both regular and LTS) are well above the new version requirement, and slower distros like Debian 10 and 11 are still below version 0.3.20, which means that their …
=> audio: pipewire: Use client config to load the realtime module

src/joystick/windows/SDL_rawinputjoystick.c
Adds correlation of trigger inputs for XInput and WGI devices to raw input device to fix rumble and initial trigger input for XBox One/Series controllers.
https://github.com/libsdl-org/SDL/issues/5241
=> Add support for correlating trigger input

src/events/SDL_touch.c
If a touch-down event is received for an existing touch-ID, that probably means the operating system lost it, and that the missing touch-up should be synthesized, to keep the client state coherent.
In my experience, MS Windows does not produce a consistent stream of user-interaction events.
The giant legacy application I'm porting to Linux has been doing the equivalent for ages.
=> Synthesize a missing touch-up event

src/video/windows/SDL_windowsevents.c
The issue is that MS Windows synthesizes a mouse-move event in response to touch-move events, and those mouse-move events are _not_ labeled as coming from a touch (e.g. `GetMouseMessageSource()` will not return `SDL_MOUSE_EVENT_SOURCE_TOUCH` for those synthesized mouse-move events).
In addition, there seems to be no way to prevent this from happening; [this article](https://gist.github.com/vbfox/1339671) claims to demonstrate a technique to prevent it, but in my experience, it doesn't work.
Because of this, the "fallthrough" case can't test that the synthesized mouse-move came from a touch-move, and starts erroneously pressing down the mouse-button, leading to massive confusion in the client application.
So what was the purpose of the original fallthrough? git history stops at a hard …
=> Fix the erroneous generation of mouse-down events from touch-move events

src/video/windows/SDL_windowsevents.c
Existing discussion at https://discourse.libsdl.org/t/disable-tablet-flicks-on-ms-windows-by-default/34156 .
In short, enabling tablet-flicks messes up touch recognition under MS Windows.
Had to bump the internally-set MS Windows version from XP to Vista.
Hopefully it's safe to say no one is running XP any more.
=> Disable tablet flicks under MS Windows.

include/SDL_hints.h, src/video/windows/SDL_windowswindow.c
Existing discussion [here](https://discourse.libsdl.org/t/more-forceful-sdl-raisewindow-under-ms-windows/34292).
The issue is that Microsoft has gone through a lot of trouble to make it nearly impossible to programmatically move a window to the foreground, for "security" reasons. Apparently, the following song-and-dance gets around their objections.
By default, it's disabled.
=> Add hint to optionally forcibly raise the window under MS Windows.

src/video/wayland/SDL_waylandwindow.c
Per a suggestion from the KWin maintainers...
https://bugs.kde.org/show_bug.cgi?id=448856
This is an attempt to clean up the large pile of wl_surface_commit calls that can happen early in an app's life. This mostly affects the XDG path. The shell-less path only gets one moved commit call (from CreateWindow to ShowWindow) and libdecor just doesn't have a commit at all anymore (libdecor does that for us anyway, I think).
For XDG, however, we do our best to buffer commits in such a way that only one commit happens by the time ShowWindow is done. After that, the call stream should be the same, we commit as much as we did before (but with slightly saner timing).
Marked as a draft for 3 reasons:
- Needs a lot of testing, moving commits is scary
- ~See the added FIXME in the changeset~ …
=> wayland: Try to avoid committing before the window is shown

src/video/SDL_video.c
This is a ~~draft~~ patch that will (at last) prioritize the Wayland video driver over X11. This is here purely for internal testing only and is NOT meant for wider community testing; to test SDL Wayland support you should set `SDL_VIDEODRIVER=wayland` instead.
Click [here](https://github.com/libsdl-org/SDL/issues?q=assignee%3Aflibitijibibo+is%3Aopen) for the SDL Wayland bug tracker.
The Big List of Annoying Things That Aren't SDL's Fault:
- [Event queue overflow issues (server-side, also affects Xwayland)](https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/188)
- [Steam overlay support](https://github.com/ValveSoftware/steam-for-linux/issues/8020)
- [NVIDIA doesn't support native Wayland Vulkan yet](https://forums.developer.nvidia.com/t/vulkaninfo-crashes-in-wayland-session-w …
=> video: Prefer Wayland over X11

CMakeLists.txt
Without this change, I was getting errors about ObjC syntax from headers being used in the test program which was being compiled as C.
Confirmed to work on:
macOS 10.15.7
XCode Version 12.4 (12D4e)
Xcode generator (`cmake -GXcode ..`)
Fixes #5010
(I think) fixes #3893
=> cmake: fix Metal detection

src/render/direct3d11/SDL_render_d3d11.c
The D3D9 backend uses `SDL_HINT_RENDER_DIRECT3D_THREADSAFE` to determine whether or not to set `D3DCREATE_MULTITHREADED` when creating the device. This PR applies the same logic to the D3D11 backend.
=> d3d11: Respect SDL_HINT_RENDER_DIRECT3D_THREADSAFE when creating device

src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
If we get a SDL_SetWindowSize() call right after SDL_SetWindowFullscreen() but before we've gotten a new configure event from the compositor, the attempt to set our window size will silently fail (when libdecor is enabled).
Fix this by remembering that we need to commit a new size, so we can do that in decoration_frame_configure().
=> wayland: Fix SDL_SetWindowSize() being dropped right after exiting fullscreen

src/joystick/vita/SDL_sysjoystick.c
As far as i understand, joystick subsystem should send SDL_JOYDEVICEADDED events for all connected joysticks on init.
This fixes it on PSVita.
=> PSVita: send initial SDL_JOYDEVICEADDED events

src/render/opengles2/SDL_render_gles2.c
When the texture state is changed outside the main state function, we forgot to disable vertex attrib array textcoord.
`data->glDisableVertexAttribArray((GLenum) GLES2_ATTRIBUTE_TEXCOORD);`
Issue with GLES2 and VBO #5235
=> GLES2: disable texcoord when not using it (see bug #5235)

src/video/windows/SDL_windowskeyboard.c, src/video/windows/SDL_windowsvideo.h
These are the patches from @pionere for win32 IME cleanups. These are the same patches in #5249--the two original patches plus the two extra fixup commits squashed in.
Fixes #5249.
=> Pionere IME patches

src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandsym.h
This fix wrong repetition on modifier keys, e.g. Control key.
=> Only generate key repetition for keys that should repeat on wayland.

src/video/vita/SDL_vitatouch.c
The PSVita touch handler always sends touch down on each update if a finger is present. This fixes it to be more in line with how touch is supposed to be handled after #5244
=> [PSVita] Fix touch holding detection after #5244 changes

android-project/app/src/main/java/org/libsdl/app/SDLControllerManager.java, src/joystick/android/SDL_sysjoystick.c
When running on a Fire TV, Amazon Fire TV controllers do not have a start button mapped. The closest alternative would be the menu button. SDL isn't detecting menu button presses from controllers. They are currently detected as keyboard events. These changes allow menu button presses from controllers to be detected as start button presses.
=> Android: Handle menu button press from controllers

src/render/SDL_render.c
1. use generic SDL_InvalidParamError instead of custom error message
2. (re)use n instead of calling SDL_GetNumRenderDrivers()
3. always check if renderer is NULL (instead of index == n which only works because n is never negative)
=> minor cleanup of SDL_CreateRenderer

src/audio/pipewire/SDL_pipewire.c, src/audio/pipewire/SDL_pipewire.h
This removes the previously hard coded 8192 upper sample limit when dealing with Pipewire buffers and latency and instead uses the buffer size set by Pipewire to clamp the spec.samples/spec.size values in addition to calculating the intermediate input buffer packet size.  This can allow the backend to avoid double-buffering in the output path when a higher latency is requested by the application as the output is only double buffered if the Pipewire buffer is too small, and the input path can avoid having to allocate extra packets in the data queue if Pipewire's new "clock.force-quantum" setting is used to increase buffer sizes, which can dramatically increase the amount of data delivered in the input callback.
The first patch in this series is just a minor bit of prep work as the stream …
=> audio: pipewire: Remove hardcoded upper sample limits

src/render/psp/SDL_render_psp.c
This fixes RenderCopyEx on the PSP not correctly.
Before this change, the images in the demo provided in #5329 would just rotate around the middle of the image, one even at the wrong aspect ratio. This PR fixes that. To proof it I've provided and image which shows how it looks now.
My solution is less efficient than the one used before, but it does work, which the previous solution didn't.
This resolves #5329
=> Psp rendercopyex

src/audio/pipewire/SDL_pipewire.c
While starting to implement the session detection code, I went though and made a few additional cleanups:
- The hotplug conditional variables are guarded by the Pipewire hotplug loop mutex in every case, so they don't need to be atomic.
- Some redundant locks when dealing with the IO device node list were removed.
- The global hotplug object pointers weren't nulled on shutdown, so if the audio system was started, shutdown, restarted and the restart failed halfway though, some object pointers could be double freed.
- Fixed up some cosmetic formatting issues.
@flibitijibibo
=> audio: pipewire: Cleanups in preparation for session detection

include/SDL_hints.h, src/joystick/hidapi/SDL_hidapi_gamecube.c
This adds support for all 3 of the gamecube controller's rumble modes
Rumble: 1
Stop: 0
StopHard: 2
This is useful for applications that need the full range of support
using the existing parameters I expanded on the meaning, now if both high and low are 0 that tells the driver that we want to perform a StopHard, if both are non-0 we want to do a normal rumble, and if low is 0 and high is non-0 we want to do a normal Stop
=> GameCubeAdapter: Add support for all rumble modes

test/testmouse.c
Add X1 and X2 button support to mouse test.
Mouse buttons X1 and X2 are not supported the the mouse test.
Mouse buttons X1 and X2 are not supported the the mouse test.
=> Add X1 and X2 button support to mouse test

src/video/emscripten/SDL_emscriptenvideo.c
Adds support for SDL_GetDisplayDPI on Emscripten.
As stated in issue #5381.
=> Add SDL_GetDisplayDPI implementation on Emscripten

src/joystick/windows/SDL_rawinputjoystick.c
The name that the Raw Input joystick driver pulls from the HID stack comes from USB string descriptors contained on the device. For official wireless receivers, this always contains "Xbox 360 Wireless Receiver for Windows" which matches the friendly name that WGI provides.
3rd party Xbox 360 wireless receivers may have different strings in their USB string descriptors (one uses "XBOX 360 For Windows" instead). This fails to match WGI's name and causes Raw Input and WGI to both report the same gamepad.
Since wireless Xbox 360 controllers seem to have a consistent VID/PID regardless of the adapter enumerating them, we can also match on that to catch these.
The duplicate case reported to me was:
Controller (XBOX 360 For Windows) - 030000005e040000a102000000007200
Xbox 360 Wireless Receiver …
=> rawinput: Fix double detection of gamepads on some 3rd party X360 wireless receivers

include/SDL_events.h, include/SDL_hints.h, include/SDL_keyboard.h, src/dynapi/SDL_dynapi_overrides.h, src/dynapi/SDL_dynapi_procs.h, src/events/SDL_keyboard.c, src/video/SDL_sysvideo.h, src/video/SDL_video.c, src/video/windows/SDL_windowskeyboard.c, src/video/windows/SDL_windowskeyboard.h, src/video/windows/SDL_windowsvideo.c, src/video/windows/SDL_windowsvideo.h
_This is a new PR that addresses the issues raised in #5378_
This PR addresses the following issues:
- Text from IME Candidates and final submissions are truncated if larger than 32 bytes.
- No way for application to query if the IME candidate window is currently open.
- No way for application to dismiss IME candidate window.
- Changes to how candidate window is placed to address some rare issues positioning.
- Whitespace being striped from the end of IME strings incorrectly
- Traditional Chinese IMEs issuing a placeholder in the form of an empty space which is inconsistent with expected behavior from other IMEs. Suppressing this seems to be the agreed upon solution (looking at Chromium source and Windows IME sample code).
- Address issues with spurious SDL_TEXTEDITING events
__IME …
=> IME Composition Truncation + SDL_IsTextInputShown + SDL_ClearComposition

src/core/android/SDL_android.c, src/video/android/SDL_androidevents.c, src/video/android/SDL_androidgl.c, src/video/android/SDL_androidvideo.c, src/video/android/SDL_androidwindow.c, src/video/android/SDL_androidwindow.h
I'm currently using SDL for windowing/input only with a custom vulkan renderer.
Building with: `-DSDL_RENDER_DISABLED=ON -DSDL_OPENGLES=OFF`
SDL seems to always link to some GLES functionality which I'd like to avoid so I don't have to link against the OpenGL libraries.
These changes add `#if SDL_VIDEO_OPENGL_EGL` around the blocks referencing opengl functions.
=> Make SDL_VIDEO_OPENGL_EGL optional on Android

src/video/windows/SDL_windowsevents.c, src/video/windows/SDL_windowswindow.c
If a user creates a new window via tearing off a tab - as you would do in a browser, for instance - the mouse button is still held at this point.
Upon releasing the mouse button, an event was not thrown because the default state of mouse_button_flags is set to 0.
Setting the initial mouse_button_flags to an invalid state fixes this.
=> Incorrect assumption that mouse button is released when new window is allocated

src/audio/SDL_audiocvt.c
Adds the sample format check to avoid byte-swap operation done for 8-bit streams.
Otherwise, this results in an assert on big-endian machines when attempting to use the SDL_LoadWAV_RW function to load 8-bit WAV files.
[#374
](https://github.com/libsdl-org/SDL_mixer/issues/374)
=> SDL_audiocvt.c: Don't byteswap 8-bit streams

android-project/app/build.gradle
This change causes the `mergeDebugAssets` task to depend on the `externalNativeBuildDebug` task--and all similar tasks for any other build variants besides Debug will have similar dependencies.
We discovered recently in DevilutionX that the assets we created at build time weren't being included in the APK produced by CI. It seems the gradle task for merging assets runs before the CMake build, so the assets that were being generated by our build process weren't being included in the APK.
=> Adjust gradle dependencies so build can position assets for APK

src/video/cocoa/SDL_cocoawindow.m
Updates the fullscreen toggle state (the green button, or 3rd button from the top left) when `SDL_SetWindowResizable` is called.  
n/a
=> SDL_cocoawindow.m: update fullscreen toggle when SDL_SetWindowResizable called

src/events/SDL_mouse.c
Here's an IRC dump that hopefully explains the issue this fixes:
```
> I'm debugging something odd where, for a libre game,
unvanquished.net (a FPS), relative mouse input in fullscreen is
buggy
> it's like, working mostly ok, but it has a weird
performance/cleanup bug
> after some time in relative mouse input mode, some time as low
as 15s, usually more, the SDL sends A LOT of relative mouse
input per frame
> almost all of which have xrel==0 && yrel==0
> by A LOT, I mean that after ~1min, it's usually in the
thousands per frame
> each frame, a while ( SDL_PollEvent( &e)) loop reads the
inputs, but it seems SDL is not clearing the list.
> one way to clear the list is to open the in-game console or
menu, which switches the input mode to absolute, then close it
which gets a working relative …
```
=> Fix relative mouse input for Unvanquished

include/SDL_hints.h, src/video/SDL_video.c
This is a patch I wrote to make it so foreign windows could create Vulkan surfaces... an example of this would be a C# WinForm that is passed to SDL_CreateWindowFrom so that it can be presented to via FNA3D's Vulkan renderer.
This is a draft for two reasons:
1. I couldn't come up with a good name for the hint ._.
2. Is this something that could potentially be in SDL_video.c instead? AFAIK the only thing the `VULKAN` flag does on all platforms is call SDL_Vulkan_LoadLibrary and that's it, so there's nothing stopping anyone from just hacking the flag in arbitrarily, the Vulkan surfaces are far less coupled to the window than they are in OpenGL.
=> video: Add a hint to allow Vulkan surfaces on foreign windows

src/audio/emscripten/SDL_emscriptenaudio.c
Commit 0dda8a7f4cdbcdccc78979ec808777b027645ac6 in #5248 erroneously also added the `SDL_*` constants to Javascript code where this constant isn't defined. This then causes an  "SDL_TRUE is not defined" exception at runtime for any emscripten app using audio. 
This PR reverses that change.
=> Fix "SDL_TRUE is not defined" runtime error for emscripten.

src/audio/dsp/SDL_dspaudio.c
In the 'dsp' audio driver, if we fail to find any devices, set an error message on the exit path.
Without this, `SDL_Init()` can fail without any message available in `SDL_GetError()`.
I built SDL on a relatively new OS install, and didn't realize I was missing some audio libs.
```bash
$ ./sdlgetaudiodriver 
Driver 0: dsp
Driver 1: disk
Driver 2: dummy
```
Only `dsp` is not "demand only". It fails to init on my system, when `SDL_EnumUnixAudioDevices()` finds no devices.
This in turn means `SDL_Init()` fails, but without any error message available, making it harder to know where to start troubleshooting.
=> audio: Set error message on dsp init failure.

src/video/SDL_blit_auto.c, src/video/sdlgenblit.pl
my compiler does not seem to make these optimizations, so it is worth to help a bit...
The script was NOT tested!
=> blit-auto optimizations

src/hidapi/android/hid.cpp
Added stub version of functions used by Java code made only to the purpose of "fill the gaps" when SDL_HIDAPI_DISABLED set to 1.
Fixes #5326, but keeping hidapi disableable.
=> Fix Android crash when SDL_HIDAPI_DISABLED set to 1

src/stdlib/SDL_getenv.c, src/stdlib/SDL_string.c
1. use simple comparison instead of SDL_strlen if the only question is whether the string is empty (SDL_getenv.c)
2. call SDL_toupper with unsigned char values instead of char, otherwise the result might be undefined according to the standard (SDL_string.c I.)
3. reduce the number of checks and the code size in the SDL_str(case)cmp functions (SDL_string.c II.)
=> stdlib improvements

src/video/SDL_video.c
I'm testing emscripten with newer (unreleased) SDL and getting a few test failures due to webgl now being used when it wasn't before. Looks like this might be related to the changes to creating texture framebuffers. I've disabled trying entirely here because:
- We used to use the backend's framebuffer support in previous releases
- There doesn't seem to be a huge performance difference between using `putImageData` and going through gl (sub-millisecond)
- Doing this drops > 200k of wasm from things that don't otherwise use the renderer API
=> Avoid trying to use texture framebuffers on emscripten

src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandvideo.h, wayland-protocols/xdg-output-unstable-v1.xml
Using wl-output to get the desktop display dimensions and dividing by the integer scale factor will not return the correct result when using a desktop with fractional scaling (e.g. a 3840x2160 display at 150% will incorrectly report the scaled desktop area as 1920x1080 instead of 2560x1440).  Use the xdg-output protocol, if available, to retrieve the correct desktop dimensions and offset.
Versions 1 through 3 of the protocol are supported.
#5437
=> video: wayland: Use xdg-output for retrieving the desktop dimensions

src/audio/vita/SDL_vitaaudio.c, src/render/vitagxm/SDL_render_vita_gxm.c, src/render/vitagxm/SDL_render_vita_gxm_tools.c, src/render/vitagxm/SDL_render_vita_gxm_tools.h, src/render/vitagxm/SDL_render_vita_gxm_types.h
* Support native planar (YV12, IYUV) and semi-planar (NV12/NV21) YUV textures.
* Fixed bug when failing to initialize native texture didn't return an error.
* Implemented support for fallback audio formats in vita audio backend.
Fixes #5417
=> Vita: implement native YUV textures.

src/video/wayland/SDL_waylanddyn.h, src/video/wayland/SDL_waylandsym.h
When using shared linking (linking in the normal way with
-lwayland-client) rather than loading Wayland libraries dynamically at
runtime, listing symbols that don't exist in the current version results
in a build failure. We don't actually call wl_proxy_marshal_flags() or
wl_proxy_marshal_array_flags() directly; the reason we need them is
that they're called by the code generated by wayland-scanner >= 1.20.
If we're building against an older Wayland library, then we'll have its
corresponding version of wayland-scanner (mismatched versions are not
supported), so we won't need those two symbols, and can avoid generating
a dependency on them.
Conversely, if we're building against a newer Wayland library, the
generated code will call them unconditionally, so we cannot treat them as
optional …
=> Avoid depending on libwayland 1.20 unnecessarily

src/video/wayland/SDL_waylandwindow.c
SDL_EGL_CreateSurface sets a more specific error message, so overwriting
it would lose information.
---
Discovered while trying to test SDL Wayland support on Ubuntu 21.10 with the NVIDIA proprietary driver (which doesn't seem to work, perhaps not enough stars have aligned yet).
=> wayland: Don't overwrite error message from SDL_EGL_CreateSurface

src/render/vitagxm/SDL_render_vita_gxm.c, src/render/vitagxm/SDL_render_vita_gxm_memory.c, src/render/vitagxm/SDL_render_vita_gxm_memory.h, src/render/vitagxm/SDL_render_vita_gxm_tools.c, src/render/vitagxm/SDL_render_vita_gxm_tools.h, src/render/vitagxm/SDL_render_vita_gxm_types.h
Use pre-allocated (on first texture creation) memory pool for textures.
This:
1. Lowers memory overhead (gpu memblocks size must be 256kb-aligned)
2. Prevents resource exhaustion (there can be no more than 2048 memblocks, so 2048 textures. This removes that limit)
3. Very-slightly speeds-up texture creation.
=> Vita: Use preallocated memory pool for textures

src/render/SDL_render.c
This leak is similar to the one fixed in commit 4fe7b2cbd1a15ae2fe174e189153bb3d0750b5c8 in `SDL_RenderDrawLinesF()`.
None
=> Fix potential memory leak in QueueCmdFillRects

include/SDL_hints.h, src/events/SDL_mouse.c, src/events/SDL_mouse_c.h, src/events/SDL_touch.c
Add `SDL_HINT_VITA_TOUCH_MOUSE_DEVICE` psvita-specific hint that allows limiting touchpad device that generates synthetic mouse events (if such generation is enabled) on PSVita. By default only front touchpad will generate such events.
We have two touch panels on vita (from touchscreen and back panel), and while generating mouse events could be useful, doing that from both touch panels brings more problems, than synthetic mouse events solve.
=> Vita: Allow limiting touch device for synthetic mouse events

src/video/SDL_sysvideo.h, src/video/SDL_video.c, src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandopengles.c, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandvideo.h, src/video/wayland/SDL_waylandvulkan.c, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h, wayland-protocols/viewporter.xml
Desktops with fractional scaling need special handling to avoid significant overdraw as desktop-sized windows can have backbuffers significantly larger than the native resolution, which then have to be downscaled for final output.  This uses the wp_viewporter protocol, when available, to allow for the use of the native display resolution in fullscreen applications and, potentially, direct scanout by compositors.
Desktops with fractional scaling that don't support viewports are still stuck rendering to oversized backbuffers, but there's nothing we can do about this (do any even exist?)
Needless to say, this needs testing on as many desktops as possible.  It works well on GNOME 41 with Vulkan, GL and the software blitter, but I haven't had a chance to test it on desktops like KDE or Sway. …
=> video: wayland: Use wp-viewporter for fullscreen with fractional scaling

src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
Given that the main goal of mode emulation is legacy compatibility, we should expose as many emulated display modes as possible.  They will currently display stretched to the display's native desktop dimensions, but if an application requires a specific hardcoded resolution, it will work at the very least.  Perhaps at some point in the future we can look into displaying non-native aspect ratios correctly, either by masking the desktop ourselves with subsurfaces or getting compositors to do it automatically.
This also prunes the emulated mode list and drops some of the really low resolutions. Anything with a horizontal width below 800 is gone, with the exceptions of 720x480 (NTSC) and 640x480 (VGA).  The old lists had resolutions as low as 320x240 and 320x200 (mode X and 13h), which I …
=> video: wayland: Expose more resolutions for mode emulation

CMakeLists.txt, docs/README-vita.md, include/SDL_config.h.cmake, src/render/opengl/SDL_render_gl.c, src/video/SDL_egl.c, src/video/vita/SDL_vitagl_pvr.c, src/video/vita/SDL_vitagles.c, src/video/vita/SDL_vitagles_c.h, src/video/vita/SDL_vitagles_pvr.c, src/video/vita/SDL_vitagles_pvr_c.h, src/video/vita/SDL_vitavideo.c, src/video/vita/SDL_vitavideo.h
- Added support for Desktop OpenGL backends via GL4ES4VITA utilizing previous PSP2_PVR support.
- Minimal modifications to SDL_egl and SDL_render_gl to account for incompatible headers.
- Added a `VITA_PVR_OGL` environment variable to force the Vita driver to use Desktop GL instead before creating a window.
- Refactored the Vita Video file structure to better reflect the different options.
Everything else in terms of usage remains the same, including being able to create any OpenGL 1.X/2.X context, or creating a Desktop GL SDL renderer.
This will never be enabled by default.
=> [PSVITA] Add Desktop OpenGL 1.X/2.X Backends

src/video/emscripten/SDL_emscriptenframebuffer.c, src/video/emscripten/SDL_emscriptenmouse.c
This PR uses new APIs added in [emscripten-core/emscripten#9336](https://github.com/emscripten-core/emscripten/pull/9336) to improve compatibility with USE_PTHREADS=1.
Original PR: https://github.com/emscripten-ports/SDL2/pull/127
By: @jakogut
Reviewed by: @Daft-Freak
This fix enables me to compile an executable using `-s USE_PTHREADS=1 -s USE_SDL=2` and not get the following error in the chromuim debug console
```
Uncought TypeError: Cannot read properties of undefined (reading 'CreateImageData')
```
With the current patch applied the [InfiniSim Simulator](https://github.com/InfiniTimeOrg/InfiniSim) works :tada: 
- https://github.com/emscripten-core/emscripten/issues/6009
=> SDL2 thread proxying fixes

test/testmouse.c
Using a scroll wheel in `testmouse` will now show and move move horizontal/vertical lines.
`testmouse` now checks for `SDL_MOUSEWHEEL` and visualises `preciseX` and `preciseY` updates.
- Intent: help avoid XInput2 bugs during development in #5481
- May also be useful for testing #5382
Submitting as a standalone PR since this has no impact on `libsdl2` clients.
NB: horizontal mouse wheel behaviour seems to be flipped wrt what the docs say (XInput2, both with and without #5382 ), cf. the comment in line 98 (from https://wiki.libsdl.org/SDL_MouseWheelEvent).
Am I misreading the docs or should I file a separate issue or PR against XInput2?
=> Add visualisation for mouse wheel testing to test/testmouse

src/video/x11/SDL_x11opengl.c
libGL.so may register callbacks that can be invoked upon XCloseDisplay(). If XCloseDisplay() is called after libGL.so is unloaded, the callback pointer will point at freed memory and invoking it will crash.
The texture framebuffer check optimized out in f37e4a9 was causing libGL.so to never be unloaded as a side-effect. Skipping it exposed this bug by allowing libGL.so to actually unload.
This should probably be reviewed for correctness by someone more familiar with X11 and/or GLX. #5484 has more detailed analysis. 
Fixes #5484
=> x11: Don't unload libGL.so to prevent a crash in XCloseDisplay()

test/testgles2.c
As far as I can see, the current implementation initializes too large VBOs. It didn't cause issues on my Linux system though.
=> testgles2: Fix buffer object sizes

src/core/linux/SDL_ibus.c
See: https://github.com/ibus/ibus/blob/5a455b1ead5d72483952356ddfe25b9e3b637e6f/client/gtk2/ibusimcontext.c#L468
IBus keycode is evdev keycode, instead of X keycode.
=> IBus should use ev keycode instead of X keycode

include/SDL_config_emscripten.h
Emscripten actually does support recursive mutexes, so no need to use SDL's fake recursive code.
Background: #5428, #5479
=> Compile with recursive mutexes for emscripten

src/render/SDL_render.c, src/render/opengl/SDL_render_gl.c
For OpenGL this means resetting the viewport state shadowing flag too.
Fixes #1504
Tested this against VVVVVV after remembering that macOS defaults to Metal (can you tell I don't do Mac stuff anymore...). The main bug was that the viewport flag needed to be reset on window changes, but the upper-level change is still important for DPI changes as well.
=> render: Update the size/scale/viewport on moves, in addition to resizes

src/render/direct3d11/SDL_render_d3d11.c
Untested but pretty self-explanatory, see the linked issue for more info.
D3D11 CC: @baidwwy
Fixes #4782
=> direct3d11: Set the swapchain target immediately after creating it

src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
I was noticing some occasional flickering and artifacts when using the emulated display modes.  Looking at the Wayland debug output, the surface damage region was being automatically calculated from the backbuffer size.  When the backbuffer is smaller than the scaled viewport area, only part of the viewport region the size of the output buffer was being marked as damaged and visual artifacts could result in the region outside of this area.  This manually sets the surface damage region to the entire output area in the frame callback when using a fullscreen viewport to fix this.
@flibitijibibo
=> video: wayland: Set the surface damage region when using fullscreen viewports

CMakeLists.txt
After https://github.com/libsdl-org/SDL/commit/7850d0cf6fa1b2e7d8999d0506bb907ae071f497 commit (autoreplace gone wrong?), vita PVR support was being incorrectly reported as Off even when enabled due to flag names mismatch
=> Vita: fix VIDEO_VITA_PVR flag

src/timer/os2/SDL_systimer.c
SDL_GetTicks64 can not rely on `ulTmrFreq == 0` check, because that is always true in case of the fallback mode (DosQuerySysInfo).
The `ticks_started` variable is added to fix the issue and bring in line with the other timers.
=> fix os2 timer in fallback mode

src/joystick/linux/SDL_sysjoystick.c
In case of error `scandir` does not initialise `entries` and this uninitialised pointer is freed. 
None
=> Initialise scandir argument

include/SDL_hints.h, src/video/wayland/SDL_waylandvideo.c
This hint allows libdecor to be used even when xdg-decoration is available.
It's mostly useful for debugging libdecor, but could in theory be used by applications which want to (for example) bundle their
own libdecor plugins. Definitely not something we'd want to enable by default, but very useful when checking that this works without having to log out or start a nested compositor.
There's a corresponding hint proposal in libdecor:
https://gitlab.gnome.org/jadahl/libdecor/-/merge_requests/81
Using them together gives libdecor client-side decorations even on systems which prefer SSDs:
```
SDL_VIDEO_WAYLAND_PREFER_LIBDECOR=1 LIBDECOR_FORCE_CSD=1 ./app
```
=> Wayland: Add SDL_HINT_VIDEO_WAYLAND_PREFER_LIBDECOR

src/render/SDL_render.c
not sure if `renderer->magic != &renderer_magic` check is necessary/desired...
=> avoid NullPointer in SDL_GetRenderTarget

src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandwindow.c
A couple of quick Wayland fixes.  Clamps the fullscreen window dimensions to the desktop and adjusts the rounding when scaling pointer coordinates so they don't exceed the window boundaries.  Should fix #5539.
@flibitijibibo
=> Wayland fixes for window boundaries and pointer scaling

CMakeLists.txt
When building SDL from source with CMake, there is an option to disable the uninstall target, but none to disable the install target. Disabling installation is generally convenient for projects shipping the SDL source with their projects, to avoid mixing both SDL's and the project's installation targets.
I tried keeping my changes to a minimum, and I made everything as consistent as I could with the uninstall option; I leave my branch open for write access for repository owners, if necessary.
=> Added CMake option to disable the installer

include/SDL_hints.h, src/audio/SDL_audio.c, src/video/SDL_video.c, src/video/dummy/SDL_nullvideo.c
They were just environment variables before.
Fixes #5528.
This seems safe enough to merge, but we're in the 2.0.22 window, so I'm putting it into a pull request in case we want to wait for 2.0.24.
=> hints: Make SDL_VIDEODRIVER and SDL_AUDIODRIVER formal hints.

include/SDL_syswm.h, src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
Tested with UE5 and works about as well as X - that is, if you shake the mouse hard enough the tooltip might flicker for a frame or two. Otherwise should be good to go.
Fixes #5495
CC: @BrandonSchaefer @mikesart
=> wayland: Add support for TOOLTIP/POPUP_MENU

src/video/SDL_video.c
When mode switching is disabled in a video backend, fullscreen windows are basically just fullscreen desktop windows with different internal scaling.  As no mode switching occurs, there's no need to minimize them on focus loss by default.  This can still be overridden by explicitly setting the internal hint for minimizing on focus loss.
This has the side effect of fixing a bug on GNOME, where, when a fullscreen Wayland window has it's focus lost and restored via alt+tab followed by switching back to windowed mode, the top portion of the window won't end up being obstructed by GNOME's top bar.
=> video: Don't minimize fullscreen windows on focus loss by default when mode switching is disabled

src/joystick/SDL_gamecontrollerdb.h
After 38ed8a955a10 `SDL_JOYSTICK_LINUX` is also defined on FreeBSD, so check it instead of `__LINUX__` ([excludes](https://github.com/libsdl-org/SDL/blob/993a56766db02fe5373a328fa1c2fe8da46801d6/include/SDL_platform.h#L65) Android).
See also https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=218289#c5
=> Enable evdev-based gamecontrollerdb on FreeBSD

src/filesystem/windows/SDL_sysfilesystem.c
use GetModuleFileName directly (as recommended)
=> simplify SDL_GetBasePath on windows

src/render/SDL_render.c, src/render/SDL_sysrender.h
SDL_render.c: internally change viewport/cliprect type from SDL_FRect  to SDL_DRect (double precision). (see bug #5547)
=> SDL_render.c: internally change viewport/cliprect type from SDL_FRect  to SDL_DRect (double precision). (see bug #5547)

src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
Fixes a -Wshadow warning and removes an unused function prototype (my fault, I deleted the function body, but accidentally left this in when prototyping the viewport/scaling code).
@flibitijibibo
=> Small Wayland cleanups

WhatsNew.txt, include/SDL_rect.h, include/SDL_stdinc.h, test/testautomation_rect.c
This changes `SDL_FRectEquals` to compare the rects using the absolute difference vs a default epsilon, implemented in terms of `SDL_FRectEqualsEpsilon`, which takes the epsilon as an argument.
The default epsilon was pulled out of thin air as of writing, and is certainly up for discussion. I don't think it need to be as small as `FLT_EPSILON`, but let me know what you think.
I did not see any tests for FRects, but I'm open to adding some.
Rationale: See #5558
=> SDL_Rect: SDL_FRectEquals /w epsilon

include/SDL_events.h, src/joystick/SDL_joystick.c, src/joystick/hidapi/SDL_hidapi_luna.c, src/joystick/hidapi/SDL_hidapi_ps4.c, src/joystick/hidapi/SDL_hidapi_switch.c, src/joystick/hidapi/SDL_hidapi_xbox360w.c, src/joystick/windows/SDL_rawinputjoystick.c
First commit ensures that battery level is updated through `SDL_PrivateJoystickBatteryLevel()` and that initialization is done by directly writing to `joystick->epowerlevel`. This way the event is sent only on update and not while opening the joystick.
Second commit adds the joystick battery event that is sent when the battery power level changes.
None.
=> Add Joystick battery event

CMakeLists.txt, configure, configure.ac, include/SDL_config.h.cmake, include/SDL_config.h.in, include/SDL_config_android.h, include/SDL_config_emscripten.h, include/SDL_config_iphoneos.h, include/SDL_config_macosx.h, include/SDL_config_os2.h, include/SDL_config_pandora.h, include/SDL_config_windows.h, include/SDL_config_winrt.h, include/SDL_stdinc.h, src/dynapi/SDL_dynapi_overrides.h, src/dynapi/SDL_dynapi_procs.h, src/stdlib/SDL_qsort.c
The necessity first came up in @creichen's PR #5481 where he worked
around it for now.
Tossing this here as a PR, so it won't get lost.
=> add SDL_bsearch

src/joystick/hidapi/SDL_hidapi_switch.c
Up until now, Switch motion sensor input was scaled with hard-coded values based on what was common to most Switch controllers. But many supported Switch controllers (including newer official Nintendo Switch controllers) use different scales for motion sensor data. This change reads the scaling factors from the controller so that they should be correct for more kinds of controllers.
No existing issue. I just fixed this for JoyShockLibrary and wanted to do the same for SDL.
=> Read motion sensor scale from Switch controllers

src/video/cocoa/SDL_cocoamouse.m
`SDL_SetRelativeMouseMode(SDL_TRUE)` fails on macOS when called following an event like window maximization. This is a common use case on mac since the only way to create a maximized window with cursor capture is to first initialize it in windowed mode without cursor capture, maximize the window using the cursor by pressing the green button in the menu bar, then turn on relative mouse mode afterwards.
Maximizing a window using the 3rd green button on the menu bar briefly causes the window to move and go out of focus, causing the current code in `Cocoa_SetRelativeMouseMode` to return early and never call `CGAssociateMouseAndMouseCursorPosition()`. Moving the call to `CGAssociateMouseAndMouseCursorPosition(NO)` before checking the window's status allows the flag to be set. This issue does …
=> SDL_cocoamouse.m: SetRelativeMouseMode even if window out of focus/being moved

src/video/cocoa/SDL_cocoawindow.m
Fixes an issue introduced via #5573 when building for i686.
See: https://github.com/libsdl-org/SDL/pull/5573#issuecomment-1110073244
=> Fixes an issue introduced via #5573 when building for i686

test/testautomation_hints.c
Corrects the following warning (GCC 11.3.0), due to the length not matching the actual number of members of the enums.
```
testautomation_hints.c: In function 'hints_getHint':
testautomation_hints.c:79:15: warning: iteration 23 invokes undefined behavior [-Waggressive-loop-optimizations]
79 |     result1 = SDL_GetHint(_HintsEnum[i]);
|               ^~~~~~~~~~~~~~~~~~~~~~~~~~
testautomation_hints.c:78:14: note: within this loop
78 |   for (i=0; i<_numHintsEnum; i++) {
|             ~^~~~~~~~~~~~~~
testautomation_hints.c: In function 'hints_setHint':
testautomation_hints.c:134:14: warning: iteration 23 invokes undefined behavior [-Waggressive-loop-optimizations]
134 |     result = SDL_SetHint(_HintsEnum[i], originalValue);
|              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
```
=> test: Correct invalid enum length.

src/joystick/iphoneos/SDL_mfijoystick.m
Small compatibility improvement to the Game Controller Framework driver to provide compatibility for applications built with older macOS SDKs.
For various compatibility reasons, macOS 11.0 is also macOS 10.16 at the same time. Usually these version numbers are interchangeable in an `@available` API availability check. However, there is a weird edge case when applications that have been built using an older macOS SDK load SDL2 as a dynamic library. In this case `@available(macOS 11.0 ...)` check will incorrectly return false although `@available(macOS 10.16 ...)` returns true. This happens for example in [MonoGame](https://github.com/mono/MonoGame) where games run in the .NET runtime and SDL is loaded dynamically. A similar issue was also described in this [forum …
=> Obj-C available check for macOS 10.16 instead of 11.0

docs/README-linux.md
Just a small fix to add some missing backslashes in the Linux README.
=> Add missing backslashes in README-linux.md command

src/render/SDL_render.c
Rearranging the code like this, specifically checking that we're not allocating 0 things,
silences a warning raised by GCC 12.0.1
Fixes #5587
=> Fix for code generating -Wmaybe-uninitialized warning.

src/joystick/windows/SDL_rawinputjoystick.c
- Fixed a case where xinput_correlation was used even when XInput was unavailable
- moved possibly undefined variable into preprocessor check
#5580
=> Fixed using WGI without XInput

src/joystick/iphoneos/SDL_mfijoystick.m
Enabling GCController.shouldMonitorBackgroundEvents to read background events for MFi controllers before receiving the first GCControllerDidConnectNotification is apparently a no-go on macOS (12.3.1 for me), and would crash on attempt.
Apple's documentation is... not great, and doesn't point this out.
This waits for IOS_AddMFIJoystickDevice() to get called down the chain from GCControllerDidConnectNotification, and enables GCController.shouldMonitorBackgroundEvents if it hadn't been already.
On iOS and tvOS, GCController.shouldMonitorBackgroundEvents is ignored, so there's no need to check their versions.
=> Fix crash when reading background events for MFi controllers on macOS

include/SDL_hints.h, src/events/SDL_events.c
Adds a new verbosity level (3) for logging of `SDL_SYSWMEVENT` events. This complements the current verbosity levels that are available with `SDL_HINT_EVENT_LOGGING`.
The hint description is updated to accommodate the change.
When enabled, `SDL_SYSWMEVENT` are really spammy, even more so mouse motion events. So it makes sense to hide them under the most verbose logging level. Additionally, the events don't provide much useful info (so even less incentive to have them logged):
```cs
INFO: SDL EVENT: SDL_SYSWMEVENT (timestamp=2134)
INFO: SDL EVENT: SDL_SYSWMEVENT (timestamp=2134)
INFO: SDL EVENT: SDL_SYSWMEVENT (timestamp=2136)
```
=> Add new verbosity level for logging of `SDL_SysWMEvent`s

test/checkkeys.c
Shows potential consumers of said event on how to use it.
Freed after handling, as described in the event docs:
https://github.com/libsdl-org/SDL/blob/3dcfe86082d94eef17518724cebf30aa3543b0e0/include/SDL_events.h#L257
=> Enable `SDL_TEXTEDITING_EXT` events in `checkkeys` test

src/video/x11/SDL_x11mouse.c
Adds missing mouse4/mouse5 checks to X11_GetGlobalMouseState.
Makes X11_GetGlobalMouseState set the X1/X2MASK button flags if x11 reports button4/button5 being pressed.
=> Add mouse4/mouse5 support to X11_GetGlobalMouseState

CMakeLists.txt
It looks as though something in the test subproject "leaks" into the
main build system, causing us to try to install ${builddir}/test/sdl2.pc
instead of the correct ${builddir}/sdl2.pc. Moving the tests subproject
further down avoids this.
Resolves: https://github.com/libsdl-org/SDL/issues/5604
=> cmake: Defer test subproject until after defining install/uninstall

src/video/SDL_video.c
Somewhere in code refactoring between .20 and .22 this check
was lost, and so the hint had no effect anymore.
=> video: restore ability to disable fb accel via hint

.github/workflows/emscripten.yml, .github/workflows/main.yml, .github/workflows/msvc.yml, .github/workflows/riscos.yml
* workflows: Remove redundant `cmake --build`
* workflows: Change how we make CMake verbose
Some CI workers don't seem to understand `cmake -v`, and Windows' shell
doesn't understand `VERBOSE=1 cmake`.
* workflows: Only run `cmake --install` on Unix platforms
The syntax used in this step assumes a Unix shell.
=> workflows: Fix CI after #5602

.github/workflows/msvc.yml, src/stdlib/SDL_stdlib.c
Adjusts the preprocessor condition controlling whether `memset()`, `memcpy()` is defined on MSVC builds.
SDL2 provided definitions of `memset()`, `memcpy()`; however, these may clash with the definitions from the compiler runtime, notably when statically linking that runtime.
#3662, #5156, #4258
=> Fix building w/ MSVC static CRT

.github/workflows/main.yml
The official source code release isn't much use unless it contains
everything that users and downstream distributions need to do a
new build, so check that it does.
=> workflows: Do the equivalent of Automake `make distcheck`

include/SDL_stdinc.h, src/cpuinfo/SDL_cpuinfo.c, test/testautomation_stdlib.c
It's common to do arithmetic to work out how much space to allocate for something. This can be a problem if the inputs to the arithmetic are attacker-supplied and could overflow (as in libsdl-org/SDL_ttf#187 if using a malicious attacker-supplied font). Signed integer overflow is undefined behaviour, which could make anything happen, including a crash or a security vulnerability. Unsigned overflow is defined to wrap around, but that's exactly what we don't want when dealing with memory allocations, because it would be Very Bad to allocate less memory than we thought we had.
We can defend against this sort of thing by doing explicit bounds checks, but because signed overflow is UB, it's necessary to avoid actually doing the computation that would overflow. Recent versions of gcc (and I …
=> Add inlines for overflow detection

CMakeLists.txt, Xcode/SDL/SDL.xcodeproj/project.pbxproj, Xcode/SDLTest/SDLTest.xcodeproj/project.pbxproj, Xcode/SDLTest/TestDropFile-Info.plist, build-scripts/clang++-fat.sh, build-scripts/clang-fat.sh, docs/README-macos.md, include/SDL_platform.h, src/render/metal/SDL_render_metal.m, src/video/cocoa/SDL_cocoaclipboard.h, src/video/cocoa/SDL_cocoaclipboard.m, src/video/cocoa/SDL_cocoaevents.m, src/video/cocoa/SDL_cocoakeyboard.m, src/video/cocoa/SDL_cocoamessagebox.m, src/video/cocoa/SDL_cocoametalview.m, src/video/cocoa/SDL_cocoamodes.m, src/video/cocoa/SDL_cocoamouse.m, src/video/cocoa/SDL_cocoaopengl.m, src/video/cocoa/SDL_cocoaopengles.m, src/video/cocoa/SDL_cocoashape.m, src/video/cocoa/SDL_cocoavideo.h, src/video/cocoa/SDL_cocoavideo.m, src/video/cocoa/SDL_cocoawindow.h, src/video/cocoa/SDL_cocoawindow.m
With this change, SDL's macOS Objective-C code always uses ARC (automatic reference counting), just like the iOS backend. The main benefits are that ARC is the standard path for Objective-C code, and it's easier to and less bug-prone share code between the iOS and macOS backends (for example the Metal SDL_Render implementation).
ARC requires a 64 bit architecture on Mac, and it doesn't completely work on macOS 10.6 (https://developer.apple.com/library/archive/releasenotes/ObjectiveC/ObjCAvailabilityIndex/), so this change increases the runtime system requirement to 64 bit macOS 10.7.
The Cocoa implementations of `SDL_VideoData` and `SDL_WindowData` are changed from C structs to Objective-C classes (similar to the UIKit/iOS backend code) because ARC makes Objective-C object fields in C …
=> macOS: always use Objective-C ARC. Increase min runtime OS to 10.7.

include/SDL_stdinc.h
=> stdinc: Add a comment to clarify why inline functions are needed here

include/SDL_hints.h, src/video/cocoa/SDL_cocoaevents.m, src/video/cocoa/SDL_cocoakeyboard.m, src/video/cocoa/SDL_cocoametalview.m, src/video/cocoa/SDL_cocoamodes.m, src/video/cocoa/SDL_cocoamouse.m, src/video/cocoa/SDL_cocoaopengl.m, src/video/cocoa/SDL_cocoavideo.h, src/video/cocoa/SDL_cocoavideo.m, src/video/cocoa/SDL_cocoawindow.m
Now that macOS 10.7 is the minimum supported runtime version, some code that was supporting 10.6 can be removed (including one of the two remaining uses of Carbon).
#5632
=> macOS: remove dead code for supporting 10.6 at runtime.

src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandvideo.h, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
Don't be fooled by the diff size - this ended up being a big refactor of the shell surface management, masked only by some helper macros I wrote for the popup support.
This change makes it so when xdg_decoration is supported, but CSD is requested, the system bails on xdg support entirely and resets all the windows to use libdecor instead. This transition isn't pretty, but once it's done it will be smooth if decorations are an OS toggle since libdecor will take things from there.
In hindsight, we really should have designed libdecor to be passed a toplevel, having it manage that for us keeps causing major refactors for _every_ change.
Fixes #5653
=> wayland: Support xdg_decoration requesting client-side decorations

src/video/cocoa/SDL_cocoawindow.h, src/video/cocoa/SDL_cocoawindow.m
Fixes crashes when destroying or recreating a window.
Fixes #5664
=> macOS: Fix reference counts of internal window data.

test/testutils.c
- fix memory leak due to variable 'base'
- fix usage of uninitialized variable (path)
=> fix GetNearbyFilename

.editorconfig
See editorconfig.org for details of the format, which is understood by
multiple text editors, either directly or via plugins.
This is not comprehensive, but should cover most of the SDL codebase.
Please extend as needed.
=> .editorconfig: Automatically configure multiple text editors

.clang-format, src/audio/netbsd/SDL_netbsdaudio.c, src/cpuinfo/SDL_cpuinfo.c, src/events/scancodes_darwin.h, src/events/scancodes_linux.h, src/events/scancodes_windows.h, src/events/scancodes_xfree86.h, src/stdlib/SDL_iconv.c, src/video/SDL_blit_1.c, src/video/SDL_blit_A.c, src/video/SDL_blit_N.c, src/video/SDL_blit_auto.c, src/video/SDL_fillrect.c, src/video/kmsdrm/SDL_kmsdrmsym.h, src/video/riscos/scancodes_riscos.h, src/video/sdlgenblit.pl, src/video/wayland/SDL_waylandsym.h, src/video/x11/SDL_x11keyboard.c, src/video/x11/SDL_x11sym.h
This PR adds a clang-format file at the top-level. The reasoning behind its addition was discussed in the linked issue.
These settings try to emulate the most widely used format currently in place. But let me know if there are any changes that should be made.
<details>
<summary> Here is a code sample with the format applied to it </summary>
```cpp
#include <assert.h>
#include <stdlib.h>
#include "SDL.h"
#define SIZE        24
#define LONGER_SIZE 2400
#define SEPARATED_SIZE 5
#define TEST_X(x)               \
if (NULL == x) {            \
SDL_Log("X is null\n"); \
return -1;              \
}
#ifdef __cplusplus
extern "C" {
#endif
extern foo(int x, char *y);
#ifdef __cplusplus
};
#endif
enum E
{
LEFT,  /* Left direction */
RIGHT, /* Right direction */
UP,    /* Up direction */
DOWN,  /* …
```
=> Addition of clang-format

include/SDL_rect.h
Resolves: https://github.com/libsdl-org/SDL/issues/5691
---
... if this was genuinely unintended, of course! Otherwise, an explicit `(double)` cast would also silence the warning.
=> Avoid unintended float -> double conversion in SDL_FRectEqualsEpsilon

test/testutils.c
The documentation for `SDL_GetBasePath` stats that "The returned path is guaranteed to end with a path separator ('\\' on Windows, '/' on most other platforms).", so it's not necessary to add another one when appending the file name. The code wasn't quite correct on RISC OS anyway, since it ignores the value of `__get_riscosify_control()` (which defaults to using Unix-style paths) and doesn't replace the file extension separator if RISC OS-style paths are used.
=> Remove extra path separator in GetNearbyFilename

test/Makefile.in
I had assumed that only Linux users would be interested in GNOME-style
installed-tests, but in principle there's no reason why they can't be
used on non-Linux.
---
Prompted by SDL_image CI leaving installed-tests enabled on macOS, which has a different and less featureful install(1).
=> test: Use install(1) more portably

.github/workflows/watcom.yml
This should fix the current CI failures for now.
=> Use a tagged version of OpenWatcom in CI builds

src/video/wayland/SDL_waylanddyn.h, src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandsym.h
As noted by @jadahl, we were missing `libdecor_dispatch` in SDL. Most of the dispatching work that needs to be done in the current cairo plugin, is already done in `Wayland_WaitEventTimeout`. But any more complex plugin, e.g. the hopefully future GTK plugin, will need additional iterations of their own event loop. This PR adds the `libdecor_dispatch` function.
However, now we are duplicating the dispatching. Most of the dispatching is done in `libdecor_dispatch` now. Everything that follows is repeating this with some additional key-repeat logic.
Any thoughts on this? Should the dispatching be divided in "wayland" dispatching and SDL-specific dispatching? I actually think that key-repeat stuff should be handled in the wayland key handlers and not the `Wayland_WaitEventTimeout`.
=> add libdecor_dispatch

src/video/android/SDL_androidwindow.c, src/video/cocoa/SDL_cocoawindow.m, src/video/directfb/SDL_DirectFB_window.c, src/video/haiku/SDL_bwindow.cc, src/video/os2/SDL_os2video.c, src/video/pandora/SDL_pandora.c, src/video/psp/SDL_pspvideo.c, src/video/raspberry/SDL_rpivideo.c, src/video/riscos/SDL_riscoswindow.c, src/video/uikit/SDL_uikitwindow.m, src/video/vita/SDL_vitavideo.c, src/video/vivante/SDL_vivantevideo.c, src/video/windows/SDL_windowswindow.c, src/video/winrt/SDL_winrtvideo.cpp, src/video/x11/SDL_x11window.c
Since #5602, SDL is intended to have the same ABI across the whole
major-version 2 cycle, so we should not check that the minor version
matches the one that was used to compile an application.
There are two checks that could make sense here.
The first check is that the major version matches the expected major
version. This is usually unnecessary and is not usually done (if we're
calling into the wrong library we'll likely crash anyway), but since we
have the information, we might as well continue to use it.
The second check is whether the version provided by the caller is
equal to or greater than a threshold version at which additional fields
were added to the struct. If it is, we should populate those fields;
if it is not, then we cannot. This is only useful on platforms where
additional …
=> video: Only check major version in SDL_GetWindowWMInfo

test/testcustomcursor.c
This is useful for video drivers that only support one or the other, as well as video drivers that don't support either but still support `SDL_ShowCursor()`.
=> testcustomcursor: Allow running without custom or system cursors

src/video/windows/SDL_windowskeyboard.c
As described in the linked issue, this fixes crashes with long IME compositions on Windows.
The issue is caused by `ImmGetCompositionStringW` returning the length without the null terminator.
Fixes #5729.
=> ime: windows: allocate space for composition null terminator

src/hidapi/SDL_hidapi.c
In doing some launch support for Super Hexagon I discovered at least one PC that will lag horribly when doing libusb enumeration... as far as I can tell this is hardware-specific; it's a crappy board from 2011 where doing certain USB operations will just stall for 100ms or more regardless of what OS you're using; I was unable to reproduce this on any other machine in my lab. AFAICT libusb isn't doing anything wrong, and even if it was I wouldn't be the person to identify the issue, so it seemed easier to have a hint to disable it for this one box. This matches the style of `SDL_HIDAPI_JOYSTICK_DISABLE_UDEV` directly above.
=> hidapi: Allow disabling libusb support at runtime

CMakeLists.txt, configure, configure.ac, sdl2-config.in
This pr:
- makes sdl2-config relocatable by calculating the sdl2 prefix relative to the binary directory
(I don't think `sdl2.pc` and the libtool `.la` files can be made relocatable)
- fixes `sdl2-config --static-libs`.
Before, the output of `sdl2-config --static-libs` was:
**linux**:
```
-L/tmp/buildautotools/prefix/lib -lSDL2 -lm -ldl -lpthread -lrt
```
**mingw**:
```
-L/tmp/buildmingw32/prefix/lib -lmingw32 -lSDL2main -lSDL2 -mwindows -Wl,--dynamicbase -Wl,--nxcompat -lm -ldinput8 -ldxguid -ldxerr8 -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lshell32 -lsetupapi -lversion -luuid
```
This pr replaces every case of `-lSDL2` with `-Wl,-Bstatic -lSDL2 -Wl,-Bdynamic` so the above outputs become:
**linux**:
```
-L/tmp/buildautotools/prefix/lib -Wl,-Bstatic -lSDL2 -Wl,-Bdynamic -lm …
```
=> Relocatable sdl2-config + fix `sdl2-config --static-libs`

CMakeLists.txt
Fixes https://github.com/libsdl-org/SDL/issues/5246 by initializing `SDL_STATIC_PIC` from `CMAKE_POSITION_INDEPENDENT_CODE`.
=> Initialize SDL_STATIC_PIC from CMAKE_POSITION_INDEPENDENT_CODE

test/testautomation_rect.c, test/testautomation_surface.c, test/testautomation_video.c
Eliminate trivial warnings issued by gcc-11.3 due to limitations in its static checkers by
adding extra initialisation and (in one case) by diverting a control flow edge that is only taken on impossible control flow paths.
These warnings break `cmake` release builds on my Debian/amd64 setup.
=> Build warning fixes for gcc-11.3

test/testautomation_rect.c
gcc-11 warns about two uninitialised fields being used.  To my understanding, the tests in question do not actually depend on the contents of those fields, but gcc's analysis is not able to see that.  This patch initialises those fields to dummy values to remove those warnings.
=> Remove two gcc-11 warnings

CMakeLists.txt, configure, configure.ac, src/render/direct3d12/SDL_render_d3d12.c
In the original PR in #5761, CMakeLists.txt and configure simply tested for the d3d12.h header. However, this is not a sufficient check as older versions of the Windows 10 SDK will not successfully compile the d3d12 renderer. This PR adds C source checks to the CMakeLists.txt/configure workflows to confirm that the WDK_NTDDI_VERSION is high enough to enable the d3d12 renderer.
It also fixes `-Wincompatible-pointer-types` warnings in some configurations.
=> Fix D3D12 support check in CMakeLists.txt/configure builds

CMakeLists.txt
Force shared SDL2 building with `POSITION_INDEPENDENT_CODE` enabled, even when `CMAKE_POSITION_INDEPENDENT_CODE` is false.
Looks like recent CMake versions behave different then older ones.
Fixes https://github.com/libsdl-org/SDL/issues/5769
=> Set POSITION_INDEPENDENT_CODE property on SDL2 for CMake 3.0

.github/workflows/emscripten.yml, src/video/emscripten/SDL_emscriptenframebuffer.c, src/video/emscripten/SDL_emscriptenmouse.c
Changes the framebuffer/cursor proxying code to use `MAIN_THREAD_EM_ASM` instead of `emscripten_sync_run_in_main_runtime_thread` with a function wrapping the `EM_ASM`. This is how everything else was handled.
Fixes this error
`error: undefined symbol: emscripten_sync_run_in_main_runtime_thread_`
caused by the proxying changes (caught while trying to update Emscripten to the latest release(https://github.com/emscripten-core/emscripten/pull/16916)).
=> emscripten: fix undefined symbol errors in non-threaded builds

src/render/direct3d11/SDL_render_d3d11.c, src/render/direct3d12/SDL_render_d3d12.c
This is the likely fix for the issue reported in #5774.
This PR also adds a couple of missing `SDL_zero` calls to fix the possibility that the `resourceView` and `renderTargetViewDesc` could contain uninitialized parameters. There was a similar issue with the `renderTargetViewDesc` not being `SDL_zero`ed in the D3D12 renderer.
=> D3D11: Fix SDL_TEXTUREACCESS_TARGET not working if SDL_HAVE_YUV is 0

CMakeLists.txt, src/test/SDL_test_harness.c, src/test/SDL_test_random.c
These are needed when building with `-DSDL_TEST=ON`.
=> PS Vita build fixes

include/SDL_stdinc.h, src/core/linux/SDL_fcitx.c, src/core/linux/SDL_ibus.c, src/dynapi/SDL_dynapi_overrides.h, src/dynapi/SDL_dynapi_procs.h, src/stdlib/SDL_string.c, src/video/wayland/SDL_waylandevents.c
The linux IME backends use a workaround to avoid the byte limit of `SDL_TEXTEDITING`. That is, they split the preedit string in multiple chunks.
With the introduction of `SDL_TEXTEDITING_EXT`, the workaround is no longer needed. Moreover, because of the workaround, the new event isn't actually used.
With this PR, if `SDL_HINT_IME_SUPPORT_EXTENDED_TEXT` is `true`, we send the whole preedit string at once.
If the hint is `true` we now also retrieve the cursor position and selection size (in utf-8 characters, not bytes) for all backends.
In iBus and Fcitx there is no simple way to obtain the selection size as they don't specify it directly, but only declare how to decorate (highlight, underline, ...) each character/section of the preedit string.
Because of this, I decided to extract the …
=> Use `SDL_TEXTEDITING_EXT` in linux IME and provide useful cursor info

include/SDL_hints.h, src/video/wayland/SDL_waylandopengles.c, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
Some general Wayland refactoring and bug fixes, some of which are just rebased from the now closed #5534.  Outside of the rework of scale factor handling, there isn't anything new in the way of overall functionality or behavior here.
- Refactors the fullscreen and viewport logic to compartmentalize the fullscreen mode emulation blocks and unify the fullscreen/windowed viewport logic.
- Consolidates some duplicate code.
- Adds a hint to disable video mode emulation.
- Fixes a bug where emulated video modes weren't swapping the width/height in all cases where they should be.
- Refactors the scaling code to unify the integer and fractional cases.  This improves the behavior when using multiple displays with different scale factors, particularly when a window is moved between or straddles …
=> Wayland general refactoring and fixes

src/SDL_error.c
Remove unused `#define SDL_ERRBUFIZE`.
=> Remove unused macro definition in SDL_error

src/events/SDL_events.c
Fixes the spurious `SDL_WaitEvent()` timeout bug described in #5780
Fixes #5780
=> events: Fix spurious early returns from SDL_WaitEvent()/SDL_WaitEventTimeout()

src/video/SDL_egl.c, src/video/SDL_egl_c.h, src/video/winrt/SDL_winrtopengles.cpp
Previously, `egl_dll_handle` actually referred to the OpenGL shared object, while `dll_handle` referred to the EGL shared object.
=> Rename variables in SDL_egl.c to be more intuitive

sdl2-config.cmake.in
When SDL is built with Wayland support on Linux, and Wayland libraries
are linked as dependencies instead of being loaded with dlopen(), its
dependencies will include libraries whose names contain a dash, like
`-lwayland-client` and `-ldecor-0`. Don't replace such libraries with
`-lwayland` and `-ldecor`: those don't exist and linking them will fail.
---
To reproduce the bug that this fixes:
* build with Autotools, as is done in Debian
* `--enable-video-wayland --disable-wayland-shared`, as is done in Debian
* run Debian's "as-installed" test-case https://sources.debian.org/src/libsdl2/2.0.22%2Bdfsg-5/debian/tests/cmake/, which links a trivial executable using https://sources.debian.org/src/libsdl2/2.0.22%2Bdfsg-5/debian/tests/cmake-static/CMakeLists.txt/
Discovered while updating the git …
=> cmake: Fix static linking to dependencies with "-" in library name

src/video/wayland/SDL_waylandvideo.c
Some compositors will provide 'nicer' / 'human readable' output descriptions via the xdg-output protocol. Use these description strings, when available, instead of the model name provided by wl-output.  On compositors such as GNOME where this is provided, the display names provided to applications by SDL will now match those in the desktop display settings panel.  On compositors where this data isn't provided, the old behavior of using the model string provided by wl-output will remain unchanged.
Additionally, per the protocol spec, information provided by xdg-output should supersede that provided by wl-output, so this is the recommended behavior in general.
=> wayland: Use the output descriptions from xdg-output when available

.github/workflows/main.yml, CMakeLists.txt, SDL2Config.cmake.in, sdl2-config.cmake.in
- Always create a `SDL2::SDL2` target.
By default it will be the shared library. When that library is not built, not installed or not available on a platform.
`SDL2::SDL2` will then be equivalent to `SDL2::SDL2-static`.
Fixes #2010
- Build SDL2 with MinGW clang on CI
=> Test with MinGW clang + always create SDL2::SDL2

src/render/direct3d12/SDL_render_d3d12.c
See https://github.com/libsdl-org/SDL/pull/5778#issuecomment-1153006938
(CC: @chalonverse, @ericwa)
=> update SDL_render_d3d12.c after DPI scaling/highdpi support patch.

src/video/wayland/SDL_waylandevents.c
This PR makes SDL pass the correct `libdecor_resize_edge` enums instead of `xdg_toplevel_resize_edge` enums to `libdecor_frame_resize()`.
`libdecor_resize_edge` and `xdg_toplevel_resize_edge` are **not interchangeable**. `xdg_toplevel_resize_edge` enums are machine generated via the wayland-protocol XMLs and can be different than what is initially thought.
closes #5801
=> wayland: use libdecor resize edge enums for libdecor

.github/workflows/emscripten.yml, .github/workflows/main.yml, .github/workflows/msvc.yml, .github/workflows/psp.yaml, .github/workflows/riscos.yml, .github/workflows/vita.yaml
This is currently a draft because some tests aren't building properly with Emscripten and I'm not sure how to fix it.
Includes changes from #5635 and #5636. See also issue #5634.
=> Build tests for all CMake platforms on CI

CMakeLists.txt
The result variables: HAVE_${VARIABLE}, ${VARIABLE}, ${VARIABLE}_CODE, etc. do not seem to be referenced anywhere in the CMake build script. Unless I was mistaken on how the check is being used.
The motivation for me to have the redundant check removed is because otherwise it would cause an error in my SDL initial build tree generation with my own custom `Emscripten.cmake` toolchain file. My custom CMake toolchain file is much simpler version than the official one provided by EMSDK, which does not provide the "hack" version of the `CheckTypeSize.cmake`.
But in any case, there should be no harm to have this redundant check removed for other use cases.
My Web CI build can be found here: https://github.com/alpha-scorpii-b/SDL/runs/3383479743?check_suite_focus=true
=> Remove redundant sizeof "size_t" check

test/testautomation_math.c
On i686-linux, the `sqrt_regularCases` and `atan_limitCases` tests would fail as the result was not precise enough.
This fix uses the `EPSILON` to check a range instead of an exact value.
This was pointed out by @sezero in #5614
=> Test: Check sqrt and atan against the epsilon.

CMakeLists.txt
FreeBSD includes the libunwind APIs in in the base system libgcc_s and
does not install a .pc file for it.
This change fixes the build on FreeBSD for me.
=> cmake: freebsd: Don't REQUIRE libunwind.pc on FreeBSD

VisualC/pkg-support/cmake/sdl2-config.cmake
=> cmake: fix location of include dir for SDL2 VC sdk

include/SDL_config_minimal.h
Without using <inttypes.h>, SDL_PRIx64 will expand to llx, but on 64-bit
FreeBSD platforms (u)int64_t is `(unsigned) long`:
```
SDL_test_memory.c:261:77: error: format specifies type 'unsigned long long' but the argument has type 'Uint64' (aka 'unsigned long') [-Werror,-Wformat]
```
This commit updates config_minimal.h to also assume presence of inttypes.h
for everything except old MSVC.
=> cmake: freebsd: Fix -Wformat warning during tests build

src/core/linux/SDL_fcitx.c
If the condition `(dbus->message_iter_get_arg_type(&sub) == DBUS_TYPE_STRING)` is false, subtext is not initialised. Then it is read on line 131.
You need to initialise it in the loop, otherwise you could add the length of the same `substring` to `pos` several times.
None
=> Fix read of uninitialised variable

src/joystick/vita/SDL_sysjoystick.c
Adding the missing `GetGamepadMapping` function to the Vita Joystick driver for fixing #5832
Closes #5832
=> [VIta] Adding GetGamepadMapping to Joystick driver

CMakeLists.txt, test/CMakeLists.txt
After https://github.com/libsdl-org/SDL/pull/5812, the generated `SDL_config.h` is created in another build include folder that was not in the include path of dependencies and was also not installed.
I was comparing with my distro's SDL2 include file tree when doing that pr, looks like this has changed since then.
@fjtrujy @sharkwouter  Does this address https://github.com/libsdl-org/SDL/issues/5823?
=> cmake: use and install generated SDL_config.h

src/joystick/psp/SDL_sysjoystick.c
Remove the unnecessary mutex, semaphore, and threads used in the PSP keyboard driver.
Tested by @sharkwouter
=> [PSP] Improve Joystick driver

.github/workflows/msvc.yml, CMakeLists.txt
[](https://github.com/libsdl-org/SDL/blob/main/CMakeLists.txt#L3122
Sets `SDL2Config.cmake` to `CMAKE_BINARY_DIR`, whereas the install file tries to find it from a different location.)
This fixes problems with trying to `cmake install` about `SDL2Config.cmake` not existing. 
Seems to occur from
https://github.com/libsdl-org/SDL/commit/5ec2d46f476f5019d1d0bb8345b7f6f79222d0c1
=> Update install directory to match generated

CMakeLists.txt, cmake/sdlchecks.cmake
By adding the generated headers to only one target, on which all other targets depend, the headers should only get generated by 1 rule.
Fixes #5849
@isage Can you test this pr?
I cannot reproduce with an old CMake 3.0.2 + GNU make 4.1.
=> cmake: add generated headers to dummy target

src/core/windows/SDL_windows.h, src/render/SDL_d3dmath.h, src/render/SDL_sysrender.h, src/render/direct3d12/SDL_render_d3d12.c, src/render/direct3d12/SDL_shaders_d3d12.h, src/video/windows/SDL_windowswindow.h
This PR makes it possible to compile `SDL_render_d3d12.c` in C++ mode. The reason this is desirable is for future Xbox support, as the core DirectX headers are slightly different and only compile in C++. Without this change, we would need to maintain an entirely separate DirectX 12 renderer file for Xbox support.
Supporting C++ compilation mainly just involves declaring a few macros and using those. For example, instead of writing code like:
```c
ptr->lpVtbl->Func(ptr, arg1, arg2)
```
You instead write:
```c
D3D_CALL(ptr, Func, arg1, arg2)
```
Then, it can correctly translate to either the C version or C++ version of the call. I think this also makes the existing code a little bit more readable.
The only other changes are adding additional `extern "C"`s in a few places if `__cplusplus` is …
=> Add support for SDL_render_d3d12.c to compile in C++ mode

src/render/vitagxm/SDL_render_vita_gxm_tools.c
=> Vita: create rendertarget color surface with same format as texture.

src/cpuinfo/SDL_cpuinfo.c
Use the proper header for PPC CPU detection code. sys/param.h includes
sys/types, but sys/types.h is the more appropriate header to be used
here.
=> Use proper header for OpenBSD PPC CPU detection

src/audio/coreaudio/SDL_coreaudio.m, src/file/cocoa/SDL_rwopsbundlesupport.m, src/filesystem/cocoa/SDL_sysfilesystem.m, src/hidapi/mac/hid.c, src/joystick/darwin/SDL_iokitjoystick.c, src/joystick/iphoneos/SDL_mfijoystick.m, src/render/metal/SDL_render_metal.m, src/timer/unix/SDL_systimer.c, src/video/cocoa/SDL_cocoaevents.m, src/video/cocoa/SDL_cocoakeyboard.m, src/video/cocoa/SDL_cocoamessagebox.m, src/video/cocoa/SDL_cocoamodes.m, src/video/cocoa/SDL_cocoamouse.m, src/video/cocoa/SDL_cocoaopengl.m, src/video/cocoa/SDL_cocoaopengles.m, src/video/cocoa/SDL_cocoashape.m, src/video/cocoa/SDL_cocoawindow.m
With the upcoming release of Xcode 14 shipping with Clang 14, the warning `declaration-after-statement` will be checked regardless of the C standards. This change makes macOS modules failing to build as they were not designed around this. This PR updates the affected modules to fix build with LLVM/Apple Clang 14. 
Fixes #5846.
=> Fix C89 declaration for macOS modules.

docs/README-gdk.md
There is an additional .dll file that needs to be in the exe directory for GDK projects to work. See #5856.
=> Add note to GDK docs about XCurl.dll

include/SDL_hints.h, src/haptic/windows/SDL_dinputhaptic.c, src/joystick/windows/SDL_dinputjoystick.c
It's what it says on the tin: Add `SDL_HINT_DIRECTINPUT_ENABLED`, which behaves like `SDL_HINT_XINPUT_ENABLED` but for DirectInput / DInput.
I've tried to stay close to the existing checking behavior in the XInput implementation, but checking against `dinput != NULL` instead of a new bool variable. This also matches existing parts of the DirectInput haptic implementation.
As to why I'm submitting this PR: In some environments, `IDirectInput8_Initialize` / `_EnumDevices` can take a minute even with no controllers plugged in. It's suspected that this might be caused by faulty drivers, but given how it's easier to live with XInput only, than to deal with wontfix user reports about buggy drivers, I've bit the bullet and am now submitting this PR.  
It's already possible to compile SDL2 …
=> Add SDL_HINT_DIRECTINPUT_ENABLED

src/main/ps2/SDL_ps2_main.c
This PR loads the necessary drivers for the filesystem in the SDL_main initialization for PS2.
Now we support:
- Memory card
- USBs
- Host
Thanks
=> [PS2] SDL MAIN improvements

src/render/direct3d12/SDL_render_d3d12.c
This change also removes the vertex buffer size limit. Turning on batching seems to give about a 40% speed boost in my testing of some of the tests.
Related to #5861
=> Fixed D3D12 renderer not working with batching

src/joystick/hidapi/SDL_hidapijoystick.c
The HIDAPI joystick driver doesn't properly reset the change counter it uses to track if re-enumeration is needed when the joystick subsystem is quit and then reinitialized.
The first SDL_Init(SDL_INIT_JOYSTICK) will result in the expected HIDAPI joysticks appearing, but subsequent calls will result in no joysticks being enumerated until another HIDAPI joystick is added or removed from the system.
This issue impacted Moonlight on the Steam Link and was reported downstream as https://github.com/moonlight-stream/moonlight-qt/issues/816
=> joystick: Fix redetection of HIDAPI joysticks after reinitializing

include/SDL_assert.h, include/begin_code.h
This convention is already used elsewhere in the repo -- looks like just these 2 places were not.
=> Check if GNUC is defined before checking its value to solve MSVC warns

test/testfilesystem.c
The binary generated for the `testfilesystem.c` file is called `testfilesystem` (if it has no extension as the `PS2` ones).
The test checks if the `filesystem` driver works fine by creating some folders.
The thing is that the line:
```c
pref_path = SDL_GetPrefPath(NULL, "testfilesystem");
``` 
Could create a folder called `testfilesystem` in the same folder where the binary `testfilesystem` is (`PS2` and other platforms uses `cwd` as the base path), generating an error. 
It is not possible to have in the same folder a filename without an extension and a folder with the same "name"
This PR changes the name of the folder created, to assure that it won't fail for this specific error.
Cheer
=> Rename folder created in test_filesystem

src/stdlib/SDL_string.c
`strchr` and `strrchr` return a pointer to the first/last occurrence of a character in a string, or `NULL` if the character is not found. According to the C standard, the final null terminator is part of the string, and it should thus be possible to get a pointer to the final null with these functions. The fallback implementations of `SDL_strchr` and `SDL_strrchr` would always return `NULL` if trying to find `'\0'`, and this commit fixes that.
=> Fix fallback implementations of SDL_strchr and SDL_strrchr for '\0'

src/atomic/SDL_spinlock.c
When building on macOS without gcc (e.g. clang) where HAVE_GCC_ATOMICS
is not defined, `SDL_AtomicTryLock` will call
`OSAtomicCompareAndSwap32Barrier` which is not yet declared.
Including OSAtomic.h on OSX resolves this error/warning:
SDL_spinlock.c:125:12: error: implicit declaration of function
'OSAtomicCompareAndSwap32Barrier' is invalid in
C99 [-Werror,-Wimplicit-function-declaration]
return OSAtomicCompareAndSwap32Barrier(0, 1, lock);
This was reported in issue #3885 but marked Invalid and closed - possibly
because the default CMake build uses gcc instead of clang.
=> Added include: libkern/OSAtomic.h

src/SDL_log.c
Add the missing string entries to the table, and add a static assert so this is less likely to happen in the future.
Fixes #5883
I can't test this locally, relying on CI.
=> android: Add missing entries to SDL_category_prefixes table.

src/joystick/hidapi/SDL_hidapi_xbox360.c, src/joystick/hidapi/SDL_hidapi_xbox360w.c, src/joystick/hidapi/SDL_hidapi_xboxone.c
The Xbox 360/360W/One HIDAPI drivers don't work properly on big-endian architectures because they don't byteswap the LE 16-bit axis values they read.
Thanks to @sezero for pointing this out in #5900.
=> joystick: Fix endianness issues in Xbox HIDAPI drivers

configure.ac
SDL makes assumption that each dynamically loaded library must have
SONAME matching pattern <libname>.so.<digit>+ hence it discards any file
that has two (or more) digits after ".so". in practice however SONAME
might be in the form of ie <libname>.so.<major>.<minor>.
as a solution keep requirement for dynamically loaded files to be named
<libname>.so.* but consider all the possibilities and prefer the shortest
one.
https://github.com/libsdl-org/SDL_image/issues/289
=> autotools: relax soname pattern for dynamic loading

Makefile.w32, VisualC-GDK/SDL/SDL.vcxproj, VisualC-GDK/SDL/SDL.vcxproj.filters, VisualC/SDL/SDL.vcxproj, VisualC/SDL/SDL.vcxproj.filters, src/audio/directsound/SDL_directsound.c, src/audio/wasapi/SDL_wasapi.c, src/audio/wasapi/SDL_wasapi.h, src/audio/wasapi/SDL_wasapi_win32.c, src/audio/wasapi/SDL_wasapi_winrt.cpp, src/core/windows/SDL_immdevice.c, src/core/windows/SDL_immdevice.h
This is a draft, because:
Other than that, this was actually really easy! We're mostly looking at cleanup, but still wanted to get Ryan's eyes on this as soon as I had something building.
Fixes #5750
=> windows: Move IMMDevice work to common file, implement DirectSound enumeration support

include/SDL_audio.h, src/audio/SDL_audio.c, src/audio/SDL_sysaudio.h, src/audio/directsound/SDL_directsound.c, src/audio/pipewire/SDL_pipewire.c, src/audio/pulseaudio/SDL_pulseaudio.c, src/audio/wasapi/SDL_wasapi.c, src/audio/wasapi/SDL_wasapi.h, src/audio/wasapi/SDL_wasapi_win32.c, src/audio/wasapi/SDL_wasapi_winrt.cpp, src/core/windows/SDL_immdevice.c, src/core/windows/SDL_immdevice.h, src/dynapi/SDL2.exports, src/dynapi/SDL_dynapi_overrides.h, src/dynapi/SDL_dynapi_procs.h
Currently this is supported on pipewire, pulseaudio, and wasapi.
~~This is flagrantly untested!~~ Also, I haven't looked at CoreAudio, but I probably won't since I'm pretty far removed from Apple stuff at this point.
Fixes #5866
=> Add SDL_GetDefaultAudioInfo

src/audio/pipewire/SDL_pipewire.c
A few Pipewire cleanups on top of the recent changes:
- Removes a deprecated config key not relevant since 0.3.21 since 0.3.24 is the new minimum.
- Persist the default sink/source metadata node to allow for updating the defaults during runtime if they change on the OS side.
- Remove the FIXME by dynamically allocating the name and path string buffer for IO nodes.
@flibitijibibo
=> Pipewire cleanups

src/filesystem/unix/SDL_sysfilesystem.c
The PWD environment variable is the initial CWD when the process is first launched, and does not change after its initial state even when the CWD is changed at any point in time after process execution. The only time PWD will not be the path we want afaik is when the environment variable is changed manually by the user in their code or by the shell, which most users and software will not likely do that. This should be more accurate than the CWD.
Tested with `~/main.cpp` below:
```
#include <cstdio>
#include <unistd.h>
#include <SDL_filesystem.h>
#include <SDL_stdinc.h>
char *data_path = nullptr;
void InitializeDataPath() {
char *base_path = SDL_GetBasePath();
if (base_path) {
/* works if argv[0] is a relative path and 
$PWD is correctly set, exe found in $PATH,
or argv[0] is an absolute …
```
=> (OpenBSD) Exe Path: Use PWD instead of CWD and use CWD as fallback

src/video/wayland/SDL_waylandwindow.c
Currently, the ``SDL_WINDOWEVENT_RESIZED`` event is sent before the actual window is resized (and various internal state, such as the desired GL/Vulkan backbuffer size, are updated). This makes sense, as SDL will discard a no-op resize, which would be the case if we had resized before sending the event (indeed, there are existing hacks to prevent this).
However, this means that ``SDL_{GL,Vulkan}_GetDrawableSize()`` will still use the old size in the ``SDL_WINDOWEVENT_RESIZED`` handler. In the case of ``SDL_Renderer``, this means the drawable size it uses will be wrong, and the viewport will get "updated" to the old value.
This then results in bug #5899.
=> video: wayland: Resize the window before sending the SDL_RESIZE event (Fix #5899)

include/SDL_video.h
Extend the SDL_WINDOW_ALLOW_HIGHDPI flag documentation to stress the importance of querying the window drawable size after every window event to avoid rendering issues in a mixed-DPI environment.
=> video: Improve the SDL_WINDOW_ALLOW_HIGHDPI flag documentation

src/render/opengles2/SDL_shaders_gles2.c
This changes SDL_Render's OpenGL ES 2 backend to use high precision (32 bit float, usually) texture coordinates in fragment shaders, when supported. Previously it would use `mediump` which was often 16 bit float or less, which isn't always enough precision to accurately render subsections of large textures.
#5884
=> SDL_Render: use high precision texcoords in ES2 shaders, when possible

src/video/wayland/SDL_waylandwindow.c
Otherwise libdecor doesn't have a chance to acquire xdg-toplevel after
libdecor_new before we attempt to use it in Wayland_ShowWindow.
Fixes #5952
=> video: wayland: Roundtrip after falling back to libdecor in xdg-decoration handler

src/video/wayland/SDL_waylandwindow.c
We actually request CSD mode with xdg-decoration for borderless
windows, so we get what we wanted there and there's no point in going
into fallback paths.
=> video: wayland: Don't switch to libdecor path for borderless windows

src/video/SDL_video.c, src/video/cocoa/SDL_cocoawindow.m
With the introduction of this function, it is possible that for certain monitor and window configurations, creating an SDL window will cause a native crash.
```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000050
Exception Codes:       0x0000000000000001, 0x0000000000000050
Exception Note:        EXC_CORPSE_NOTIFY
Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [56627]
VM Region Info: 0x50 is not in any region.  Bytes before following region: 140737486737328
REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
UNUSED SPACE AT START
--->
VM_ALLOCATE …
```
=> Fix `Cocoa_GetWindowDisplayIndex` failing and causing a catastrophic crash

src/events/SDL_events.c
Improves the behavior of `SDL_HINT_AUTO_UPDATE_JOYSTICKS` and `SDL_HINT_AUTO_UPDATE_SENSORS` to properly respond to changes and allow for them to control if the event loop is forced into a polling mode or not.
`SDL_HINT_AUTO_UPDATE_JOYSTICKS` and `SDL_HINT_AUTO_UPDATE_SENSORS` are supposed to help control the values of `SDL_update_joysticks` and `SDL_update_sensors` respectively, but due to an order of operations issue changing just a hint value was not enough to change the update variables. This change fixes that bug.
Additionally, the values of `SDL_update_joysticks` and `SDL_update_sensors` are used to determine if `SDL_JoystickUpdate()` and `SDL_SensorUpdate()` should be called by the event loop. In order to call these functions, the event loop will use a less efficient polling mode …
=> Event loop fixes

src/SDL_assert.c
otherwise SDL_PromptAssertion (and SDL_GenerateAssertionReport) can not be eliminated
=> hide SDL_GenerateAssertionReport in case SDL_ASSERT_LEVEL is 0

src/video/cocoa/SDL_cocoaevents.m, src/video/cocoa/SDL_cocoawindow.h, src/video/cocoa/SDL_cocoawindow.m
Cache off NSWindow's windowNumber in SDL_WindowData on setup and use that in `Cocoa_SendWakeupEvent` to prevent accessing windowNumber off the main thread.
Documentation seems to imply that the windowNumber value is unique per window, which implies to me that it won't change over the lifetime of the window, so caching it on create should be safe.
#5796
=> Fix Main Thread Checker warning on macOS

.github/workflows/main.yml
Adds the `CMAKE_OSX_ARCHITECTURES` flag to make the macOS CI create a universal build.
=> CI: Make macOS universal build with CMake.

CMakeLists.txt
This fixes the following error when building with `SDL_LIBC` enabled:
SDL\test\testautomation_math.c(1965): error C2065: 'M_PI': undeclared identifier
Part of #5969, but committed separately
=> Check for presence of M_PI macro in math.h

sdl2.pc.in
There are a lot of programs that use `SDL2` by explicitly including <SDL2/SDL.h>. On most platforms, this may not be the problem, as `${includedir}` should has already been included by the compiler somewhere, e.g. `/usr/include` or `/usr/local/include`. But on the new M1 macOS, `/opt/homebrew/include` has not been(at least for now) such a standard directory to include by compiler or environment.
I think we can support including SDL2 by `<SDL2/SDL.h>`.
=> Compatible with including as <SDL2/SDL.h>

CMakeLists.txt, include/SDL_config.h.cmake, src/stdlib/SDL_mslibc.c
Fixes https://github.com/libsdl-org/SDL/issues/5156
Fixes https://github.com/libsdl-org/SDL/issues/1685
https://github.com/libsdl-org/SDL/issues/5156#issuecomment-1195884090 explains it all:
- ~Group all functions, normally part of the C library, and possibly emitted by the compiler into a dedicated source and disable LTO on that.~ => moved to #5974
- Always use the system C library when using the static SDL2 library.
=> Use the System C library when building/using a static SDL2, on Windows

src/core/linux/SDL_threadprio.c
Use the xdg-desktop-portal interface to RealtimeKit1, when available, to set realtime scheduling and elevated priority for threads.  This portal handles pid/tid mapping to allow for the use of rtkit within containers such as Flatpak.  It will fall back to using RealtimeKit1 directly if the xdg-desktop-portal interface is too old or not available.
The realtime portal interface had some breaking bugs until very recently (type mismatches with rtkit and a lack of thread ID mapping in containers), so checking that the RTTimeUSecMax property is an int64, where it was previously incorrectly set as an int32, should be a reliable flag that the portal is the newer, fixed version, otherwise it always falls back to using RealtimeKit1 directly. All of the appropriate patches are now merged upstream, …
=> core: linux: Favor xdg-desktop-portal for elevating thread priority

.github/workflows/main.yml, docs/README-linux.md
The Ubuntu 22.04 environment is currently in beta, but allows compatible versions of PipeWire and libdecor to be installed more easily.
=> Update the list of required Ubuntu packages, and add Ubuntu 22.04 workflows

src/events/SDL_keyboard.c, src/events/SDL_keyboard_c.h, src/video/android/SDL_androidkeyboard.c, src/video/cocoa/SDL_cocoakeyboard.m, src/video/directfb/SDL_DirectFB_events.c, src/video/wayland/SDL_waylandevents.c, src/video/windows/SDL_windowsevents.c, src/video/windows/SDL_windowskeyboard.c, src/video/windows/SDL_windowskeyboard.h, src/video/x11/SDL_x11events.c, src/video/x11/SDL_x11keyboard.c, src/video/x11/SDL_x11keyboard.h
This implements the suggestion in https://github.com/libsdl-org/SDL/issues/5520#issuecomment-1101882674 to avoid sending duplicate SDL_KEYMAPCHANGED events if the keymap didn't actually change.
Fixes #5564
=> keyboard: Only send SDL_KEYMAPCHANGED when the keymap actually changes

src/events/SDL_keyboard.c, src/events/SDL_keyboard_c.h, src/video/android/SDL_androidkeyboard.c, src/video/android/SDL_androidkeyboard.h, src/video/android/SDL_androidvideo.c, src/video/directfb/SDL_DirectFB_events.c
During my work on #5984, I discovered that there is a subtle mapping inconsistency created by the [AZERTY fixup](https://github.com/libsdl-org/SDL/blob/8b438f7b51013a6494f385e26dd061e050a65f68/src/events/SDL_keyboard.c#L605-L612) that `SDL_SetKeymap()` performs. Since `SDL_KeyboardInit()` copies the default keymap directly, that fixup doesn't happen for video backends that never call `SDL_SetKeymap()` (even if they just pass the default keymap). Fixing that allows us to eliminate redundant calls to `SDL_SetKeymap()` that pass the unmodified default keymap.
I'm not sure if the AZERTY thing is necessarily a good idea (see comment thread in #5127), but if we're going to do it, we should probably at least do it consistently.
=> keyboard: Fix default keymap inconsistency and remove no-op SDL_SetKeymap() calls

src/joystick/hidapi/SDL_hidapijoystick.c
`device->children` is never freed.
In `HIDAPI_CreateCombinedJoyCons()`, `children` need to be freed in case of error.
None
=> Fix memory leak of children for combined JoyCon

src/joystick/hidapi/SDL_hidapi_switch.c
ReadJoyConControllerType calls WriteSubcommandSync with pbuf=NULL.
Full callstack:
line 1027 in: ReadJoyConControllerType(SDL_HIDAPI_Device *device)
line 1041 calling: WriteSubcommandSync(ctx, k_eSwitchSubcommandIDs_RequestDeviceInfo, NULL, 0, &reply); // 3rd parameter 'pBuf' is NULL
line 568  calling: ConstructSubcommand(ctx, ucCommandID, pBuf, ucLen, &commandPacket); // 'pBuf' is NULL
line 496: SDL_memcpy(outPacket->rgucSubcommandData, pBuf, ucLen); // 'pBuf' is NULL
None
=> Do not pass NULL to memcpy

src/audio/wasapi/SDL_wasapi_winrt.cpp, src/core/windows/SDL_immdevice.c
I am not sure if `devid` is unique so I made this patch.
If they are unique, you could return after finding the right device, instead of using this patch.
None
=> Fix use after free when removing Windows audio device

src/video/ps2/SDL_ps2video.c
This PR basically creates the `CreateSDLWindow` method on the PS2 Video driver.
Main purpose is to call `SDL_SetKeyboardFocus(window);` there.
Cheers
=> [PS2] Implement create windows method

src/render/ps2/SDL_render_ps2.c
Currently, the PS2 render driver wasn't able to make it work properly with the examples `testoverlay2` and `teststreaming`, it was showing an static image.
In this PR we solve the problem by invalidating the texture in the UnlockTextureMethod.
Cheers
=> [PS2] Render Driver - Fix Streaming Textures

src/video/wayland/SDL_waylandwindow.c
The current method of toggling the libdecor window visibility by destroying and recreating the frame results in a race where a use-after-free bug can manifest itself within libdecor when window visibility is toggled quickly. Instead, use the libdecor function for toggling visibility instead of destroying and recreating the frame every time.
Fixes the memory corruption crash when stress-testing hide/show functionality with libdecor described in #5672
=> wayland: Use libdecor visibility toggle for hiding/showing the window

src/core/linux/SDL_evdev.c
Adds `SDL_EVDEV_DEVICES` environment variable which allows the user to explicitly specify a list of input devices of the form:
```
deviceclass:path[,deviceclass:path[,...]]
```
where `deviceclass` is an integer representing the `SDL_UDEV_deviceclass` and `path` is the full path to the event device file.
This is only used in non-udev mode.
=> evdev: Support user-provided devices via SDL_EVDEV_DEVICES in non-udev mode.

src/video/SDL_sysvideo.h, src/video/SDL_video.c, src/video/dummy/SDL_nullvideo.c
Specifying `SDL_VIDEODRIVER=evdev` in the environment (or via hints) enables a device akin to the original "dummy" video device but with evdev support such that `SDL_WaitEvent` will capture input events without a window or graphics context.
=> Support evdev-only psuedo-device with no video.

CMakeLists.txt
External .c files are brought in that don't adhere to this requirement for
pre-C99 code and causes the build to break with the latest NDK.
Fixes #6019
=> Disable declaration-after-statement warning on Android

src/joystick/SDL_gamecontrollerdb.h
We had some wrong values in the `SDL_gamecontrollerdb.h` for `PS2`:
- `lefttrigger` was missing
- `righttrigger` was missing
- `rightshoulder` had wrong value
Cheers
=> [PS2] Fix wrong mapping in some ps2 controller keys

docs/README-ps2.md, include/SDL_main.h, src/main/ps2/SDL_ps2_main.c
This PR includes:
- Add USB filesystem support to the `SDL_main`
- Offer the possibility of avoiding the reset of the IOP CPU. That's is useful in the case that a user is debugging the PS2 app through `ps2link/ps2client`, if we reset IOP, we lose the connection with the console.
- Create a macro to make it easier for the developers to avoid resetting the IOP.
- Updated the readme with that specific functionality as an additional note.
=> [PS2] SDL_main - General improvements

src/joystick/windows/SDL_windows_gaming_input.c
QI for Added/Removed events need to handle IAgileObject
The app (dolphin emulator) has its own WGI code which also registers Added/Removed event handlers. Without this change, the events stop firing after the first one for both dolphin's WGI code and SDL's WGI code. Generally, device detection stops working (even if event handlers aren't explicitly used).
=> WGI: fix interop with applications that have their own WGI code

include/SDL_hints.h, src/video/cocoa/SDL_cocoaopengl.m
Since https://github.com/libsdl-org/SDL/pull/4242, context updates get dispatched without blocking the current thread. And while that works fine with OpenGL drivers on intel-powered mac GPUs, it doesn't play well on M1, which uses a OpenGL-to-Metal wrapper driver (`AppleMetalGLRenderer`), thus failing with the error seen in #5203:
```
-[AGXG13XFamilyCommandBuffer renderCommandEncoderWithDescriptor:]:380: failed assertion `A command encoder is already encoding to this command buffer'
```
I haven't investigated through the issue with the M1's wrapper in detail, but I'm opening this PR in the interim to workaround it, as this has been quite annoying in my workflow as an M1 user.
I have considered forcing `dispatch_sync` on M1 machines rather than a hint, but it would mean bringing back …
=> macOS: Add hint for blocking thread on OpenGL context update dispatch

test/testautomation_math.c
On Win32, the `exp_baseCase` from the Math test suite would fail from lack of precision.
=> Test: Fix Exp base case for Win32.

src/video/wayland/SDL_waylandwindow.c
#5450 reintroduced some duplicate `SDL_WINDOWEVENT_SIZE_CHANGED` and `SDL_WINDOWEVENT_RESIZED` events that I had addressed in #5232.
This can be noted when running `testgl2` on Wayland with `SDL_EVENT_LOGGING=1` and pressing Alt+Enter to enter fullscreen.
Before this fix:
```
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=675237 windowid=1 event=SDL_WINDOWEVENT_SIZE_CHANGED data1=1503 data2=1002)
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=675237 windowid=1 event=SDL_WINDOWEVENT_RESIZED data1=1503 data2=1002)
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=675240 windowid=1 event=SDL_WINDOWEVENT_SIZE_CHANGED data1=1503 data2=1002)
INFO: SDL EVENT: SDL_WINDOWEVENT (timestamp=675240 windowid=1 event=SDL_WINDOWEVENT_RESIZED data1=1503 data2=1002
```
After the fix:
```
INFO: SDL EVENT: …
```
=> wayland: Avoid duplicate resize events when entering fullscreen

src/video/cocoa/SDL_cocoawindow.m
76afb8583b39305cf73191664c0015a8ee2400d4 introduced a regression when creating a new window on a secondary display using `SDL_WINDOWPOS_CENTERED_DISPLAY()`. Windows created this way are always placed on display 0 instead of where the caller wanted.
`SDL_CreateWindow()` may call `GetWindowDisplayIndex()` to compute the position of a new window that the caller has requested to be placed on a certain display. Since we haven't fully constructed the window yet, our driverdata will be nil and we will fail to get the NSScreen (which is fine). However, we need to return an error (not 0, which is a valid display index) for `SDL_GetWindowDisplayIndex()` to know to figure out the display index itself.
We should probably do something to avoid calling `GetWindowDisplayIndex()` before window …
=> cocoa: Return an error if GetWindowDisplayIndex() is called too early

src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
Don't call the roundtrip in ShowWindow unless restoring a previously hidden window.  This fixes a regression in GNOME when creating a window with the fullscreen flag set, as the fullscreen window will be offset down the screen the height of the top bar if the window is made fullscreen on the primary display and the roundtrip is called when initially displaying the window.
=> wayland: Don't roundtrip in ShowWindow unless restoring a hidden window

src/audio/ps2/SDL_ps2audio.c
Currently, the audio thread has the same priority as the main thread, with this PR we follow the same approach as other platforms, where we are setting a lower priority when the audio thread is created.
=> [PS2] Decrease audio thread priority when created

src/render/ps2/SDL_render_ps2.c
Be sure that we are deallocating the VRAM memory when destroying texture.
Additionally, also be sure that we are setting the driverdata from the texture to NULL
`texture->driverdata = NULL;` 
Cheers
=> [PS2] Fix memory leak when destroying texture

src/video/SDL_sysvideo.h, src/video/SDL_video.c, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
Eliminate excessive calls to `SetFullscreen` by removing the calls in the libdecor and xdg-toplevel config callbacks.
These calls were being made there in case something explicitly called the window minimization function from within SDL, which unsets fullscreen, and as minimizing a window in Wayland is just a suggestion to the compositor and doesn't actually change the window state or communicate anything back to the application, it was necessary to call SetFullscreen in every call to the config functions just in case something minimized a window via `SDL_MinimizeWindow()` and later needed to restore it.  GNOME in particular had issues with strange behavior when fullscreen set/unset operations were being hammered and commits were being performed on surfaces while switching to fullscreen. …
=> video: wayland: Remove excessive SetFullscreen calls

test/testgles2.c
Fixes a typo in #6065 that led to help text for `--threaded` being printed incorrectly
=> testgles2: Fix typo in help text

src/video/wayland/SDL_waylandwindow.c
If libdecor performs a commit with the frame title being undefined, a crash can occur within the library or its plugins. Always ensure that the title is set to a valid string to avoid this.
Fixes the Pango crash in #6074
=> wayland: Never commit with an undefined window title

src/video/wayland/SDL_waylandwindow.c
Set the frame app ID after toggling visibility or the name displayed in window manager task switchers may not display correctly.
Edit: This is a regression bugfix for 2.24 if possible.
=> wayland: Set the libdecor app ID after visibility calls

src/video/kmsdrm/SDL_kmsdrmsym.h, src/video/kmsdrm/SDL_kmsdrmvideo.c
This PR contains changes to the kmsdrm backend to enable Variable Refresh Rate on displays that support it during initialization.
=> kmsdrm: enable vrr on displays that support it

include/SDL_atomic.h
Neither modern gcc:
```
$ gcc -mfpu=neon-vfpv4 -dM -E -x c /dev/null | grep -i -E ARM
#define __ARM_SIZEOF_WCHAR_T 32
#define __ARM_FEATURE_SAT 1
#define __ARM_ARCH_ISA_ARM 1
#define __ARMEL__ 1
#define __ARM_FEATURE_UNALIGNED 1
#define __ARM_FP 14
#define __ARM_NEON_FP 6
#define __ARM_SIZEOF_MINIMAL_ENUM 4
#define __ARM_PCS_VFP 1
#define __ARM_FEATURE_LDREX 4
#define __ARM_FEATURE_QBIT 1
#define __ARM_FEATURE_FMA 1
#define __ARM_NEON__ 1
#define __ARM_ARCH_6__ 1
#define __ARM_32BIT_STATE 1
#define __ARM_FEATURE_CLZ 1
#define __ARM_ARCH_ISA_THUMB 1
#define __ARM_ARCH 6
#define __arm__ 1
#define __ARM_FEATURE_SIMD32 1
#define __ARM_NEON 1
#define __ARM_EABI__ 1
#define __ARM_FEATURE_DSP 1
```
nor modern clang:
```
$ clang -march=armv7 -dM -E -x c /dev/null | grep -i -E ARM 
#define …
```
=> Use __ARM_ARCH instead of __ARM_ARCH__

sdl2-config.cmake.in
The static `libSDL2.a` library might require external libraries, which might be located in non-standard locations.
The patch of this pr extracts these paths from the exported autotools variables and adds them to appropriate properties of the imported targets.
`pthread` also needs special care.
Fixes https://github.com/libsdl-org/SDL/issues/6094
Candidate for 2.24.1 (is there a label for this?)
=> cmake: add library directories & pthread to imported targets of sdl2-config.cmake

src/video/wayland/SDL_waylanddyn.h, src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandevents_c.h, wayland-protocols/wayland.xml
Updates the Wayland core protocol spec file and adds support for the new axis_value120 event to support high resolution scroll wheels.  This new event replaces axis_discrete in version 8 of the protocol and higher and delivers values in increments of 1/120 of a logical scroll step.  Unlike axis_discrete, axis_value120 makes no guarantees about only delivering one event per-axis per-frame, so values are accumulated and committed during the frame event.
A minor include header order change was needed as well, as the libdecor headers were pulling in the older, system provided Wayland core protocol header file instead of the newer, locally generated one.
Marked as draft for now, as this protocol is quite new and this needs testing.
=> wayland: High resolution scroll wheel support

src/video/cocoa/SDL_cocoashape.h, src/video/cocoa/SDL_cocoashape.m
Objective-C with ARC works best when Objective-C objects have direct references in other ObjC objects instead of in C structs. In #5632 I changed most of the Cocoa backend code to use this convention but missed the shaped window code. Apparently this caused compilation problems on some systems, but not on mine.
Fixes #6089
I also think I discovered #6104 while making this change.
=> cocoa: change Shape data to use ObjC objects instead of C structs.

src/joystick/SDL_gamecontroller.c, src/joystick/SDL_joystick.c, src/joystick/SDL_joystick_c.h, src/joystick/SDL_sysjoystick.h, src/joystick/android/SDL_sysjoystick.c, src/joystick/bsd/SDL_bsdjoystick.c, src/joystick/darwin/SDL_iokitjoystick.c, src/joystick/emscripten/SDL_sysjoystick.c, src/joystick/haiku/SDL_haikujoystick.cc, src/joystick/hidapi/SDL_hidapijoystick.c, src/joystick/iphoneos/SDL_mfijoystick.m, src/joystick/linux/SDL_sysjoystick.c, src/joystick/os2/SDL_os2joystick.c, src/joystick/ps2/SDL_sysjoystick.c, src/joystick/psp/SDL_sysjoystick.c, src/joystick/virtual/SDL_virtualjoystick.c, src/joystick/vita/SDL_sysjoystick.c, src/joystick/windows/SDL_dinputjoystick.c, src/joystick/windows/SDL_rawinputjoystick.c, src/joystick/windows/SDL_windows_gaming_input.c, src/joystick/windows/SDL_xinputjoystick.c
This will make it possible to have mappings for different controllers
that have the same VID/PID. This happens frequently with some generic
controller boards that have been reused in many products.
Fixes https://github.com/libsdl-org/SDL/issues/6004
=> Added the CRC of the joystick name to the GUID

src/video/kmsdrm/SDL_kmsdrmvideo.c, src/video/kmsdrm/SDL_kmsdrmvideo.h
Solves comments on [this commit](https://github.com/libsdl-org/SDL/commit/ad874536a4be9b602a0b2bc1f95a21e4a06e1876)
Adds  a missing null check and propagate an error instead of calling exit.
=> kmsdrm: added missing checks

.editorconfig
The Wayland protocol XML files are stored in the root directory of SDL
and not in `src`.
---
This is just a minor fix for editconfig.
=> .editorconfig: Use correct path for wayland-protocols

Xcode/SDL/pkg-support/resources/CMake/sdl2-config.cmake, sdl2-config.cmake.in
- Always create `SDL2::SDL2main` target in autotools CMake config file is the `libSDL2main.a` library exists.
- Always create a `SDL2::SDL2main` target in the Macos framework config file
Fixes https://github.com/libsdl-org/SDL/issues/6119
I have a question left.
The autotools CMake config file will not create a `SDL2::SDL2main` target when `libSDL2main.a` does not exists.
I think this is fine as this means the SDL install is incomplete.
@FtZPetruska
=> cmake: always create SDL2::SDL2main in Macos framework and autotools CMake config file

Xcode/SDL/pkg-support/resources/CMake/sdl2-config.cmake, sdl2-config.cmake.in
Same as #6120 but rebased on release-2.24.x
=> cmake: always create SDL2::SDL2main in Macos framework and autotools CMake config file (backport)

CMakeLists.txt, test/CMakeLists.txt
This PR enables CET Shadow Stack compatibility for CMake builds using VS 16.7 or later. CET Shadow Stack protection helps protect against exploitation by detecting unexpected control flow changes caused by ROP attacks. CET is supported on Windows 10 20H2 and later when running on Intel Tiger Lake and AMD Zen 3 CPUs and newer.
The `/CETCOMPAT` flag sets a bit in the PE header that indicates to Windows that the binary can safely run with CET Shadow Stack protection which helps protect against ROP attacks. It is backwards compatible with older OSes and non-CET compatible CPUs.
Since it's just setting a bit in the PE header, it doesn't result in less efficient code generation (unlike Control Flow Guard), so it should be safe to use by default. It also is only enabled for the process if the …
=> cmake: Enable CET compatibility for x86/x64 targets using VS 16.7+

src/main/ps2/SDL_ps2_main.c
I have decided for now to disable `fileXio` because it is unstable and has some issues in the PS2 toolchain that need to be fixed, so for now we are going to use `fio` meanwhile issues in the toolchain are fixed.
=> [PS2] Main Driver - Disable `fileXio` and patch `fio`

src/video/windows/SDL_windowskeyboard.c
Regression of https://github.com/libsdl-org/SDL/commit/f317d619ccd22e60cebf1b09d716d3985359c981#diff-bff8f3e638d51e86cb6f0f42e2c527549d649951b7aa5ec4a539e865a5b57027R398
Tested on Visual Studio 2019
=> Fix building with SDL_DISABLE_WINDOWS_IME

src/video/windows/SDL_windowsmodes.c
This was getting the wrong monitor's name because the source identifier was not being included in the DisplayConfigGetDeviceInfo request.
In my case, this ended up showing my first monitor's name twice, instead of showing two different monitor names.
=> windows: fix monitor name enumeration

src/joystick/bsd/SDL_bsdjoystick.c
OpenBSD 6.9 added a ujoy(4) device.
https://github.com/openbsd/src/commit/1d44892edf51d2b78a17901b1aa49c83bd9a69e0
=> Add support for OpenBSD's ujoy(4)

configure.ac
find_lib() uses sort -V, which is a GNU extension. Users of non-GNU
operating systems should either install GNU coreutils (assumed to
provide a gsort executable), or use the CMake build system.
Resolves: https://github.com/libsdl-org/SDL/issues/6106
=> autotools: Require GNU sort

src/video/windows/SDL_windowskeyboard.c
Adjust candidate count so list is not draw bigger that needed. This also fix potential uninitialised read of variable `candsize[i]` if `vertical` is false on line 1631.
I did not test this and i am not sure how a candidate could be an empty string.
None
=> Fix candidate list size for Windows IME

CMakeLists.txt, configure, configure.ac, src/core/linux/SDL_dbus.c, src/core/linux/SDL_sandbox.c, src/core/linux/SDL_sandbox.h, src/hidapi/SDL_hidapi.c, src/joystick/hidapi/SDL_hidapijoystick.c, src/joystick/linux/SDL_sysjoystick.c
In order to inhibit the screen saver, SDL currently uses
`org.freedesktop.ScreenSaver.Inhibit()` and, as a fallback, a protocol
specific method for X11 or Wayland.
Accessing `org.freedesktop.ScreenSaver` is usually not allowed when
inside a sandbox like Flatpak, unless the permission has been explicitly
granted to the application.
Another issue is that the Wayland protocol "Idle inhibit" is relatively
new and not yet widely adopted. For example Mutter still doesn't support
it.
For those reasons, when running under Flatpak or Snap, we should try to
inhibit the screen saver by using xdg-desktop-portal instead. This
should give us an higher chance of success.
https://github.com/libsdl-org/SDL/issues/6075
/cc @smcv
=> dbus: Use xdg-desktop-portal Inhibit when running under Flatpak or Snap

CMakeLists.txt
This makes it easier to set these options when SDL is used as a subproject.
Since CMake v3.13+, one can simply `set(SDL_TEST OFF)` before include the SDL2 subproject because options do not override existing variables. (https://cmake.org/cmake/help/latest/policy/CMP0077.html)
This is also true for `set(CACHE)` commands but only in CMake v3.21+ (https://cmake.org/cmake/help/latest/policy/CMP0126.html).
=> CMake: Make SDL_SHARED/STATIC/TEST options

docs/README-ps2.md, include/SDL_hints.h, src/render/ps2/SDL_render_ps2.c
The current SDL implementation for PS2 automatically disables VSYNC even if it is enabled if the FPS isn't enough.
With this PR, I'm keeping VSYNC if the user set it, however I have added an extra `SDL_Hint` in case the user wants to have the dynamic VSYNC (something really useful, when you have some apps that are running almost at 60 FPS)
=> [PS2] Render Driver - Adding specific SDL_Hint for the dynamic VSYNC

src/video/x11/SDL_x11dyn.c
```
SDL_x11dyn.c:123:17: warning: unused variable 'i' [-Wunused-variable]
int i;
^
```
=> Silence unused variable warning

src/joystick/windows/SDL_windows_gaming_input.c
Retry...
Our app disables warnings when compiling external code, and I do not know what warnings you enable, so you will have to check it meets your bar.
=> wgi: refcount the delegate objects

src/video/wayland/SDL_waylandmouse.c
Multiple cursors under Wayland are incorrect.
Many cursors were mapped to `hand1`, not sure why. This proposal sets them to match the same cursor names used under X11.
=> Update Wayland cursors to match X11 cursors

src/video/SDL_video.c, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
A batch of Wayland improvements and fixes.
The big changes are additional refactoring to fullscreen handling in order to properly handle the compositor initiating a fullscreen enter/leave event, or when the compositor moves a fullscreen window between displays.  Previously, SDL's internal state wasn't being updated with these events, so the SDL window state could get out of sync with the actual window state and lead to unexpected behavior (similar to what was reported in #6153 on x11). SDL's internal fullscreen state tracking is now properly updated with externally initiated window state changes, and things like toggling fullscreen or moving fullscreen windows between displays via a desktop hotkey will now behave properly.
Aside from that, there are other small fixes:
- Add some missing …
=> Batch of Wayland improvements and fixes.

src/video/wayland/SDL_waylandwindow.c
Only commit on a move event if the display was changed for a fullscreen window and the compositor has returned bad dimensions. If the window wasn't actually moved then we already have the correct dimensions from the output specs and this is redundant.
=> wayland: Only commit on move if the display was changed

src/joystick/hidapi/SDL_hidapi_wii.c, src/render/opengles2/SDL_shaders_gles2.h
Fixed two warnings which occurs in android build process
```
src/joystick/hidapi/SDL_hidapi_wii.c:733:13: warning: 'break' will never be executed [-Wunreachable-code-break]
break;
^~~~~
src/render/opengles2/SDL_shaders_gles2.h:66:63: warning: this function declaration is not a prototype [-Wstrict-prototypes]
GLES2_ShaderIncludeType GLES2_GetTexCoordPrecisionEnumFromHint();
^
void
```
=> android: fix some compiler warnings

CMakeLists.txt
sceClibMemcmp is not a safe replacement to newlib memcmp.
In real use test cases it has been proven to be more error prone (in particular when NULL ptrs are involved seemingly).
Some good example cases are World of Goo Vita ( https://github.com/Rinnegatamante/goo_vita/blob/main/loader/main.c#L545 ), max-vita ( https://github.com/fgsfdsfgs/max_vita/blob/1d6fa3cf249e1435ff35f3aa191371e3925ccc87/imports.c#L557 ) and YoYo Loader ( https://github.com/Rinnegatamante/yoyoloader_vita/blob/main/loader/main.c#L1694 ).
The first two if compiled with sceClibMemcmp will crash at boot (whilst running fine with memcmp) and the second will have a lot of games crashing in memcmp calls.
sceClibMemcmp is a good speedy replacement for memcmp only in use cases where it's proven to run just fine (and having …
=> vita: Drop memcmp redirect to sceClibMemcmp.

src/video/wayland/SDL_waylandwindow.c
In some cases, a backbuffer size update may not be accompanied by a resize event if the window size and/or scale were updated before the new backbuffer size was recomputed. Instead of the scale, use the old/new backbuffer sizes to determine if a resize event is required so that a backbuffer size change will always be followed by a resize event.
Fixes #6219
=> wayland: Use the backbuffer size for determining if a resize event is required

CMakeLists.txt, configure.ac
The offscreen video driver is pretty useful for automated tests, however because it isn't built by default some (most?) distros don't bother enabling it. This PR simply builds it by default to avoid building SDL from source if you want to use the offscreen driver.
None that I can find.
=> Build the offscreen video driver by default

src/render/SDL_render.c, src/render/SDL_sysrender.h, src/render/direct3d/SDL_render_d3d.c, src/render/direct3d11/SDL_render_d3d11.c, src/render/direct3d12/SDL_render_d3d12.c, src/render/metal/SDL_render_metal.m, src/render/opengl/SDL_render_gl.c, src/render/opengles/SDL_render_gles.c, src/render/opengles2/SDL_render_gles2.c, src/render/ps2/SDL_render_ps2.c, src/render/psp/SDL_render_psp.c, src/render/software/SDL_render_sw.c, src/render/vitagxm/SDL_render_vita_gxm.c, src/video/SDL_sysvideo.h, src/video/SDL_video.c
This kicks in if the platform doesn't support vsync directly, or if the present fails for some reason (e.g. minimized on some platforms)
Fixes https://github.com/libsdl-org/SDL/issues/5134
=> Added support for simulated vsync in the renderer

CMakeLists.txt, src/stdlib/SDL_string.c
Revert #6218 with additional check to make it linux/bsd - compatible.
Additionally drop other mem redefines, since we have them in libc now.
=> Vita: restore sceClibMemcmp

src/joystick/vita/SDL_sysjoystick.c
Gamepad input was reported on PSTV even when, in fact, it was intercepted by IME.
This also simplifies code and adds error-reporting on vita for led/rumble.
CI will fail until vitasdk docker image gets rebuilt.
=> Vita: fix controls on PSTV with opened IME

src/video/windows/SDL_windowsevents.c
This PR adds `WIN_ClientPointToSDL` conversion to other mouse motion events triggered by `WM_MOUSELEAVE`, `WIN_UpdateFocus`, and `WIN_UpdateMouseCapture`.
Since https://github.com/libsdl-org/SDL/commit/ab81a559f43abc0858c96788f8e00bbb352287e8, SDL has supported the `SDL_WINDOWS_DPI_SCALING`, which changes the SDL coordinate system units to be DPI-scaled points.
In that commit, `WIN_ClientPointToSDL` was used to convert mouse positions to SDL coordinate system units (before passing them to `SDL_SendMouseMotion`).
However, a few places were missed, which could result in unexpected / incorrect mouse position values when using `SDL_WINDOWS_DPI_SCALING` on a system with a high DPI mode in certain cases (like that triggered by `WM_MOUSELEAVE`).
This PR adds `WIN_ClientPointToSDL` conversion to …
=> Fix: Use WIN_ClientPointToSDL for converting additional mouse coordinate events (for DPI scaling)

src/render/opengles/SDL_render_gles.c
Free data->pixels in error path
=> Fix memory leak in GLES_CreateTexture

src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandevents_c.h
If multiple keys were simultaneously depressed and one was being repeated, the repeat flag was being cleared when any of the pressed keys were released, even if the released key wasn't the one being repeated.
This tracks the key currently being repeated and only clears the repeat flag when the particular key being repeated is released.
Fixes #6267
=> wayland: Only clear the key repeat flag when the repeated key is released

src/video/haiku/SDL_bmodes.cc
Before, `HAIKU_ColorSpaceToSDLPxFormat` was returning `0` for 24 bit screen colorspaces, which would ultimately lead to `SDL_GetWindowSurface` failing with 'Unknown pixel format' error
---
To trigger this bug, just open the Screen app and change color depth to 24 bits, then run an SDL application that uses SDL_GetWindowSurface
=> haiku: Fix SDL_GetWindowSurface always failing when screen color depth was 24 bits

src/video/wayland/SDL_waylandevents.c
The XKB keysym to SDL keycode mappings were missing for the Escape and NumLock keys, which prevented them from being remapped. Add them to the table so that the remapping of these keys will work.
Fixes #6256
=> wayland: Add mappings for the Escape and NumLock keys

src/video/wayland/SDL_waylandevents.c
The text component of a repeated keystroke is initially set when a key is first pressed and the cached value remains static until the repeated key is released and another repeatable key is pressed. If the state of a modifier such as shift or capslock is changed while a key is being repeated, the text emitted will not have the modifier applied to it until the repeated key is released and pressed again.
For example, holding A while toggling shift:
```
Wayland: aaa <shift down> aaa <shift up> aaa
X11: aaa <shift down> AAA <shift up> aaa
```
This patch updates the text to be repeated by a key if a modifier is changed while a key is actively being repeated so that the appropriate text is emitted and X11 behavior is matched.
=> wayland: Apply modifier changes to the text of repeated keys

test/testiconv.c
This helps make it more clear at a glance whether or not testiconv succeeded or not.
This change is based on libsdl-org/SDL-1.2#868 and libsdl-org/sdl12-compat#219.
=> testiconv: Print the total number of errors at the end

sdl2-config.cmake.in
Same as https://github.com/libsdl-org/SDL/pull/6260 but for the autotools build system
It looks like autotools for MinGW is not tested on CI.
Is this intentional?
=> cmake: only add -Wl,--undefined=WinMain when building an executable

src/video/kmsdrm/SDL_kmsdrmvideo.c
ad874536 removed an unnecessary limit as we *can* have a devindex greater than 99, this error message does not reflect the support for values greater than 99.
=> kmsdrm: only negative devindex's are not allowed

src/core/linux/SDL_dbus.c
Before calling any DBus related methods we should first ensure that they were correctly loaded.
In the event where `LoadDBUSLibrary()` was not able to load the DBus library, we should just return early, signalling with SDL_FALSE that we were unable to inhibit the Screensaver.
Helps: https://github.com/ValveSoftware/steam-for-linux/issues/8815
=> dbus: guard against uninitialized D-Bus

src/hidapi/SDL_hidapi.c, src/hidapi/libusb/hid.c
Mainstream commit:
https://github.com/libusb/hidapi/commit/5ce9051e2f2e65013485bc4c83897610df82f3c9
... which has references to the original bug report and its associated PR.
=> hidapi, libusb: backport read_thread indefinite loop fix from mainstream

src/video/wayland/SDL_waylandwindow.c
Calling SDL_HideWindow() to destroy the window is a NOP if the SDL_WINDOW_SHOWN flag was never set. Bypass it and call the Wayland-specific function directly to ensure that the window is always destroyed before switching from server-side to client-side decorations, even if it hasn't been shown yet.
Likewise, call Wayland_ShowWindow() directly when the window isn't explicitly hidden to ensure that it is always recreated since the SDL_WINDOW_SHOWN flag won't be cleared, which, when set, renders SDL_ShowWindow() a NOP.
Fixes #6284
=> wayland: Call the Wayland hide/show functions directly when changing decoration modes

.github/workflows/emscripten.yml, src/timer/SDL_timer.c
Instead use the native emscripten timer API.
See https://github.com/emscripten-core/emscripten/issues/17941
=> emscripten: Remove use of EM_ASM from SDL_timer code.

src/video/cocoa/SDL_cocoawindow.m
Added #if checks for OpenGL in locations where it requires types that aren't defined.
=> Fixed Mac compile errors when OpenGL is disabled.

build-scripts/android-prefab.sh
This pr adds a script to build a binary aar archive, that can be uploaded to some maven repository.
In short, by providing SDL this way people can add SDL into their project without requiring to clone this repo.
Recent versions of Android Studio allow third-party native dependencies to be made available to CMake.
[This blogpost](https://android-developers.googleblog.com/2020/02/native-dependencies-in-android-studio-40.html) explains it rather well.
Users can bring SDL into their project by simply adding the following line into their `build.gradle`:
```gradle
dependencies {
implementation 'org.libsdl.android:SDL2:2.25.0-1' // the namespace is to be determined
}
```
[Prefab](https://google.github.io/prefab/) automatically generates the same CMake targets as we do in our `*-config.cmake` …
=> Android: add script for building prefab archive

include/SDL_hints.h, src/joystick/SDL_gamecontroller.c, src/joystick/hidapi/SDL_hidapi_switch.c
* Added support for vertical mode for Joy-Con controllers
* Added the hint SDL_HINT_JOYSTICK_HIDAPI_VERTICAL_JOY_CONS for switching to this mode
* Added support for SL/SR buttons in combined/vertical mode and L/ZL/R/ZR buttons in mini-gamepad mode
For now, joy-cons are in mini-gamepad mode when a single joy-con is connected, or a pair of joy-cons are connected with the combine hint disabled (SDL_HINT_JOYSTICK_HIDAPI_COMBINE_JOY_CONS = 0). In the mini-gamepad mode (also called the horizontal mode), left stick and a/b/x/y are targeted for either Joy-Con(L) or Joy-Con(R). However, in practice, there is demand for a vertical mode of joy-cons (e.g., playing Just Dance in yuzu emulator by a single player), which is not supported now. In the vertical mode, each joy-con should work as a half part …
=> Add vertical mode for Nintendo Joy-Con

docs/README-ios.md, src/video/uikit/SDL_uikitappdelegate.m, src/video/uikit/SDL_uikitmessagebox.m, src/video/uikit/SDL_uikitmetalview.m, src/video/uikit/SDL_uikitmodes.m, src/video/uikit/SDL_uikitopengles.m, src/video/uikit/SDL_uikitopenglview.m, src/video/uikit/SDL_uikitvideo.m, src/video/uikit/SDL_uikitviewcontroller.m, src/video/uikit/SDL_uikitwindow.m
SDL hasn't supported those older iOS versions for a little while now (e.g. https://github.com/libsdl-org/SDL/commit/f789bc7d5f33911671f30438a5c4980a269cee38).
None.
=> iOS: remove dead pre-iOS 8 codepaths.

include/SDL_hints.h, src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandevents_c.h, src/video/wayland/SDL_waylandmouse.c
Several games (including Source and GoldSrc games, and Bioshock Infinite) attempt to "fake" relative mouse mode by repeatedly warping the cursor to the centre of the screen. Since mouse warping is not supported under Wayland, the viewport ends up "stuck" in a rectangular area.
Detect this case (mouse warp while the cursor is not visible), and enable relative mouse mode, which tracks the cursor position
independently, and so can Warp successfully.
This is behind the ``SDL_HINT_VIDEO_WAYLAND_EMULATE_MOUSE_WARP`` hint, which is enabled by default.
Note that there is a behavioural difference, in that relative mouse mode typically doesn't take mouse acceleration into account, but the repeated-warping technique does, so mouse movement can seem very slow with this (unless the game has its own …
=> Wayland: Emulate mouse warp using relative mouse mode

CMakeLists.txt
See f18fae4c689a68bd50ce34d6b9c1f014c2f220a2
=> cmake: Use DWARF 4 debug information when building using mingw

src/audio/coreaudio/SDL_coreaudio.m
Compilation error on MacOS with CMake
```
SDL/src/audio/coreaudio/SDL_coreaudio.m:1225:17: error: mixing declarations and code is incompatible with standards before C99 [-Werror,-Wdeclaration-after-statement]
CFIndex len = CFStringGetMaximumSizeForEncoding(CFStringGetLength(cfstr),
```
Move the declaration of `len` outside code.
Related issue: https://github.com/libsdl-org/SDL/issues/6330
Fixes #6330
=> fix compilation error SDL_coreaudio mixing declarations and code

src/video/uikit/SDL_uikitappdelegate.m, src/video/uikit/SDL_uikitevents.m
Removes the need to call SDL counterparts manually when custom AppDelegate is used in the app.
=> [UIKit] handle app lifecycle events in a custom object instead of AppDelegate

src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandvideo.h, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
Another small batch of Wayland improvements, the big one being deduplicating calls to set the EGL window size, viewport and surface opaque region in `ConfigureWindowGeometry()`.  This further reduces redundant Wayland state calls and can close #6006, as the point of that was to achieve the same goal. It also allowed for some code removal in `Wayland_CreateWindow()`, the elimination of the window size helper functions, and for the streamlining of the logic when setting the damage region since it now always has the 'true' window size stored.
The other changes include using wl_surface.damage_buffer to set the damage region, as this is the preferred method if the wl_compositor version is ≥ 4, caching the EGL transparency hint at startup and registering a notification callback, so that if it …
=> Wayland: Dedupe window geometry calls and other optimizations/improvements

src/audio/SDL_audio.c
In the `open_audio_device()` function, enlarge the scope of the detection mutex lock so that 2 devices don't get the same id.
The current scope of mutex in `open_audio_device()` seems not enough to prevent that several devices can get the same id if several threads are calling `SDL_OpenAudio()` at the same time.
In this PR, the `SDL_LockMutex()` scope on the `current_audio.detectionLock` is enlarged so that the search for an available id and the binding of the new created device id in the `open_devices` global array are protected by the mutex.
On each error cases the mutex is released by `SDL_UnlockMutex()` before returning.
Address a FIXME L.1316 of `SDL_audio.c`. On a machine with many cores calling `SDL_OpenAudio()` in several threads (5 in our context) at the same time will provoke a …
=> audio open: ensure 2 devices don't get the same id

src/video/wayland/SDL_waylandevents.c
The drop data needs to be null terminated, otherwise random data is sent as a drop event.
=> wayland: null-terminate drop data

CMakeLists.txt
This is incompatible with enabling bitcode, such as with iOS builds. The default value for "undefined" is "error" so this option should be redundant.
=> Removed "undefined" argument for Apple platforms.

.github/workflows/ps2.yaml, .github/workflows/psp.yaml, .github/workflows/vita.yaml, src/render/ps2/SDL_render_ps2.c, src/thread/psp/SDL_sysmutex.c, src/thread/psp/SDL_syssem.c, src/video/ps2/SDL_ps2video.h, src/video/psp/SDL_pspevents.c, test/testgl2.c
- Fixes the remaining warnings for the PS2 and PSP toolchains.
- Turns on `SDL_WERROR` in CI for PS2, PSP, and PS Vita.
Mentioned by @madebr in https://github.com/libsdl-org/SDL/pull/6251#issuecomment-1273518688
=> Enabling SDL_WERROR on Homebrew platforms.

src/joystick/hidapi/SDL_hidapi_switch.c
I am testing the sensor data of Nintendo controllers, finding that the new timestamp_us in SDL_ControllerSensorEvent increases un-monotonically, which brings some troubles.
This pull request makes the timestamp_us of Nintendo controllers change monotonically by modifying the order of SendSensorUpdate callings.
The timestamp_us changing:
```
Old:
5000 -> 10000 -> 15000 -> 5000 -> 10000 -> 15000 ->
20000 -> 25000 -> 30000 -> 20000 -> 25000 -> 30000 -> ...
New:
5000 -> 5000 -> 10000 -> 10000 -> 15000 -> 15000 ->
20000 -> 20000 -> 25000 -> 25000 -> 30000 -> 30000 -> ...
```
=> Made timestamp_us of sensor events increase monotonically for Nintendo controllers

src/video/wayland/SDL_waylandevents.c
Version 8 is required for supporting axis_value120 high-resolution scroll events.
=> wayland: Raise wl_seat maximum version to 8

.github/workflows/vita.yaml
`SDL_WERROR` was misspelled in the PS Vita workflow.
https://github.com/libsdl-org/SDL/pull/6372#discussion_r992374463
=> Vita: Fix typo in CI CMake command.

src/video/x11/SDL_x11mouse.c, src/video/x11/SDL_x11sym.h
Fixes #6275.
If a coordinate transformation is set, the cursor jumps when moving after `XWarpPointer` is called. This doesn't happen with `XIWarpPointer` (which is the same, but takes the pointer device explicitly (according to man page)).
Fixes #6275.
cc @ndren
=> Use XIWarpPointer if compiled with xinput2

src/render/direct3d/SDL_render_d3d.c
The two linked PRs have been merged since May. Build and tests pass in CI without the workaround. 
Aforementioned PRs:
- open-watcom/open-watcom-v2#868
- open-watcom/open-watcom-v2#869
=> Remove D3D9 workarounds for Watcom.

test/testevdev.c
Follow-up from #6380.
* testevdev: Add a static assertion for supported sizeof(long)
If this assertion fails on some platform (unlikely), we will need a
third implementation for SwapLongLE().
* testevdev: Explain why the test data is encoded the way it is
=> testevdev: Add a static assertion and a comment

.github/workflows/android.yml, .github/workflows/emscripten.yml, .github/workflows/ios.yml, .github/workflows/main.yml, .github/workflows/msvc.yml, .github/workflows/n3ds.yml, .github/workflows/ps2.yaml, .github/workflows/psp.yaml, .github/workflows/riscos.yml, .github/workflows/vita.yaml, .github/workflows/vmactions.yml, .github/workflows/watcom.yml
This fixes the `Node.js 12 actions are deprecated.` warnings in CI.
Functionally, v3 does not change anything other than running on Node 16 rather than 12.
See the `Annotations` section of [recent CI runs](https://github.com/libsdl-org/SDL/actions/runs/3236271203)
=> CI: Update to actions/checkout@v3.

src/video/wayland/SDL_waylandevents.c
Per the Wayland spec, this must be mapped with MAP_PRIVATE in version 7 of the protocol and higher.
Fixes #6392
=> wayland: Use MAP_PRIVATE when mapping the keyboard keymap file descriptor

src/joystick/hidapi/SDL_hidapi_switch.c
When I test the sensors of my Nintendo controllers, I find:
> For Pro Controller, accel_x is about 1.3 times of the normal value
> For Joy-Con(L) in mini-pad mode, accel_y and accel_z are about 1.3 times of the normal value
I'm not sure if the cause is the mistake in the bitwise operations in LoadIMUCalibration. Anyway, after I changed 0xF00 to 0xFF00 in the code, the sensor data became normal. So, please have a check.
=> Fix bugs in IMU calibration loading for Nintendo Controllers

include/SDL_hints.h, src/audio/SDL_audio.c, src/audio/SDL_audio_c.h, src/audio/SDL_audiocvt.c
Hi, first time PR.  I was digging around in the audio code while debugging #6391 (did not find a real solution for that sadly.)  I saw that libsamplerate is a library already being used for the AudioStreams API but wasn't yet implemented for the Audio_CVT API.  I thought it would be more consistent if this was applied universally.
It's basically just a function pointer that gets set if the hint is set (off by default) and the user has libsamplerate available on their system.  I used the src_simple API which doesn't require any init/de-init.  It just converts the entire buffer in much the same way as SDL's internal conversion function does.
I wasn't sure what to do if the library reports an error.  It doesn't look like the AudioStreams API handles libsamplerate failures in any special way …
=> SDL_audiocvt: Respct the SDL_HINT_AUDIO_RESAMPLING_MODE hint

src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandevents_c.h
Hi guys, after a bit more digging, it looks like `SDL_SendKeyboardKeyInternal` in `src/events/SDL_keyboard.c` already does what I was suggesting, which is setting the keyboard modifier flags in response to key events. Because this code already runs whenever the user presses a key, I don't think it's necessary to also change these modifiers in `keyboard_handle_modifiers`, so I wrote a commit that removes that code, and modifiers appear to work fine.
I also added some code to update the modifiers in `keyboard_handle_enter` and generate keypress events for those keys. Maybe modifiers like shift and control should also be unset in `keyboard_handle_leave`?
Fixes issue #6037
=> Fix issue #6037 (incorrect modifier flags on Wayland)

src/video/cocoa/SDL_cocoawindow.m
Mouse warp can be broken on macOS for at least two ways.
1. If you resize a window while mouse is already slightly outside of the window rather than inside of it (after mouse leave event).
2. When you use maximize window button on titlebar.
In both cases it executes the Cocoa_HandleTitleButtonEvent() function but only for mouse down event. It never receives mouse up event, so that SDL is constantly in FocusClickPending state and it breaks mouse warp functions.
An easy fix is to reset this state when resizing window is finished. Something similar is already done in windowDidMiniaturize().
=> Fixed mouse warp after resizing window on macOS.

src/video/cocoa/SDL_cocoakeyboard.m
There is at least one case when modifiers on macOS don't work properly. When I use "command+tab" shortcut to switch window and then go back to SDL window with another "command+tab". SDL cocoa driver will think that the command key is still pressed. Thus it will not send next command key press event. I mean the following:
- command+tab (switch to another window)
- command+c (copy text)
- command+tab (go back to SDL Window)
- command+v (try to paste text text, it will not work)
- command+v (another attempt, this one will work)
This bug happens because system doesn't send the NSEventTypeFlagsChanged event when window is not active, so that in data.modifierFlags the command key was still marked as pressed. And then, when window is already active again, another NSEventTypeFlagsChanged is sent. …
=> Fixed command modifier on macOS

src/events/SDL_keyboard.c
=> fix SDL_SendEditingText when long composition text is enabled and strlen(text) == SDL_TEXTEDITINGEVENT_TEXT_SIZE

CMakeLists.txt
Create + install `sdl2.pc` for Visual Studio (and Watcom).
Fixes https://github.com/libsdl-org/SDL/issues/6158
This PR generates the following `sdl2.pc`:
```
prefix=C:/Users/maarten/source/repos/SDL/cmake-build-debug/prefix
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
Name: sdl2
Description: Simple DirectMedia Layer is a cross-platform multimedia library designed to provide low level access to audio, keyboard, mouse, joystick, 3D hardware via OpenGL, and 2D video framebuffer.
Version: 2.25.0
Requires:
Conflicts:
Libs: -L${libdir}   -lSDL2
Libs.private:  -lSDL2-static  -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lversion -luuid -ladvapi32 -lsetupapi -lshell32 -ldinput8
Cflags: -I${includedir} -I${includedir}/SDL2
```
Because `SDL2.lib` != …
=> cmake: create and install sdl2.pc for MSVC & WATCOM

src/loadso/dlopen/SDL_sysloadso.c
- strlcpy was passed a wrong buffer length parameter. has worked so far by luck.
- use memcpy instead of strlcpy for simplicity.
- 'append' has been a typo: should be 'prepend'.
=> loadso, dlsym, SDL_LoadFunction: cleanup the underscored name path.

CMakeLists.txt, cmake/CheckCPUArchitecture.cmake, src/stdlib/SDL_mslibc.c
Building a shared SDL2.dll failed on MSVC when building in `MinSizeRel` configuration.
The (main) difference between these 2 configurations are the used c flags.
```
//Flags used by the C compiler during DEBUG builds.
CMAKE_C_FLAGS_DEBUG:STRING=/MDd /Zi /Ob0 /Od /RTC1
//Flags used by the C compiler during MINSIZEREL builds.
CMAKE_C_FLAGS_MINSIZEREL:STRING=/MD /O1 /Ob1 /DNDEBUG
//Flags used by the C compiler during RELEASE builds.
CMAKE_C_FLAGS_RELEASE:STRING=/MD /O2 /Ob2 /DNDEBUG
//Flags used by the C compiler during RELWITHDEBINFO builds.
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=/MD /Zi /O2 /Ob1 /DNDEBUG
```
Changing `/O1` in `CMAKE_C_FLAGS_MINSIZEREL` to `/O2` makes it link again. But that is not a real solution.
By passing [`/NODEFAULTLIB`](https://learn.microsoft.com/en-us/cpp/build/referen …
=> Pass -nodefaultlib to linker when wanting to avoid the C library

src/video/uikit/SDL_uikitview.m
The velocityInView causes issues on iPad with external mouse. For first event in gesture velocity is always 0, so that you have to use your scroll wheel twice to generate actual scroll event in SDL. Other issue is that when you scroll up and down quickly, then velocity is still positive for some time before to changes sign to negative, so that you get scroll events for incorrect direction.
translationInView gives position in pixels, so that if I subtract it from value from previous event, then I should always get correct direction.
Note that this patch is not 100% correct because I always set SDL_MOUSEWHEEL_NORMAL. I don't know how to read from system if mouse scrolling is inverted.
And btw. with translationInView it should be possible to make some kind of smooth scroll because if you …
=> Use translationInView for mouse wheel event on iOS

src/video/winrt/SDL_winrtevents_c.h, src/video/winrt/SDL_winrtkeyboard.cpp, src/video/winrt/SDL_winrtvideo.cpp
Fixes WINRT_IsScreenKeyboardShown on Xbox. I kept existing behavior the same on universal apps/windows mobile to avoid issues for developers on those platforms.
Fixes #6433
=> Fix WINRT_IsScreenKeyboardShown on Xbox

src/video/SDL_egl.c
Closes https://github.com/libsdl-org/SDL/issues/6236.
CC: @ccawley2011.
=> SDL_EGL_GetProcAddress: remove unnecessary underscore-prepended search.

src/video/wayland/SDL_waylandvideo.c
Somehow this wound up being included twice.
=> wayland: Remove duplicate #include statement

src/video/wayland/SDL_waylandwindow.c
Exit the fullscreen sequence sooner if it is requested that a popup window be fullscreen.
The surface commit formerly in this path is irrelevant and can be removed as previous changes made it so that `SetFullscreen()` is no longer called from anywhere except `Wayland_SetWindowFullscreen()`, so there is no longer any case where a commit is warranted here.
=> wayland: Early-out sooner when requesting fullscreen on a popup

src/events/SDL_keyboard.c, src/events/SDL_keyboard_c.h, src/video/emscripten/SDL_emscriptenevents.c
emscripten: Make an attempt at correct keyboard scancode/keycodes.
This uses a newer browser API to get physical scancodes, but still uses the (deprecated) event field that we were already using scancodes, but for keycodes instead now, which appears to be more accurate.
Since keyboard layout isn't (generally) available to web apps, this adds an internal interface to send key events with both scancode and keycode to SDL's internals, instead of sending just scancodes and expecting SDL to use its own keymap to generate keycodes.
Future work in this area would be to use the keyboard layout APIs on browsers that support them, which would allow us to use SDL's usual keymap code and not rely on a deprecated browser API, but until we get there, this patch gives significantly more correct results …
=> emscripten: Make an attempt at correct keyboard scancode/keycodes.

sdl2-config.in, sdl2.m4
If we deprecate these in SDL 2.x, then developers of dependent projects will have had some advance warning before they're removed in SDL 3 (which I think should only install `${libdir}/pkgconfig/sdl3.pc` and `${libdir}/cmake/SDL3/*.cmake`, with no replacement for `${bindir}/sdl2-config` or `${datadir}/aclocal/sdl2.m4`).
* sdl2-config.in: Deprecate sdl2-config
Library-specific foo-config scripts duplicate very similar logic across
various different projects, and tend to break cross-compiling, multilib
(gcc -m32), Debian/Ubuntu multiarch and so on by only being able to have
one sdl2-config at a time as the first one in the PATH.
The direct replacement is pkg-config(1) or a compatible reimplementation
like pkgconf(1), which relies on each library installing declarative
metadata, like SDL's …
=> Deprecate sdl2-config and AM_PATH_SDL2

src/video/wayland/SDL_waylandevents.c
If relative mouse mode is explicitly enabled, don't modify the capture flag on button events or the window might report having lost mouse focus if a button is pressed while moving the cursor.
Fixes #6460
=> wayland: Don't modify the mouse capture flag in relative mode

src/SDL.c
Init says that audio implies events (line 195), Quit was missing the implication.
https://github.com/libsdl-org/SDL/blob/b9e1d1b4de713c031353ec300113bd776961625c/src/SDL.c#L194-L196
(Just noticed this as I was reading the code on Github, I don't have an example where this causes a bug.)
=> Fix mismatch between Init and Quit

src/video/wayland/SDL_waylandevents.c
Since 33a430056f15fa5e75ee11f3d7917b4fd2f81c1a, clicking on `libdecor` decorations causes a crash.
=> wayland: Read `window` data only if `window` is valid

CMakeLists.txt
=> cmake: use SDL2-static as static library output name when prefix/static == ""/".lib"

src/video/cocoa/SDL_cocoakeyboard.m
This will send an empty `TEXTEDITING` event to signal the end of the composition, the same way that is done on other platforms.
=> cocoa: Reset IME when sending composed text

src/video/wayland/SDL_waylandmouse.c, src/video/wayland/SDL_waylandvideo.c
571ff1a3a96f03a3c1e2e01479077c5d61eadfa0 introduces an experimental patch for handling compositor restarts. A few minor parts were missed out.
- For mouse cursors we have a wl_surface for both system and custom cursors which needs recreating.
- The other patch is about nullification after deletions
Most this code is disabled behind #if statements for now so this makes no difference to the end user.
=> Fix wayland reconnection paths

src/video/cocoa/SDL_cocoakeyboard.m
Fixes the issue that you need to double press the Escape key to dismiss the IME Candidate Window
Before: Candidate Window is discarded on the second Escape key press
After: Candidate Window is discarded immediately
(Please ignore that I'm not printing the `SDL_TEXTEDITING` event)
=> macOS: Discard the IME Candidate Window immediately when Escape is pressed

src/events/SDL_events.c
- SDL_EventQ.active is a bool variable -> do not use SDL_AtomicGet/Set, it does not help in any way
- protect SDL_EventQ.active with SDL_EventQ.lock
- set SDL_EventQ.active to FALSE by default
=> fix handling of SDL_EventQ.active

src/joystick/SDL_joystick.c, src/joystick/SDL_sysjoystick.h
Dualshock 4 controller only rumbles for 5 seconds maximum. Trying to rumble for longer or to extend an existing rumble with same force does not work.
This patch resend rumble command every 2 seconds to make long rumble work.
Xbox controller actually rumbles for `SDL_MAX_RUMBLE_DURATION_MS`, so we don't need this trick for trigger rumble.
None
=> Fix Dualshock 4 rumble stopping too early

src/atomic/SDL_atomic.c
use 'sizeless' int types (int uses 32-bit even if _LP64 is set)
(WARNING: I do not have Solaris, just read the documentation)
=> fix SOLARIS_ATOMICS

src/video/SDL_video.c
return `SDL_InvalidParamError("rect")` if `rect` is `NULL` (SDL_GetDisplayBounds and SDL_GetDisplayUsableBounds).
(first commit of PR 5315)
=> solve FIXMEs in SDL_video.c

src/video/SDL_video.c
Add SDL_ContextNotSupported and validate flags in SDL_RecreateWindow similar to SDL_CreateWindow.
Remark: do you plan to add SDL_HINT_VIDEO_FOREIGN_WINDOW_METAL similar to _VULKAN and _OPENGL?
(third commit+ of PR 5315)
=> video: add SDL_ContextNotSupported

src/video/SDL_video.c
- add SDL_DllNotSupported and use it to sync the behavior of SDL_GL_LoadLibrary with SDL_Vulkan_LoadLibrary
('fourth' commit of PR 5315)
=> video: add SDL_DllNotSupported

src/video/SDL_video.c
- add NOT_AN_OPENGL_WINDOW define (similar to NOT_A_VULKAN_WINDOW)
- sync Metal_CreateView with GL_CreateContext and Vulkan_CreateSurface
(fifth and sixth commit of PR 5315)
=> video: minor adjustments to sync behavior of various drivers

src/video/SDL_video.c
The flag checks can be done in one step assuming these are bit-flags.
(commit 8. of PR 5315)
=> video: simplify window-type check in SDL_CreateWindow

src/video/x11/SDL_x11keyboard.c, src/video/x11/SDL_x11keyboard.h, src/video/x11/SDL_x11video.c, src/video/x11/SDL_x11video.h
This detects SteamOS game mode sessions and makes use of their deep link to interact with the OSK.
This is marked as a draft because the parameters for the deeplink are stubs, I'm not sure if there's a nice way to just use the default settings that Steam+X uses... I'd prefer that over doing weird math against a focused window or something! Other than that this should be a very uninvasive change.
Fixes https://github.com/Plagman/gamescope/issues/668
=> x11: Add support for the Steam Deck on-screen keyboard

src/video/wayland/SDL_waylandevents.c
Clamp the wl_seat max version to 5 if being built against a version of libwayland below 1.21.0, or containers that bundle newer versions of SDL with older versions of libwayland can break if the compositor advertises support for a protocol version above 5 without the supporting update for libwayland.
Fixes #6516
=> wayland: Clamp wl_seat version on older versions of libwayland

src/events/SDL_keyboard.c
As discussed in #6164, these lines are redundant. Most probably just an artifact from a bad merge when going from https://github.com/libsdl-org/SDL/pull/5378 to https://github.com/libsdl-org/SDL/pull/5398.
Thanks @Guldoman.
=> events: eliminate redundant code in SDL_SendEditingText

test/controllermap.c, test/testautomation_pixels.c, test/testautomation_rwops.c, test/testautomation_video.c
Using this configuration:
- DevkitARM R59 GCC 12.2.0 (3DS toolchain)
- Build type: Debug
- `SDL_TESTS=ON`
- `SDL_WERROR=ON`
Build fails from `-Wmaybe-uninitialized` (part of `-Wall`) warnings in some tests.
The warnings are most likely false positives as the switch statements are only called with the listed values, so a default is added.
I was not able to reproduce the warning in Release mode, or when making a native Linux build with GCC 12.2.0.
N/A
=> Silence spurious `-Wmaybe-uninitialized` warnings in tests.

docs/README-n3ds.md, include/SDL_filesystem.h, src/SDL_log.c, src/file/n3ds/SDL_rwopsromfs.c, src/filesystem/n3ds/SDL_sysfilesystem.c, src/joystick/n3ds/SDL_sysjoystick.c, src/sensor/n3ds/SDL_n3dssensor.c, src/video/n3ds/SDL_n3dsvideo.c
This PR brings various small tweaks and fixes to the Nintendo 3DS port, most notably:
- Fix an subtle issue with GameController/Joystick polling where the events would be ignored if `SDL_SetKeyboardFoxus` wasn't called when creating the window.
- Move the location of `SDL_Log.txt` to the `/3ds/` directory. This is the recommended directory for homebrew applications.
N/A
=> N3DS: Fixes and improvements

src/video/wayland/SDL_waylandmouse.c
Cursors don't get fractionally scaled, so always scale system cursor sizes to the next whole integer and return the rounded scale value.
Fixes #6526
=> wayland: Always use integer scaling for cursors.

src/SDL.c, src/SDL_hints.c, src/audio/SDL_audiocvt.c, src/core/windows/SDL_immdevice.c, src/events/SDL_events.c, src/joystick/SDL_gamecontroller.c, src/joystick/SDL_joystick.c, src/joystick/hidapi/SDL_hidapi_shield.c, src/joystick/windows/SDL_dinputjoystick.c, src/render/software/SDL_render_sw.c, src/stdlib/SDL_malloc.c, src/video/SDL_pixels.c, src/video/SDL_rect_impl.h, src/video/SDL_video.c, src/video/SDL_yuv.c, src/video/windows/SDL_windowskeyboard.c, src/video/windows/SDL_windowswindow.c
Most of these are probably harmless, but the changes to SDL_immdevice.c and SDL_pixels.c appear to have fixed genuine bugs.
SDL_audiocvt.c: By separating the calculation of the divisor, I got rid of the suspicion that dividing a double by an integer led to loss of precision.
SDL_immdevice.c: Added a missing test, one that could have otherwise led to dereferencing a null pointer.
SDL_events.c, SDL_gamecontroller.c, SDL_joystick.c, SDL_malloc.c, SDL_video.c: Made it clear the return values weren't used.
SDL_hidapi_shield.c: The size is zero, so nothing bad would have happened, but the SDL_memset() was still being given an address outside of the array's range.
SDL_dinputjoystick.c: Initialize local data, just in case IDirectInputDevice8_GetProperty() isn't guaranteed to write to it. …
=> Fixes made in response to running a static code analyzer under MS Windows.

VisualC-GDK/tests/testgamecontroller/wingdk/MicrosoftGame.config, VisualC-GDK/tests/testgamecontroller/xboxone/MicrosoftGame.config, VisualC-GDK/tests/testgamecontroller/xboxseries/MicrosoftGame.config, VisualC-GDK/tests/testgdk/wingdk/MicrosoftGame.config, VisualC-GDK/tests/testgdk/xboxone/MicrosoftGame.config, VisualC-GDK/tests/testgdk/xboxseries/MicrosoftGame.config, VisualC-GDK/tests/testsprite2/wingdk/MicrosoftGame.config, VisualC-GDK/tests/testsprite2/xboxone/MicrosoftGame.config, VisualC-GDK/tests/testsprite2/xboxseries/MicrosoftGame.config
Previously we were using the Microsoft sample identifiers which @walbourn asked us not to. This now uses the identifiers which are used in the GDK templates (`PleaseChangeMe` and `FFFFFFFF`).
Also there was a minor issue that testgamecontroller/xboxone/MicrosoftGame.config was referencing DesktopRegistration dependencies, which aren't used on Xbox.
Fixes reopen of #4519
=> GDK: Updated MicrosoftGame.config files to use placeholder identifiers

src/events/SDL_keysym_to_scancode.c
The XKB_KEY_* and XK_* macros resolve to the same constant values, so use the raw values and note what keys they correspond to in the comments, as is done for the other keysym values in this file.
This completely eliminates the need for any X or XKB system headers along with the if/else defines.
=> events: Remove X and XKB keysym constants and headers

src/core/gdk/SDL_gdk.cpp, src/thread/ngage/SDL_sysmutex.cpp, src/thread/ngage/SDL_syssem.cpp, src/video/haiku/SDL_bopengl.cc
Cleanup of SDL_SetError that already return -1 value
eg: 
```
-  SDL_SetError("[GDK] Could not create global task queue");
-  return -1;
+  return SDL_SetError("[GDK] Could not create global task queue");
```
=> Cleanup of SDL_SetError that already return -1 value

src/video/wayland/SDL_waylandkeyboard.c, src/video/wayland/SDL_waylandkeyboard.h
Some applications (and embarrassingly, testime is one of them) call SDL_StartTextInput() or SDL_SetTextInputRect() every frame. On KDE/KWin with fcitx5, this causes there to be several preedit events every frame (particularly given some of the workarounds in Wayland_StartTextInput), which slows testime down to an unusable crawl.
Instead, make SDL_StartTextInput() a no-op if text input is already enabled, and cache the input rect, only changing it when the new rect is actually different.
With these changes, we only get preedit events (and hence SDL_TEXTEDITING events) when the preedit string actually changes. This matches the behaviour under XWayland, and works very smoothly.
=> wayland: keyboard: Cache text input parameters.

src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
When changing the window state from non-floating to floating (e.g. leaving fullscreen), libdecor can send bogus content sizes that are +/- the height of the window title bar and start 'walking' the window height in one direction or the other with every transition.
The floating window size is known, so use the cached value instead of the size reported by libdecor when restoring the floating state.
This is a known libdecor issue: https://gitlab.gnome.org/jadahl/libdecor/-/issues/40
Previously I only observed this when hiding a window, but after installing the latest libdecor/mutter/gnome-shell updates I observed it happening when leaving desktop fullscreen mode as well.  Every time fullscreen mode was entered/exited the window content area would be taller by the height of the title bar.
=> wayland: Use the cached window size when switching from non-floating to floating window state

docs/README-riscos.md
The builtin atomic functions were fixed in GCCSDK [r7724](https://www.riscos.info/websvn/comp.php?repname=gccsdk&compare[]=/trunk/gcc4/@7723&compare[]=/trunk/gcc4/@7724).
=> Update README-riscos.md to reflect that atomic functions have been fixed

src/video/windows/SDL_windowsevents.c
Allows consumers to differentiate pen from touch input.
Windows will send `WM_TOUCH` messages for both regular touch input, and for pen/tablet PC/Windows Ink input.
Pen events will have the `TOUCHEVENTF_PEN` flag is set in [`TOUCHINPUT.dwFlags`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-touchinput#remarks).
Consumers can use `SDL_GetTouchName` to get the device type (`"pen"` or `"touch"`) for a `SDL_TouchFingerEvent`:
```c
SDL_Event event; // from event loop
int index = -1;
for (int i = 0; i < SDL_GetNumTouchDevices(); i++) {
if (event.tfinger.touchId == SDL_GetTouchDevice(i)) {
index = i;
break;
}
}
if (SDL_strncmp(SDL_GetTouchName(index), "pen", 3) == 0) {
// pen/tablet handling
} else {
// touchscreen handling
}
```
- https://github.com/ppy/osu/issues/19150 …
=> Differentiate between Windows Ink (pen) and regular touch input

include/SDL_stdinc.h, include/begin_code.h
- SDL_MALLOC when the pointer returned is not aliased.
- SDL_ALLOC_SIZE* to gives hint about the size.
=> alloc api having new attributes for micro optimisations.

src/render/software/SDL_render_sw.c
This ensures that the pixel format used by the framebuffer is prioritised over the others to avoid unnecessary conversion and allow faster blitting routines to be used for opaque images.
=> Select the best pixel formats for use in the software renderer

configure.ac
Only enable MFI if we also have CoreHaptics to ensure rumble works. See:
- cmake: Detect SDL_JOYSTICK_MFI for macOS (bc409163a81e5f440399926774202dd2da3e37c3)
- cmake: Weak link with CoreHaptics (401f485490c68d91b8444f23f61b08e162ef04fb)
WARNING: I have no idea what I'm doing, just trying to sync cmake and configure.
=> autotools: Detect SDL_JOYSTICK_MFI for macOS + Weak link with CoreHaptics

src/video/cocoa/SDL_cocoaopengl.h
The typedef seems to be pulled in coincidentally with newer SDKs, but older ones need to import the header explicitly.
=> SDL_cocoaopengl.h: ensure CVDisplayLinkRef is defined

src/video/cocoa/SDL_cocoaevents.m
Fixes building against OS X 10.7 SDK.
=> Check build-time SDK in LoadMainMenuNibIfAvailable

src/joystick/iphoneos/SDL_mfijoystick.m
Fixes #6601.
`@available` is not available in Xcode versions older than 9.0, so check for it before using.
https://github.com/libsdl-org/SDL/issues/6601
=> SDL_mfijoystick.m: fix build with Xcode < 9

src/video/wayland/SDL_waylandsym.h
The function returns an int, not a bool.
=> wayland: Fix libdecor_dispatch signature

src/video/khronos/vulkan/vulkan_metal.h
Fixes #6598
ARC, at least with older compilers and/or SDKs, doesn't allow Objective-C objects in structs without declaring them `__unsafe_unretained`.
https://github.com/libsdl-org/SDL/issues/6598
=> vulkan_metal.h: Make compatible with ObjC ARC

Makefile.in, android-project/gradlew, configure.ac, src/events/SDL_keysym_to_scancode.c, src/events/scancodes_linux.h, src/joystick/check_8bitdo.sh
GNU grep 3.8 emits a deprecation warning on use of egrep/fgrep.
=> Avoid use of deprecated egrep/fgrep

src/video/wayland/SDL_waylanddyn.h
Explicitly include the Wayland protocol headers when statically linking against the Wayland libraries, or older system headers might be used instead of the locally generated versions.
Should fix #6589
I say should as I can't replicate their exact build error, but this fixes a header discrepancy between the shared/non-shared library code paths, and the header in question contains the object and function definitions that their build said were missing.
=> wayland: Fix build when not using the shared Wayland libraries

src/video/ngage/SDL_ngagevideo.h
Fix non-working N-Gage port.
I messed something up in my test workflow.
The bitdraw.h include can't replaced by a stub class. This PR basically reverts the commit and keeps the cleanup.
I apologise for the slip-up.
#6610
=> Fix non-working N-Gage port.

.github/workflows/main.yml, CMakeLists.txt, Makefile.in, configure.ac
We want the library to come out as libSDL3.so.0 on Unix, or something similar on other platforms. There's no need to have libSDL3-3.0.so.0, because next time we intentionally break the API it should become libSDL4 anyway.
Partially implements #5626.
---
Autotools: changed here
CMake: changed here
Android.mk: already used the simpler name
Makefile.minimal: already used the simpler name
XCode: TODO, I have no idea how this works (maybe it uses the simpler name already)
Visual Studio: TODO, I have no idea how this works (maybe it uses the simpler name already)
android-project{,-ant}: TODO, I have no idea how this works (maybe it uses the simpler name already)
=> [SDL3] build: Simplify library name

docs/README-migration.md, include/SDL_hints.h, src/video/x11/SDL_x11opengl.c, src/video/x11/SDL_x11opengles.c, src/video/x11/SDL_x11video.c, src/video/x11/SDL_x11window.c
`SDL_HINT_VIDEO_X11_FORCE_EGL` was deprecated in favor of the more general `SDL_HINT_VIDEO_FORCE_EGL`, and Xinerama and Xvidmode support were previously removed from SDL, rendering these hints useless.
=> x11: Remove deprecated/defunct X11 hints

src/video/cocoa/SDL_cocoaopengl.m
The `_Nullable` attribute is not available in older versions.
=> Fix build with Xcode < 7

WhatsNew.txt
SDL2 hints that are removed in SDL3 weren't listed in WhatsNew.txt before this change.
Followup of https://github.com/libsdl-org/SDL/pull/6671#issuecomment-1328283945
=> Update WhatsNew.txt with removed hints.

CMakeLists.txt
- Avoid caching `HAVE_xx` options: cached variables spoil the configuration result when reconfiguring CMake with `-DSDL_ASSEMBLY=OFF` after `-DSDL_ASSEMBLY=ON`.
- Use `SDL_ARCH_xx` variables for enabling/disabling options
- Use `CMakePushCheckState` for handling check states
=> cmake: assembly fixes 

src/audio/SDL_audiocvt.c
While 78f97108f9dad22db6708f28322561eb9828fc36 reduced the accumulation error, it was still big enough to cause distortions. Fixes #6196.
=> SDL_ResampleAudio: Fix float accumulation error

src/filesystem/unix/SDL_sysfilesystem.c
`argv[0]`/`getexexname()` are not always absolute paths by default and can be modified to anything the developer wants them to be. Consider using `readSymLink("/proc/self/path/a.out")` instead and `getexecname()` as the fallback, since the symlink will always be the correct absolute path (unless `/proc` is not mounted, but it is by default on Solaris and Illumos platforms).
=> Solaris getexecname() returns argv[0]; consider using procfs instead.

src/thread/n3ds/SDL_syssem.c, src/thread/ngage/SDL_sysmutex.cpp
- SDL_CreateMutex returns NULL when the creation fails (ngage)
- SDL_SemValue returns 0 when the semaphore is NULL (n3ds)
=> thread: fix inconsistent return values

src/video/SDL_pixels.c, src/video/cocoa/SDL_cocoametalview.m, src/video/uikit/SDL_uikitmetalview.m
- do not overwrite error message set by SDL_InitFormat (SDL_AllocFormat)
- set proper error message (SDL_AllocPalette + Cocoa_Metal_CreateView)
- protect against allocation failure (UIKit_Metal_CreateView)
=> video: fix error messages

CMakeLists.txt
- Directly use SDL version to set SO version, simplify DYLIB versioning in the same commit
- No more `SDL_CMAKE_DEBUG_POSTFIX` ==> debug libraries won't have a `d` suffix by default anymore
Fixes #5626
Fixes #6703
cc: @smvc
=> cmake: simplify SO/DYLIB versioning + remove SDL_CMAKE_DEBUG_POSTFIX option

src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandvideo.h, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h, wayland-protocols/fractional-scale-v1.xml
A pending protocol adds support for more native communication of
fractional scaling.
Everything in the wayland backend already existed only the fractional
scale was calculated implicitly through a combination of output size
guesswork.
The new protocol makes that explicit. I have left the old code in place
for now.
draft because:
1) it needs more testing. Volunteers please!
2) the protocol is not yet landed, which is a chicken and egg with
approval here
=> wayland: Support wp-fractional-scale-v1 protocol

src/video/SDL_video.c
Right, let's try this again...
It's been about a year and a half since the first attempt, and we've had some good progress on the Wayland driver in that time. In particular, the Fedora project and most (maybe even all?) Flatpaks have enforced Wayland by default, which has forced a lot of developers to dogfood the new backend a bit more. With all the improvements (and with the scariest bug now resolved) let's track this one more time.
I'm still out for the rest of the year and the next deadline is less than 3 weeks away, so at the absolute best this is going to be a 2.28 task.
In any case, the tracker!
Fractional Scaling Stuff:
- #5892
- #6707
External Stuff Involving Us:
- #6531
- Blocked by https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/283
External Stuff Not Involving …
=> video: Prefer Wayland over X11 (take 2!)

CMakeLists.txt
This will only work with CMake 3.16+ and is enabled by default.
It can be disabled by configuring with `-DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON`.
=> cmake: add support for precompiled headers

.github/workflows/psp.yaml, .github/workflows/riscos.yml, CMakeLists.txt, test/CMakeLists.txt
- Do verbose CMake PSP build
- Tag RISCOS as bool (this is just meta information for CMakeCache.txt)
- Build SDL with rpaths: this allows the tests to be linked against libSDL3.so.0, without requiring `LD_LIBRARY_PATH`.
When configuring SDL with `-DSDL_INSTALL_TESTS=ON`, the rpath is removed at install time.
- Clean up `test/CMakeLists.txt` a bit + make it CMake 3.0 compatible (untested)
* add option in `test/CMakeLists.txt` to link against a static/shared SDL3 library.
* The test cmake script also contained duplicate information about dependent libraries (e.g. the libraries required for PSP).
CMake already knows about these via the `SDL3::SDL3/SDL3::SDL3-static` targets.
* Build `test/testutils.c` only once, instead of once for every test executable requiring it.
=> cmake: don't repeat dependent libraries in test/CMakeLists.txt

src/audio/pipewire/SDL_pipewire.c, src/video/wayland/SDL_waylandclipboard.c, src/video/wayland/SDL_waylanddatamanager.c, src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandkeyboard.c, src/video/wayland/SDL_waylandopengles.c, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandwindow.c
Fixes the formatting on some function signatures that clang-format missed.
=> Fix formatting on Wayland and Pipewire function signatures

src/joystick/SDL_joystick.c
This adds the missing vendor + product id for the Logitech PRO Racing Wheel  in PC and PS4/PS5 mode.
=> Detect Logitech PRO Racing Wheel as wheel

src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandevents_c.h, src/video/wayland/SDL_waylandtouch.c
SDL events support system timestamps now, so pass them through.  This just wires up basic functionality, higher resolution event handling will come later.
Closes #6738 
One issue: On line 483, a pointer movement event is generated when the pointer enters the window, however, there is no system timestamp provided for this event so the default 'now' value is used, which creates an anomaly in the subsequent pointer movement timestamps.   The movement events that follow the enter event have older timestamps even though they are actually newer.
Does this fake movement event still need to be there, or was this to fix a bug in an old version of some compositor and is no longer required?  Any other suggestions for dealing with this issue?
=> wayland: Pass event timestamps to SDL

src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandevents_c.h, src/video/wayland/SDL_waylandtouch.c, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandvideo.h, wayland-protocols/input-timestamps-unstable-v1.xml
Add the protocol for high-resolution timestamp events and subscribe to them if available.
Event timestamps are now handled natively in nanoseconds as much as possible to avoid error-prone conversions.
Variables have been appended with _ms or _ns where appropriate, to avoid ambiguity.
=> wayland: Add high-resolution event timestamp support

src/audio/SDL_mixer.c, src/core/openbsd/SDL_wscons_kbd.c, src/cpuinfo/SDL_cpuinfo.c, src/render/SDL_render.c, src/test/SDL_test_common.c, src/test/SDL_test_md5.c, src/video/SDL_blit_slow.c, src/video/SDL_fillrect.c, src/video/SDL_stretch.c, src/video/SDL_video.c
Fix warnings 'macro argument should be enclosed in parentheses'
=> Fix warnings 'macro argument should be enclosed in parentheses'

src/video/wayland/SDL_waylandwindow.c
"app_ids" can be used for multiple windows
Signed-off-by: Lei.Huang <leihuang@amd.com>
Currently, classname is used. Only one name can be set for a process, which cannot support multiple windows。
Added a method to set the appid, which is set through the sdl window title
=> Add window title to app_ids for different

src/video/wayland/SDL_waylandevents.c
Always pass through undefined event timestamps of 0 so the current time will be used for the event.
=> wayland: Pass through event timestamps of 0

src/video/wayland/SDL_waylandevents.c
Num Lock and Caps Lock always need to be explicitly handled by the modifier handler function, or they won't be correctly set if active at application startup, or if the lock state is changed while the application lacks focus since a key press for these keys will never be received.  In these cases, the internal SDL modifier state can end up the inverse of the actual modifier state.
=> wayland: Handle the Num Lock and Caps Lock modifiers via modifier events

docs/README-n3ds.md, src/thread/n3ds/SDL_syssem.c, src/thread/n3ds/SDL_systhread.c, test/testsem.c
There were a handful of issues with Nintendo 3DS' semaphore implementation. Namely:
- lacking a function to wait with a timeout, it had a naive implementation that tried once every millisecond.
- contended Post/TryWait operations would hang the OS.
This PR addresses both issues:
- the best delay between acquire attempts seems to be around 10-100µs, which gave about 10 timeouts each for 10000 iterations
- for TryWait, a delay of at least 50µs after the call is needed to avoid the OS hang.
Testing was done using `test/testsem.c`.
I'll make a similar patch for the SDL2 branch since it is also applicable there.
N/A
=> N3DS: Semaphore fixes.

docs/README-n3ds.md, src/thread/n3ds/SDL_syssem.c, src/thread/n3ds/SDL_systhread.c, test/testsem.c
Backport the fixes from #6776 to the SDL2 branch.
Related to #6776.
=> N3DS: Backport semaphore fixes to SDL2 branch.

.gitignore
Some of these are probably unnecessary now that Autotools (with its optional in-tree builds) has been deleted in favour of CMake (with mandatory out-of-tree builds), but let's be consistent.
Spotted while doing a `git grep` for other bugs of the same form as #6801.
=> [SDL3] .gitignore: Replace all SDL2 with SDL3

src/core/linux/SDL_dbus.c, src/core/linux/SDL_dbus.h, src/core/linux/SDL_ibus.c
This fixes the crash seen https://github.com/libsdl-org/SDL/issues/6712
not sure if this is the right thing to do.
but there were already a "connection_unref", make sense to have a "connection_ref"
=> DBus: add a reference to the connection (Fixed bug #6712)

src/video/wayland/SDL_waylandevents.c
On window focus, look up the pressed modifier keys via keycodes instead of scancodes to handle the case of remapped keys, as xkb remapping changes the associated keycode, not the scancode.
=> wayland: Look up pressed keys via keycodes instead of scancodes on keyboard entry

android-project/app/src/main/java/org/libsdl/app/SDL.java, android-project/app/src/main/java/org/libsdl/app/SDLActivity.java, android-project/app/src/main/java/org/libsdl/app/SDLAudioManager.java, include/SDL_surface.h, src/audio/aaudio/SDL_aaudio.c, src/audio/aaudio/SDL_aaudiofuncs.h, src/audio/android/SDL_androidaudio.c, src/core/android/SDL_android.c, src/core/android/SDL_android.h
Make it possible to select a specific audio device for Android
Support selecting a specific audio device on Android. Currently supporting only aaudio and android drivers. openslES support is missing.
Fixes #6813
=> Android audio device selection

include/SDL3/SDL_events.h
=> Use alias types for which members of event structs instead of plain types

include/build_config/SDL_build_config_xbox.h, src/video/windows/SDL_windowsopengl.c, src/video/windows/SDL_windowsopengl.h, src/video/windows/SDL_windowsvideo.h, src/video/windows/SDL_windowswindow.c
This is a WIP patch to build the Xbox GDK SDL with OpenGL support. This is part of the FNA team's work to support GDK via GLon12, which is also in development:
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/19022
In addition to enabling the obvious stuff, we have some GDI/WGL "stuff" that we're faking for Xbox targets, and that could possibly change depending on what we do for GLon12. @TheSpydog has been handling it up to this point, but we're also bringing in [Eden Industries](http://edenindustries.ca/blog/) to put the finishing touches on everything!
=> gdk: Add support for building with OpenGL on Xbox

src/dynapi/SDL_dynapi_procs.h
Fixes the dynapi signature of `SDL_GDKSuspendComplete` to remove a stray `return` that was resulting in build warnings for GDK. This was already fixed on main, but it wasn't backported to SDL2.
=> [SDL2] Fix dynapi signature for SDL_GDKSuspendComplete

src/video/windows/SDL_windowsopengl.c
Fixes a build error (a missing `_THIS`) when compiling SDL_windowsopengl.c for Xbox GDK. This will need to be backported to SDL2 as well.
=> Fix Xbox GDK OpenGL build error

src/core/android/SDL_android.c, src/dynapi/SDL_dynapi.sym, src/dynapi/gendynapi.py, src/hidapi/android/hid.cpp, src/hidapi/android/hid.h
By registering all methods from withing `JNI_OnLoad`, we don't need to export any native method.
This simplifies #6859
=> android: register all methods using JNI_OnLoad

include/SDL_hints.h, src/video/windows/SDL_windowsevents.c, src/video/windows/SDL_windowsvideo.c, src/video/windows/SDL_windowsvideo.h
Add a new Windows-only hint, `SDL_HINT_WINDOWS_DISABLE_MENU_MNEMONICS`, to make it possible to select whether the behavior of pressing Alt+something is better suited for graphics-only applications or applications that also have UI elements.
See #6726.
=> Add `SDL_HINT_WINDOWS_ENABLE_MENU_MNEMONICS`.

src/video/winrt/SDL_winrtgamebar.cpp, src/video/winrt/SDL_winrtvideo.cpp
Add `const` on some strings, use `SDL_strdup` on others.
I recently compiled the WinRT code of SDL and ran into these warnings (as errors from `/Zc:strictStrings`, in my project).
=> fix string literal constness warnings

src/video/kmsdrm/SDL_kmsdrmvideo.c
A previous cleanup commit inverted a statement that checked the return value of a KMSDRM_CreateSurfaces call during KMSDRM_CreateWindow, which causes the video backend to always fail despite success.
This commit restores the intended behavior. It probably needs to also be cherry-picked for the SDL2 branch.
Fixes: 3c501b963dd8 ("Clang-Tidy fixes (#6725)").
=> kmsdrm: Fix wrong check on KMSDRM_CreateWindow.

WhatsNew.txt, build-scripts/rename.py, include/SDL3/SDL.h, include/SDL3/SDL_oldnames.h
You can rename APIs using rename.py and all the code and documentation will be updated, and entries will be added to WhatsNew.txt and docs/README-migration.md.
e.g. `rename.py SDL_foo.h function SDL_CreateFoo SDL_FooCreate`
SDL_oldnames.h is included in the SDL header, and if you define SDL_ENABLE_OLD_NAMES, will redefine the old API functions to call the new ones, and if not, will define them as a symbol letting you what the new API function is.
=> Added infrastructure for renaming API functions

include/SDL_thread.h
SDL_CreateThreadWithStackSize doesn't pass the stack size when using win32 static api, causing build failures due to incorrect number of arguments
https://github.com/libsdl-org/SDL/issues/6904
=> Fix SDL_CreateThreadWithStackSize

include/SDL3/SDL_joystick.h, src/joystick/SDL_sysjoystick.h
remove underscore in _SDL_Joystick 
@slouken it seems you missed this one ?
=> Remove reserved underscore SDL_joystick
