- docs/README-git.md
- docs/README-hg.md
Just a simple commit to correct the docs!
> We're in Git now! Updated docs.

- src/audio/emscripten/SDL_emscriptenaudio.c
- src/filesystem/emscripten/SDL_sysfilesystem.c
- src/video/emscripten/SDL_emscriptenevents.c
I was about to push some of these, but I see the repo is on GitHub now... so here you go.
> A few Emscripten patches

- .github/PULL_REQUEST_TEMPLATE.md
Yup - overstepping already. :)
Totally fine to smash this one. I've used it in many projects to try and organize PR's coming in for the maintainers. No idea what really *matters* for a maintainer in this project for a review, so this is a way to just help out.
> a draft for a github pull_request template

- src/video/kmsdrm/SDL_kmsdrmvideo.c
Simple indentation correction so the KMSDRM_CreateWindow function is easier to read.
> [KMSDRM] Correct indentation.

- android-project/app/src/main/java/org/libsdl/app/SDLActivity.java
- include/SDL_system.h
- src/core/android/SDL_android.c
- src/core/android/SDL_android.h
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
add SDL_AndroidShowToast for https://developer.android.com/reference/android/widget/Toast
Show toast in UI thread [https://developer.android.com/guide/topics/ui/notifiers/toasts]
Params description
message   : text message to be shown
duration  : 0 - short [https://developer.android.com/reference/android/widget/Toast#LENGTH_SHORT],
1 - long  [https://developer.android.com/reference/android/widget/Toast#LENGTH_LONG]
gravity   : the location at which the notification should appear on the screen.
It's an optional parameter. Set -1 if you don't want specify any gravity or
choose some value from https://developer.android.com/reference/android/view/Gravity
xOffset   : set this parameter only when gravity >=0
yOffset   : set this parameter only when gravity >=0
Returns 0 if success, -1 if any …
> add SDL_AndroidShowToast

- src/video/kmsdrm/SDL_kmsdrmsym.h
- src/video/kmsdrm/SDL_kmsdrmvideo.c
- src/video/kmsdrm/SDL_kmsdrmvideo.h
This PR adds KMSDRM gamma support.
> KMSDRM: Add gamma support

- src/video/kmsdrm/SDL_kmsdrmvideo.c
Fixes a couple of KMSDRM-related warnings.
> Fix KMSDRM-related warnings

- src/audio/pipewire/SDL_pipewire.c
> audio: pipewire: fix uninitialized variable warnings

- .github/workflows/main.yml
The current CI doesn't work and can be fixed. To simplify steps, use a matrix to build on various OS + allow platform specific flags.
The linux build should now cover a wider case of video backends.
no issue, just all github builds are broken so far
> Fix and improve github CI

- Makefile.in
- configure.ac
- src/video/haiku/SDL_BWin.h
- src/video/haiku/SDL_bvideo.cc
These are the latest SDL patches for the HAIKU operating system.
Ref: https://github.com/haikuports/haikuports/blob/master/media-libs/libsdl2/patches/libsdl2-2.0.14.patchset
Closes #3116
>  SDL: Updated SDL patches for HAIKU

- src/video/kmsdrm/SDL_kmsdrmvideo.c
This commit removes the calls to SDL_GL_LoadLibrary() and SDL_GL_UnloadLibrary() on the KMSDRM backend.
Those calls weren't doing anything apart from mark the library as being loaded, because on the KMSDRM backend I had to make SDL_GL_LoadLibrary() and SDL_GL_UnloadLibrary() point to dummy functions.
Long story on why these are dummy functions: that had to be done so I could do the actual EGL/GL library loading at the right time.
And the right time is AFTER the GBM stuff is initialized, which is done on window creation, not sooner in VideoInit() because doing so would prevent Vulkan apps from working since Vulkan accesses the DRM/GBM stuff itself too.
Anyway: this also improves some comments I need for future reference on how things work internally, so I can easily go back to the …
> Remove unneeded function calls and improve comments for future reference.

- src/video/SDL_video.c
- src/video/wayland/SDL_waylandmessagebox.c
- src/video/wayland/SDL_waylandmessagebox.h
> Implement Wayland_ShowMessageBox using Zenity

- test/testautomation_clipboard.c
- test/testautomation_keyboard.c
- test/testautomation_platform.c
- test/testautomation_sdltest.c
- test/testautomation_video.c
- test/testdrawchessboard.c
- test/testmultiaudio.c
- test/testoverlay2.c
- test/testqsort.c
- test/testrelative.c
- test/testspriteminimal.c
- test/teststreaming.c
- test/testviewport.c
- test/testvulkan.c
This cleans up the test code to silence compiler warnings.
> test code cleanups to silence warnings

- debian/docs
Signed-off-by: Philippe Coval <rzr@users.sf.net>
Change-Id: I7cd02e3094cb60328a24702afecb13f61beb67a1
> debian: Update README file in doc package

- .gitignore
Signed-off-by: Philippe Coval <rzr@users.sf.net>
Change-Id: Iebfef58f41056c01736aba99f38fdedb9ee93013
> git: Ignore debian generated files

- src/video/wayland/SDL_waylandvideo.c
> wayland: Fix leaked zxdg_decoration_manager

- src/video/kmsdrm/SDL_kmsdrmvideo.c
This PR is in preparation for the 6.9 release of OpenBSD. It also avoids issues that may arise later when the "/dev/drmN" device nodes are eventually removed.
> KMSDRM: Only use OpenBSD-specific defines on pre-6.9 releases

- src/video/x11/SDL_x11video.c
- src/video/x11/SDL_x11window.c
- src/video/x11/SDL_x11window.h
This PR implements SDL_SetWindowAlwaysOnTop for X11.
> Implement SDL_SetWindowAlwaysOnTop for X11

- src/joystick/SDL_joystick.c
Adds the T300RS to the list of known wheels when querying the device type.
n/a
> Added T300RS to known wheel list

- src/video/wayland/SDL_waylandwindow.c
Sneaking in one last thing before 2.0.16! The libdecor patch had these flags set in its configure callback and made me realize that these events were not exposed to SDL's queue.
CC @christianrauch, this probably needs to be applied to #4068 as well (in contrast, the input focus flag should be fine as-is).
> wayland: Add support for maximized/restored events

- src/video/wayland/SDL_waylandvideo.c
- src/video/wayland/SDL_waylandwindow.c
- src/video/wayland/SDL_waylandwindow.h
Wayland patch to supplement #4418.
Fixes #4372.
> wayland: Implement FlashWindow

- CMakeLists.txt
- docs/README-vita.md
- include/SDL_config.h.cmake
- src/render/SDL_render.c
- src/render/SDL_sysrender.h
- src/render/vitagxm/SDL_render_vita_gxm.c
- src/render/vitagxm/SDL_render_vita_gxm_tools.c
- src/render/vitagxm/SDL_render_vita_gxm_types.h
- src/video/vita/SDL_vitagl.c
- src/video/vita/SDL_vitamessagebox.c
- src/video/vita/SDL_vitavideo.c
* Removed leftovers from vita-gles2 renderer and some dead code.
* Switched to conditional build of gles2 support due to popular demand. That'll help with implementing support for different gl library. (and we'll deal with this on vitasdk side with different package "flavors", default one being gl-less).
> Updates to vita port

- docs/README-android.md
The android-project-ant directory does not exist anymore.
> Removed reference to ant project.

- src/video/windows/SDL_windowsevents.c
Patch from https://github.com/flyinghead/flycast/commit/ed7bd06f9632e6a1c820c92d945c6aa6000f4e61#diff-0279799c4cfea36eb3715e2e22270474ee6506a367f4f5111755face9b111285
> SDL_windowsevents: add support for multiple mice

- .github/workflows/main.yml
> CI: add github actions for windows x86

- src/render/vitagxm/SDL_render_vita_gxm.c
Fixes rotation (and scaling) around non-default center-point.
> VITA: Rewrite and fix RenderCopyEx rotation

- src/video/kmsdrm/SDL_kmsdrmvulkan.c
Fixes various issues related to improper initialization of the `VK_KHR_display` info structs.
> kmsdrm: various fixes

- Makefile.in
- configure.ac
Fixes Makefile.in and configure.ac for building on the Haiku operating system.
Patch by: https://github.com/jessicah
Ref: https://github.com/haikuports/haikuports/issues/6095
>  SDL: Updated patches for HAIKU

- src/video/wayland/SDL_waylanddyn.h
- src/video/wayland/SDL_waylandsym.h
- src/video/wayland/SDL_waylandwindow.c
We missed a couple spots for libdecor support - luckily both are straightforward and self-explanatory.
> Implement a few Wayland functions for libdecor

- src/video/wayland/SDL_waylandvideo.c
While libdecor supports zxdg-decoration, we already have our own implementation and we know it works (and we can debug it if something goes wrong). With this in mind, I flipped the priorities for SSD/CSD: We'll try to get both xdg-shell and zxdg-decoration, but if the latter is unavailable we'll fall back to libdecor.
Tested with both GNOME and Plasma.
> wayland: Prefer our SSD implementation if available

- src/video/wayland/SDL_waylandwindow.c
This is an attempt to re-do #4570's work to make the libdecor configure callback more like the one used for xdg-shell. It mostly copies the order of operations from xdg_toplevel/xdg_surface, then fills the rest in with the appropriate libdecor functions.
Tested with Super Hexagon (nonresizable) and VVVVVV (resizable) and both seem happy! @christianrauch, as long as this passes your tests we should be good to go here.
> wayland: Make libdecor configure match xdg_toplevel

- WhatsNew.txt
Adding a note about the new keyboard grab APIs for 2.0.16.
> Add note about keyboard grab to WhatsNew.txt for 2.0.16

- src/video/wayland/SDL_waylandwindow.c
Configure events from compositors have an extremely annoying habit of giving us completely bogus sizes, from all sorts of places. Thankfully, the protocol gives us the ability to completely ignore the width/height and just stick with what we know, so for all windows that are not meant to be resized, pretend we never even got the width/height at all, the compositor is required to respect our dimensions whether they match configure's suggestion or not.
Tested with FEZ, Capsized, Streets of Rage 4, a handful of Unity games, Baba Is You, Portal 2, and Super Hexagon.
This fixes an issue with xdg-shell where going from fullscreen->windowed would give us configure event that very clearly ignored dimensions passed via a SetWindowSize call. Should fix #4572 to the extent that is possible (need a …
> wayland: Always assume configure is wrong for non-resizable windows.

- src/video/wayland/SDL_waylandopengles.c
Use `SDL_IOReady()` to sleep until we have events to dispatch rather than busy looping
Fixes #4609
> wayland: Avoid busy waiting for vsync

- src/video/x11/SDL_x11modes.c
If we are already in the desired mode, changing it is a no-op at best,
and harmful at worst: on Xwayland, it sometimes happens that we disable
the crtc and cannot re-enable it.
Resolves: https://github.com/libsdl-org/SDL/issues/4630
---
This is another possible way to avoid #4630.
@amshafer, is this any better for you than #4632?
> x11: Don't change mode if we are already in the correct mode

- .github/workflows/emscripten.yml
Was doing some Emscripten stuff today, so thought this might be useful.
> Add Emscripten CI build

- test/testvulkan.c
Fix the vulkan test application behavior with resizing.
Vulkan provides validation layers to help the application figure out potential programming error.
There are a number reported when using the test application with resizing enabled.
This fixes those issues. There is also a Intel/Mesa driver issue that needs to be fixed https://gitlab.freedesktop.org/mesa/mesa/-/issues/5177
This is addressing https://github.com/libsdl-org/SDL/issues/4595
There are a number reported when using the test application with resizing enabled.
> test/vulkan: fix/workaround validation errors

- .gitignore
- test/CMakeLists.txt
- test/Makefile.in
- test/Makefile.os2
- test/README
- test/testmouse.c
This is helpful when testing mouse events, and ensuring that the mouse position matches the position reported by SDL.
> Add testmouse

- src/video/vita/SDL_vitagl_pvr.c
> Vita: Allow completely skipping pvr init to override apphint from app

- .github/workflows/vita.yaml
CI integration of PS Vita build using vitasdk docker image.
> Add PS Vita CI build

- CMakeLists.txt
- VisualC/SDL/SDL.vcxproj
- VisualC/SDL/SDL.vcxproj.filters
- include/SDL_hints.h
- src/thread/windows/SDL_syscond_cv.c
- src/thread/windows/SDL_sysmutex.c
- src/thread/windows/SDL_sysmutex_c.h
This is @cgutman's patch from #4051, rebased to the HEAD.
> Allow usage of the new Condition Variable code with Critical Sections

- src/thread/vita/SDL_systhread.c
* Fix thread priority
* Add support for thread name and stack size
> Vita: fix threads

- src/thread/vita/SDL_systhread.c
> Vita: fix thread detach. Remove leftover KillThread

- src/video/SDL_blit_A.c
This provides some performance improvements on RISC OS, which often uses XBGR8888 for the framebuffer.
> Add a fast path for ARGB888->(A)BGR888 blending with pixel alpha

- src/render/vitagxm/SDL_render_vita_gxm.c
Implement render commands batching.
While perf boost is negligible, as a side effect that cleans code a little (merging codepaths for drawlines/drawpoints and rendergeometry)
> Vita: support render batching

- src/audio/SDL_audiocvt.c
Add audio conversion from/to 6.1
to fix the issue "Audio Capture from source with 7 channels" (#4458)
Compile, but not tested !
Audio 6.1: https://fr.wikipedia.org/wiki/6.1
#4458
> Add audio conversion from/to 6.1

- docs/README-os2.md
> fixed typo: ervironment to environment

- src/video/wayland/SDL_waylanddyn.h
- src/video/wayland/SDL_waylandsym.h
> Fix build against wayland 1.20

- src/render/psp/SDL_render_psp.c
This PR improves the `PSP` renderer. It listens again to the `vsync` values.
Additionally if the `PSP` is not able to run at full speed automatically will disable `vsync`
Thanks
> [PSP] Improve performance when vsync is enabled

- src/thread/psp/SDL_sysmutex.c
This PR simplifies logic used in the mutex for PSP, it also uses new functions from SDK which are lighter and faster.
Thanks
> [PSP] Use lightweight mutex for improving performance

- src/render/SDL_render.c
- src/render/direct3d/SDL_render_d3d.c
- src/render/direct3d11/SDL_render_d3d11.c
- src/render/metal/SDL_render_metal.m
- src/render/opengl/SDL_render_gl.c
- src/render/opengles/SDL_render_gles.c
- src/render/opengles2/SDL_render_gles2.c
Remove specific QueueDrawLines and use RenderGeometry
> Remove specific QueueDrawLines

- src/main/haiku/SDL_BApp.h
- src/stdlib/SDL_string.c
- src/video/haiku/SDL_BApp.h
- src/video/haiku/SDL_bframebuffer.cc
- src/video/haiku/SDL_bopengl.cc
- src/video/haiku/SDL_bvideo.cc
- src/video/haiku/SDL_bwindow.cc
- src/video/haiku/SDL_bwindow.h
Haiku patchset integration for libsdl 2.0.20.
Patchset: https://raw.githubusercontent.com/haikuports/haikuports/master/media-libs/libsdl2/patches/libsdl2-2.0.20.patchset
> libsdl: updated libsdl 2.0.20 for Haiku

- src/render/opengles2/SDL_render_gles2.c
When the texture state is changed outside the main state function, we forgot to disable vertex attrib array textcoord.
data->glDisableVertexAttribArray((GLenum) GLES2_ATTRIBUTE_TEXCOORD);
better fix that PR #5266 
#5235
> Br gles2 update texture state v2

- src/audio/pipewire/SDL_pipewire.c
The context and stream creation functions will automatically destroy the passed properties object in case of failure, so don't free it twice.
> audio: pipewire: Don't double free properties on init failure

- src/video/wayland/SDL_waylandevents.c
- src/video/wayland/SDL_waylandkeyboard.h
For every batch of text_input_v3 updates, if there is no preedit in this
batch, preedit should be cleared.
> Fix text_input_v3 preedit string

- src/joystick/SDL_joystick.c
This thing changes its VID/PID on firmware revisions...
> Add additional VID/PIDs for Anne Pro II

- src/video/haiku/SDL_BWin.h
As in the title, this rolls up a number of changes made in the HaikuPorts downstream. They should generally be self-explanatory, or have explanations in their commit messages.
> Rollup of downstream changes from HaikuPorts

- src/render/opengl/SDL_render_gl.c
Do OpenGL batching.
So that we can drop the glBegin/glEnd and be more consistent.
Code is similar to the GLES2 backend.
(add @slime73 )
> SDL_Renderer do Opengl batching

- docs/README-vita.md
> Vita: credit cpasjuste

- src/core/openbsd/SDL_wscons_kbd.c
wscons: Make USB keyboard input layout independent
Other keyboard types continue to use the current mechanism as a fallback.
None.
> wscons: Make USB keyboard input layout independent

- src/audio/openslES/SDL_openslES.c
Allow using of the float output type on newer Android devices, but keep PCM16 output on older
Here is possible to detect the support for the float type by dynamical retrieving of the SDK version. So, let's use this than just force everybody to use the limitation of old devices.
Closes #5358
> SDL_openslES.c: Detect float support in runtime

- src/joystick/SDL_joystick.c
Add the Thrustmaster T248, as well as some alternate IDs for the T300RS.
n/a
> Add some Thrustmaster wheels to known wheel list

- src/render/vitagxm/SDL_render_vita_gxm.c
> Vita: Fix NULL-pointer dereference

- test/testshader.c
1. Initialize shader compile status variable. 
2. Add check for program link status, to provide more information to developer in case of linking failure.
Tested on Linux.
> testshader: Initialize compile status variable and check also program link status

- src/video/wayland/SDL_waylandwindow.c
Use viewports for non-fullscreen windows when the desktop uses fractional scaling and the window is flagged as DPI-aware to provide a backbuffer mapped as close to 1:1 output as possible.  In the cases of odd window sizes the backbuffer may be a pixel off of scaling perfectly into the window size due to it's scaled size being rounded off, but a minute amount of scaling during output is likely preferable to the large amounts of overdraw needed with integer scaled buffers.
@flibitijibibo
> video: wayland: Use viewports for non-fullscreen windows with fractional scaling

- test/Makefile.in
> test: Copy utf8.txt to build directory

- WhatsNew.txt
New dependencies are useful things for packagers to know about.
> WhatsNew.txt: Document new dependency on libwayland-client 1.18.0

- include/SDL_rect.h
Move and add some documentation comments.
> SDL_Rect: Add \sa documentation block to SDL_FRect

- src/core/windows/SDL_hid.c
- src/core/windows/SDL_hid.h
- src/joystick/windows/SDL_rawinputjoystick.c
> joystick: get HID top-level collection preparsed data directly from RawInput API

- src/SDL_assert.c
I forgot about the 'assert' side in #5646. Probably not as important, but here's a version anyway.
First I moved the rendering of the string to a separate function, to get rid of the loop-to-retry construction.
I then decided on a small semantic change; instead of aborting on allocation failure/integer overflow, we use the (truncated) stack buffer instead.
The return value of the `SDL_snprintf()` is now checked, and failure there is treated as fatal.
> assert: Check for integer overflow before malloc.

- src/SDL_hints.c
Free `entry` in error path.
None
> Fix potential memory leak in SDL_AddHintCallback

- src/video/kmsdrm/SDL_kmsdrmvulkan.c
- src/video/x11/SDL_x11window.c
- test/testautomation_platform.c
- test/testguid.c
Detected by Debian's packaging QA tool, Lintian.
> Fix some typos in diagnostic messages

- CMakeLists.txt
Fix an issue after rebasing applying suggestions in #5806
> [PS2] Fix Compilation CI

- android-project/app/src/main/java/org/libsdl/app/SDLActivity.java
I did these fixes a while ago while debugging my application, however, forgot to send them back.
> SDLActivity.java: Compatibility fix for debugSource

- src/joystick/sort_controllers.py
Changed some lines of code according to Python conventions. No functionality is changed.
> Python conventional changes

- src/filesystem/ps2/SDL_sysfilesystem.c
Improving filesystem driver.
The previous implementation wasn't working proplery, now it creates the parent folders if needed.
Cheers
> [PS2] Improve filesystem driver

- src/video/windows/SDL_windowsevents.c
Accidentally omitted the comment part mentioned in #5869
> Fixed comment after #endif in Xbox changes

- src/audio/pipewire/SDL_pipewire.c
Pipewire 0.3.44 introduced PW_KEY_TARGET_OBJECT, which is to be used to specify target connection nodes for streams.  This parameter takes either a node path (PW_KEY_NODE_NAME) or serial number (PW_KEY_OBJECT_SERIAL) to specify a target node.  The former is used in this case since the path is already being retrieved and stored for other purposes.
The target_id parameter in pw_stream_connect() is now deprecated and should always be PW_ID_ANY when PW_KEY_TARGET_OBJECT is used.
@flibitijibibo
> pipewire: Use PW_KEY_TARGET_OBJECT to specify stream connection nodes

- src/audio/directsound/SDL_directsound.c
> directsound: For channel counts > 2, generate a dwChannelMask for CreateSoundBuffer

- acinclude/ax_compute_relative_paths.m4
- acinclude/ax_normalize_path.m4
- acinclude/ax_recursive_eval.m4
- configure
- configure.ac
- sdl2-config.cmake.in
This is the SDL equivalent of https://github.com/libsdl-org/SDL_ttf/pull/238#event-7052032195
Please test on your Macos system, with SDL installed in the same way as homebrew does.
> autoconf: use ax_compute_relative_paths

- src/video/wayland/SDL_waylandmouse.c
GNOME exposes the cursor size and theme via the org.freedesktop.portal.Settings interface of the xdg-desktop portal, so query these values via D-Bus, if available.
The XCURSOR_SIZE/XCURSOR_THEME envvars will be tried first, so as not to override any user specified sizes or themes, then D-Bus, then, failing that, it will fall back to default values.
> wayland: Use D-Bus to retrieve the cursor size and theme on GNOME

- include/SDL_atomic.h
- src/atomic/SDL_spinlock.c
pause instructions so could be used in app infinite loops.
A handful of games do already so we unify it in one place.
> Proposing exposing as public api the various arch dependent

- src/video/wayland/SDL_waylandwindow.c
Perform a round trip after showing/hiding the window to avoid protocol errors when ShowWindow() is called immediately after HideWindow().
Fixes #5672
> wayland: Round trip after window show/hide operations.

- src/joystick/ps2/SDL_sysjoystick.c
With the previous implementation, if the `SDL_JoystickClose` function was called, the joystick never worked again, even if the `SDL_JoystickOpen` was called.
Now with this PR, we are opening Joystick in the `SDL_JoystickOpen` if it is closed,
> [PS2] Joystick - Improve OpenPort functionality

- docs/CONTRIBUTING.md
This PR adds contributing guidelines to the project as well as two issue templates (one for bug reports, the other for enhancements).
The issue templates can be seen [here](https://github.com/FtZPetruska/SDL/issues/new/choose), and the contributing file [here](https://github.com/FtZPetruska/SDL/blob/main/docs/CONTRIBUTING.md).
Let me know what you think about it and if you wish for any change to be made!
#5610
> Add contribution guidelines and issue templates.

- src/render/ps2/SDL_render_ps2.c
This PR just basically implements the `SetTextureScaleMode` for the `PS2` render driver.
> [PS2] Render Driver - Implement SetTextureScaleMode

- src/video/wayland/SDL_waylandvideo.c
Since f39500297c17e65b4886df0a17e6e8e692f4a3a9 when a display is freed it isn't removed from `SDL_WaylandOutputData->output_list`.
When a new display is added, the `output_list->next` chain is explored, which can cause a segmentation fault.
With this PR the chain is modified accordingly when `Wayland_free_display` is called.
Fixes #6035.
> `wayland`: Remove freed display from `SDL_WaylandOutputData->output_list`

- src/core/linux/SDL_threadprio.c
If the D-Bus subsystem is shutdown and restarted mid-execution, the cached connection will be invalid. Fetch it each time that it is used to ensure that the connection is always from the current context.
Fixes #6048
> core: linux: Don't cache the RealtimeKit D-Bus connection

- test/testgles2.c
This option allows us to easily reproduce bugs that require more complex rendering techniques, such as those that require a separate render thread (like #6056) or even concurrent rendering on multiple windows at once.
I also fixed issues with how it was handling state across multiple windows, so the viewport is now set correctly in each window when the windows are different sizes.
> testgles2: Add --threaded option to use a render thread per window

- src/video/kmsdrm/SDL_kmsdrmvideo.c
Adresses the problem pointed out in a comment in [this commit](https://github.com/libsdl-org/SDL/commit/e3ea9b5b7c15da16940dc77b9082552c8ddd5570)
> free drm prop before returning

- src/audio/ps2/SDL_ps2audio.c
This PR basically extends the valid PS2 audio configurations
> [PS2] Audio Driver - Add more valid configurations

- src/joystick/windows/SDL_windows_gaming_input.c
assert if calls become unbalanced.
discussed [here](https://github.com/libsdl-org/SDL/issues/6150#issuecomment-1229351413)
Adds an assert (which should never fire unless there's a bug in sdl or the sdl-using app).
I previously found some similar code to be helpful when debugging.
> wgi: refcount the delegate objects

- src/joystick/windows/SDL_windows_gaming_input.c
bound the buttons, hats, and axes in WGI_JoystickUpdate to be <= 255.
The `> 0` check isn't strictly necessary but is IMO nicer.
Just came across this when fixing other warnings in the file.
> WGI_JoystickUpdate: bounds-check array sizes

- src/render/direct3d12/SDL_render_d3d12.c
> Fix compatibility with Windows XP

- src/video/haiku/SDL_bframebuffer.cc
- src/video/haiku/SDL_bmodes.cc
- src/video/haiku/SDL_bmodes.h
This hasn't been tested, but shouldn't in theory result in any behaviour changes.
> haiku: Combine HAIKU_ColorSpaceToBitsPerPixel and HAIKU_BPPToSDLPxFormat

- src/video/SDL_bmp.c
More information and examples can be found here: http://fileformats.archiveteam.org/wiki/Pocket_PC_Bitmap
> Support loading 2bpp .bmp files

- src/render/vitagxm/SDL_render_vita_gxm.c
Fix memory leak in function VITA_GXM_CreateRenderer
> Fix memory leak in VITA_GXM_CreateRenderer

- src/video/cocoa/SDL_cocoametalview.h
- src/video/cocoa/SDL_cocoametalview.m
- src/video/uikit/SDL_uikitmetalview.h
- src/video/uikit/SDL_uikitmetalview.m
I don't think these particular credits are necessary at all, but I don't mind keeping them as long as they're accurate.
None.
> Fix some credit comments.

- src/video/uikit/SDL_uikitappdelegate.m
For example, if I define to hide status bar initially in my project's Info.plist, it's hidden while OS shows the launch storyboard, but as soon as the same is done by SDL by creating the storyboard VC, the status bar appears and moves the VC's content a bit down.
This change embeds the manually displayed storyboard VC into a standard VC which can be fully controlled.
> [iOS] respect initial status bar configuration when displaying the launch storyboard

- src/video/uikit/SDL_uikitvideo.m
- src/video/uikit/SDL_uikitwindow.h
- src/video/uikit/SDL_uikitwindow.m
A little late, but here's the followup to https://github.com/libsdl-org/SDL/pull/6112#issuecomment-1225047075
#6105, #6112
> iOS: implement SDL_GetWindowSizeInPixels.

- include/SDL_metal.h
Just a small documentation fix
> Fix see also in documentation to a valid function in SDL_metal.h.

- src/video/wayland/SDL_waylandwindow.c
The `xdg_surface_set_window_geometry()` calls were needed to fix a bug regarding committing surfaces with an old size after ack-ing a configuration, particularly when entering fullscreen, which has since been fixed as entering fullscreen no longer leads to multiple, overlapping configuration events. Remove the unnecessary calls.
As the `CommitWindowGeometry()` function no longer has a purpose outside of libdecor with this change, it has been renamed to `CommitLibdecorFrame()` and can be used to factor out a little more common code in a couple of places.
Closes #4563
@flibitijibibo 
@dos1
> Wayland: Eliminate XDG surface geometry calls

- src/render/psp/SDL_render_psp.c
Fix memory leak in function PSP_CreateTexture
Remove dead code in function PSP_CreateRenderer
> Fix memory leak in PSP_CreateTexture

- src/video/wayland/SDL_waylandevents.c
libdecor_dispatch() needs to be called, as libdecor plugins might do some required internal processing within, however care must be taken to avoid double-blocking in the case of a timeout, which can occur if libdecor_dispatch() and the SDL event processing both work on the main Wayland queue. Additionally, assumptions that libdecor will always dispatch the main queue or not process zero-length queues (can occur if a wait is interrupted by the application queueing an event) should not be made, as this behavior is outside the control of SDL and can change.
SDL handles polling for Wayland events and then calls libdecor to do its internal processing and dispatch. If libdecor operates on the main queue, it will dispatch the queued events and the additional wl_display_dispatch_pending() call …
> wayland: Don't wait on event queues twice

- src/video/wayland/SDL_waylandevents.c
Just some cosmetic cleanup on the source file. Aside from replacing `fprintf()` with `SDL_SetError()`, nothing functional is changed.
- Replaces instances of `fprintf(stderr, ...)` with `SDL_SetError()`
- Replaces C++ comments with C style
- Uses a uniform format for multi-line comments
- Removes unused headers as poll and select aren't used in this file (the equivalent SDL function is used instead)
> wayland: Cleanup event source comments, headers, and error reporting

- src/video/cocoa/SDL_cocoashape.m
- src/video/cocoa/SDL_cocoawindow.m
- src/video/directfb/SDL_DirectFB_shape.c
- src/video/os2/SDL_os2video.c
- src/video/windows/SDL_windowsshape.c
- src/video/windows/SDL_windowswindow.c
- src/video/x11/SDL_x11shape.c
- src/video/x11/SDL_x11window.c
Fixes #2128.
Just letting this sit in a pull request so I can make sure I didn't break the build before pushing.
> shape: Free platform-specific shaped window data.

- src/render/ps2/SDL_render_ps2.c
This PR is improving the PS2 render driver.
Thanks to the latest improvements being done in `gsKit` (the PS2 library that we use in SDL in the renderer layer) https://github.com/ps2dev/gsKit/pull/56 and https://github.com/ps2dev/gsKit/pull/57, we could saving now tons of operations, making to perform way faster than before.
The specific `testspriteminimal2` has changed from:
```
INFO: 469.61 frames per second
```
to
```
INFO: 547.89 frames per second
```
The `testdraw2` example has been also improved
from:
```
INFO: 39.57 frames per second
```
to
```
INFO: 51.42 frames per second
```
Additionally, I have also made some clean up in the driver.
Cheers
> [PS2] Improve Render Driver

- include/SDL_hints.h
- src/audio/qsa/SDL_qsa_audio.c
- src/core/linux/SDL_ibus.h
- src/loadso/windows/SDL_sysloadso.c
- src/main/ps2/SDL_ps2_main.c
- src/render/psp/SDL_render_psp.c
- src/video/kmsdrm/SDL_kmsdrmopengles.c
> Correct some spelling mistakes in comments

- src/atomic/SDL_atomic.c
- use _Interlocked(Compare)ExchangePointer in case of _M_IX86 as well
- improve assertions:
1. add assertions to SDL_AtomicAdd/SDL_AtomicSet and SDL_AtomicCAS
2. use sizeof(a->value) instead of sizeof(int)
> simplify MSC_ATOMICS

- src/video/ngage/SDL_ngageframebuffer.cpp
- src/video/ngage/SDL_ngagevideo.h
I have started to implement audio support for the Nokia N-Gage port. I also want to clean up and maintain the existing code e.g. remove redundand dependencies etc.
- ~~[ ] Add basic audio support~~
- ~~[ ] Add N-Gage example launcher application~~
- ~~[ ] Add N-Gage build workflow (optional)~~
Unfortunately, I can't estimate how quickly I'll be able to get on with this, but I would very much appreciate it if the changes already committed could be merged before the release of version `2.26.0`, regardless of the progress made so far.
This would also help me to maintain and improve the [N-Gage SDK.](https://github.com/ngagesdk/ngage-toolchain) project
> [Draft] Nokia N-Gage: General code maintenance

- src/video/SDL_video.c
- graphics-flags check in one place
- more readable
- less error prone (handling of SDL_WINDOW_-flags is no longer dependent on the order)
- less code
(part of commit 9. of PR 5315)
> video: check graphics flags the same way as the type flags

- src/video/SDL_bmp.c
- test/testutils.c
Unneed test before calling SDL_FreeSurface, as it's never done in sdl code
> Unneed test before calling SDL_FreeSurface

- src/thread/n3ds/SDL_syscond.c
- src/thread/n3ds/SDL_sysmutex.c
- src/thread/n3ds/SDL_syssem.c
- src/thread/ngage/SDL_sysmutex.cpp
- src/thread/ngage/SDL_syssem.cpp
- src/thread/pthread/SDL_syssem.c
set consistent error-message + fix possible NULL-pointer error in ngage/SDL_syssem.cpp (SDL_SemTryWait)
> use SDL_InvalidParamError in the thread 'classes'

- test/testautomation_mouse.c
add SDL_GetDefaultCursor and SDL_GetGlobalMouseState test cases
> Add mouse test cases

- include/SDL3/SDL_pixels.h
Fixes https://github.com/libsdl-org/SDL/issues/6658
> Removed unused SDL_ArrayOrder enumeration values

- src/filesystem/unix/SDL_sysfilesystem.c
> Fix broken solaris build. (missing brace).

- Xcode/SDL/SDL.xcodeproj/project.pbxproj
The xcode project needed to be updated after 1e2dfdb.
None.
> Fix xcode project after opengles renderer removal

- .github/workflows/android.yml
- .github/workflows/emscripten.yml
- .github/workflows/ios.yml
- .github/workflows/main.yml
- .github/workflows/msvc.yml
- .github/workflows/n3ds.yml
- .github/workflows/ps2.yaml
- .github/workflows/psp.yaml
- .github/workflows/riscos.yml
- .github/workflows/vita.yaml
- .github/workflows/vmactions.yml
This should help get build feedback more quickly when someone is iterating on a PR
> Cancel current CI actions when a PR is updated

- test/testautomation_rwops.c
- test/testime.c
>  fixed build rwops

- src/audio/aaudio/SDL_aaudio.c
- src/audio/android/SDL_androidaudio.c
- src/core/android/SDL_android.c
- src/core/android/SDL_android.h
remove VLA, dynamic alloc, check max length get using GetIntArrayRegion
following #6824
> Android: make Detect devices common between aaudio and android driver.

- android-project/app/src/main/java/org/libsdl/app/SDLAudioManager.java
- src/core/android/SDL_android.c
It seems to me, is_capture is inverted ? @v3rm0n 
`source == 1`  is same as  `capture ==1 ` 
A sink is an output
> Android JAVA DetectDevices: 'is_capture' is inverted

- include/SDL_config_xbox.h
- src/video/windows/SDL_windowsopengl.c
- src/video/windows/SDL_windowsopengl.h
- src/video/windows/SDL_windowsvideo.h
- src/video/windows/SDL_windowswindow.c
Same as #6370 but for SDL2! Running this to check against CI...
> [SDL2] gdk: Add support for building with OpenGL on Xbox

- WhatsNew.txt
- docs/README-migration.md
- include/SDL3/SDL_events.h
- include/SDL3/SDL_video.h
- src/core/haiku/SDL_BApp.h
- src/core/winrt/SDL_winrtapp_direct3d.cpp
- src/events/SDL_displayevents.c
- src/events/SDL_displayevents_c.h
- src/events/SDL_events.c
- src/events/SDL_windowevents.c
- src/events/SDL_windowevents_c.h
- src/render/SDL_render.c
- src/render/direct3d/SDL_render_d3d.c
- src/render/direct3d11/SDL_render_d3d11.c
- src/render/direct3d12/SDL_render_d3d12.c
- src/render/opengl/SDL_render_gl.c
- src/render/opengles2/SDL_render_gles2.c
- src/render/software/SDL_render_sw.c
- src/test/SDL_test_common.c
- src/video/cocoa/SDL_cocoametalview.m
- src/video/emscripten/SDL_emscriptenevents.c
- test/testdrawchessboard.c
- test/testgles.c
- test/testgles2.c
- test/testgles2_sdf.c
- test/testhittesting.c
- test/testnative.c
- test/testoverlay2.c
- test/testwm2.c
Fixes https://github.com/libsdl-org/SDL/issues/6772
> Made SDL_WINDOWEVENT_* and SDL_DISPLAYEVENT_* first class event types

- WhatsNew.txt
- docs/README-migration.md
- include/SDL3/SDL_audio.h
- include/SDL3/SDL_oldnames.h
- src/audio/SDL_wave.c
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
- test/loopwave.c
- test/loopwavequeue.c
- test/testaudiohotplug.c
- test/testmultiaudio.c
- test/testresample.c
remove / rename SDL_FreeWAV() to SDL_free()
(using rename_api.py) + manually remove dynapi entries.
see #6908
> Remove/Rename SDL_FreeWAV() to SDL_free()

- include/SDL3/SDL_begin_code.h
- include/SDL3/SDL_close_code.h
- include/SDL3/SDL_locale.h
- include/build_config/SDL_build_config_emscripten.h
- src/audio/aaudio/SDL_aaudio.h
- src/audio/n3ds/SDL_n3dsaudio.h
- src/audio/openslES/SDL_openslES.h
- src/audio/vita/SDL_vitaaudio.h
- src/video/kmsdrm/SDL_kmsdrmvideo.h
- src/video/ngage/SDL_ngagevideo.h
- src/video/ngage/SDL_ngagewindow.h
- src/video/offscreen/SDL_offscreenopengles.h
- src/video/offscreen/SDL_offscreenvideo.h
- src/video/offscreen/SDL_offscreenwindow.h
- src/video/raspberry/SDL_rpivideo.h
- src/video/vita/SDL_vitakeyboard.h
- src/video/vita/SDL_vitamouse_c.h
- src/video/vita/SDL_vitatouch.h
- src/video/vita/SDL_vitavideo.h
Remove underscore in guard header defines
> Remove underscore in guard header defines

- include/SDL3/SDL_stdinc.h
- src/stdlib/SDL_iconv.c
And change the name, not to have the same for pointer and data
> Remove underscore for _SDL_iconv_t

- src/joystick/SDL_joystick_c.h
- src/joystick/SDL_sysjoystick.h
remove internal underscore prefix
https://github.com/libsdl-org/SDL/issues/6856
> Remove reserved identified with underscore prefix

- cmake/test/main_gui.c
- docs/README-migration.md
- docs/README-visualc.md
- include/SDL3/SDL_video.h
- src/events/SDL_windowevents.c
- src/test/SDL_test_common.c
- src/video/SDL_shape.c
- src/video/SDL_sysvideo.h
- src/video/SDL_video.c
- src/video/android/SDL_androidwindow.c
- src/video/cocoa/SDL_cocoawindow.m
- src/video/windows/SDL_windowswindow.c
- src/video/winrt/SDL_winrtvideo.cpp
- src/video/x11/SDL_x11window.c
- test/testautomation_video.c
Remove SDL_WINDOW_SHOWN and keep SDL_WINDOW_HIDDEN
NB: I haven't updated the flags value, should I do it?
https://github.com/libsdl-org/SDL/issues/6882
> Remove window show flag

- include/SDL3/SDL_events.h
Fixes https://github.com/libsdl-org/SDL/issues/6971
> Include SDL_audio.h for SDL_AudioDeviceID definition

- src/video/SDL_egl.c
- src/video/SDL_egl_c.h
- src/video/SDL_sysvideo.h
- src/video/SDL_video.c
- src/video/cocoa/SDL_cocoaopengl.h
- src/video/cocoa/SDL_cocoaopengl.m
- src/video/emscripten/SDL_emscriptenopengles.c
- src/video/emscripten/SDL_emscriptenopengles.h
- src/video/haiku/SDL_bopengl.cc
- src/video/haiku/SDL_bopengl.h
- src/video/psp/SDL_pspgl.c
- src/video/psp/SDL_pspgl_c.h
- src/video/psp/SDL_pspvideo.h
- src/video/wayland/SDL_waylandopengles.c
- src/video/wayland/SDL_waylandopengles.h
- src/video/windows/SDL_windowsopengl.c
- src/video/windows/SDL_windowsopengl.h
- src/video/x11/SDL_x11opengl.c
- src/video/x11/SDL_x11opengl.h
update the backends
following https://github.com/libsdl-org/SDL/pull/6939
https://github.com/libsdl-org/SDL/issues/2158
not really tested ...
> Update GL_GetSwapInterval for backends

- WhatsNew.txt
- include/SDL3/SDL_render.h
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
- src/render/SDL_render.c
Add SDL_GetRenderVSync()
see 
https://github.com/libsdl-org/SDL/issues/6495
> Add SDL_GetRenderVSync (see #6495)

- test/testautomation_pixels.c
we can create all pixel format, including SDL_PIXELFORMAT_UNKNOWN (as before). 
Check for really unknown pixel format. (eg != SDL_PIXELFORMAT_UNKNOWN)
> Fix testautomation_pixels

- test/testautomation_mouse.c
FLT_MIN is positive and very small. we want -FLT_MAX here.
> Fix testautomation_mouse:

- CMakeLists.txt
After testing, HAS_LSX/LASX is not used, it needs to be modified to  HAVE_LSX/LASX.
@madebr
> Fix loongarch64 support

- build-scripts/SDL_migration.cocci
- build-scripts/rename_api.py
SDL_migration.cocci / rename_api.py: 
- handle migration of enum/structure
- fix previous one in SDL_migration.cocci.
> SDL_migration.cocci / rename_api.py: handle migration of enum/structure

- build-scripts/SDL_migration.cocci
> Add vulkan migration

- build-scripts/SDL_migration.cocci
> SDL_migration.cocci: add SIMD Alloc / Free

- build-scripts/SDL_migration.cocci
> SDL_migration: add RW read/write

- build-scripts/SDL_migration.cocci
> SDL_migration.cocci: more gamepad migration

- build-scripts/SDL_migration.cocci
> SDL_migration.cocci:  set events

- build-scripts/SDL_migration.cocci
> SDL_migration.cocci: simplify multiplicaction / division by 1

- sdl2-config.cmake.in
Use REALPATH to resolve symlinks fixing merged-usr platforms
> fix prefix path not resolving symlinks

- src/video/vita/SDL_vitagles_pvr.c
Update single brace on SDL_vitagles_pvr.c that was broken unintentionally during https://github.com/libsdl-org/SDL/commit/6a2200823c66e53bd3cda4a25f0206b834392652.
There was no issue reported yet (but this literally breaks compilation).
> Update single brace on SDL_vitagles_pvr.c

- docs/README-migration.md
- test/testresample.c
- update testresample to use SDL_DestroyAudioStream()
- Add code snippet to migrate from AudioCVT
> Audio stream comments and test

- include/SDL3/SDL_init.h
- src/SDL.c
This groups the init flags into a named enum, similar to other flags groupings in the library.
I hope I didn't miss any other locations where the function signatures need to be updated! I'm not an expert on the library's organization though.
Closes https://github.com/libsdl-org/SDL/issues/7133
> group init flag defines into an enum

- build-scripts/SDL_migration.cocci
- docs/README-migration.md
- include/SDL3/SDL_oldnames.h
- include/SDL3/SDL_video.h
- src/core/android/SDL_android.c
- src/core/android/SDL_android.h
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
- src/test/SDL_test_common.c
- src/video/SDL_sysvideo.h
- src/video/SDL_video.c
- src/video/android/SDL_androidvideo.c
- src/video/cocoa/SDL_cocoamodes.h
- src/video/cocoa/SDL_cocoamodes.m
- src/video/cocoa/SDL_cocoavideo.m
- src/video/emscripten/SDL_emscriptenvideo.c
- src/video/uikit/SDL_uikitmodes.h
- src/video/uikit/SDL_uikitmodes.m
- src/video/uikit/SDL_uikitvideo.m
- src/video/wayland/SDL_waylandvideo.c
- src/video/windows/SDL_windowsmodes.c
- src/video/windows/SDL_windowsmodes.h
- src/video/windows/SDL_windowsvideo.c
- src/video/x11/SDL_x11modes.c
- src/video/x11/SDL_x11modes.h
- src/video/x11/SDL_x11video.c
- test/testdisplayinfo.c
> Rename SDL_GetDisplayDPI to SDL_GetDisplayPhysicalDPI

- android-project/app/src/main/java/org/libsdl/app/SDLSurface.java
> Android: display_mode scale: cast to do a float division

- src/video/uikit/SDL_uikitmodes.m
UIScreenMode objects don't have the real pixel size of the display for some phones (e.g. the iPhone 8 Plus). Some extra code is needed to convert the reported pixel size to the real pixel size. SDL2 had that code but it was lost during the SDL3 changes to SDL_DisplayMode coordinates.
The iPhone I have isn't one of the phones which would run into this situation, and the iOS Simulator doesn't behave the same as those phones so I haven't been able to test with an affected device, just on ones that already worked fine.
Fixes #7166
> iOS: fix display modes to have accurate pixel sizes and screen scales.

- docs/README-migration.md
I believe you intend to say "video driver", not audio driver
> [docs] SDL_Video.h - audio driver

- src/video/wayland/SDL_waylandvideo.c
Portrait displays may have native, physical resolutions that are taller than wide. Reverse the mode dimensions when dealing with these displays as well as those rotated via software means.
> wayland: Transform mode values for native portrait displays

- build-scripts/SDL_migration.cocci
> SDL_migration.cocci: fix syntax

- build-scripts/SDL_migration.cocci
> SDL_migration.cocci: remove metavariable warning

- src/render/SDL_render.c
Clean up the textures first, as destroying the current render target will queue viewport and clip rectangle commands
> Fixed memory leak at shutdown (thanks @1bsyl!)

- src/render/SDL_render.c
SDL_DestroyRenderer: drop all commands first
and don't queue new command from SDL_DestroyTexture() (memory leak)
> SDL_DestroyRenderer: drop all commands first

- src/haptic/darwin/SDL_syshaptic.c
- src/video/SDL_video.c
> Return the SDL_SetError value

- src/video/SDL_video.c
Attempt to retrieve the display for fullscreen windows using the window position so that the correct display ID is returned if an exclusive fullscreen window is moved to another display.
`SDL_SetWindowFullscreenMode()` did rely on the old behavior when calling `SDL_CheckWindowDisplayChanged()` directly after changing the mode on a non-visible window, so it had to be reworked to send a move event with the new display bounds instead. Sending a move event here will lead to the display changed check being called after the coordinates are updated.
Fixes #7254
>  video: Try to get the display for fullscreen windows via the window position

- include/SDL3/SDL_stdinc.h
> More `\param` added for SDL function in stdinc.h

- include/SDL3/SDL_surface.h
> Fix build documentation

- include/SDL3/SDL_audio.h
- include/SDL3/SDL_gamepad.h
- include/SDL3/SDL_hidapi.h
- include/SDL3/SDL_joystick.h
- include/SDL3/SDL_main.h
- include/SDL3/SDL_misc.h
- include/SDL3/SDL_mouse.h
- include/SDL3/SDL_mutex.h
- include/SDL3/SDL_pixels.h
- include/SDL3/SDL_render.h
- include/SDL3/SDL_sensor.h
- include/SDL3/SDL_system.h
- include/SDL3/SDL_video.h
- include/SDL3/SDL_vulkan.h
Update \returns to the generic form
> Update `\returns` to the generic form

- include/SDL3/SDL_assert.h
- include/SDL3/SDL_atomic.h
- include/SDL3/SDL_error.h
- include/SDL3/SDL_rect.h
- include/SDL3/SDL_stdinc.h
- include/SDL3/SDL_surface.h
- include/SDL3/SDL_system.h
- include/SDL3/SDL_test_font.h
- include/SDL3/SDL_thread.h
- include/SDL3/SDL_video.h
Add \since docs where missing and resets some to 3.0.0
- remove a \returns
> Add \since docs where missing and resets some to 3.0.0

- src/core/android/SDL_android.c
- src/core/freebsd/SDL_evdev_kbd_freebsd.c
- src/core/linux/SDL_evdev.c
- src/core/linux/SDL_evdev_kbd.c
- src/core/linux/SDL_udev.c
- src/core/openbsd/SDL_wscons_mouse.c
Fixed most small problems reported by cppcheck for src/core PR #7307 (from @kevin2kevin2)
https://github.com/libsdl-org/SDL/pull/7307
> Fixed most small problems reported by cppcheck for src/core PR #7307

- src/core/haiku/SDL_BeApp.cc
- src/video/haiku/SDL_bmessagebox.cc
> Haiku modernizing a bit the C++ code with C++11 heuristics

- src/video/x11/SDL_x11clipboard.c
> Correct typo GetSlectionText -> GetSelectionText

- src/video/SDL_video.c
> Change local (void*) to SDL_FunctionPointer

- test/checkkeys.c
- test/checkkeysthreads.c
- test/gamepadmap.c
- test/loopwave.c
- test/loopwavequeue.c
- test/testaudiohotplug.c
- test/testcustomcursor.c
- test/testdraw.c
- test/testdrawchessboard.c
- test/testgamepad.c
- test/testgeometry.c
- test/testgles2_sdf.c
- test/testintersections.c
- test/testjoystick.c
- test/testmouse.c
- test/testmultiaudio.c
- test/testnative.c
- test/testoffscreen.c
- test/testoverlay.c
- test/testrendercopyex.c
- test/testrendertarget.c
- test/testscale.c
- test/testsem.c
- test/testshader.c
- test/testsprite.c
- test/testspriteminimal.c
- test/teststreaming.c
- test/testviewport.c
- test/testwm.c
- test/torturethread.c
> Fix warnings about static function and prototype

- src/video/cocoa/SDL_cocoakeyboard.m
> Fixed incorrect modifier keys handling on macOS

- include/SDL3/SDL_blendmode.h
- src/render/SDL_render.c
- src/render/psp/SDL_render_psp.c
- src/render/software/SDL_draw.h
- src/render/software/SDL_triangle.c
- src/video/SDL_blit_auto.c
- src/video/SDL_blit_auto.h
- src/video/SDL_blit_slow.c
- src/video/sdlgenblit.pl
see https://github.com/libsdl-org/SDL/issues/7473
> Simplify SDL_BLENDMODE_MUL

- include/SDL_blendmode.h
- src/render/SDL_render.c
- src/render/psp/SDL_render_psp.c
- src/render/software/SDL_draw.h
- src/render/software/SDL_triangle.c
- src/video/SDL_blit_auto.c
- src/video/SDL_blit_auto.h
- src/video/SDL_blit_slow.c
- src/video/directfb/SDL_DirectFB_render.c
- src/video/sdlgenblit.pl
manually back-port:  https://github.com/libsdl-org/SDL/pull/7475/
> [SDL2] backport SDL_BLENDMODE_MUL change

- src/audio/SDL_audiocvt.c
> Fixed bug #7467 - testautomation_audio currently fails

- docs/README-android.md
I added lots of little nuggets of information to guide a possible newcomer better into the world of SDL Android development. I also fixed errors in the readme; some text was not visible because it used less-than/greater-than signs that made Markdown remove the text.
https://github.com/libsdl-org/SDL/issues/7533
> Made the Android documentation more clear and understandable

- src/video/SDL_video.c
see https://github.com/libsdl-org/SDL/issues/7515
> Fixed bug #7515 - Window still grabbed after destroying

- src/video/SDL_pixels_c.h
- src/video/SDL_surface.c
- src/video/SDL_yuv.c
- src/video/SDL_yuv_c.h
- simplication and factorization around CalculateSize and Pitch, RGB/YUV
- update SDL_CalculateYUVSize pitch to size_t
> Simplication and factorization around CalculateSize and Pitch, RGB/YUV

- src/main/haiku/SDL_BApp.h
- src/main/haiku/SDL_BeApp.cc
- src/main/haiku/SDL_BeApp.h
- src/video/haiku/SDL_BApp.h
- src/video/haiku/SDL_BWin.h
- src/video/haiku/SDL_bframebuffer.cc
- src/video/haiku/SDL_bmessagebox.cc
- src/video/haiku/SDL_bmodes.cc
- src/video/haiku/SDL_bopengl.cc
- src/video/haiku/SDL_bwindow.cc
adapted from #7555 for SDL2
fix #5385 for SDL2
> Haiku: use a BLooper for events, only create a BApplication when it doesn't already exist

- test/testaudiocapture.c
> testaudiocapture: let main exit normally

- src/audio/SDL_audio.c
- src/audio/SDL_sysaudio.h
- src/audio/aaudio/SDL_aaudio.c
not much tested, but maybe that solves https://github.com/libsdl-org/SDL/issues/7573
> Android AAUDIO: handle multiple devices

- src/test/SDL_test_assert.c
- src/test/SDL_test_harness.c
SDL_test: add more color when success/fail/skip
> SDL_test: add more color when success/fail/skip

- test/testautomation.c
> Android: let main return normally for testautomation

- src/video/SDL_surface.c
In SDL_ConvertSurface(), Check return values of SDL_CreateSurface()
and SDL_ConvertSurface().
> SDL_ConvertSurface(): add null pointer check

- .github/workflows/haiku.yml
A cross compiler is much faster then an emulated one :)
@icculus
> ci: use Haiku cross toolchain

- WhatsNew.txt
- android-project/app/src/main/java/org/libsdl/app/SDLActivity.java
- docs/README-android.md
- include/SDL3/SDL_hints.h
- src/core/android/SDL_android.c
https://github.com/libsdl-org/SDL/issues/7567
> Android: make sure the activity gets really finished

- docs/README-wayland.md
Add a README file for Wayland that lists common issues and limitations.
Addresses issues such as those in #7699, which have come up more than once. Hopefully this will help head-off reports of non-bugs in the future.
> docs: Add README-wayland

- src/video/x11/SDL_x11modes.c
Expose the text scaling factor (aka the global scale factor on KDE) as the display content scale value so applications can scale themselves as necessary.
If D-Bus is unavailable or retrieving the setting fails, fall back to trying the legacy GDK_SCALE envvar before reverting to the default 1.0 value.
> x11: Expose the text/global scaling factor as the display content scale

- src/video/wayland/SDL_waylandevents.c
Ensure that incoming touch events originate from valid surfaces owned by SDL and have proper window data before forwarding them to the touch subsystem, or the window focus pointer that is sent with the event may not be a pointer to an SDL window.
Additionally, ensure that allocated touch events are always cleaned up on exit.
Should fix #7726
Needs to be backported to SDL2 as well, but this will need to be done manually as too much has changed to just cherry-pick this commit.
> wayland: Validate surfaces and window data before sending touch events

- VisualC-GDK/SDL/SDL.vcxproj
- VisualC-GDK/SDL/SDL.vcxproj.filters
- VisualC-GDK/tests/testgdk/src/testgdk.cpp
- include/SDL3/SDL_syswm.h
Fixes compilation for the GDK SDL3 project.
Note to GDKX fellas: The renderer files will need to be edited as well (NOT the ones that have `#error` in the public repo).
> gdk: Fix the project

- src/SDL_utils_c.h
- src/stdlib/SDL_string.c
- src/video/x11/SDL_x11events.c
Fixes https://github.com/libsdl-org/SDL/issues/7766
> Only convert the result of XLookupString() if it's not already UTF-8

- src/video/SDL_video.c
Hiding a window and then clearing the minimized, maximized, fullscreen, or grabbed flags wouldn't result in the new state being applied to the window when shown, as the pending flags would always be zero, resulting in the flag application function never being entered. Calling SDL_RestoreWindow() didn't result in the minimized or maximized state being cleared on the hidden window either.
Save the current window flags to the pending flags when hiding a window, and universally apply the pending flags when the window is shown again to ensure that all state that was set or cleared when the window was hidden is applied. Any pending flags that match the existing window flags will be automatically deduplicated by the corresponding functions.
> video: Apply cleared flag states when restoring hidden windows

- src/video/x11/SDL_x11window.c
factorize the x11 wait code, 
timeout or not, and various methods to break the timeout:
(compare: size, position, size and position origin, double attempts )
not much more difference, except:
- it always check if we're a popup window  (before only in X11_UpdateWindowPosition())
- it can now send a move event from X11_SetWindowSize(). (which would be discarded by SDL layer if nothing has changed).
- it always re-query the x11 window parent
> X11: common function to wait for the WM before sending SDL Window events

- test/testautomation_hints.c
testautomation_hints.c: free hint memory
> testautomation_hints.c: free hint memory

- src/video/x11/SDL_x11clipboard.c
> Use SDL_strdup instead of strdup

- src/core/linux/SDL_dbus.c
SDL_DBus_AppendDictWithKeyValue: allows several key/value for other PRs
> SDL_DBus_AppendDictWithKeyValue: allows several key/value for other PRs

- src/core/android/SDL_android.c
Android: also protect Hat/Joy/PadDown,Up so there are not sent without window
> Android: also protect Hat/Joy/PadDown,Up so there are not sent without window

- src/joystick/linux/SDL_sysjoystick.c
> After using SDL_qsort, mark sort_entries() as SDLCALL

- src/audio/coreaudio/SDL_coreaudio.m
- src/audio/n3ds/SDL_n3dsaudio.c
- src/filesystem/ps2/SDL_sysfilesystem.c
- src/video/cocoa/SDL_cocoaclipboard.m
- src/video/cocoa/SDL_cocoawindow.m
use of SDL functions in a few files
(need to make sure that compiles ...)
> use of SDL functions

- include/SDL3/SDL_hints.h
Remove hints that were removed in SDL2 and that are not used in source code anymore
> Remove hints that weren't used anymore !

- build-scripts/SDL_migration.cocci
- build-scripts/rename_headers.py
- build-scripts/rename_symbols.py
- cmake/GetGitRevisionDescription.cmake
- docs/README-android.md
- docs/README-ps2.md
- test/testautomation_rect.c
- test/testautomation_surface.c
- test/testautomation_video.c
- test/testfile.c
- test/testhotplug.c
- test/testime.c
- test/testplatform.c
Per title, misc. typos found a fixed. Some typos found have been sent downstream and merged (for example: https://github.com/libusb/hidapi/pull/597)
n/a
> Fix various typos (docs/build scripts/tests)

- src/video/windows/SDL_windowswindow.c
https://github.com/libsdl-org/SDL/pull/7933#issuecomment-1622126174
> center cursor to client area (excludes titlebar thickness)

- src/joystick/linux/SDL_sysjoystick.c
Detecting by name such as "Accelerometer and "Motion Sensor" may be too broad. Sensors on Dualshock and Switch gamepad are correctly detected by `SDL_EVDEV_GuessDeviceClass()`.  Use vendor and product ID for Wii extension controls.
Discussion in the original pull request: https://github.com/libsdl-org/SDL/pull/7697#discussion_r1231255288
> Improve sensor detection for Linux gamepad v2

- src/video/x11/SDL_x11events.c
- src/video/x11/SDL_x11sym.h
- src/video/x11/SDL_x11xfixes.c
- src/video/x11/SDL_x11xfixes.h
Cherry-pick of https://github.com/libsdl-org/SDL/pull/7951 for SDL3
> SDL3: X11: Use XFixes to detect clipboard updates

- src/audio/SDL_audiocvt.c
> Fix typo in SDL_audiocvt.c

- src/video/windows/SDL_windowswindow.c
This PR improves the previous Win32 transparency support by:
- Not restricting it to just OpenGL (but can still be requested via a hint)
- Not removing windows decorations (i.e. title bar, etc) as a side effect
This method was tested in a project of mine on Windows 11 with hybrid GPUs with the following configurations:
- AMD Integrated Radeon Graphics: `direct3d` backend
- NVIDIA RTX 3060 Laptop: `opengl` backend
Use `DwmEnableBlurBehindWindow` instead
Closes #8148
> Better Win32 transparent window support

- include/SDL3/SDL_audio.h
- src/audio/SDL_audio.c
- src/audio/SDL_audiocvt.c
- src/audio/alsa/SDL_alsa_audio.c
- src/audio/emscripten/SDL_emscriptenaudio.c
- src/audio/n3ds/SDL_n3dsaudio.c
- src/audio/netbsd/SDL_netbsdaudio.c
- src/audio/pipewire/SDL_pipewire.c
- src/audio/wasapi/SDL_wasapi.c
- test/testaudio.c
- test/testaudiostreamdynamicresample.c
- test/testautomation_audio.c
Both of these calculations are done in lots of places, so I thought it woud be nice to add macros for them.
> Added SDL_AUDIO_BYTESIZE and SDL_AUDIO_FRAMESIZE macros

- docs/README-windows.md
Provides information on transparent windows in Win32
> Added README about transparent windows in Win32

- src/joystick/SDL_joystick.c
This adds the vendor id + product id pairs to detect all fanatec steering wheels.
> detect fanatec steering wheels

- src/core/linux/SDL_dbus.c
- src/core/linux/SDL_dbus.h
- src/video/wayland/SDL_waylanddatamanager.h
- src/video/wayland/SDL_waylandevents.c
Port of portal DnD from #8257 to SDL3
See #8257
> linux: Add portal drag and drop

- test/testautomation_video.c
Backports of f30a182 and f8e8dff
> Fix automated video tests under X11/Wayland

- Xcode/SDL/SDL.xcodeproj/project.pbxproj
Modified the Xcode project according to added files by #8269.
> Fix macOS build error

- src/stdlib/SDL_string.c
- test/testautomation_stdlib.c
Fixes https://github.com/libsdl-org/SDL/issues/8423
> Added support for "%[]" sscanf syntax

- docs/README-migration.md
- include/SDL3/SDL_events.h
- include/SDL3/SDL_hints.h
- src/core/linux/SDL_fcitx.c
- src/core/linux/SDL_ibus.c
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
- src/events/SDL_dropevents.c
- src/events/SDL_events.c
- src/events/SDL_keyboard.c
- src/main/SDL_main_callbacks.c
- src/test/SDL_test_common.c
- src/video/wayland/SDL_waylandevents.c
- test/checkkeys.c
- test/checkkeysthreads.c
- test/testaudio.c
- test/testdropfile.c
- test/testime.c
- test/testwm.c
This is used to free any dynamically allocated memory in events.
> Added SDL_CleanupEvent()

- Xcode/SDL/SDL.xcodeproj/project.pbxproj
- src/main/generic/SDL_sysmain_callbacks.c
Add SDL_sysmain_callbacks.c to the Xcode project.
> Fix macOS build

- docs/README-main-functions.md
- docs/README-migration.md
- include/SDL3/SDL_events.h
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
- src/events/SDL_dropevents.c
- src/events/SDL_events.c
- src/events/SDL_keyboard.c
- src/main/SDL_main_callbacks.c
- src/test/SDL_test_common.c
- test/checkkeys.c
- test/checkkeysthreads.c
- test/testcontroller.c
- test/testdropfile.c
- test/testime.c
Resolves https://github.com/libsdl-org/SDL/issues/8476 and https://github.com/libsdl-org/SDL/pull/8481
> Automatically clean up memory associated with events

- VisualC/tests/testautomation/testautomation.vcxproj
- src/SDL.c
- test/Makefile.in
- test/testautomation_subsystems.c
- test/testautomation_suites.h
- test/watcom.mif
This is a remake of #8385 for SDL2 branch which fixes issue #8381 there (because the changes could not be cherry picked trivially).
> SDL 2: Handle subsystem dependencies recursively

- include/SDL3/SDL_render.h
- include/SDL3/SDL_video.h
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
- src/render/SDL_render.c
- src/render/SDL_sysrender.h
- src/render/direct3d11/SDL_render_d3d11.c
- src/render/direct3d12/SDL_render_d3d12.c
- src/render/opengl/SDL_render_gl.c
- src/render/opengles2/SDL_render_gles2.c
- test/testffmpeg.c
Fixes https://github.com/libsdl-org/SDL/issues/8529
> Replaced SDL_GetTextureDXGIResource() with texture properties

- src/video/SDL_shape.c
- src/video/SDL_shape_internals.h
- src/video/windows/SDL_windowsmouse.c
- src/video/x11/SDL_x11shape.c
Closes #6476
Now generating proper mask for a cursor.
Ref code: https://github.com/dotnet/wpf/blob/main/src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/IconHelper.cs#L199-L332
https://learn.microsoft.com/en-us/windows/win32/menurc/using-cursors#creating-a-cursor
> Cleanup WIN_CreateCursor() code a bit

- src/SDL_properties.c
The hash table can be recursively locked from the same thread, which can cause issues with RWLocks, as locking them recursively can result in undefined behavior or deadlocks. Use a mutex instead, as it can be safely recursively locked.
Fixes #8549
> properties: Use a mutex instead of an RWLock to guard the hash table

- src/video/windows/SDL_windowsmouse.c
Generate bimap mask from the alpha channel.
Ref code:
https://github.com/dotnet/wpf/blob/89d172db0b7a192de720c6cfba5e28a1e7d46123/src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/IconHelper.cs#L283-L347
Also https://github.com/wine-mirror/wine/blob/1d178982ae5a73b18f367026c8689b56789c39fd/dlls/user32/cursoricon.c#L1148-L1164
Closes #6476
> [Rev 2] Cleanup WIN_CreateCursor() code a bit

- src/events/SDL_keyboard.c
> Use SDL_iscntrl() call instead of manual code that is doing the same

- src/video/windows/SDL_windowsclipboard.c
> Extract BMP magic into separate define

- docs/README-migration.md
- include/SDL3/SDL_hints.h
- include/SDL3/SDL_render.h
- src/render/SDL_render.c
- src/render/SDL_sysrender.h
- src/render/metal/SDL_render_metal.m
- src/test/SDL_test_common.c
Make sure your app uses SDL_RenderFlush() before it talks to D3D/OpenGL/etc!
Fixes #8584.
> render: Batching is always enabled now!

- src/core/linux/SDL_evdev_capabilities.h
- src/core/linux/SDL_udev.c
- src/video/SDL_sysvideocapture.h
- src/video/SDL_video_capture.c
- src/video/SDL_video_capture_apple.m
- src/video/SDL_video_capture_v4l2.c
- src/video/android/SDL_android_video_capture.c
- test/testvideocapture.c
- test/testvideocaptureminimal.c
Allow to add/remove capture device at runtime on linux, using UDEV
> SDL_VideoCapture: allow add/remove device at runtime on linux

- src/video/windows/SDL_windowskeyboard.c
Old implementation with `MapVirtualKey(..., MAPVK_VK_TO_CHAR) & 0x7FFFF` simply returned `A`..`Z` for VK_A..VK_Z and
completely useless <U+0002 START OF TEXT> (`WCH_LGTR 0xF002` without high-order bit) in case of ligature.
Keymap before/after:
- [Gothic keyboard](https://www.diffchecker.com/75lM72Pr/)
- [Russian keyboard](https://www.diffchecker.com/Q7A59q38/)
See https://kbdlayout.info/features/ligatures for a list of affected keyboard layouts with ligatures.
More info on `MAPVK_VK_TO_CHAR` behavior: https://stackoverflow.com/a/72464584/1795050
> Win32: Fix keymap for keyboard layouts that can print UTF-16 surrogates and ligatures

- CMakeLists.txt
- include/SDL3/SDL_stdinc.h
- include/build_config/SDL_build_config.h.cmake
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
- src/stdlib/SDL_string.c
- test/testautomation_stdlib.c
Independent implementation of https://github.com/libsdl-org/SDL/pull/8655
> Added SDL_strnstr()

- include/SDL3/SDL_hints.h
- src/joystick/SDL_gamepad.c
- src/joystick/SDL_joystick.c
- src/joystick/SDL_joystick_c.h
Fixes https://github.com/libsdl-org/SDL/issues/8595
> Make built-in joystick device lists extendable by using hints

- src/joystick/windows/SDL_windows_gaming_input.c
It turns out that returned PID is zero in this case and it breaks SDL_IsXInputDevice/HIDAPI_IsDevicePresent checks
> joystick: fixup for Wireless Xbox 360 Controller VID/PID detection in WGI backend

- include/SDL3/SDL_surface.h
Update doc: SDL_SoftStretch() and SDL_SoftStretchLinear() #8667
> Update doc: SDL_SoftStretch() and SDL_SoftStretchLinear() #8667

- src/video/windows/SDL_windowsevents.c
- src/video/windows/SDL_windowskeyboard.c
Remove unused defines in SDL_windowsevents.c
> win32: minor fixup in WIN_UpdateKeymap()

- src/thread/ps2/SDL_syssem.c
Same as https://github.com/libsdl-org/SDL/pull/8740 but for main branch
> SDL3 PS2 use WaitSemaEx for waiting for semaphore with timeout

- android-project/app/src/main/java/org/libsdl/app/SDLActivity.java
> AndroidShowToast: make OneShotTask members private final

- src/video/windows/SDL_windowsevents.c
- src/video/windows/SDL_windowswindow.c
- src/video/windows/SDL_windowswindow.h
This is a huge performance improvement for high polling rate mice, like the Razer Viper 8K mouse.
Fixes https://github.com/libsdl-org/SDL/issues/8756
> Use GetRawInputBuffer() instead processing raw input one at a time

- src/video/wayland/SDL_waylandvulkan.c
> Fix Duplicated includes

- src/video/yuv2rgb/yuv_rgb.c
- src/video/yuv2rgb/yuv_rgb_sse_func.h
- src/video/yuv2rgb/yuv_rgb_std_func.h
(cherry picked from commit 46de6241d79c6f4531dbb729b2ed5992ec61b4a2)
(cherry picked from commit 0bd77a5b93494ca88bfd1a86fe106e7bb1d90133)
(cherry picked from commit f341c06552c8618c1178287880fcb8775decfbd3)
(cherry picked from commit 4d2f9f3a324884add7245e8cd13ee06af907c306)
(cherry picked from commit 06f8f9a891194d86ff93a5856f80510d39b75272)
(cherry picked from commit 0c4cb3d1539fefa66c05d131385e35fb2a205fa3)
(cherry picked from commit 0dad56354ceb4222be569e6969475adeec5a1ca1)
> [SDL2] yuv2rgb: warning fixes and comment out unused code

- src/video/wayland/SDL_waylandwindow.c
> wayland: Restore accidentally removed line of code

- cmake/test/inc_sdl_noslash.c
- cmake/test/inc_sdl_slash.c
- docs/README-migration.md
- include/SDL3/SDL_init.h
- src/SDL.c
- test/testautomation_platform.c
- test/testautomation_subsystems.c
Fixes https://github.com/libsdl-org/SDL/issues/8709
> Removed SDL_INIT_EVERYTHING

- src/video/SDL_stretch.c
Fixed overflow in SDL_SoftStretch() (see #8878)
> Fixed overflow in SDL_SoftStretch() (see #8878)

- .gitignore
- VisualC-GDK/SDL/SDL.vcxproj
- VisualC-GDK/clean.sh
- VisualC-GDK/shaders/D3D12_PixelShader_Colors.hlsl
- VisualC-GDK/shaders/D3D12_PixelShader_NV12_BT601.hlsl
- VisualC-GDK/shaders/D3D12_PixelShader_NV12_BT709.hlsl
- VisualC-GDK/shaders/D3D12_PixelShader_NV12_JPEG.hlsl
- VisualC-GDK/shaders/D3D12_PixelShader_NV21_BT601.hlsl
- VisualC-GDK/shaders/D3D12_PixelShader_NV21_BT709.hlsl
- VisualC-GDK/shaders/D3D12_PixelShader_NV21_JPEG.hlsl
- VisualC-GDK/shaders/D3D12_PixelShader_Textures.hlsl
- VisualC-GDK/shaders/D3D12_PixelShader_YUV_BT601.hlsl
- VisualC-GDK/shaders/D3D12_PixelShader_YUV_BT709.hlsl
- VisualC-GDK/shaders/D3D12_PixelShader_YUV_JPEG.hlsl
- VisualC-GDK/shaders/D3D12_VertexShader.hlsl
- VisualC-GDK/shaders/buildshaders.bat
- docs/README-gdk.md
- src/render/direct3d12/SDL_render_d3d12_xbox.cpp
- src/render/direct3d12/SDL_render_d3d12_xbox.h
- src/render/direct3d12/SDL_shaders_d3d12_xboxone.cpp
- src/render/direct3d12/SDL_shaders_d3d12_xboxseries.cpp
Not much to see here, this just applies the open Xbox GDK portions to SDL2!
CC @chalonverse @TheSpydog
> gdk: Backport SDL3 MR #8844

- include/SDL3/SDL_surface.h
- src/video/SDL_blit.c
- src/video/SDL_blit.h
- src/video/SDL_blit_slow.c
- src/video/SDL_pixels.c
- src/video/SDL_pixels_c.h
Specifically, SDL_COLOR_PRIMARIES_XYZ, SDL_COLOR_PRIMARIES_SMPTE431, and SDL_COLOR_PRIMARIES_SMPTE432
> Added support for other HDR color primaries

- src/audio/aaudio/SDL_aaudio.c
- src/audio/aaudio/SDL_aaudio.h
Fixes #4985.
I think. It needs testing on real hardware.
> aaudio: Backport headphone hotplugging support from SDL3.

- acinclude/libtool.m4
- acinclude/ltoptions.m4
- build-scripts/ltmain.sh
- configure
@slouken: if this goes in, cherry-pick to 2.30.x or keep it as is?
> autotools: a few libtool updates from mainstream

- src/render/ps2/SDL_render_ps2.c
This PR solve:
- Remove not needed shift bit for color coordinates.
- Fix viewport
- Fix clip
Now viewport example is working as expected
https://github.com/libsdl-org/SDL/assets/10010409/c39ccf30-7c8b-4d1e-bb9a-110644b287d3
> [SDL3] Some fixes around PS2 port

- src/render/ps2/SDL_render_ps2.c
This PR solve:
- Remove not needed shift bit for color coordinates.
- Fix viewport
- Fix clip
Now viewport example is working as expected
https://github.com/libsdl-org/SDL/assets/10010409/c39ccf30-7c8b-4d1e-bb9a-110644b287d3
> [SDL2] Some fixes around PS2 port

- src/render/direct3d11/SDL_render_d3d11.c
Fixes https://github.com/libsdl-org/SDL/issues/8986
> Don't release currentOffscreenRenderTargetView

- src/video/wayland/SDL_waylandvideo.c
Fix for Issue #8990 
https://github.com/libsdl-org/SDL/issues/8990#issue-2116681700
> Null check SDL_DBusContext pointer

- src/video/SDL_pixels.c
- src/video/x11/SDL_x11pen.c
- test/testpen.c
Noticed `pow` in a recent commit so I ran `check_stdlib_usage.py` script.
None
> Use functions from SDL instead of libc

- src/video/wayland/SDL_waylandvideo.c
They aren't used for anything, and cause problems if the video core tries to free them.
Will fix #9010 when backported.
> wayland: Don't store wl_output pointers in mode driver data

- src/render/vulkan/SDL_render_vulkan.c
Adds missing support for v-sync disabled.
Closes #9116.
> Vulkan Renderer - implement support for vsync disabled. 

- docs/README-cmake.md
https://github.com/libsdl-org/SDL/issues/9134
> docs: improve CMake documentation for Apple

- include/SDL3/SDL_render.h
- src/render/vulkan/SDL_render_vulkan.c
> Vulkan: added support for wrapping existing textures

- src/render/vulkan/SDL_render_vulkan.c
Fix validation error with VkSemaphore being reused before signaling.  Have one semaphore per-submit rather than using the same one.
> Vulkan Renderer - fix validation error with VkSemaphore reuse.

- include/SDL3/SDL_hints.h
Add vulkan to SDL_HINT_RENDER_DRIVER
Question: Should I sort drivers as their order in render_drivers[]?
> Add vulkan to SDL_HINT_RENDER_DRIVER

- test/testffmpeg.c
Propagate the DRM format modifier from the AVDRMObjectDescriptor to eglCreateImage() on Linux. Some hardware will decode video into a non-linear DRM surface, and propagating this value using the `EGL_EXT_image_dma_buf_import_modifiers` extension is required in order to display something useful.
Fixes https://github.com/libsdl-org/SDL/issues/9075
> testffmpeg: Use EGL_EXT_image_dma_buf_import_modifiers extension

- src/hidapi/windows/hid.c
This merges mainstream commit
https://github.com/libusb/hidapi/commit/4f2e91bae80cc48e567a80bd9ae3dc53dc5b73c6
(authored by Vladimir Gladkov) into ours. From the original commit log:
```
Win32 HID API doc says: For USB devices, the maximum string length is
126 wide characters (not including the terminating NULL character).
For certain USB devices, using a buffer larger or equal to 127 wchars
results in successful completion of HID API functions, but a broken
string is stored in the output buffer. This behaviour persists even if
HID API is bypassed and HID IOCTLs are passed to the HID driver directly
(IOCTL_HID_GET_MANUFACTURER_STRING, IOCTL_HID_GET_PRODUCT_STRING, etc).
So, the buffer MUST NOT exceed 126 wchars.
windows: refactor ULONGLONG hid_internal_get_info(...) -> …
```
> hidapi, windows: sync with mainstream: change MAX_STRING_WCHARS to 126.

- test/testgeometry.c
Update hardcoded value of pi to use SDL constant SDL_PI_F for improved consistency and readability.
> Update hardcoded value of pi

- src/video/windows/SDL_windowskeyboard.c
No change in functionality. Just a minor cleanup.
> WIN_UpdateKeymap: cleanup code a bit

- test/testautomation_video.c
This fixes 90 leaks when running the video tests.
Reproducer:
```
$ testautomation --filter video --trackmem
```
<details>
<summary>The leaks</summary>
```
INFO: Memory allocations:
Allocation 0: 744 bytes
0x7fb996ef682d: SDL_calloc_REAL+0x45
0x7fb996ea4512: GL_CreateRenderer+0x11b
0x7fb996e92923: SDL_CreateRendererWithProperties_REAL+0x260
0x7fb996e92dd0: SDL_CreateRenderer_REAL+0x9f
0x7fb996e57603: SDL_CreateRenderer+0x2e
0x43ad4b: createVideoSuiteTestWindow+0x126
0x43f19e: video_getSetWindowState+0x105
0x44b117: SDLTest_RunTest+0x132
0x44baf0: SDLTest_RunSuites+0x842
0x408e8a: main+0x4e7
0x7fb996c2fb8a: __libc_start_call_main+0x7a
0x7fb996c2fc4b: __libc_start_main+0x8b
0x4088b5: _start+0x25
Allocation 1: 680 bytes
0x7fb996ef682d: SDL_calloc_REAL+0x45
0x7fb996ea457a: …
```
> testautomation: fix renderer leak in video tests

- include/SDL3/SDL_filesystem.h
- include/SDL3/SDL_timer.h
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
- src/filesystem/SDL_filesystem.c
- src/filesystem/posix/SDL_sysfsops.c
- src/filesystem/windows/SDL_sysfsops.c
Related to https://github.com/libsdl-org/SDL/pull/9257
> SDL file times are 64-bit integers representing nanoseconds since the Unix epoch

- cmake/sdlcompilers.cmake
- src/core/freebsd/SDL_evdev_kbd_freebsd.c
- src/events/SDL_pen.c
- src/joystick/linux/SDL_sysjoystick.c
- src/video/vita/SDL_vitavideo.c
- test/testautomation_audio.c
- test/testautomation_pen.c
- test/testcolorspace.c
- test/testoverlay.c
- test/testsurround.c
> cmake: add -Wimplicit-fallthrough warning

- src/stdlib/SDL_memcpy.c
- src/stdlib/SDL_memmove.c
- src/stdlib/SDL_memset.c
> Fix warnings when building with -DSDL_LIBC=OFF on Linux

- src/events/SDL_events.c
Companion PR to #9307 for SDL3
The only real functional difference is that SDL2 considers the sensor subsystem to need periodic polling for reenumeration, but that was removed for SDL3 in 324c0b76a0111f0955063ac657617708208963ea. I left the existing SDL3 behavior intact (no enumeration poll for sensors), but I'm not sure if it should be removed from SDL2 as well (or added back in SDL3).
> Improve event processing latency when gamepad/sensor is open (SDL3)

- Xcode/SDL/SDL.xcodeproj/project.pbxproj
> Add SDL_storage files to Xcode project

- src/events/SDL_events.c
The current implementation of `SDL_WaitEventTimeout_Device()` is limited to cases where we don't have any joystick or sensors open (`SDL_events_need_polling() == SDL_FALSE`). This limitation is due to the fact that many joystick and sensor backends don't deliver events via the normal event loop that `WaitEventTimeout()` waits on and instead require calls to `SDL_PumpEvents()` to receive new input.
The major downside of the `SDL_PumpEvents()+SDL_PeepEvents()+SDL_Delay()` loop is that it increases event latency due to that `SDL_Delay(1)` we're doing every iteration. The user-facing effect is that you are happily using your high polling rate mouse seeing > 2000 Hz mouse updates, then you plug in a gamepad and your polling rate plummets well below 1000 Hz.
To resolve this, I've consolidated …
> Improve event processing latency when gamepad/sensor is open

- src/time/vita/SDL_systime.c
A little addition to https://github.com/libsdl-org/SDL/pull/9257 for psvita
> PSVita: fix SDL_GetSystemTimeLocalePreferences

- src/time/n3ds/SDL_systime.c
Implement `SDL_GetSystemTimeLocalePreferences` using the system's current language and region.
Since there is no "user preference" for date and time format, they are inferred based on the language and region. Playing around with my locales for the available languages, it seems only en_US uses mm/dd/yyyy and 12hr formats.
There does not seem to be a way to differentiate Canada from the USA, so I chose to make go for MMDDYYYY + 12hr when the language is set to English and the region is North America.
See #9257
> N3DS: Implement `SDL_GetSystemTimeLocalePreferences`

- VisualC-GDK/SDL/SDL.vcxproj
- VisualC-GDK/SDL/SDL.vcxproj.filters
- src/video/windows/SDL_windowskeyboard.c
- src/video/windows/SDL_windowskeyboard.h
- src/video/windows/SDL_windowsvideo.c
- src/video/windows/SDL_xboxkeyboard.cpp
This is a port of https://github.com/libsdl-org/SDL/pull/7461 to main, completely untested.
@chalonverse, @ts-13512, can you take a look?
> Added virtual keyboard support for Xbox (thanks @ts-13512!)

- src/dialog/windows/SDL_windowsdialog.c
The behavior of the folder selection dialog on Windows OS has been fixed.
- The folder selection dialog now returns the full path to the folder, not just the name of the selected folder.
- Added support for the default folder to open in the dialog.
> Fix SDL_ShowOpenFolderDialog behavior on Windows

- src/render/vulkan/SDL_render_vulkan.c
Vulkan Renderer - fix synchronization validation issues with testrendertarget and testcopyex.  When a texture is destroyed, VULKAN_IssueBatch is called to make sure the texture isn't referenced in any outstanding command work.  This path did not wait on the semaphore from vkAcquireNextImageKHR, which would create a hazard.
testrendertarget, testcopyex, testsprite, testautomation with full Vulkan synchronization validation on Vulkan SDK 1.2.275.0.
> Vulkan Renderer - fix synchronization validation issues

- include/SDL3/SDL_pen.h
- include/SDL3/SDL_touch.h
Missed in f8844d387c2a0e3ccc7f8ce26001fd745e35bfee and d1eb4adb1618bb2685974eb720b10bc63b049b9f.
> Add missing header includes for SDL_MouseID

- src/time/windows/SDL_systime.c
GetSystemTimePreciseAsFileTime is only available on Win8/Server 2012 or higher, so it must be dynamically loaded and only used if available.  Fixes compatability with Win7 and XP.
Fixes #9416
> time: Only call GetSystemTimePreciseAsFileTime if available

- include/SDL3/SDL.h
- include/SDL3/SDL_events.h
Sorts includes in `SDL.h` and adds forgotten `SDL_Event` type and fixes event name in `SDL_JoyAxisEvent`.
> Misc public API header fixes

- src/video/cocoa/SDL_cocoawindow.m
This fixes an macOS bug that is only known to occur in fullscreen windows on the built-in displays of newer MacBooks with camera notches. The bug can cause the default cursor to be visible when it should not be.
This is a workaround for a bug in macOS. It's easy to reproduce in a sample app and I'm planning to submit it to Apple. It only occurs on fullscreen windows on the built-in display of newer MacBooks with camera notches. It doesn't occur on external monitors and it doesn't occur on the built-in monitors of older MacBooks (ex: 2019).
When the mouse is moved near the top of a fullscreen window (within about 44 units) and then moved back down, the cursor rects, which were requested when `resetCursorRects` was called, aren't respected.
The workaround involves detecting that the cursor …
> Workaround a macOS cursor-related bug.

- src/video/windows/SDL_windowsevents.c
For whatever reason, `ExtractIconEx` returns icons whose sizes are inappropriate for the current DPI, resulting in terribly-blurry window icons at higher DPIs.
To solve this, the window icon is now set to the first icon group that is present in the executable. This behaviour should match what Explorer does. By selecting an icon group instead of a specific icon, Windows is free to select the icon within the group that best suits the current DPI.
Before:
After:
> Fix default Windows window icon not suiting the DPI.

- include/SDL3/SDL_camera.h
- include/SDL3/SDL_clipboard.h
- include/SDL3/SDL_dialog.h
- include/SDL3/SDL_filesystem.h
- include/SDL3/SDL_hidapi.h
- include/SDL3/SDL_hints.h
- include/SDL3/SDL_init.h
- include/SDL3/SDL_main.h
- include/SDL3/SDL_messagebox.h
- include/SDL3/SDL_misc.h
- include/SDL3/SDL_pixels.h
- include/SDL3/SDL_power.h
- include/SDL3/SDL_properties.h
- include/SDL3/SDL_render.h
- include/SDL3/SDL_storage.h
- include/SDL3/SDL_surface.h
- include/SDL3/SDL_system.h
- include/SDL3/SDL_version.h
- include/SDL3/SDL_video.h
- include/SDL3/SDL_vulkan.h
> Including SDL_error.h into headers with error-returning functions

- docs/README-migration.md
- docs/README-visualc.md
- include/SDL3/SDL_render.h
- src/render/SDL_render.c
- src/render/SDL_sysrender.h
- src/render/direct3d/SDL_render_d3d.c
- src/render/direct3d11/SDL_render_d3d11.c
- src/render/direct3d12/SDL_render_d3d12.c
- src/render/metal/SDL_render_metal.m
- src/render/opengl/SDL_render_gl.c
- src/render/opengles2/SDL_render_gles2.c
- src/render/ps2/SDL_render_ps2.c
- src/render/psp/SDL_render_psp.c
- src/render/software/SDL_render_sw.c
- src/render/vitagxm/SDL_render_vita_gxm.c
- src/render/vulkan/SDL_render_vulkan.c
- src/test/SDL_test_common.c
- src/video/SDL_video.c
- test/testautomation_render.c
These flags are unnecessary and have always been a source of confusion.
> Removed SDL_RENDERER_ACCELERATED and SDL_RENDERER_SOFTWARE

- include/SDL3/SDL_pixels.h
> Removing macro SDL_FColour from SDL_pixels.h

- INSTALL.md
Added a subsection for building MacOS universal packages.
This new subsection simply shows an alternate MacOS build command for a universal SDL package.
> Updated INSTALL.md

- build-scripts/SDL_migration.cocci
- docs/README-migration.md
- include/SDL3/SDL_oldnames.h
> SDL_RendererFlip rename fixes

- src/audio/SDL_audioresample.c
GCC 4.9.4 doesn't seem to like reading a `__m128`, gotta use `_mm_load_ps`.
Fixes #9596
> Workaround GCC bug in audio resampler

- src/video/x11/SDL_x11mouse.c
Trying to capture the pointer via XGrabPointer() when XInput2 is in use will always fail with 'AlreadyGrabbed', since the pointer is already grabbed by XInput2.
Fixes #9593
> x11: Don't try to capture mouse input via X when XInput2 is in use

- docs/README-migration.md
- include/SDL3/SDL_render.h
- src/dynapi/SDL_dynapi_procs.h
- src/render/SDL_render.c
- test/testaudiocapture.c
- test/testdialog.c
- test/testspriteminimal.c
Fixes https://github.com/libsdl-org/SDL/issues/9626
> SDL_CreateWindowAndRenderer() takes the window title as the first parameter

- .github/workflows/main.yml
The `stdlib_swprintf` test also fails on SDL3
https://github.com/libsdl-org/SDL/issues/9606
> ci: build SDL on macos 14 (arm64)

- include/SDL3/SDL_joystick.h
- include/SDL3/SDL_stdinc.h
- include/SDL3/SDL_touch.h
Adding tag names to following enums:
```
SDL_JoystickType
SDL_JoystickConnectionState
SDL_TouchDeviceType
SDL_DUMMY_ENUM
```
> Adding tag names to enums

- src/dialog/windows/SDL_windowsdialog.c
This fixes a bunch of issues with dialogs on Windows.
- Removed lpstrFileTitle assignation, which overwrote the buffer
- Increased the memory size available for long file selections¹
- Removed seemingly unused `default_folder` in win_Args struct
- Properly handle the case where only one file is selected in multiselect mode
- Properly handle the initial folder, which would fail in specific conditions²
¹: I have to create a fixed-size buffer that must contain the path and filenames of all the selected files; an overflow would cause an error on Windows and, apparently, an unmanaged overflow on Wine. I put a default buffer size of 65535 characters, which is generous enough to contain 1000 files called `LoremIpsumDolorSitAmetConsecteturAdisciplingElit{1..1000}.txt`. If somebody selects too …
> Fix dialogs on Windows

- src/dialog/cocoa/SDL_cocoadialog.m
The Cocoa implementation of dialogs did not properly handle the case where `filters` would be null.
Fixes #9665
> Fix improper handling of NULL dialog filter on Cocoa

- src/core/linux/SDL_evdev.c
- src/events/SDL_keyboard.c
- src/events/SDL_keyboard_c.h
- src/events/SDL_mouse.c
- src/events/SDL_mouse_c.h
- src/video/uikit/SDL_uikitevents.m
- src/video/wayland/SDL_waylandevents.c
- src/video/windows/SDL_windowsevents.c
- src/video/x11/SDL_x11xinput2.c
Fixes https://github.com/libsdl-org/SDL/issues/9487
> Fixed memory leak cleaning up mouse and keyboard instances

- src/video/cocoa/SDL_cocoawindow.m
Cocoa will resize the window from the bottom-left instead of the top-left, so the position must be preserved when setting the new size. This was already done in most places, except when doing an immediate, programmatic resize.
Fixes #9730
> cocoa: Fix the window position when resizing

- include/SDL3/SDL_render.h
- src/render/SDL_render.c
- src/render/SDL_sysrender.h
- src/render/direct3d/SDL_render_d3d.c
- src/render/direct3d11/SDL_render_d3d11.c
- src/render/direct3d12/SDL_render_d3d12.c
- src/render/metal/SDL_render_metal.m
- src/render/opengl/SDL_render_gl.c
- src/render/opengles2/SDL_render_gles2.c
- src/render/ps2/SDL_render_ps2.c
- src/render/psp/SDL_render_psp.c
- src/render/software/SDL_render_sw.c
- src/render/vitagxm/SDL_render_vita_gxm.c
- src/render/vulkan/SDL_render_vulkan.c
Fixes https://github.com/libsdl-org/SDL/issues/9056
> Removed the limit on the number of supported renderer texture formats

- src/camera/pipewire/SDL_camera_pipewire.c
> PipeWire: removing log message

- docs/README-cmake.md
- docs/README-migration.md
Fixes https://github.com/libsdl-org/SDL/issues/9697
> doc: document how to use generator expressions + explain why we no longer provide CMake variables

- src/SDL_hints.c
Check if the argument is a NULL pointer.
> Added NULL pointer check in SDL_GetHint.

- src/hidapi/SDL_hidapi.c
This pull request intends to downport the changes made [here](https://github.com/libsdl-org/SDL/pull/6014) to SDL2.
Arch builds the SDL2 package with the SDL_HIDAPI_LIBUSB flag ON to support devices such as [gamecube controllers](https://bugs.archlinux.org/task/75827). As a result of this, any other packages/plugins/etc using SDL2 will always grab controller devices with exclusivity, which is undesirable. Including this change in SDL2 will should fix issues users have with that configuration decision while retaining the ability to use those devices.
I have tested this on my local system to confirm that my use case (the input-overlay plugin for OBS) will no longer pull exclusive control for my PS4 controller, and that this behavior can be configured by applications using SDL2 with the …
> SDL2: Add support for libusb device whitelisting

- src/video/windows/SDL_windowswindow.c
If a window is fullscreen and the maximized state is requested, it needs to be explicitly entered only after leaving fullscreen, or the resulting window will be in the maximized state, but still the size of the non-maximized window.
This worked on Win10, but was broken on Win11.
> win32: Fix maximized windows when leaving fullscreen

- src/video/x11/SDL_x11clipboard.c
- src/video/x11/SDL_x11events.c
- src/video/x11/SDL_x11video.h
This adds support for pasting large clipboard contents using the INCR property mechanism
Fixes #8871
> Support X11 incremental clipboard transfers.

- src/camera/mediafoundation/SDL_camera_mediafoundation.c
Fixes the FIXME left in there.
> SDL_camera_mediafoundation.c: hardcode MF_DEVSOURCE_ATTRIBUTE_* GUIDs

- src/video/windows/SDL_windowsmodes.c
- src/video/windows/SDL_windowsvideo.c
- src/video/windows/SDL_windowsvideo.h
backport from PR/9923 (commit e4518af3770aad16eab206531e181a54225fd0fb)
> move vista+ display config function ptr calls to device->driverdata

- src/video/windows/SDL_windowsevents.c
This PR fixes #5685
When hitting the RAlt key (AltGR more precisely) on windows on a non US keyboard, windows sends two key pressed events:
- one LCtrl
- followed by one RAlt
- (same order for releasing)
Note that this behavior doesn't seem to happen under a Windows Virtual Machine (with Linux host) but on native windows.
The solution is taken from the GLFW library:
- check if the LCtrl is pressed, and is an extended key
- if so, get the next windows message (without removing it) from the pump message
- check if the next message is RAlt
- Ignore the current message if every conditions is ok
A second patch is done in case of keyboard "grabbing" (with WH_KEYBOARD_LL)
In this case, the AltGr triggers a LCtr which is a bit different as the 'classic' LCtrl, but can easily be identified as we …
> Fix spurious LCtrl on RAlt key pressed

- src/joystick/bsd/SDL_bsdjoystick.c
(cherry picked from commit 4d63c919f9b0c2bb68e714b72ec7eb3445a113d1)
> simplify OpenBSD D-pad calculation with bitwise operation (#7996)

- include/SDL3/SDL_camera.h
- src/camera/SDL_camera.c
- src/camera/SDL_syscamera.h
- src/camera/android/SDL_camera_android.c
- src/camera/coremedia/SDL_camera_coremedia.m
- src/camera/emscripten/SDL_camera_emscripten.c
- src/camera/mediafoundation/SDL_camera_mediafoundation.c
- src/camera/pipewire/SDL_camera_pipewire.c
- src/camera/v4l2/SDL_camera_v4l2.c
- test/testcamera.c
This is more intuitive for game developers and users.
Fixes https://github.com/libsdl-org/SDL/issues/9896
> Switched the camera format to use framerate ratio instead of interval ratio

- src/stdlib/SDL_qsort.c
Update used qsort implementation to https://www.mccaughan.org.uk/software/qsort.c-1.16
This version fixes stack buffer overflow problem.
Fixes #10055
> Update qsort implementation

- docs/README-documentation-rules.md
- include/SDL3/SDL_render.h
I chose to do an extra PR, since i'm not really sure about this one.
There is a US/UK discrepancy in spelling, but "judgment" seems to be the "official/court" spelling.
Feel free to reject
This is also comments-only
>  JANITORIAL: Fix judgement typos

- include/SDL3/SDL_hints.h
- src/events/SDL_mouse.c
- src/events/SDL_mouse_c.h
- src/video/windows/SDL_windowsevents.c
Another proof of concept. 
Closes #8006
> Add SDL_HINT_MOUSE_RELATIVE_CLIP_INTERVAL

- src/camera/SDL_camera.c
Fixes https://github.com/libsdl-org/SDL/issues/10051
> Camera: Bugfix: `ChooseBestCameraSpec` doesn't set camera colorspace

- src/thread/stdcpp/SDL_systhread.cpp
Removed the workaround used to mimic a thread id on non winrt platforms.
The code was updated by first adding an assertion on the size of `std::thread::id` being not greater than the size of `SDL_ThreadID`, since the standard only says that it should be an object trivially copyable suited to be used as index in a container, but realistically it would always match to the platform's pointer type size, the only exception being windows where it will always be a 32 bit value, which is good for our needs.
After that it's just a matter of memcpying the value returned by `std::this_thread::get_id()` to `SDL_ThreadID` and returning that.
The winrt path got removed as the value returned by std::thread is the same as the win32 function.
The redoundant move construction in `SDL_SYS_CreateThread` got …
> stdcpp threads: simplify SDL_GetCurrentThreadID implementation

- include/SDL3/SDL_stdinc.h
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
- src/filesystem/SDL_filesystem.c
- src/stdlib/SDL_string.c
- src/stdlib/SDL_sysstdlib.h
- test/testiconv.c
> stdinc: Drastically improve SDL_StepUTF8() and make it a public API.

- src/video/windows/SDL_windowskeyboard.c
- src/video/windows/SDL_windowsvideo.h
Fixes https://github.com/libsdl-org/SDL/issues/6254
> We should still set the text input area if SDL_DISABLE_WINDOWS_IME is defined

- docs/README-migration.md
- include/SDL3/SDL_hints.h
- src/core/linux/SDL_fcitx.c
- src/core/linux/SDL_ibus.c
- src/video/windows/SDL_windowskeyboard.c
- src/video/windows/SDL_windowsvideo.h
- test/testime.c
This inverts the logic to make more sense from an application perspective.
> Renamed SDL_HINT_IME_NATIVE_UI to SDL_HINT_IME_IMPLEMENTED_UI

- src/video/SDL_video.c
- test/testautomation_video.c
Also added an automated test to verify window surface functionality.
Fixes https://github.com/libsdl-org/SDL/issues/10133
> Clean up any renderer in SDL_DestroyWindowSurface()

- src/events/SDL_keyboard.c
- src/video/wayland/SDL_waylandevents.c
- src/video/wayland/SDL_waylandwindow.c
Fixes https://github.com/libsdl-org/SDL/issues/5616
> Losing keyboard focus doesn't automatically mean you lose mouse capture

- src/joystick/hidapi/SDL_hidapi_steamdeck.c
Add a loop around SDL_hid_read() in the Steam Deck HIDAPI driver as it is done in other HIDAPI drivers. This loop reads data from the device and processes it until the input buffer is empty which ensures that clients always get the latest data.
This fixes an input latency issue if the application polls the events slower than the hardware generates them.
Fixes #10149
> SDL3: Drain HIDAPI buffer in SDL_hidapi_steamdeck.c.

- mingw/pkg-support/INSTALL.txt
- mingw/pkg-support/Makefile
> mingw: use DESTDIR to change the install location of the mingw package 

- .github/workflows/cpactions.yml
- src/dynapi/SDL_dynapi.sym
- src/hidapi/netbsd/hid.c
- test/testautomation_pixels.c
Kudos to @jacob-carlborg for the feedback in https://github.com/cross-platform-actions/action/discussions/90
Fixes #10224
> ci: bump the BSDS 

- src/audio/pipewire/SDL_pipewire.c
The preferred Pipewire path requires both devices being available, and that a sufficiently recent underlying core version is running on the host system. These criteria were being checked separately, which required two separate instances of enumerating the Pipewire registry, which is a fairly heavy operation. Move the version info callback to the main hotplug thread to avoid enumerating the registry twice, and check for both the version and required devices at the same time on the preferred path.
This pull doesn't change any behavior, just consolidates everything into one pass over the registry, which is both cleaner and more efficient.
> pipewire: Consolidate registry enumeration instances

- src/SDL.c
- src/thread/SDL_systhread.h
- src/thread/SDL_thread.c
- src/thread/SDL_thread_c.h
- src/thread/generic/SDL_systls.c
- src/thread/pthread/SDL_systls.c
- src/thread/stdcpp/SDL_systhread.cpp
- src/thread/windows/SDL_systls.c
Fixes https://github.com/libsdl-org/SDL/issues/8576
> Added TLS initialization and shutdown functions

- src/SDL.c
- src/SDL_internal.h
- src/thread/SDL_thread.c
Fixes https://github.com/libsdl-org/SDL/issues/8576
> Make sure SDL subsystems are initialized before starting threads

- include/SDL3/SDL_properties.h
Fixes https://github.com/libsdl-org/SDL/issues/10241
> Clarify property group documentation

- src/video/windows/SDL_windowsmodes.c
- src/video/windows/SDL_windowsvideo.c
- src/video/windows/SDL_windowsvideo.h
Fixes https://github.com/libsdl-org/SDL/issues/10185
> Use DXGI to get precise display mode refresh rate values

- include/SDL3/SDL_surface.h
- src/dynapi/SDL_dynapi_procs.h
- src/video/SDL_blit.c
- src/video/SDL_blit.h
- src/video/SDL_blit_slow.c
- src/video/SDL_pixels.c
- src/video/SDL_pixels_c.h
- src/video/SDL_surface.c
- test/testautomation_surface.c
Fixes https://github.com/libsdl-org/SDL/issues/8079
> Added full feature blit support for 8-bit surfaces

- docs/README-migration.md
- src/render/SDL_render.c
- src/video/SDL_surface.c
- test/testautomation_render.c
Fixes https://github.com/libsdl-org/SDL/issues/9941
> Textures with alpha format default to SDL_BLENDMODE_BLEND

- include/SDL3/SDL_video.h
Led to the actual list of WindowsFlag in the documentation of the SDL_CreateWindow method
> Updated the documentation of the SDL_CreateWindow method in SDL_video.h

- android-project/app/proguard-rules.pro
(& remove unnecessary native keywords)
> Update proguard-rules.pro to include onNativeInsetsChanged

- src/video/cocoa/SDL_cocoakeyboard.m
This makes the macOS behavior match other platforms where the IME eats keys that are used for composing text.
> Don't send keys consumed by the IME on macOS

- src/SDL.c
- src/SDL_log.c
- src/render/SDL_render.c
- src/render/direct3d/SDL_render_d3d.c
- src/render/direct3d11/SDL_render_d3d11.c
- src/render/direct3d12/SDL_render_d3d12.c
- src/render/opengl/SDL_render_gl.c
- src/render/opengles2/SDL_render_gles2.c
- src/render/ps2/SDL_render_ps2.c
- src/render/software/SDL_render_sw.c
- src/render/vitagxm/SDL_render_vita_gxm.c
- src/render/vulkan/SDL_render_vulkan.c
- src/test/SDL_test_common.c
Fixes memory leaks reported in https://github.com/libsdl-org/SDL/pull/10390#issuecomment-2254214159
> Memory cleanup

- examples/template.html
In reference to #10350, the style of the page as I made it.
I've checked the "Allow edits and access to secrets by maintainers" option, so that further changes can be done on my branch directly.
> Add style to `examples/template.html`

- examples/CMakeLists.txt
- examples/game/01-snake/main.c
- examples/game/01-snake/snake.c
- examples/game/01-snake/snake.h
Hey! I saw https://github.com/libsdl-org/SDL/issues/10350 and decided to contribute this little game as one of the examples. I adapted it from https://github.com/DyXel/snake, which was using SDL2.
I always used this project to make sure my SDL installation was working fine, so putting it as an example seems like the perfect fit IMO.
> Add "Snake" game example

- include/SDL3/SDL_test_common.h
- src/test/SDL_test_common.c
- src/video/x11/SDL_x11events.c
- src/video/x11/SDL_x11window.c
- test/testnative.c
Fixes https://github.com/libsdl-org/SDL/issues/3825
Fixes https://github.com/libsdl-org/SDL/issues/5142
Fixes https://github.com/libsdl-org/SDL/issues/9503
> Enable events for external X11 windows

- src/video/windows/SDL_windowskeyboard.c
Fixes https://github.com/libsdl-org/SDL/issues/7853
> Handle Colemak swapping of CapsLock and Backspace

- src/video/windows/SDL_windowsvideo.c
- src/video/windows/SDL_windowsvideo.h
- src/video/windows/SDL_windowswindow.c
Xbox doesn't have drag-and-drop?! No _wonder_ Nintendo and Sony are more popular 🙄🙄🙄
> Xbox buildfixes

- src/stdlib/SDL_string.c
- test/testautomation_stdlib.c
Fixes https://github.com/libsdl-org/SDL/issues/10310
> Implemented left-justification in SDL_PrintString()

- src/video/wayland/SDL_waylandmouse.c
Add a cursor caching system and viewport support, to allow for high-DPI, fractionally-scaled, custom cursors.
Wayland support for #10443
> wayland: Add support for high-DPI custom cursors

- include/SDL3/SDL_stdinc.h
- src/stdlib/SDL_iconv.c
- test/testautomation_stdlib.c
- Document the iconv functions (please review @icculus )
- Add iconv testautomation
- Avoid crash on system (macos) iconv by checking the input.
> Document iconv functions + add testautomation

- src/video/kmsdrm/SDL_kmsdrmvideo.c
Fixes https://github.com/libsdl-org/SDL/issues/10499
> kmsdrm: free the connector when looking for available devices

- include/SDL3/SDL_audio.h
- src/audio/SDL_audio.c
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
- test/testautomation_audio.c
Fixes https://github.com/libsdl-org/SDL/issues/10489
> Added SDL_GetAudioFormatName()

- android-project/app/proguard-rules.pro
Also sort methods and add a note about preserving unused native method nativeGetHint.
> Update proguard-rules.pro in line with recent changes

- src/events/SDL_keymap.c
You forgot to remove it in c298a37
None
> Remove stray return statement

- src/camera/SDL_camera.c
- test/testcamera.c
Fixes https://github.com/libsdl-org/SDL/pull/10525#discussion_r1718239103
> Fix testcamera

- include/SDL3/SDL_mouse.h
- include/SDL3/SDL_video.h
- src/video/SDL_surface.c
This implements the ideas described in  #10536
> Prefer downscaling in SDL_GetSurfaceImage

- examples/audio/01-simple-playback/simple-playback.c
- examples/audio/02-simple-playback-callback/simple-playback-callback.c
- examples/audio/03-load-wav/load-wav.c
- examples/game/01-snake/main.c
- examples/pen/01-drawing-lines/drawing-lines.c
- examples/renderer/01-clear/renderer-clear.c
- examples/renderer/02-primitives/renderer-primitives.c
- examples/template.c
- include/SDL3/SDL_init.h
- include/SDL3/SDL_main.h
- include/SDL3/SDL_test_common.h
- src/main/SDL_main_callbacks.c
- src/main/SDL_main_callbacks.h
- src/main/emscripten/SDL_sysmain_callbacks.c
- src/main/generic/SDL_sysmain_callbacks.c
- src/main/ios/SDL_sysmain_callbacks.m
- src/test/SDL_test_common.c
- test/loopwave.c
- test/testaudio.c
- test/testaudiorecording.c
- test/testcamera.c
- test/testdropfile.c
- test/testpen.c
- test/testsprite.c
Fixes https://github.com/libsdl-org/SDL/issues/10515
> Changed main callback return values to an enumeration

- src/joystick/controller_list.h
- src/joystick/hidapi/SDL_hidapi_ps3.c
- src/joystick/usb_ids.h
Fixes https://github.com/libsdl-org/SDL/issues/10557
> Added support for the Retro-bit Controller in PS3 mode

- CMakeLists.txt
> cmake: build uclibc as a static library

- src/video/SDL_blit_A.c
I've improved avx2 and sse4 SIMD blit blending code. It is now **~1.5x faster**.
New code calculates exactly same byte values as before.
To measure performance I called SDL_BlitSurface for 256x256 ABGR surface 1000x in a loop.
Here are timings for old -> new code on AMD and Intel CPU's on Windows using MSVC v19.41.
AVX2 blit:
```
Ryzen 5950x: 21.6 msec -> 14.2 msec = 1.52x faster
i7-7940X:    24.6 msec -> 17.5 msec = 1.41x faster
```
SSE4 blit:
```
Ryzen 5950x: 44.1 msec -> 27.8 msec = 1.59x faster
i7-7940X:    46.5 msec -> 29.9 msec = 1.55x faster
```
I have run `testautomation.exe --filter Blending` on both codepaths to check that hashes of blit results matches expected values.
> Faster sse4 and avx2 SIMD blitters

- src/video/offscreen/SDL_offscreenvulkan.c
> offscreen: Fix bogus surface pointer assignment

- src/video/SDL_blit_A.c
I've added neon SIMD code for alpha blending blitter. It runs **~3.5x to 6x faster** than scalar code.
Neon code is enabled only for 64-bit arm. Supporting 32-bit arm would require a extra code (because of `vqtbl1q_u8`). 
For 64-bit arm neon is always present, so new code is enabled unconditionally.
Neon calculates exactly same byte values as scalar code.
To measure performance I called SDL_BlitSurface for 256x256 ABGR & ARGB surfaces 1000x in a loop.
Here are timings for old scalar -> new neon code improvement.
Raspberry Pi 5, gcc 14.1.1
```
ABGR->ABGR: 244.7 msec -> 63.1 msec = 3.88x faster
ABGR->ARGB: 376.4 msec -> 63.1 msec = 5.97x faster
```
Apple M1, clang 15.0.0
```
ABGR->ABGR: 76.2 msec -> 20.8 msec = 3.66x faster
ABGR->ARGB: 94.2 msec -> 20.8 msec = 4.53x faster
```
I have run …
> Add neon SIMD alpha blending blitter

- CMakeLists.txt
> Added configuration dependencies for SDL_RENDER_GPU

- src/render/SDL_render.c
- src/render/SDL_yuv_sw.c
- src/render/SDL_yuv_sw_c.h
Fixes https://github.com/libsdl-org/SDL/issues/10624
> Fixed the colorspace for YUV textures using native RGB representations

- src/audio/SDL_audioresample.c
- src/render/sdlgpu/SDL_render_gpu.c
Fixes https://github.com/libsdl-org/sdl2-compat/issues/95
> Adjust rounding when calculating resampled output frames

- src/gpu/d3d12/SDL_gpu_d3d12.c
Resolves #10629 
Let's see if this fixes CI...
> GPU D3D12: Fix teardown and leaks on device creation failure

- Xcode/SDL/SDL.xcodeproj/project.pbxproj
> Add GPU files to xcodeproj

- src/render/direct3d12/SDL_render_d3d12.c
- src/render/vulkan/SDL_render_vulkan.c
Fixes https://github.com/libsdl-org/SDL/issues/10649
> Fixed return value from D3D12_UpdateVertexBuffer()

- src/video/kmsdrm/SDL_kmsdrmdyn.c
- src/video/kmsdrm/SDL_kmsdrmdyn.h
- src/video/kmsdrm/SDL_kmsdrmsym.h
- src/video/kmsdrm/SDL_kmsdrmvideo.c
Fixes https://github.com/libsdl-org/SDL/issues/10675
> Make newer DRM and GBM functions optional

- test/testthread.c
- test/torturethread.c
Fixes https://github.com/libsdl-org/SDL/issues/10711
> Use atomic variables for thread communication

- include/SDL3/SDL_gpu.h
- src/gpu/d3d11/SDL_gpu_d3d11.c
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
- test/testgpu_spinning_cube.c
I've documented all the GPU header structs up to the binding structs, which I'll get to soon. Comments welcome.
> GPU: Document structs

- include/SDL3/SDL_gpu.h
- src/dynapi/SDL_dynapi_procs.h
- src/gpu/SDL_gpu.c
- src/gpu/SDL_sysgpu.h
- src/gpu/d3d11/SDL_gpu_d3d11.c
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
- src/render/sdlgpu/SDL_render_gpu.c
- test/testgpu_spinning_cube.c
The parameters list for this function was getting long so I moved them into an info struct.
Requesting a sanity check from @TheSpydog
> Add load op and clear color to SDL_BlitGPUTexture

- src/gpu/d3d11/SDL_gpu_d3d11.c
- src/gpu/metal/SDL_gpu_metal.m
- src/gpu/vulkan/SDL_gpu_vulkan.c
0 is currently `SDL_GPU_TEXTUREFORMAT_A8_UNORM`
> GPU: fix SDL_GetGPUSwapchainTextureFormat error return value

- src/gpu/vulkan/SDL_gpu_vulkan.c
Makes FetchDescriptorSet pretty much vanish from FNA3D profiling data!
> vulkan: Use a spinlock instead of a mutex for descriptor pools

- include/SDL3/SDL_gpu.h
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
- src/gpu/SDL_gpu.c
Helpful function for app infrastructure that separates querying driver support from actually creating the GPU device!
> gpu: Add SDL_QueryGPUSupport

- include/SDL3/SDL_process.h
- include/SDL3/SDL_stdinc.h
- src/dialog/unix/SDL_zenitydialog.c
- src/misc/unix/SDL_sysurl.c
- src/process/SDL_process.c
- src/process/SDL_sysprocess.h
- src/process/posix/SDL_posixprocess.c
- src/process/windows/SDL_windowsprocess.c
- src/stdlib/SDL_getenv.c
- src/video/wayland/SDL_waylandmessagebox.c
- test/testprocess.c
@Semphriss, how does this look?
> Switched zenity dialogs to use the new process API

- android-project/app/proguard-rules.pro
A couple of JNI methods changed from returning int to boolean.
> Update proguard-rules.pro in-line with commit 9ff3446

- build-scripts/clang-format-src.sh
- docs/README-migration.md
- include/SDL3/SDL_hints.h
- src/atomic/SDL_spinlock.c
- src/audio/SDL_audiocvt.c
- src/audio/dummy/SDL_dummyaudio.h
- src/camera/SDL_camera.c
- src/camera/android/SDL_camera_android.c
- src/core/linux/SDL_evdev.c
- src/core/windows/SDL_windows.h
- src/dialog/SDL_dialog_utils.h
- src/dynapi/gendynapi.py
- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/gpu/vulkan/SDL_gpu_vulkan.c
- src/joystick/SDL_joystick.c
- src/misc/ios/SDL_sysurl.m
- src/stdlib/SDL_random.c
- src/test/SDL_test_harness.c
- src/time/SDL_time.c
- src/video/SDL_video.c
- src/video/wayland/SDL_waylandevents.c
- src/video/wayland/SDL_waylandwindow.c
- src/video/x11/edid.h
- test/testaudio.c
I took the patch in https://github.com/libsdl-org/SDL/pull/10890 and reverted third-party code changes.
Closes https://github.com/libsdl-org/SDL/pull/10890
> Fix typos (thanks @qndel!)

- src/video/wayland/SDL_waylandevents.c
Backport @Kontrabant 's leak fixes from #8060 to SDL2.
#8056
> wayland: Fix memory leaks (SDL2)

- test/testautomation_stdlib.c
i.e.:  `unknown conversion type character 'l' in format`
See https://github.com/libsdl-org/SDL/pull/10789#issuecomment-2354011906
> testautomation_stdlib.c: fix -Wformat warnings from mingw with %lld / %llu

- src/video/kmsdrm/SDL_kmsdrmvideo.c
SDL3 port of #10915 (including the follow-up fix in 7eb85b07e0b76c7e8ae5bfdde5932af7249df395)
> kmsdrm: Keep fd around if we can drop master (SDL3)

- test/testautomation_audio.c
- test/testautomation_events.c
- test/testcamera.c
Discussed in https://github.com/libsdl-org/SDL/pull/10933
> Remove casts from typed pointer to void * for printf %p in test projects

- .github/workflows/create-test-plan.py
- .github/workflows/generic.yml
- build-scripts/check_android_jni.py
- build-scripts/check_stdlib_usage.py
- The versioning script did not run on ci
- Check the android JNI bindings on ci
- Fix `build-scripts/check_stdlib_usage.py` (it spews a few warnings)
> Check Android JNI bindings on ci

- .github/workflows/generic.yml
- build-scripts/check_stdlib_usage.py
- src/camera/pipewire/SDL_camera_pipewire.c
- src/core/android/SDL_android.c
- src/render/gpu/SDL_render_gpu.c
- src/video/cocoa/SDL_cocoawindow.m
- src/video/haiku/SDL_bmodes.cc
Make sure we're not using libc functions, unless there's an override.
> Test stdlib usage on ci

- src/video/wayland/SDL_waylandevents.c
> wayland: Raise all touches on a cancel event

- src/gpu/d3d12/SDL_gpu_d3d12.c
- src/stdlib/SDL_getenv.c
Another small batch of renames and API changes which slipped through the cracks for Xbox targets.
> Fix Xbox builds

- include/SDL3/SDL_filesystem.h
- src/filesystem/SDL_filesystem.c
- src/filesystem/windows/SDL_sysfsops.c
- test/testfilesystem.c
> filesystem: SDL_CreateDirectory should make parent directories.

- src/gpu/vulkan/SDL_gpu_vulkan.c
> gpu: Check Vulkan device features for IsDeviceSuitable

- src/file/SDL_iostream.c
This makes SDL_IOStream::flush not just flush the C runtime buffers to the OS, it also now makes sure it syncs file data to disk.
Just making sure the Windows builders like this before I merge.
> iostream: flush() should attempt to sync file data to physical media.

- include/SDL3/SDL_stdinc.h
- include/SDL3/SDL_test_crc32.h
- include/SDL3/SDL_test_memory.h
- src/joystick/gdk/SDL_gameinputjoystick.c
Closes https://github.com/libsdl-org/SDL/pull/10980
> Including stdbool.h, take 2!

- src/process/windows/SDL_windowsprocess.c
- test/CMakeLists.txt
- test/childprocess.c
- test/testprocess.c
This WIP pr contains extra tests for the SDL_process family of functions.
It's not finished yet, but I hope it helps to fix issues with SDL_process and avoid double work.
> Tests for SDL_process

- .github/workflows/create-test-plan.py
- src/file/SDL_iostream.c
> ci: bump haiku to r1beta5

- src/render/gpu/SDL_render_gpu.c
> Render GPU: Don't cycle on UpdateTexture

- include/SDL3/SDL_iostream.h
- src/file/SDL_iostream.c
Just need confirmation that I got the name right!
Fixes #11025
> Add SDL_PROP_IOSTREAM_MEM_BASE_POINTER

- include/SDL3/SDL_gpu.h
> GPU Introduction

- src/file/SDL_iostream.c
- src/file/SDL_iostream_c.h
- src/process/posix/SDL_posixprocess.c
Possibly fixes https://github.com/libsdl-org/SDL/issues/11006
> Use file descriptor I/O for process pipes

- test/childprocess.c
Make sure we flush all output so it's seen by the parent as it happens.
> Just use normal stdio for the child process

- include/SDL3/SDL_properties.h
- src/SDL_properties.c
- src/SDL_properties_c.h
You'd think a C library would love the letter C. Guess not :(
> Fix typo: DiretMedia->DirectMedia

- src/video/wayland/SDL_waylandmouse.c
- src/video/wayland/SDL_waylandshmbuffer.c
- src/video/wayland/SDL_waylandshmbuffer.h
- src/video/wayland/SDL_waylandvideo.c
- src/video/wayland/SDL_waylandvideo.h
- src/video/wayland/SDL_waylandwindow.c
- src/video/wayland/SDL_waylandwindow.h
- wayland-protocols/xdg-toplevel-icon-v1.xml
Backport of window icon support to SDL2, by request.
Closes #11086
> SDL2: Add Wayland icon support

- test/testautomation_mouse.c
X11 seems to need a slight delay before warping the pointer to ensure that the window is actually fully visible on the desktop.
This also disables the warp focus test on XWayland, as warping the mouse cursor when outside the window on any Wayland desktop usually just doesn't work, XWayland included.
Fixes #11128
> test: Fix mouse focus test on X11

- src/thread/generic/SDL_syscond.c
This replaces the internal mutex with a semaphore, so we're only using a single synchronization primitive to implement this, and cleans up some logic around wait timeouts.
The existing SDL code has this comment:
```c
/*
This implementation borrows heavily from the BeOS condition variable
implementation, written by Christopher Tate and Owen Smith.  Thanks!
*/
```
And later references [this blog post](https://web.archive.org/web/20010914175514/http://www-classic.be.com/aboutbe/benewsletter/volume_III/Issue40.html#Workshop) from Christopher Tate about the topic.
The code from that post was on ftp.be.com--long gone--but there was still [a mirror](https://ftp.zx.net.nz/pub/archive/ftp.be.com/), so tada, we have [the actual code](https://github.com/user-attachments/files/17330369/condvar.zip). …
> thread: Rewrote generic Condition Variables.

- src/timer/SDL_timer.c
- src/timer/windows/SDL_systimer.c
- test/testtimer.c
Fixes https://github.com/libsdl-org/SDL/issues/10592
> Improved implementation of SDL_DelayPrecise() (thanks @nightmareci!)

- src/video/x11/SDL_x11opengles.c
SDL3: opengles2 render not support window with transparent flag on Linux/X11(maybe bug) (#11167)
SDL3:  opengles2 render not support window with transparent flag on Linux/X11:    
1. create window with transparent flag SDL_WINDOW_TRANSPARENT    
SDL_SetHint(SDL_HINT_VIDEO_FORCE_EGL, "true");     
SDL_CreateWindowWithProperties(...);    
2.  create opengles2 render    
SDL_Renderer* sdlRenderer = SDL_CreateRenderer(sdlWindow, "opengles2");    
the first render support transparent, it's ok.    
3. create another window/render with the same code, the second window not support transparent.    
Bug reason:    
When create the first Window:    
in src\video\x11\SDL_x11opengles.c:X11_GLES_GetVisual    
create a XVisualInfo support transparent(because _this->egl_data->eglGetConfigAttrib return …
> SDL3: opengles2 render not support window with transparent flag on Linux/X11(maybe bug) (#11167)

- include/SDL3/SDL_log.h
- src/SDL_log.c
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
Fixes https://github.com/libsdl-org/SDL/issues/10603
Closes https://github.com/libsdl-org/SDL/pull/11106
> Added SDL_GetDefaultLogOutputFunction()

- src/video/SDL_rect_impl.h
- test/testautomation_rect.c
Fixes https://github.com/libsdl-org/SDL/issues/10866
> Fixed Cohen-Sutherland out code computation for float line intersection

- src/SDL_log.c
- src/render/SDL_render.c
- src/render/opengl/SDL_render_gl.c
- src/render/opengl/SDL_shaders_gl.c
- src/render/opengles2/SDL_render_gles2.c
- src/render/vitagxm/SDL_render_vita_gxm.c
- src/video/SDL_surface.c
- src/video/windows/SDL_windowsevents.c
- src/video/windows/SDL_windowswindow.c
Fixes https://github.com/libsdl-org/SDL/issues/8959
> Check return value of SDL_small_alloc()

- src/video/SDL_yuv.c
- src/video/yuv2rgb/yuv_rgb_common.h
- src/video/yuv2rgb/yuv_rgb_internal.h
- test/testyuv.c
Also added simple colorspace testing to testyuv.
> Added support for full range BT.709 YUV conversion

- src/file/SDL_iostream.c
Add more error information when failing to open a SDL_IOStream on windows.
> Report win32 last error string windows_file_open

- src/render/vitagxm/SDL_render_vita_gxm.c
> VITA: fix yuv texture update

- src/render/vitagxm/SDL_render_vita_gxm.c
> VITA: fix yuv texture update (SDL2)

- src/main/SDL_main_callbacks.c
- src/render/SDL_render.c
- src/render/vulkan/SDL_render_vulkan.c
@AntTheAlchemist, I just ran testcontroller on my Pixel phone with the vulkan renderer and this patch, and it worked for me. It worked fine, showing up in landscape mode. Does this fix https://github.com/libsdl-org/SDL/issues/10318 for you?
> Fixed crash if the Vulkan renderer changes swapchain image count

- src/events/SDL_keyboard.c
Fixes https://github.com/libsdl-org/SDL/issues/10679
> If we get a newline character, treat it as SDLK_RETURN

- docs/README-cmake.md
- docs/README-git.md
Fixes https://github.com/libsdl-org/SDL/issues/11260
Fixes https://github.com/libsdl-org/SDL/issues/11262
> docs: document copying shared SDL3 a bit more + document sanitizer/libc incompatibility

- src/render/vulkan/SDL_render_vulkan.c
> Fix VULKAN_UpdateViewport judgment.

- include/SDL3/SDL_events.h
- include/SDL3/SDL_gamepad.h
Add documentation for the times when GAMEPAD_ADDED events are added to the
event queue.
Supersedes https://github.com/libsdl-org/SDL/pull/11272
> docs: Explain events for already plugged in controllers

- include/SDL3/SDL_events.h
- src/render/direct3d11/SDL_render_d3d11.c
- src/render/direct3d12/SDL_render_d3d12.c
- src/render/vulkan/SDL_render_vulkan.c
- src/test/SDL_test_common.c
This is sent when the device is lost and can't be recovered.
Also fixed the vulkan renderer so it returns errors appropriately and will log and break if debug mode is enabled.
> Added SDL_EVENT_RENDER_DEVICE_LOST

- CMakeLists.txt
- cmake/sdlchecks.cmake
- src/video/SDL_video.c
- src/video/openvr/SDL_openvrvideo.c
- src/video/windows/SDL_windowsvideo.c
> OpenVR fixes

- src/filesystem/windows/SDL_sysfilesystem.c
Set error using function hresult, previous code was using win32 last-error when it wasn't set.
> Set error using function hresult

- include/SDL3/SDL_stdinc.h
https://github.com/libsdl-org/SDL/pull/11315#issuecomment-2434066298
> Allow redefinition of only one macro SDL_SINT64_C SDL_UINT64_C

- src/render/vulkan/SDL_render_vulkan.c
Closes #10318 - implement Android prerotation in the Vulkan renderer
Switching from portrait -> landscape orientation did not work correctly in the SDL Vulkan renderer.  This change implements Vulkan pre-rotation for Android as is recommended (https://developer.android.com/games/optimize/vulkan-prerotation).  Tested with testspriteminimal on Huawei P30 and Google Pixel 3XL.
#10318
> Closes #10318 - implement Android prerotation in the Vulkan renderer

- src/filesystem/posix/SDL_sysfsops.c
> SDL_SYS_RenamePath(): Fix error message.

- .github/workflows/create-test-plan.py
The only real change in the CI script is the consolidation of some Ubuntu-specific steps; the existing Ubuntu builders should behave exactly as they did before.
Waiting for artifacts to upload so I can locally test the output binary, but the configure results appear to be correct so I'm expecting everything to work as intended!
Fixes #11357
> ci: Add Steam Linux Runtime (Sniper) task

- src/gpu/metal/SDL_gpu_metal.m
Support of Metal on macOS should not be assumed to be always available.
When macOS runs under a virtual environment, it is possible that MTLCreateSystemDefaultDevice() does not succeed.
Not checking this failure results in a crash down the road. This change allows to skip GPU renderer and use an adequate fallback.
> metal: check success of device creation

- examples/game/02-woodeneye-008/woodeneye-008.c
- fixed typo in player spawn position, and initialize yaw for all four players
- move SetRenderDrawColor out of hot loop
- proceduralize cube edge generation
> quick fixes to WoodenEye 008

- test/testgl.c
- test/testgles2.c
- test/testgles2_sdf.c
It should be then consistent with SDL_SetError().
> test: Change LoadContext() return value type from int to bool

- src/gpu/vulkan/SDL_gpu_vulkan.c
Fixes #11429
Needs review from @thatcosmonaut before merge.
> GPU Vulkan: release submitted command buffer after defrag

- examples/game/01-snake/snake.c
I am not a native speaker but the old word order confused me.
> snake: improve comment

- src/events/SDL_mouse.c
In the last PR I missed the case where relative mode is emulated by warping. This patch adds in the case to differentiate it from hardware relative deltas.
> fix relative warp emulation broken by #11460

- android-project/app/proguard-rules.pro
Based on existing work by @AntTheAlchemist on SDL3 branch.
Similar to SDL3, it allows SDL2 to be built with enabled optimizations and code shrinking.
> Add proguard rules for SDL2

- include/SDL3/SDL_events.h
- src/events/SDL_categories.c
- src/events/SDL_categories_c.h
- src/events/SDL_events.c
- src/render/direct3d/SDL_render_d3d.c
- src/render/direct3d11/SDL_render_d3d11.c
- src/render/direct3d12/SDL_render_d3d12.c
- src/render/vulkan/SDL_render_vulkan.c
- src/test/SDL_test_common.c
- src/video/android/SDL_androidevents.c
> events: Added SDL_RenderEvent.

- src/video/emscripten/SDL_emscriptenevents.c
This implementation writes dropped files to `/tmp/filedrop/<id>/<filename>` (with `id` an incrementing counter).
All files are removed when unregistering the event handlers, but should the dragdrop folders be freed somewhere else?
Fixes #9882
> emscripten: send drag and drop events

- include/SDL3/SDL_hints.h
- src/events/SDL_mouse.c
- src/events/SDL_mouse_c.h
- src/video/android/SDL_androidmouse.c
- src/video/cocoa/SDL_cocoamouse.m
- src/video/emscripten/SDL_emscriptenmouse.c
- src/video/haiku/SDL_bvideo.cc
- src/video/wayland/SDL_waylandmouse.c
- src/video/windows/SDL_windowsmouse.c
- src/video/x11/SDL_x11mouse.c
> hint for choosing which system cursor to use as default 

- src/video/vita/SDL_vitamouse.c
> Vita: implement mousewheel and buttons 4/5

- include/SDL3/SDL_audio.h
- src/audio/SDL_audio.c
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
> audio: Added SDL_IsAudioDevicePhysical and SDL_IsAudioDevicePlayback.

- include/SDL3/SDL_surface.h
Removed extra sa in SDL_ConvertSurfaceAndColorspace
> Removed extra sa in SDL_ConvertSurfaceAndColorspace

- src/gpu/d3d12/SDL_gpu_d3d12.c
The D3D12 validation layer outputs exclusively with OutputDebugString() which is only visible when running an external debugger. This is in contrast to the Vulkan validation layers which output to standard output. As validation warnings are important for development purposes but not all SDL users use an external debugger this PR duplicates all warnings and outputs them to the SDL log as well.
The output format of these messages attempt to match the official D3D12 validation layer as much as possible so it's easy to Google the warnings. The only difference is that I've opted to not stringify D3D12_MESSAGE_ID as it's an extremely large enum and I felt that it was too verbose to include.
This PR also removes the debug break on "error" messages to more accurately follow the behavior of the …
> GPU: Forward D3D12 validation warnings to the SDL log

- include/SDL3/SDL_clipboard.h
- include/SDL3/SDL_events.h
- include/SDL3/SDL_init.h
- include/SDL3/SDL_keyboard.h
- include/SDL3/SDL_mouse.h
- include/SDL3/SDL_render.h
- include/SDL3/SDL_video.h
- src/SDL.c
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
- src/events/SDL_events.c
- test/testautomation_events.c
This PR documents the main thread requirements of SDL video and input functions and provides a way to easily run code on the main thread.
Fixes https://github.com/libsdl-org/SDL/issues/11447
> SDL main thread requirements

- src/video/emscripten/SDL_emscriptenvideo.c
This adds support for `SDL_GetSystemTheme()` with Emscripten. It works with the CSS media query [`prefers-system-theme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).
Two notable limitations:
1. The media queries do not distinguish between the light theme and no preference, so no preference means light theme by default.
2. _Edit: it is implemented now._ ~~There is a way in Javascript to listen to changes for system theme preferences, but notifying SDL would require implementing a JS-to-C callback, which requires exporting that function to be callable with `Module.ccall()`. Since I believe SDL does not require exporting functions, I judged that it would be unfit to add that requirement just for querying the system theme.~~
~~There seem to be [alternative …
> Add system theme support for Emscripten

- src/gpu/d3d12/SDL_gpu_d3d12.c
This PR logs the driver version when using the D3D12 GPU backend. The Vulkan backend already logs this information. This information is useful to know when debugging graphics issues submitted by end users.
D3D12 log output with this PR:
```
SDL_GPU Driver: D3D12
D3D12 Adapter: NVIDIA GeForce RTX 2060
D3D12 Driver: 32.0.15.6614
```
Vulkan log output:
```
SDL_GPU Driver: Vulkan
Vulkan Device: NVIDIA GeForce RTX 2060
Vulkan Driver: NVIDIA 566.14
Vulkan Conformance: 1.3.2
```
> GPU: Log D3D12 driver version

- src/SDL_hashtable.c
- src/SDL_hashtable.h
- src/SDL_properties.c
- src/SDL_utils.c
- src/audio/SDL_audio.c
- src/camera/SDL_camera.c
- src/events/SDL_keymap.c
- src/gpu/vulkan/SDL_gpu_vulkan.c
- src/joystick/SDL_gamepad.c
- src/render/gpu/SDL_pipeline_gpu.c
- src/stdlib/SDL_getenv.c
- src/video/SDL_pixels.c
Fixes https://github.com/libsdl-org/SDL/issues/11635
> SDL_HashTable is now optionally thread-safe

- src/video/SDL_video.c
It's possible (likely!) someone could just pass a pointer returned by SDL_GetError for one of these strings, but the message box code has to do a ton of complicated stuff that might _also_ call SDL_SetError, so you could end up with the string having different contents by the time you display it.
Just make a copy of the strings unconditionally at the start, so they're safe no matter where they came from.
Fixes #10932.
> messagebox: Copy title and message up front, to protect SDL_GetError() strings.

- src/video/uikit/SDL_uikitviewcontroller.m
Fixes https://github.com/libsdl-org/SDL/issues/7518
> Enable high refresh rates on iOS

- include/SDL3/SDL_stdinc.h
- src/stdlib/SDL_malloc.c
- src/test/SDL_test_memory.c
Fixes https://github.com/libsdl-org/SDL/issues/11099
> Disable tracking memory allocation counts by default

- src/video/SDL_sysvideo.h
- src/video/SDL_video.c
- src/video/cocoa/SDL_cocoawindow.h
- src/video/cocoa/SDL_cocoawindow.m
- src/video/windows/SDL_windowsevents.c
Fixes https://github.com/libsdl-org/SDL/issues/11508
> Allow rendering during the modal resize loop on macOS

- include/SDL3/SDL_render.h
- src/render/gpu/SDL_render_gpu.c
- src/test/SDL_test_common.c
Fixes https://github.com/libsdl-org/SDL/issues/11600
> Added SDL_PROP_RENDERER_GPU_DEVICE_POINTER

- src/tray/windows/SDL_tray.c
> Tray: subclass the builtin system message class instead

- include/SDL3/SDL_stdinc.h
Fixed a world ending typo in SDL_stdinc.h
None
> Fix documentation for SDL_sinf

- include/SDL3/SDL_tray.h
SDL_tray.h was missing some includes it uses
> Add missing includes to SDL_tray.h

- src/video/windows/SDL_windowswindow.c
> win32: Fix popup positioning

- src/thread/pthread/SDL_systhread.c
Cherry-picked from SDL2 https://github.com/libsdl-org/SDL/commit/e79b0ce2e4660e7621719ca3fce362545c90cbf7 and updated the android platform define
Set thread name on Android the same way as we do on Linux.
Acording to Bionic source code this function is available since 2013 [1] and hase the same signature.
[1] https://android.googlesource.com/platform/bionic/+/2a1bb4e64677b9abbc17173c79768ed494565047
(cherry picked from commit e79b0ce2e4660e7621719ca3fce362545c90cbf7)
/
> SDL3 - Use `pthread_setname_np` also on Android

- src/video/windows/SDL_windowsclipboard.c
This addresses the issue #11762 by reading the biCompression field to determine the correct size of the color table, and consequently the correct bih_size value.
#11762
> Fix dib-to-bmp logic in SDL_windowsclipboard.c

- android-project/app/src/main/java/org/libsdl/app/SDLSurface.java
- include/SDL3/SDL_asyncio.h
- include/SDL3/SDL_events.h
- src/core/linux/SDL_evdev.c
- src/events/SDL_categories.c
- src/events/SDL_events.c
- src/events/SDL_mouse.c
- src/events/SDL_touch.c
- src/events/SDL_touch_c.h
- src/file/generic/SDL_asyncio_generic.c
- src/file/io_uring/SDL_asyncio_liburing.c
- src/file/windows/SDL_asyncio_windows_ioring.c
- src/render/SDL_render.c
- src/test/SDL_test_common.c
- src/video/android/SDL_androidtouch.c
- src/video/cocoa/SDL_cocoawindow.m
- src/video/emscripten/SDL_emscriptenevents.c
- src/video/n3ds/SDL_n3dstouch.c
- src/video/uikit/SDL_uikitview.m
- src/video/vita/SDL_vitatouch.c
- src/video/wayland/SDL_waylandevents.c
- src/video/windows/SDL_windowsevents.c
- src/video/x11/SDL_x11xinput2.c
- test/testasyncio.c
Fixes https://github.com/libsdl-org/SDL/issues/10528
> Added SDL_EVENT_FINGER_CANCELED

- src/video/windows/SDL_windowsevents.c
- src/video/windows/SDL_windowswindow.c
- src/video/windows/SDL_windowswindow.h
Fixes #11764 (correctly this time)
> win32: Fix popup size event (take 2)

- src/video/windows/SDL_windowsmessagebox.c
- test/testmessage.c
Fixes https://github.com/libsdl-org/SDL/issues/4775
Fixes https://github.com/libsdl-org/SDL/issues/9691
> Make Windows dialogs DPI aware

- src/video/windows/SDL_windowsevents.c
- src/video/windows/SDL_windowsvideo.c
- src/video/windows/SDL_windowsvideo.h
This is SDL3 pen support for Windows. This compiles, but my Windows hard drive bit the dust, so I'm cloning to a new hard drive today so I can test this.
Fixes #10516.
> pen: Windows pen support.

- src/video/SDL_video.c
I've found that on some systems (Mesa) calling `SDL_GL_GetAttribute(SDL_GL_STENCIL_SIZE, ...)` with no stencil bits will cause an SDL error (GL error, GL_INVALID_OPERATION). This doesn't seem to be the case for all systems (windows nvidia just returns 0).
According to the GL spec for `glGetFramebufferAttachmentParameteriv`:
`GL_INVALID_OPERATION is generated if the value of GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE is GL_NONE and pname is not GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME or GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE.`
and
`If the value of GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE is GL_NONE, then either no framebuffer is bound to target; or a default framebuffer is queried, attachment is GL_DEPTH or GL_STENCIL, and the number of depth or stencil bits, respectively, is zero. In this case …
> video: Fix SDL_GL_GetAttribute depth/stencil size when 0

- android-project/app/src/main/AndroidManifest.xml
Removed an outdated comment in AndroidManifest.xml
> Removed outdated comment in AndroidManifest.xml

- src/tray/unix/SDL_tray.c
When using the libappindicator/gtk/unix Tray backend, the background thread which calls gtk_main() is never destroyed. This means that we detect a leaked thread as SDL_Quit().
Instead, tell gtk to shut down its main loop when no tray icons are active. This fixes the issue here: SDL notices no leak, and repeatedly creating / destroying tray icons seems to work fine.
I've tested this against testtray (no regressions), and a build of DEFCON which implements 'Office Mode' using SDL_Tray, which seems to now work fine.
That being said, it's entirely possible that this could cause problems if:
- There's some horrendous multithreaded nightmare going on. This works against some things (like the icon being destroyed from within the callback), but if multiple threads create tray icons at the same …
> tray: unix: Shutdown the GTK thread when not in use

- include/SDL3/SDL_render.h
Fixes #9424.
@cgutman, @slouken: does this cover the issue?
> SDL_render.h: Improve SDL_ConvertEventToRenderCoordinates documentation.

- src/tray/unix/SDL_tray.c
If we write directly to filenames in /tmp, we're subject to time-of-check/time-of-use symlink attacks on most systems (although recent Linux kernels mitigate these by default). We can avoid these attacks by securely creating a directory owned by our own uid, and doing all our file I/O in that directory. Other uids cannot create symbolic links in that directory, so we are protected from symlink attacks.
This does not protect us from an attacker that is running with the same uid, but if such an attacker exists, then we have already lost.
Resolves: https://github.com/libsdl-org/SDL/issues/11887
> tray: Create tray icons for libappindicator securely

- src/storage/generic/SDL_genericstorage.c
> storage: Trim the title storage root from enumerated paths

- src/gpu/metal/SDL_gpu_metal.m
> gpu: Metal depth write should behave like Vulkan/D3D12

- include/SDL3/SDL_assert.h
> Leave SDL_TriggerBreakpoint undefined on unknown platforms

- include/SDL3/SDL_hints.h
- src/events/SDL_mouse.c
Context: https://github.com/libsdl-org/SDL/pull/11539#issuecomment-2585382009
> apply relative multiplier scale after system scale

- .github/workflows/create-test-plan.py
- .github/workflows/release.yml
- Xcode/SDL/SDL.xcodeproj/project.pbxproj
- docs/README-ios.md
- docs/README-macos.md
- src/SDL_internal.h
- src/audio/coreaudio/SDL_coreaudio.m
- src/dialog/cocoa/SDL_cocoadialog.m
- src/gpu/metal/SDL_gpu_metal.m
- src/hidapi/ios/hid.m
- src/joystick/apple/SDL_mfijoystick.m
- src/misc/ios/SDL_sysurl.m
- src/render/metal/SDL_render_metal.m
- src/video/cocoa/SDL_cocoaclipboard.m
- src/video/cocoa/SDL_cocoaevents.m
- src/video/cocoa/SDL_cocoamodes.m
- src/video/cocoa/SDL_cocoavideo.h
- src/video/cocoa/SDL_cocoavideo.m
- src/video/cocoa/SDL_cocoawindow.m
- src/video/uikit/SDL_uikitappdelegate.m
- src/video/uikit/SDL_uikitevents.m
- src/video/uikit/SDL_uikitmodes.m
- src/video/uikit/SDL_uikitpen.h
- src/video/uikit/SDL_uikitpen.m
- src/video/uikit/SDL_uikitvideo.m
- src/video/uikit/SDL_uikitview.h
- src/video/uikit/SDL_uikitview.m
- src/video/uikit/SDL_uikitviewcontroller.m
- src/video/uikit/SDL_uikitwindow.m
We require at least Xcode 12.2 and macOS SDK 11 to build. We support deploying to macOS 10.13, iOS 11.0, and tvOS 11.0.
This cleans up the code significantly
> Bumped deployment requirements for Apple platforms

- include/SDL3/SDL_hints.h
- include/SDL3/SDL_pen.h
- src/events/SDL_mouse.c
- src/events/SDL_mouse_c.h
- src/events/SDL_pen.c
- src/events/SDL_pen_c.h
- src/events/SDL_touch.c
- src/video/wayland/SDL_waylandevents.c
This is a draft, because I need to pull this branch onto other machines to test, and I wanted to have the builders take a run at it in the meantime.
Fixes #11948.
> pen: Send virtual mouse and touch events for pen input.

- src/video/emscripten/SDL_emscriptenevents.c
Fixes https://github.com/libsdl-org/SDL/issues/11973
> Fixed detection of function keys on Emscripten

- src/video/windows/SDL_windowsevents.c
- src/video/windows/SDL_windowswindow.h
Fixes https://github.com/libsdl-org/SDL/issues/11688
> windows: use the initial rect to anchor fixed aspect ratio resizing

- Xcode/SDL/pkg-support/resources/INSTALL.md
Document using the dmg/xcframework in CMake
Fixes https://github.com/libsdl-org/SDL/issues/12009
> release: document using the xcframework with CMake

- src/video/windows/SDL_windowsevents.c
- src/video/windows/SDL_windowswindow.h
Fixes https://github.com/libsdl-org/SDL/issues/12029
> Call the windows message hook while inside a modal message loop

- src/joystick/apple/SDL_mfijoystick.m
- src/video/uikit/SDL_uikitpen.m
Fixes https://github.com/libsdl-org/SDL/issues/12048
> Fixed build when using an older Xcode SDK

- src/audio/aaudio/SDL_aaudio.c
- src/audio/alsa/SDL_alsa_audio.c
- src/joystick/hidapi/SDL_hidapijoystick.c
- src/video/kmsdrm/SDL_kmsdrmvideo.c
- src/video/wayland/SDL_waylanddatamanager.c
- src/video/wayland/SDL_waylandevents.c
- src/video/windows/SDL_windowskeyboard.c
- src/video/windows/SDL_windowswindow.c
- test/testrumble.c
- test/testvulkan.c
https://github.com/libsdl-org/SDL/pull/12061
> Remove even more newlines from log messages

- src/video/wayland/SDL_waylanddatamanager.c
This fixes the issues reported in https://github.com/libsdl-org/SDL/issues/12113
> linux 32 bit build fixes in 64 bit environments (steam sniper sdk, gcc 14)

- src/timer/windows/SDL_systimer.c
These functions are not available on Windows XP
> Dynamically load CreateWaitableTimerExW and SetWaitableTimerEx

- src/joystick/windows/SDL_windows_gaming_input.c
I've cherry-picked 6b4b9b5f2bc690faf35d6baf527a3a3c2f471eef to SDL2 branch.
This fixes #9091 for SDL2 where it was still an issue (tested with SDL2 branch and 2.30.11). After the fix hot-plugging doesn't add two devices (tested on Windows 11 with a wireless Xbox 360 controller).
> Improved XInput controller detection for SDL2, too

- src/video/SDL_bmp.c
Hi. The Preview app on macOS doesn't seem to like RGBA32 bitmaps that are missing bitmap header v5 values. I tested the changes on Windows, macOS, and Linux (ffplay) and have not found any regressions.
#11903
> SDL_SaveBMP_IO: Write bitmap header v5 values

- src/video/x11/SDL_x11events.c
Use the modifier state supplied with key events to track the system modifier state instead of relying on the state returned by XQueryPointer(), which can be racy when used with automated text entry.
Fixes #12267
> x11: Apply the modifier state from key events

- VisualC-GDK/SDL/SDL.vcxproj
- VisualC-GDK/SDL/SDL.vcxproj.filters
- VisualC/SDL/SDL.vcxproj
- VisualC/SDL/SDL.vcxproj.filters
- src/core/windows/SDL_gameinput.c
- src/core/windows/SDL_gameinput.h
- src/joystick/gdk/SDL_gameinputjoystick.c
- src/video/windows/SDL_windowsgameinput.c
Also fixed a bug with keyboard and mouse readings
> Refactored GameInput initialization

- src/tray/unix/SDL_tray.c
This PR fixes the management of tray menus for GTK.
It's essentially #12225, minus the warning silencing, plus @smcv's last feedback.
Fixes https://github.com/libsdl-org/SDL/issues/12092
> Fix GTK tray icon without menu and lifetime

- src/video/haiku/SDL_bvideo.cc
fixes https://github.com/libsdl-org/SDL/issues/12284#issuecomment-2661584212
> [Haiku] Check if the returned _SDL_GLView is null or not

- test/testautomation_audio.c
Freeing memory in `test/testautomation_audio.c` when prematurely returning from functions.
```shell
[ 56%] Building C object test/CMakeFiles/testautomation.dir/testautomation_audio.c.o
/mnt/devel/dev/projects-NEW/external/libs/c/SDL/sources/SDL-git-Sackzement/test/testautomation_audio.c:822:36: warning: Potential leak of memory pointed to by 'src_buf' [clang-analyzer-unix.Malloc]
822 |                             return TEST_ABORTED;
|                                    ^
/mnt/devel/dev/projects-NEW/external/libs/c/SDL/sources/SDL-git-Sackzement/include/SDL3/SDL_test_harness.h:51:30: note: expanded from macro 'TEST_ABORTED'
51 | #define TEST_ABORTED        -1
|                              ^
/mnt/devel/dev/projects-NEW/external/libs/c/SDL/sources/SDL-git-Sackzement/test/testautomation_audi …
```
> test/testautomation_audio.c: Free variables before returning

- src/audio/emscripten/SDL_emscriptenaudio.c
Same as #12332 which already landed on SDL2 branch.
> Fix SDL_emscriptenaudio.c under wasm64

- src/core/windows/SDL_hid.c
- src/core/windows/SDL_hid.h
- src/video/windows/SDL_windowsevents.c
> use hidapi to get mouse/keyboard string

- src/video/cocoa/SDL_cocoawindow.m
isZoomed returns true if the window has the size and position that it would if it were maximized, so we need to check to see if our floating state matches that before saying we're zoomed.
This fixes calling zoom:nil on a borderless resizable window that was created with the same size as the usable desktop area, which happens to also be the maximized state.
Fixes https://github.com/libsdl-org/SDL/issues/12228
> Check desired window area when checking zoom state

- src/audio/pipewire/SDL_pipewire.c
The fix in 32cc92dceb3eba19935fd4ea95397877e7a46a16 mostly addressed the init race condition, but there was still a small window where it could occur.
If the pipewire thread invokes `output_callback()` while we're still waiting inside `PIPEWIRE_OpenDevice()` (before `pw_thread_loop_wait()` has woken up), we will deadlock. The pipewire thread owns the loop lock and is blocked on the audio device lock, which cannot be released because `pw_thread_loop_wait()` needs to reacquire the loop lock before it can return and allow `PIPEWIRE_OpenDevice()` to complete and release the device lock.
I fixed this by adding an additional bit to `PW_READY_FLAGS` that is only set when the device opening thread exits the init loop, so the new checks added in 32cc92dceb3eba19935fd4ea95397877e7a46a16 will cover …
> pipewire: Fix possible deadlock when opening a device

- src/video/x11/SDL_x11window.c
> x11: Accommodate the borders when setting the initial window position

- src/audio/pulseaudio/SDL_pulseaudio.c
When the flushing is not able to keep up with the audio stream coming in, it will end up flushing forever and block API clients from getting any audio.
The example program in #9706 get some audio with SDL 3, while do not get any audio with SDL 2, which I suspect is because SDL 3 is quicker at flushing the audio. A fix for the SDL 2 issue is available in #12378.
> Changed PULSEAUDIO_FlushRecording() to only flush audio present when called.

- src/video/wayland/SDL_waylandcolor.c
- src/video/wayland/SDL_waylandcolor.h
- src/video/wayland/SDL_waylandvideo.c
- src/video/wayland/SDL_waylandvideo.h
- src/video/wayland/SDL_waylandwindow.c
- src/video/wayland/SDL_waylandwindow.h
> wayland: Ensure that color descriptions are always retrieved

- src/SDL_utils.c
- src/SDL_utils_c.h
- src/joystick/SDL_joystick.c
- src/video/windows/SDL_windowsevents.c
@expikr, thanks for the feedback, can you review?
> Include the VID/PID of generic keyboard/mouse devices on Windows

- include/SDL3/SDL_render.h
- src/render/SDL_render.c
- src/render/SDL_sysrender.h
Initial work on this patch was by @slouken, with further work from me. His work was perfect, the mistakes are all mine.  :)
Fixes https://github.com/libsdl-org/sdl2-compat/issues/279
> render: allow render targets to use logical presentation.

- src/audio/SDL_audioresample.c
Tweak the resampling rate calculation to better match the expected output frame count.
Generally it's expected that `dst_frames = (src_frames * dst_rate) / src_rate`.
To match this as closely as possible without infinite precision, always round up the resample rate.
For example, without rounding up, a sample ratio of 2:3 would have `sample_rate = 0xAAAAAAAA`
After 3 frames, the position would be 0x1.FFFFFFFE, meaning we haven't fully consumed the second input frame.
By rounding up to 0xAAAAAAAB, we would instead reach 0x2.00000001, fulling consuming the second frame.
#12115
> Ceil the audio resampling rate to avoid over-estimating output samples.

- src/video/windows/SDL_windowsevents.c
Fixes https://github.com/libsdl-org/SDL/issues/12423
> Update mouse button state when re-entering a window

- src/video/cocoa/SDL_cocoawindow.m
Fullscreen spaces and miniaturization will always give us some notification that they succeeded or failed, so the timeout isn't required. This prevents errant timeouts when live-resize is active.
> cocoa: Run pending events to completion

- src/SDL.c
- src/SDL_error_c.h
Fixes https://github.com/libsdl-org/SDL/issues/12439
> Save and restore error messages when rolling back after failed init

- src/events/SDL_events.c
Fixes https://github.com/libsdl-org/SDL/issues/12457
> Make SDL_RegisterEvents() thread-safe

- include/SDL3/SDL_surface.h
- src/render/SDL_render.c
- src/render/SDL_sysrender.h
- src/render/direct3d/SDL_render_d3d.c
- src/render/direct3d11/SDL_render_d3d11.c
- src/render/direct3d12/SDL_render_d3d12.c
- src/render/gpu/SDL_render_gpu.c
- src/render/metal/SDL_render_metal.m
- src/render/opengl/SDL_render_gl.c
- src/render/opengles2/SDL_render_gles2.c
- src/render/ps2/SDL_render_ps2.c
- src/render/psp/SDL_render_psp.c
- src/render/software/SDL_render_sw.c
- src/render/vitagxm/SDL_render_vita_gxm.c
- src/render/vitagxm/SDL_render_vita_gxm_tools.c
- src/render/vitagxm/SDL_render_vita_gxm_tools.h
- src/render/vitagxm/SDL_render_vita_gxm_types.h
- src/render/vulkan/SDL_render_vulkan.c
- test/testautomation_render.c
Also added texture addressing mode support to the PSP and Vita renderers (untested)
Fixes https://github.com/libsdl-org/SDL/issues/12461
> Make texture scale mode a part of the 2D renderer draw state

- src/video/SDL_surface.c
Fixes https://github.com/libsdl-org/SDL/issues/12472
> Added support for SDL_PIXELFORMAT_MJPG to SDL_DuplicateSurface()

- src/cpuinfo/SDL_cpuinfo.c
Tested on hardware
New3DS = 255
Old3DS = 127
> Implement SDL_GetSystemRAM for the 3ds

- src/gpu/SDL_gpu.c
Resolves https://github.com/libsdl-org/SDL/issues/12446
> gpu: Validate that CopyGPUTextureToTexture formats match

- docs/INTRO-mingw.md
As was discussed in the discord, this cleans up the CMakeLists.txt from the MinGW readme.
> Fixup the mingw readme cmakelists

- test/testautomation_hints.c
- test/testautomation_rect.c
These tests were failing with sdl2-compat
> tests: port failing SDL_{Hint,Rect} tests from pysdl2 to testautomation

- src/video/SDL_yuv.c
Fixes https://github.com/libsdl-org/SDL/issues/12546
> Added unaligned version of SDL_ConvertPixels_SwapNV_std()

- src/render/opengl/SDL_shaders_gl.c
This fixes the following warning/error during `SDL_CreateRenderer` and fallback to fixed opengl functions.
```
ERROR: Failed to compile shader:
ERROR: #define UVCoordScale 1.0
ERROR: varying vec4 v_color;
varying vec2 v_texCoord;
uniform sampler2D tex0;
uniform vec4 texel_size;
void main()
{
vec2 boxSize = clamp(fwidth(v_texCoord) * texel_size.zw, 1e-5, 1.0);
vec2 tx = v_texCoord * texel_size.zw - 0.5 * boxSize;
vec2 txOffset = smoothstep(vec2(1.0) - boxSize, vec2(1.0), fract(tx));
vec2 uv = (floor(tx) + 0.5 + txOffset) * texel_size.xy;
gl_FragColor = textureGrad(tex0, uv, dFdx(v_texCoord), dFdy(v_texCoord));
gl_FragColor.a = 1.0;
gl_FragColor *= v_color;
}
ERROR: 0:13(17): error: no function with name 'textureGrad'
```
> opengl: pixelart fragment shader uses GLSL version 1.30

- src/time/unix/SDL_systime.c
The tm_gmtoff field of the broken-down time 'tm' struct wasn't formally standardized until POSIX.1-2024, but practically it has been available on desktop *nix platforms such as Linux/glibc, FreeBSD, OpenBSD, NetBSD, OSX/macOS (NextStep before that), and others since the 1990s. The notable exception is SunOS/Solaris, where the timezone offset must still be retrieved in the strictly POSIX.1-2008 compliant way.
Fixes #12563
> time: Fix compilation on Solaris

- src/gpu/vulkan/SDL_gpu_vulkan.c
There was a gap in the render pass fetch lock which can cause a render pass to be inserted twice with the same key and thus get erroneously destroyed. I applied the same fix to framebuffer fetch just in case.
Resolves #12580
> GPU Vulkan: Fix render pass race

- test/testautomation_render.c
- test/testautomation_subsystems.c
> tests: port failing SDL_Renderer test from pysdl2 to testautomation

- docs/README-android.md
- docs/README-ios.md
Updates SDL's Android and iOS getting started documentation.
SDL_EventFilter points to a function that now returns a bool.
> Updates SDL_SetEventFilter code snippet to SDL3

- src/render/direct3d12/SDL_render_d3d12.c
Fixes https://github.com/libsdl-org/SDL/issues/12544
> Don't update a texture twice in the same batch on D3D12

- src/render/direct3d12/SDL_render_d3d12.c
Fixes https://github.com/libsdl-org/SDL/issues/12544
> We need to rebind D3D12 resources after updating them

- src/video/SDL_video.c
Fixes libsdl-org/sdl2-compat#415
> video: Fix boolean logic for getting the pending window position

- src/audio/SDL_audiotypecvt.c
Disable floating point exceptions when using neon intrinsics to convert between fixed and floating point numbers to avoid crashes caused by overflow. 
#12560
> audio: hold floating point exceptions when using neon

- src/video/windows/SDL_windowsevents.c
- src/video/windows/SDL_windowsvideo.c
- src/video/windows/SDL_windowsvideo.h
- src/video/windows/SDL_windowswindow.c
Fixes https://github.com/libsdl-org/SDL/issues/12528
> Improve move/resize visual smoothness on Windows

- src/joystick/windows/SDL_rawinputjoystick.c
Fixes https://github.com/libsdl-org/SDL/issues/12095
> Fixed mixed trigger and body rumble for Xbox controllers on Windows

- src/render/opengles2/SDL_render_gles2.c
Closes #12600
The web example mentioned in the linked issue no longer logs shader compilation errors with this fix (tested using Safari on iOS).
> Check if GL_OES_EGL_image_external is supported before trying to use it

- src/test/SDL_test_common.c
- src/video/SDL_sysvideo.h
- src/video/SDL_video.c
- src/video/windows/SDL_windowsevents.c
- src/video/windows/SDL_windowsvideo.c
- src/video/windows/SDL_windowswindow.c
- src/video/windows/SDL_windowswindow.h
It's visually only hooked up on Windows for now, but the API will be internally consistent on all platforms.
> Allow the progress API to be used on all platforms

- CMakeLists.txt
- include/SDL3/SDL_process.h
- include/build_config/SDL_build_config.h.cmake
- src/process/posix/SDL_posixprocess.c
- src/process/windows/SDL_windowsprocess.c
Fixes https://github.com/libsdl-org/SDL/issues/12654
> Added SDL_PROP_PROCESS_CREATE_WORKING_DIRECTORY_STRING

- examples/renderer/19-affine-textures/affine-textures.c
Adapted from the rotating texture example.
https://github.com/user-attachments/assets/c7460b12-281e-49d0-8ff4-b54e1536cbc3
> Spinning cube example with SDL_RenderTextureAffine

- test/testautomation_hints.c
- test/testautomation_rect.c
- test/testautomation_render.c
- test/testautomation_video.c
> Port pysdl2 tests to sdl3

- include/SDL3/SDL_pixels.h
- src/render/software/SDL_triangle.c
- src/video/SDL_blit_0.c
- src/video/SDL_blit_1.c
- src/video/SDL_blit_auto.c
- src/video/SDL_blit_slow.c
- src/video/SDL_bmp.c
- src/video/SDL_pixels.c
- src/video/SDL_pixels_c.h
Reference issue: https://github.com/libsdl-org/SDL/issues/12749.
> rename 'pixel' params of SDL_GetRGB, SDL_GetRGBA and SDL_LookupRGBAColor

- src/events/SDL_mouse.c
- src/render/software/SDL_draw.h
- src/render/software/SDL_drawline.c
- src/video/stb_image.h
Reference issue: https://github.com/libsdl-org/SDL/issues/12749.
(These were missed in previous pull req.  CC @barracuda156 )
> rename local pointer vars 'pixel' to 'pixels'

- src/video/SDL_blit_auto.h
- src/video/sdlgenblit.pl
Closes: https://github.com/libsdl-org/SDL/issues/12774.
> update sdlgenblit.pl after PR/12769

- build-scripts/wikiheaders.pl
Fixes various formatting issues and adds minor tweaks
**Changes:**
- Fixed characters surrounding bold/italic/code being separated by spaces
- Fixed missing line breaks
- Fixed sentences being broken up by bold/italic text and code
- Fixed multi-line macro definitions
- Fixed removing return types from `RETURN VALUE` section (as originally intended)
- Fixed the `SEE ALSO` section recommending to see bullet points (`•(3), SDL_acosf(3), •(3), ...`)
- Merged the `HEADER FILE` and `SYNOPSIS` sections
- Added the `MACRO PARAMETERS` section
**Things that could still be done:**
- `_not_` (and similar) could be underlined/italic
- Not as flexible as bold/italic/code as it'd break things like `SDL_SOMETHING_WHATEVER`
- `.UL` is a GNU extension I think? Didn't work for me when trying it out
- …
> docs: improve man page generation

- src/joystick/SDL_joystick.c
Add VID/PID for Turtle Beach VelocityOne joystick and throttle controllers
> Add Turtle Beach VelocityOne

- include/SDL_surface.h
https://github.com/libsdl-org/SDL/issues/12858
SDL3 PR: https://github.com/libsdl-org/SDL/pull/12863
> [SDL2] SDL_BlitSurface() comment: only dstrect is modified in function

- src/video/SDL_surface.c
Related: https://github.com/libsdl-org/SDL/issues/12844
> SDL_BlitSurfaceScaled(): Fix divisions by zero

- include/SDL3/SDL_haptic.h
See #12829 for information and motivation for this change. It wasn't much work to implement so here's a PR for it.
#12829
> Add and use typedefs SDL_HapticEffectFlags and SDL_HapticDirectionType

- src/video/wayland/SDL_waylandvideo.c
- src/video/x11/SDL_x11video.c
Closes https://github.com/libsdl-org/SDL/pull/12862
> Log information about Wayland environment detection

- include/SDL3/SDL_events.h
- src/dynapi/SDL_dynapi.sym
- src/dynapi/SDL_dynapi_overrides.h
- src/dynapi/SDL_dynapi_procs.h
- src/events/SDL_events.c
> events: Added SDL_GetEventDescription().

- src/joystick/hidapi/SDL_hidapi_switch.c
Cherry-picks https://github.com/libsdl-org/SDL/commit/ba88b6aa06f78ca7b5811efb1a50e76503deec10 to fix a rare issue on Windows where Switch controllers read incorrect stick calibration values after repeated connect/disconnect cycles.
Using the script linked in #12843, I was able to verify the fix with the changes from this PR. 0 instances of stick drift in nearly 200 cycles. Compared to the base SDL2 branch, which had 2 instances of stick drift in about 50 cycles.
#12843
> [Windows][SDL2] Switch controllers read incorrect stick calibration values after repeated connect/disconnect cycles (backport from SDL3)

- src/joystick/hidapi/SDL_hidapi_lg4ff.c
ref: https://github.com/sonik-br/lgff_wheel_adapter/blob/d97f7823154818e1b3edff6d51498a122c302728/pico_lgff_wheel_adapter/reports.h#L265-L310
Unlike the g25 and the g29, the g27 has the reverse gear state outside of the main button bit field. Capture that bit for button input.
> capture g27 shifter r input

- src/audio/vita/SDL_vitaaudio.c
> VITA: fix audio playback

- src/video/emscripten/SDL_emscriptenframebuffer.c
Backported from https://github.com/libsdl-org/SDL/pull/12970
> [emscripten] Remove reference to Module['createContext']

- src/joystick/SDL_joystick.c
- src/joystick/hidapi/SDL_hidapi_8bitdo.c
- src/joystick/usb_ids.h
add SN30 Pro, SF30 Pro, Pro 2.
Supported versions:
Pro 2 v3.06 and  above
SF30 Pro/SN30 Pro v2.05 and above
> add 8BitDo Controller

- src/gpu/vulkan/SDL_gpu_vulkan.c
Updates present wait semaphores to be indexed by swapchain image index instead of inflight frame number, to resolve Vulkan validation errors on potentially inappropriate semaphore reuse.
Reference: https://vulkan.lunarg.com/doc/view/1.4.313.0/windows/antora/guide/latest/swapchain_semaphore_reuse.html
> GPU Vulkan: fix for Swapchain Semaphore Reuse

- src/video/wayland/SDL_waylandmouse.c
Fixes the first part of #13003
> wayland: Check the cursor visibility flag when updating seat pointers

- src/joystick/hidapi/SDL_hidapi_gip.c
This adds support for the official Xbox One Chatpad attachment. I'm not 100% about the correctness of the SDL interfacing side, but the functionality all works fine from my testing.
> joystick: Add support for Xbox One Chatpad attachment

- src/video/cocoa/SDL_cocoaclipboard.m
Adjust Cocoa_SetClipboardData so that SetClipboardText text can be pasted outside SDL
---
Now the text copied can be pasted elsewhere (web/text editor, etc), otherwise it does nothing.
For the mime check, `SDL_IsTextMimeType` can be used as well, but it will match more things as it only looks for "text".
> MacOS: fix cocoa clipboard text

- docs/README-platforms.md
Change the platforms document to link to the actual N3DS article.
N/A
> Fix reference to nonexistent "README-3ds.md"

- src/events/SDL_events.c
- src/video/SDL_sysvideo.h
- src/video/SDL_video.c
- src/video/cocoa/SDL_cocoavideo.m
- src/video/wayland/SDL_waylandvideo.c
- src/video/windows/SDL_windowsvideo.c
- src/video/x11/SDL_x11video.c
Fixes https://github.com/libsdl-org/SDL/issues/12797
> Fixed rare crash trying to interrupt SDL_WaitEvent()

- android-project/app/proguard-rules.pro
- android-project/app/src/main/java/org/libsdl/app/SDLActivity.java
- src/core/android/SDL_android.c
Get preferred locales on android
#13071
> Android: Get preferred locales

- src/dialog/windows/SDL_windowsdialog.c
Advancing UTF-8 offset into UTF-16 string
#13097
> Windows: bugfix advancing UTF-8 length in UTF-16 string

- src/joystick/hidapi/SDL_hidapi_gip.c
This mostly fixes stylistic issues, but also fixes an issue with some controllers where an erroneous check would clear the DLI flag, offsetting the share button index so it wouldn't work.
I'm still in the process of validating some changes here, but I should be able to do that tomorrow.
> joystick: Several minor GIP fixes

- src/video/vita/SDL_vitavideo.c
- src/video/vita/SDL_vitavideo.h
https://github.com/libsdl-org/SDL/issues/13079
> VITA: support only fullscreen windows. Fixes #13079

- src/video/x11/SDL_x11window.c
XMonad ignores size hints and shrinks the client area to overlay borders on fixed-size windows, even if no borders were requested, resulting in the window client area being smaller than requested. Calling XResizeWindow after mapping seems to fix it, even though resizing fixed-size windows in this manner doesn't work on any other window manager.
Fixes #13180
> x11: Resize fixed-size windows after mapping on xmonad

- cmake/sdlchecks.cmake
- include/build_config/SDL_build_config.h.cmake
Like with #12199 this adds a few more definitions for private platforms
> More CMake definitions for private platforms

- src/joystick/hidapi/SDL_hidapi_switch.c
This is the SDL2 version of https://github.com/libsdl-org/SDL/pull/13217.
> Read Switch controller gyro/accel sensitivity coeffs (SDL2)

- src/joystick/hidapi/SDL_hidapi_8bitdo.c
Gathered correct IMU polling rate in wired mode for good gyro synchronization.
Wireless: different models had different amounts of Bluetooth packet loss.
USB_PRODUCT_8BITDO_ULTIMATE2_WIRELESS: Solid 120hz over bluetooth (note: only appears via).
USB_PRODUCT_8BITDO_PRO_2_BT: Lossy - 80-90hz registered.
SB_PRODUCT_8BITDO_SN30_PRO_BT & USB_PRODUCT_8BITDO_SN30_PRO_BT: Very Lossy - 60-90hz registered
> 8 bitdo polling rate corrections

- src/video/kmsdrm/SDL_kmsdrmvideo.c
Also cleaned up the code for consistency so it's easy to see memory leaks here.
> Fixed memory leaks in KMSDRM property handling

- src/joystick/hidapi/SDL_hidapi_8bitdo.c
> add 8BitDo Controller sensor_timestamp

- src/video/emscripten/SDL_emscriptenevents.c
This allows us to avoid browser mouse emulation for touches, since we provide our own anyhow.
The other option is to "prevent default" in the legacy touch event handlers we historically used, to tell the browser not to supply emulation, but we can't currently tell Emscripten to mark those handlers as not "passive," so as it stands they are unable to prevent default. Using Pointer Events bypasses this problem entirely.
Fixes #13161.
> emscripten: Move over to using Pointer Events for all mouse, pen, and touch.

- src/video/windows/SDL_windowswindow.c
The dark mode window code introduced in https://github.com/libsdl-org/SDL/pull/11543 passes the requested function's ordinal value to `SDL_LoadFunction`, and if the system doesn't implement those functions in uxtheme.dll, it will cause a crash because `SDL_LoadFunction` always expects the name to be a real string.
This swaps out the SDL_ library calls for native Windows ones, which matches some of the surrounding code and gracefully handles situations where a system reports itself as 17663 or newer, but doesn't implement one or more of the functions.
This was encountered by a couple of players running System Shock 2 Remastered on Linux Mint Cinnamon with Proton 7.0.6.
> windows: Fix crash on certain versions of Proton/Wine

- src/joystick/hidapi/SDL_hidapi_8bitdo.c
- src/joystick/usb_ids.h
> Add support for Pro3

- src/main/emscripten/SDL_sysmain_callbacks.c
- src/video/emscripten/SDL_emscriptenopengles.c
> emscripten: Respect SDL_HINT_MAIN_CALLBACK_RATE.

- src/audio/alsa/SDL_alsa_audio.c
This fills the `SDL_AudioSpec` struct being passed to the `SDL_AddAudioDevice()` call in `add_device()` with the data available from ALSA.
To get this data, the device being added has to be opened, and it's then closed immediately.
This fixes issue https://github.com/libsdl-org/SDL/issues/13315 affecting current MAME when it's run on SDL2 on ALSA (I added a workaround in MAME too, which I will probably remove now after this is merged as it's not needed anymore).
> SDL2: Fill the SDL_AudioSpec in add_device()

- src/joystick/hidapi/SDL_hidapi_sinput.c
This PR implements explicit device names for supported SInput devices.
> Implement SInput Device Namings

- src/gpu/vulkan/SDL_gpu_vulkan.c
In the file `src/gpu/vulkan/SDL_gpu_vulkan.c` there are two places where `renderer` is used after it has been freed:
<details><summary>Warning 1</summary>
<p>
```c
[ 47%] Building C object CMakeFiles/SDL3-shared.dir/src/gpu/vulkan/SDL_gpu_vulkan.c.o
/path/to/SDL/src/gpu/vulkan/SDL_gpu_vulkan.c:11726:9: warning: Use of memory after it is freed [clang-analyzer-unix.Malloc]
11726 |         SET_STRING_ERROR_AND_RETURN("Failed to initialize Vulkan!", NULL);
|         ^
/path/to/SDL/src/gpu/vulkan/SDL_gpu_vulkan.c:1262:47: note: expanded from macro 'SET_STRING_ERROR_AND_RETURN'
1262 | #define SET_STRING_ERROR_AND_RETURN(msg, ret) SET_ERROR_AND_RETURN("%s", msg, ret)
|                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
```
> Fix two use-after-free warnings in `SDL_gpu_vulkan.c`

- src/gpu/vulkan/SDL_gpu_vulkan.c
Doing more testing with c5edf4bd5b249848c771bd6c08bd3da945c70c2d, I noticed that there is a bit of lag when rendering a rather large number of frames to the hidden window, showing it, then quitting. The lag seemingly became worse as more frames were rendered to the hidden window before showing it. 
When skipping presentation due to the window being hidden, presentDataCount is not incremented on the command buffer, and subsequently the flag to clean up previously submitted command buffers will not be set as long as the window is hidden. This results in a lag spike when showing the window due to all previously submitted command buffers suddenly being cleaned up at once, and lag at shutdown due to an equivalent number of fences needing to be destroyed.
Add a flag to signal that the command …
> gpu: Clean up Vulkan command buffers when presentation is skipped

- src/core/linux/SDL_fcitx.c
Use the existing `SDL_GetExeName()`, available for all the UNIX platforms, in the internal `GetAppName()`; this has few advantanges:
- `SDL_GetExeName()` (and `SDL_GetAppID()` that builds on top of it) are used in various places already; since it caches the executable name, this may remove one extra read of the application name
- `SDL_GetExeName()` has a non-dummy implementation in more OSes than `GetAppName()`, thus providing a small improvement for this IME
As drive-by change: since `SDL_GetExeName()` provides a constant string, there is no more need to allocate a new string in `GetAppName()`, which is used as constant string anyway. Hence, return a constant string in `GetAppName()` too.
> ime: fcitx: use SDL_GetExeName() in GetAppName()

- src/video/wayland/SDL_waylandevents.c
> wayland: Cleanup and return if keymap allocation fails

- include/SDL3/SDL_power.h
> Fix typo in SDL_power doc comment

- android-project/app/src/main/java/org/libsdl/app/HIDDeviceBLESteamController.java
- android-project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
- android-project/app/src/main/java/org/libsdl/app/SDLActivity.java
better check to know if App is running on Chromebook.
(and also chromebook on AVD emulator)
From https://stackoverflow.com/questions/39784415/how-to-detect-programmatically-if-android-app-is-running-in-chrome-book-or-in
> Android: improve check to know if running on ChromeBook or emulator.

- android-project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
more simplification since min API supported is 21
following (https://github.com/libsdl-org/SDL/pull/13844 )
> Android: more simplification since min API supported is 21

- android-project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
make the intent always explicit / using setPackage
> Fixed bug #13849 - Intent always explicit

- src/render/vulkan/SDL_render_vulkan.c
- test/testyuv.c
Fixes https://github.com/libsdl-org/SDL/issues/13734
> Fixed Vulkan YUV texture update functions

- src/video/windows/SDL_windowsmodes.c
Fixes https://github.com/libsdl-org/SDL/issues/13233
> Fixed memory leak enumerating display modes on Windows

- include/SDL3/SDL_hints.h
- src/SDL_log.c
Fixes https://github.com/libsdl-org/SDL/issues/12275
> Added support for the DEBUG_INVOCATION environment variable

- examples/renderer/15-cliprect/cliprect.c
- src/video/SDL_surface.c
Fixes https://github.com/libsdl-org/SDL/issues/10953
Fixes https://github.com/libsdl-org/SDL/issues/12658
> Fixed jitter when doing a scaled blit to a surface with clipping set

- include/SDL3/SDL_render.h
- src/render/gpu/SDL_render_gpu.c
- src/render/vulkan/SDL_render_vulkan.c
Fixes https://github.com/libsdl-org/SDL/issues/13907
> Added SDL_PROP_TEXTURE_GPU_TEXTURE_POINTER

- src/video/emscripten/SDL_emscriptenevents.c
> Emscripten: Fix Emscripten_GetFocusedWindow

- src/video/emscripten/SDL_emscriptenevents.c
> Emscripten: Ensure drop functionality is the same as other platforms

- src/thread/SDL_thread.c
Fixes https://github.com/libsdl-org/SDL/issues/13886
> Fixed memory leak when using detached threads

- src/io/SDL_iostream.c
Fixes https://github.com/libsdl-org/SDL/issues/13116
Fixes https://github.com/libsdl-org/SDL/issues/13412
> Ignore errors flushing output on POSIX pipes

- .github/workflows/create-test-plan.py
The GitHub runners no longer have the needed SDK for this
> Removed UWP workflow from CI

- .github/workflows/create-test-plan.py
> ci: add macOS 26 job

- src/video/x11/SDL_x11toolkit.c
Hopefully this will fix #13989, this also cleans up some code.
> X11TK: Cleanups, reduce scaling factor if a font cant be found

- src/gpu/metal/SDL_gpu_metal.m
See https://github.com/libsdl-org/SDL/issues/14068
> Fix Metal 3D texture upload stride calculation

- src/render/psp/SDL_render_psp.c
> SDL_render_psp.c: Implemented working viewport support

- src/dialog/windows/SDL_windowsdialog.c
Replaces SetDefaultFolder with SetFolder
> Fix for #14072

- src/joystick/SDL_gamepad.c
See https://github.com/godotengine/godot/issues/110906, https://github.com/godotengine/godot/issues/110536#issuecomment-3298994611, https://github.com/godotengine/godot/pull/101260 and https://gist.github.com/geekley/5e6daf62d2e86b566c4886f20b604d21
This PR implements a blacklist of words that indicate that a joystick/gamepad should be ignored, similar to `initial_blacklist_devices` in `SDL_joystick.c`.
I'm not 100% sure having this list is desirable by SDL, so if it's not, please let me know. 😅 
None in this repository.
> Add blacklist words for joystick/gamepad names

- src/events/SDL_windowevents.c
- src/video/SDL_sysvideo.h
- src/video/SDL_video.c
- src/video/windows/SDL_windowsevents.c
- src/video/windows/SDL_windowswindow.c
- src/video/windows/SDL_windowswindow.h
- src/video/x11/SDL_x11window.c
Fixes https://github.com/libsdl-org/SDL/issues/12665
> Don't change the display of a window until it is mostly on the new one

- src/time/ngage/SDL_systime.cpp
Implement SDL_TimeToDateTime() for the Nokia N-Gage/Symbian S60v1  [sdl-ci-filter ngage]
Fixes #14047
> [N-Gage] Add SDL_TimeToDateTime() implementation
