libsdl-org/SDL

include/SDL3/SDL_stdinc.h
more `warning: identifier '_SDL_size_mul_overflow_builtin' is reserved because it starts with '_' followed by a capital letter`
=> Remove underscore for some SDL_ builtin function/macros

CMakeLists.txt, VisualC/pkg-support/cmake/sdl3-config.cmake, Xcode/SDL/pkg-support/resources/CMake/sdl3-config.cmake, cmake/sdl3.pc.in
This reverts parts of 9f2ca87
I *think* the SDL3 framework also supports both include styles: `#include "SDL.h"` and `#include <SDL3/SDL.h>`:
- The `-F SDL3.framework` will make sure `#include <SDL3/SDL.h>` works.
- The `INTERFACE_INCLUDE_DIRECTORIES` will make sure `#include "SDL.h"` works.
But once again: somebody with a mac, please verify.
=> cmake: add SDL3 to include path

include/SDL3/SDL_main_impl.h
I don't think there's any point in console_*main() for non-MSVC - I think it can't be called anyway now that SDL_main is header-only. So I renamed those functions to main() and wmain() and made them MSVC-only
For reference, MinGW (at least the version I tested) supports both main() and WinMain(), no matter if compiled with -mconsole or -mwindows (it seems to prefer main() over WinMain() if both are available, in both cases).
But when building with -municode, it needs wmain() or wWinMain(), so that case is now handled with wWinMain()
=> SDL_main for Win32: Get rid of console_*main, add wWinMain()

android-project/app/src/main/java/org/libsdl/app/SDLActivity.java
redo the PR in https://github.com/libsdl-org/SDL/pull/6959 in a simpler way
- inverse landscapeLeft and landscapeRight
- fix to match exactly Portrait (as it is contained in PortraitUpsideDown)
=> Br android orientation bug

src/render/SDL_yuv_sw.c
`swdata` is leaked in case of error.
None
=> Fix memory leak in SDL_SW_CreateYUVTexture

src/joystick/SDL_gamepad.c
`joysticks` is returned by SDL_GetGamepads , it shoud not be freed.
None
=> Fix use after free in SDL_GetGamepads

src/joystick/SDL_joystick.c
SDL_JoystickID is unsigned, 0 is invalid id.
=> Fix joystick instance id check

src/render/SDL_yuv_sw.c, src/video/SDL_surface.c, src/video/SDL_yuv.c, src/video/SDL_yuv_c.h
For SDL2 branch, we could back-port,  SDL_CalculateYUVSize() that checks for YUV size overflow.
=> SDL2: backport SDL_CalculateYUVSize() that checks for YUV size overflow

src/render/SDL_render.c, src/video/SDL_video.c, src/video/SDL_video_c.h
SDL_RenderSetVSync doesn't disable vsync for software renderers created with the SDL_RENDERER_PRESENTVSYNC flag
Attempt to fix: https://github.com/libsdl-org/SDL/issues/6816
not sure if this is the best fixes ..
@hkva please give a try !
=> Fixed bug #6816 - SDL_RenderSetVSync doesn't disable vsync for software renderer

src/video/wayland/SDL_waylanddatamanager.h, src/video/wayland/SDL_waylandevents.c
this resolves fixme's in wayland code. to give the correct SDL_Window to the Drag and drop API.
probably need also to apply to SDL2
=> Wayland / Drag and Drop: find the current window

docs/README-migration.md, include/SDL3/SDL_events.h, include/SDL3/SDL_video.h, src/video/SDL_sysvideo.h, src/video/SDL_video.c
Add SDL_WindowID type !
(no re-indentation, because this could be done afterward, when multiple replacement are done)
https://github.com/libsdl-org/SDL/issues/6955
=> Add SDL_WindowID type for SDL_Window id

src/video/wayland/SDL_waylandmouse.c
If a cursor can't be found (for example it's not defined in the user theme) SDL crashes with a segmentation fault.
With this PR, the default cursor is used if the chosen one wasn't found.
This change should be backported to SDL2.
=> wayland: Fallback to default cursor if chosen one wasn't found

src/video/cocoa/SDL_cocoamessagebox.m
MessageBoxes attached to a window in macOS should use modal APIs and not use a poll/sleep pattern on the main thread. Sleeping the main thread makes the NSWindow message loop sluggish and interferes with external applications that need to send messages to that window, such as VoiceOver.
- use [NSApplication runModalForWindow] / [NSApplication stopModalWithCode] APIs for the showAlert: implementation in SDL_cocoamessagebox.m
- unify the runtime paths around window-attached and application modal as much as possible
- Clean up #ifdef code in showAlert. It was subtly buggy, and the runtime detection of which beginSheetModalForWindow... selector to use should be sufficient.
https://github.com/libsdl-org/SDL/issues/6948
=> Fix For issue #6948

src/events/SDL_keyboard.c, src/events/SDL_keyboard_c.h, src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandevents_c.h
Modifier keys on Wayland can be remapped, latched/locked, and change the system modifier state on key release events instead of key down events, which the default SDL modifier handling code doesn't deal with correctly. This tracks and sets the modifier keys internally to deal with the plethora of various combinations that the system modifier state can be in and correctly reflects the actual system modifier state to SDL applications.
This fixes such cases as:
- Latching or locking modifiers (e.g. sticky keys).
- Handling the level 3 shift/AltGr/Mode modifier correctly, including remapping.
- Remapping capslock to shiftlock (caps:shiftlock), where it still sends the capslock scancode and keycode, but activates the shift modifier.
- Remapping numlock to capslock (caps:numlock), where …
=> wayland: Handle latched/locked and remapped modifiers

docs/README-migration.md, include/SDL3/SDL_syswm.h
You can enable and disable subsystems with SDL_ENABLE_SYSWM_*/SDL_DISABLE_SYSWM_* and you can disable the type forward declarations with SDL_DISABLE_SYSWM_*_TYPES
=> SDL_syswm.h provides the platform specific types by default again

src/video/SDL_blit_A.c
SDL2 Branch.
Fix computation of alpha in BlitRGBtoRGBPixelAlphaMMX
`(srcA * 255) >> 8` is approximate, wheras we want to keep the srcA value.
and it replaced by:
`(srcA * 256) >> 8`
#6990
=> Fixed bug #6990: fix computation of alpha in BlitRGBtoRGBPixelAlphaMMX

test/testautomation_pixels.c
Use truly invalid pixel format, so that test pixels pass
=> Fix testautomation_pixels using really invalid pixel format

test/testevdev.c
Configure with "-DSDL_LIBC=OFF" to get this configuration.
=> testevdev: cannot test evdev capabilities without linux input

include/SDL3/SDL_vulkan.h, src/dynapi/SDL_dynapi_procs.h, src/video/SDL_sysvideo.h, src/video/SDL_video.c, src/video/android/SDL_androidvulkan.c, src/video/android/SDL_androidvulkan.h, src/video/cocoa/SDL_cocoavulkan.h, src/video/cocoa/SDL_cocoavulkan.m, src/video/kmsdrm/SDL_kmsdrmvulkan.c, src/video/kmsdrm/SDL_kmsdrmvulkan.h, src/video/uikit/SDL_uikitvulkan.h, src/video/uikit/SDL_uikitvulkan.m, src/video/vivante/SDL_vivantevulkan.c, src/video/vivante/SDL_vivantevulkan.h, src/video/wayland/SDL_waylandvulkan.c, src/video/wayland/SDL_waylandvulkan.h, src/video/windows/SDL_windowsvulkan.c, src/video/windows/SDL_windowsvulkan.h, src/video/x11/SDL_x11vulkan.c, src/video/x11/SDL_x11vulkan.h, test/testvulkan.c
This patch removes the unused `window` parameter from SDL_Vulkan_GetInstanceExtensions and adds a call to SDL_Vulkan_LoadLibrary.
Before calling SDL_Vulkan_GetInstanceExtensions an app has to either:
1. Create a Vulkan-capable window **or**
2. Pass a NULL window but manually call SDL_Vulkan_LoadLibrary beforehand
None of the video backends actually use the supplied window, so I (and the other users in #6895) suggest it should go. With the window parameter gone, SDL_Vulkan_GetInstanceExtensions should call SDL_Vulkan_LoadLibrary since it's the first SDL_Vulkan-related function called in a typical SDL+Vulkan application.
**Edit**: I force-pushed and removed the call to SDL_Vulkan_LoadLibrary and replaced it with a documentation update.
https://github.com/libsdl-org/SDL/issues/6895
=> SDL_Vulkan_GetInstanceExtensions: Remove unused window parameter

CMakeLists.txt, cmake/GetGitRevisionDescription.cmake, cmake/GetGitRevisionDescription.cmake.in, include/SDL3/SDL.h, src/SDL.c, test/testver.c
This allows the build system (ninja/make/VS) to detect whether the current checkout git commit has changed. If so, SDL_revision.h will be updated.
- `#include <SDL3/SDL_revision.h>` is removed from `SDL3/SDL.h` to avoid a complete rebuild when checking out a different commit.
Before, all SDL sources would get recompiled.
Now only SDL.c is compiled, and SDL3 + all its dependencies are relinked.
- `GetGitRevisionDescription` ensures the generated build system (=make/ninja/vcxproj/xcodeproject) will run cmake when a different git commit has been checked out.
I fetched `GetGitRevisionDescription` from [rpavlik/cmake-modules](https://github.com/rpavlik/cmake-modules/blob/main/GetGitRevisionDescription.cmake). It's licensed under BSL-1.0.
I hope that's okay?
=> cmake: generate git hash using GetRevisionDescription CMake module

test/testautomation_main.c
It conflicts with the initialization of test common.
before it used SDL_VideoInit SDL_VideoQuit which weren't perturbated by SDL_Quit()
=> Remove one test that contains call of SDL_Quit() / SDL_Init() 

include/SDL3/SDL_oldnames.h
Add oldname entry: GetTicks64() is renamed GetTicks()
=> Add oldname entry: GetTicks64() is renamed GetTicks()

src/joystick/hidapi/SDL_hidapi_switch.c
Automatically select the correct stick calibration profile based on the magic bytes. 
Switch controllers are know to have drift issues. Often the joysticks are replaced and invalidates the factory calibration. However an user calibration profile exist and can be used to calibrate the sticks. 
Closes #4594
=> hidapi: switch: Add user stick calibration support

build-scripts/SDL_migration.cocci, build-scripts/rename_api.py, docs/README-migration.md
semantic patch for project migration
// - all function renaming (without parameter change) as in SDL_oldnames.h
// - remove SDL_WINDOW_SHOWN
// - migrate SDL_CreateRGB* and SDL_ConvertSurface* functions
=> Add SDL_migration.cocci for SDL2 to 3 migration

android-project/app/src/main/java/org/libsdl/app/SDLAudioManager.java
Fixed the work of SDL2 on Android older than 6.0.
Added a set of conditions to ensure the thing will work on Android older than API 23.
Since the commit https://github.com/libsdl-org/SDL/commit/741499dea777b98f6dee4479596f94ba02adbfdc the application won't boot on Android older than 6.0.
=> SDLAudioManager.java: Fixed the support for Android older than API 23

src/render/SDL_render.c, src/render/ps2/SDL_render_ps2.c
This PR solves some situations where the textures were not being rendered properly.
It was rendered:
And the expected is:
In order to fix it, I have changed the renderer strategy from `STQ` to `UV`, most probably there is a bug in the `gsKit` library in the `PS2DEV` toolchain.
If I'm able to find the bug I will revert the change, because STQ performs slightly better.
Cheers
=> [SDL3] PS2 Render Driver - Fix issue rendering textures

src/render/SDL_render.c, src/render/ps2/SDL_render_ps2.c
This PR solves some situations where the textures were not being rendered properly.
It was rendered:
And the expected is:
In order to fix it, I have changed the renderer strategy from `STQ` to `UV`, most probably there is a bug in the `gsKit` library in the `PS2DEV` toolchain.
If I'm able to find the bug I will revert the change, because STQ performs slightly better.
Cheers
=> [SDL2] PS2 Render Driver - Fix issue rendering textures

src/SDL_log.c
There was only 1 warning left when building SDL3, configured with `-DSDL_LIBC=OFF`:
```
/home/maarten/programming/SDL/src/SDL_log.c:73:20: warning: ‘SDL_priority_prefixes’ defined but not used [-Wunused-variable]
73 | static const char *SDL_priority_prefixes[SDL_NUM_LOG_PRIORITIES] = {
|                    ^~~~~~~~~~~~~~~~~~~~~
```
This pr fixes this by surrounding the variable with `#pragma GCC diagnostic ignored "-Wunused-variable"`
Fixes #6622
=> Fix last warning when building SDL with -DSDL_LIBC=OFF

src/joystick/windows/SDL_rawinputjoystick.c
The commit [#e8b1dfe](https://github.com/libsdl-org/SDL/commit/e8b1dfef9b6e581cdf1e219600b106ab9c84db25) fixed the issue #6767, which I have also met when using my FlyDigi Vader 2 Pro Controller in iOS (BlueTooth) mode. I find that there is a risk of segmentation fault related to `hat_map` in the commit: in [this line](https://github.com/libsdl-org/SDL/blob/e8b1dfef9b6e581cdf1e219600b106ab9c84db25/src/joystick/windows/SDL_rawinputjoystick.c#L1471), `hat_map[9]` may be accessed.
```
match_state = (match_state & ~HAT_MASK) | hat_map[state];
```
This PR appends `0` to `hat_map` for avoiding the segmentation fault and other unexpected behaviors.
=> Fixed the hat_map to avoid segmentation fault

src/video/wayland/SDL_waylandwindow.c
Perform a round trip when maximizing and restoring windows so the changes have already taken effect when the associated functions return.
Fixes the Wayland portion of #7070
=> wayland: Round trip when maximizing and restoring windows

src/video/wayland/SDL_waylandwindow.c
This reverts commit e35c3872dc6a8f7741baba8b786b202cef7503ac.
The bug turned out to be unrelated, so this should be reverted to restore behavior that matches other platforms.
=> Revert "wayland: Don't try to restore non-resizable windows"

src/main/ps2/SDL_ps2_main.c
This PR improves the `PS2 main` driver, it now supports:
- `exFat` format devices
- `HDD` devices
- `CDFS` devices
Everything now is done, in the `ps2_driver` library instead to be here in the SDL
Cheers
=> [SDL2] PS2 Main - Use filesystem drivers

src/core/ps2/SDL_ps2.c
This PR improves the `PS2 core` driver, it now supports:
- `exFat` format devices
- `HDD` devices
- `CDFS` devices
Everything now is done, in the `ps2_driver` library instead to be here in the SDL
Cheers
=> [SDL3] PS2 Core - Use filesystem drivers

CMakeLists.txt, cmake/sdl3.pc.in
By using `${pcfiledir}`, the installed `sdl3.pc` is fully relocatable.
So no more fix-ups to the installed sdl3.pc post-installation, or overriding the prefix through aguments (`--define-variable=prefix=/new/prefix`)
This requires a pkg-config that supports `${pcfiledir}`.
Freedesktop's pkg-config and pkgconf support this.
Fixes https://github.com/libsdl-org/SDL/issues/3516 for good
=> cmake: make sdl3.pc relocatable

include/SDL3/SDL_video.h, src/render/software/SDL_render_sw.c, src/video/SDL_video.c, src/video/dummy/SDL_nullframebuffer.c, src/video/emscripten/SDL_emscriptenframebuffer.c, src/video/n3ds/SDL_n3dsframebuffer.c, src/video/ngage/SDL_ngageframebuffer.cpp, src/video/offscreen/SDL_offscreenframebuffer.c, src/video/riscos/SDL_riscosframebuffer.c, src/video/windows/SDL_windowsframebuffer.c, src/video/x11/SDL_x11framebuffer.c, test/testdrawchessboard.c
Addresses the bug reported here https://discourse.libsdl.org/t/how-do-i-bugfix-surface-size-in-windows-high-dpi/41647 so if SDL is in DPI aware mode, `SDL_GetWindowSurface` returns a surface of the same size as `SDL_GetWindowSizeInPixels` instead of `SDL_GetWindowSize` (points).
Also clarified in the docs that `SDL_UpdateWindowSurfaceRects` takes rects in units of pixels.
I've tested this on macOS 10.15, Win 11, and Ubuntu 22.10 / Wayland.
This PR is a bit invasive because all `SDL_<backend>_CreateWindowFramebuffer` backend functions need to be updated to switch from `window->w` or `SDL_GetWindowSize` to `SDL_GetWindowSizeInPixels`. But, I think it's worth doing as a correctness fix - assuming `window->w`/`SDL_GetWindowSize` is pixels is wrong with our highdpi design.
I'm not set up to …
=> Make SDL_GetWindowSurface HighDPI aware

src/audio/SDL_audio.c
The libsamplerate library provides 5 different converter types, but only 3 of them (i.e. the SRC_SINC_* converters) can be set through SDL's API. In my projects I need fastest-possible on-the-fly conversion of audio samples and libsamplerate's SRC_LINEAR converter fits this purpose quite well. Please make it possible to select this (and possibly even SRC_ZERO_ORDER_HOLD) through SDL's API.
Fixes #6998
=> add support for libsamplerate's "linear" resampling mode

src/video/wayland/SDL_waylandkeyboard.c
This mimics the behavior of the other platforms.
This change should be backported to SDL2.
=> wayland: Set `APPLICATION` scancode name to `Menu`

src/hidapi/windows/hid.c
Changes the blacklist logic to treat a vendor ID with product ID of 0x0000 to be a full vendor blacklist and adds Konami Amusement to the blacklist to handle their controllers, all of which cause hanging on enumeration.
#7118
=> Include Konami Amusement Controllers in HIDAPI Blacklist

src/render/opengl/SDL_render_gl.c, src/render/opengles/SDL_render_gles.c
Hello! I noticed that OpenGL has always supported the Min/Max blend operations and OpenGL ES supports them through an extension (https://registry.khronos.org/OpenGL/extensions/EXT/EXT_blend_minmax.txt; GL ES 3.0 makes this support core). I'd like to add this support to SDL2.
I think this is a reasonable addition because it doesn't extend the render API, but rather makes its support more complete.
Thank you for your time and work on the project!
> The GL_MIN, and GL_MAX equations do not use the source or destination factors, only the source and destination colors. (https://registry.khronos.org/OpenGL-Refpages/gl4/html/glBlendEquation.xhtml)
In OpenGL, these operations effectively use blend factors of ONE, but I think that returning that the blend mode is unsupported when non-ONE blend …
=> Support MIN/MAX blend on OpenGL + ES

include/SDL3/SDL_atomic.h
inline assembly compatible gcc/clang.
=> SDL_CPUPauseInstruction RISCV-64 version proposal.

src/video/SDL_video.c
When moving exclusive fullscreen windows to another display, `SDL_UpdateFullscreenMode()` may kick the window out of fullscreen if the display to which it was moved doesn't support the window's requested video mode. This can happen when, for example, moving a native resolution, exclusive fullscreen window from a 4k display to a 1080p display. Additionally, the resulting window will be resized as though it were still fullscreen, which can result in a window larger than the usable desktop bounds.
Two parts to the fix:
- `SDL_UpdateFullscreenMode()` returns a success code even when it can't find a matching video mode and the fullscreen request fails; modify it to return an error on failure to find a compatible display mode.
- Clear the fullscreen flag and skip the resize of the moved window …
=> video: Don't resize fullscreen windows when moved to a display that doesn't support the requested video mode

src/render/opengl/SDL_render_gl.c, src/render/opengles/SDL_render_gles.c, src/render/opengles2/SDL_render_gles2.c
A small followup to my last PR [edit: linked here #7122 ]. I didn't initially realize that there were separate opengles and opengles2 render drivers. Thanks for letting me know.
Since min/max blending didn't become core until OpenGL ES 3, the capability checks are still needed. I added a bool to the renderer data struct. I placed it somewhat arbitrarily next to another bool, in a new cluster of declarations.
=> Min/Max blending for OpenGL ES 2

VisualC/SDL/SDL.vcxproj
The Visual Studio project for SDL3 uses search paths relative to the solution file, meaning that they are incorrect if you try to build the project from inside a different solution. The solution is to change the paths to be relative to the project file instead.
Fixes #7139
=> Change the Visual Studio project search paths to look relative to the project, not the solution.

android-project/app/src/main/java/org/libsdl/app/SDLActivity.java, android-project/app/src/main/java/org/libsdl/app/SDLSurface.java, src/core/android/SDL_android.c, src/video/android/SDL_androidvideo.c, src/video/android/SDL_androidvideo.h
There is the "density" fields which seems ok to use.
https://github.com/libsdl-org/SDL/issues/7149
Not yet binded to SDL_DisplayMode, since it hasn't the scale field
density is: 
> The logical density of the display. This is a scaling factor for the Density Independent Pixel unit, where one DIP is one pixel 
> on an approximately 160 dpi screen (for example a 240x320, 1.5"x2" screen), providing the baseline of the system's display. 
> Thus on a 160dpi screen this density value will be 1; on a 120 dpi screen it would be .75; etc.
> 
> This value does not exactly follow the real screen size (as given by [xdpi](https://developer.android.com/reference/android/util/DisplayMetrics#xdpi) and [ydpi](https://developer.android.com/reference/android/util/DisplayMetrics#ydpi)), 
> but rather is used …
=> Android get the display Density

src/video/SDL_video.c
Previously it returned a scale value of zero when creating a window with the `SDL_WINDOW_FULLSCREEN` flag set, which caused problems if anything used it without checking for a valid value. Make sure the scale is always set to some valid, non-zero value.
=> video: Ensure that the closest returned video mode match always has a valid scale value

include/SDL_atomic.h
Update #pragma aux to not use hardcoded instruction bytes
Appropriate CPU directive can be used in #pragma aux that not necessary to hardcode instruction bytes
=> Update #pragma aux for Open Watcom

src/video/wayland/SDL_waylandmouse.c, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
- Set the desktop display scale
- Exclusive fullscreen modes all have a scale of 1.0, so don't add the scaled desktop mode to the list.
=> wayland: Set the display scale for video modes

src/video/wayland/SDL_waylandvideo.c
Remove some duplicate code that was left behind when rearranging things during the new high-DPI support work.
=> wayland: Remove duplicate video init code

src/video/SDL_video.c
After successfully entering fullscreen, send the new fullscreen window dimensions in screen coordinates, not pixels, to avoid a unit mismatch.
=> video: Send the new fullscreen size in screen coordinates

src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandvideo.h, src/video/wayland/SDL_waylandwindow.c
Fixes the Wayland backend to report the desktop mode dimensions in pixels instead of screen units, adjusts enumerated fullscreen resolutions to use the correct pixel values and scaling, and changes the Wayland backend `SDL_GetDisplayBounds()` function to return screen coordinates instead of the desktop mode in pixels.
=> wayland: Correct mode values to use pixels instead of screen units

src/video/cocoa/SDL_cocoamodes.m
Previously they were discarded because SDL didn't expose enough information for apps to differentiate between a low-dpi and high-dpi mode which had the same size in DPI-scaled points (#3025 has some discussion about that). Now the information is available in SDL_DisplayMode.
I'm not to sure how useful this change is in practice, so I wonder if anyone else has opinions about it.
Fixes #3025.
=> macOS: include @1x (low-dpi) display modes with the same point-size as @2x (high-dpi) modes

src/video/cocoa/SDL_cocoaevents.m, src/video/cocoa/SDL_cocoamodes.m, src/video/cocoa/SDL_cocoawindow.m
SDL only supports macOS 10.9+ as of last year (and some code has since been committed which won't run on 10.7 or 10.8). This change cleans up some dead code which used to be needed for those two older releases.
None.
=> macOS: remove obsolete 10.7 and 10.8-specific code.

src/video/cocoa/SDL_cocoamessagebox.m
SDL2 MessageBoxes on macOS have broken VoiceOver support (#6948), this change fixes it. It was already merged into the main branch via #6991.
SDL2 officially dropped support for pre-10.9 macOS systems last year, but this might be the first change to SDL2 which removes runtime code support for that. If it's at all important to keep we can change this commit a bit to do so.
#6948
=> SDL2 backport of macOS messagebox fix (#6991)

src/video/cocoa/SDL_cocoawindow.m
Code that referenced OpenGL access was unprotected with defines to determine whether OpenGL is enabled.
Added #if checks for SDL_VIDEO_OPENGL around code that triggered compiler errors or warnings.
=> Fixes for building on Mac with OpenGL disabled.

src/video/wayland/SDL_waylandwindow.c
The event is de-duplicated internally, so a check in the Wayland backend is unnecessary.
=> wayland: Send a pixel size change event when the drawable size changes

src/video/uikit/SDL_uikitmodes.m
The display scale of other display modes were fixed in my previous PR, but I missed this line in that commit.
None.
=> iOS: fix the desktop display mode's display scale property.

build-scripts/SDL_migration.cocci
Update the migration script, so that:
`SDL_DisplayMode.w` or `h` gets replaced by `screen_w / display_scale` or `screen_h / display_scale`
=> migration: replace SDL_DisplayMode w and h

src/video/SDL_video.c
it used to be the display_index. but this isn't exposed anymore.
so this should be DisplayId
=> When coordinate is undefined, it can contains the display id

include/SDL3/SDL_assert.h, src/video/android/SDL_androidvideo.c
With these fixes my sample Android app runs properly:
- Ensure there is not garbage values in `current_mode`.
- On my device, hitting the `SDL_assert` will terminate the app; unlike with `assert(0)` from `assert.h` Android Studio triggers the breakpoint as expected.
- N/A
=> Fixes for Android builds

src/video/SDL_video.c
If the window was fully enclosed, GetDisplayForRect() would return the index of the display ID in the array instead of the display ID itself. Return the display ID itself.
=> video: Return the display ID when the window is fully enclosed

src/video/SDL_video.c
When adding a display, traverse the list of added fullscreen modes and ensure the display ID is set to its final, valid value, or the modes will have an invalid ID if they were added before calling SDL_AddVideoDisplay().
=> video: Set the ID of fullscreen modes when adding a display

src/video/cocoa/SDL_cocoametalview.m
On macOS, the internal drawable size of a Metal layer was being computed before the layer's view was attached to the window's content view, and wasn't being recomputed after attaching until another resize event in SDL.
In practice this meant that the pixel size of the layer wasn't always right in mixed-density multi display setups depending on which display the window was created in.
In SDL2 this also affected `SDL_Metal_GetDrawableSize`. This should be backported to SDL2 after merging.
Fixes #7215
=> macOS: fix initial Metal drawable size in certain multi-display setups

src/video/SDL_video.c
The C specification states that passing a size of 0 to functions like memcpy is valid, but even if the size is 0 and the function is essentially a no-op, the result when passing any invalid pointers is considered undefined behavior. Don't rely on undefined behavior when copying the display or mode lists.
=> video: Don't rely on memcpy undefined behavior

src/video/SDL_video.c, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
Fixes up Wayland to work with the new video core changes. The patch is fairly large, however, a lot of it is deleted code that is no longer needed and little has changed in the way of functionality.  Most of the work is in the window sizing code, which no longer needs to short-circuit the video core event deduplication code, and is actually a bit simpler now. Some bugs that testing the new code shook out have been addressed as well.
A small change is needed in the video core for Wayland: as Wayland windows don't really have a concept of being minimized (minimization can be requested, but what actually happens to the window is implementation defined, and no event is sent to the application to let it know that it was minimized via the window decorations or desktop shortcut keys), the logic …
=> Wayland work for the video core changes

src/events/SDL_mouse.c
Changing the mouse cursor isn't cheap on some platforms, so this turns multiple calls to `SDL_SetCursor()` with the same cursor into a no-op.
Dear ImGui sets the mouse cursor every frame (downside of being an immediate mode GUI), and due to the specifics of how SDL2 handles mouse cursor changes on macOS, this has a large impact on event polling performance. Sometimes it makes the event polling loop take over a millisecond!
This mostly fixes the issue. Calling `SDL_SetCursor()` with a different cursor will still be expensive, but calling it again (next frame or whenever) with the same cursor returns immediately.
Fixes issue #7151 for SDL 2
https://github.com/libsdl-org/SDL/issues/7151
=> [SDL2]: Fix #7151: Setting the same mouse cursor twice is a no-op

src/events/SDL_mouse.c, src/video/cocoa/SDL_cocoamouse.m, src/video/cocoa/SDL_cocoawindow.m
Currently, changing the mouse cursor on macOS is very slow. It can cause the next `SDL_PollEvent()` loop to take over a millisecond! Unfortunately, some libraries (like Dear ImGui) call `SDL_SetCursor()` every single frame, which can cause stuttering if the long event polling loop causes a vsync miss.
This PR will give SDL3 applications that use Dear ImGui (whenever it gets an SDL3 backend) a decent performance boost.
This PR does 2 things:
1) Multiple calls to `SDL_SetCursor()` with the same cursor is a no-op
2) When the cursor really does change, increase performance by calling `[NSCursor set]` instead of invalidating the Cocoa cursor rects.
Since `[NSCursor set]` changes the cursor for the entire screen, this PR checks to see if the mouse has gone outside the window or if the window …
=> [SDL3] macOS SetCursor performance fix (fixes #7151)

src/video/x11/SDL_x11modes.c
The dot clock value in the Xrandr mode struct can be large enough to overflow a 32-bit integer if multiplied by 100. Perform the calculation using doubles to avoid overflow and precision issues before casting the final value to float.
Should fix #7260
=> x11: Use double precision to calculate the refresh rate

src/audio/emscripten/SDL_emscriptenaudio.c, src/video/SDL_video.c
`EM_ASM_` and `EM_ASM_INT_V` are calls that have been deprecated for a long time.
Since the return value isn't used for the call to `EM_ASM_`, it can be replaced with `EM_ASM`.
`EM_ASM_INT_V` is now (for the last few years) `EM_ASM_INT`.
cc: @sbc100 @kripken 
This is related to taking another run at fixing https://github.com/emscripten-core/emscripten/pull/9874
=> emscripten: Update deprecated calls to EM_ASM*.

src/video/SDL_video.c, src/video/x11/SDL_x11window.c
Fixes up the fullscreen placement mechanism so that macOS, Win32 and X11 (real Xorg and XWayland) place exclusive fullscreen window on the proper displays.
This ends up splitting the display retrieval functions into one that returns the explicit display for fullscreen windows over all else and another that works strictly on position for when a window is moved, as Macs and Windows need the former to correctly position exclusive fullscreen windows. A small X11 fix is also needed, as both real Xorg and XWayland need the window to actually be moved to the display where it's being made fullscreen for it to appear on the correct display.
=> Fixes for Mac/X11/Win32 fullscreen window placement

src/audio/psp/SDL_pspaudio.c
This PR is solving audio issues with frequencies different than 44100 KHz.
There was a [commit](https://github.com/libsdl-org/SDL/commit/5d07c03613cc25ae1564b34408033266c50a0d23) trying to fix an issue in the driver when surround was used, and this one also introduced this issue.
With this PR all the scenarios should be covered properly.
=> [PSP] [SDL2] Audio Driver - Fix audio for `freq != 4100`

src/audio/psp/SDL_pspaudio.c
This PR is solving audio issues with frequencies different than 44100 KHz.
There was a [commit](https://github.com/libsdl-org/SDL/commit/5d07c03613cc25ae1564b34408033266c50a0d23) trying to fix an issue in the driver when surround was used, and this one also introduced this issue.
With this PR all the scenarios should be covered properly.
=> [PSP] [SDL3] Audio Driver - Fix audio for `freq != 4100`

include/SDL3/SDL_audio.h, include/SDL3/SDL_gamepad.h, include/SDL3/SDL_joystick.h, include/SDL3/SDL_keyboard.h, include/SDL3/SDL_locale.h, include/SDL3/SDL_main.h, include/SDL3/SDL_metal.h, include/SDL3/SDL_mutex.h, include/SDL3/SDL_render.h, include/SDL3/SDL_shape.h, include/SDL3/SDL_stdinc.h, include/SDL3/SDL_surface.h, include/SDL3/SDL_system.h, include/SDL3/SDL_thread.h, include/SDL3/SDL_touch.h, include/SDL3/SDL_video.h
* Add missing \returns, change "return" to "returns" to have same naming
=> Add missing \returns, change "return" to "returns" to have same naming

include/SDL_stdinc.h
Currently if a project has already defined _USE_MATH_DEFINES for other purposes, inclusion of SDL_stdinc.h will error with a macro redefinition error.  This guards against that error while still retaining the functionality.
No existing issue
=> Guard against _USE_MATH_DEFINES redefinition

src/events/SDL_mouse.c
Fixed bug #7302 - Memory 'leak' in SDL_SetMouseSystemScale()
=> Fixed bug #7302 - Memory 'leak' in SDL_SetMouseSystemScale()

test/testwm.c
Previously, only the modes for the window's current display were listed.
To be able to test https://github.com/libsdl-org/SDL/pull/7317 , it sounds like we want to list all modes of all displays.
=> testwm.c: show all modes of all displays in the on-screen list

src/video/SDL_sysvideo.h, src/video/SDL_video.c, src/video/cocoa/SDL_cocoawindow.m, src/video/kmsdrm/SDL_kmsdrmvulkan.c, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandwindow.c
This set of patches, along with some previous work, allows for moving exclusive fullscreen windows between displays with proper sizing and mode selection. When an exclusive fullscreen mode is chosen for the window, it is stored in the window properties as the 'desired mode', and when an application requests to enter fullscreen, it is initially set as the window's fullscreen mode and the window will be placed on the display specified by it. If an exclusive fullscreen window is then moved, an attempt to find a matching mode on the new display will be made and, if one is found, the window on the new display will use the closest match mode. If none exists, it will become desktop fullscreen. If the window is again moved, the process will repeat and attempt to find a mode that matches the …
=> Handle moving exclusive fullscreen windows between displays

.github/workflows/vita.yml
Cache manually downloaded vita dependencies.
This (hopefully) avoids errors like https://github.com/libsdl-org/SDL/actions/runs/4205890858/jobs/7298627144
```
Connecting to github.com (192.30.255.113:443)
Connecting to objects.githubusercontent.com (185.199.110.133:443)
wget: server returned error: HTTP/1.1 503 Egress is over the account limit.
```
https://github.com/libsdl-org/SDL/pull/7332
=> ci: cache PVR_PSP2 and gl4es4vita

.github/workflows/haiku.yml, CMakeLists.txt, cmake/SDL3Config.cmake.in, cmake/test/CMakeLists.txt, docs/README-cmake.md, test/CMakeLists.txt
Introduce a `SDL3::SDL3-shared` CMake target that will always represent a shared SDL library.
`SDL3::SDL3-static` will always be a static SDL library.
Then, `SDL3::SDL3` will be one of both.
There are now 5 components available:
```cmake
find_package(SDL3 REQUIRED CONFIG COMPONENTS Headers)     # for SDL3::Headers
find_package(SDL3 REQUIRED CONFIG COMPONENTS SDL3-shared) # for SDL3::SDL3-shared
find_package(SDL3 REQUIRED CONFIG COMPONENTS SDL3-static) # for SDL3::SDL3-static
find_package(SDL3 REQUIRED CONFIG COMPONENTS SDL3)        # for SDL3::SDL3 (same as SDL3::SDL3-shared or SDL3::SDL3-static)
find_package(SDL3 REQUIRED CONFIG COMPONENTS SDL3_test)   # for SDL3::SDL3_test
```
This change allows users to declare what SDL library they want to link to without ambiguity.
A default …
=> cmake: SDL3-shared target will always be a shared target

src/video/SDL_sysvideo.h, src/video/SDL_video.c, src/video/cocoa/SDL_cocoawindow.h, src/video/cocoa/SDL_cocoawindow.m, src/video/haiku/SDL_bvideo.cc, src/video/haiku/SDL_bwindow.cc, src/video/haiku/SDL_bwindow.h, src/video/kmsdrm/SDL_kmsdrmvideo.c, src/video/kmsdrm/SDL_kmsdrmvideo.h, src/video/psp/SDL_pspvideo.c, src/video/psp/SDL_pspvideo.h, src/video/raspberry/SDL_rpivideo.c, src/video/raspberry/SDL_rpivideo.h, src/video/vita/SDL_vitavideo.c, src/video/vita/SDL_vitavideo.h, src/video/windows/SDL_windowswindow.c, src/video/windows/SDL_windowswindow.h, src/video/x11/SDL_x11window.c, src/video/x11/SDL_x11window.h
As described in the issue, when `SDL_SetWindowIcon` fails, it does so silently. This PR changes:
1. The signature of the function so that it return `0` on success or an integer on error
2. Calls `SDL_GetError` in order to report what when wrong while trying to set the Window's Icon.
Calling this function on a system which does not support setting a window's icon (or it is meaningless to do so), will always return `SDL_UNSUPPORTED`.
Closes #1473
=> [SDL3] SDL_SetWindowIcon now reports errors.

src/video/x11/SDL_x11window.c
When a window is maximized, a call to `SDL_SetWindowSize` will fail to resize the window with X11 (and KDE at least).
Thep orblem is that `window->w` and `window->h` are modified to take the requested size into account and GL renderer uses this new size to draw resulting in image being located in lower left corner.
This bug exists in SDL2 and SDL3 (SDL1.2 not tested).
A backport would be great.
A test case can be found here: https://gist.github.com/lephilousophe/33936ede1631e1d237927f1233365b42
It compiles with SDL2 and 3.
=> Fix window size in X11 when window manager refuses to resize

src/video/x11/SDL_x11mouse.c
When XI2 was available at build time but is not available at runtime, GetGlobalMouseState will return a static mouse position. This patch fixes this.
=> Fix GetGlobalMouseState when xi2 is not available at runtime

src/video/x11/SDL_x11modes.c, src/video/x11/SDL_x11shape.c, src/video/x11/SDL_x11xinput2.c
These warnings showed up when building with:
- `-DSDL_X11_XSHAPE=OFF`
- `-DSDL_X11_XRANDR=OFF`
- `-DSDL_X11_XINPUT2=OFF`
=> Fix a few -Wunused-function/-Wunused-variable warnings

src/video/windows/SDL_windowsopengles.c
It's legitimate to have other contexts and keep using EGL.
=> windows/gles: do not unload EGL when context is destroyed

src/video/SDL_video.c, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h, src/video/windows/SDL_windowsevents.c, src/video/windows/SDL_windowswindow.c, src/video/windows/SDL_windowswindow.h
Use `SDL_UpdateFullscreenMode()` for repositioning desktop fullscreen windows to handle cases where the target display changed the video mode and/or already has a fullscreen window on it.
Additionally, update the window's display ID when setting the position programmatically so it remains in sync with the current window position, even if the move event is deduplicated.
=> video: Window placement fixes

src/video/raspberry/SDL_rpivideo.c
Found by running build-scripts/SDL_migration.cocci on SDL's source tree.
=> raspberry: SDL_DisplayMode's w/h members have been renamed to screen_w/screen_h

src/video/x11/SDL_x11mouse.h, src/video/x11/SDL_x11window.c, src/video/x11/SDL_x11xinput2.c
Passing True for owner_events in the XGrabPointer call makes all XI_RawMotion events appear in the queue twice, with the only difference between them being the value of XGenericEventCookie::cookie. These have always been filtered out by a check in the XI_RawMotion handler, however with a mouse that polls at more than 1 kHz frequency, there also exist legitimate events that appear indistinguishable from these duplicated events. These must not be filtered out, otherwise the pointer may move at an inconsistent speed, appearing like a bad pointer acceleration implementation.
Change owner_events to False in the XGrabPointer and remove the duplicate event detection code to fix this.
=> Fix wonky rawinput mouse speed with 8kHz mice on X11

include/SDL3/SDL_stdinc.h, src/stdlib/SDL_iconv.c
Before this, the function could not be used on buffers, as it would not account for the zero-termination unless it was included in the input. That makes it extremely error-prone to use.
The output from `SDL_iconv_string()` is prone to generate Valgrind warnings when used on buffers where the input buffer and the provided buffer length does not include a zero-terminator.
This change always accounts for a zt when allocating memory, and unconditionally writes one to the output before returning. 
Since existing SDL code that calls this with `strlen(s)+1` or similar continues to work as before after this change, I did not bother to try and 'adjust' any callsites.
```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>
int main(int argc, …
```
=> Always allocate and write zt to output of SDL_iconv_string()

src/cpuinfo/SDL_cpuinfo.c
using native system_info's api.
=> SDL_GetSystemRAM completion for Haiku system.

test/testautomation_audio.c, test/testautomation_pixels.c
=> testautomation_pixels/audio: use SDL_arraysize and fix warnings

src/core/linux/SDL_evdev_kbd.c
keymap can change over time, caching the keymap causes wrong keys returned when user changes keymap during runtime
=> evdev_kbd: Use current keymap

CMakeLists.txt, VisualC/pkg-support/cmake/sdl3-config.cmake, Xcode/SDL/pkg-support/resources/CMake/sdl3-config.cmake
With this change, CMake will detect and block linking to SDL2 and SDL3 simultaneously.
(SDL2 will need a similar change)
The following trivial CMake script will fail to configure:
```cmake
cmake_minimum_required(VERSION 3.25)
project(test_compatible_interface_properties C)
find_package(SDL2 REQUIRED CONFIG)
find_package(SDL3 REQUIRED CONFIG)
file(WRITE main.c [[
#include "SDL.h"
int main(int argc, char *argv[]) {
SDL_Init(SDL_INIT_EVERYTHING);
SDL_Quit();
return 0;
}
]])
add_executable(main main.c)
target_link_libraries(main PRIVATE SDL2::SDL2 SDL3::SDL3)
```
The error is:
```
-- Configuring done
CMake Error: The INTERFACE_SDL_VERSION property of "SDL3::SDL3-shared" does
not agree with the value of SDL_VERSION already determined
for "main".
-- Generating done
CMake Generate step failed. …
```
=> cmake: use compatible interface properties to disallow linking to a different version of SDL

include/SDL3/SDL_events.h, src/events/SDL_dropevents.c, src/events/SDL_dropevents_c.h, src/video/cocoa/SDL_cocoawindow.m, src/video/wayland/SDL_waylandevents.c, src/video/x11/SDL_x11events.c, test/testdropfile.c
Some start to send event of position while doing a drag n drop:
(see https://github.com/libsdl-org/SDL/issues/5292 )
x11:
- doesn't report the filename. (is it possible?)
wayland: 
- doesn't report the window (original flaw for all drag and drop) (solved with https://github.com/libsdl-org/SDL/pull/6980)
=> Add Drag and drop position, for x11  wayland and macosx

src/test/SDL_test_common.c, src/video/wayland/SDL_waylandwindow.c
Sets the scale factor correctly for fullscreen windows when the dimensions match the desktop size and integer scaling is used, and fixes the test framework so it sets valid fullscreen width/height values.
Fixes #7418
=> SDL2 Wayland Fullscreen Fixes

CMakeLists.txt, src/core/linux/SDL_system_theme.c, src/core/linux/SDL_system_theme.h, src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandvideo.c, src/video/x11/SDL_x11events.c, src/video/x11/SDL_x11video.c
This PR adds support for the color scheme part (`org.freedesktop.appearance`) of the `org.freedesktop.portal.Settings` portal for linux, with the interfaces added in #7416.
Tested on GNOME (both wayland and xwayland).
The portal implements "dark" and "light" preferences, as well as "no preference".
This PR maps the "no preference" to `SDL_SYSTEM_THEME_UNKNOWN`. Is this the correct choice?
The `SDL_SystemTheme_PumpEvents` part is taken straight from `SDL_Fcitx_PumpEvents`, and `SDL_IBus_PumpEvents` implements a similar one. Should this function be provided by `SDL_dbus`?
=> Add portal interface to support `SDL_GetSystemTheme` in linux

src/audio/SDL_audiocvt.c, test/testautomation_audio.c
SDL_ResampleAudio was using floating point values in its calculation. Because larger float values have lower absolute precision, this causes the algorithm to produce distortion when resampling audio data. Previously a workaround was added for x64 targets that reverts to using double, but it did not fix the problem for x86 targets.
This PR rewrites the function to use integer arithmetics when possible to improve both the precision and speed of the algorithm. A unit test is also added to test the signal-to-noise ratio and maximum error of the function.
The unit test shows that the fix has better signal-to-noise ratio and maximum error compared to both using float and double. The results on Windows 10 x64 for the 50 s 44100 Hz -> 48000 Hz conversion are as follows:
| Algorithm | …
=> Uses integer arithmetics in SDL_ResampleAudio to fix distortion

src/audio/SDL_audiocvt.c, test/testautomation_audio.c
This is #7435 rebased on and adjusted to the 2.26.x branch.
The unit test results on Windows 10 x64 for the 50 s 44100 Hz -> 48000 Hz conversion are as follows:
| Algorithm | Signal-to-noise (dB) | Maximum error | Time elapsed (s) |
|------------|------------------------|------------------|-------------------|
| Float         | 20.243176                 | 1.001052           | 0.247096             |
| Double     | 24.793083                 | 0.058135           | 0.303199             |
| Integer     | 61.306635                 | 0.002269           | 0.201917             |
The current fix has the best signal-to-noise ratio, maximum error, and elapsed time.
Fixes https://github.com/libsdl-org/SDL_mixer/issues/466.
=> Uses integer arithmetics in SDL_ResampleAudio to fix distortion (2.26.x branch)

build-scripts/androidbuildlibs.sh
This script relies on string indexes in parameter expansions, which aren't suppored by /bin/sh (e.g. dash).
Based on a patch by Roflcopter4:
https://github.com/joncampbell123/dosbox-x/pull/3850
=> Specify bash for androidbuildlibs.sh

docs/README-migration.md, include/SDL3/SDL_video.h, src/dynapi/SDL_dynapi.sym, src/dynapi/SDL_dynapi_overrides.h, src/dynapi/SDL_dynapi_procs.h, src/events/SDL_windowevents.c, src/video/SDL_sysvideo.h, src/video/SDL_video.c, src/video/cocoa/SDL_cocoavideo.m, src/video/cocoa/SDL_cocoawindow.h, src/video/cocoa/SDL_cocoawindow.m, src/video/wayland/SDL_waylanddyn.h, src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandopengles.c, src/video/wayland/SDL_waylandsym.h, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h, src/video/windows/SDL_windowsevents.c, src/video/windows/SDL_windowsvideo.c, src/video/windows/SDL_windowswindow.c, src/video/windows/SDL_windowswindow.h, src/video/x11/SDL_x11events.c, src/video/x11/SDL_x11sym.h, src/video/x11/SDL_x11video.c, src/video/x11/SDL_x11window.c, src/video/x11/SDL_x11window.h, test/CMakeLists.txt, test/testpopup.c
Implements cross-platform tooltips and popup menus.
Previously, popup menus and tooltips were only implemented on Wayland and X11, and there was no standardized behavior for these window types. This implements popup windows on Win, Mac, X11 and Wayland, with consistent behavior across all platforms.
The video layer gains the concept of parent/child windows to handle this, as popups must have an associated parent. Closing, hiding, or showing a parent will also perform the action recursively on it's child windows. Popups are positioned relative to their parent windows, move with them, and are confined to the display boundaries of the parent window, so as not to position them off screen or between displays.
To applications, tooltip and popup menu windows are mostly identical in behavior, …
=> Implement cross-platform tooltips and popup menus

src/video/wayland/SDL_waylandwindow.c
Don't use the cached floating window size for maximized or tiled windows. Fixes the initial window size when creating a window with the maximized flag set.
=> wayland: Never use the cached size for maximized or tiled windows

src/filesystem/haiku/SDL_sysfilesystem.cc
when solely looking for the path for the current binary in the current team, find_path is sufficient.
=> SDL_GetBasePath simplification for Haiku.

src/video/wayland/SDL_waylandopengles.c
Set the timeout max to one second from the current time or presentation time will always be greater than the timeout and the application will run unthrottled.
Fixes #7452, which was regressed by #7210
=> wayland: Set the EGL swap timeout to one second from the current time

include/SDL3/SDL_video.h, src/video/SDL_video.c
- Disallow additional operations on popups where they have no effect or don't make sense.
- Update the popup window creation documentation with information about popup menu input focus, additional ignored flags, and note additional invalid popup window operations.
=> Popup checks

src/video/wayland/SDL_waylandopengles.c
Don't throttle window updates until the first swap has occurred, as the window won't actually be shown or receive the frame callback until that point and this causes new window creation to have a full 1 second delay.
=> wayland: Don't throttle presentation until the first swap has occurred

src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandwindow.c
Update for clarified xdg-output rules, use a better name and description for the popup position constraint function, and recalculate the window geometry on popup configure events, if necessary.
=> Wayland updates

src/test/SDL_test_common.c, src/video/SDL_video.c
=> Fixed bug #7462 - 8888 as default GL backbuffer red/green/blue/alpha bit sizes

src/audio/wasapi/SDL_wasapi.c, src/audio/wasapi/SDL_wasapi.h
(Putting this in a pull request so I can make sure it compiles on Windows.)
This lets background threads open a WASAPI audio device.
Note that this PR is for SDL2; for SDL3, we'll avoid the chance of a leak by managing this ourselves, since we're (hopefully) changing how device opens happen.
Fixes #7478.
=> wasapi: Force WIN_CoInitialize duing device open.

src/render/SDL_render.c
The RendererInfo's flags are supposed to contain SDL_RENDERER_PRESENTVSYNC in case vsync is on, and not have it set if it's off.
Usually this is done inside SetVSync implementations for each separate "driver". But this flag is not updated within SDL_RenderSetVSync() in case the driver fails and the simulated vsync is enabled instead. This change lets the user to correctly detect current vsync state by reading SDL_RendererInfo in case the simulated vsync was activated.
Also fixes SetVSync's return value check: it may be positive for error too, but existing condition only tests for `< 0` values.
TBH I don't know how this is seen from design pov; if it's not correct, and simulated vsync must not be active in this case, then the flag should be updated under a separate condition perhaps?
Fixes …
=> Fix SDL_RenderSetVSync does not update flags if simulated vsync is on

src/test/SDL_test_fuzzer.c, src/video/x11/SDL_x11events.c, src/video/x11/SDL_x11events.h, src/video/x11/SDL_x11window.c, test/testautomation.c, test/testautomation_events.c, test/testautomation_video.c
X11: fix size/position (test video_setWindowCenteredOnDisplay)
this fix x11 backend to correctly pass video_setWindowCenteredOnDisplay()
- get border values early  (eg status bar)
- add border values, to have correct position sets.
- wait for size/position change to get valid values
=> X11: fix size/position (test video_setWindowCenteredOnDisplay)

src/video/wayland/SDL_waylandwindow.c
Rolls back a hacky workaround, which itself may have caused a resource leak, for an internal libdecor use-after-free crash that has long since been properly fixed, and keeps the minimized flag on windows until they regain focus to retain the state when a window is recreated as part of attaching a renderer to it.
=> Wayland window unref and minimize fixes

src/test/SDL_test_assert.c, src/test/SDL_test_harness.c
Not sure if this is ok, for all platforms, but adding some color for the long listing passed/failed helps to spot the correct informations
=> Add some color in testautomation logs!

src/video/x11/SDL_x11events.c, src/video/x11/SDL_x11events.h, src/video/x11/SDL_x11window.c, test/testautomation.c, test/testautomation_video.c
4b1378f
X11: fix size/position (test video_setWindowCenteredOnDisplay)
this fix x11 backend to correctly pass video_setWindowCenteredOnDisplay()
get border values early (eg status bar)
wait for size/position change to get valid values
d4d26e0
testautomation_video: if SDL_SetWindowSize/Position isn't honored, we should check there is an event
x11: send the events if various occasions
=> backport x11/sdl2 fixes

android-project/app/src/main/java/org/libsdl/app/SDLControllerManager.java, src/core/android/SDL_android.c
This PR contains a few fixes for issues I encountered when trying to build and run a test android project off of the `SDL2` branch.
The missing type in question is causing compilation failures. The error was introduced in https://github.com/libsdl-org/SDL/commit/dca3fd8307c2c9ebda8d8ea623bbbf19649f5e22, which was a backport of commit https://github.com/libsdl-org/SDL/commit/de3909a190f6e1a3f11776ce42927f99b0381675 from SDL3 to SDL2.
Because `int nballs` was removed as a parameter from the controller API in SDL3 in revision https://github.com/libsdl-org/SDL/commit/fcafe40948fe308cc9552df5a3d625ee2725de5a, this change is only applicable to the SDL2 branch.
Another regression from commit https://github.com/libsdl-org/SDL/commit/dca3fd8307c2c9ebda8d8ea623bbbf19649f5e22, which was a backport …
=> SDL2: android: Fix regressions in android project after controller change backport

test/testdisplayinfo.c
All reported modes were identical. Using 'i' variable instead of 'm' seemed wrong.
=> testdisplayinfo: use correct index variable

test/testgles2_sdf.c
glGetShaderInfoLog should be the correct one here.
=> testgles2_sdf: Call correct function to get shader info log

src/test/SDL_test_common.c, test/testautomation.c
testcommon/automation: add [--audio driver] option
allow to use --audio --video --renderer for testautomation
=> testcommon/automation: add [--audio driver] option

src/joystick/hidapi/SDL_hidapi_steam.c
When N2935 is implemented, the enum breaks compilation in c2x mode. This PR replaces the enum with a `#define` to the `SDL_bool` type.
Fixes #7522
=> SDL_hidapi_steam.c: Fix compilation under c2x.

src/video/SDL_video.c
I haven't been able to reproduce them with current test (eg testautomation), 
but ot sounds, like there could be issues after Destroying a window, if:
- a wakeup event for the window is pending 
- _this->current_glwin is accessed
so let's clear those variables if needed
=> SDL_DestroyWindow: some safety fix

Makefile.minimal
CFLAGS currently takes care of two aspects of the build: optimisation and debug symbols on one hand, the include path on the other. The former should be overridable by users, the latter shouldn't. This patch allows CFLAGS to be overridden either from the environment or from the command line, and adds the required include setting unconditionnally.
Based on a patch by Roflcopter4:
https://github.com/joncampbell123/dosbox-x/pull/3850
=> Split up CFLAGS construction so it can be overridden

include/SDL_mutex.h
Apply the same fix as was been applied to main brainch: https://github.com/libsdl-org/SDL/commit/78725dc0cd8502a91d2565af44ff9e6e65f0f30d
Fixes C90 compatibility in the public header
C90-enforcing projects fails to build because of C++ comment in the public header.
=> SDL2: Fixed a C++-style single line comment at SDL_mute.h

src/core/haiku/SDL_BApp.h, src/core/haiku/SDL_BeApp.cc, src/core/haiku/SDL_BeApp.h, src/video/haiku/SDL_BApp.h, src/video/haiku/SDL_BWin.h, src/video/haiku/SDL_bframebuffer.cc, src/video/haiku/SDL_bmessagebox.cc, src/video/haiku/SDL_bmodes.cc, src/video/haiku/SDL_bopengl.cc, src/video/haiku/SDL_bwindow.cc
SDL_BApp becomes very basic, handles the framework dropped files.
SDL_BLooper is created in all cases, and handles the earlier tasks of SDL_BApp
This makes this implementation work when be_app already exists, for instance with a Qt application.
fix #5385
=> Haiku: use a BLooper for events, only create a BApplication when it doesn't already exist.

src/video/x11/SDL_x11keyboard.c
The X11 driver uses scancodes derived from keysyms to map the scancodes for extended keys to the physical keyboard, however, this can be incorrect when using certain XKB options (e.g. caps:swapescape), which changes the keysyms emitted by certain keys, but does not imply that their scancodes or positions should be altered. Mark selected scancodes as being non-remappable so that they aren't changed by toggling XKB mapping options.
In the case of `caps:swapescape`, during initialization, the escape key was being changed to the capslock scancode, and capslock was unchanged, because the escape key's scancode isn't considered to be extended. Then, during keycode remapping, both the escape key (remapped at the scancode level as capslock) and the real capslock key were being altered to emit the …
=> x11: Don't allow the changing of certain scancodes 

build-scripts/SDL_migration.cocci, docs/README-migration.md, include/SDL3/SDL_video.h, src/dynapi/SDL_dynapi.sym, src/dynapi/SDL_dynapi_overrides.h, src/dynapi/SDL_dynapi_procs.h, src/test/SDL_test_common.c, src/video/SDL_video.c, test/testautomation_video.c
It turns out there's a race condition on X11 where the window could be placed by the window manager while being placed by the application, so we need to have the initial position available at window creation.
=> Added SDL_CreateWindowWithPosition()

src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandevents_c.h, src/video/wayland/SDL_waylandwindow.c
Refactors the window constraint handling, as there were times when limits weren't being set when they should have been and vice versa, avoids setting some redundant libdecor state with every frame configure event, and ensures that libdecor constraints are always committed when necessary, as libdecor introduces an extra level of buffering for these values. Additionally, as the limits are just hints that the compositor is free to ignore, they need to be manually applied when appropriate to try and enforce the user requested limits, particularly for non-resizable windows.
Other cleanups/fixes include:
- Avoiding potential recursive calls back into the video subsystem when entering full screen.
- Avoiding unnecessary round trips when initially showing a minimized or maximized window.
- …
=> Wayland constraint refactoring and other fixes

CMakeLists.txt
Split `SDL_NEON` in 2 options:
- `SDL_NEON`: for enabling neon intrinsics
- `SDL_NEON_BLITTERS`: for enabling neon assembly blitters
Because I think the MIT licensing issue is with the assembly blitters, this pr enables `SDL_NEON` by default for all arm architectures, and keeps `SDL_NEON_BLITTERS` disabled.
#7570
=> cmake: split SDL_NEON into SDL_NEON and SDL_NEON_BLITTERS

cmake/sdlchecks.cmake, src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandevents_c.h, wayland-protocols/wayland.xml
This allows clients to be aware of "natural scrolling" settings in the compostior and adjust accordingly to optionally keep the same wheel and trackpad behaviour accross platforms.
Testing using the "testmouse" example, behaviour in the demo is now the same regardless of the compositor setting for scrolling.
=> wayland: Support axis relative direction

src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandvideo.h
A bit of protocol housekeeping:
- wl_output and wl_seat favor release methods over destroy, when available
- wl_output v4 deprecates the name and description handling in xdg_output and moves this into the core protocol
=> Wayland seat and output version updates

src/video/cocoa/SDL_cocoakeyboard.m
This issue has been spotted on Apple MacOS Ventura 13.3, with an Apple Magic Keyboard ISO French layout.
With the tool `checkkeys`:
```
2023-04-04 21:51:37.847 checkkeys[14324:247087] INFO: Initial state: modifiers: (none)
2023-04-04 21:51:40.155 checkkeys[14324:247087] INFO: Key pressed :  scancode 53 = `, keycode 0x0000003C = <  modifiers: (none)
2023-04-04 21:51:40.155 checkkeys[14324:247087] INFO: INPUT Text (\x40): "@"
2023-04-04 21:51:40.358 checkkeys[14324:247087] INFO: Key released:  scancode 53 = `, keycode 0x0000003C = <  modifiers: (none)
2023-04-04 21:51:43.100 checkkeys[14324:247087] INFO: Key pressed :  scancode 100 = , keycode 0x00000040 = @  modifiers: (none)
2023-04-04 21:51:43.101 checkkeys[14324:247087] INFO: INPUT Text (\x3c): "<"
2023-04-04 21:51:43.305 …
```
=> Fix key code names for ISO keyboard layouts

src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandwindow.c
wl_compositor v6 introduces the preferred buffer scale event, which serves a similar function to the fractional scale protocol, but deals in integer scale factors. Listen to this event when the wl_compositor version is >= 6 and the fractional scale protocol is not present to set the scale factor for surfaces.
=> wayland: Use the integer buffer scale event when applicable

src/video/android/SDL_androidevents.c, src/video/android/SDL_androidwindow.h
Android: need to save/restore the swap interval / vsync
otherwise, there is a difference of framerate, either with gles2 or SDL_renderer (testspriteminimal, testgles2).
=> Android: need to save/restore the swap interval / vsync

test/template.test.in
Otherwise they'll try to run with no arguments, and fail, when run by ginsttest-runner.
Fixes: 81ca9d61 "cmake+test: add more automated tests + use properties"
---
We use the installed-tests (and run them via GNOME's ginsttest-runner) as a smoke-test in the Debian packaging, to make sure that changes in SDL's dependencies don't make it regress: for example see <https://ci.debian.net/packages/libs/libsdl3/unstable/amd64/>. (We'll make more active use of this when SDL3 reaches a point where its API/ABI are stable and it's suitable to be shipped to users, but at the moment its packaging in Debian experimental is more like a proof-of-concept so that we can catch any showstopper issues early.)
=> test/template.test.in: Pass SDL_NONINTERACTIVE_ARGUMENTS to installed-tests

sdl2-config.cmake.in
Add option to `sdl2-config.cmake` to remove `-mwindows` of the link options.
It's to be used as:
```
add_executable(my_game my_game.c)
set(SDL2_NO_WINDOWS TRUE)
find_package(SDL2 REQUIRED)
target_link_libraries(my_game PRIVATE SDL2::SDL2)
```
The option is added for keeping the current behavior.
`SDL2Config.cmake`, and `SDL3Config.cmake` never add `-mwindows`.
These expect users to set the [`WIN32_EXECUTABLE` property](https://cmake.org/cmake/help/latest/prop_tgt/WIN32_EXECUTABLE.html).
TODO:
- add item to sdlwiki SDL2 cmake page
Fixes https://github.com/libsdl-org/sdlwiki/issues/368
=> cmake: allow users of sdl2-config.cmake to not add -mwindows to the link options

src/video/wayland/SDL_waylandwindow.c
Destroy any proxy wrappers and callbacks before the associated event queues to silence libwayland warnings about destroying the queues while proxies are still attached.
Fixes #7397
=> wayland: Destroy proxy wrappers before and callbacks before event queues

src/audio/aaudio/SDL_aaudio.c
=> Android: fix crash when AAUDIO isn't used (bug #7620)

src/video/wayland/SDL_waylandvideo.c
Insert new displays at the end of the list instead of the front so that the initial ordering, as exposed by the compositor, is preserved. This is particularly important when the compositor exposes the xdg-output instance after the wl_output instance, as xdg-output must be attached to the outputs in the same order that wl_output exposed them, or they can be added to the SDL output list in reverse order.
=> wayland: Insert new displays at the end of the output list

src/video/SDL_shape.c
In function `RecursivelyCalculateShapeTree()`, check the return value of `SDL_malloc()` to prevent null pointer dereference.
=> Check return value of SDL_malloc()

src/joystick/virtual/SDL_virtualjoystick.c
In function `VIRTUAL_JoystickGetGamepadMapping()`, check return value of `VIRTUAL_HWDataForIndex()` for null.
=> Check return value of VIRTUAL_HWDataForIndex()

src/video/wayland/SDL_waylandevents.c
Noticed a leak in the wayland driver where `primary_selection_device` wasn't being freed
Added checks and free up the allocated data if it exists
=> wayland: Fixes a memory leak wheere primary selection isn't freed

src/video/wayland/SDL_waylandwindow.c
Destroy any proxy wrappers and callbacks before the associated event queues to silence libwayland warnings about destroying the queues while proxies are still attached.
Backport of bad4f4e for SDL2
=>  wayland: Destroy proxy wrappers and callbacks before event queues

include/SDL3/SDL_events.h, src/events/SDL_windowevents.c, src/video/SDL_video.c
As child windows can be recursively destroyed when their parents are destroyed, emit an event to notify the application when a window is being or has been implicitly destroyed so that it can appropriately clean up any associated resources.
If the application has registered an event watch, the destroy message will be received when the window handle is still valid, so the application can retrieve and release any userdata associated with the window. If the message is processed at any time after that, the window handle is already invalid and the ID is only useful for application-side bookkeeping purposes.
I've run into a real-world situation where this will be useful while adding popup support to sdl2-compat as needed by Unreal Engine, as some bookkeeping is required when managing the event …
=> events: Emit an event when a window is destroyed

docs/README-migration.md
Add info pointing users to #6766 when they look for SDL_JoystickNumBalls
=> Update migration guide with info on trackballs

src/audio/SDL_audiocvt.c
SDL_ConvertMonoToStereo_SSE was not properly adjusting the src/dst pointers before the main loop.
=> Fixed SDL_ConvertMonoToStereo_SSE reading out of bounds

src/video/directfb/SDL_DirectFB_shape.c
Bitmap is not initialized before use, that cause segmentation fault on function use it. Fix by allocate memory before use.
Allocate memory for bitmap with the require size for the function before pass to the function. The current will meet the segmentation fault because function use bitmap will memset the bitmap with the size of the shape. 
https://github.com/libsdl-org/SDL/issues/7676
=> Fix bug memory access

src/video/SDL_sysvideo.h, src/video/SDL_video.c, src/video/cocoa/SDL_cocoawindow.h, src/video/cocoa/SDL_cocoawindow.m, src/video/haiku/SDL_bwindow.h, src/video/kmsdrm/SDL_kmsdrmvideo.c, src/video/kmsdrm/SDL_kmsdrmvideo.h, src/video/psp/SDL_pspvideo.c, src/video/psp/SDL_pspvideo.h, src/video/raspberry/SDL_rpivideo.c, src/video/raspberry/SDL_rpivideo.h, src/video/vita/SDL_vitavideo.c, src/video/vita/SDL_vitavideo.h, src/video/vivante/SDL_vivantevideo.c, src/video/vivante/SDL_vivantevideo.h, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h, src/video/windows/SDL_windowswindow.c, src/video/windows/SDL_windowswindow.h, src/video/x11/SDL_x11window.c, src/video/x11/SDL_x11window.h
This pr is created as a result of this comment:
https://github.com/libsdl-org/SDL/issues/7197#issuecomment-1524160409
Return a negative error variable when `SDL_SetWindowPosition` fails.
#7197
=> video: set error code when SetWindowPosition fails

src/video/wayland/SDL_waylandwindow.c
Various fixes for bugs that popped up when testing the UE5 editor via sdl2-compat. Wayland has strict rules for popups, so we must ensure, in all cases, that the rules for popup positioning are obeyed.
=> Wayland popup fixes for UE5

src/video/wayland/SDL_waylandwindow.c
Repositioning a hidden popup window is valid behavior, so don't print an error message in this case.
=> wayland: Don't print an error when moving a hidden popup window

src/video/SDL_blit_N.c
An in-place swizzle mutation was erroneously inside of a loop, which caused each consecutive 4-pixel vector to alternate between correct and incorrect endianness.
The bug was introduced in 715e070d299fc547cce8c52915b75e6316af6bff. Thanks to RobbieAB for reporting the bug. I was only able to test the fix as applied to SDL v2.26.5, but it doesn't look like the relevant code has changed in `main`. I did verify that it still builds in `main` at least. I only could test the fix in `ConvertAltivec32to32_prefetch`, but the same broken pattern shows up in 2 other functions, so I fixed them too even though I couldn't test them.
Fixes https://github.com/libsdl-org/SDL/issues/3428
=> SDL_blit_N.c: Move ppc64le swizzle outside of loop

src/video/wayland/SDL_waylandwindow.c
If the popup is positioned such that it requires correction on both the x and y axes, it will be aligned with parent only at the window corners, which is neither overlapping nor adjacent. In this case, nudge the window plus or minus one screen unit on the x axis so it is properly adjacent to the parent and within spec guidelines.
=> wayland: Fix the corner case when positioning popups

include/SDL3/SDL_filesystem.h, src/filesystem/android/SDL_sysfilesystem.c, src/filesystem/cocoa/SDL_sysfilesystem.m, src/filesystem/dummy/SDL_sysfilesystem.c, src/filesystem/emscripten/SDL_sysfilesystem.c, src/filesystem/haiku/SDL_sysfilesystem.cc, src/filesystem/n3ds/SDL_sysfilesystem.c, src/filesystem/ps2/SDL_sysfilesystem.c, src/filesystem/psp/SDL_sysfilesystem.c, src/filesystem/riscos/SDL_sysfilesystem.c, src/filesystem/unix/SDL_sysfilesystem.c, src/filesystem/vita/SDL_sysfilesystem.c, src/filesystem/winrt/SDL_sysfilesystem.cpp
Follow-up #7665 
This fixes a few remaining problems with SDL_GetPath:
- Added a "return NULL" where one was missing in the Unix implementation
- Implemented the function the best I could for Emscripten and Haiku, and wrote a basic SDL_Unsupported() implementation for other platforms.
I found [documentation for Android](https://developer.android.com/reference/android/os/Environment#lfields), but it's in Java, and I wouldn't know where to start to implement it, so I think it's best to leave it in the hands of someone more knowledgeable than me.
=> Implement SDL_GetPath stub for all OSes, and fix a bug

src/audio/aaudio/SDL_aaudio.c, src/audio/aaudio/SDL_aaudio.h, src/audio/android/SDL_androidaudio.c, src/audio/android/SDL_androidaudio.h, src/audio/openslES/SDL_openslES.c, src/audio/openslES/SDL_openslES.h, src/video/android/SDL_androidevents.c
Android: use the headers to have the audio pause/resume definitions
and make SDL_PriveAudioData more private
(after  https://github.com/libsdl-org/SDL/pull/7692 and https://github.com/libsdl-org/SDL/issues/7688 )
=> Android: use the headers to have the audio pause/resume definitions

src/video/cocoa/SDL_cocoaclipboard.h, src/video/cocoa/SDL_cocoaclipboard.m, src/video/cocoa/SDL_cocoavideo.m
Implements Get/Set/HasClipboardData functions for generic data on MacOS.
Adds ClipboardDataProvider that calls the `SDL_ClipboardDataCallback` when requested by the OS.
Adds implementations for checking, getting and setting any data to the clipboard with a specific mime-type.
Cocoa Pasteboard uses Uniform Type Identifiers for identifying the type of data in the clipboard, a mapping between mime-type coming from SDL to UTI in Cocoa has been implemented.
#7625
=> MacOS generic clipboard data implementation

src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandwindow.c
Add support for the pixel density hint and fix the integer scale path to assume that exclusive fullscreen pixel density values are always 1.
=> wayland: Fixups for new DPI code

src/core/linux/SDL_dbus.c, src/core/linux/SDL_dbus.h, src/core/linux/SDL_system_theme.c, src/core/linux/SDL_system_theme.h, src/video/wayland/SDL_waylandevents.c, src/video/x11/SDL_x11events.c, src/video/x11/SDL_x11modes.c
If the `text-scaling-factor` setting is available via D-Bus, add a listener and update the content scale values for the displays if the value is changed during runtime.
Factors out the D-Bus message pump from the system theme detection code to the general D-Bus code, as it's now used for more purposes than just the system theme.
Follow up to #7718
=> x11: Dynamically update the scale factor

src/video/uikit/SDL_uikitview.m
If an SDL-based iOS app is running on an ARM-based Mac, certain keypresses may result in a system beep.
We built a project in C# using FNA which uses SDL with a target of iOS 11.  It runs fine on ARM-based Macs, however, some keypresses (for example, enter but not an array key) result in the system beep sound, even though the application can process the keypress correctly.
Some searching brought us to this:
https://developer.apple.com/forums/thread/651252
Removing the super calls in our own build removed the beeping sound.
N/A
=> Stop beep when running iOS apps on ARM-based Macs

src/core/windows/SDL_windows.c, src/core/windows/SDL_windows.h, src/video/windows/SDL_windowsevents.c, src/video/windows/SDL_windowswindow.c
`IsRectEmpty` is not defined for Xbox GDK, resulting in a link error in `WIN_GetWindowSizeInPixels`. Note that `IsRectEmpty` is called elsewhere in the codebase too, but this is the only place it's not #ifdef'd out for Xbox.
I wasn't sure how to style this, since it's a bit of a weird case where the #ifdef goes in the middle of an `if` statement. I'm happy to reformat this if needed.
Note that this affects SDL2 too, since the commit introducing this line was cherrypicked for the SDL2 branch.
=> Fix Xbox link error from IsRectEmpty

src/video/wayland/SDL_waylandevents.c
Ensure that incoming touch events originate from valid surfaces owned by SDL and have proper window data before forwarding them to the touch subsystem, or the window focus pointer that is sent with the event may not be a pointer to an SDL window.
SDL2 backport of #7729 
Closes #7726
=> wayland: Validate surfaces and window data before sending touch events

test/testevdev.c
* testevdev: Add the ability to mark a device entry as unimplemented
There are some devices for which SDL's device classification heuristic
is known not to give the ideal result. Add a way to incorporate these
into our test data, so that when the heuristic is improved we can
detect them as their intended device type, without making the test fail
before that has been implemented.
* testevdev: Add some driving sim controllers from Proton issue reports
Ideally we'd detect these as "joysticks" (or more generally, gaming
controllers), but in most cases their evdev flags are indistinguishable
from an accelerometer or gyro, so the only way to achieve this would be
a table of known devices that doesn't currently exist.
One exception is the one that reports a THROTTLE axis and TRIGGER, THUMB …
=> testevdev: Add some driving sim controllers from Proton issue reports

src/video/x11/SDL_x11dyn.h, src/video/x11/SDL_x11modes.c, src/video/x11/SDL_x11sym.h, src/video/x11/SDL_x11video.h
There are many toolkit specific ways to set a font DPI in X11 desktop environments. The primary approach of reading a Gnome specific setting from the portal is ok, it will work on Gnome and on Plasma most the time.
The current fallback GDK_SCALE is less great; it's an internal GTK setting relating to the mapping of logical pixels to device pixels within the toolkit, it's a developer setting for a toolkit. We were instructed within Plasma to not set this as it caused issues.
Xft.dpi in xresources is a good universal fallback, it's very dated to the point that it works in clients like xterm, Qt on X11 uses it in our font DPI path.
=> x11: Use XResources font DPI as a fallback for X11 content scale

src/audio/SDL_audio.c, src/audio/pulseaudio/SDL_pulseaudio.c, src/audio/pulseaudio/SDL_pulseaudio.h
This moves the PulseAudio code over to a threaded mainloop.
We weren't meant to have multiple contexts and mainloops, but we had one for each opened device and the hotplug detection thread. Instead, use pa_threaded_mainloop, which can be shared between threads and objects, and a single context (which, according to the PulseAudio documentation, is usually meant to be a singleton that represents a global server connection, possibly with multiple streams hung on it).
Now instead of polling in a loop, threads will block until the threaded_mainloop runs a callback, and the callback will fire a signal to unblock the thread.
Prior to this, the code upset ThreadSanitizer, as Pulse has some unprotected global resource that each mainloop/context would touch.
Reference Issue …
=> Pulseaudio threaded mainloop

CMakeLists.txt
This allows `#include <SDL2/SDL.h>` when using SDL2 as a subproject.
For https://github.com/libsdl-org/SDL/issues/7737
SDL3 supports this already.
=> cmake: allow #include "SDL2/SDL.h.h" when using SDL2 as subproject

src/hidapi/SDL_hidapi.c, src/hidapi/linux/hid.c, src/hidapi/mac/hid.c, src/hidapi/windows/hid.c
The error string is not protected by a mutex, and can be set from multiple threads at the same time. Without this change, it can be double-freed. It can still be double-allocated, leading to a memory leak, but at least it won't crash now.
=> Fixed double-free during multi-threaded hidapi access

include/SDL3/SDL_hidapi.h, include/SDL3/SDL_hints.h, src/hidapi/SDL_hidapi.c, src/hidapi/SDL_hidapi_c.h, src/hidapi/android/hid.cpp, src/hidapi/ios/hid.m, src/hidapi/libusb/hid.c, src/hidapi/linux/hid.c, src/hidapi/mac/hid.c, src/hidapi/windows/hid.c
By default SDL will only enumerate controllers, to reduce risk of hanging or crashing on devices with bad drivers and avoiding macOS keyboard capture permission prompts.
=> Added SDL_HINT_HIDAPI_ENUMERATE_ONLY_CONTROLLERS to control whether SDL_hid_enumerate() enumerates all HID devices or only controllers.

src/video/x11/SDL_x11modes.c, src/video/x11/SDL_x11sym.h
XRandR supports applying transformations to an output's picture including changes to scale. Such scaling is used by some desktop environments under feature names such as "fractional scaling" to accommodate HiDPI devices. Alternatively, such scaling can be enabled by a command such as the following:
xrandr --output DP1 --scale 0.5x0.5 --filter nearest
XRandR scaling has no "HiDPI awareness" or other way for an application to signal that it wants to work with physical display pixels, and so all we do in these changes is scale SDL's returned display modes so that applications receive the number of usable pixels that they expect. For instance, when XRandR is applying a 0.5x0.5 scale, a full screen application will only receive a quarter of the pixels that it is expecting, and only a single …
=> X11: apply XRandR scaling to returned display modes

CMakeLists.txt
Use CMakeDependentOption instead to configure SDL_HIDAPI_LIBUSB to a okay-ish variable.
By not forcing the variable, it should be possible to disable `SDL_HIDAPI_LIBUSB`.
#7736
=> cmake: don't force enable/disable SDL_HIDAPI_LIBUSB

docs/README-migration.md, include/SDL3/SDL_hints.h, src/core/unix/SDL_appid.c, src/core/unix/SDL_appid.h, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandvideo.h, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h, src/video/x11/SDL_x11keyboard.c, src/video/x11/SDL_x11video.c, src/video/x11/SDL_x11video.h, src/video/x11/SDL_x11window.c
Per #7702, converts the X11 WM_CLASS and Wayland app ID envvars to a consolidated hint, and adds some documentation for them along with the migration info.
Will need an sdl2-compat mapping.
=> Convert the X11 WM_CLASS and Wayland App ID envvars to a unified hint

src/audio/pipewire/SDL_pipewire.c
Now we have ``SDL_HINT_APP_ID`` (see #7741), we can pass it to other APIs which support it.
If SDL_HINT_APP_ID is set, pass it as the application.id to pipewire. This gives any pipewire-based tools a hint to find an associated .desktop file for icons, etc.
(Note that, unlike the application name, etc, we don't have a default here: we just don't set an application.id. This means any pipewire tools will fall back to using the other available properties to describe the application / stream.)
=> pipewire: Set 'application.id' if SDL_HINT_APP_ID set

.gitignore
Locally, I do make multiple build directories for various purposes, like "build-debug", "build-release", "build-novideo", etc. Also, Qt Creator (if configure it) may automatically create build directories that always starts with a "build-*" prefix.
=> GitIgnore: Also ignore "build-*/" sub-directories

include/SDL3/SDL_hints.h, src/video/wayland/SDL_waylandwindow.c
Add aspect-correct output of scaled video modes and a hint to control this behavior (aspect, stretch, or none).
The Wayland spec states that fullscreen surfaces that do not cover the entire output shall be centered with the borders masked by the compositor, so no additional work is required aside from calculating the proper window dimensions, which is fairly simple (unlike the previous attempt that used subsurfaces, and became quite ugly trying to work around compositor bugs).
The default is still 'stretch' mode (same as the existing behavior), as some window managers as of right now (KDE and older versions of GNOME still found in LTS distros) don't behave according to the spec and present an unmasked window that is not centered, so it's not yet safe to change the default.
KDE will likely …
=> wayland: Add aspect-correct output for scaled modes

VisualC-GDK/SDL/SDL.vcxproj, VisualC-GDK/SDL/SDL.vcxproj.filters, include/SDL3/SDL_hints.h, include/build_config/SDL_build_config_wingdk.h, include/build_config/SDL_build_config_xbox.h, src/video/gdk/SDL_gdktextinput.cpp, src/video/gdk/SDL_gdktextinput.h, src/video/windows/SDL_windowsvideo.c
This implements a very basic TextInput & ScreenKeyboard backend for GDK platforms.
For Windows GDK builds it's better to use the Windows IME, but on Xbox there is no option other than the GDK IME.
The virtual keyboard window can be additionally controlled with optional set-only SDL hints:
```cpp
/* all of these hints are optional, and it's recommended that you don't try to GetHint them, only SetHint */
/* "example" comment means that this line will probably be specific to your game or however you handle it */
SDL_SetHint(SDL_HINT_GDK_TEXTINPUT_TITLE, "Stones Keeper");
SDL_SetHint(SDL_HINT_GDK_TEXTINPUT_DESCRIPTION, "Enter save data name:");
SDL_SetHint(SDL_HINT_GDK_TEXTINPUT_DEFAULT, "optional value to put into the textbox here...");
SDL_SetHint(SDL_HINT_GDK_TEXTINPUT_SCOPE, …
```
=> gdk: Commit virtual keyboard support

include/SDL_hints.h, src/video/wayland/SDL_waylandwindow.c
Since 63ae103cd184eb46020eb77f5fd49504183296bd, SDL_HINT_QTWAYLAND_CONTENT_ORIENTATION can accept comma-separated list of used screen orientations. But this change also introduced a bug: primary orientation is always set, no matter the hint value.
Also added a note in SDL_hints.h header about this change.
SDL3 branch has the same bug, probably should be cherry-picked there as well.
=> QtWayland orientation fixes

test/testevdev.c
Similar to #7597, having broader test data helps to make sure our heuristic for detecting these won't regress.
A few of these controllers (coincidentally, all from my colleague Jeremy Whiting's collection of test devices) are detected as `SDL_UDEV_DEVICE_JOYSTICK | SDL_UDEV_DEVICE_KEYBOARD` because one of their buttons has been mapped to what is normally a keyboard key:
* 8BitDo N30 Pro 2 via Bluetooth (but not via USB!) has `KEY_MENU`, the "Windows 95 keyboard" right-click-menu key, normally found between right Alt and right Ctrl
* Google Stadia Controller has volume up/down and media play/pause buttons mapped the same way they would be for a multimedia keyboard or a Bluetooth headset
* Microsoft Xbox Series S|X Controller has its Share button mapped to `KEY_RECORD`
I've assumed here …
=> Add more known controllers to testevdev

android-project/app/src/main/java/org/libsdl/app/SDLActivity.java
Android: add timeout when waiting the SDL thread to finish
C SDLmain() thread might have started (mSDLThread.start() called) while the SDL_Init() might not have been called yet, and so the previous QUIT event will be discarded by SDL_Init() and app is running, not exiting.
This is reprocible by adding instrumentation code in the SDLActivity.
And hopefully, this could fix an ANR, where SDLActivity is in WAITING state (in thread.join()):
at java.lang.Thread.join (Thread.java:1519)
at org.libsdl.app.SDLActivity.onDestroy (SDLActivity.java)
while SDLThread seems to be running
=> Android: add timeout when waiting the SDL thread to finish

src/video/wayland/SDL_waylandclipboard.c, src/video/x11/SDL_x11clipboard.c
The X11 driver was failing to adhere to the test 'Verify SDL_GetClipboardText did not return NULL' which has been fixed.
The wayland driver was failing to check if clipboard content is available when the program itself is the current clipboard content holder. This happened for both clipboard and primary selection. It has also been fixed.
Fixed problems in the two drivers.
#7800
=> clipboard: Fixes testautomation fails introduced by clipboard changes

src/video/x11/SDL_x11clipboard.c, test/testautomation_clipboard.c
Fixes one more x11 clipboard bug uncovered by automated tests. If a user doesn't supply a callback method when setting clipboard data and instead supplies NULL this wasn't handled gracefully in all places.
Introduces additional NULL checks before using the user supplied clipboard data callback function.
#7800
=> clipboard: Fixes additional x11 clipboard bugs found in tests

src/joystick/linux/SDL_sysjoystick.c
Please review and test carefully: I do not have the affected hardware, so I am unable to test this.
* linux: Reduce magic numbers when mapping gamepad axes
The bitfield `mapped` has two different sets of meanings, depending
whether we're setting up the triggers or the d-pad. Represent them
as symbolic constants rather than opaque integers.
* linux: Improve gamepad mapping heuristic to accept Android conventions
This heuristic for gamepads without a more specific mapping already
tried two incompatible conventions for handling triggers: the Linux
Gamepad Specification uses hat switch 2 for the triggers (for whatever
reason), but the de facto standard set by the drivers for older Xbox
and Playstation controllers represents each trigger as the Z-axis of
the nearest analog stick.
Android …
=> linux: Improve gamepad mapping heuristic to accept Android conventions

test/testautomation_events.c
testautomation_events.c: initialize "timestamp" to solve "conditiona  jump or move depends on uninitialised value"
=> testautomation_events.c: initialize "timestamp" 

test/testevdev.c
This slightly newer device than the one from #7814 is functionally equivalent when connected via USB. When connected via Bluetooth, it has a different button mapping.
Thanks to @slouken.
---
As with #7791, I've assumed that reporting `SDL_UDEV_DEVICE_JOYSTICK | SDL_UDEV_DEVICE_KEYBOARD` is intentional here.
=> testevdev: Expand test data for X-Box One Elite 2

test/testevdev.c
Thanks to Ben Fradella.
---
From https://github.com/ValveSoftware/Proton/issues/5126
=> testevdev: Add details of another driving simulator controller

src/core/android/SDL_android.c
Android: potential ANR during onKeyDown/Up
SDLActivity may call onNativeKeyDown, while application is quitting
cannot reproduce, but the stack-trace:
```
SDLActivity: 
#00  pc 0x0000000000089630  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+32)
#01  pc 0x000000000008e0f8  /apex/com.android.runtime/lib64/bionic/libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*)+148)
#02  pc 0x00000000000f6790  /apex/com.android.runtime/lib64/bionic/libc.so (NonPI::MutexLockWithTimeout(pthread_mutex_internal_t*, bool, timespec const*)+660)
#03  pc 0x00000000000f6360  /apex/com.android.runtime/lib64/bionic/libc.so (pthread_mutex_lock+264)
#04  pc 0x000000000028fd18  split_config.arm64_v8a.apk (SDL_LockMutex+4096)
#05  pc 0x0000000000279de0  split_config.arm64_v8a.apk …
```
=> Android: potential ANR during onKeyDown/Up

test/testevdev.c
* testevdev: Verify most Wii devices against real hardware
Some of the test data previously seen here was guessed from kernel
source code, and not all of it was correct. The following devices have
now been verified against `evemu-describe` output with Linux 6.3
(thanks to Jeremy Whiting for collecting this):
- basic Wiimote
- buttons
- 3-axis accelerometer
- infra-red sensor for Sensor Bar location (precise aim)
- Motion Plus accessory (3-axis gyroscope)
- Nunchuck accessory (joystick, 2 buttons, a second 3-axis accelerometer)
- Classic Controller accessory (a complete traditional gamepad)
* testevdev: Try to correct Wii devices guessed from kernel source
The comments here disagreed with the actual bytes. According to
https://elixir.bootlin.com/linux/v6.3.7/source/drivers/hid/hid-wiimote-m …
=> testevdev: Verify most Wii devices against real hardware

src/core/linux/SDL_evdev_capabilities.c, src/core/linux/SDL_evdev_capabilities.h, src/core/linux/SDL_udev.c, src/joystick/linux/SDL_sysjoystick.c, test/testevdev.c
* testevdev: Allow device properties to be fully populated
The props array was too small for the highest property bits to be set,
although in practice this didn't matter since only the lower-order bits
have a meaning. Make it consistent with all the others.
* linux: Pass evdev properties when guessing device type
In newer kernels, devices that can be positively identified as a
particular device type (for example accelerometers) get a property
bit set. Plumb this information through into the function, but don't
use it for anything just yet.
* linux: If the kernel specifically tells us the device type, trust it
If a device is positively identified as an accelerometer, pointing stick
or clickpad, then we don't need to second-guess it.
In practice this does not change the result for any …
=> linux: Guess device type from input properties

include/SDL3/SDL_hints.h, src/SDL_hints.c, src/SDL_hints_c.h, src/joystick/SDL_gamepad.c, src/joystick/SDL_joystick.c, src/joystick/SDL_sysjoystick.h, src/sensor/SDL_sensor.c, src/sensor/SDL_sensor_c.h
This allows using the gyro and accelerometer in handheld devices in conjunction with built-in or wraparound controllers.
=> For gamepads that don't have their own sensors, try to use the system sensors.

src/core/linux/SDL_dbus.c, src/core/linux/SDL_dbus.h, src/core/linux/SDL_ibus.c
It is possible for retrieving the machine ID to fail, either because dbus was installed incorrectly (machine ID absent or corrupt), or in 32-bit builds, because stat() on the machine ID fails with EOVERFLOW if it has an out-of-range timestamp or inode number.
dbus has historically treated this as a faulty installation, raising a warning which by default causes the process to crash. Unfortunately, dbus_get_local_machine_id() never had a way to report errors, so it has no alternative for that (bad) error handling.
In dbus >= 1.12.0, we can use dbus_try_get_local_machine_id() to get the same information, but with the ability to cope gracefully with errors. ibus won't work in this situation, but that's better than crashing.
(cherry picked from commit 91198baed40d5709020c3001e9234f4580df696a) …
=> ibus: Handle error when getting the D-Bus machine ID

src/joystick/hidapi/SDL_hidapi_switch.c
MCU input reports are practically identical to normal reports with the only difference of having extra data at the end of the package. Yuzu configures the controller in this state to access advanced features like IR, NFC or RingCon. SDL stops responding in this mode.
This is solved by simply not ignoring the report.
=> hidapi: switch: Handle MCU input reports

src/video/wayland/SDL_waylandwindow.c
Applications that don't specify a rendering flag are likely handling Vulkan/GL themselves, so SDL loading OpenGL by default in this case is unnecessary overhead, and if a render backend requires it, the window will be recreated with the appropriate flags when the renderer is initialized.
This was there from the very first commit of the skeleton Wayland code in 2013. Maybe it made sense then, but now there seems to be little point in it, as it just adds overhead for applications that want a bare surface.  BGFX, for example, creates it's own EGL window and handles OpenGL itself, so SDL is just creating additional overhead by loading OpenGL internally.  Similarly, if an application wants a bare window to pass to its own Vulkan loader instance, initializing OpenGL has no point.
X11 doesn't …
=> wayland: Don't initialize OpenGL when the window flags didn't specify it

docs/README-migration.md
=> Fixed bug #7821 - docs/README-migration.md function name typos

src/audio/SDL_audiocvt.c
For-loop in this function crashed. For example, on a little-endian system one might change testautomation audio_resampleLoss case to use F32MSB type to trigger a segmentation fault on Linux.
=> Fix crash in AudioConvertByteswap

src/core/linux/SDL_evdev.c
On 32-bit platforms such as i386, if SDL is compiled with -D_TIME_BITS=64 to opt-in to ABIs that will not stop working in 2038, the fields in this struct change their naming and interpretation.
The Linux header <linux/input.h> defines macros input_event_sec and input_event_usec which resolve to the right struct field to look at. The actual field names and types are an implementation detail, historically signed 32-bit time.tv_sec and time.tv_usec on 32-bit platforms, but becoming unsigned __sec and __usec when using 64-bit time (which makes them able to represent times up to 2106).
None
---
Without this, when forcing `_TIME_BITS=64` and `_FILE_OFFSET_BITS=64`, I get:
```
/home/smcv/src/SDL/src/core/linux/SDL_evdev.c: In function ‘SDL_EVDEV_GetEventTimestamp’: …
```
=> evdev: Use time64-friendly accessors for struct input_event

CMakeLists.txt
Define `_TIME_BITS=64` on 32-bit glibc, such that`time_t` becomes a 64-bit timestamp.
I got `abi-compliance-checker` working with the following script:
```sh
#!bin/sh
set -ex
git checkout origin/main
cmake -S . -B /tmp/SDL3-before -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="-Og -gdwarf-4 -m32" -DCMAKE_CXX_FLAGS="-Og -gdwarf-4 -m32"
cmake --build /tmp/SDL3-before --target SDL3-shared
git checkout 64-bit-timestamps
cmake -S . -B /tmp/SDL3-after -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="-Og -gdwarf-4 -m32" -DCMAKE_CXX_FLAGS="-Og -gdwarf-4 -m32"
cmake --build /tmp/SDL3-after --target SDL3-shared
rm -rf workdir
mkdir workdir
pushd workdir
abi-dumper /tmp/SDL3-before/libSDL3.so.0.0.0 -o ABI-0.dump -lver 0
abi-dumper /tmp/SDL3-after/libSDL3.so.0.0.0 -o ABI-1.dump -lver 1
abi-compliance-checker -l …
```
=> cmake: Compile with 64-bit time stamps where possible

src/video/windows/SDL_windowswindow.c
=> Center cursor to client area rather than window area

.github/workflows/emscripten.yml, docs/README-emscripten.md, src/audio/emscripten/SDL_emscriptenaudio.c, src/misc/emscripten/SDL_sysurl.c, src/video/emscripten/SDL_emscriptenmouse.c
See https://github.com/emscripten-core/emscripten/pull/19780
=> emscripten: Add JS library dependencies using EM_JS_DEPS macro

src/joystick/hidapi/SDL_hidapi_xboxone.c, src/video/wayland/SDL_waylandmessagebox.c
This PR tries to use --icon for Zenity and fall back to --icon-name when it fails.
Many distros ship an older version of Zenity that supports GTK3, while some distros ship newer version of Zenity which uses libadwaita. These different version has different flags and only the latest version (3.99.0) provides a safe fallback for `--icon-name`.
Closes #7895.
=> video(wayland): use both --icon and --icon-name for Zenity

src/joystick/SDL_joystick.c
Initialise `gamepads.max_entries` before `SDL_LoadVIDPIDListFromHint()` reads it.
None
=> Fix uninitialised variable

src/video/x11/SDL_x11events.c, src/video/x11/SDL_x11sym.h, src/video/x11/SDL_x11xfixes.c, src/video/x11/SDL_x11xfixes.h
Currently, SDL_CLIPBOARDUPDATE events are only sent when an SDL window has its selection cleared.  This change sends the event anytime the XFixesSelectionNotify event is raised, and when the selection is either the clipboard or the primary selection.
=> X11: Use XFixes to detect clipboard updates

CMakeLists.txt
When cross-compiling with [`clang-cl`](https://clang.llvm.org/docs/MSVCCompatibility.html) targeting Win32 native using this [CMake toolchain file provided by LLVM](https://github.com/llvm-mirror/llvm/blob/d35e5f8dded4c884ca25ca88f184e1505cad106c/cmake/platforms/WinMsvc.cmake).
I get the following linking errors.
```
[ 62%] Linking C shared library SDL2d.dll
cd /home/jshbrntt/snake/build/win32/_deps/sdl2-build && /usr/bin/cmake -E cmake_link_script CMakeFiles/SDL2.dir/link.txt --verbose=1
/usr/bin/cmake -E vs_link_dll --intdir=CMakeFiles/SDL2.dir --rc=llvm-windres-16 --mt=CMAKE_MT-NOTFOUND --manifests -- /usr/bin/lld-link  @CMakeFiles/SDL2.dir/objects1.rsp  /out:SDL2d.dll /implib:SDL2d.lib /pdb:/home/jshbrntt/snake/win32/_deps/sdl2-build/SDL2d.pdb /dll /version:2.26  /manifest:no …
```
=> Add kernel32 to SDL_EXTRA_LIBS

CMakeLists.txt, configure, configure.ac, src/SDL.c, src/core/windows/SDL_windows.h, src/main/windows/SDL_windows_main.c, src/thread/windows/SDL_systhread.c
Affects both SDL2 and SDL3. GCC 4.5.2 and later assume a 16-byte aligned stack, but the x86 Windows stack is not necessarily so aligned. This problem was observed in #477 (2011), and the workaround was to use `-mpreferred-stack-boundary` to, in essence, disable this assumption when building SDL itself — at some small performance and size cost.
However, that disabled assumption does not carry into applications running on top of SDL, particularly `SDL_main` and thread entry points. The use of `-mpreferred-stack-boundary` prevents most such crashes on the main thread *purely by accident*, which, in addition to the x64 ABI being unaffected, is probably why it's gone mostly unnoticed for the past 12 years. That is, SDL 16-byte aligns the main thread stack for applications by chance — a result …
=> Unaligned stacks on i686-w64-mingw32, may lead to crashes

test/testevdev.c
Thanks: Ravi Kanodia (via https://github.com/ValveSoftware/steam-devices/pull/40)
None
=> testevdev: Add some examples of PDP third-party Switch controllers

src/core/linux/SDL_evdev.c
In cases where the mouse is being reported as absolute, such as an USB tablet device, the evdev handling code was not implementing scaling to screen size, and was ignoring the reported ABS_X/ABS_Y MAX values. So the mouse pointer was mostly outside the screen bounds.
(squashed version)
=> linux evdev: Added support for absolute mode mice, such as USB tablet or VirtualBox mouse integration

src/video/SDL_video.c, src/video/wayland/SDL_waylandwindow.c
If, in the case where all displays has been disconnected, and some window state change occurs before an active display is re-added and finalized, the pointer returned by SDL_GetDisplayForWindow() will be null necessitating that the returned pointer be checked for validity before dereferencing it.
Weston, for example, can send a window configuration event before a reconnected display has its properties fully enumerated and finalized, and is re-added to the SDL display list, leading to a crash without these null checks.
SDL3 will need a bit of work for this case as well, but that will come separately as there is too much divergence to just cherry-pick this.
Fixes #7961
=> [SDL2] Check for a valid display pointer before dereferencing it

cmake/xxd.py, test/CMakeLists.txt
A pure CMake script was too slow
Fixes cmake portion of #7983
=> cmake: convert bmp headers to c headers using python script

CMakeLists.txt, test/CMakeLists.txt
Follow-up from [this discussion](https://github.com/libsdl-org/SDL_image/pull/375#discussion_r1263828248)
Note:
After this pr, `SDL_TESTS_LINK_SHARED` is reported incorrectly.
This will be fixed after https://github.com/libsdl-org/SDL/pull/7923 (in that pr, the tests are configured before printing the cmake log)
=> cmake: remove ability to build tests as a standalone project

src/joystick/bsd/SDL_bsdjoystick.c
The OpenBSD D-pad code converts a series of button-like inputs (`HUG_DPAD_UP` etc.) into an integer to pass to `SDL_PrivateJoystickHat()`. The existing solution in SDL_bsdjoystick.c is overly complicated for the task by using branching if-logic.
This PR changes this into a bitwise operation which is shorter and should also be more performant. I have tested this on OpenBSD 7.3 -current with sdl2-jstest and other applications that use SDL2's gamecontroller code without issues.
None known.
=> simplify OpenBSD D-pad calculation with bitwise operation

src/core/linux/SDL_fcitx.c
This call is actually a left-over when porting from fcitx4 service to the new org.freedesktop.portal.Fcitx supported by both fcitx4/fcitx5. CloseIC is actually never a part of the new interface on org.freedesktop.portal.Fcitx. It cause any issue user visible effect.
Reference to the interface in fcitx 4 and fcitx5
https://github.com/fcitx/fcitx/blob/master/src/frontend/ipcportal/ipcportal.c#L120
https://github.com/fcitx/fcitx5/blob/master/src/frontend/dbusfrontend/dbusfrontend.cpp#L375
=> Remove the leftover CloseIC dbus call in fcitx module

src/SDL.c
This returns the correct platform name when running on Managarm.
=> src/SDL.c: add managarm support

src/audio/os2/SDL_os2audio.c, src/audio/os2/SDL_os2audio.h
- Fixes audio device detection and usage,
- Implements audio capture support,
- Refactors buffer handling to separate pointers to fill and drain buffers.
Based on patches by josch1710 and Lars Erdmann:
https://github.com/bitwiseworks/SDL2-os2/pull/7
P.S.: If this is accepted, consider for release-2.28.x or not?
=> os2 audio refactoring and capture support

.gitignore
I made a minor PR about pixelformats today, and I noticed this VS code folder popped into the diff. I figure it should just be gitignored. Other IDEs have specific gitignore entries already. Maybe this will save someone a second in the future if they accidentally commit things from the `.vscode` folder.
None
=> Add VS code directory to gitignore

src/events/SDL_mouse.c, src/events/SDL_mouse_c.h, src/video/SDL_video.c
The mouse->CreateCursor function pointer will always be null if checked before the video backend is initialized, so a dummy default cursor with null internal structure pointers was being created in all cases, not just for backends lacking cursor functionality. Move the check to after the video subsystem is initialized, when the function pointer check is valid.
Passing this dummy cursor with null internal structures to the Wayland backend would cause a crash, as it requires the internal cursor structures to be valid in order to store cursor backing data, even for default system cursors.
=> Try to create the dummy mouse cursor after video backend initialization

src/joystick/SDL_gamepad.c
Looks like a `break` is missing for this `case`.
None. It does not generate any bug because the same mapping is appended a second time for some buttons.
=> Add missing break

CMakeLists.txt
Allow predefine SDL_REVISION without creating VERSION.txt file.
Fix for https://github.com/libsdl-org/SDL/issues/7561
=> Allow predefine SDL_REVISION

src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandvideo.c
Fix some memory leaks reported by Valgrind due to not destroying objects. `wl_display_sync()` returns a pointer to a `wl_callback`, which was being ignored and never destroyed, causing a leak. Created xdg_output and primary_selection_device objects were not being destroyed either.
Fixes #8056
=> wayland: Fix memory leaks

.github/workflows/main.yml, CMakeLists.txt
- ~Move all SDL_test related headers to `SDL3_test` instead of `SDL3`.~
- Don't build a `SDL3-test` Apple framework
Does not address #8062 anymore :clown_face:
=> cmake: Don't build SDL3-static Apple framework

src/video/SDL_sysvideo.h, src/video/SDL_video.c, src/video/android/SDL_androidvideo.c, src/video/cocoa/SDL_cocoaevents.m, src/video/cocoa/SDL_cocoamodes.m, src/video/cocoa/SDL_cocoawindow.m, src/video/n3ds/SDL_n3dsvideo.c, src/video/uikit/SDL_uikitmodes.m, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandwindow.c, src/video/windows/SDL_windowsmodes.c, src/video/x11/SDL_x11messagebox.c, src/video/x11/SDL_x11modes.c, src/video/x11/SDL_x11video.c
This fixes current_mode from pointing at the wrong data when displays are moved around
=> Allocate displays as an array of pointers instead of an array of objects

src/video/SDL_video.c
As offscreen is enabled in CMakeLists.txt, we get a blanks window
otherwise.
From a patch by Silvan Scherrer, at Bitwiseworks' fork.
NOTE: One might think of the same as NGAGE driver: Should I move it
before offscreen too?
=> SDL_video.c: move os2 video before offscreen.

src/SDL.c, src/core/SDL_runapp.c, src/core/windows/SDL_windows.h, src/thread/windows/SDL_systhread.c
Port of original SDL2 patch by Christopher Wellons (@skeeto, #7607)
to SDL3. As it turns out, our cmake build system had never added
`-mpreferred-stack-boundary=2` to any CFLAGS, so this is necessary
in SDL3.
It does not touch SDL_main headers, but applies the attribute to
`SDL_RunApp` instead.
@icculus, @slouken: Please review for correctness and any possible
places missed.
CC: @skeeto as author of original patch, @DanielGibson as author of
SDL3 main stuff.
Closes: https://github.com/libsdl-org/SDL/issues/8075
=> Unaligned stacks on i686-w64-mingw32 may lead to crashes  (SDL3.)

include/SDL3/SDL_audio.h, src/audio/SDL_wave.c, src/dynapi/SDL_dynapi_procs.h
Commit bea99d4 was partially reverted by 905c4ff "audio: First shot at the SDL3 audio subsystem redesign!"
This commit also modified error management of `SDL_LoadWAV_RW()`, so reapplying it is needed to respect the `freesrc` parameter.
None
=> Reapply "Changed 'freesrc' parameter from int to SDL_bool" to SDL_wave.c

.clang-tidy, src/audio/SDL_audio.c
And add diagnostic that allows to find this kind of issue in clang-tidy.
Clang has a warning for this but it doesn't work on the SDL version of standard functions. It works in clang tidy because SDL function are redifined as standart function (https://github.com/libsdl-org/SDL/blob/main/include/SDL3/SDL_stdinc.h#L719).
None
=> Fix size of memcpy in SDL_AudioDeviceFormatChangedAlreadyLocked

src/audio/alsa/SDL_alsa_audio.c
if there are 2 devices and `match` is NULL, then one of the device is not the default and NULL is passed to `SDL_strncmp()`.
None
=> Don't pass NULL to strncmp

src/stdlib/SDL_string.c, test/testautomation_stdlib.c
This code wasn't actually tested by the `9.9999999f` case, because that value is actually equal to `10.0f`.
Some of the previously incorrect results, as shown by the updated set of tests:
```
expected: '1.000000', got: '11.000000'
expected: '-10.00000', got: '1.0.00000'
expected: '-10', got: '1.0'
```
=> Fixed rounding up in SDL_PrintFloat

test/CMakeLists.txt
According to #8088 it has no value as an automated test, and by default it takes long enough to hit the default test timeout.
Resolves: #8088
=> test: Don't flag testsurround as suitable for non-interactive use

src/joystick/linux/SDL_sysjoystick.c
Found with `-fsanitize=undefined`:
SDL3/src/joystick/linux/SDL_sysjoystick.c:1152:42: runtime error: index -8 out of bounds for type 'SDL_bool [4]'
Nobody noticed because the `hwdata` structure is memset to 0 so the condition was false as expected.
=> Fix out of bound read of 'has_hat' array

src/stdlib/SDL_string.c
Fix an overflow when using `%hd` in `SDL_sscanf`.
This happened with the clang toolchains of msys2.
For example, see [this ci output](https://github.com/libsdl-org/sdl2-compat/actions/runs/5803154544/job/15730733338?pr=97#step:10:7114).
Because `SDL_sscanf` always wrote the parsed integer as a 32-bit integer, it overflowed into other data on the stack.
The automation test catched this issue because `expected_result` got corrupted (=zeroed).
https://github.com/libsdl-org/SDL/blob/9129e1d5577ef2eeaa7008eee14473dcf27d92c3/test/testautomation_stdlib.c#L620-L639
=> Fix overflow with SDL_sscanf(..., "%hd", ...)

include/SDL3/SDL_assert.h
`ebreak` acts like int3 for x86, giving control of running process to debuggers.
=> SDL_TriggerBreakppoint for riscv arch (both 32/64) version.

src/audio/SDL_audiocvt.c
This fixes audio playback noise on big endian systems as SDL_AUDIO_F32 means SDL_AUDIO_F32LSB.
I have tested this change on an X64 Linux system using loopwave and testmultiaudio. I have "simulated" the original issue on the same little endian system by using SDL_AUDIO_F32MSB instead of SDL_AUDIO_F32 and it triggers the noise.
=> Convert audio using SDL_AUDIO_F32SYS format instead of SDL_AUDIO_F32

CMakeLists.txt, src/hidapi/SDL_hidapi.c
When combining both libusb and an OS backend for SDL_hidapi, we want to ensure that libusb is only used when absolutely necessary. At the same time, we don't want to interfere with platforms that _only_ have libusb. So, implement a whitelist but only use it when another backend exists.
With this in place, it should now be safe to enable libusb support by default.
Affects SDL_hidapi (Sam), configure.ac (Ozkan), and CMake (Anon).
Fixes #6005
=> Add support for libusb device whitelisting

include/SDL3/SDL_video.h, src/video/cocoa/SDL_cocoawindow.m, src/video/wayland/SDL_waylandwindow.c, src/video/x11/SDL_x11events.c, src/video/x11/SDL_x11window.c
SDL considers a hidden window to be unmapped and blocks or defers certain operations until the window is shown again, however, the X11 and Cocoa backends would set the hidden flag when the window was minimized, which blocked the functionality of SDL_RestoreWindow().
This specifies that a window with the hidden flag set is unmapped and not visible on the desktop or in the dock/taskbar/window list without a call to SDL_ShowWindow(), and doesn't set the hidden flag in the X11 and Cocoa backends when the window is in the minimized state, but still mapped to the desktop. The occluded flag is more suitable in these cases (macOS sets it explicitly on miniaturized windows, and we can set it implicitly when X11 windows are 'hidden', but still mapped).
There is some prior art here too, as both GTK …
=> Clarify that a window being 'hidden' means that it is unmapped/ordered out

src/audio/SDL_audiocvt.c, src/audio/SDL_audiotypecvt.c, test/testautomation_audio.c
Noticed these functions were quite sub-optimal so decided to optimize them. There were a few options but bithacking seems to be the fastest for 8/16-bit, with the instructions available in SSE2.
A few observations/questions:
* Do we still need bother with the alignment logic for SSE? I think generally we've moved to unaligned loads/stores because there is no real performance difference.
* Is there a specific reason for shifting before converting to a float (`((float)(src[i] >> 8)) * DIVBY8388607)`)? If the number doesn't fit in the mantissa the least significant bits will be discarded. Plus shifting by 8 leaves you with 24 bits, so not all numbers will fit anyway.
=> Improved audio format converters

src/video/windows/SDL_windowswindow.c
Use DWM to create a "sheet of glass" effect for the Win32 window.
Unfortunately, this only works for OpenGL, and it's all I know works for now
This is my first PR for SDL, so I'm not familiar with how the files interact with each other, etc.
=> Transparent window for Win32 + OpenGL

VisualC-GDK/SDL/SDL.vcxproj, VisualC-GDK/SDL/SDL.vcxproj.filters, docs/README-gdk.md, include/SDL_system.h, src/core/gdk/SDL_gdk.cpp, src/filesystem/gdk/SDL_sysfilesystem.cpp, src/filesystem/windows/SDL_sysfilesystem.c
This adds some features that are _really_ helpful for single-player titles that don't need a lot of fancy user management and want to reuse their existing desktop work.
Marked as a draft until I get this stuff through cert! Also, this targets SDL2 instead of SDL3, for now.
=> gdk: Add SDL_GDKGetDefaultUser, SDL_GetPrefPath implementation

src/audio/SDL_audiocvt.c
Non-euclidean division is a pain.
#8155
=> Fixed GetResamplerAvailableOutputFrames

cmake/sdlchecks.cmake
avoids false positives when using a cross-toolchain file (which happened
to me on linux when configuring for windows.)
@madebr: My patch may not be fully correct, so please review and apply a
different solution if necessary.
SDL2 may or may not have the same issue -- not tested it.
=> cmake: check linkage to libusb too, instead of libusb.h presence only.

src/hidapi/libusb/hid.c, src/hidapi/linux/hid.c
This applies mainstream commit [8a4de63b](https://github.com/libusb/hidapi/pull/601) (mainstream [PR/601](https://github.com/libusb/hidapi/pull/601)) to our
hidapi. The patch is a direct apply of the mentioned commit, with one sdl-
specific part guarded by HIDAPI_IGNORE_DEVICE adapted accordingly.
=> hidapi: sync the hidraw changes with mainstream

include/SDL3/SDL_test_memory.h, src/audio/SDL_audiocvt.c, src/test/SDL_test_common.c, src/test/SDL_test_memory.c, test/testautomation_audio.c
A small collection of audio-related fixes, plus added the `--randmem` argument to hopefully make finding uninitialized data issues easier.
#8164
=> Audio fixes and randmem test argument

src/video/wayland/SDL_waylanddyn.c
These defines mess with `#ifdef` conditionals in headers
Fixes #8183
=> wayland: don't define SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_* macro's

include/SDL3/SDL_hints.h, src/render/metal/SDL_render_metal.m
Metal API allow device selection based on capabilities.
Low power consumption is one of them and in some case like video rendering (e.g. ffplay) a low power device is enough for display.
This PR add a hint to ask for a low power device.
If no such device respect the hint, the default device is selected as before.
On some system like MacBook Pro Intel with AMD card, asking for the default device will always return the AMD GPU.
This is not an issue for 99% of the case when the renderer context is here to provide the maximum performance level like for game.
However, for video application using GPU for 1 quad and 1 texture, using the discrete GPU for that lead to an important power consumption (4 to 8W), heat increase, and fan noise.
With this patch, I successfully amend ffplay to only use …
=> metal: Add hint to select low power device instead of the default one

docs/README-wayland.md
Wayland doesn't support programmatically setting the app icon, so note this restriction and specify that a desktop entry file that points to the desired icon image is required.
Closes #8170
=> docs: Add note about Wayland application icons

include/SDL3/SDL_audio.h, src/audio/SDL_audio.c, src/audio/SDL_audiocvt.c, src/audio/SDL_sysaudio.h, src/dynapi/SDL_dynapi.sym, src/dynapi/SDL_dynapi_overrides.h, src/dynapi/SDL_dynapi_procs.h, test/testaudiostreamdynamicresample.c, test/testautomation_audio.c
Renamed SDL_(Get|Set)AudioStreamSpeed to SDL_(Get|Set)AudioStreamFrequencyRatio based on the feedback in #8181.
Also included a few other audio fixes that I noticed.
Perhaps the non-endian-explicit audio formats should be removed? I seem to remember this being discussed a while ago, and I'm pretty some of the other uses of the in SDL are also wrong, but these were the obvious ones.
=> Renamed AudioStreamSpeed to AudioStreamFrequencyRatio + Fixes

src/joystick/SDL_joystick.c
This adds the missing vendor + product id for the Logitech PRO Racing Wheel for Xbox (PC mode)
=> Detect Logitech PRO Racing Wheel for Xbox as wheel

src/joystick/SDL_joystick.c
This adds the missing vendor + product id for the Logitech G923 Racing Wheel in PC and PS4/PS5 mode.
G923 have two different versions - Xbox version is already present in the wheel list, but not the PS version
=> Detect Logitech G923 Playstation as wheel

src/joystick/SDL_joystick.c
This adds the missing vendor + product id for the Simagic wheel bases, including M10, Alpha Mini, Alpha, Alpha U
=> Detect Simagic wheel bases as wheels

build-scripts/wikiheaders.pl
Implements [this suggestion](https://github.com/libsdl-org/SDL_mixer/pull/552#issuecomment-1708302299) by @icculus 
> What if, instead of printing warnings, it generates a wiki page called "Undocumented.md" that updates on each run? That way we would have a public list of things that lack documentation.
I've kept the `warn_about_missing` option alone, so you can still run the perl script with `--warn-about-missing`.
For SDL3, this will generate `Undocumented.md` with the following contents:
<details>
<summary>Undocumented.md</summary>
```
- [SDL_calloc](SDL_calloc)
- [SDL_ulltoa](SDL_ulltoa)
- [SDL_wcslen](SDL_wcslen)
- [SDL_strtoul](SDL_strtoul)
- [SDL_atoi](SDL_atoi)
- [SDL_strtoull](SDL_strtoull)
- [SDL_wcsnlen](SDL_wcsnlen)
- [SDL_asinf](SDL_asinf)
- [SDL_fabsf](SDL_fabsf)
- …
```
=> wikiheaders.pl: create Unsupported.md file with list of functions undocumented in either the headers or the wiki

src/render/SDL_render.c
Battle for Wesnoth apparently relies on being able to disable rendering of UI elements by setting the clip rectangle to be empty.
Resolves: https://github.com/libsdl-org/SDL/issues/6896
Fixes: 00f05dcf "render: only enable clipping when the rectangle is valid"
---
Untested, but it seems to be what commenters on #6896 are asking for.
@lukegrahamSydney, if your game is using SDL 3, please try this and confirm whether it fixes whatever issue you are seeing? Or if your game is using SDL 2, please test #8229 instead.
=> [SDL3] render: Enable clipping for zero-sized rectangles

src/render/SDL_render.c
Battle for Wesnoth apparently relies on being able to disable rendering of UI elements by setting the clip rectangle to be empty.
Resolves: https://github.com/libsdl-org/SDL/issues/6896
Fixes: 00f05dcf "render: only enable clipping when the rectangle is valid"
---
SDL 2 version of #8228, which doesn't cherry-pick trivially to SDL 2 since adjacent code has changed. Untested, but it seems to be what commenters on https://github.com/libsdl-org/SDL/issues/6896 are asking for.
@Pentarctagon, please could you confirm whether a SDL 2 with this change fixes the GUI issues you see in Wesnoth?
@lukegrahamSydney, if your game is using SDL 2, same question for your game? Or if your game is using SDL 3, please test #8228 instead.
=> [SDL2] render: Enable clipping for zero-sized rectangles

src/video/wayland/SDL_waylandevents.c
The data device leave function is intended for drag offers, not selections, and the function as was previously written was a no-op.
=> wayland: Fix drag offer leak

src/video/windows/SDL_windowswindow.c
Windows: fix for client rect resizing larger each time we came from exclusive fullscreen -> windowed on a monitor with HiDPI set.  The problem was we were using the monitor DPI rather than the window DPI so AdjustWindowRectExForDpi was giving us an incorrect size which would be too large for the client rect.  
Closes #8237.
=> Windows: fix for client rect resizing larger each time we came from exclusive fullscreen.

src/video/x11/SDL_x11clipboard.c
Without this PR, if the clipboard is set multiple times from the same SDL application, clipboard managers fail to pick up the changes.
This should be cherry-picked for SDL2.
lite-xl/lite-xl#1610
=> x11: Always update clipboard owner

VisualC-GDK/SDL/SDL.vcxproj, VisualC-GDK/SDL/SDL.vcxproj.filters, VisualC-WinRT/SDL-UWP.vcxproj, VisualC-WinRT/SDL-UWP.vcxproj.filters, VisualC/SDL/SDL.vcxproj, VisualC/SDL/SDL.vcxproj.filters, src/audio/SDL_audiocvt.c, src/audio/SDL_audioqueue.c, src/audio/SDL_audioqueue.h, src/audio/SDL_audioresample.c, src/audio/SDL_audioresample.h, src/audio/SDL_sysaudio.h, test/testaudiostreamdynamicresample.c, test/testautomation_audio.c
The naming and semantics need some tweaking, but the idea is to allow queueing audio without having to copy it in, as well being able to loop the audio (possibly forever).
Also makes a nice excuse to do a large round of refactoring :)
iOS builds are broken because I don't know how to update the pbxproj file.
=> Refactor SDL_audiocvt.c

src/audio/SDL_audio.c
Return as soon as `SDL_CreateAudioStream()` or `SDL_BindAudioStream()` fail. Otherwise field `simplified` is accessed from NULL `stream` pointer.
None
=> Fix NULL dereference in SDL_OpenAudio

include/SDL3/SDL_events.h, src/audio/SDL_audio.c, src/audio/SDL_audiocvt.c, src/audio/SDL_sysaudio.h, src/events/SDL_events.c
This fires if an opened device changes formats (which it can on Windows, if the user changes this in the system control panel, and WASAPI can report), or if a default device migrates to new hardware and the format doesn't match.
This will fire for all logical devices on a physical device (and if it's a format change and not a default device change, it'll fire for the physical device too, but that's honestly not that useful and might change).
Fixes #8267.
=> audio: Added SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED

include/SDL3/SDL_audio.h, src/audio/SDL_audiocvt.c, src/audio/SDL_sysaudio.h, src/dynapi/SDL_dynapi.sym, src/dynapi/SDL_dynapi_overrides.h, src/dynapi/SDL_dynapi_procs.h, test/loopwave.c
This adds SDL_GetAudioStreamQueued, for reporting the amount of data still pending in an SDL_AudioStream.
It reports in sample frames, not bytes. See the documentation in SDL_audio.h.
This makes an effort to track this value so we don't have to calculate it every time this function is called.
CC @0x1F9F1 and @slouken
=> audio: Added SDL_GetAudioStreamQueued

src/core/linux/SDL_dbus.c, src/core/linux/SDL_dbus.h, src/video/wayland/SDL_waylanddatamanager.h, src/video/wayland/SDL_waylandevents.c
Adds DnD path resolution for portals required for flatpak packages.
- ~[x] X11~ (I don't know enough X11 to work around the directory issue)
- ~[ ] Copy paste?~ (`SDL_DBus_DocumentsPortalRetrieveFiles` will also work for pasted files but that can be a future MR)
Adds a `SDL_DBus_DocumentsPortalRetrieveFiles` function to convert from dropped files with mime type `application/vnd.portal.filetransfer` using [RetrieveFiles](https://flatpak.github.io/xdg-desktop-portal/#gdbus-method-org-freedesktop-portal-FileTransfer.RetrieveFiles)
Reports support for dropped `application/vnd.portal.filetransfer` on wayland.
If the list of dropped files contains a directory the list of dropped files will be empty, this is the case even outside of flatpaks.
In the case the list is empty we'll fallback to …
=> linux: Add portal drag and drop

src/power/linux/SDL_syspower.c
On my laptop, the battery is configured to stop charging at around 80% most of the time, to increase the overall useful lifetime of the battery. When in that state, upower reports UP_DEVICE_STATE_PENDING_CHARGE (numeric value 5), which SDL previously mapped to SDL_POWERSTATE_UNKNOWN. This made the platform_testGetPowerInfo automated test fail, because it assumes that SDL_POWERSTATE_UNKNOWN means no battery is connected, and does not expect to see a percentage.
Map UP_DEVICE_STATE_PENDING_CHARGE (5) to SDL_POWERSTATE_CHARGED, which seems close enough.
Also map UP_DEVICE_STATE_PENDING_DISCHARGE (6) to
SDL_POWERSTATE_ON_BATTERY, which matches how at least GNOME presents it.
=> linux: Handle upower's UP_DEVICE_STATE_PENDING_CHARGE, PENDING_DISCHARGE

src/events/imKStoUCS.h
Presumably this is an accidental character due to the copyright symbol and conversion to/from different encodings. The *.c file does not have this character.
=> Remove stray Â

src/audio/aaudio/SDL_aaudio.c, src/audio/aaudio/SDL_aaudio.h, src/video/android/SDL_androidevents.c
The audio processing thread isn't scheduled in lock-step with the audio callback so sometimes the callback would consume the same data twice and sometimes the audio processing thread would write to the same buffer twice.
Also handle variable sizes in the audio callback so the Android audio system doesn't have to do additional buffering to match our buffer size requirements.
=> Fixed stuttering on Android when using the AAudio driver

src/audio/SDL_audio.c, src/audio/wasapi/SDL_wasapi.c, src/audio/wasapi/SDL_wasapi.h
Since these get proxied to a different thread, if we wait for that thread to finish while holding the lock, and the management thread _also_ requests the lock, we're screwed.
WaitDevice never holds the lock by design, so just mark devices as failed and clean up or recover them in there.
In the WASAPI backend, both playback and capture devices use the same WaitDevice implementation.
Putting this in a PR because I'm not near a Windows machine right now to test this until later today.
=> wasapi: Deal with device failures when we aren't holding the device lock

test/testautomation_math.c
We can't rely on irrational numbers like pi being represented exactly, particularly when compiling for i386, where the i387 floating-point interface carries out calculations in registers that have higher precision than the actual double-precision variable. The 1980s were a strange time.
Resolves: https://github.com/libsdl-org/SDL/issues/8311
=> test: Accept small numerical differences in more mathematical tests

src/test/SDL_test_compare.c
Previously, if acting on a surface with less than 32 bits per pixel, this code was placing the pixel value from the surface in the first few bytes of the Uint32 to be decoded, and unrelated data from a subsequent pixel in the remaining bytes.
Because SDL_GetRGBA takes the bits to be decoded from the least-significant bits of the given value, ignoring the higher-order bits if any, this happened to be correct on little-endian platforms, where the first few bytes store the least-significant bits of an integer.
However, it was incorrect on big-endian, where the first few bytes are the most-significant bits of an integer.
The previous implementation also assumed that unaligned access to a 32-bit quantity is possible, which is not the case on all CPUs (but happens to be true on x86).
These …
=> SDLTest_CompareSurfaces: Decode pixels correctly on big-endian platforms

src/events/SDL_mouse.c, src/events/SDL_mouse_c.h, src/video/SDL_video.c, src/video/dummy/SDL_nullvideo.c, test/testautomation_video.c
Backport of b8d9125 for SDL2 to fix the automated video tests using the dummy video driver.
Fixes #8308
Fixes #8309
=> [SDL2] Fix automated tests using the dummy video driver

test/testautomation_mouse.c
Wayland does not allow warping the mouse pointer, thus these tests are unreliable and should be skipped.
Fixes #8333
=> tests: Disable mouse warp test under Wayland

src/joystick/linux/SDL_sysjoystick.c
Set `has_accelerometer` and `has_gyro` to false if we can't read all axes' info.
And fix typo in comment "an "-> "a".
None
=> Do not report gyro/accelerometer if we can't read axes info

src/video/SDL_blit_slow.c
The destination pixels are read here:
https://github.com/libsdl-org/SDL/blob/49abb9c1fa954bf2fa3e8fdce6d99803c3701b05/src/video/SDL_blit_slow.c#L108-L117
but are discarded/overwritten here:
https://github.com/libsdl-org/SDL/blob/49abb9c1fa954bf2fa3e8fdce6d99803c3701b05/src/video/SDL_blit_slow.c#L135-L141
#8350  (needs backport to SDL2)
=> blit_slow: don't read destination pixel when you're going to discard it anyways

src/test/SDL_test_compare.c
* SDLTest_CompareSurfaces: Log better messages if NULL or different sizes
* SDLTest_CompareSurfaces: If surfaces differ, log their formats
* SDLTest_CompareSurfaces: Output RGBA values of first differing pixel
---
I used this to get better information out of #8315.
=> Improve ability to debug failed surface comparisons

src/joystick/linux/SDL_sysjoystick.c
Calling `LINUX_JoystickSetSensorsEnabled()` after the joystick is unplugged will trigger this assertion. `item_sensor` is set to NULL by `RemoveSensorlistItem()`.
None
=> Fix assertion in LINUX_JoystickSetSensorsEnabled()

src/video/wayland/SDL_waylandmessagebox.c
On Counter Strike 2, when running under wayland, version_str is null, causing a crash. There's probably an underlying issue in the steam runtime, but we should still have a null check here regardless.
=> wayland: Add null check for zenity version string

src/joystick/linux/SDL_sysjoystick.c, src/joystick/linux/SDL_sysjoystick_c.h
Backports @meyraud705's changes from #7697 to SDL 2.
This work copies the original implementation as faithfully as possible, without modifying the core systems it touches. Notable deviations from the original PR:
- Use of `M_PI` instead of `SDL_PI_F`
- Proactive inclusion of sensor detection changes from #7945 and cleanup from fd062657dd2d9afb151f71beb0d35caca5d5c36c
- Calls `SDL_PrivateJoystickSensor(...)` instead of `SDL_SendJoystickSensor(...)`. `SDL_PrivateJoystickSensor` lacks the `timestamp` field and operates on microseconds instead of nanoseconds, but appears to be used in the same way.
=> Backport #7697 to SDL 2

include/SDL3/SDL_test_compare.h, src/test/SDL_test_compare.c, src/video/SDL_shape.c, src/video/SDL_surface.c, src/video/SDL_surface_pixel_impl.h, src/video/SDL_video_c.h, test/testshape.c
* test: Extract SDLTest_ReadSurfacePixel
This is essentially the same as was added in d95d2d70, but with clearer
error handling. It's implemented in a private header file so that it
can be shared with SDL_shape, which also wants this functionality.
Resolves: https://github.com/libsdl-org/SDL/issues/8319
* surface: Add a private SDL_ReadSurfacePixel
This shares its implementation with SDLTest_ReadSurfacePixel: the same
code is compiled twice, to get it into the static test library and also
the public shared library.
* shape: Use SDL[Test]_ReadSurfacePixel
This avoids assuming that the pixels are suitably aligned for direct
access, which there's no guarantee that they are; in particular,
3-bytes-per-pixel RGB images are likely to have 3 out of 4 pixels
misaligned. On x86, dereferencing a …
=> Add internal function to read individual pixels from a surface

include/SDL3/SDL_pixels.h, include/SDL3/SDL_surface.h
* pixels: Document the naming convention
Whenever I have to fix something endianness-related, I always get
confused about whether the byte-oriented format that guarantees to put
red in byte 0 is RGBA8888 or RGBA32. (The answer is that it's RGBA32.)
* surface: Document the in-memory layout of the pixels
I don't think we ever explicitly said this.
Prompted by #8315.
=> Document pixel format naming convention and surface format

src/audio/SDL_audiotypecvt.c
We need to do this early in the file, so that it will be taken into account when deciding whether to define NEED_SCALAR_CONVERTER_FALLBACKS and therefore provide a non-SIMD fallback.
Mitigates: https://github.com/libsdl-org/SDL/issues/8352
=> audio: Disable NEON sample conversion until test failures are fixed

src/video/cocoa/SDL_cocoamouse.m, src/video/cocoa/SDL_cocoawindow.m
Fixes #8190.
From #7249, reverted the hunks other than #7239 and further modified them to match the current code.
=> Fix a malfunction of SDL_HideCursor()

src/SDL.c, src/SDL_internal.h, src/joystick/SDL_joystick.c, src/joystick/SDL_joystick_c.h, src/joystick/android/SDL_sysjoystick.c, src/joystick/apple/SDL_mfijoystick.m, src/joystick/bsd/SDL_bsdjoystick.c, src/joystick/darwin/SDL_iokitjoystick.c, src/joystick/hidapi/SDL_hidapijoystick.c, src/joystick/linux/SDL_sysjoystick.c, src/joystick/virtual/SDL_virtualjoystick.c, src/joystick/windows/SDL_rawinputjoystick.c, src/joystick/windows/SDL_windows_gaming_input.c, src/joystick/windows/SDL_windowsjoystick.c, src/sensor/SDL_sensor.c, src/sensor/SDL_sensor_c.h, src/sensor/android/SDL_androidsensor.c, src/sensor/coremotion/SDL_coremotionsensor.m, src/sensor/n3ds/SDL_n3dssensor.c, src/sensor/vita/SDL_vitasensor.c, src/sensor/windows/SDL_windowssensor.c, src/video/SDL_sysvideo.h, src/video/SDL_video.c
This ensures that we don't accidentally interpret an ID from one system as an ID in another system. Audio device IDs are not covered here, since they have a unique numbering system.
=> Added a single source of SDL object IDs

src/audio/n3ds/SDL_n3dsaudio.c, src/audio/n3ds/SDL_n3dsaudio.h, src/thread/n3ds/SDL_systhread.c
* SDL_n3dsaudio.c: separate mixer locks from audio device locks
* SDL_n3dsaudio.h: use triple buffer by default
* SDL2: fix 3DS mixer thread stack overflows
* SDL_n3dsaudio.c: don't leave priority uninitialized
* SDL_systhread.c: attempt to put audio thread on system core
* Comment and style fixes
This is a set of fixes to improve the stability of audio processing on 3DS made by me and @ds-sloth.
- Audio needs a different priority setup in order to don't slow-down the main thread and don't lead the choppy playback on using some heavier codec libraries.
- Audio needs a bigger stack size, otherwise it leads a memory data damage because of some custom codec libraries that allocate more memory size than stack allows.
- The own audio lock is redundant as SDL does it already, and this may lead …
=> Fixes for the 3DS Audio

src/video/wayland/SDL_waylandevents.c
If the relative protocol is unsupported, this will always be null and the destroy function won't be called.
Fixes #8444
=> wayland: Check the relative pointer handle before destroying

CMakeLists.txt, VisualC-GDK/SDL/SDL.vcxproj, VisualC-GDK/SDL/SDL.vcxproj.filters, VisualC-WinRT/SDL-UWP.vcxproj, VisualC-WinRT/SDL-UWP.vcxproj.filters, VisualC/SDL/SDL.vcxproj, VisualC/SDL/SDL.vcxproj.filters, Xcode/SDL/SDL.xcodeproj/project.pbxproj, include/SDL3/SDL_hints.h, include/SDL3/SDL_main.h, include/SDL3/SDL_main_impl.h, include/SDL3/SDL_test_common.h, src/dynapi/SDL_dynapi.sym, src/dynapi/SDL_dynapi_overrides.h, src/dynapi/SDL_dynapi_procs.h, src/main/SDL_main_callbacks.c, src/main/SDL_main_callbacks.h, src/main/emscripten/SDL_sysmain_callbacks.c, src/main/generic/SDL_sysmain_callbacks.c, src/main/ios/SDL_sysmain_callbacks.m, src/test/SDL_test_common.c, test/CMakeLists.txt, test/loopwave.c, test/testaudio.c, test/testaudiocapture.c, test/testsprite.c
**EDIT: updated this on 10/29/2023 with SDL_AppEvent details, etc.**
This lets apps optionally have a handful of callbacks for their entry points instead of a single `main` function. If used, the actual main/SDL_main/whatever entry point will be implemented in the single-header library SDL_main.h and the app will implement four separate functions:
First:
```c
int SDL_AppInit(int argc, char **argv);
```
This will be called _once_ before anything else. argc/argv work like they always do. If this returns 0, the app runs. If it returns < 0, the app calls SDL_AppQuit and terminates with an exit code that reports an error to the platform. If it returns > 0, the app calls SDL_AppQuit and terminates with an exit code that reports success to the platform. This function should not go into an …
=> main: Added _optional_ callback entry points.

CMakeLists.txt
I think removing the check for `linux/input.h` from within the `if(SDL_LIBC)` block and merging it with the check for `linux/input.h` and `EVIOCGNAME` is fine.
I preprocessed `/usr/include/linux/input.h` and no c library header is included.
Eligible for 2.28.x
Fixes #8450
=> cmake: fold HAVE_INPUT_EVENTS into HAVE_LINUX_INPUT_H

VisualC/tests/testautomation/testautomation.vcxproj, src/SDL.c, test/testautomation.c, test/testautomation_subsystems.c, test/testautomation_suites.h
This applies to subsystem dependencies such as Joystick necessary for Gamepad, Events needed for multiple other systems.
Existing code is erroneous, because it adds or removes dependency's ref count based on number of InitSubSystem/QuitSubSystem calls, while ref count diff should depend on number of inited or quit dependents. Recursive approach seems to be simplest solution that guarantees proper ref count. I hope it's okay to do this as supposedly this should not affect performance much.
Used following code sample to test its work:
```
// Init 3 subsystems separately
SDL_InitSubSystem(SDL_INIT_VIDEO); // +1 EVENTS ref count
SDL_assert(SDL_WasInit(SDL_INIT_VIDEO | SDL_INIT_EVENTS) == SDL_INIT_VIDEO | SDL_INIT_EVENTS);
SDL_InitSubSystem(SDL_INIT_AUDIO); // +1 EVENTS ref count …
```
=> Handle subsystem dependencies recursively

include/SDL3/SDL_events.h, src/core/android/SDL_android.c, src/core/haiku/SDL_BeApp.cc, src/events/SDL_dropevents.c, src/events/SDL_dropevents_c.h, src/events/SDL_events.c, src/video/cocoa/SDL_cocoaevents.m, src/video/cocoa/SDL_cocoawindow.m, src/video/uikit/SDL_uikitappdelegate.m, src/video/wayland/SDL_waylandevents.c, src/video/windows/SDL_windowsevents.c, src/video/x11/SDL_x11events.c
This is only implemented on iOS, but is useful for third party application integrations.
Fixes https://github.com/libsdl-org/SDL/issues/2024
=> Add the source application for drag and drop events (thanks Nathan!)

docs/README-migration.md, include/SDL3/SDL_events.h, src/events/SDL_events.c, src/events/SDL_keyboard.c, test/checkkeys.c, test/checkkeysthreads.c, test/testcontroller.c, test/testime.c
This prevents input text from being split across Unicode combining or modifier characters, and in practice allocations will rarely happen.
=> Dynamically allocate long text for SDL_EVENT_TEXT_INPUT events

src/events/SDL_events.c
Added a case where the event type is SDL_EVENT_DROP_FILE to SDL_CopyEvent().
=> Fix dropping file event

android-project/app/src/main/java/org/libsdl/app/SDLSurface.java, src/video/emscripten/SDL_emscriptenevents.c, src/video/n3ds/SDL_n3dstouch.c, src/video/vita/SDL_vitatouch.c, src/video/wayland/SDL_waylandevents.c, src/video/windows/SDL_windowsevents.c
When converting normalized coordinates to pixel coordinates, the valid range is 0 to (width or height) - 1, and the pixel coordinate of width or height is past the edge of the window.
Fixes https://github.com/libsdl-org/SDL/issues/2913
=> Fixed touch normalized coordinates

cmake/sdlchecks.cmake
Clarified the comment to explain why the `SDL_X11_SHARED` is disabled on Apple platforms.
#6778
=> [SDL2] sdlchecks.cmake: Clarified the reason why shared X11 mode doesn't work

cmake/sdlchecks.cmake
Same as #8505, but for SDL3
Clarified the comment to explain why the `SDL_X11_SHARED` is disabled on Apple platforms.
#6778
=> [SDL3] sdlchecks.cmake: Clarified the reason why shared X11 mode doesn't work

src/core/freebsd/SDL_evdev_kbd_freebsd.c, src/core/linux/SDL_evdev.c, src/core/linux/SDL_evdev.h, src/core/linux/SDL_evdev_kbd.c, src/core/linux/SDL_evdev_kbd.h, src/video/kmsdrm/SDL_kmsdrmopengles.c, src/video/kmsdrm/SDL_kmsdrmsym.h, src/video/kmsdrm/SDL_kmsdrmvideo.c
Fixes https://github.com/libsdl-org/SDL/issues/3844
@vanfanel, @inolen, can you review this? I'm not sure what to do for Vulkan windows.
=> Implemented VT switching for KMSDRM on Linux

src/test/SDL_test_memory.c
`dbghelp_SymFromAddr` is checked twice, `dbghelp_SymInitialize` is not checked.
None
=> Fix condition in SDLTest_TrackAllocations()

src/SDL_properties.c
If SDL_CreateHashTable() fails, properties->lock is not initialised, SDL_FreeProperties() is called and destroys the uninitialised lock.
None
=> Fix uninitialised variable 'properties'

src/events/SDL_dropevents.c
Free event.drop.source in case of error.
None
=> Fix memory leak in SDL_SendDrop()

src/joystick/SDL_gamepad.c, src/joystick/windows/SDL_rawinputjoystick.c, src/thread/SDL_thread.c, src/video/kmsdrm/SDL_kmsdrmvideo.c, src/video/wayland/SDL_waylandmouse.c, src/video/wayland/SDL_waylandwindow.c, src/video/x11/SDL_x11window.c
You need a temporary variable when reallocating.
Note that in most case the size of the array was not set to 0 when realloc fails and it would lead to NULL dereference later.
None
=> Don't leak if realloc fails

src/video/wayland/SDL_waylandvideo.c
`driverdata->width` and `driverdata->height` represent the width and height in logical pixels on scaled outputs with xdg_output. However, to correctly calculate the display's DPI value, we need to use its native resolution.
For example, on a 27" 4K screen with 175% scaling, we have `width` == 2192 and `height` == 1233, resulting in a bogus value of 92dpi, whereas 162dpi are correct for 3840x2160 pixels at 27 inches.
Tested on GNOME mutter 45.1.
=> wayland: Fix DPI calculation with scaled outputs

include/SDL3/SDL_events.h
... to preserve compatibility with sdl2-compat.
CC: @creichen
=> move SDL_EVENT_WINDOW_PEN_ENTER and SDL_EVENT_WINDOW_PEN_LEAVE down

src/cpuinfo/SDL_cpuinfo.c
Rework the code to clearly prefer 64-bit sysctls first, then legacy sysctls, and eliminate a second ifdef.
HW_PHYSMEM64: https://github.com/NetBSD/src/commit/9e7bb2595ef5b2d59e74dc036b67e6b0efe842c8
HW_REALMEM: https://github.com/freebsd/freebsd-src/commit/a09150446db803d356fd7058462a595bdb114f0e
HW_MEMSIZE: https://opensource.apple.com/source/xnu/xnu-1456.1.26/bsd/sys/sysctl.h.auto.html
=> cpuinfo: Fix detection of physical memory above 2GB on NetBSD

src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandmouse.c, src/video/wayland/SDL_waylandmouse.h, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h, src/video/x11/SDL_x11events.c, src/video/x11/SDL_x11events.h, src/video/x11/SDL_x11mouse.c, src/video/x11/SDL_x11mouse.h, src/video/x11/SDL_x11window.c, src/video/x11/SDL_x11window.h, src/video/x11/SDL_x11xinput2.c
Hit testing on X11 and Wayland should now behave more like it does on Windows - the current active zone is tracked on mouse motion events and the cursor is changed accordingly when hovering a "special" zone (such as the resize handles).
- when set, the hit testing callback is now called from the `MotionNotify`/`XI_Motion`/`wl_pointer::motion` handlers (depending on the active video driver and library configuration). When the callback returns `SDL_HITTEST_RESIZE_*` the mouse cursor is temporarily set to the corresponding system cursor.
- `SDL_WindowData` for X11/Wayland has been extended with e `hit_test_result` member that records the result of the last hit test
- `ButtonPress`/`XI_ButtonPress`/`wl_pointer::button` handlers trigger the corresponding action (window resize/move) based on …
=> Hit testing tweaks for X11 and Wayland

src/video/windows/SDL_windowsmouse.c
Should work better for bigger masks.
=> Use SDL_small_alloc() instead of SDL_stack_alloc() in CreateMaskBitmap()

android-project/app/src/main/java/org/libsdl/app/SDLActivity.java, include/SDL3/SDL_mouse.h, src/video/cocoa/SDL_cocoamouse.m, src/video/emscripten/SDL_emscriptenmouse.c, src/video/haiku/SDL_bvideo.cc, src/video/wayland/SDL_waylandmouse.c, src/video/windows/SDL_windowsmouse.c, src/video/winrt/SDL_winrtmouse.cpp, src/video/x11/SDL_x11mouse.c, test/testcustomcursor.c
This PR makes X11/Wayland hit testing resize hover cursors match Linux usage of 8 unique (single arrow with edge/corner) cursors for each side/corner.
Currently SDL tries to mimic Windows double arrows when hovering and then the compositor switches to 8 direction cursors when the mouse is clicked.
The cursors are added as SDL_SYSTEM_CURSOR_WINDOW_TOPLEFT, etc matching the SDL_HITTEST_RESIZE_TOPLEFT names and order. X11/Wayland have new cursors. Other platforms use the existing SIZE cursors.
These should not replace SDL_SYSTEM_CURSOR_SIZENS, SIZEWE, etc as resizing a column/row in a window uses double arrows on Linux.
=> Add 8 direction cursors for X11/Wayland hit testing window resizing

src/joystick/haiku/SDL_haikujoystick.cc, src/joystick/n3ds/SDL_sysjoystick.c, src/joystick/ps2/SDL_sysjoystick.c, src/joystick/psp/SDL_sysjoystick.c, src/joystick/vita/SDL_sysjoystick.c
Fix joystick implementations returning invalid (0) device IDs
=> Fix joysticks returning invalid device IDs

CMakeLists.txt, include/build_config/SDL_build_config.h.cmake, src/stdlib/SDL_iconv.c
- check libiconv with a linkage test with iconv.h included
- check libc iconv with a linkage test with iconv.h included
and LIBICONV_PLUG defined (in case libiconv header is in
include path)
- add new configuration option to prefer iconv from libiconv,
if available, over the libc version: SDL_LIBICONV, defaults
to disabled.
- remove FindIconv + pkg_check_modules for iconv, and use our
manual iconv finding only
- change FreeBSD specific LIBICONV_PLUG define in SDL_iconv.c
to configuration result.
Tested on linux with and without libiconv installed.
This is SDL3 adaptation of #8602. @madebr: Please review.
=> revise iconv detection:

.github/workflows/cpactions.yml, CMakeLists.txt
Add NetBSD to test matrix
Building currently fails because of the following errors:
- ci installs libiconv. It cannot find the `iconv_open` symbol in the `iconv` library, but can find `iconv_open` in the C library.
Looking at [libiconv.h from netbsd](https://cdn.netbsd.org/pub/pkgsrc/packages/NetBSD/x86_64/9.3/All/), its header does `#define iconv_open libiconv_open` for all iconv symbols.
```
ld: CMakeFiles/SDL3-shared.dir/src/stdlib/SDL_iconv.c.o: in function `SDL_iconv_REAL':
SDL_iconv.c:(.text+0xc): undefined reference to `libiconv'
ld: CMakeFiles/SDL3-shared.dir/src/stdlib/SDL_iconv.c.o: in function `SDL_iconv_string_REAL':
SDL_iconv.c:(.text+0x91): undefined reference to `libiconv_open'
ld: SDL_iconv.c:(.text+0x140): undefined reference to `libiconv'
ld: SDL_iconv.c:(.text+0x1f3): …
```
=> ci: add NetBSD to test matrix

cmake/macros.cmake
CMP0087 does not exist until CMake 3.14. Trying to set it in CMake versions before 3.14 is an error.
=> Check if CMP0087 exists before setting it

src/video/x11/SDL_x11pen.c
xinput2_device_is_pen() was testing against default-zero values in the X11 Atom cache on at least the first round of detections, leading to imprecise detection.
The patch fixes two aspects of initialisation:
1. Ensure that the selector cache is always initialised in xinput2_device_is_pen().
2. Ensure that all X11 Atoms used in SDL_x11pen.c are instantiated if missing. This ensures that they are never None and avoids potential failures to detect hot-plugged tablet devices.
- fixes #8611 
@tilman3 for narrowing down the issue and an initial fix, verifying
=> X11 pen detection: fix misclassification due to improper init

src/video/windows/SDL_windowsopengl.c
Allow checking to see if we actually got an sRGB framebuffer on windows opengl
Update the value of framebuffer_srgb_capable based on the value of WGL_FRAMEBUFFER_SRGB_CAPABLE_ARB obtained from the driver
https://github.com/libsdl-org/SDL/issues/8632
=> Set framebuffer_srgb_capable to the actual value obtained

include/SDL3/SDL_keyboard.h
The original doc is hopelessly useless. Rect for what and why?
Based on what I read from X11/Wayland implementation. This is the same as 
* Qt's QInputMethod::setInputItemRectangle https://doc.qt.io/qt-6/qinputmethod.html#setInputItemRectangle
* GTK's gtk_im_context_set_cursor_location https://docs.gtk.org/gtk4/method.IMContext.set_cursor_location.html
It will set a cursor position so that native input methods will smartly avoid covering text being inputted.
Better doc.
None.
=> document the purpose of SDL_SetTextInputRect

src/core/winrt/SDL_winrtapp_direct3d.cpp, src/video/windows/SDL_windowsevents.c, src/video/winrt/SDL_winrtevents_c.h, src/video/winrt/SDL_winrtkeyboard.cpp, src/video/winrt/SDL_winrtvideo.cpp, src/video/winrt/SDL_winrtvideo_cpp.h
Characters outside Basic Multilingual Plane (BMP) are coded as so called "surrogate pair" in two separate UTF-16 character events. This works the same in Win32 and in UWP.
Simplified Win32 code and added UWP implementation.
Corresponding fix in API docs: https://github.com/MicrosoftDocs/winrt-api/pull/2428
=> UWP: Add support for supplementary Unicode characters input

src/render/direct3d/SDL_render_d3d.c, src/render/direct3d11/SDL_render_d3d11.c, src/render/direct3d12/SDL_render_d3d12.c, src/render/metal/SDL_render_metal.m, src/render/opengl/SDL_render_gl.c, src/render/opengles2/SDL_render_gles2.c, src/render/ps2/SDL_render_ps2.c, src/render/psp/SDL_render_psp.c, src/render/software/SDL_render_sw.c, src/render/vitagxm/SDL_render_vita_gxm.c
SDL_render: Call InvalidateCachedState to initialise some of driverdata values (eg '*_dirty' to 1).
At the earliest place, immediatly after driverdata is set. (Doing it in SDL_render.c, after creation, would be too late, because there're renderers that already use/change those values in the CreateRender() function).
not really tested with all renderers.
but, it seems a bug that we don't start/create the renderer with *_dirty to SDL_TRUE!
(see https://github.com/libsdl-org/SDL/pull/8616)
=> SDL_render: Call InvalidateCachedState to initialise some of driverdata

src/video/x11/SDL_x11window.h
=> x11: Move unrelated variables out of XFixes #ifdef

src/joystick/SDL_joystick.c, src/joystick/hidapi/SDL_hidapijoystick.c, src/joystick/usb_ids.h, src/joystick/windows/SDL_xinputjoystick.c
0x02fe is actually PID of Xbox Wireless Adapter for Windows 10 (Model 1790) and creates confusion.
Was added in  https://github.com/libsdl-org/SDL/commit/1031231b2922142940eaa2c26d9debe17e5e5f09
Here is USB descriptor dump: https://github.com/DJm00n/ControllersInfo/blob/master/xboxone/DescriptorDump_Adapter%20(Xbox%20Wireless%20Adapter%20for%20Windows).txt
PS: There was older version of receiver: Xbox Wireless Receiver (Model 1713). It have VID:045e PID: 02e6. [Ref](https://github.com/medusalix/xow/blob/d335d6024f8380f52767a7de67727d9b2f867871/dongle/dongle.h#L34C1-L35).
=> Use existing XUSB driver software PID 0x02a1 instead of PID 0x02fe

src/video/cocoa/SDL_cocoawindow.m
isZoomed always returns true if the window is not resizable, so the resizable flag needs to be checked as well.
Fixes #8684
=> cocoa: Check the resizable flag along with zoomed status when resizing

src/video/wayland/SDL_waylandevents.c
Compositors may switch from mouse to touch mode when a touch event is received, causing a pointer leave event and subsequent loss of mouse focus.
Don't relinquish mouse focus on surfaces with active touch events. If there are active touch events when pointer focus is lost, the keyboard focus is used as a fallback for relinquishing mouse focus: if, in this case, the keyboard focus is then lost and there are no active touches, mouse focus is lost, and if all touches are raised and there is no keyboard or pointer focus, then the window loses mouse focus.
Needs to be cherry-picked for SDL2 as well.
Fixes #8687
=> wayland: Handle mouse focus when receiving touch events

src/events/SDL_mouse.c, src/video/windows/SDL_windowsmouse.c
Used this code to test `SDL_CreateCursor`:
```cpp
static const char *g_mouseArrowData[] = {
/* pixels */
"X                               ",
"XX                              ",
"X.X                             ",
"X..X                            ",
"X...X                           ",
"X....X                          ",
"X.....X                         ",
"X......X                        ",
"X.......X                       ",
"X........X                      ",
"X.....XXXXX                     ",
"X..X..X                         ",
"X.X X..X                        ",
"XX  X..X                        ",
"X    X..X                       ",
"     X..X                       ",
"      X..X                      ",
"      X..X                      ",
"       XX                       ",
" …
```
=> Add support for monochrome cursors with inverted pixels under Windows

Xcode/SDL/SDL.xcodeproj/project.pbxproj
This commit fixes a linker issue when building SDL 3.0 using Xcode
This change fixes a linker issue when building SDL 3.0 using Xcode. It adds the new SDL_hidapi_steamdeck.c file to the build target.
Fixes #8702
=> Add SDL_hidapi_steamdeck.c to Xcode target to fix linker error

src/video/windows/SDL_windowsevents.c
- SDL2 backport of https://github.com/libsdl-org/SDL/pull/5926
Since the new feature is non-breaking and small, I though it would be useful to have it in SDL2 as well. Merging this will help us with solving https://github.com/ppy/osu/issues/25590.
=> Backport "Differentiate between Windows Ink (pen) and regular touch input"

test/testautomation_platform.c
```
testautomation_platform.c:351:28: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
351 |     result = SDL_SetError("%s", testError);
|                            ^~
/home/slvn/release/Release_SDL/sdl2-compat/test/testautomation_platform.c:364:64: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
364 |                             "SDL_GetError(): expected message '%s', was message: '%s'",
```
sdl2-compat:
https://github.com/libsdl-org/sdl2-compat/pull/120
=> Fix compilation / same as sdl2-compat

src/joystick/SDL_joystick.c, src/joystick/SDL_joystick_c.h, src/joystick/android/SDL_sysjoystick.c, src/joystick/apple/SDL_mfijoystick.m, src/joystick/bsd/SDL_bsdjoystick.c, src/joystick/darwin/SDL_iokitjoystick.c, src/joystick/hidapi/SDL_hidapijoystick.c, src/joystick/hidapi/SDL_hidapijoystick_c.h, src/joystick/linux/SDL_sysjoystick.c, src/joystick/virtual/SDL_virtualjoystick.c, src/joystick/windows/SDL_dinputjoystick.c, src/joystick/windows/SDL_rawinputjoystick.c, src/joystick/windows/SDL_windows_gaming_input.c, src/joystick/windows/SDL_xinputjoystick.c
This allows the most information possible for the CRC string, which is used to differentiate controllers with the same VID/PID.
Fixes https://github.com/libsdl-org/SDL/issues/8724
=> Use the original manufacturer and product strings for the joystick CRC

include/SDL3/SDL_surface.h, src/render/SDL_render.c, src/video/SDL_surface.c, src/video/SDL_video.c
We'll use properties for new data associated with a surface, which lets us preserve ABI compatibility with SDL2 and any surfaces created by applications and passed in to SDL functions.
=> Make the SDL3 surface ABI compatible with SDL2

src/joystick/SDL_joystick.c
Fixes the regression introduced by 919cd56b20c59249bdde3bb005aeeb8f6550f3e3 (@slouken)
**This also needs to be backmerged to SDL2.**
=> Use crc16 return value when calculating GUID

src/video/SDL_video.c, src/video/cocoa/SDL_cocoawindow.m, src/video/wayland/SDL_waylandwindow.c, src/video/x11/SDL_x11events.c, src/video/x11/SDL_x11window.c, src/video/x11/SDL_x11window.h
Don't check the fullscreen flag when toggling resizable, bordered, always on top, and minimum/maximum size limits, as the flag doesn't reflect pending async changes that may be in progress.
These properties can be made to be safely toggled while the window is in fullscreen mode and applied when returning to windowed mode, which ensures that requested window state changes aren't lost if calling these functions while async fullscreen changes are in flight.
The Cocoa windowing code commit cleans up some edge-case behavior when toggling borders on fullscreen windows, and is committed separately so it can be easily reverted if necessary, as the current code works perfectly on Sonoma, but I don't know if older versions may still have issues the changed/removed code was covering up.
=> Cleanup remaining unsafe fullscreen flag checks in the video layer

src/joystick/SDL_gamepad.c
Make sure the string is terminated, fixed invalid read in SDL_PrivateParseGamepadConfigString()
```
----- Test Case 7.1: 'TestVirtualJoystick' started
==51751== Conditional jump or move depends on uninitialised value(s)
==51751==    at 0x484BC38: strlen (vg_replace_strmem.c:501)
==51751==    by 0x4BD5D57: __printf_buffer (vfprintf-process-arg.c:435)
==51751==    by 0x4BFA443: __vsnprintf_internal (vsnprintf.c:96)
==51751==    by 0x4BFA443: vsnprintf (vsnprintf.c:103)
==51751==    by 0x493DD92: SDL_vsnprintf_REAL (SDL_git/src/stdlib/SDL_string.c:1636)
==51751==    by 0x4882839: SDL_SetError_REAL (SDL_git/src/SDL_error.c:38)
==51751==    by 0x48D58DF: SDL_PrivateParseGamepadConfigString (SDL_git/src/joystick/SDL_gamepad.c:1291)
==51751==    by 0x48D15FE: SDL_PrivateLoadButtonMapping …
```
=> Make sure the string is terminated, fixed invalid read in SDL_PrivateParseGamepadConfigString()

src/thread/ps2/SDL_syssem.c
This is a refactor which uses the common function of waiting for a semaphore with timeout in ps2sdk
=> PS2 use WaitSemaEx for waiting for semaphore with timeout

src/core/linux/SDL_udev.c, src/core/linux/SDL_udev.h, src/joystick/linux/SDL_sysjoystick.c
The udev container issue is mostly to do with device notifications and netlink. The device classification stuff just pokes file in /sys and /run/udev. Doesn't hurt to try it first for classifying joysticks and then fall to the guess heuristics if it fails.                                                                     
Here is an example of the the [sdl-jtest](https://github.com/Grumbel/sdl-jstest) program compiled against the current SDL2 HEAD
```
tyson@tux ~> ./sdl2-orig/bin/sdl2-jstest -l
Found 1 joystick(s)
Joystick Name:     'PRODUCTS CH PRO PEDALS USB'
Joystick GUID:     0300b9e88e060000f200000000010000
Joystick Number:    0
Number of Axes:     3
Number of Buttons:  0
Number of Hats:     0
Number of Balls:    0
GameControllerConfig:
missing (see 'gamecontrollerdb.txt' or …
```
=> Try SDL_UDEV_deviceclass to detect joysticks even if in a container

src/core/linux/SDL_udev.c, src/core/linux/SDL_udev.h, src/joystick/linux/SDL_sysjoystick.c
The udev container issue is mostly to do with device notifications and netlink. The device classification stuff just pokes file in /sys and /run/udev. Doesn't hurt to try it first for classifying joysticks and then fall to the guess heuristics if it fails.
@slouken this is #8645 cherry picked for main. I was unable to test it beyond comparing the diffs and just verifying it builds okay as the [sdl-jtest](https://github.com/Grumbel/sdl-jstest) program does not build against head.
=> Try SDL_UDEV_deviceclass to detect joysticks even if in a container (pull request for main)

src/video/windows/SDL_windowsevents.c, test/testwm.c
Fixes a copy-paste typo from https://github.com/libsdl-org/SDL/commit/9302d7732dfbb3c6364da142efd06ea9846206c1.
Also includes a bonus fix for `testwm` that would trigger an assert on startup, and an array out-of-bounds access if the relevant code paths were reached.
Notices when looking into https://github.com/libsdl-org/SDL/issues/8725.
SDL really needs a mouse+finger+pen test. I'm currently modifying `testwm.c` to test this. I don't really feel comfortable adding a new test, as lots of project files for lots of different platforms need to be updated.
=> Fix windows touch normalisation on the Y axis

src/video/windows/SDL_windowsevents.c, test/testpen.c
The actual fix is in d6321592e82fa55ed48741bb732f8cbaa81d34f9. The rest is just code quality, WinAPI call optimisations and tests.
We're using the same `0x80` strategy in [osu!framework](https://github.com/ppy/osu-framework/blob/396c9f82a64db85240013f9e7d16d39ee5bbdd09/osu.Framework/Platform/Windows/WindowsMouseHandler.cs#L72-L94).
- Closes https://github.com/libsdl-org/SDL/issues/8725
=> Fix unwanted mouse events when using touchscreen with relative mouse mode

src/video/kmsdrm/SDL_kmsdrmsym.h
Fixes the static build with libdrm 2.4.116, which change the signature of this function.
Reference: https://gitlab.freedesktop.org/mesa/drm/-/commit/cc8c223c9e5307387fd5d3c0a77c3a0354610bb3
These symbols have been removed in SDL3, so this is a SDL2-specific fix.
=> [SDL2] Fix static build with libdrm 2.4.116

src/video/wayland/SDL_waylandsym.h
Fixes the static build with libdecor v0.2.0 which changed the signature of these functions. Please cherry-pick to SDL2.
Reference: https://gitlab.freedesktop.org/libdecor/libdecor/-/commit/c3b3965dcf0fe07e95b8a36bf17d65ebb965852b
=> Fix static build with libdecor 0.2.0

sdl2.m4
When cross-compiling, pkg.m4 will set the PKG_CONFIG variable to a suitable pkg-config executable, which might be a host-architecture-prefixed name like aarch64-linux-gnu-pkg-config. This ensures that we will use a suitable search path that is suitable for the host architecture (the machine we are compiling for) rather than the build architecture (the machine we are compiling on) to find dependency libraries like SDL. When using pkg-config as a substitute for sdl2-config, we will similarly need to use the host-architecture-prefixed pkg-config.
Setting the PKG_CONFIG environment variable is also the canonical way to request that a different pkg-config implementation be used, if that becomes necessary for some reason.
Bug-Debian: https://bugs.debian.org/1059749
---
Please also apply to …
=> sdl2.m4: Call $PKG_CONFIG rather than hard-coding pkg-config

src/joystick/hidapi/SDL_hidapi_steamdeck.c
This adds support for Xbox-style rumble using the Deck's new built-in Xbox-style rumble report.
However, testhaptics fails since it doesn't attempt to enumerate if the Deck has haptics, and I'm not sure what to do about that. It seems like a bug in SDL_SYS_HapticInit or similar. As such I've left it on draft for now.
=> Add basic rumble support to Steam Deck

src/video/cocoa/SDL_cocoawindow.h, src/video/cocoa/SDL_cocoawindow.m
For some reason, fullscreen space windows won't receive any mouse button events without the NSWindowStyleMaskTitled flag set, even though they successfully become key and receive key and mouse motion events. Make sure the flag is always set on fullscreen space windows.
Fixes #8778
=> cocoa: Set the titled flag on fullscreen space windows

src/audio/SDL_audio.c
I'll quickly describe the scenario we had. It may happen under totally different circumstances too.
I compiled SDL2 with AddressSanitizer to see where it happens.
Windows
SDL2
FNA/FNAAudio (https://github.com/FNA-XNA/FNA)
ClassicUO (https://github.com/ClassicUO/ClassicUO/)
If you do this while in-game:
this happens:
This is because SDL uses the WASAPI backend implementation on modern Windows. 
If the default audio device changes or gets reset, the WASAPI will try to recover, which is fine. 
But some things may change: device buffer size, work buffer size, and device->stream will hop from 0 to 1, or from 1 to 0
When SDL_OpenAudioDevice is called, the function reports a certain WaveFormat to the application, and the application will keep streaming in that format, so if the underlying device …
=> SDL_audio.c: Fix buffer overflow in SDL_RunAudio

include/SDL3/SDL_atomic.h
The ARM926EJ-S Technical Reference Manual states:
> You can only access CP15 registers with MRC and MCR instructions in a
> privileged mode. CDP, LDC, STC, MCRR, and MRRC instructions, and unprivileged
> MRC or MCR instructions to CP15 cause the Undefined instruction exception to
> be taken.
Furthermore, `MCR p15, 0, <Rd>, c7, c10, 5` (later called Data Memory Barrier) is not specified for the ARM926. Thus, SDL should not use these cache instructions on ARMv5.
This PR applies to the `main` branch as well as the `SDL2` branch.
None.
=> Fix memory barriers on ARMv5

include/SDL3/SDL_hints.h, src/SDL.c, src/core/linux/SDL_dbus.c
Adds a new hint, `SDL_HINT_SHUTDOWN_DBUS_ON_QUIT`, to allow app developers to let SDL know they won't use D-Bus directly, and that it can safely call dbus_shutdown() within SDL_Quit().
As requested, the default behavior is to keep D-Bus open on quit.
I added a description that clearly explains why SDL doesn't close D-Bus by default, and what to think about before enabling the option (such as making sure no other dependency uses D-Bus). I'm open to adapt the description, if necessary.
```c
#include "SDL3/SDL.h"
int main()
{
SDL_SetHint(SDL_HINT_SHUTDOWN_DBUS_ON_QUIT, "1");
SDL_Init(0);
// ...
SDL_Quit();
return 0;
}
```
I had to change the shutdown order in SDL.c, because hints were cleared before SDL_DBus_Quit() was called. I wanted to specify this because I'm not sure if it could have …
=> Add hint to make SDL handle dbus_shutdown()

include/SDL3/SDL_gamepad.h
It would be easy to assume that all APIs that reference SDL_JOYSTICK_AXIS_MAX work the same way, but they do not: triggers generally use the full signed 16-bit range in the lower-level joystick API, but are normalized to be non-negative by the higher-level gamepad API.
We also never said explicitly which direction is positive here. Experimentally, it's right (X), down (Y), and pressed (triggers).
Resolves: https://github.com/libsdl-org/SDL/issues/8793
=> gamepad: Clarify range and direction of axes

src/test/SDL_test_harness.c
When a test has been disabled because it's known not to work reliably or it's a test for unimplemented functionality, we probably don't want to encourage developers and testers to run it and report its failures as a bug.
Helps: #8798, #8800
---
SDL2 version of #8801.
=> [SDL2] test: When listing test-cases, say which ones are disabled

test/testautomation_render.c
Backported from SDL3 commit 85e3099b.
Resolves: https://github.com/libsdl-org/SDL/issues/8799
=> testautomation: only require accelerated renderer with non-dummy video driver

include/SDL_gamecontroller.h
SDL_GetGamepadAxis() is a SDL3-specific name: SDL2 calls gamepads "game controllers".
Fixes: d3c21666 "gamepad: Clarify range and direction of axes"
=> [SDL2] gamecontroller: Fix function name in cherry-picked documentation

docs/README-wayland.md, include/SDL3/SDL_video.h, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h, test/CMakeLists.txt, test/testwaylandcustom.c
This adds the ability to create and SDL_Window with a 'roleless' Wayland surface not attached to a toplevel window, so it can be used by the application for its own purposes, such with the wlr_layer_shell protocol, which has been requested before (#5779 #7262), or whatever custom purpose the application may have. A simple test/example is included, which demonstrates how to create an SDL_Window with a custom surface role, attach it to an XDG toplevel window managed by the application, and signal size changes back to SDL.
The internal changes were fairly simple, and generally cleaned up the logic while removing redundant checks in the process.
The final commit adds a property to force the creation of a `wl_egl_window`, even if the window is not flagged as OpenGL-enabled, to make it easier …
=> Add properties to enable/enhance the use of SDL Wayland windows outside of SDL

test/testautomation_math.c
* testautomation: don't do float equality tests
From: Anonymous Maarten
(cherry picked from commit 474c8d0073b0fb4b14b65b79c7e620db1332e4f3)
* test: Accept small numerical differences in more mathematical tests
We can't rely on irrational numbers like pi being represented exactly,
particularly when compiling for i386, where the i387 floating-point
interface carries out calculations in registers that have higher
precision than the actual double-precision variable. The 1980s were a
strange time.
Resolves: https://github.com/libsdl-org/SDL/issues/8311
(cherry picked from commit 6248472c0c738496a6f246aafa07a0e30afa6a01)
---
Changes vs. SDL3: replace `SDL_PI_D` with `M_PI` since that's what SDL2 uses.
I hope we now have SDL2 testautomation working on x86_64, but when I tried x86_64 + i386 …
=> [SDL2] test: Backport SDL3 commits to accept small numerical differences

src/test/SDL_test_imageBlit.c, src/test/SDL_test_imageBlitBlend.c, src/test/SDL_test_imageFace.c, src/test/SDL_test_imagePrimitives.c, src/test/SDL_test_imagePrimitivesBlend.c
* test: Fix encoding declaration for RGB24 test images
All of these test images are provided as an octal dump of
3-bytes-per-pixel data with red, green and blue bytes in that order,
referred to as RGB24 in SDL's taxonomy. However, the call to
SDL_CreateRGBSurfaceFrom() used masks that would have been appropriate
for RGBA32 data.
On little-endian platforms, the test images loaded as intended anyway,
because SDL does not actually check all four masks before deciding to
use RGB24 (it only looks at the red mask), and the red channel happens to
be in the 0x000000FF position for both RGB24 and RGBA32 on little-endian.
Unfortunately, on big-endian platforms, the required masks are not the
same and the call failed with "Unknown pixel format". As far as I can
tell, this means …
=> [SDL2] Make testautomation --filter Surface pass on big-endian

src/core/windows/SDL_xinput.h
A recent version of the MSVC v143 toolset broke compilation for the XInputOnGameInput.h header we use on Xbox platforms. Specifically, the header uses some math functions but does not explicitly `#include <math.h>` -- instead, it has historically pulled them in indirectly from another standard library header (`<atomic>`). However, due to recent changes in the toolset header files, `<atomic>` no longer implicitly pulls in those math function declarations. This results in a bunch of "missing identifier" errors and a build failure.
Since this is an official GDK header, I have reported this to Microsoft on the private Xbox forum for a proper fix, but this PR addresses the issue on our end by simply including math.h before we include the header.
This will also need to be backported to SDL2.
cc …
=> Xbox: Fix compile error with XInputOnGameInput.h

src/video/wayland/SDL_waylandopengles.c
Raise the minimum frame throttle limit to 1/3 the refresh rate (or 20hz) to prevent titles from timing out when occluded.
Fixes #8807
=> [SDL2] wayland: Raise the frame throttle limit

src/render/SDL_render.c
The previous code was working incorrectly on viewports not having the top left corner on the origin: even in those cases we only need to look at the width and height of the viewport, because the drawing coordinates are translated.
Fixes #8828
=> render: Fix line clipping with translated viewports

src/video/windows/SDL_windowsevents.c
This fixes restoring window size and position after moving it to a tiled location (which isn't maximized) and then back.
=> Let Windows track floating window state

src/render/software/SDL_triangle.c, test/testgeometry.c
like SDL_triangle.c:305:30: runtime error: left shift of negative value -672 (even if the value was correctly computed)
=> Prevent ASAN warning in SDL_triangle.c

src/video/windows/SDL_windowsevents.c, src/video/windows/SDL_windowswindow.c, src/video/windows/SDL_windowswindow.h
Recent changes broke a few of the automated tests on Windows. This fixes the video_getSetWindowSize, video_setWindowCenteredOnDisplay, and video_getSetWindowState tests.
Dealing with windows in a docked/tiled state is annoying, as this state is completely internal to windows with no reliable way to detect it (simply relying on size doesn't always work), and doing things like programmatically changing the size on a window in the docked state will result in the immediate size changing, but Windows considers it to still be docked and will snap it back to the original, pre-docked size as soon as it is moved and leaves the docked state. This is all internal Windows behavior, so there's nothing we can really do to fix this. The best we can do, and what these commits implement, is to just let …
=> Win32 test fixes

.github/workflows/ps2.yml
This PR basically do 2 things:
- Remove from workflow the previous `ps2_drivers` installation because it is already included in the docker
- Put back the usage of all the threads (@madebr let's check now if the issue you raised https://github.com/ps2dev/ps2dev/issues/67 is still happening. Could you also add here more information about how to reproduce it? I just see this [PR](https://github.com/libsdl-org/SDL/pull/7505) making reference)
Cheers.
=> Improve ps2 workflow

src/render/software/SDL_triangle.c
Fixed bug #8301 - Software renderer draws long lines incorrectly / SDL_RENDERLINEMETHOD_GEOMETRY
=> Fixed bug #8301 - Software renderer draws long lines incorrectly / SDL_RENDERLINEMETHOD_GEOMETRY

src/video/SDL_surface.c
Fix overflow  of issue https://github.com/libsdl-org/SDL/issues/7614
(simplier fix, compared to #7808)
SDL3 and SDL2 are affected
but I think, the code should be re-written using SDL_GetRectIntersection() like it was done in #7808
=> Fixed bug #7614: Segmentation Fault in SDL_BlitSurface

docs/README-migration.md, include/SDL3/SDL_hints.h, src/thread/windows/SDL_systhread.c
Update the way threads are named in Windows
* Regarding the usage of the function `SetThreadDescription`, added a fallback to also look for it in `KernelBase.dll`, as per the docs:
> Windows Server 2016, Windows 10 LTSB 2016 and Windows 10 version 1607: SetThreadDescription is only available by Run Time Dynamic Linking in KrnelBase.dll.
* For the structured exception approach, use `AddVectoredExceptionHandler` and `RemoveVectoredExceptionHandler` to properly guard the raised exception, so that the extra checks (the debugger being present and the hint added recently) are no longer needed, as the exception will be immediately caught by SDL (the compiler will still be able to react to it and set the name if it supports it).
Those 2 functions are the equivalent of using a ``__try{} __except …
=> Update thread naming on Windows

src/video/SDL_surface.c, src/video/SDL_yuv.c, test/testautomation_surface.c
* testautomation_surface: Really make pitch + alignment overflow
Adding 3 bytes of alignment to 0x7fff'ffff is not enough to make it
overflow a 4-byte unsigned size_t, so this test was not exercising
the intended failure mode. We cannot actually make this overflow
with a signed 32-bit width and an 8-bit format: the maximum width is
not enough to achieve that. However, if we switch to a 24-bit format,
we can make the calculation overflow.
In SDL 2, this test bug was hidden by the fact that allocating
0x7fff'ffff bytes on a 32-bit platform will usually fail, and SDL 2
reported both "malloc() failed" and "this amount of memory is too large
for a size_t" with the same error code.
* testautomation_surface: Really make width * bpp overflow
A surface of width (0x7fff'ffff) / 2 = 0x3fff'ffff is …
=> [SDL3] Fix tests, error reporting for surface sizes that would overflow

test/testautomation_surface.c
Backport of the relevant parts of #8873.
* testautomation_surface: Really make pitch + alignment overflow
Adding 3 bytes of alignment to 0x7fff'ffff is not enough to make it
overflow a 4-byte unsigned size_t, so this test was not exercising
the intended failure mode. We cannot actually make this overflow
with a signed 32-bit width and an 8-bit format: the maximum width is
not enough to achieve that. However, if we switch to a 24-bit format,
we can make the calculation overflow.
In SDL 2, this test bug was hidden by the fact that allocating
0x7fff'ffff bytes on a 32-bit platform will usually fail, and SDL 2
reported both "malloc() failed" and "this amount of memory is too large
for a size_t" with the same error code.
* testautomation_surface: Really make width * bpp overflow
A surface of …
=> [SDL2] Fix tests for surface sizes that would overflow

src/video/yuv2rgb/yuv_rgb_lsx.c
After testing #8864  , it was found thatit did not compile on the loongson platform. The reason is that ’yuv_rgb_lsx.c‘ is missing ’yuv_rgb_internal.h‘. @madebr
=> Fix compilation problems about yuv_rgb_lsx.c

src/stdlib/SDL_qsort.c
Prevent asan warning on qsort():
`'src/stdlib/SDL_qsort.c:27:5: runtime error: null pointer passed as argument 1, which is declared to never be null``
=> Prevent asan warning on qsort():

CMakeLists.txt, src/video/yuv2rgb/yuv_rgb_lsx.c
On the loongarch platform, the compilation issue of SDL2 was fixed. @sezero @slouken
=> Fix compilation on loongarch

test/Makefile.in
* test: Don't distinguish between different categories of tests
It's reasonable to assume that any of them might need a display and an
audio backend. We run them with SDL_VIDEODRIVER and SDL_AUDIODRIVER
set to dummy anyway.
* test: Run testautomation under Autotools too, not just CMake
The CMake build system runs this since #8313, so we already have to make
sure it doesn't regress.
---
Autotools equivalent of #8313.
In at least Debian/Ubuntu and the Steam Runtime, we're still using Autotools to build and test SDL2. If the SDL team would recommend switching to CMake (like Fedora and Arch did) then we can do that, but I was under the impression that Autotools is still the recommendation for 2.x, until it gets fully superseded by SDL3 + sdl2-compat.
=> [SDL2] Run testautomation under Autotools

src/power/linux/SDL_syspower.c
On my laptop, the battery is configured to stop charging at around 80% most of the time, to increase the overall useful lifetime of the battery. When in that state, upower reports UP_DEVICE_STATE_PENDING_CHARGE (numeric value 5), which SDL previously mapped to SDL_POWERSTATE_UNKNOWN. This made the platform_testGetPowerInfo automated test fail, because it assumes that SDL_POWERSTATE_UNKNOWN means no battery is connected, and does not expect to see a percentage.
Map UP_DEVICE_STATE_PENDING_CHARGE (5) to SDL_POWERSTATE_CHARGED, which seems close enough.
Also map UP_DEVICE_STATE_PENDING_DISCHARGE (6) to
SDL_POWERSTATE_ON_BATTERY, which matches how at least GNOME presents it.
(cherry picked from commit eebd5d18a2af0f3505791d7d40c2ec2bb5c08bb6)
---
SDL2 backport of #8273. This seems to be …
=> [SDL2] linux: Handle upower's UP_DEVICE_STATE_PENDING_CHARGE, PENDING_DISCHARGE

src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandevents_c.h, src/video/wayland/SDL_waylandvideo.c
Fixes a crash if no seat was available at initialization, but still allows for one to still be created later if an input device is added.
Removes some unnecessary abstractions in the process.
This is the SDL3 version, a simplified backport to SDL2 will happen separately.
Fixes #8898
=> wayland: Always create the backing input store, even if there is no seat

src/video/SDL_sysvideo.h, src/video/SDL_video.c, src/video/android/SDL_androidvideo.c, src/video/cocoa/SDL_cocoavideo.m, src/video/dummy/SDL_nullvideo.c, src/video/emscripten/SDL_emscriptenvideo.c, src/video/haiku/SDL_bvideo.cc, src/video/kmsdrm/SDL_kmsdrmvideo.c, src/video/n3ds/SDL_n3dsvideo.c, src/video/ngage/SDL_ngagevideo.cpp, src/video/offscreen/SDL_offscreenvideo.c, src/video/ps2/SDL_ps2video.c, src/video/psp/SDL_pspvideo.c, src/video/qnx/SDL_qnxvideo.c, src/video/raspberry/SDL_rpivideo.c, src/video/riscos/SDL_riscosvideo.c, src/video/uikit/SDL_uikitvideo.m, src/video/vita/SDL_vitavideo.c, src/video/vivante/SDL_vivantevideo.c, src/video/wayland/SDL_waylandvideo.c, src/video/windows/SDL_windowsvideo.c, src/video/winrt/SDL_winrtmessagebox.cpp, src/video/winrt/SDL_winrtvideo.cpp, src/video/x11/SDL_x11video.c
This a larger change than was discussed, so I'm putting it in a Pull Request for GitHub Actions to test, and humans to scrutinize.
But this cleans out a bunch of platform-specific `#ifdef` blocks from SDL_video.c that no longer need to be updated as supported platforms change, and also makes it so the extended `SDL_VIDEO_DRIVER=target1,target2,etc` format is respected.
We'll cherry-pick this back to SDL2 if it makes sense, or do something less invasive if not.
Fixes #8892.
=> SDL_ShowMessageBox: Remove `#ifdef`s and respect SDL_VIDEO_DRIVER hint.

include/SDL3/SDL_surface.h, src/video/SDL_blit.c, src/video/SDL_blit.h, src/video/SDL_blit_slow.c, src/video/SDL_blit_slow.h
This currently only supports PQ, but can be expanded in the future
=> Added HDR surface properties and tone mapping from HDR to SDR

cmake/sdlchecks.cmake, src/video/arm/pixman-arm-neon-asm.S, src/video/arm/pixman-arm-simd-asm.S, src/video/khronos/EGL/eglplatform.h, src/video/khronos/KHR/khrplatform.h, src/video/khronos/vulkan/vk_platform.h
* Revert Khronos headers to upstream version
These are third-party headers, so it's best if they're identical to the
upstream version rather than using SDL-specific macros or coding style.
This partially reverts commits b6ae281e and 31d133db.
Fixes: 31d133db "Define SDL_PLATFORM_* macros instead of underscored ones (#8875)"
* Go back to using compiler built-in macros in ARM assembly code
These files don't #include SDL headers, so SDL-specific macros will
never be defined here.
This partially reverts commit 31d133db.
Fixes: 31d133db "Define SDL_PLATFORM_* macros instead of underscored ones (#8875)"
* Don't try to use SDL platform macros in configure-time checks
At the point that we run this, nothing SDL-specific is set up yet.
`__APPLE__` is a compiler predefined macro that forms part of …
=> Don't use SDL platform macros in contexts where they seem inappropriate

src/video/x11/SDL_x11modes.c
This PR fixes outdated refresh rate calculations from XRandR's output.
The original `CalculateXRandRRefreshRate` function didn't consider double scan and interlace and thus led to incorrect display mode. see #8918 for more info.
should be able to close #8918
=> X11: Fix refresh rate calculation

include/SDL3/SDL_keyboard.h
The tutorial code posted [here](https://wiki.libsdl.org/SDL2/Tutorials-TextInput) implies that `SDL_StartTextInput` must be called before text input events are emitted, but those events are emitted by default. If that default behavior isn't a bug that's being fixed, I think we could save people some time by adding a note to the function headers.
=> Document that text input is on by default

src/core/windows/SDL_windows.c, src/core/windows/SDL_windows.h, src/hidapi/windows/hid.c, src/video/windows/SDL_windowsevents.c, src/video/windows/SDL_windowsmodes.c, src/video/winrt/SDL_winrtkeyboard.cpp
This only needed minor changes, afaik, so here you go.
It will _not_ be our policy to support WinXP if we have to make heroic efforts to maintain compatibility, but these changes are small, so this might be worth merging.
Fixes #8666.
=> SDL3 WinXP support

docs/README-wayland.md, include/SDL3/SDL_hints.h, include/SDL3/SDL_video.h, src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h, test/testautomation_video.c
Adds a hint and property to force non-DPI-aware Wayland windows to output at 1:1.
When this hint is set, Wayland windows that are not flagged as being DPI-aware will have their logical size altered to force 1:1 output when on a scaled desktop. In essence, it uses more scaling to try and make it look like the window _isn't_ scaled.
This is intended for legacy games/applications that will never be updated to be DPI-aware, and has various issues with certain display configurations, as this forces the window to behave in a way that Wayland desktops were not designed to accommodate:
- Rounding errors can result with odd window sizes and/or desktop scales.
- The window may be unusably small.
- The window may jump in size at times.
- The window may appear to be larger than the desktop size to …
=> Add Wayland screen space scaling

build-scripts/cmake-toolchain-mingw64-i686.cmake, build-scripts/cmake-toolchain-mingw64-x86_64.cmake
Add missing `windres` RC compiler to cmake mingw64 buildscripts.
Was causing fatal error during build process as seen in #8942
#8942
=> Add missing `windres` RC compiler to cmake mingw64 buildscripts

include/SDL3/SDL_pixels.h
There's a wrong SDL_ColorRange value in SDL_COLORSPACE_BT601_FULL and SDL_COLORSPACE_BT709_FULL.
Because of that SDL_COLORSPACE_BT601_FULL has the same value as COLORSPACE_BT601_LIMITED
and SDL_COLORSPACE_BT709_FULL has the same value as COLORSPACE_BT709_LIMITED.
=> Fixes in SDL_ColorSpace (SDL_pixels.h)

src/joystick/apple/SDL_mfijoystick.m, src/joystick/apple/SDL_mfijoystick_c.h
Add missing guards around use of physicalInputProfile.
Add explicit import of Foundation which seems to be needed on some systems to get the NSArray definition.
Add `__unsafe_unretained` to ObjC types in struct so the compiler doesn't complain about that not being allowed with ARC.
#8979
=> Fix SDL_mfijoystick build issues

src/audio/SDL_audiotypecvt.c
I accidentally found that my pre-Pentium III 32-bit builds (most of SSE2+ extensions got been disabled) do crash for unknown and weird reason, and I found accidentally, that it was at the `SDL_Convert_S16_to_F32_Scalar()` function: the num_samples was being assigned without being divided by the size of the Sint16.
=> SDL_audiotypecvt.c: Fixed memory corruption when resampling S16 to F32

src/video/windows/SDL_windowsopengl.c
Fixed the crash introduced at https://github.com/libsdl-org/SDL/commit/594a79c2f9db21a11a76c012b2b1655a21fc8982 .
The crash may happen when `wglGetPixelFormatAttribivARB` field gets defined by NULL. To resolve this, I moved two new lines into the condition above that checks, are these fields defined or not.
Fixes #8968
=> SDL_windowsopengl.c: WGL: Fixed null-pointer dereference crash

src/joystick/SDL_steam_virtual_gamepad.c
Allocation of `info.name` in the last iteration of the loop is never freed.
None
=> Fix memory leak in SDL_UpdateSteamVirtualGamepadInfo()

src/video/emscripten/SDL_emscriptenvideo.c
[`EmscriptenFullscreenStrategy`](https://github.com/emscripten-core/emscripten/blob/c47d0601fbf6296ba5f03191c2c9fe99df27d25f/system/include/emscripten/html5.h#L280C16-L287) has a `canvasResizedCallbackTargetThread` member which wasn't being zeroed or initialized by SDL. A garbage `canvasResizedCallbackTargetThread` value can lead to a crash later on inside Emscripten core library code, during the call to `emscripten_request_fullscreen_strategy()`.
To fix this (and possible future issues), use the same pattern as Emscripten's tests: https://github.com/emscripten-core/emscripten/blob/c47d0601fbf6296ba5f03191c2c9fe99df27d25f/test/test_html5_fullscreen.c#L132
```diff
EmscriptenFullscreenStrategy strategy;
+ memset(&strategy, 0, sizeof(strategy)); // or, in this case, SDL_zero(strategy);
``` …
=> Emscripten_SetWindowFullscreen: Fix crash due to uninitialized EmscriptenFullscreenStrategy member(s)

src/video/wayland/SDL_waylandevents.c
* Fix potential leaks if a second keymap notification occurs.
* Make sure we do not crash by calling xkbcommon with invalid state if we get a modifier before the first keymap.
* Crash on Wayland due to nullptr in keyboard modifier handling #9022
=> Wayland: Avoid SEGV if a modifier notification comes before the keymap

src/video/windows/SDL_windowsevents.c
Fixes regression introduced in
```
commit 2670eb44afec9311ee8fbec447703c427db1e1c8
Author: Sam Lantinga <slouken@libsdl.org>
Date:   Thu Jan 25 06:30:07 2024 -0800
Improved timing accuracy of SDL_WaitEventTimeout() on Windows
We don't need to use the hack of setting a timer and waiting for a timer message, MsgWaitForMultipleObjects() will allow us to wait for input directly with a timeout.
Before this change, sleeping for 20 ms would actually sleep for around 30 ms, with this change the sleep time is pretty accurate at 20-21 ms.
```
Bug manifested where SDL_WaitEvent() would return SDL_FALSE.
- Timeout < 0 was not handled properly
- Return value for success is WAIT_OBJECT_0 + nCount, not positive value
=> Fix broken use of MsgWaitForMultipleObjects.

include/SDL3/SDL_render.h, include/SDL3/SDL_video.h, src/render/SDL_render.c, src/render/opengl/SDL_render_gl.c, src/render/opengles2/SDL_render_gles2.c, src/video/SDL_video.c, src/video/wayland/SDL_waylandwindow.c
I renamed the following property define names to have a type suffix to match other property names.
SDL_PROP_TEXTURE_OPENGL_TEXTURE_TARGET (number)
SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_TARGET (number)
SDL_PROP_WINDOW_CREATE_WAYLAND_SCALE_TO_DISPLAY (boolean)
SDL_PROP_WINDOW_RENDERER (pointer)
SDL_PROP_WINDOW_TEXTUREDATA (pointer)
=> Rename property define names to have a type suffix

src/video/wayland/SDL_waylandvideo.c
They aren't used for anything, and cause problems if the video core tries to free them.
Manual backport of f9ba0e1
Fixes #9010
=> wayland: Don't store wl_output pointers in mode driver data

src/video/cocoa/SDL_cocoawindow.m
Zeroing the window width and height was necessary in SDL2 to short-circuit the resize event deduplication code when the window backing scale changed, but not the logical size. This is no longer necessary in SDL3, as it will explicitly check for scale changes on resize events and dispatch pixel size/scale changed events as appropriate, even if the window's logical size hasn't changed.
Fixes #9061
=> cocoa: Remove resize hack when changing the window backing scale

src/video/SDL_sysvideo.h, src/video/SDL_video.c, src/video/emscripten/SDL_emscriptenmouse.c, src/video/wayland/SDL_waylandmouse.c, src/video/x11/SDL_x11mouse.c
Related to #8939. SDL2 version of #9077.
* wayland: Use CSS/freedesktop cursor name "default" as a fallback
The "left_ptr" name is an X11 thing, and there's no guarantee that
Wayland cursor themes contain it. In particular, GNOME's Adwaita theme
as of version 46.beta only contains the CSS/freedesktop names.
To test, either move one of the known cursors out of the way, or edit
the switch statement above to use a wrong name for one of them.
* wayland: Prefer to use CSS names for cursors, falling back to X11
From: @icculus 
SDL3's Wayland code already uses the CSS names exclusively with no
fallback, but since SDL2 has historically used the older names, keeping
them as a fallback makes sense if the CSS names don't work out.
[smcv: Added commit message]
* emscripten, wayland, x11: Map SIZEALL …
=> [SDL2] Prefer to use CSS cursor names for Wayland

android-project/app/build.gradle, android-project/app/src/main/AndroidManifest.xml, android-project/app/src/main/java/org/libsdl/app/SDL.java
A simple change to drop stray trailing whitespace.
There is some leftover in src/hidapi/windows/test/data, but it looked fragile and I was afraid to touch it.
=> Drop stray trailing whitespace for android-project

src/render/opengles2/SDL_render_gles2.c
Commit 554f0625d349c106f2633f6db039e332c4c18cec introduced these changes in `GLES2_RunCommandQueue()`:
https://github.com/libsdl-org/SDL/commit/554f0625d349c106f2633f6db039e332c4c18cec#diff-9275fcae5c62a725a16efd2bd4385f9751628f56bb088846b2db90a7059f37cfL1247-R1247
```diff
@@ -1244,18 +1234,17 @@ static int GLES2_RunCommandQueue(SDL_Renderer *renderer, SDL_RenderCommand *cmd,
case SDL_RENDERCMD_CLEAR:
{
-            const Uint8 r = colorswap ? cmd->data.color.b : cmd->data.color.r;
-            const Uint8 g = cmd->data.color.g;
-            const Uint8 b = colorswap ? cmd->data.color.r : cmd->data.color.b;
-            const Uint8 a = cmd->data.color.a;
-            const Uint32 color = (((Uint32)a << 24) | (r << 16) | (g << 8) | b);
-            if (data->drawstate.clear_color_dirty || …
```
=> opengles2: Call glClearColor() with r,g,b,a, not r,g,g,a

src/video/wayland/SDL_waylandmouse.c
The function calls strcmp internally without checking for a null string parameter, and calling strcmp with a null parameter is undefined behavior.
Fixes #9086
=> wayland: Don't pass null string pointers to wl_cursor_theme_get_cursor

cmake/sdlchecks.cmake, include/build_config/SDL_build_config.h.cmake, src/video/wayland/SDL_waylanddyn.h, src/video/wayland/SDL_waylandsym.h, src/video/wayland/SDL_waylandwindow.c
It is becoming necessary to enable additional features as libdecor continues to evolve, and checking against a single base version will no longer be adequate. Libdecor doesn't provide versioning defines in its headers, so split the version string into parts to allow for discrete version detection and feature enablement at build time.
@madebr does the regex method used to do this look ok, or would you suggest something else?
=> cmake: Split and store the libdecor version as individual parts

src/audio/SDL_audio.c
Visual Studio analyzer is right here, `streams[j]` is NULL when `j = i`.
None
=> Fix null pointer dereference in SDL_BindAudioStreams()

src/test/SDL_test_common.c, test/testcamera.c
`SDLTest_CommonEventMainCallbacks` assumes the test framework has created the window(s) and renderer(s), and segfaults because `state->windows` == NULL.
https://github.com/libsdl-org/SDL/blob/26ffbe43c246b71004821d2fcc91d332f2eb2d76/test/testcamera.c#L202
https://github.com/libsdl-org/SDL/blob/26ffbe43c246b71004821d2fcc91d332f2eb2d76/src/test/SDL_test_common.c#L2148-L2155
=> testcamera: fix segfault at exit

src/camera/v4l2/SDL_camera_v4l2.c
Build of SDL_camera_v4l2.c fails against old kernel headers:
```
/tmp/SDL3/src/camera/v4l2/SDL_camera_v4l2.c: In function ‘V4L2_OpenDevice’:
/tmp/SDL3/src/camera/v4l2/SDL_camera_v4l2.c:482: error: ‘struct v4l2_capability’ has no member named ‘device_caps’
/tmp/SDL3/src/camera/v4l2/SDL_camera_v4l2.c:552: error: ‘struct v4l2_capability’ has no member named ‘device_caps’
/tmp/SDL3/src/camera/v4l2/SDL_camera_v4l2.c:573: error: ‘struct v4l2_capability’ has no member named ‘device_caps’
/tmp/SDL3/src/camera/v4l2/SDL_camera_v4l2.c: In function ‘MaybeAddDevice’:
/tmp/SDL3/src/camera/v4l2/SDL_camera_v4l2.c:698: error: ‘struct v4l2_capability’ has no member named ‘device_caps’
make[2]: *** [CMakeFiles/SDL3-shared.dir/src/camera/v4l2/SDL_camera_v4l2.c.o] Error 1
```
`device_caps` member in `struct …
=> SDL_camera_v4l2: allow building against older kernel headers

src/video/x11/SDL_x11window.c
The resize/move/raise calls when changing a window's min/max size are redundant, as the video core will call the X11_SetWindowSize() function after the change, and the resize function will perform whatever actions are necessary.
SDL3 was changed to have similar behavior some time ago.
Fixes #9117
=> x11: Don't resize, move, or raise windows when changing the min/max size

.github/workflows/cpactions.yml
Improve performance by using the latest version
[main](https://github.com/libsdl-org/SDL/actions/runs/8022297829)
- FreeBSD 13.2: 11m7s
- NetBSD 9.3: 10m9s
[PR](https://github.com/libsdl-org/SDL/actions/runs/8024470767)
- FreeBSD 13.2: 2m13s
- NetBSD 9.3: 2m2s
=> ci: bump cross-platform-actions/action version to v0.23.0

.github/workflows/android.yml, .github/workflows/emscripten.yml, .github/workflows/loongarch64.yml, .github/workflows/msvc.yml
Fix the following warnings in the related workflows:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: [...]. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
=> ci: update deprecated node.js 16 actions

src/render/vulkan/SDL_render_vulkan.c
When enabling the Vulkan validation layers, the 'validationLayerName' variable technically went out of scope before vkCreateInstance() was called. While most compilers won't clean up stack variables after random 'if' statements, some will, particularly when optimisation or memory sanitizers are enabled.
This can lead to vkCreateInstance() segfaulting when SDL_HINT_RENDER_VULKAN_DEBUG is enabled.
Instead, make the validationLayerName visible throughout the entire VULKAN_CreateDeviceResources() function.
While we're at it, extract the validation layer name out into a preprocessor #define, so that we are definitely using the same name in VULKAN_ValidationLayersFound().
CC: @danginsburg
=> Vulkan: Make sure validation layer name is in-scope

src/render/vulkan/SDL_render_vulkan.c
There are a couple of problems with the way we select a memory type in ``VULKAN_FindMemoryTypeIndex()``:
- We can return a memory type which doesn't have some properties we need (leading, e.g., to ``vkMapMemory()`` failing because a memory type without ``VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT`` was selected).
- We can fail to find any suitable memory types, because we are overzealous in throwing out types without ``VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT`` (bug #9130).
This PR addresses both of these issues (in separate commits, for clarity), by only returning memory types which are a superset of the required flags (patch 1), and by splitting the flags up into separate "required" and "desired" flags (patch 2).
There's still more we could do to improve this (by more explicitly ranking memory …
=> Vulkan: Improve memory type selection (Fix #9130)

src/render/vulkan/SDL_render_vulkan.c
The ``VULKAN_InvalidateCachedState()`` function seems to be meant to invalidate any _cached_ state, i.e. global state of the API which may have been modified outside the renderer.
However, at the moment, the Vulkan renderer also resets a number of internal variables which track buffers, offsets, etc, in use. As a result, the renderer can get into an inconsistant state and/or lose data.
For example, if ``VULKAN_InvalidateCachedState()`` is called in between two calls to ``VULKAN_UpdateVertexBuffer()``, the data from the first call will be overwritten by that from the second, as the number of the next vertex buffer to use will be reset to 0. This can result in rendering errors, as the same vertex data is used incorrectly for several calls.
I tested this against …
=> Vulkan: Don't invalidate internal state in InvalidateCachedState

src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
The removal of a wl_output may not be accompanied by leave events for the surfaces present on it. Ensure that no window continues to hold a reference to a removed output.
SDL3 needs this as well, but it will require manual porting as too much has changed for a clean cherry pick.
Fixes #9107
=> [SDL2]wayland: Remove all references to destroyed outputs from windows

include/SDL3/SDL_filesystem.h
Changes the description of SDL_GetUserFolder() in SDL_filesystem.h to account for a renamed parameter. I removed the reference to the parameter entirely.
Fixes #9115
=> Fix typo in SDL_filesystem.h

include/SDL3/SDL_pixels.h, src/video/SDL_pixels.c
It's not supported by any renderer or pixel conversion path
=> Remove SDL_PIXELFORMAT_P010

src/test/SDL_test_common.c
A few tests (e.g. testwm) were not exiting when pressing the close window because the event loop keeps processing events. Those later events cause the `done` variable to reset to false.
=> SDLTest_CommonEvent: only set done when it is finished

src/core/linux/SDL_udev.c, src/joystick/linux/SDL_sysjoystick.c
Set the correct class for accelerometer and do not filter them out in hotplug callback.
Since "Removed SDL_HINT_ACCELEROMETER_AS_JOYSTICK" (9ce7fe2), sensors do not show up when hot plugging a gamepad. The hint was setting joystick class to accelerometer by default.
=> Set udev class for accelerometer

include/SDL3/SDL_properties.h
Adds an include that was missing in `SDL_properties.h`. `SDL_stdinc.h` was included by other headers, so this isn't easily noticeable when building the project.
Noticed this when [ClangSharpPInvokeGenerator](https://github.com/dotnet/ClangSharp) gave me a bunch of errors:
```
Diagnostics for 'S:\code\SDL\include\SDL3/SDL_properties.h':
S:\code\SDL\include\SDL3/SDL_properties.h:42:9: error: unknown type name 'Uint32'
S:\code\SDL\include\SDL3/SDL_properties.h:220:93: error: unknown type name 'Sint64'
S:\code\SDL\include\SDL3/SDL_properties.h:254:94: error: unknown type name 'SDL_bool'
S:\code\SDL\include\SDL3/SDL_properties.h:269:17: error: unknown type name 'SDL_bool'
S:\code\SDL\include\SDL3/SDL_properties.h:354:17: error: unknown type name 'Sint64' …
```
=> Add missing include

include/SDL3/SDL_events.h, include/SDL3/SDL_pen.h
Uses specific typedef'd types instead of generic integral types where applicable.
PR of salvageable parts of https://github.com/libsdl-org/SDL/pull/9191. As enums don't seem to be adequate for strong typing in C.
=> Use specific types in public headers

include/SDL3/SDL_touch.h
Missed when picking 7ff34249c753122a2ba67e78aa6e9f9b56aa4a65 from https://github.com/libsdl-org/SDL/pull/9191.
=> Use specific types in SDL_touch.h

include/SDL3/SDL_keycode.h, src/test/SDL_test_common.c, src/video/emscripten/SDL_emscriptenevents.c, src/video/wayland/SDL_waylandevents.c, test/testautomation_keyboard.c, test/testime.c, test/testintersections.c, test/testmouse.c
Previously, the `SDL_Keycode` was a `Sint32` typedef, while the actual enum was named `SDL_KeyCode` (notice the capital C).
This PR:
- removes the typedef and changes the enum name
- adds `default` branches to switch statements involving `SDL_Keycode`s to silence compiler errors about not handling all enum values
- changes format specifiers involving `SDL_Keycode`s to `%i` (to match surrounding code style and prevent errors)
- I recommend to use `%d` in new code, as that is a more known specifier, and [there are no differences](https://en.cppreference.com/w/c/io/fprintf)
Changes in this PR have been picked from https://github.com/libsdl-org/SDL/pull/9191.
- https://github.com/libsdl-org/SDL/issues/9186
=> Change `SDL_Keycode` type to an enum

docs/README-migration.md, include/SDL3/SDL_render.h, include/SDL3/SDL_test_common.h, include/SDL3/SDL_video.h, src/render/SDL_render.c, src/render/opengl/SDL_render_gl.c, src/render/opengles2/SDL_render_gles2.c, src/test/SDL_test_common.c, src/video/SDL_sysvideo.h, src/video/SDL_video.c, src/video/windows/SDL_windowsevents.c, src/video/winrt/SDL_winrtvideo.cpp, src/video/winrt/SDL_winrtvideo_cpp.h, src/video/x11/SDL_x11events.c, src/video/x11/SDL_x11window.c, test/testautomation_video.c, test/testffmpeg.c, test/testpopup.c, test/testshape.c, test/testvulkan.c
The `SDL_WindowFlags` enum was removed in https://github.com/libsdl-org/SDL/commit/ebd7f9adbdc0975f6c7584738609028abb3cce6e. This PR brings back `SDL_WindowFlags`, but as a typedef and uses the new type where applicable.
Unsure if changing from an enum to a typedef is a breaking change which should be included in the docs.
=> Bring back `SDL_WindowFlags` as a typedef and use it public headers

include/SDL3/SDL_events.h, src/events/SDL_mouse.c, src/test/SDL_test_common.c, test/testcamera.c, test/testhittesting.c, test/testhotplug.c, test/testoffscreen.c, test/testoverlay.c, test/testrelative.c, test/teststreaming.c
- updates public API structs to use `SDL_EventType` and `SDL_MouseWheelDirection` instead of generic `Uint32`
- only those are used as other event enums are used in 16 or 8 bit fields, but enums are always 32-bit `int`s
- the main `SDL_Event` union is still using `Uint32` since using the `SDL_EventType` enum would not be correct because of user defined events
- changes format specifiers involving `SDL_MouseWheelDirection` to `%d`
- also includes `default: break;` in switch statements that invlolve `SDL_Event::type`
Changes in this PR have been picked from https://github.com/libsdl-org/SDL/pull/9191.
- https://github.com/libsdl-org/SDL/issues/9186
=> Use enum types in `SDL_Event`s

Xcode/SDL/pkg-support/resources/CMake/sdl3-config.cmake
The Xcode framework CMake config file uses `get_filename_component` in PATH mode three times in a row to get the parent framework path, however the last two invocations use `_IMPORT_PREFIX` as the filename which on my system is empty, causing the `set_and_check` macro to immediately error with: 
```
CMake Error at /Library/Frameworks/SDL3.framework/Resources/CMake/sdl3-config.cmake:17 (message):
File or directory /Headers referenced by variable _sdl3_include_dirs does
not exist !
Call Stack (most recent call first):
/Library/Frameworks/SDL3.framework/Resources/CMake/sdl3-config.cmake:40 (set_and_check)
CMakeLists.txt:4 (find_package)
```
Even if `_IMPORT_PREFIX` held the correct value I'm not sure how this script would've worked properly and this seems like a typo, this PR replaces it …
=> Fix empty prefix in Xcode sdl3-config.cmake when SDL3.framework is found with find_package

src/joystick/SDL_joystick.c
Since commit 0dfdf1f3 "Fixed crash if joystick functions are passed a NULL joystick", we've already done this check by the time we get to this point.
=> joystick: Remove redundant CHECK_JOYSTICK_MAGIC in SDL_GetJoystickName

src/joystick/SDL_joystick.c
In particular this affects the doomsday game engine if no joystick or gamepad is attached.
(cherry picked from commit 0dfdf1f3f2a1f62e579527ef3abe63543af7e6da)  
[smcv: Also included minor adjustment from #9233]
---
Backport from SDL3, with #9233 also included. This fixes a crash in the doomsday game engine: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1062969
=> [SDL2] Fixed crash if joystick functions are passed a NULL joystick

src/video/x11/SDL_x11clipboard.c
Make it check for the most commonly used text type first.
https://github.com/libsdl-org/SDL/issues/8338 talks more about the issue. This pr does not fix it, but it makes the bug occur less often and differently.
=> x11: workaround issues with primary selection and clipboard temporal ignorance

android-project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
Hello, I've been updating a project from SDL 2.0.5 to 2.28.5 tonight and I had a spot of bother with `HIDDeviceManager.java` throwing an error. Conveniently, it isn't doing it anymore, try as I might. Anyway, here's a pull request with the fix I used.
Further reading: [https://stackoverflow.com/q/77235063](https://stackoverflow.com/questions/77235063/one-of-receiver-exported-or-receiver-not-exported-should-be-specified-when-a-rec)
=> Add flag to registerReceiver on Android

src/render/SDL_render.c
Properties created in `SDL_CreateTextureFromSurface` should be destroyed after using them in `SDL_CreateTextureWithProperties` call.
#9051
=> Destroy properties after using them to avoid memory leakage

.github/workflows/android.yml, src/render/SDL_render.c, test/testautomation_surface.c
This builds a lean SDL by building with `-DCMAKE_C_FLAGS="-DSDL_LEAN_AND_MEAN=1"`.
Do we want a `SDL_LEAN_AND_MEAN` CMake option that does this instead?
Fixes #9248
Fixes #9249
=> Fix SDL_LEAN_AND_MEAN build + add to Android ci

CMakeLists.txt, include/build_config/SDL_build_config.h.cmake, src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandevents_c.h, src/video/wayland/SDL_waylandmouse.c, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandvideo.h, wayland-protocols/cursor-shape-v1.xml
To bits of Wayland cursor work:
- Use memfd_create() to allocate the temporary SHM backing file in memory, and set the size with posix_fallocate(), which will return an error on insufficient space vs ftruncate(), which will silently succeed and allow a SIGBUS error to occur if the unbacked memory is accessed. Additionally, make the legacy path more robust by unlinking the temp file after creation, so it won't persist after close, and unmapping the shared memory buffer.
- Add support for the cursor shape protocol so that KDE will display the correct cursors, even if the settings portal is absent or SDL is built without dbus support.
Fixes #9256 
Fixes #9250 (when the developers release a new build with an updated statically linked library)
Cherry picks to SDL2 will be required.
=> Wayland cursor work

src/render/SDL_render.c
There was some software renderer specific code that can be excluded with `SDL_LEAN_AND_MEAN`. This contributes towards #9206
Visual Studio DLL sizes before this change:
Win32 1,167,872 bytes
x64 1,415,680 bytes
After:
Win32 1,165,824 bytes (saving 2,048 bytes) 
x64 1,413,120 bytes (saving 2,560 bytes)
=> Move some code blocks inside `SDL_VIDEO_RENDER_SW`, where it belongs

include/SDL3/SDL_init.h
When initializing SDL with the flag SDL_INIT_AUDIO or SDL_INIT_SENSOR, the event subsystem also gets initialized(SDL_INIT_EVENTS). This isn't mentioned in the comments.
This commit adds the two comments.
Here SDL_INIT_AUDIO initializes SDL_INIT_EVENTS:
https://github.com/libsdl-org/SDL/blob/495e432fb9776fdc13a8d96179136064ccddf6e5/src/SDL.c#L261-L268
Here SDL_INIT_SENSOR initializes SDL_INIT_EVENTS:
https://github.com/libsdl-org/SDL/blob/495e432fb9776fdc13a8d96179136064ccddf6e5/src/sensor/SDL_sensor.c#L124-L135
=> Adding comments to init-flags SDL_INIT_AUDIO and SDL_INIT_SENSOR that they imply SDL_INIT_EVENTS

include/SDL3/SDL_video.h, src/dialog/unix/SDL_portaldialog.c, src/video/wayland/SDL_waylandvideo.c, src/video/wayland/SDL_waylandvideo.h, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h, wayland-protocols/xdg-foreign-unstable-v2.xml
- Adds the xdg-foreign protocol to Wayland to create exportable window handles for toplevel windows.
- Uses the introspection method to detect if the file chooser portal is available.
- Passes the Wayland or X11 window handle to the file dialog during creation, which allows the window manager to correctly position the file dialog relative to the parent window.
=> Detect the file chooser portal and pass the Wayland/X11 window handle when opening a file dialog

src/video/wayland/SDL_waylandwindow.c
Not doing so can result in protocol errors if the viewport source region is updated and a buffer with the old, smaller dimensions is committed.
Fixes #9283
=> wayland: Always use the entire buffer for the viewport source

src/video/wayland/SDL_waylandwindow.c
Not doing so can result in protocol errors if the viewport source region is updated and a buffer with the old, smaller dimensions is committed.
SDL2 version of the fix. Will be cherry-picked to 2.30.x (maybe further back?)
Fixes #9283
=> [SDL2]wayland: Always use the entire buffer for the viewport source

test/testautomation_math.c
Fixes #9284
Using `fpclassify` can cause a linker error.
Using `isinf` instead fixes this.
=> testautomation_math.c: use isinf(V) instead of fpclassify(V) == FP_INFINITE

src/filesystem/SDL_filesystem.c, src/filesystem/SDL_sysfilesystem.h, src/filesystem/dummy/SDL_sysfsops.c, src/filesystem/posix/SDL_sysfsops.c, src/filesystem/windows/SDL_sysfsops.c
This removes the "FSops" naming scheme, which was meant to mirror the "RWops" naming scheme, which was also recently removed from SDL3.
The build system defines (`SDL_FSOPS_POSIX`, etc) and the source code filenames retain this, because there's already things using the word "filesystem" that might overlap (for example, lots of things have a unique "SDL_sysfilesystem.c", to query base dirs, etc, but almost everything uses the POSIX "SDL_sysfsops.c" source code.
Fixes #9288.
=> filesystem: Rename some internal symbols to remove "FSops" terminology.

src/joystick/psp/SDL_sysjoystick.c
using the blocking sceCtrlReadBufferPositive() effectively turns SDL_PollEvent() into WaitForVblank(), because the functions does exactly that if no input is buffered. due to this, calling SDL_PollEvent() once per frame averaged in 7 ms delay, wasting nearly half of the available 16ms budget to get a frame calculated and drawn to achieve 60 fps.
=> PSP: don't block on joystick event query

src/filesystem/unix/SDL_sysfilesystem.c
gets rid of following warnings:
```
SDL_repo/src/filesystem/unix/SDL_sysfilesystem.c: In function ‘xdg_user_dir_lookup_with_fallback’:
SDL_repo/src/filesystem/unix/SDL_sysfilesystem.c:393:10: warning: implicit declaration of function ‘fopen’ [-Wimplicit-function-declaration]
393 |   file = fopen (config_file, "r");
|          ^~~~~
SDL_repo/src/filesystem/unix/SDL_sysfilesystem.c:37:1: note: ‘fopen’ is defined in header ‘<stdio.h>’; did you forget to ‘#include <stdio.h>’?
36 | #include <unistd.h>
+++ |+#include <stdio.h>
37 | 
SDL_repo/src/filesystem/unix/SDL_sysfilesystem.c:393:8: warning: assignment to ‘FILE *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
393 |   file = fopen (config_file, "r");
|        ^ …
```
=> src/filesystem/unix/SDL_sysfilesystem.c add <stdio.h> inclusion

include/SDL3/SDL_camera.h, include/SDL3/SDL_egl.h, include/SDL3/SDL_pen.h
Changes `"SDL_*.h"` and `"SDL3/SDL_*.h"` to `<SDL3/SDL_*.h>`.
All offending include directives were found by grepping for `#include "`. Grepping after this change yields no matches in the public headers.
Noticed when testing out C# binding generation.
N/A
=> Standardise header includes in public headers

src/locale/n3ds/SDL_syslocale.c
This PR fixes a typo with the traditional Chinese locale, which used `zn` instead of `zh`, and an early return that would skip calling a cleanup function when hit.
If merged, this should also be cherry-picked for the SDL2 branch(es).
N/A
=> N3DS: Fix locale name and early return.

src/video/wayland/SDL_waylandopengles.c
Fixes a crash when all displays are disconnected.
Fixes #9323
=> wayland: Check the returned display pointer before dereferencing

src/thread/pthread/SDL_sysmutex.c
Fix a tiny compile error:
```
src/thread/pthread/SDL_sysmutex.c:144:13: error: void function 'SDL_UnlockMutex' should not return a value                     
return SDL_SetError("mutex not owned by this thread");
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> SDL_sysmutex.c: fix void return compile error

test/testffmpeg_vulkan.c, test/testffmpeg_vulkan.h
Fixes this compile warning:
```
[1/1] Building C object test/CMakeFiles/testffmpeg.dir/testffmpeg_vulkan.c.o
/src/SDL/test/testffmpeg_vulkan.c: In function ‘BeginVulkanFrameRendering’:
/src/SDL/test/testffmpeg_vulkan.c:787:20: warning: passing argument 1 of ‘vk->lock_frame’ from incompatible pointer type [-Wincompatible-pointer-types]
787 |     vk->lock_frame(frames, pVkFrame);
|                    ^~~~~~
|                    |
|                    AVHWFramesContext *
/src/SDL/test/testffmpeg_vulkan.c:787:20: note: expected ‘struct AVHWFramesContext *’ but argument is of type ‘AVHWFramesContext *’
/src/SDL/test/testffmpeg_vulkan.c: In function ‘FinishVulkanFrameRendering’:
/src/SDL/test/testffmpeg_vulkan.c:885:22: warning: passing argument 1 of ‘vk->unlock_frame’ from incompatible pointer …
```
=> testffmpeg_vulkan: fix -Wincompatible-pointer-types warning

src/timer/psp/SDL_systimer.c
currently the granularity of the PSP tickcounter is only millisecond based,
however almost all of te PSP APIs work on microsecond granularity.
this change allows more precise timing measurements.
=> PSP: improve performance counter res to us granularity

android-project/app/src/main/java/org/libsdl/app/SDLControllerManager.java
=> Fix bug #9331 - SDL3 Android crash getVibrator() == null

VisualC-GDK/SDL/SDL.vcxproj, VisualC-GDK/SDL/SDL.vcxproj.filters, VisualC-WinRT/SDL-UWP.vcxproj, VisualC-WinRT/SDL-UWP.vcxproj.filters, VisualC/SDL/SDL.vcxproj, VisualC/SDL/SDL.vcxproj.filters, include/SDL3/SDL_hints.h, src/SDL.c, src/audio/SDL_audiotypecvt.c, src/cpuinfo/SDL_cpuinfo.c, src/cpuinfo/SDL_cpuinfo_c.h, src/video/SDL_blit.c, test/CMakeLists.txt
- Introduces a `SDL_HINT_CPU_FEATURE_MASK` hint with which you can limit supported cpu features.
- Add another run of testautomation and testplatform to the test matrix, but without simd support.
- Always build scalar audio converters, since it is now possible to e.g. not have sse2 on x86_64.
- Reset cpuinfo flags on `SDL_Quit`
Things to consider when reviewing:
- is the hint correctly named?
- for all CPU features, you currently need to run with `SDL_CPU_FEATURES=sse,sse2,sse3,sse41,sse42`. Should we assume when you pass `sse42`, you also want sse1 to sse4.1?
- please review the hint documentation
- ~The hint is only parsed once. Should it be used through `SDL_AddHintCallback` instead? This would be useful for GUI options, or for doing performance testing with one non-forking …
=> Limit CPU features through a hint

src/timer/psp/SDL_systimer.c
introduced in 82b449611afc4129c562512a5463da0cd9937406
=> PSP: fix regression, GetTicks64 should return millisecs

src/events/SDL_pen.c, test/testautomation_pen.c
- Fixes a leak in pen name allocation that would trigger for both X11 and Wayland for some non-pen input devices when new devices are added/removed.
- `SDL_PenQuit()` now deallocates and resets the table of known pens
- `testautomation_pen.c` now uses `PenInit` and `PenQuit` as setup and teardown, respectively
`testautomation_pen.c` was already triggering the leak, and it is visible with `--trackmem`, so I did not add new tests.
Fixes #9279
=> Fix #9279: Memory leak in pen name handling

test/testautomation_pen.c
`testautomation_pen.c` had stray tabs that had somehow slipped through my `clang-format` checks.  My apologies for that!
Noticed this while working on #9279 but submitting it separately to simplify code review, since there's no overlap.  Let me know if you prefer these changes folded into more meaningful PRs.
=> Removed all tabs in testautomation_pen.c

include/SDL_video.h, src/render/psp/SDL_render_psp.c, src/render/psp/SDL_render_psp.h, src/video/psp/SDL_pspvideo.c, src/video/psp/SDL_pspvideo.h
instead of dealing with renderers and textures, this allows you to create a window, set the pixel format using SDL_SetWindowDisplayMode() - preferably BGR565 for optimal speed - and then request SDL_GetWindowSurface() for each redraw, which provides you a surface with direct framebuffer access - that's why you need to call it on every repaint, rather than storing the surface variable.
note that you need to overwrite all pixels of the PSP visible area (480x272) to not encounter old data.
after you're done writing your pixels, call SDL_UpdateWindowSurface() and your changes will be sent to the graphics chip.
the result is a framerate of 60+ fps with BGR565 mode, unlike the other methods involving renderer and textures and a lot of copying.
#9260
=> PSP: implement SDL_GetWindowSurface() API for direct VRAM access

src/joystick/psp/SDL_sysjoystick.c
At the moment no joystick add event is created on the PSP when the controls are initialized. This can cause issues in some games.
This change makes sure the event is created when controls are initialized. The controls on the PSP are not hotpluggable at all, so this solution should be good enough. I've done some testing with it and it solves the problem.
=> PSP: send initial SDL_JOYDEVICEADDED event

src/core/linux/SDL_udev.c
I believe there was a O(n^2) device walking issues on startup
- MaybeAddDevice gets called for every device at startup
- MaybeAddDevice calls IsJoystick
- IsJoystick calls SDL_UDEV_GetProductInfo
- SDL_UDEV_GetProductInfo calls udev_enumerate_scan_devices
- udev_enumerate_scan_devices walks all the devices
Prior to commit 3b1e0e1 this was mostly masked as IsJoystick only called SDL_UDEV_GetProductInfo when a JSIOCGNAME ioctl was successful. This fixes the O(n^2) behaviour by directly getting the device via udev_device_new_from_devnum (based on type, major, and minor number) instead of enumerating everything via udev_enumerate_scan_devices and matching on name.
Pull request for patch ported to master as requested in #9092. Note that I haven't test beyond the fact that it compiles cleanly.
=> udev: Fix O(n^2) device walking issue (closes #9092)

test/testevdev.c
We were including some system headers with `_GNU_SOURCE`, and some without.
Moving  `#include <SDL_internal.h>` to the top fixes that.
The move inflicts some collateral damage (`SDL_internal.h` includes `SDL_main.h` and does `define SDL_MAIN_NOIMPL`), which is also fixed here.
Fixes #9357
=> testevdev: include SDL_internal.h first, and fixup SDL_main.h

src/core/linux/SDL_system_theme.c
Fix an include path.
```
src/core/linux/SDL_system_theme.c:25:10: error: '../SDL_sysvideo.h' file not found             
#include "../SDL_sysvideo.h" 
```
Fwiw, I only noticed this when compiling with a non-cmake build system.
Files, for context:
```sh
$ fd SDL_sysvideo ; fd SDL_system_theme
src/video/SDL_sysvideo.h
src/core/linux/SDL_system_theme.c
src/core/linux/SDL_system_theme.h
```
=> linux/SDL_system_theme.c: fix an include path

VisualC-GDK/SDL/SDL.vcxproj, VisualC-GDK/SDL/SDL.vcxproj.filters, VisualC/SDL/SDL.vcxproj, VisualC/SDL/SDL.vcxproj.filters, include/SDL3/SDL_hints.h, src/events/SDL_events.c, src/events/SDL_keyboard.c, src/video/windows/SDL_windowsevents.c, src/video/windows/SDL_windowsmouse.c, src/video/windows/SDL_windowsrawinput.c, src/video/windows/SDL_windowsrawinput.h, src/video/windows/SDL_windowsvideo.c, src/video/windows/SDL_windowsvideo.h, src/video/x11/SDL_x11events.c, src/video/x11/SDL_x11video.h, src/video/x11/SDL_x11xinput2.c, src/video/x11/SDL_x11xinput2.h, test/testcustomcursor.c, test/testmanymouse.c
Enable raw keyboard events on Windows by default
Added support for events from distinct keyboards
=> More keyboard improvements

VisualC-GDK/SDL/SDL.vcxproj, include/build_config/SDL_build_config_xbox.h, src/video/windows/SDL_windowsevents.c, src/video/windows/SDL_windowsrawinput.c
Fixes some build errors in `Gaming.Desktop.x64` and `Gaming.Xbox.*.x64` configurations.
`VisualC-GDK/SDL/SDL.vcxproj` was missing sources about the newly added dialog subsystem. Now uses `dummydialog` on consoles and `windowsdialog` on desktop.
=> VisualC-GDK: Add missing dialog sources, fix Xbox builds

src/video/SDL_video.c, test/testautomation_video.c
Previously, renderers would be implicitly destroyed when their associated window was destroyed, a behavior that was lost when the old window userdata system was removed in favor of the property system. This behavior change isn't noted in any commits, so I'm guessing it was an oversight. This checks for and destroys an associated renderer when a window is destroyed, restoring the previous behavior.
This is the root cause of #9278 and otherwise caused renderer objects to be leaked when SDL_Quit() was called without them being explicitly cleaned up first.
=> Implicitly destroy renderers when the associated window is destroyed

src/video/windows/SDL_windowsevents.c, src/video/windows/SDL_windowsrawinput.c, src/video/windows/SDL_windowswindow.h
RAWINPUT structures are variable size
Multiplying size by 8 is important when reallocating the rawinput buffer
=> windows: fixed rawinput crash

include/SDL3/SDL_stdinc.h
Reference issue: https://github.com/libsdl-org/SDL/issues/9392 .
Android builds do survive the assertion, so I guess we can do this?
Maybe even in SDL2 assuming this one goes in SDL3 ??
=> SDL_stdinc.h: Android passes sizeof(ENUM) == sizeof(int) assertion

src/dynapi/gendynapi.py
Currently, running `gendynapi.py` with a recent python version produces multiple warnings about using invalid escape sequences in some regular expressions.
The solution to this problem is outlined in https://docs.python.org/3/library/re.html and is applied as such in this PR. I've checked that all escape sequences are invalid, and therefore won't be affected by using raw strings.
> The solution is to use Python’s raw string notation for regular expression patterns; backslashes are not handled in any special way in a string literal prefixed with `'r'`. So `r"\n"` is a two-character string containing `'\'` and `'n'`, while `"\n"` is a one-character string containing a newline. Usually patterns will be expressed in Python code using this raw string notation.
The warnings in question:
```py
❯ …
```
=> Fix 'SyntaxWarning: invalid escape sequence' when running `gendynapi.py`

src/audio/SDL_audio.c, src/audio/coreaudio/SDL_coreaudio.m
AudioDeviceID is not unique (hardware that can do both capture and output will expose both interfaces off the same AudioDeviceID!).
This is in a Pull Request, waiting on the builders to verify, and @slouken to test.
=> coreaudio: Make sure device handles are unique.

src/dialog/cocoa/SDL_cocoadialog.m, src/dialog/dummy/SDL_dummydialog.c, src/dialog/windows/SDL_windowsdialog.c
As stated in #9321, neither tvOS nor iOS support direct file dialogs. This PR disables their use on those platforms.
I also took the opportunity to remove the various `/* TODO: macro? */` that I left in the code, since the build system ended up not needing macros.
Fixes #9321
=> Disable SDL dialogs for tvOS and iOS

src/video/windows/SDL_windowsmodes.c
WIN_GetMonitorPathInfo() returns a bool, not an int.
None
=> Fix return value of WIN_GetMonitorPathInfo

src/video/windows/SDL_windowswindow.c
Store `data` to `windows->driverdata` after call to `SetProp()` in case it fails.
None
=> Do not store pointer before potentialy freeing it

src/dialog/windows/SDL_windowsdialog.c
Add a flag for file dialogs on Windows to not change the current working directory of the application that invokes it.
Windows changes the working directory of the entire application if the file dialog went to a different folder. This does not make sense to me, but I'm open to opinions and willing to take this PR down if this is the intended behavior.
Also, maybe this can use properties, so I don't need to make another parameter alongside `allow_many`?
=> Don't change cwd with file dialogs

src/render/vulkan/SDL_render_vulkan.c
When the vertex buffer size is exceeed, make sure to wait for outstanding work before resizing it.  This fixes validation errors/crash found with using Imgui SDL3 renderer on Vulkan.  Closes #9385.
=> Vulkan Renderer - fix crash with imgui SDL3 renderer

.github/workflows/psp.yml, CMakeLists.txt
CMake automatically sets the `SYSTEM` property on imported targets.
This pr disables that such that a project using SDL from a non-system SDL prefix will not accidentally use headers from a system SDL prefix.
This might be an issue for projects doing `#include "SDL.h"` instead of `#include <SDL.h>`.
This pr also tests this by "polluting" the psp prefix with bad SDL headers that should not be used in any situation.
Finally, this pr also removes a psp fix that has been fixed upstream.
=> cmake: disable SYSTEM property on exported SDL targets

src/video/windows/SDL_windowsevents.c
Fixes issue [Backspace on Colemak keyboard layout doesn't work on Windows #7853](https://github.com/libsdl-org/SDL/issues/7853)
=> Fix Caps Lock and Backspace mapping for Colemak

include/SDL3/SDL_filesystem.h, include/SDL3/SDL_storage.h, src/dynapi/SDL_dynapi.sym, src/dynapi/SDL_dynapi_overrides.h, src/dynapi/SDL_dynapi_procs.h, src/filesystem/SDL_filesystem.c, src/filesystem/SDL_sysfilesystem.h, src/stdlib/SDL_string.c, src/stdlib/SDL_sysstdlib.h, src/storage/SDL_storage.c, test/testfilesystem.c
This works well enough that testfilesystem.c can list all the .bmp files in its base directory, but someone should probably look over the WildcardMatch() function, because it feels a little fragile.
Fixes #9287.
=> filesystem: Added SDL_GlobDirectory().

include/SDL3/SDL_locale.h, include/SDL3/SDL_quit.h
In `SDL_quit.h`: removing `SDL_error.h` inclusion
In `SDL_locale.h` -> `SDL_GetPreferredLocales()`: adding `SDL_GetError()` comment
From #9444, fixes these:
SDL headers, which include `SDL_error.h` but don't have a comment about calling `SDL_GetError()`:
```
SDL_locale.h
SDL_quit.h
```
=> SDL_error.h inclusion and comment fixes

CMakeLists.txt, VisualC-GDK/SDL/SDL.vcxproj, VisualC-GDK/SDL/SDL.vcxproj.filters, VisualC-WinRT/SDL-UWP.vcxproj, VisualC-WinRT/SDL-UWP.vcxproj.filters, VisualC/SDL/SDL.vcxproj, VisualC/SDL/SDL.vcxproj.filters, Xcode/SDL/SDL.xcodeproj/project.pbxproj, include/SDL3/SDL_dialog.h, include/SDL3/SDL_hints.h, src/dialog/SDL_dialog_utils.c, src/dialog/SDL_dialog_utils.h, src/dialog/cocoa/SDL_cocoadialog.m, src/dialog/haiku/SDL_haikudialog.cc, src/dialog/unix/SDL_portaldialog.c, src/dialog/unix/SDL_unixdialog.c, src/dialog/unix/SDL_zenitydialog.c, src/dialog/windows/SDL_windowsdialog.c
- Add a globally-accessible function to handle the parsing of filter extensions (reduces difficulty of porting, and risks of adding memory issues)
- Remove the ability of putting the wildcard `*` among other patterns; it's either a list of patterns or a single `*` now
- Add a hint to select between portals and Zenity on Unix
I've also added some documentation for the callback.
The documentation for the hint would need review. I wrote what I think makes sense (I mostly copied the description of the similar video driver hint), but the writing style may need to be adjusted.
Closes #9432
=> File dialog improvements

build-scripts/SDL_migration.cocci, docs/README-migration.md, include/SDL3/SDL_oldnames.h, include/SDL3/SDL_pixels.h
fixes #9469
-------------------------------------------------------------------------
Steps to reproduce
Execute script:
```
./build-scripts/rename_api.py ./include/SDL3/SDL_pixels.h structure SDL_Colour SDL_Color
```
In `SDL_pixels.h` remove line:
```
#define SDL_Color SDL_Color
```
In `README-migration.md` replace this:
```
The following structures have been renamed:
* SDL_Colour => SDL_Color
```
with this:
```
The following macros have been removed:
* SDL_Colour - use SDL_Color instead
```
--------------------------------------------------------
I'm not sure about this line in `SDL_oldnames.h`:
```
#define SDL_Colour SDL_Colour_renamed_SDL_Color
```
because technically it wasn't renamed, but removed.
ps: I tried renaming `SDL_Colour` with the script as a symbol first, but when testing, …
=> Removing SDL_Colour macro

include/SDL3/SDL_surface.h
I noticed the Doxygen comments for SDL_FlipSurface and SDL_DuplicateSurface were not highlighting properly in my IDE (CLion).  I changed the start of both Doxygen comments from '/*' to '/**' to fix this.
=> Fixed Doxygen comments

include/SDL3/SDL_stdinc.h
Currently, SDL_stdinc.h has a documentation comment for SDL_acos(), but nothing else.
We should expand on that comment, and add comments for the remaining maths functions. This provides examples for the first few, in a format that seems okay to me.
In particular, note that functions like ``SDL_exp()`` are not expected to give the same result across different setups, as mentioned in #8948. 
This draft only covers up to SDL_expf() -- if the idea and format looks sound, I can add the remaining ones. Also, since we can just use the platform implementations, I'm not 100% sure the descriptions are prefectly correct for all possible implementations, but should be.
=> stdinc: Document maths functions

src/video/wayland/SDL_waylandwindow.c
=> wayland: Round fractional scale values when viewports aren't supported

include/SDL3/SDL_sensor.h
There is an existing SDL3 Wiki page at https://wiki.libsdl.org/SDL3/SDL_SensorType , the documentation in the header includes all the information in that Wiki page.
=> include: Fix documentation generation for SDL_SensorType.

include/SDL3/SDL_messagebox.h
Adds public documentation to an enumeration that did not have it before. The enumeration currently has a page in the SDL3 Wiki: https://wiki.libsdl.org/SDL3/SDL_MessageBoxColorType .
=> include: Add documentation to SDL_MessageBoxColorType.

src/audio/SDL_audio.c, src/audio/SDL_sysaudio.h, src/audio/pipewire/SDL_pipewire.c, src/core/linux/SDL_dbus.c, src/core/linux/SDL_dbus.h
If SDL is configured with both Pipewire and Pulseaudio support, this adds a preferred Pipewire bootstrap entry that uses DBus to query if the pipewire-pulse service exists and is in the "running" state. If it is, then it is certain that Pipewire is being used instead of Pulseaudio as the preferred system mixer and will be preferred over Pulseaudio. If DBus support is not enabled or Systemd is not being used on the underlying system, this check will simply fail and the standard driver order will be tested as before.
While still not 100% flawless, it is currently the best method for detecting if Pipewire is the preferred mixer for the system, as other possibilities have drawbacks:
- Simply checking for sinks/sources won't work, as Pipewire can still be used to mix audio and lists …
=> audio: Prefer Pipewire over Pulseaudio (take 2)

include/SDL3/SDL_sensor.h
Fixes #9515 , sorry about that. I have now actually run wikiheaders.pl beforehand and actually confirmed that the Wiki page is generated correctly.
=> include: Fixes the improper fix I made before of documentation, `SDL_SensorType`.

src/video/SDL_sysvideo.h, src/video/SDL_video.c, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h, src/video/x11/SDL_x11events.c, src/video/x11/SDL_x11window.c
Some fixes for Wayland and X11 to address issues with initial window placement, and jitter or incorrect behavior when moving fullscreen windows between displays.
Tested across Win32/Mac/X11/Wayland (GNOME, KDE, and Sway) with no regressions noted.
This seems to address the root cause of #8186, but it needs separate confirmation.
=> Miscellaneous windowing fixes

include/SDL3/SDL_oldnames.h
Adding following macro to SDL_oldnames.h:
#define SDL_atomic_t SDL_atomic_t_renamed_SDL_AtomicInt
=> SDL_atomic.h rename fixes

include/SDL3/SDL_test_compare.h, src/test/SDL_test_compare.c
When 2 memory blocks are not equal, this prints a xxd-style hexdump.
The hexdumps don't contain color codes because these show up in the raw github logs.
For example:
```
INFO:  04/03/24 02:36:57: Assert 'Sizes of memory blocks must be equal (256 == 256)': Passed
ERROR: 04/03/24 02:22:53: Assert 'Memory blocks contains the same data': Failed
ERROR: 04/03/24 02:22:53: 0000000000000000 42 4d 52 0e 01 00 00 00 00 00 2a 04 00 00 28 00 BMR.......*...(. | 2e 00 16 54 08 00 38 22 48 00 08 0a 14 00 62 42 ...T..8"H.....bB
ERROR: 04/03/24 02:22:53: 0000000000000010 00 00 98 01 00 00 a7 00 00 00 01 00 08 00 00 00 ................ | 4c 00 3a 34 32 00 6a 52 4e 00 62 34 30 00 06 20 L.:42.jRN.b40.. 
ERROR: 04/03/24 02:22:53: 0000000000000020 00 00 28 0a 01 00 6d 0b 00 00 6d 0b 00 00 fd 00 …
```
=> Add SDLTest_CompareMemory function to compare memory ranges

VisualC-GDK/SDL/SDL.vcxproj
This makes it so the build still works when the project is referenced by another solution.
=> Fixed reference path for buildshaders.bat

src/dialog/SDL_dialog_utils.c
`converted` is never freed on success, `combined` need to be freed on error.
None
=> Fix memory leak in dialog

src/video/windows/SDL_windowsmodes.c
Free `path_infos` and `mode_infos` in case of error.
None
=> Fix memory leak in WIN_GetMonitorPathInfo

test/testdialog.c
This fixes a few apparent problems in `test/testdialog.c`:
- Removes one empty `if` block that doesn't execute anything, neither in its body nor its condition.
- Adds a missing `SDL_Quit()` in an error branch that occurs after `SDL_Init()` was called.
=> Fixes for testdialog.c

src/core/linux/SDL_evdev_capabilities.c, src/core/linux/SDL_evdev_capabilities.h
Some psmouse touchpads were being misdetected as joysticks due to only having INPUT_PROP_SEMI_MT and  INPUT_PROP_POINTER as well as having BTN_1. I'm unsure if this is the best fix, but it definitely should fix this.
User has an old Synaptics touchpad that was being misdetected as a joystick. evtest lists the following evdev properties:
```
Input driver version is 1.0.1
Input device ID: bus 0x11 vendor 0x2 product 0x7 version 0x1b1
Input device name: "SynPS/2 Synaptics TouchPad"
Supported events:
Event type 0 (EV_SYN)
Event type 1 (EV_KEY)
Event code 256 (BTN_0)
Event code 257 (BTN_1)
Event code 258 (BTN_2)
Event code 259 (BTN_3)
Event code 272 (BTN_LEFT)
Event code 273 (BTN_RIGHT)
Event code 325 (BTN_TOOL_FINGER)
Event code 330 (BTN_TOUCH)
Event code 333 (BTN_TOOL_DOUBLETAP)
Event code …
```
=> evdev INPUT_PROP_SEMI_MT devices should be early-detected as touchpads

test/testffmpeg.c
=> Fixing testffmpeg.c fallthrough warning

Xcode/SDLTest/SDLTest.xcodeproj/project.pbxproj, test/testautomation.c
IOS: fix compilation of testautomation.app
only for IOS/TVOS, also disable testautomation_pen suite which requires sdl internals files
=> IOS: fix compilation of testautomation.app

src/video/n3ds/SDL_n3dsevents.c, src/video/n3ds/SDL_n3dstouch.c, src/video/n3ds/SDL_n3dstouch.h, src/video/n3ds/SDL_n3dsvideo.c, src/video/n3ds/SDL_n3dsvideo.h, test/testmouse.c
Without this, mouse events won't be generated when emulation is enabled.
=> 3DS: Ensure that touchscreen events are associated with a window

src/video/x11/SDL_x11video.c
That way we don't do the awful minimise on focus loss logic by default on XWayland where mode switching is emulated (like on the Wayland backend).
This fixes CS2, Dota 2 minimising on alt-tab when playing in fullscreen (which is really annoying when managing eg. Discord on another screen)
=> x11: Mark XWayland as MODE_SWITCHING_EMULATED

src/video/n3ds/SDL_n3dsframebuffer.c, src/video/n3ds/SDL_n3dsvideo.c, src/video/n3ds/SDL_n3dsvideo.h
I'm not sure the implementation of `SetDisplayMode` is correct since I can't figure out how to select modes that use `GSP_RGB565_OES` or `GSP_RGB5_A1_OES` with it, but these changes help make things faster compared to before.
Requires the changes from PRs #9519 and #9525.
=> 3DS: Improve framebuffer support

src/video/wayland/SDL_waylandwindow.c
If the if statement was not fulfilled, the pointers passed would be silently left unfilled.
I kept the `SDL_WindowData *data;` variable, although I'm not sure why it would need to be stored in a variable.
Fixes #9530
=> Replace if() with SDL_assert() in `Wayland_GetWindowSizeInPixels`

CMakeLists.txt
We currently build the following dylibs on Macos:
```
./lib/libSDL3.102.0.0.dylib
./lib/libSDL3.dylib
```
After this pr, these are:
```
./lib/libSDL3.0.dylib
./lib/libSDL3.dylib
```
The macho compatibility/current version is only added as metadata.
=> cmake: pass macho version information separately from so version

src/dialog/SDL_dialog_utils.c
When building the string in convert_filters, it forgets to allocate an extra space for the terminator character for each iteration. For Windows, this results in the trailing \x01 for each filter not actually being stored, which is undesirable. This fix simply adds 1 to new_length.
=> dialog: Allocate space for terminator when building filter string

src/video/wayland/SDL_waylandmessagebox.c
When closing message box by pressing escape, Zenity does not write to the pipe and fgets() get stuck waiting for EOF.
Fix #9565
=> Close pipe in Wayland_ShowMessageBox

include/SDL3/SDL_render.h
textures now default to linear filtering, use SDL_SetTextureScaleMode(texture, SDL_SCALEMODE_NEAREST) if you want nearest pixel mode instead
https://github.com/libsdl-org/SDL/blob/093160904d49d99c9e50467a3dd04c0f98f292d2/docs/README-migration.md?plain=1#L724
=> SDL3 removed SDL_HINT_RENDER_SCALE_QUALITY hint

src/hidapi/windows/hidapi_descriptor_reconstruct.h
I am compiling SDL using Zig and I hit a compilation error - the `SDL_COMPILE_TIME_ASSERT` macro wasn't available to this header. Following the convention of `SDL_riscosdefs.h`, I think it makes sense to include `SDL_internal.h` at the top of the header.
=> windows hidapi: fix header compilation

src/render/SDL_render.c, src/render/SDL_sysrender.h, src/render/direct3d/SDL_render_d3d.c, src/render/direct3d11/SDL_render_d3d11.c, src/render/direct3d12/SDL_render_d3d12.c, src/render/metal/SDL_render_metal.m, src/render/opengl/SDL_render_gl.c, src/render/opengles2/SDL_render_gles2.c, src/render/ps2/SDL_render_ps2.c, src/render/psp/SDL_render_psp.c, src/render/software/SDL_render_sw.c, src/render/software/SDL_render_sw_c.h, src/render/vitagxm/SDL_render_vita_gxm.c, src/render/vulkan/SDL_render_vulkan.c, src/video/SDL_video.c
This allows apps to destroy the window and renderer in either order, but makes sure that the renderer can properly clean up its resources while OpenGL contexts and libraries are still loaded, etc.
If the window is destroyed first, the renderer is (mostly) destroyed but its pointer remains valid. Attempts to use the renderer will return an error, but it can still be explicitly destroyed, at which time the struct is free'd.
If the renderer is destroyed first, everything works as before, and a new renderer can still be created on the existing window.
This also moves memory management of the SDL_Renderer struct itself out of the backends and to the higher level, which was necessary for this, but also turned out to be a nice code cleanup.
Fixes #9540.
=> render: SDL_DestroyWindow hollows out its renderer but doesn't free it. 

include/SDL3/SDL_render.h, include/SDL3/SDL_video.h, test/testautomation_video.c
-Removes the documentation about renderers being implicitly destroyed with windows.
-Cleans up renderers associated with windows in the automated video test suite.
Cleanups for #9540
=> Documentation and test updates for renderer destruction changes

cmake/sdlchecks.cmake, src/audio/pipewire/SDL_pipewire.c
Currently, the minimum version of the Pipewire library required to build the SDL backend is 0.3.20, with 0.3.24 required for basic operation. Several config keys have been backported from newer versions, and version checks are required to account for behavior changes. There seems to be little point in keeping the base build version so low for SDL 3, as every distro that isn't currently EOL-ed either [ships a much newer version than is required](https://repology.org/project/pipewire/versions), or, in the cases of Debian 11 and Ubuntu 20.02, ships a version below the base version of 0.3.20 that is currently required (0.3.19 and 0.2.7 respectfully, although Debian 11 backports offers 0.3.65).
This bumps the minimum version to 0.3.44 (released in Jan 2022), which allows for the removal of the …
=> pipewire: Raise minimum build version to 0.3.44

include/SDL3/SDL_surface.h
so it will link to the type in the docs/wiki (I hope it works this way :smile: )
=> reword SDL_BlitSurfaceScaled param

src/joystick/SDL_joystick.c
This change adds USB IDs for the Thrustmaster TS-XW racing wheel. This is related to https://github.com/berarma/oversteer/pull/200 and https://github.com/Kimplul/hid-tmff2/pull/94.
N/A
=> Add USB IDs for the Thrustmaster TS-XW racing wheel

src/joystick/linux/SDL_sysjoystick.c
This adds several early outs to the scanning before opening device files, if udev can returns information about devices, to avoid long synchronous device closes
* in `IsJoystick` if `SDL_UDEV_GetProductInfo` says device file is not joystick class
* in `IsSensor` if  `SDL_UDEV_GetProductInfo` says device file is not accelerometer class
* in `LINUX_ScanSteamVirtualGamepads` if `SDL_UDEV_GetProductInfo` says vendor and product isn't a Steam virtual gamepad
In #9092 it was revealed that closing device files can take anywhere from 0.5-0.01s. If the user has permissions to open a large number of device files, this can accumulate to significant startup time.
This resolves this in the case that the udev device data is available by using the udev devices data, which comes from _/run/udev_ or …
=> Significant device enumeration speedup by using udev info instead of opening device files

test/testlock.c
#fixes #9617
Replacing function call `kill(0, SIGINT);` with `(void)raise(SIGINT);` in file test/testlock.c.
The `kill()` function isn't available on Unix systems when compiling with STDC instead of GNUC.
=> testlock.c: Replacing function call kill with raise

CMakeLists.txt, configure, configure.ac
This option causes the compiler to automatically generate 256-bit vector instructions. This can cause errors on some machines(2k2000) that do not support 256-bit vectors. @madebr
=> loongarch: Delete the configuration of the compilation option "mlasx"

.gitignore
Useful when compiling with `CMake` and the `-D CMAKE_EXPORT_COMPILE_COMMANDS=YES` flag and then placing the `compile_commands.json` file (or a symlink) into the SDL directory for linting.
=> .gitignore: Adding compile_commands.json and .cache/

include/SDL3/SDL_events.h
In c8a0660 `SDL_eventaction` was renamed to `SDL_EventAction`.
At that time it only had an identifier in the ordinary name space.
Shortly after, ad090d2 added a tag name but it was the old name `SDL_eventaction`.
This commit here also changes the tag name to `SDL_EventAction`.
=> Renaming SDL_eventaction tag to SDL_EventAction

build-scripts/SDL_migration.cocci, docs/README-migration.md, include/SDL3/SDL_oldnames.h, include/SDL3/SDL_stdinc.h, src/video/haiku/SDL_bkeyboard.cc, src/video/kmsdrm/SDL_kmsdrmdyn.c, src/video/psp/SDL_pspevents.c, src/video/qnx/SDL_qnxkeyboard.c, src/video/wayland/SDL_waylanddyn.c, src/video/x11/SDL_x11dyn.c
For some structures, like a keymap, getting the "table-size" sounds more explicit than an "array-size", but having two names for exactly the same expression can also be confusing.
=> Removing function macro SDL_TABLESIZE()

android-project/app/src/main/java/org/libsdl/app/SDLActivity.java
This PR uses the new [`onTrimMemory()`](https://developer.android.com/reference/android/content/ComponentCallbacks2#onTrimMemory(int)) function instead of the old `onLowMemory()` to provide `SDL_EVENT_LOW_MEMORY` events to applications. `onTrimMemory()` provides different levels of memory to trim, but I've opted to always send the event.
From the docs: https://developer.android.com/reference/android/content/ComponentCallbacks#onLowMemory()
> Preferably, you should implement ComponentCallbacks2#onTrimMemory from ComponentCallbacks2 [...].
> That API is available for API level 14 and higher, so you should only use this onLowMemory() method as a fallback for older versions.
Since the SDL3 min API level is 19, there's no need for `onLowMemory()` compat.
=> Use `onTrimMemory()` instead of `onLowMemory()` on Android

include/SDL3/SDL_iostream.h
`num` was used in SDL2's SDL_RWwrite. SDL3's SDL_WriteIO only accepts `size` in bytes, so there's no reason for `num` to be here.
=> docs: rename num to size in SDL_iostream

include/SDL3/SDL_filesystem.h, src/filesystem/cocoa/SDL_sysfilesystem.m, src/filesystem/emscripten/SDL_sysfilesystem.c, src/filesystem/haiku/SDL_sysfilesystem.cc, src/filesystem/unix/SDL_sysfilesystem.c, src/filesystem/windows/SDL_sysfilesystem.c, src/filesystem/winrt/SDL_sysfilesystem.cpp, test/testdialog.c
The underlying implementations for `SDL_GetUserFolder()` generally (possibly all?) don't append a trailing path separator at the end of the paths. This PR adds the separator on all currently supported platforms.
I also added a missing `SDL_OutOfMemory()` for Cocoa.
Note that I couldn't test on all platforms. It would be good to confirm that all works as expected, and I didn't add a path separator when it's not needed for some platform.
I also took the opportunity to update the documentation (I copy-pasted the same line as for `SDL_Get{Base,Pref}Path()`) and updated `testdialog` accordingly.
Closes #9656
=> Add trailing path separator to SDL_GetUserFolder()

src/time/SDL_time.c
In SDL_time.c SDL_GetDaysInMonth()
Setting the number of days in january to 31.
=> Fix SDL_GetDaysInMonth() num days in january

src/filesystem/cocoa/SDL_sysfilesystem.m, src/filesystem/unix/SDL_sysfilesystem.c
@Sackzement noticed [here](https://github.com/libsdl-org/SDL/pull/9658#issuecomment-2089933247) that the specific case of `SDL_FOLDER_HOME` did not have a trailing slash on Unix and/or Cocoa. This PR fixes both cases :)
=> Add trailing '/' to `SDL_GetUserFolder(SDL_FOLDER_HOME)` on Cocoa and Unix

src/dynapi/SDL_dynapi.h
Same issue as other static analyzers, stops visual studio showing multiple definitions when trying to navigate to a function.
=> Disable SDL_DYNAMIC_API during IntelliSense

docs/README-wayland.md, include/SDL3/SDL_hints.h, src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandevents_c.h, src/video/wayland/SDL_waylandmouse.c, src/video/wayland/SDL_waylandwindow.c, test/testmouse.c
The pointer confinement protocol does allow warping the pointer via a hint, provided that the window has focus, the pointer is locked at the time of the request, and the requested coordinates fall within the bounds of the window.
Toggle the pointer locked state and request the pointer warp when the required protocol is available. This is similar to what XWayland does internally, and what commit [a845c70](https://github.com/libsdl-org/SDL/commit/a845c7027e68ff1c75bf814819d8e6b22499d899) causes to happen behind the scenes.
The warp emulation using relative mode that is triggered when warping a hidden cursor remains enabled by default for now, as otherwise, the cursor could potentially leave the window if it is moved fast enough, and once out, it can't be warped back in.
=> wayland: Add mouse pointer warp support

include/SDL3/SDL_dialog.h
I added more links to various document pages in the documentation, after I saw the current page for `SDL_ShowOpenFIleDialog` did not have any links to `SDL_DialogFileCallback`:
I also edited the documentation to be more up-to-date (adding info about the `filter` param in the callback) and I clarified that a filter of -1 is not an error flag, considering [this comment](https://github.com/libsdl-org/SDL/issues/9631#issuecomment-2080992840).
=> Add more links in SDL_dialog documentation

src/dynapi/gendynapi.py
When running `gendynapi.py` in Windows (non-cygwin) version of Python, the whole `SDL_dynapi.sym` is rewritten with CRLF line endings. Furthermore, the modified header files has CRLF line endings in it.
Fortunately, the fix is simple. Simply add `newline=""` when opening the file for writing. It tells Python to disable any newline translation.
=> gendynapi.py: Fix output line ending when running in non-cygwin Windows.

src/video/x11/SDL_x11events.c
=> x11: Fix text input not being null-terminated

android-project/app/proguard-rules.pro, android-project/app/src/main/java/org/libsdl/app/SDLActivity.java, include/SDL3/SDL_iostream.h, src/core/android/SDL_android.c, src/core/android/SDL_android.h, src/file/SDL_iostream.c
Allow opening `content://` URIs using `SDL_IOFromFile` in Android.
This change allows `SDL_IOFromFile` to open Android's `content://` URI retrieved either through file dialogs (#9687) or by other means. The motivation of this change is mainly to support former usecase as Android doesn't return ordinary file paths rather than `content://` URIs.
This change used to be in the Android file dialog pull request but I've been asked to separate the `SDL_IOFromFile` changes and remove the `SDL_AndroidOpenFileDescriptor` API.
=> Android: Allow SDL_IOFromFile to open content:// URI.

src/SDL_properties.c, src/camera/mediafoundation/SDL_camera_mediafoundation.c, src/video/SDL_video.c, test/testautomation_properties.c
The documentation for `SDL_SetPropertyWithCleanup` mentions that the cleanup function is called upon failure. But this wasn't working in the code.
- Closes https://github.com/libsdl-org/SDL/issues/9642
=> Fix property cleanup callback not being called on error

src/audio/wasapi/SDL_wasapi.c
Old `IAudioClient_Initialize` doesn't allow shared streams to set [periodicity](https://learn.microsoft.com/en-us/windows/win32/api/audioclient/nf-audioclient-iaudioclient-initialize#parameters).
Starting from Windows 10, a new interface IAudioClient3 can be used to initialize a shared audio stream with periodicity set in sample frame unit. 
This PR uses `device->sample_frames` to let users adjust latency through `SDL_AUDIO_DEVICE_SAMPLE_FRAMES`, and the value will get rounded to the closest possible value.
I did a rough test to measure latency difference on osu! with my changes:
1. Place speaker, keyboard, and microphone closely to one another
2. Start recording, and play a very simple chart with beep hitsound
3. Measure the gap between hitsound and keyboard hit with Audacity
I got …
=> wasapi: Use IAudioClient3 if possible to make use of sample_frames

src/video/windows/SDL_windowsevents.c, src/video/windows/SDL_windowswindow.c
Some API calls (`LoadIcon()`, `EnableWindow()`) are only available on desktop.
=> VisualC-GDK: Fix Xbox builds

src/dialog/SDL_dialog_utils.c, src/dialog/unix/SDL_portaldialog.c, src/dialog/windows/SDL_windowsdialog.c
This fixes some issues with dialogs:
- Properly handle `NULL` filter and empty (0-length) filter list on Windows
- Enforce a filter being terminating if it doesn't have both a name and a pattern (some places enforced only the name, but used the pattern)
- Add some missing callback calls in the DBus implementation
- Remove a few unneeded calls to SDL_OutOfMemory
Fixes #9702
=> Fixes and improvements for dialogs

include/SDL3/SDL_video.h, src/video/kmsdrm/SDL_kmsdrmvideo.c
Queries the "panel orientation" property on the connector and reports it in degrees of rotation via the 'SDL.display.KMSDRM.panel_orientation' display property.
This is provided by the kernel as a hint to userspace applications, and the application itself is ultimately responsible for any required coordinate transformations needed to conform to the requested orientation.
Closes #9682
=> kmsdrm: Report the panel orientation hint property 

src/audio/SDL_audio.c, src/audio/SDL_audioqueue.c, src/camera/emscripten/SDL_camera_emscripten.c, src/core/android/SDL_android.c, src/dialog/cocoa/SDL_cocoadialog.m, src/dialog/unix/SDL_portaldialog.c, src/dialog/unix/SDL_zenitydialog.c, src/dialog/windows/SDL_windowsdialog.c, src/joystick/gdk/SDL_gameinputjoystick.c, src/joystick/hidapi/SDL_hidapi_steamdeck.c, src/storage/steam/SDL_steamstorage.c, src/test/SDL_test_harness.c, src/thread/SDL_thread.c, src/video/n3ds/SDL_n3dsvideo.c, src/video/x11/SDL_x11mouse.c
Since commit 447b508a77b8601d23ca48cf189fe4436ab33572, SDL_malloc, SDL_calloc, and SDL_realloc already calls SDL_OutOfMemory().
If this is good, I can do the same for SDL3 satellite libraries.
=> remove most of SDL_OutOfMemory() calls where SDL is the allocator.

include/SDL3/SDL_stdinc.h
These are needed when `INT64_C` and `UINT64_C` macros are either not
available (not likely), or guarded by `__STDC_LIMIT_MACROS` in C++
compilations (which is the case in many old SDKs.)
@icculus: Don't know if this is good wrt documentation (i.e. wikiheaders, etc)
CC: @Sackzement
=> SDL_stdinc.h: add fallback cases for SDL_SINT64_C and SDL_UINT64_C

src/video/x11/SDL_x11sym.h
Noticed this in SDL-1.2 in a gcc-13 build, which emitted the following
warning:  (No such warnings in SDL2 and SDL3, due to macro differences)
```
./src/video/x11/SDL_x11sym.h:84:48: warning: argument 2 of type 'char *' declared as a pointer [-Warray-parameter=]
84 | SDL_X11_SYM(int,XQueryKeymap,(Display* a,char *b),(a,b),return)
|                                          ~~~~~~^
./src/video/x11/SDL_x11dyn.c:95:15: note: in definition of macro 'SDL_X11_SYM'
95 |         rc fn params { ret p##fn args ; }
|               ^~~~~~
In file included from ./src/video/x11/SDL_x11dyn.h:27,
from ./src/video/x11/SDL_x11dyn.c:26:
/usr/include/X11/Xlib.h:2980:5: note: previously declared as an array 'char[32]'
2980 |     char [32]           /* keys_return */
|     ^~~~~~~~~
```
The original actually …
=> SDL_x11sym.h: corrected XQueryKeymap() proto.

src/stdlib/SDL_iconv.c
The change matches the intention, yes?
Noticed this in SDL-1.2 where gcc-13 emits a -Wuse-after-free warning.
No such warning in SDL2 and SDL3, because unlike SDL1.2, SDL_realloc()
is not a macro expanding to libc realloc(). It warns, of course, if
SDL_realloc() is replaced with plain realloc():
```
src/stdlib/SDL_iconv.c: In function 'SDL_iconv_string_REAL':
src/stdlib/SDL_iconv.c:824:39: warning: pointer 'oldstring' may be used after 'realloc' [-Wuse-after-free]
824 |             outbuf = string + (outbuf - oldstring);
|                               ~~~~~~~~^~~~~~~~~~~~
src/stdlib/SDL_iconv.c:818:30: note: call to 'realloc' here
818 |             string = (char *)realloc(string, stringsize + sizeof(Uint32));
|                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
```
=> SDL_iconv_string: simplify recomputation of outbuf and outbytesleft

include/SDL3/SDL_keyboard.h
This shrinks the structure by 32-bits because we've removed implicit padding between the fields.
This doesn't affect sdl2-compat because the keysym is the last field in the structure and sizeof(keysym.mod) is the same.
=> Use the correct type for the modifier in SDL_Keysym

src/dialog/unix/SDL_portaldialog.c
If you close the file dialog on Linux using the escape key or killing the window, `SDL_ShowOpenFileDialog` returns NULL (error) to the callback, even if this should count as the user canceling the dialog.
=> Do not throw error using escape to close file dialog

include/SDL3/SDL_hints.h, src/audio/pipewire/SDL_pipewire.c, src/audio/pulseaudio/SDL_pulseaudio.c
Add a new hint, `SDL_HINT_AUDIO_DEVICE_APP_ICON_NAME`, to request an XDG icon name which may be displayed in audio mixers, such as pavucontrol and the KDE Plasma sound settings.
Here is the description I've added to the hints header file:
```
/**
* Specify an application icon name for an audio device.
*
* Some audio backends (such as Pulseaudio and Pipewire) allow you to set an
* XDG icon name for your application. Among other things, this icon might show
* up in a system control panel that lets the user adjust the volume on specific
* audio streams instead of using one giant master volume slider. Note that this
* is unrelated to the icon used by the windowing system, which may be set with
* SDL_SetWindowIcon (or via desktop file on Wayland).
*
* Setting this to "" or leaving it unset …
```
=> Add SDL_HINT_AUDIO_DEVICE_APP_ICON_NAME

test/testautomation_clipboard.c
Clipboard allocations were being leaked in two instances.
Fixes #9778
=> test: Free clipboard data after calling SDL_GetClipboardText()

include/SDL3/SDL_scancode.h
usb.org updated the HID specification this year to version 1.5.
This commit updates the link in `SDL_scancode.h` to point to the new pdf version.
It also removes the second link near the bottom of the file.
=> SDL_scancode.h: Updating HID usage tables link

include/SDL3/SDL_blendmode.h
Regressed when SDL_BlendMode was changed from an enum to a typedef Uint32.
=> Fix missing #include in SDL_blendmode.h

include/SDL3/SDL_render.h
This PR expands the documentation of `SDL_SetRenderVSync` to mention how to disable vsync. Also replaces magic integer values used to describe vsync with `SDL_RENDERER_VSYNC_ADAPTIVE` and `SDL_RENDERER_VSYNC_DISABLED` defines.
`SDL_HINT_RENDER_VSYNC` could also be updated to support `-1`, `2`, `3` etc. It says [`0` is the default](https://github.com/libsdl-org/SDL/blob/8b5f0d07e995cf216d2268863e0deb77bb621300/include/SDL3/SDL_hints.h#L2573-L2588), but [`SDL_GetHintBoolean` is called with SDL_TRUE](https://github.com/libsdl-org/SDL/blob/17520c2e6eeac14839ecc510472353bf84a9c985/src/render/SDL_render.c#L972) (after checking that the hint is set).
- Closes https://github.com/libsdl-org/sdlwiki/issues/533
=> Add defined constants for renderer vsync values

src/camera/pipewire/SDL_camera_pipewire.c
SDL expects an interval fraction to be provided by the backend, but pipewire provides a framerate fraction, so we we just switch them.
```
SDL Camera Driver: v4l2
- Camera #0: Chicony USB2.0 Camera: Chicony
- 1280x720@10 SDL_PIXELFORMAT_YUY2
/- d10 n1
- 640x480@30 SDL_PIXELFORMAT_YUY2
/- d30 n1
```
pw (wrong)
```
SDL Camera Driver: pipewire
- Camera #0: Chicony USB2.0 Camera (V4L2)
- 1280x720@0.1 SDL_PIXELFORMAT_YUY2
/- d1 n10
- 640x480@0.0333333 SDL_PIXELFORMAT_YUY2
/- d1 n30
```
CC @wtay
=> fix pipewire camera interval fraction inversion

src/joystick/SDL_joystick.c
Added more devices in SDL wheel list, to enable wheel detection for them
Added devices:
- Simucube 1 
- Simucube 2 Ultimate
- Simucube 2 Pro
- Simucube 2 Sport
- Cammus C5
- Moza R3
- Moza R5
- Moza R9
- Moza R12
- Moza R16
- Moza R21
=> Added more wheel VID/PIDs in wheel devices list

.github/workflows/main.yml
DMG creation on macOS occasionally fails, so try multiple times https://gitlab.kitware.com/cmake/cmake/-/issues/25671
Fixes #9815
=> ci: retry package creation multiple times

include/SDL3/SDL_begin_code.h
Add a `SDL_NODISCARD` macro that, when applied to a function, warns the user of that function if the return value is ignored. The presence of this macro prevents defects in programs caused by forgetting to check a function's error code return value, either by absentmindedness or because the function's name did not suggest that an error code would be returned.
~~As a proof of concept, the `SDL_NODISCARD` macro has been selectively applied to some functions in `SDL_audio`.~~
The `SDL_NODISCARD` macro expands to, in order:
- `[[nodiscard]]` in C++17 and C23;
- otherwise, `__attribute__((warn_unused_result))` for GCC and Clang;
- otherwise, `_Check_return_` in MSVC;
- otherwise, expands to nothing.
The `SDL_NODISCARD` macro could theoretically be applied on any function that returns a value …
=> Add `SDL_NODISCARD` macro to `SDL_begin_code.h`

src/video/wayland/SDL_waylandvulkan.h, src/video/windows/SDL_windowsvulkan.h, src/video/x11/SDL_x11vulkan.h
Fixes the following errors in x11. (The wayland and windows code touched w/o build-testing but passes the CI runs.)
CC: @Lephar (also CC: @Sackzement )
<details>
```
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
from /tmp/SDL3/src/video/x11/SDL_x11clipboard.c:27:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:101: error: redefinition of typedef ‘VkInstance’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:53: note: previous declaration of ‘VkInstance’ was here
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
from …
```
=> fix type redefinition errors after #9817

src/test/SDL_test_common.c, src/video/SDL_video.c, test/testatomic.c, test/testcamera.c, test/testiconv.c
This pr fixes leaks in `testatomic` and `testiconv`  when running with `--trackmem`.
It also fixes printing of the following debug messages when exiting `testcamera`:
```
DEBUG: Parameter 'texture' is invalid
DEBUG: Parameter 'renderer' is invalid
DEBUG: Invalid window
DEBUG: Invalid window
```
This pr does *not* address the leak in testautomation. See issue 9778.
=> tests: fix some leaks + fix debug messages when exiting testcamera

src/events/SDL_touch.c
- See https://github.com/libsdl-org/SDL/issues/9810#issuecomment-2120834171 for deep dive into the double-free.
- Regressed with https://github.com/libsdl-org/SDL/commit/1862a62b5d22c90323ddb257d75974348c3c807e.
- Tested on Windows to not cause crashes and the nonsense described in the issues below.
- Closes https://github.com/libsdl-org/SDL/issues/9591
- Closes https://github.com/libsdl-org/SDL/issues/9810
- Closes https://github.com/libsdl-org/SDL/issues/9833
- Closes downstream issue https://github.com/ppy/osu/issues/28211
=> Fix finger double free and general SDL_Finger event nonsense

src/video/SDL_blit_copy.c
This is a draft pull request to remove MMX code from SDL3.
There are only three places we use it. One of them is likely superfluous (SDL_BlitCopy), and I have removed it in this first commit. The other two appear like they would be good candidates for replacement with SSE versions, which will let us operate on twice as much data at a time (at least at first glance; I could be wrong).
=> MMX code removal

include/SDL3/SDL_test_common.h, src/test/SDL_test_common.c
To help debugging SDL applications that are running with the cursor hidden, provide an option to hide the cursor in SDL tests at startup, and a key toggle to show / hide the cursor while the test is running.
The prime target is `testwm`, but as the option  and the key are handled by `SDL_test_common.c`, this in fact applies to any SDL test that uses `SDLTest_CommonInit`.
**Changes:**
- In `include/SDL3/SDL_test_common.h` : Add flag `state->hide_cursor`,
- In `src/test/SDL_test_common.c` : Handle option `--hide-cursor` setting `state->hide_cursor` to apply `SDL_HideCursor` downstream, Handle `Ctrl-h` toggle to `SDL_HideCursor` and `SDL_ShowCursor`. Also two replacements of tabs to spaces.
**NB** There are no SDL test that use `Ctrl-h` except `testmodal`, and `testmodal` does not use …
=> TESTWM : Option --hide-cursor and Keyboard toggle Ctrl-h to ShowCursor and HideCursor

.github/workflows/android.yml, android-project/app/build.gradle, android-project/app/jni/src/CMakeLists.txt, android-project/app/jni/src/YourSourceHere.c
This also:
- Modifies the gradle project file to use the CMake script by default instead of the `Android.mk` makefile
- Adds a minimum, barely functioning, SDL app
ci job output:
https://github.com/libsdl-org/SDL/actions/runs/9181472626/job/25248284307?pr=9849
=> ci: build simple Android SDL app using gradle

include/SDL3/SDL_dialog.h
I added documentation for dialogs about the case on Linux where handling events is required.
I did not mention the workaround with `SDL_SetHint(SDL_HINT_FILE_DIALOG_DRIVER, "zenity")` because I'm not sure how reliable that is (not all systems ship zenity, some features like modality don't work with zenity, some behavior may change in the future, new options can pop, etc).
Fixes #9703 somewhat, I'm not sure there can be any better fix than that.
=> Add documentation about dialogs and events

src/core/gdk/SDL_gdk.cpp, src/core/windows/SDL_windows.c
Otherwise, this will crash if the app sets its own SDL_malloc allocator, since SDL_iconv uses SDL_malloc.
WideCharToMultibyte lets us calculate the needed memory for the argv[] string conversions, and then we use the win32 HeapAlloc() API to get some memory for it.
Fixes #8967.
=> windows: Before SDL_main has run, use WideCharToMultibyte, not SDL_iconv.

src/video/emscripten/SDL_emscriptenevents.c
Added 1 to touchid received from emscriptien. 
When browsing a emscripten project on android, if I click the window, the assertion at line 212 in `src/events/SDL_touch.c` triggers. Which leads to crash.
```
WARN: [TileMap.js:1628:16](http://mysite:8000/TileMap.js)
<empty string> [TileMap.js:1628:16](http://mysite:8000/TileMap.js)
Assertion failure at SDL_AddFinger (/home/user/Developer/web/SDL/src/events/SDL_touch.c:212), triggered 1 time: [TileMap.js:1628:16](http://mysite:8000/TileMap.js)
'fingerid != 0' [TileMap.js:1628:16](http://mysite:8000/TileMap.js)
<empty string> [TileMap.js:1628:16](http://mysite:8000/TileMap.js)
`allocate` is a library symbol and not included by default; add it to your library.js __deps or to DEFAULT_LIBRARY_FUNCS_TO_INCLUDE on the command line (e.g. …
```
=> Fix touchid assertion faliure on emscripten

src/dialog/unix/SDL_portaldialog.c
XDG Portals returned file paths as `file:///path/to/file`; this PR truncates the "file://" part.
Fixes #9863
=> Dialog: XDG Portals: Remove the `file://` URI

VisualC-GDK/SDL/SDL.vcxproj, VisualC-GDK/SDL_test/SDL_test.vcxproj, VisualC-GDK/tests/testcontroller/testcontroller.vcxproj, VisualC-GDK/tests/testgdk/testgdk.vcxproj, VisualC-GDK/tests/testsprite/testsprite.vcxproj, VisualC/SDL/SDL.vcxproj, VisualC/SDL_test/SDL_test.vcxproj, VisualC/tests/checkkeys/checkkeys.vcxproj, VisualC/tests/loopwave/loopwave.vcxproj, VisualC/tests/testatomic/testatomic.vcxproj, VisualC/tests/testautomation/testautomation.vcxproj, VisualC/tests/testcontroller/testcontroller.vcxproj, VisualC/tests/testdraw/testdraw.vcxproj, VisualC/tests/testfile/testfile.vcxproj, VisualC/tests/testgl/testgl.vcxproj, VisualC/tests/testgles2/testgles2.vcxproj, VisualC/tests/testoverlay/testoverlay.vcxproj, VisualC/tests/testpen/testpen.vcxproj, VisualC/tests/testplatform/testplatform.vcxproj, VisualC/tests/testpower/testpower.vcxproj, VisualC/tests/testrendertarget/testrendertarget.vcxproj, VisualC/tests/testrumble/testrumble.vcxproj, VisualC/tests/testscale/testscale.vcxproj, VisualC/tests/testsensor/testsensor.vcxproj, VisualC/tests/testshape/testshape.vcxproj, VisualC/tests/testsprite/testsprite.vcxproj, VisualC/tests/testsurround/testsurround.vcxproj, VisualC/tests/testvulkan/testvulkan.vcxproj, VisualC/tests/testwm/testwm.vcxproj, VisualC/tests/testyuv/testyuv.vcxproj
Only thing these do is define a _VC80_UPGRADE macro.
=> VC: don't import Microsoft.CPP.UpgradeFromVC[67]0.props projects

docs/README-migration.md
Fixes an incorrect name in the migration guide.
=> Correct name for SDL_CreateThreadWithStackSize()

src/render/opengl/SDL_render_gl.c
Remove duplicated texture format in OpenGL renderer.
=> opengl: remove duplicated texture format

CMakeLists.txt, configure, configure.ac, src/render/direct3d12/SDL_render_d3d12.c
Backport of https://github.com/libsdl-org/SDL/pull/9867, and its successor 89a4d9ae67e82913af71a93611f396530a05f61d
Looks like running `autogen.sh` also fixes support for latest gcc.
=> [SDL2] [d3d12] Older Windows SDK contain bad function prototypes, so declare our own

src/test/SDL_test_common.c, test/loopwave.c, test/testaudio.c, test/testaudiocapture.c, test/testcamera.c, test/testdropfile.c, test/testsprite.c
Use the new main callback code macros in the tests that use those callbacks, as discussed in #9883.
=> Tests: Use the main callback code macros

CMakeLists.txt, cmake/sdlchecks.cmake, configure.ac, src/video/raspberry/SDL_rpivideo.h
This is required with newer versions of Raspberry Pi OS that don't supply the custom EGL headers with the rest of the dispmanx headers.
=> Allow building the Raspberry Pi video driver with standard EGL headers (SDL2)

src/time/psp/SDL_systime.c
SDL3 failed to build with the current version of the pspdev toolchain, because of this missing header. No idea when it changed.
Added `#include <psptypes.h>` to `SDL_systime.c`
- N/A
=> SDL_systime.c: missing include for PSP toolchain

src/core/windows/SDL_windows.h
to make sure `DISPLAYCONFIG_SDR_WHITE_LEVEL` is visible to us.
=> SDL_windows.h: set _WIN32_WINNT to 0xA00 if dxgi1_6.h is available

src/video/x11/SDL_x11window.c
Otherwise, the window manager can think that the window is larger than it is and try to resize/reposition it according to the constraints.
Fixes #9915
=> x11: Use the floating size for the initial constraints on non-resizable windows

src/video/windows/SDL_windowswindow.c
warnings from gcc-7.5:
```
/tmp/SDL3/src/video/windows/SDL_windowswindow.c: In function 'WIN_SetWindowPositionInternal':
/tmp/SDL3/src/video/windows/SDL_windowswindow.c:216:17: warning: 'h' may be used uninitialized in this function [-Wmaybe-uninitialized]
rect.bottom = *height;
~~~~~~~~~~~~^~~~~~~~~
/tmp/SDL3/src/video/windows/SDL_windowswindow.c:320:12: note: 'h' was declared here
int w, h;
^
/tmp/SDL3/src/video/windows/SDL_windowswindow.c:215:16: warning: 'w' may be used uninitialized in this function [-Wmaybe-uninitialized]
rect.right = *width;
~~~~~~~~~~~^~~~~~~~
/tmp/SDL3/src/video/windows/SDL_windowswindow.c:320:9: note: 'w' was declared here
int w, h;
^
```
=> WIN_AdjustWindowRectWithStyle: silence gcc maybe-uninitialized warnings

src/events/SDL_events.c
This changes SDL_SetEventFilter to only cut events that don't pass the user filter instead of flushing the entire list.
This also prevents the event queue from being flushed when the user is removing a filter with `SDL_SetEventFilter(NULL, NULL)`.
Fixes #9592
=> SDL_SetEventFilter: Don't flush good events

src/video/windows/SDL_windowsmodes.c, src/video/windows/SDL_windowsvideo.c, src/video/windows/SDL_windowsvideo.h
Question: Why are we not using `GetModuleHandle()` in there for peeking
into user32.dll? Is GDK or XBOX in the way or something? If not, I easily
can change the patch to use `GetModuleHandle()`.
=> move vista+ display config function ptr calls to device->driverdata

android-project/app/src/main/AndroidManifest.xml, android-project/app/src/main/res/values/styles.xml
Custom theme file exists in project, but is not used by app, which is kinda unintuitive. Using it by default so people who not familiar with Android development won't spend lots of time troubleshooting.
=> android: Default to custom theme in styles.xml

src/video/SDL_video.c, src/video/x11/SDL_x11window.c
This prevents the GNOME window manager from moving the window to a different display before the window goes fullscreen.
Fixes https://github.com/libsdl-org/SDL/issues/9915
=> Don't set the borderless flag if we're about to go fullscreen.

include/SDL3/SDL_stdinc.h
Avoids -Wformat warnings from mingw toolchains -- e.g.:
`src/test/SDL_test_harness.c:581:37: warning: unknown conversion type character 'l' in format [-Wformat=]`
The warnings happened to me with the gcc7.5 and mingw-v8.x based mingw
toolchain. Since we enable `_GNU_SOURCE` and/or C99, mingw headers seem
to enable `__USE_MINGW_ANSI_STDIO` which in turn defines `PRI?64` macros
using `ll` instead of `I64`. I don't know other gcc and/or mingw version
combinations but `I64` is always safe, as far as I know.
If this is acceptable, can I apply to SDL2 too?
=> always define PRI?64 using 'I64' when targeting windows

src/SDL.c, src/SDL_hashtable.c, src/SDL_internal.h, src/SDL_utils.c, src/SDL_utils_c.h, src/audio/SDL_audio.c, src/audio/dsp/SDL_dspaudio.c, src/events/SDL_keyboard.c, src/haptic/SDL_haptic.c, src/haptic/SDL_syshaptic.h, src/hidapi/SDL_hidapi.c, src/joystick/SDL_gamepad.c, src/joystick/SDL_joystick.c, src/joystick/SDL_joystick_c.h, src/joystick/SDL_sysjoystick.h, src/joystick/hidapi/SDL_hidapijoystick.c, src/joystick/hidapi/SDL_hidapijoystick_c.h, src/joystick/linux/SDL_sysjoystick.c, src/render/SDL_render.c, src/render/SDL_sysrender.h, src/render/opengl/SDL_render_gl.c, src/sensor/SDL_sensor.c, src/sensor/SDL_syssensor.h, src/video/SDL_sysvideo.h, src/video/SDL_video.c, src/video/wayland/SDL_waylandwindow.c, src/video/x11/SDL_x11events.c, src/video/x11/SDL_x11window.c
Instead of using the magic tag in the object, we'll actually keep track of valid objects
Fixes https://github.com/libsdl-org/SDL/issues/9869
Fixes https://github.com/libsdl-org/SDL/issues/9235
=> Prevent crashes if freed objects are passed to SDL API functions

include/SDL_assert.h
GCC 15 development branch provides an experimental support for Windows on ARM64, which will be officially released next year, according to latest news. I tried to compile SDL2 with this new compiler but I got a problem into SDL_assert.h because it couldn't find the right platform. However, it has been easy to fix and I included it into this PR. 
More details can be also found here:
https://learn.microsoft.com/en-us/cpp/intrinsics/debugbreak?view=msvc-170
Probably, this tiny fix also needs to be imported into SDL3 development branch.
=> SDL_assert: add support for aarch64-w64-mingw32

docs/README-migration.md, include/SDL3/SDL_render.h, src/core/winrt/SDL_winrtapp_direct3d.cpp, src/dynapi/SDL_dynapi.sym, src/dynapi/SDL_dynapi_overrides.h, src/dynapi/SDL_dynapi_procs.h, src/render/SDL_render.c, src/render/SDL_sysrender.h, src/render/direct3d/SDL_render_d3d.c, src/render/direct3d11/SDL_render_d3d11.c, src/render/direct3d12/SDL_render_d3d12.c, src/render/metal/SDL_render_metal.m, src/render/opengl/SDL_render_gl.c, src/render/opengles2/SDL_render_gles2.c, src/render/ps2/SDL_render_ps2.c, src/render/psp/SDL_render_psp.c, src/render/software/SDL_render_sw.c, src/render/vitagxm/SDL_render_vita_gxm.c, src/render/vulkan/SDL_render_vulkan.c, src/test/SDL_test_common.c, src/video/SDL_video.c, test/testcolorspace.c, test/testffmpeg.c
The texture formats are available via the SDL_PROP_RENDERER_TEXTURE_FORMATS_POINTER property
Fixes https://github.com/libsdl-org/SDL/issues/9851
=> Replaced SDL_GetRendererInfo() with SDL_GetRendererName()

src/joystick/SDL_joystick.c, src/joystick/SDL_joystick_c.h, src/joystick/hidapi/SDL_hidapi_ps4.c
`SDL_HINT_JOYSTICK_HIDAPI_PS4_REPORT_INTERVAL` allows to change sensor rate. Make `SDL_GetGamepadSensorDataRate()` returns the updated value.
None
=> Update gamepad sensor rate

src/file/SDL_iostream.c
If `Android_JNI_FileOpen()` or `windows_file_open()` fail, `SDL_CloseIO(iostr)` does nothing because `iostr` is NULL and `iodata` is leaked.
None
=> Fix memory leak in SDL_IOFromFile()

src/camera/SDL_camera.c
If allocation of `p` fails, `pending_tail` points to `pending`. Fix is similar to what is done in `SDL_CameraDeviceDisconnected()`.
None
=> Fix stack address escape in SDL_CameraDevicePermissionOutcome()

src/render/SDL_render.c
It's possible to destroy an SDL_Renderer without freeing it using SDL_DestroyRendererWithoutFreeing(), which is used to make it possible to destroy windows and their renderers in either order. However, if a renderer has already been destroyed before it is freed (e.g., the window was destroyed before the renderer), the object is never marked invalid. This means the SDL_Renderer is reported as leaked, even if SDL_DestroyRenderer() is called.
SDL_GetWindowSurface() will trigger this, as the window texture is cleaned up _after_ the window destroys its associated renderer. This makes it impossible to use SDL_FRAMEBUFFER_ACCELERATION without triggering a leak warning.
Fix this by unconditionally marking the SDL_Renderer object as invalid in SDL_DestroyRenderer().
=> renderer: Mark an already-destroyed renderer as freed

src/video/SDL_video.c, src/video/psp/SDL_pspvideo.c
This adds support for the integrated on screen keyboard for the Playstation Portable in SDL2.
This is a little bit more disruptive than is normally expected for OSKs in SDL, since it locks up the main thread. I was not able to make it work in another way unfortunately, but it works quite well. Not sure how it affect playing music or sounds.
Once we have this merged, I can port it up to SDL3 as well.
=> PSP: Add on-screen keyboard support

src/render/psp/SDL_render_psp.c
I fixed a crash being caused by `SDL_DestroyRenderer()` on PSP.
- I removed a call to `StartDrawing()` in in `PSP_DestroyRenderer()` because it was causing a crash. I've attached an image of the backtrace in GDB, but I don't know much else. It looks like `psp_texture` is becomes a null pointer
and becomes dereferenced in the function `TextureBindAsTarget()`.
- N/A
=> SDL_render_psp.c: Fix crash in PSP_DestroyRenderer()

src/camera/coremedia/SDL_camera_coremedia.m, test/testcamera.c
Before:
After
`AVCaptureVideoDataOutput.videoSettings` should be initialized to zero to receive frames matching the device format. On my setup this was defaulting to `2vuy`, which broke testcamera because it was expecting the same format as the capture device (`420v`).
See: https://developer.apple.com/documentation/avfoundation/avcapturevideodataoutput/1389945-videosettings?language=objc
I also added a parameter to select a specific camera by name with running testcamera.
All the cameras I could find output NV12 frames so I wasn't able to test with other pixel formats.
Noticed here: https://github.com/libsdl-org/SDL/issues/9930#issuecomment-2141060439
=> camera: Fix corrupted CoreMedia input

src/video/psp/SDL_pspmessagebox.c, src/video/psp/SDL_pspmessagebox.h, src/video/psp/SDL_pspvideo.c
It's a basic implementation of SDL_ShowMessageBox on PSP.
I wrote this based on the [pspdev example](https://github.com/pspdev/pspsdk/blob/master/src/samples/utility/msgdialog/main.c) and [sharkwouter:SDL:psp-message-dialog](https://github.com/libsdl-org/SDL/compare/main...sharkwouter:SDL:psp-message-dialog). The one major caveat is that it doesn't work if the GL/GU backend has not been initialized yet, so it fails to satisfy the "works before SDL initialization" requirement. But it still works otherwise. I'm looking at ways to address that.
- N/A
=> Add a basic ShowMessageBox implementation for PSP

src/video/psp/SDL_pspmessagebox.c, src/video/psp/SDL_pspmessagebox.h, src/video/psp/SDL_pspvideo.c
This backports ShowMessageBox support for the Playstation Portable to SDL2. The original PR was #9932.
=> Add a basic ShowMessageBox implementation for PSP (#9932)

src/joystick/SDL_joystick.c
Added VRS DirectForce Pro wheelbase VID/PID to wheel devices list
With this VRS DirectForce Pro Wheel Base can be detected as a wheel in SDL
VID/PID: `0x0483/0xa355`
=> Added VRS DirectForce Pro wheelbase VID/PID to wheel devices list

src/render/metal/SDL_render_metal.m
This patch fixes #9879.
Tested only under macOS sonoma 14.5.
=> Add SDL_PIXELFORMAT_XRGB8888 and SDL_PIXELFORMAT_XBGR8888 to SDL_render_metal.m

src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandkeyboard.c, src/video/wayland/SDL_waylandkeyboard.h, src/video/wayland/SDL_waylandsym.h
Fixes numerous issues regarding dead key behavior on Wayland.
This fixes numerous problems regarding dead keys on Wayland. Most
notably, Wayland was enforcing dead keys on SDL_KEYDOWN and SDL_KEYUP
events, which caused unresponsiveness on keys that were mapped to dead
keys (tilde on US-Intl is most notable for this, commonly used as a
console key).
In addition to this, Wayland was also ignoring SDL_StopTextInput calls,
and proceeded to process dead keys regardless if text input is disabled
or not. This caused issues on console keys where the first keypress
after the console key is merged with the dead key, causing the first key
to appear as à instead of a.
None
=> Fix broken dead key behavior on Wayland

Android.mk, include/build_config/SDL_build_config_android.h, src/core/android/SDL_android.c
Defines such as SDL_SENSOR_DISABLED don't make much difference (about 2k) to the final build. This patch will exclude respective drivers from the build-config to further reduce build size. A total of 177k can be saved, with SDL_LEAN_AND_MEAN that's 542k, which is a considerable saving and results in a much more compact APK for anyone looking to strip out unwanted systems. Fixes #9947
=> Filter Android drivers according to SDL_***_DISABLED macros to help reduce APK size

src/video/wayland/SDL_waylandevents.c, src/video/wayland/SDL_waylandkeyboard.c, src/video/wayland/SDL_waylandkeyboard.h, src/video/wayland/SDL_waylandsym.h
This fixes numerous problems regarding dead keys on Wayland. Most notably, Wayland was enforcing dead keys on SDL_KEYDOWN and SDL_KEYUP events, which caused unresponsiveness on keys that were mapped to dead keys (tilde on US-Intl is most notable for this, commonly used as a console key).
When starting text input, not all state was reset properly. The text input protocol requires to be re-enabled every time text input changes, which SDL did not do. Also, XKB compose state was not reset at all, causing composite and dead keys to carry over from when text input was disabled.
Manual cherry-pick of #9983, as it was easier to manually apply vs trying to untangle the resulting merge mess when cherry-picking forward.
=> wayland: Fix broken dead key behavior

include/SDL3/SDL_video.h
so they link the types in the wiki
I think it would be a good idea to
- either do this change for all the functions before 3.0
- or make the types in the function prototype links.
edit:
- or make all types related pages
=> reword SDL_FlashWindow params

build-scripts/SDL_migration.cocci, build-scripts/rename_api.py, docs/README-migration.md, include/SDL3/SDL_endian.h, include/SDL3/SDL_oldnames.h, src/audio/SDL_mixer.c, src/audio/SDL_wave.c, src/file/SDL_iostream.c, src/joystick/SDL_gamepad.c, src/joystick/SDL_joystick.c, src/joystick/android/SDL_sysjoystick.c, src/joystick/hidapi/SDL_hidapi_ps3.c, src/joystick/hidapi/SDL_hidapi_shield.c, src/joystick/hidapi/SDL_hidapi_xbox360.c, src/joystick/hidapi/SDL_hidapi_xbox360w.c, src/joystick/hidapi/SDL_hidapi_xboxone.c, src/video/windows/SDL_windowswindow.c, test/testevdev.c
This commit was created by running:
```
build-scripts/rename_api.py SDL_endian.h function SDL_SwapLE16 SDL_Swap16LE SDL_SwapLE32 SDL_Swap32LE SDL_SwapBE16 SDL_Swap16BE SDL_SwapBE32 SDL_Swap32BE SDL_SwapLE64 SDL_Swap64LE SDL_SwapBE64 SLD_Swap64BE
```
Fixes #10007
=> Rename SDL_Swap(16|32|64)(LE|BE) to SDL_Swap(LE|BE)(16|32|64)

src/render/SDL_render.c
This PR fixes a broken compilation due to a change in the structure of the renderer commands (there was added a nested structure for color).
=> Fix compilation with enabled render commands logging

src/video/x11/SDL_x11window.c
If XInput2 is enabled, it will grab the pointer on button presses, which results in XGrabPointer returning AlreadyGrabbed. Clear any existing grabs before attempting the confinement grab to avoid a timeout scenario.
Fixes #10014
=> x11: Ungrab before attempting a confinement grab with XInput2 enabled

cmake/3rdparty.cmake, src/video/x11/SDL_x11events.c, src/video/x11/SDL_x11modes.c, src/video/x11/SDL_x11settings.c, src/video/x11/SDL_x11settings.h, src/video/x11/SDL_x11video.c, src/video/x11/SDL_x11video.h, src/video/x11/xsettings-client.c, src/video/x11/xsettings-client.h
On X11, the global content scale factor is currently queried using three mechanisms:
- the settings portal
- the Xft.dpi setting in the Xrm database
- the GDK_SCALE environment variable
According to the GTK documentation, the GDK_SCALE is merely a debugging tool, and GTK does not use the Xrm database for settings, and hasn't been doing so for nearly 15 years.
The way X11 clients receive the windowing scaling factor from the system under GNOME in the X11 session is, typically, through the [XSETTINGS](https://specifications.freedesktop.org/xsettings-spec/xsettings-latest.html) key `Gdk/WindowScalingFactor`, since under X11 it's assumed to be a global value that covers the logical Screen (as opposed to be a per-monitor setting). Sadly, while the XSETTINGS spec has been part of the …
=> Query XSETTINGS on X11 for the global content scale

include/SDL3/SDL_video.h, src/video/windows/SDL_windowsopengl.c, src/video/x11/SDL_x11opengl.c
Using a struct typedef instead of a void pointer results in extra C typechecks.
I only had to cast types in x11 and windows opengl code.
Fixes #10025
=> Use an opaque struct typedef for SDL_GLContext

src/audio/coreaudio/SDL_coreaudio.m
I identified a memory leak in the `SDL_coreaudio.m` file. The leak was caused by the allocation of a CFString object. 
When it is passed to AudioObjectGetPropertyData, it is treated as an UnsafeMutableRawPointer, so memory must be
manually managed. 
Changes include:
- Adding the necessary calls to free allocated memory.
- Ensuring proper handling of audio buffers to prevent memory leaks.
- Additional checks to ensure no memory is leaked during the initialization and de-initialization processes.
https://github.com/libsdl-org/SDL/issues/10026
=> Addressed memory leak in SDL_coreaudio.m

.editorconfig
Remove the excess apostrophe (') introduced by commit c4b471bd1314933fd726ef987d96c92c68033f99.
Some editors complain about it.
=> .editorconfig: Remove excess apostrophe at *.cocci

android-project/app/src/main/java/org/libsdl/app/SDLActivity.java
This changes the code that specify `ActivityInfo.SCREEN_ORIENTATION_FULL_SENSOR` to `ActivityInfo.SCREEN_ORIENTATION_FULL_USER`.
In Android, resizable window implies allowing rotation on any orientation. However it doesn't respect user orientation lock in their status bar and the automatic orientation will always engaged regardless of user orientation lock. This PR changes it so it respect the user orientation lock in their status bar.
* #6090
=> Android: Use SCREEN_ORIENTATION_FULL_USER instead of SCREEN_ORIENTATION_FULL_SENSOR For Resizable Window.

docs/README-documentation-rules.md, docs/README-emscripten.md, docs/README-gdk.md, docs/README-migration.md, docs/README-ps2.md, include/SDL3/SDL_camera.h, include/SDL3/SDL_dialog.h, include/SDL3/SDL_hints.h, include/SDL3/SDL_keycode.h, src/audio/SDL_audiocvt.c, src/camera/mediafoundation/SDL_camera_mediafoundation.c, src/hidapi/linux/hid.c, src/hidapi/netbsd/hid.c, src/joystick/hidapi/steam/controller_structs.h, src/stdlib/SDL_malloc.c, src/video/SDL_video.c, test/testautomation.c
Fixed a bunch of misspelling in various files.
Those are all within comments
=>  JANITORIAL: Fix typos in comments in various files

android-project/app/src/main/java/org/libsdl/app/SDL.java, android-project/app/src/main/java/org/libsdl/app/SDLActivity.java
Add an option to pass the context when loading the native libraries and use it. This avoids the case when context is not yet saved and we fail to use relinker because of the `NullPointerException`.
#10067
=> Fix Android usage of ReLinker

.github/workflows/main.yml, .github/workflows/msvc.yml, test/CMakeLists.txt, test/win32/sdlprocdump.c
Tests on ci are run using this dumper, and will upload the minidumps.
This (currently) only supports win32 Windows, and should hopefully help us with finding the cause for #8576
=> tests: run tests under a minimal debugger that can create minidumps

test/testevdev.c
* testevdev: Add a field for the USB device version
For some devices, such as the Steam Deck's built-in Steam Controller,
the version number reported via evdev and the version number reported
via USB are different. We don't currently use this information anyway,
but in case we want to use it in the future, let's include it in our
test data.
* testevdev: Add test data from Steam Deck built-in devices
Thanks: Robert Beckett
* testevdev: Add the virtual X360 controller created by Steam Input
Thanks: Robert Beckett
=> testevdev: Add test data from Steam Deck built-in devices

test/testevdev.c
=> testevdev: Add missing device ID for Wiimote Classic Controller

test/testmanymouse.c
This is required for supporting multiple keyboards on Windows.
=> testmanymouse: enable raw keyboard events on Windows

test/testevdev.c
* Revert "testevdev.c:  comment out two unused data to fix build."
This reverts commit e4f53e6b214cf476c9ad4b035ead97fb62da81c0.
We'll use these in the next commit.
* testevdev: Associate HID reports for pedals with their other test data
This is how these globals were intended to have been used, similar to
what we already did for the Fanatec device.
Fixes: 3772d6cc "testevdev: Add raw HID report descriptors where available"
=> testevdev: Associate HID reports for pedals with their other test data

src/thread/stdcpp/SDL_systhread.cpp
In the c++thread implementation, the allocated `std::thread` objects were never deleted after joining/detaching.
=> Fix memory leak in stdcpp systhread implementation

src/video/wayland/SDL_waylandevents.c, src/video/x11/SDL_x11events.c
SDL sets `Invalid window` error if `SDL_PumpEvents` is called while the keyboard is not focused.
This PR fixes it by checking if `SDL_GetKeyboardFocus` returns null before calling `SDL_TextInputActive`. I think there may be a better fix but it does the trick for me.
Probably none since this change got pushed only recently?
=> Check if SDL_GetKeyboardFocus is null in X11/Wayland events

src/video/windows/SDL_windowskeyboard.c, src/video/windows/SDL_windowsvideo.h
* Don't need to initialize values already zeroed
* Added debug message logging
* Don't send duplicate SDL_EVENT_TEXT_EDITING events with empty text
* Send the length of selected text in the SDL_EVENT_TEXT_EDITING event
* Fixed potential crashes when out of memory
=> Windows IME cleanup

src/video/SDL_video.c, src/video/wayland/SDL_waylandvideo.c
Fixes a double-free scenario on Wayland, and a memory leak in the video core where display names and driverdata may not be freed if the display is the last, or only, display in the list.
Fixes #10075
=> SDL2: Display double-free and leak fix

src/filesystem/ps2/SDL_sysfilesystem.c
Previously the PS2Dev toolchain was returning an `/` at the end when calling `getcwd` now the toolchain is posix and it is not returning the `/` so, we need to add it.
PD: Now it has the same implementation as the PSP.
Cheers.
=> [SDL3] [PS2] Fix `SDL_GetBasePath`

src/filesystem/ps2/SDL_sysfilesystem.c
Previously the PS2Dev toolchain was returning an `/` at the end when calling `getcwd` now the toolchain is posix and it is not returning the `/` so, we need to add it.
PD: Now it has the same implementation as the PSP.
Cheers.
=> [SDL2] [PS2] Fix `SDL_GetBasePath`

src/timer/ps2/SDL_systimer.c
After solving some issues in the `PS2DEV` toolchain, the `SDL_GetTicks64` was returning value in `usecs` instead of `msecs`.
I don't know with the current approach in SDL3 if that implementation is right. I will double-check it also
=> [PS2] [SDL2] Fix Systimer

src/core/unix/SDL_uri_decode.c, src/core/unix/SDL_uri_decode.h, src/dialog/unix/SDL_portaldialog.c, src/video/wayland/SDL_waylandevents.c, src/video/x11/SDL_x11events.c
Factor out the common URI decode functions from Wayland and X11 into core/unix, and use the functions to decode percent encoded file paths received from the xdg file chooser portal.
The decode functions were reworked slightly to allow separate source and destination buffers to make them easier to use in the file portal case.
Fixes #10119
=> Decode percent encoded paths received from the xdg file chooser portal

docs/README-migration.md, include/SDL3/SDL_vulkan.h, src/dynapi/SDL_dynapi_procs.h, src/render/vulkan/SDL_render_vulkan.c, src/video/SDL_sysvideo.h, src/video/SDL_video.c, src/video/android/SDL_androidvulkan.c, src/video/android/SDL_androidvulkan.h, src/video/cocoa/SDL_cocoavulkan.h, src/video/cocoa/SDL_cocoavulkan.m, src/video/kmsdrm/SDL_kmsdrmvulkan.c, src/video/kmsdrm/SDL_kmsdrmvulkan.h, src/video/offscreen/SDL_offscreenvulkan.c, src/video/offscreen/SDL_offscreenvulkan.h, src/video/uikit/SDL_uikitvulkan.h, src/video/uikit/SDL_uikitvulkan.m, src/video/vivante/SDL_vivantevulkan.c, src/video/vivante/SDL_vivantevulkan.h, src/video/wayland/SDL_waylandvulkan.c, src/video/wayland/SDL_waylandvulkan.h, src/video/windows/SDL_windowsvulkan.c, src/video/windows/SDL_windowsvulkan.h, src/video/x11/SDL_x11vulkan.c, src/video/x11/SDL_x11vulkan.h, test/testffmpeg_vulkan.c, test/testvulkan.c
Fixes #10091.
The necessary sdl2-compat change looks like this:
```diff
--- a/src/sdl2_compat.c
+++ b/src/sdl2_compat.c
@@ -6329,10 +6329,11 @@ SDL_Vulkan_GetInstanceExtensions(SDL_Window *window, unsigned int *puiCount, con
}
/* SDL3 added a VkAllocationCallbacks* argument; SDL2 always uses the default (NULL) allocator */
+/* SDL3 also changed the return type from SDL_bool to int (with usual 0==success, -1==error semantics) */
SDL_DECLSPEC SDL_bool SDLCALL
SDL_Vulkan_CreateSurface(SDL_Window *window, VkInstance vkinst, VkSurfaceKHR *psurf)
{
-    return SDL3_Vulkan_CreateSurface(window, vkinst, NULL, psurf);
+    return (SDL3_Vulkan_CreateSurface(window, vkinst, NULL, psurf) == 0) ? SDL_TRUE : SDL_FALSE;
}
diff --git a/src/sdl3_syms.h b/src/sdl3_syms.h
index e96dff4..a6d54ae 100644
--- …
```
=> vulkan: SDL_Vulkan_CreateSurface now returns the usual int (0=ok, -1=error).

src/render/vulkan/SDL_render_vulkan.c
If window transparency was requested via the SDL_WINDOW_TRANSPARENT flag, don't set the opaque bit on the swapchain composite alpha value. Fixes transparent windows when using the Vulkan renderer (e.g. `testsprite --transparent`).
=> vulkan: Don't set the opaque bit on transparent windows

src/core/linux/SDL_fcitx.c
This PR removes the `usleep(10)` call from `SDL_fcitx.c`. Besides being inconsistent with other similar parts of SDL, this call was causing performance issues.
The additional sleeping code is likely the cause of lag (or for Minetest, a regression). In `SDL_ibus.c`, the respective code never sleeps and works well: (not tested, but nobody complained about this code anyways)
https://github.com/libsdl-org/SDL/blob/0fc3574464326b05568f4804d88cbeb66848f3ea/src/core/linux/SDL_ibus.c#L750-L761
However, `SDL_fcitx.c` does sleep and creates additional lag:
https://github.com/libsdl-org/SDL/blob/0fc3574464326b05568f4804d88cbeb66848f3ea/src/core/linux/SDL_fcitx.c#L479-L490
I did the tests on a virtual machine (QEMU, Arch Linux x86_64) with https://github.com/minetest/minetest/commit/9a1501ae89ffe79c38 …
=> Remove the inconsistent and lag-causing usleep call in SDL_fcitx.c

include/SDL3/SDL_audio.h, src/audio/SDL_audio.c, src/audio/SDL_audiocvt.c, src/audio/SDL_audioqueue.c, src/audio/SDL_audioqueue.h, src/audio/SDL_sysaudio.h, src/audio/alsa/SDL_alsa_audio.c, src/audio/pulseaudio/SDL_pulseaudio.c, src/audio/qnx/SDL_qsa_audio.c, test/loopwave.c, test/testaudiostreamdynamicresample.c, test/testautomation_audio.c, test/testffmpeg.c
This wasn't as hard as I thought, although I suspect we could get some optimization wins out of special-casing some common swizzle operations and datatypes, possibly with some SIMD, but I haven't profiled this yet.
Now you can do things like this, as a simple example, in loopwave:
```diff
diff --git a/test/loopwave.c b/test/loopwave.c
index 9cd24fae9..cb19300c0 100644
--- a/test/loopwave.c
+++ b/test/loopwave.c
@@ -109,6 +109,10 @@ int SDL_AppInit(void **appstate, int argc, char *argv[])
SDL_Log("Using audio driver: %s\n", SDL_GetCurrentAudioDriver());
+    wave.spec.use_channel_map = SDL_TRUE;
+    wave.spec.channel_map[0] = 1;
+    wave.spec.channel_map[1] = 0;
+
stream = SDL_OpenAudioDeviceStream(SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK, &wave.spec, NULL, NULL);
if (!stream) { …
```
=> audio: Add channel remapping to SDL_AudioSpec and SDL_AudioStream.

src/joystick/hidapi/SDL_hidapi_steamdeck.c
Add a loop around SDL_hid_read() in the Steam Deck HIDAPI driver as it is done in other HIDAPI drivers. This loop reads data from the device and processes it until the input buffer is empty which ensures that clients always get the latest data.
This fixes an input latency issue if the application polls the events slower than the hardware generates them.
Fixes #10149
=> SDL2: Drain HIDAPI buffer in SDL_hidapi_steamdeck.c.

src/video/windows/SDL_windowsopengl.c, src/video/x11/SDL_x11opengl.c
This commit fixes the attribute list in the WGL and GLX code when requesting a floating point pixel format. The name of the attribute was missing in the list.
Should be fixed in SDL2 branch also.
Fixes libsdl-org#10189
=> wgl/glx: Fix attribute list for SDL_GL_FLOATBUFFERS

include/SDL3/SDL_pixels.h, src/test/SDL_test_compare.c, src/video/SDL_RLEaccel.c, src/video/SDL_blit.c, src/video/SDL_blit.h, src/video/SDL_blit_A.c, src/video/SDL_blit_N.c, src/video/SDL_pixels.c, test/testautomation_pixels.c
This makes more sense and handles pixel formats with > 8 bits per channel
Fixes https://github.com/libsdl-org/SDL/issues/10168
=> Switch pixel format loss fields to number of bits

src/video/uikit/SDL_uikitmodes.h
It never really worked, as the value was arbitrary, digging apple docs showed the right values.
Swapped arbitrary values for actual apple provided values, tested. Works now.
App window was wrong, showed half content, resizing was wrong.
=> Fix vision os fake screen size

src/SDL_hashtable.c
SDL_HashID does no hashing, which isn't good if the lower bits of the key aren't evenly distributed.
To try and alleviate this, always do a bit of bit-mixing before chosing the bucket.
=> Improve the bucket distribution of SDL_HashTable

src/video/SDL_pixels.c
The SDL_Surface rework in #10201 adds some extra checks that the pixel format enum matches the SDL_PixelFormatDetails struct, which is largely filled in with values from SDL_GetMasksForPixelFormat().
However, there are a few cases where these do not match:
- Indexed 1-, 2-, and 4-bit formats encode a bytes_per_pixel of 0, but SDL_GetMasksForPixelFormat() gives a value of 1.
- Packed formats, like SDL_PIXELFORMAT_XRGB8888 encode a bits_per_pixel of the number of used bits (24), but SDL_GetMasksForPixelFormat() includes the padding byte, giving a total of 32.
We could change the encoding of these in the enum, or change what we store in the details struct to match, but I suspect we'd either break something that relies on it, or lose some (_maybe_ useful?) information. In the meantime, this …
=> Remove incorrect asserts from SDL_InitPixelFormatDetails()

src/video/emscripten/SDL_emscriptenevents.c
SDL consumes key down/up events regardless of the user have enabled or disabled them, which causes text input html elements not to work whenever there is an SDL canvas on screen. This patch initializes `prevent_default` to first check if `SDL_KEYDOWN` or `SDL_KEYUP` events are enabled or not (depending on the emscripten event being emitted).
The downside for this is that the user might have `SDL_KEYDOWN` and `SDL_KEYUP` disabled, but have `SDL_TEXTINPUT` enabled. We can add an extra check for `SDL_TEXTINPUT`, but I think that this is a bad configuration anyways.
Closes https://github.com/libsdl-org/SDL/issues/7681
=> SDL2 emscripten: don't consume key down/up events if the user disabled them

CMakeLists.txt
projects are expected to use CMAKE_MSVC_RUNTIME_LIBRARY to select the runtime library.
With current CMake versions, this can be done with:
-DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_MSVC_RUNTIME_LIBRARY=xxx
with xxx one of:
"MultiThreaded"         -> -MT (static non-debug)
"MultiThreadedDLL"      -> -MD (shared non-debug)
"MultiThreadeDebug"     -> -MTd (static debug)
"MultiThreadedDebugDLL" -> -MDd (shared debug)
See CMake documentation for more information:
https://cmake.org/cmake/help/latest/policy/CMP0091.html
https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html
Closes https://github.com/libsdl-org/SDL_mixer/issues/621
=> cmake: remove SDL_STATIC_VCRT option

src/hidapi/libusb/hid.c
These warnings popped up in `src/hidapi/libusb/hid.c` on MSVC.
The libusb functions accept an int where we are trying to pass a size_t.
=> hidapi: fix 'conversion from 'size_t' to 'int', possible loss of data' of libusb functions

src/video/uikit/SDL_uikitmetalview.m, src/video/uikit/SDL_uikitwindow.m
Set Fixed Scale Factor for VisionOS in SDL Metal View Creation
Implemented a fixed scale factor of 2.0 for VisionOS devices
Added explanatory comment for the VisionOS-specific handling
This change addresses the lack of nativeScale concept in VisionOS
Aims to achieve better pixel density on VisionOS devices
No specific issue linked. Addresses the need for proper scaling on VisionOS devices in SDL.
=> Set Fixed Scale Factor for VisionOS

test/CMakeLists.txt, test/testspritesurface.c
This is a cut-down version of testsprite which uses SDL_Surface (and SDL_GetWindowSurface), instead of the Render API. It's useful for quickly validating that blitting works, including some basic format conversion (as ``icon.bmp`` has a palette).
Both testsprite and testspriteminimal use the Render API, so this can also serve as a simple translation guide from one to the other.
(This is not written against the SDL_Surface revamp in #10201, but could be updated to test it, too.)
=> test: Add testspritesurface

docs/README-migration.md, src/video/SDL_bmp.c, src/video/SDL_pixels.c, src/video/SDL_surface.c, test/testautomation_surface.c
Currently, all SDL_Surfaces with an indexed pixel format have an associated SDL_Palette. This palette either consists of entirely the colour black, or -- in the special case of 1-bit surfaces, black and white.
When an indexed surface is blitted to another indexed surface, a 'map' is generated from the source surface's palette to the destination surfaces palette, in order to preserve the look of the image if the palettes differ.
However, in most cases, applications will want to blit the raw index values, rather than translate to make the colours as similar as possible. For instance, the destination surface's palette may have been modified to fade the screen out.
This change allows an indexed surface to have no associated palette. If either the source or destination surface of a blit do not …
=> Support indexed surfaces without palettes (thanks @sulix!)

docs/README-migration.md, src/core/haiku/SDL_BeApp.cc
Use SDL_GetBaseDir() to find this directory instead.
Reference Issue #8403.
Fixes #7596.
=> haiku: No more chdir to executable's directory at startup in SDL3.

src/video/SDL_pixels.c
Fix Mutex Unlock in SDL_GetPixelFormatDetails: without unlocking, we trigger an assertion failure in SDL_sysmutex.c at line 80 (i.e. 'rc == 0'). Each lock-unlock pair should ideally cancel each other out, maintaining a reference count that returns to zero.
Added missing SDL_UnlockMutex call before returning from SDL_GetPixelFormatDetails to ensure the mutex is properly released, preventing assertion failures in SDL_sysmutex.c at line 80 due to unbalanced mutex lock-unlock operations.
N/A - This change addresses assertion failures and a potential defect where mutexes could remain locked under certain conditions, leading to resource leaks and stability issues.
Platform details:
MacBook Pro: 2021 M1 
Xcode: Version 15.4 (15F31d)
macOS: 14.5 (23F79)
Libraries: SDL3 …
=> Unlocking mutex in success case too

src/thread/pthread/SDL_syscond.c, src/thread/pthread/SDL_syssem.c
Fixes https://github.com/libsdl-org/SDL/issues/8576#issuecomment-2227124926
=> pthread: timespec.tv_nsec must be less then 1000000000 ns

src/thread/pthread/SDL_syscond.c, src/thread/pthread/SDL_syssem.c
=> [SDL2] pthread: timespec.tv_nsec must be less then 1000000000 ns

include/SDL3/SDL_audio.h
This makes it easier to understand in the debugger, and is consistent with SDL_PixelFormat and SDL_Colorspace
=> Change SDL_AudioFormat into an enum

sdl2-config.in
/bin/sh of Solaris does not understand $()
Fixes https://github.com/libsdl-org/SDL/issues/10092
=> sdl2-config.in: use backtics instead of $() for older shells

src/core/linux/SDL_ibus.h
`ibus-1.0.pc` adds `/usr/include/ibus-1.0` to the search path but not `/usr/include`, which makes the canonical include path `<ibus.h>` (you can confirm this by running `pkg-config ibus-1.0 --cflags` or by looking at https://github.com/ibus/ibus/blob/main/ibus-1.0.pc.in). Correcting the include path improves SDL's compatibility with third-party build scripts and build systems without requiring such ports to modify the SDL source code itself.
=> Correct ibus include path

cmake/macros.cmake, cmake/sdltargets.cmake
Fixes some typos in the cmake directory, including one that impacted a debug message.
=> Fix typos in cmake

include/SDL3/SDL_timer.h, src/timer/SDL_timer.c, src/timer/SDL_timer_c.h, src/timer/haiku/SDL_systimer.c, src/timer/n3ds/SDL_systimer.c, src/timer/ngage/SDL_systimer.cpp, src/timer/ps2/SDL_systimer.c, src/timer/psp/SDL_systimer.c, src/timer/unix/SDL_systimer.c, src/timer/vita/SDL_systimer.c, src/timer/windows/SDL_systimer.c, test/testtimer.c
This provides a highly accurate sleep function for your application, although you are still subject to being switched out occasionally.
Fixes https://github.com/libsdl-org/SDL/issues/10210
=> SDL_DelayNS() will attempt to sleep exactly the requested amount of time

docs/README-migration.md, include/SDL3/SDL_video.h, src/dynapi/SDL_dynapi_procs.h, src/test/SDL_test_common.c, src/video/SDL_video.c
Fixes https://github.com/libsdl-org/SDL/issues/10286
=> SDL_GetWindowOpacity() directly returns the opacity instead of using an out parameter.

include/SDL_hints.h, src/video/wayland/SDL_waylandopengles.c, src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
This makes the Wayland backend honor the **SDL_VIDEO_DOUBLE_BUFFER** environment variable.
This does the same as in the KMS/DRM backend: if we want low latency, we must wait immediately after issuing a pageflip.
Since waiting wastes CPU, this is disabled by default (user must export `SDL_VIDEO_DOUBLE_BUFFER = 1`) but it's a very good feature to have for precise gaming, and for emulation of old systems where immediate response is needed for proper gameplay.
To easily notice the difference this provides, enable the system cursor (which is updated on it's own plane with no lag at all) and a software cursor at the same time, and move them both to see how the software cursor lags behind way less with `SDL_VIDEO_DOUBLE_BUFFER = 0`.
I do this on Scummvm, but any program that sets a software …
=> Add SDL_VIDEO_DOUBLE_BUFFER support to the Wayland backend.

src/video/kmsdrm/SDL_kmsdrmopengles.c, src/video/kmsdrm/SDL_kmsdrmvideo.c
At some point, the KMS/DRM backend double buffering feature stopped working in SDL2 because someone removed **SDL_KMSDRM_DOUBLE_BUFFER** environment variable (in favor of  **SDL_VIDEO_DOUBLE_BUFFER** I guess?) but didn't wire up the environment variable evaluation code in the KMS/DRM backend code.
This core simply fixes that so double buffering works again on the KMS/DRM backend.
=> Fix KMSDRM double buffering.

src/video/emscripten/SDL_emscriptenevents.c
This restores the behaviour before 92215481146f9225a458e9a09abb85a33b52d9ff where we only preventDefault the event if:
- the key is recognised
- the event is enabled
- the event is not filtered
(ignoring the KEYPRESS special case, which is unchanged)
I don't currently have the environment set up to test this, but it's restoring the old behaviour which was well tested at the time...
=> emscripten: restore key event prevent default behaviour

src/video/wayland/SDL_waylandwindow.c, src/video/wayland/SDL_waylandwindow.h
Always use the size sent by the compositor when transitioning back to the floating state on the xdg-toplevel path, unless the client explicitly requested a new floating size while the window was in a fixed-size state.
If a window is requested to be maximized or made fullscreen while an uncommitted size request is pending, the surface will first be committed so that the compositor will set the new size when the window is restored.
Fixes the window being wrongly resized when leaving the maximized state in KDE.
Fixes #10203
=> wayland: Use the compositor provided size during state transitions

include/SDL3/SDL_joystick.h
This PR removes a duplicate definition in `SDL_joystick.h` which already exists in `SDL_guid.h`.
=> Remove a duplicate definition in SDL_joystick.h

include/SDL3/SDL_rect.h, src/video/SDL_rect.c, src/video/SDL_rect_impl.h, test/testautomation_rect.c
* A floating point rectangle contains all points >= x and <= x + w
* A floating point rectangle is only empty if it has negative width. The zero rectangle contains the zero point.
* Adjacent floating point rectangles intersect along their shared side
Fixes https://github.com/libsdl-org/SDL/issues/6791
=> Fixed floating point rectangles to be mathematically correct.

include/SDL3/SDL_surface.h, src/video/SDL_blit.c, src/video/SDL_blit_slow.c, src/video/SDL_stretch.c, src/video/SDL_surface.c, src/video/SDL_surface_c.h
Now that we have surface internal data, we can store it there. This slightly improves performance in the surface blitting paths.
=> Removed SDL_PROP_SURFACE_COLORSPACE_NUMBER

src/video/cocoa/SDL_cocoawindow.m
Into `src/video/cocoa/SDL_cocoawindow.m`
- Support Copy in addition to Generic as Drag and Drop operation,
- Register and Support `public.utf8-plain-text` for `SDL_EVENT_DROP_TEXT`. 
This is the equivalent of `text/plain;charset=utf-8` for macOS.
Main target : Provide TEXT Drag and Drop `SDL_EVENT_DROP_TEXT` to macOS ( Cocoa )
- Add `kUTTypeUTF8PlainText` or `public.utf8-plain-text` into `RegisterForDraggedTypes` on the `NSWindow`
- Add `NSPasteboardTypeString` or `public.utf8-plain-text` into `AvailableTypesFromArray` on the `NSPasteboard`,
- Handle `NSPasteboardTypeString` as `NSString`, split it by lines like the `text/plain;charset=utf-8` Drags and Drops, submit each line to `SDL_SendDropText`.
Secondary target : Support Drag and Drop Copy in addition to Drag and Drop Generic
- in …
=> Support Drag and Drop SDL_EVENT_DROP_TEXT in Cocoa

src/video/SDL_RLEaccel.c, src/video/SDL_blit.c, src/video/SDL_blit.h, src/video/SDL_blit_0.c, src/video/SDL_blit_1.c, src/video/SDL_blit_A.c, src/video/SDL_blit_N.c, src/video/SDL_pixels.c, src/video/SDL_pixels_c.h, src/video/SDL_surface.c, src/video/SDL_surface_c.h, test/testautomation_surface.c
We don't actually need to change the blit mapping if we're targeting a new surface with the same format and palette.
=> Don't recalculate the blit mapping when changing surfaces

include/SDL3/SDL_stdinc.h
=> stdinc: c23 deprecated _Static_assert in favor of static_assert

src/video/SDL_rect.c, src/video/SDL_rect_impl.h, test/testautomation_rect.c
We're limiting the functions to rects with positions and sizes < 1 billion for speed, which is totally fine for most SDL use cases. If you need rectangles larger than that, you can roll your own functions that use 64-bit intermediate values and do proper overflow handling of output values.
Fixes https://github.com/libsdl-org/SDL/issues/8879
=> Prevent potential overflow in rectangle functions

include/SDL3/SDL_video.h
Fixed a typo in the function name in the documentation for SDL_EGL_GetProcAddress
=> Fixed a typo in the function name in the documentation for SDL_EGL_GetProcAddress in SDL_video.h

include/SDL3/SDL_video.h, src/video/SDL_video.c
Also use the real pointer to display modes for internal mode processing
Fixes https://github.com/libsdl-org/SDL/issues/10353
=> Functions that return display modes return temporary memory.

VisualC-GDK/SDL/SDL.vcxproj, VisualC-GDK/tests/testgdk/src/testgdk.cpp, src/core/SDL_core_unsupported.c, src/core/gdk/SDL_gdk.cpp, src/core/gdk/SDL_gdk.h, src/filesystem/gdk/SDL_sysfilesystem.cpp, src/main/gdk/SDL_sysmain_runapp.cpp, src/video/windows/SDL_windowsevents.c, src/video/windows/SDL_windowsvideo.c, src/video/windows/SDL_windowsvideo.h
A fresh round to update GDK builds to the latest version.
- adjusts for recent API changes
- moves setup code for app change notification to SDL_gdk.cpp since the data (handles) now live there
- conditionally disables some more types&calls not available on Xbox
- fixes DXGI cleanup code
=> Fix VisualC-GDK build

src/video/SDL_video.c
`SDL_GetWindowFullscreenModeInternal` returns non-null even when the window is not in fullscreen, if full screen display mode is previously set through `SDL_SetWindowFullscreenMode`.
This PR fixes it by checking window flag before calling `SDL_GetWindowFullscreenModeInternal`.
=> Check window fullscreen flag in SDL_GetWindowSizeInPixels

include/SDL3/SDL_gamepad.h
In the documentation for the SDL_GetGamepadGUIDForID method in the SDL_gamepad.h file, there are two references to the methods SDL_GetGamepadGUID and SDL_GetGamepadGUIDString, but there are no methods of its own. I replaced these two methods with the existing SDL_GUIDToString.
=> Fix documentation references and update method usage for SDL_GetGamepadGUIDForID in SDL_gamepad.h

include/SDL3/SDL_touch.h
The Finger framework documentation referred to a non-existent GetTouchFinger method
=> Fixed a typo in the link to the GetTouchFingers function

src/video/wayland/SDL_waylandmouse.c
Doing this can leave the cursor data in a weird, corrupt state.
Fixes #10395
=> wayland: Don't fail to retrieve a system cursor if no window is focused

src/dynapi/gendynapi.py
It replaces `SDL_DECLSPEC_FREE` to ` _FREE` first, so removing `SDL_DECLSPEC_FREE` after that has no effect.
This PR fixes it by changing the order of replacing.
=> Remove SDL_DECLSPEC_FREE before SDL_DECLSPEC in gendynapi

include/SDL3/SDL_test_common.h, test/loopwave.c, test/testaudiorecording.c, test/testcamera.c, test/testevdev.c, test/testfile.c, test/testplatform.c, test/testqsort.c, test/testrwlock.c, test/testsensor.c, test/teststreaming.c, test/testthread.c, test/testyuv.c, test/torturethread.c
Also fixes the memory leak reported in https://github.com/libsdl-org/SDL/pull/10396#issuecomment-2254518947
=> Make sure we call SDL_Quit() before SDLTest_CommonDestroyState()

src/stdlib/SDL_mslibc.c
[SDL3] SDL_mslibc.c: revert PR/10303 changes
This reverts parts of PR/#10303 applied to SDL_mslibc.c functions.
We should keep them as `()` because their signatures are already wrong
and they work only because they are marked with `naked` attributes.
To be cherry-picked to 2.30.x after merge.
(CC: @akk0rd87)
=> [SDL2] SDL_mslibc.c: revert PR/10303 changes

src/stdlib/SDL_mslibc.c
This reverts parts of PR/#10303 applied to SDL_mslibc.c functions.
We should keep them as `()` because their signatures are already wrong
and they work only because they are marked with `naked` attributes.
(CC: @akk0rd87)
=> [SDL3] SDL_mslibc.c: revert PR/10303 changes

src/audio/aaudio/SDL_aaudio.c, src/audio/aaudio/SDL_aaudio.h, src/audio/openslES/SDL_openslES.c, src/audio/openslES/SDL_openslES.h
The AAudio driver implemented pause/resume by dangerously locking the audio devices. If there was an audio hotplug event or a background thread tried to interact with the audio system, this could cause deadlocks.
=> Pause and resume Android audio without taking device locks

include/SDL_hints.h, src/file/cocoa/SDL_rwopsbundlesupport.m
This is the SDL2 branch solution. In SDL3, this behavior is removed by #10420, but here for backwards compatibility, this offers a hint to turn off the usual behavior.
Fixes #8403.
=> SDL_RWFromFile: On Apple platforms, offer a hint to not look in resource dirs.

src/joystick/SDL_joystick.c
This prevents continuing a rumble after the first one fails, and fixes a long standing crash issue if rumble is started immediately before the controller is disconnected.
Thanks to @AntTheAlchemist for the key bug report that showed what was happening here.
Fixes https://github.com/libsdl-org/SDL/issues/10422
=> Fixed crash with joystick rumble after disconnection

examples/template.html
Fixes the description display for HTML examples.
I did it how I thought it was meant to display as, but I can modify it if necessary.
Re https://github.com/libsdl-org/SDL/issues/10350#issuecomment-2258841751
=> Fix examples description CSS

src/core/android/SDL_android.c
This patch fixes two issues with pausing and resuming the Android activity when an external graphics context[^1] is used:
1. When pausing, don't wait for the EGL context to be backed up if a context wasn't created in the first place.
2. When resuming, don't recreate the EGL surface unless one was requested by the user when originally creating the window.
[^1]: SDL_PROP_WINDOW_CREATE_EXTERNAL_GRAPHICS_CONTEXT_BOOLEAN
=> android: Fix activity pause/resume with external graphics context

src/test/SDL_test_memory.c, src/video/windows/SDL_windowsevents.c
We want to keep mouse timestamps consistently using the same interval, and it's helpful to know when multiple keyboard events come in at the same time.
=> Don't mix keyboard and mouse raw input timestamps

src/render/direct3d12/SDL_render_d3d12.c, src/render/direct3d12/SDL_render_d3d12_xbox.h, src/render/direct3d12/SDL_shaders_d3d12.c, src/video/directx/SDL_d3d12.h
SDL_Render had enough of this going on to make this easy to write! The `COBJMACROS` change will come later since it pretty much sweeps through the entire render file, we'll do this while porting GPU to Xbox.
=> d3d12: Move platform-specific includes/defines to SDL_d3d12.h

src/video/windows/SDL_windowsvideo.c, src/video/windows/SDL_windowsvideo.h, src/video/windows/SDL_windowswindow.c, src/video/windows/SDL_windowswindow.h
Remove `WM_DROPFILES` ( supports only `SDL_EVENT_DROP_FILE` ), use `IDropTarget` instead ( provides `SDL_EVENT_DROP_POSITION`, `SDL_EVENT_DROP_FILE` and `SDL_EVENT_DROP_TEXT` ).
- In `src/video/windows/SDL_windowsevents.c`, remove `WM_DROPFILES`
- In `src/video/windows/SDL_windowswindow.c + .h`,
Create `IDropTarget` and issue `SDL_SendDropPosition`,
Handle `text/uri-list` for `SDL_SendDropFile`, `text/plain;charset=utf-8` and `CF_UNICODE_TEXT` and `CF_TEXT` for `SDL_SendDropText`, `CF_HDROP` for `SDL_SendDropFile`.
- The `IDropTarget` Drop OLE object requires a full `OleInitialize` in `WIN_AcceptDragAndDrop`, as `CoInitialize(Ex)` are not enough and cause a Memory Management Overflow error. Whereas `CoInitialize(Ex)` have a centralized support in SDL, `OleInitialize` has not. What is the …
=> Support SDL_EVENT_DROP_FILE and SDL_EVENT_DROP_TEXT in Windows

android-project/app/build.gradle, android-project/app/proguard-rules.pro, build-scripts/build-release.py, build-scripts/create-android-project.py, build-scripts/pkg-support/android/INSTALL.md.in, docs/README-android.md
Document creating a gradle project using Android aar archives, and remove aar generation support from the gradle files.
The android archive also includes a `INSTALL.md` text file documenting how to use the archive.
You can download an example SDL3 android archive here:
https://github.com/madebr/SDL/actions/runs/10201751044
Closes #5717
=> Document Android Archive and remove library creation support from Gradle project

android-project/app/src/main/java/org/libsdl/app/SDLActivity.java, src/core/android/SDL_android.c
Moves the initialisation code from `nativeRunMain()` to separate methods to allow a better way to customised the SDL_main entry point for non-native applications (eg. C#).
`createSDLMainRunnable()` has been removed in favour of just a regular `main()` method.
- Fixes https://github.com/libsdl-org/SDL/issues/9652
=> Remove `createSDLMainRunnable()` in favour of `main()` to fix multiple issues when providing custom main/runnable code

.github/actions/setup-gdk-desktop/action.yml, .github/workflows/create-test-plan.py, .github/workflows/generic.yml, .gitignore, build-scripts/setup-gdk-desktop.py
The new `build-scripts/setup-gdk-desktop.py` script downloads and extracts a GDK release from [microsoft/GDK](https://github.com/microsoft/GDK).
Then, it copies MSBuild files from a Visual Studio installation such that the `Gaming.Desktop.x64` platform gets working.
If finally creates a `Directory.Build.props` file in `VisualC-GDK`, with properties that are automatically read by MSBuild.
Closes #8847
=> ci: add GDK job

src/core/android/SDL_android.c
https://github.com/libsdl-org/SDL/blob/e3cf20e1cc5645646f7216733e97b4c7660d2df8/android-project/app/src/main/java/org/libsdl/app/SDLActivity.java#L1042-L1043
It's `nativeInitMainThread`/`nativeCleanupMainThread` in Java part, but `nativeInitSDLThread`/`nativeCleanupSDLThread` in C.
This PR fixes the name discrepancy between these two.
Here is a crash log:
```
08-05 20:10:24.694 20307 20307 W sh.ppy.osulazer: CheckJNI: method to register "nativeInitSDLThread" not in the given class. This is slow, consider changing your RegisterNatives calls.
08-05 20:10:24.695 20307 20307 E sh.ppy.osulazer: Failed to register native method org.libsdl.app.SDLActivity.nativeInitSDLThread()V in /data/app/~~ui-_rds_eyAnV7UtSGX8PQ==/sh.ppy.osulazer-soF48SUniHmqmHAgvAGNdw==/base.apk
```
=> Fix name discrepancy in Android JNI

src/video/x11/SDL_x11events.c
The `SDL_EVENT_DROP_TEXT` event is limited to the MIME target `text/plain`.
This adds, in `src/video/x11/SDL_x11events.c`,
- the MIME text target `text/plain;charset=utf-8`,
- the generic text targets `UTF8_STRING` and `TEXT` provided by the Web browsers, by `GTK+`.
=> Add MIME targets to SDL_EVENT_DROP_TEXT in X11

test/testautomation_clipboard.c
Fixes several cases of potentially accessing null pointer in testautomation_clipboard.c. The NULL result may be returned by `SDL_GetClipboardData`.
Found this is possible while experimenting with #8385, apparently clipboard requires certain subsystems to be present, so if prerequisites are not initialized then `SDL_GetClipboardData` fails.
=> Fix potential access violation in testautomation_clipboard.c

src/cpuinfo/SDL_cpuinfo.c
This is https://github.com/libsdl-org/SDL/pull/8325 cleaned up to compile with the latest SDL2 branch.
=> add failsafe for querying cache line size on linux

include/SDL3/SDL_test_harness.h, src/test/SDL_test_harness.c, test/testautomation.c
Run tests in non-linear order (see #9303)
It mixes the testSuites array, and for each suite, it mixes the sub-tests.
Hence, it changes the public API behavior of SDLTest_RunSuites(). not sure if this is acceptable ?
=>  Run tests in non-linear order (see #9303)

src/render/SDL_render.c
Add internal SDL_UpdateTextureFromSurface().
Since, SDL_CreateTextureFromSurface() is a big function, this makes it more readable.
Currently this only splits and lets the function internal.
Also: maybe we want a future SDL_Create**Streaming**TextureFromSurface() or other variants for creating textures.
So maybe something like: SDL_CreateTextureWithPropertiesFromSurface() ? 
so I guess, this would be a first step to prepare this.
in SDL_UpdateTextureFromSurface():
- it can resolve the ColorKey if needed. (was there)
- update texture alpha modulation and turn off/on blending if needed (was there)
- maybe some stuff from colorspace (was there)
- could handle streaming/static texture (not)
=> Add internal SDL_UpdateTextureFromSurface()

src/events/SDL_windowevents.c, src/video/SDL_video.c
Fixes https://github.com/libsdl-org/SDL/issues/10494
=> Fixed crash when the current mouse capture window is destroyed

include/SDL3/SDL_hints.h, src/events/SDL_mouse.c, src/events/SDL_mouse_c.h, src/video/SDL_video.c
Require more than one warp to the window center within a certain timespan (currently 30ms, but can be tweaked) to better avoid erroneously entering warp emulation mode.
This also correctly resets the warp emulation mode activation if the window loses and regains focus.
Closes #10413
=> Use more stringent criteria for entering warp emulation mode

src/joystick/SDL_joystick.c
Add Cammus C12 in the SDL wheel list to enable wheel detection for them.
With this Cammus C12 Wheel Base can be detected as a wheel in SDL
VID/PID: `0x3416, 0x0302`
=> Add Cammus C12 VID & PID to wheel device list.

src/video/x11/xsettings-client.c
If there is only 1 element in the list or memory allocation fails on the 2nd iteration then new->next is uninitialised. Any operation on the list will follow this uninitialised pointer.
@ebassi  I don't know where you get this version of xsettings.c from, could you propagate this fix upstream?
None.  This function is not used in SDL.
=> Fix xsettings list copy

src/SDL_hints.c
Return immediately if allocation fails to avoid use after free of `entry`, null pointer dereference of `hint` and calling the user callback.
None
=> Fix error handling of SDL_AddHintCallback
